### ISSUE TITLE
yay -Ss connection reset error

### ISSUE THREAD

**Issue by aclifton314** [Jguer/yay#1001]
#### Affected Version

yay v9.2.1 - libalpm v11.0.3

#### Issue
I installed yay on my manjaro vm (see details below) and am getting an error during AUR search. I am behind a proxy and have done the following:

- set the `http_proxy https_proxy HTTP_PROXY HTTPS_PROXY` variables in my `.bashrc`
- uncommented `Defaults env_keep += "http_proxy https_proxy no_proxy HTTP_PROXY HTTPS_PROXY` in `sudoers`
- uncommented `XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u` in `pacman.conf`
- entered my proxy information into `/etc/wgetrc` and uncommented `use_proxy = on`

System Info
`DISTRIB_ID=ManjaroLinux`
`DISTRIB_RELEASE=18.0.4`
`DISTRIB_CODENAME=Illyria`
`DISTRIB_DESCRIPTION="Manjaro Linux"`

#### Output

`$ yay -Ss spotify`
`Error during AUR search: Get https://aur.archlinux.org/rpc.php?arg=spotify&type=search&v=5: proxyconnect tcp: read tcp vm.ip.address->proxy.ip.address: read: connection reset by peer
Showing Repo packages only`

`$ yay -Pg`
`{`
	`"aururl": "https://aur.archlinux.org",`
	`"buildDir": "/home/aclifton/.cache/yay",`
	`"editor": "nano",`
	`"editorflags": "",`
	`"makepkgbin": "makepkg",`
	`"makepkgconf": "",`
	`"pacmanbin": "pacman",`
	`"pacmanconf": "/etc/pacman.conf",`
	`"tarbin": "bsdtar",`
	`"redownload": "no",`
	`"rebuild": "no",`
	`"answerclean": "",`
	`"answerdiff": "",`
	`"answeredit": "",`
	`"answerupgrade": "",`
	`"gitbin": "git",`
	`"gpgbin": "gpg",`
	`"gpgflags": "",`
	`"mflags": "",`
	`"sortby": "votes",`
	`"gitflags": "",`
	`"removemake": "ask",`
	`"requestsplitn": 150,`
	`"sortmode": 0,`
	`"completionrefreshtime": 7,`
	`"sudoloop": false,`
	`"timeupdate": false,`
	`"devel": false,`
	`"cleanAfter": false,`
	`"gitclone": true,`
	`"provides": true,`
	`"pgpfetch": true,`
	`"upgrademenu": true,`
	`"cleanmenu": true,`
	`"diffmenu": true,`
	`"editmenu": false,`
	`"combinedupgrade": false,`
	`"useask": false`
`}`

Any pointers would be much appreciated. Thank you!

**Comment by Jguer** [comment]
Go uses `http_proxy` and `https_proxy` as env variables but not a lot of formats are supported, if you still face this issue I'll need to know the format.

Refer to #429, #701 and #795   for some pointers
