### ISSUE TITLE
Ambiguous wording of missing packages warning

### ISSUE THREAD

**Issue by jshap70** [Jguer/yay#1002]
#### Affected Version

n/a 

#### Issue
The wording of the warning that a package was not found should indicate that the package does not exist _anywhere_ not merely in the AUR. This is because a user could have had a package installed from an official repo and not from the AUR, but if the package is removed `yay` always frames the message like it was removed from the AUR. 

Message originates from: 
https://github.com/Jguer/yay/blob/c9f7105481ebdfdd81f5c022469a76576536a273/print.go#L23

Ideas for message: 
`Missing Packages:`
or to be more explicit that their system is potentially in a very bad state:
`WARNING - Missing Packages: `

#### Steps to reproduce

1. Have a package installed from `[community]`, like `gtk-xfce-engine` yesterday 
1. Have the TU's remove that package from the repos so it no longer exists in any repos nor in the AUR
1. `yay` will be unable to find the package and report it as a missing AUR package.

**Comment by Jguer** [comment]
How about ` Packages not found in AUR:`?

**Comment by jshap70** [comment]
I don't understand your edit, but the different suggestion sounds fine. my issue is just that the current wording implies that they were originally AUR packages when they weren't necessarily.

**Comment by Jguer** [comment]
Didn't make it so clear, that warning is produced by yay after it has searched the AUR, so it's really that they're missing from the AUR. But yes, this will be changed for easier comprehension

**Comment by mskiptr** [comment]
Implementing something like https://github.com/Jguer/yay/issues/512 would allow to query whether a package was installed from AUR.

Also similar in implementation https://github.com/Jguer/yay/issues/1145

**Comment by mskiptr** [comment]
I don't think this is resolved.

I may try to implement it in the future. Should this issue stay closed or open until then?

**Comment by mskiptr** [comment]
.
