### ISSUE TITLE
Environment variables, export ... gets ignored

### ISSUE THREAD

**Issue by LinuxUserGD** [Jguer/yay#1004]
#### Affected Version
yay v9.2.1.r13.gc9f7105 - libalpm v11.0.3
#### Issue
How can I use environment variables with yay when compiling AUR packages?
Example: https://aur.archlinux.org/packages/blender-2.7/
This only works with makepkg and not with ỳay, it gets ignored (still installs cuda) or says "invalid package DISABLE_CUDA=1"

#### Steps to reproduce

1. export DISABLE_CUDA=1 before build
2. DISABLE_CUDA=1 ~your-aur-helper~
3. makepkg DISABLE_CUDA=1

**Comment by LinuxUserGD** [comment]
Editing PKGBUILD also doesn't work

**Comment by Jguer** [comment]
`env DISABLE_CUDA=1 yay -S blender-2.7` does pull cuda as a makedep.

`blender-2.7` [.SRCINFO](https://aur.archlinux.org/cgit/aur.git/tree/.SRCINFO?h=blender-2.7) mentions cuda as a makedep so any AUR helper that parses `.SRCINFO` will trip on that.
yay uses [RPC](https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=blender-2.7) to handle makedeps , which the package also includes cuda in. 

Adding/Removing makedeps on runtime through the `PKGBUILD` is not supported by yay (arguable if it's best practice from what I've seen), but it is not an issue of Environment Variables, just something that is not implemented.

**Comment by bartoszek** [comment]
Sorry, but I'm not going to adjust `PKGBUILD` for every AUR helper out there. If `yay` diverge form pristine `makepkg` in case of deps handling there's not much I can do :disappointed:
You could always try `aurutils` with -T swich, which just starts `makechrootpkg` and so is immune to this problem.

**Comment by bartoszek** [comment]
@LinuxUserGD Use `yay --mflags "DISABLE_CUDA=1"` to pass configuration variable to the `PKBUILD`

**Comment by LinuxUserGD** [comment]
@bartoszek 
I tried this:
```
[user @ archlinux blender-2.7] $ yay --mflags "DISABLE_CUDA = 1"
[user @ archlinux blender-2.7] $ yay -S blender-2.7 --noconfirm
:: Checking for conflicts ...
:: Checking for inner conflicts ...
[Repo Make: 7] gcc8-libs-8.3.0-2 gcc8-8.3.0-2 opencl-nvidia-430.40-2 eglexternalplatform-1.0 + 3 + g7c8f8e2-1 egl-wayland-1.1.3-1 nvidia-utils -430.40-2 cuda-10.1.243-1
[Aur: 1] blender-2.7-2.79b.r71421.e045fe53f1b-2

  1 blender-2.7 (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N] one [A] ll [location] [I] nstalled [No] tInstalled or (1 2 3, 1-3, ^ 4)
==>
:: PKGBUILD up to date, skipping (1/1): blender-2.7
  1 blender-2.7 (Installed) (Build Files Exist)
==> Diffs to show?
==> [N] one [A] ll [location] [I] nstalled [No] tInstalled or (1 2 3, 1-3, ^ 4)
==>
:: Parsing SRCINFO (1/1): blender-2.7
[sudo] Password for user:
Solve dependencies on ...
Search conflicting packages ...
Warning: dependency cycle detected:
Warning: egl-wayland will be installed before its dependency eglexternalplatform

Packages (7) cuda-10.1.243-1 egl-wayland-1.1.3-1
           eglexternalplatform-1.0 + 3 + g7c8f8e2-1 gcc8-8.3.0-2
           gcc8-libs-8.3.0-2 nvidia-utils-430.40-2 opencl-nvidia-430.40-2

Total size of installed packages: 4546.15 MiB

:: continue installation? [J / n]
(7/7) Check keys in keyring [######################] 100%
(7/7) Check package integrity [######################] 100%
(7/7) Loading package files [######################] 100%
(7/7) Check for file conflicts [######################] 100%
(7/7) Check available hard disk space [######################] 100%
Error: Partition / is crowded: 1178362 blocks are needed, 106641 blocks are free
Error: Not enough free hard disk space
Error: Could not complete the operation (Not enough free disk space)
Errors have occurred, no packages have been updated.
Error installing repo packages
[user @ archlinux blender-2.7] $
```
Using `makepkg -si` in the `blender-2.7` works but when I run `ỳay -Syu --devel --timeupdate` it always says that there is a newer commit without being a new release.

**Comment by bartoszek** [comment]
I've to dive into `yay --devel` logic to answer the last question. But I've fixed the pesky `cuda` always getting yield by `yay` with `aur-rpc`. Now it's back to good old times, when user has to manually install deps to indicate which feature to build.

**Comment by LinuxUserGD** [comment]
Now it works for `blender-2.7` with `yay -Syu --noconfirm --aur --devel --timeupdate --rebuild --mflags "DISABLE_CUDA=1"` :+1:

Only `blender-2.8-git` still installs `cuda`.

Would be better if `yay` could support environment variables (e. g. `mem_limit`) without having to manually adjust the `PKGBUILD`by the maintainer (@bartoszek ) in the future as https://github.com/Jguer/yay/pull/1008 didn't get merged.

**Comment by bartoszek** [comment]
> Only `blender-2.8-git` still installs `cuda`.

I've ported changes from `blener-2.7` to `blender-2.8-git`, they should have congruent behavior now.

For the `_mem_limit`, We are back at the same issue - We cant decide if a package can be safely omitted from dependencies without calling `makepkg --sync`. So it's up to the user to decide how to handle this use case with `yay`, or to invoke `makepkg` directly and let `PKGBUILD` to decide.
