### ISSUE TITLE
[Feature Request] Add warning if SUID files are present

### ISSUE THREAD

**Issue by iyanmv** [Jguer/yay#1005]
It would be nice if this helper shows a warning if SUID files are detected. This is implemented, for example, in [rua](https://github.com/vn971/rua) (Secure AUR helper).

**Comment by Jguer** [comment]
Leaving example implementation [here](https://github.com/vn971/rua/blob/b5bc2af0887abe7679cd5ee757a2fd6d388d3e4d/src/tar_check.rs#L64) for when there's will to pick this up.

**Comment by Morganamilo** [comment]
Should we also add a warning for any systemd services that run as root? What about any sudoers.d drop ins? Polkit drop ins? Kernel modules? SSH keys?

The solution is to read the pkgbuild, not rely on a helper to give you a false sense of security.

**Comment by iyanmv** [comment]
@Morganamilo Yes, I agree that reading the PKGBUILD is the solution if security is a concern, but let's be honest, most people using helpers don't read in detail the PKGBUILDs. So maybe adding some security warning may persuade people to read in detail the PKGBUILD.

I give the example that made me write this feature request. Two very popular PKGBUILDs in AUR, [skypeforlinux-stable-bin](https://aur.archlinux.org/packages/skypeforlinux-stable-bin/) and [skypeforlinux-preview-bin](https://aur.archlinux.org/packages/skypeforlinux-preview-bin) had a SUID file for days, and probably most users didn't even notice they were using a binary compiled program by Microsoft with root permission.

**Comment by AladW** [comment]
> most people using helpers don't read in detail the PKGBUILDs

Even if such is the case, that's entirely their own fault. Nobody should support users who deliberately choose the ignore the "use at your own risk" warning on the AUR website.

Similarly, helpers like `rua` are not more or less "secure" since they won't take away the necessity to read the PKGBUILD.
