### ISSUE TITLE
Add gcc, make and fakeroot as dependencies to PKGBUILD

### ISSUE THREAD

**Issue by bencelaszlo** [Jguer/yay#1007]
#### Affected Version
yay 9.2.1

#### Issue
The currently recommended method in the README.md file is immanently C-normative, and the following dependency packages are missing from the `PKGBUILD`: `gcc`, `make`, and `fakeroot`. These packages are not necessaries for a working Arch Linux install.

#### Steps to reproduce
1. Install Arch Linux without bloat, so you don't have `gcc`, `make`, nor `fakeroot`
1. `git clone https://aur.archlinux.org/yay.git`
2. `cd yay`
3. `makepkg -si`

#### Output
```
exec: "gcc": executable file not found in $PATH
make: *** [Makefile:51: build] Error 2
```

**Comment by Jguer** [comment]
But `base-devel` is assumed for AUR operation and those packages are included in it.
https://wiki.archlinux.org/index.php/Arch_User_Repository#Getting_started
