### ISSUE TITLE
'yay -R <package>' is canceled with Ctrl + c => entry is still removed from ~/.cache/yay/vcs.json

### ISSUE THREAD

**Issue by attila123** [Jguer/yay#1011]
#### Affected Version
yay v9.2.1 - libalpm v11.0.3

#### Issue
Regarding -R I think it has a problem: if you cancel package removal with Ctrl + c, e.g.:
```
$ yay -R git-cola-git
[sudo] password for avangel: 
checking dependencies...

Packages (1) git-cola-git-v3.4.53.gf912364a-1

Total Removed Size:  3,15 MiB

:: Do you want to remove these packages? [Y/n] ^C
Interrupt signal received
```
then the entry for the package is deleted (too soon) from ~/.cache/yay/vcs.json.

**Comment by Morganamilo** [comment]
I assume the fix is to just swap the order yay does these things. Could be easy for you to try fixing yourself.
