### ISSUE TITLE
Yay shows way to many packages

### ISSUE THREAD

**Issue by Raymo111** [Jguer/yay#1015]
#### Affected Version
yay v9.2.1 - libalpm v11.0.3

#### Issue
How do I get yay to show less packages when I just do yay <package>? Also how do I get it to show in reverse order? (1 at bottom)

1. `yay g++`

#### Output
![image](https://user-images.githubusercontent.com/34818275/64189743-e2d0aa00-ce42-11e9-9d2e-e8d0e49246ae.png)

**Comment by Jguer** [comment]
`yay -Y g++ --bottomup --save` should make it permanently show 1 first. How to narrow down on `g++` I can't help with unfortunately

**Comment by Morganamilo** [comment]
`pacman -Ss <foo>` matches regex. That's what there's so many results. Pacman has no option to do a literal search and yay can't do regex. Fun.

**Comment by HollMax** [comment]
I use a solution similar to the one mentioned on [Arch wiki](https://wiki.archlinux.org/index.php/Fzf).
Simply replace pacman with yay and you're good to go. I also use skim instead of fzf...
