### ISSUE TITLE
Yay -Syu --devel not being updated working on some computers in my network

### ISSUE THREAD

**Issue by Baitinq** [Jguer/yay#1016]
#### Affected Version
yay v9.2.1 - libalpm v11.0.3
#### Issue
For some reason only on one of my 3 computers connected to my network updates from devel packages (-git) are being found. On the other two when i perform `yay -Syu --devel` it outputs that no updates were found.

Would you know the reason to my problem?

Thanks a lot and sorry for the short description of my issue as I dont really know how to explain this weird behaviour.

**Comment by Jguer** [comment]
Did you `yay -Y --gendb` when you moved to yay? You may need to generate that db if you know you have devel packages but `~/.cache/yay/vcs.json` is empty.  After that, once upstream is again updated you'll get updates

**Comment by Baitinq** [comment]
Yes, i did execute that command. The `~/.cache/yay/vcs.json` is not empty.

**Comment by Jguer** [comment]
Can I check the contents of said `vcs.json`? A good solution for stuck devel packages has been `yay -S --rebuild <your-devel-packages>`, they will be rebuilt according to the last source available and they should be correctly tracked after

**Comment by Baitinq** [comment]
My vcs.json
`{
	"anime-downloader-git": {
		"github.com/vn-ki/anime-downloader.git": {
			"protocols": [
				"https"
			],
			"branch": "HEAD",
			"sha": "d7756a8fccdc6ab1bf40500147af50f4c00d40b5"
		}
	},
	"dmenu-baitinq-git": {
		"github.com/Baitinq/dmenu.git": {
			"protocols": [
				"git"
			],
			"branch": "HEAD",
			"sha": "4935902378d321c465f5f8ec18619b22da75527b"
		}
	},
	"dwm-baitinq-git": {
		"github.com/Baitinq/dwm.git": {
			"protocols": [
				"git"
			],
			"branch": "HEAD",
			"sha": "2b69d13fbd411fb9cca50988073874a9f45140b3"
		}
	},
	"genkernel-next-git": {
		"github.com/Sabayon/genkernel-next.git": {
			"protocols": [
				"git"
			],
			"branch": "HEAD",
			"sha": "7b20b78268327b33bc9fe06c8603e8a2300fe090"
		}
	},
	"geolocate-git": {
		"github.com/Baitinq/geolocate": {
			"protocols": [
				"git"
			],
			"branch": "HEAD",
			"sha": "3ef45aa979beb4bfad32755b05ba1b301ad2ab49"
		}
	},
	"i3-battery-popup-git": {
		"github.com/rjekker/i3-battery-popup.git": {
			"protocols": [
				"https"
			],
			"branch": "master",
			"sha": "d894a102a1ff95019fc59d0a19c89687d502cd1a"
		}
	},
	"imlib2-webp-git": {
		"github.com/gawen947/imlib2-webp.git": {
			"protocols": [
				"https"
			],
			"branch": "HEAD",
			"sha": "52ca890669f700c36ecd9088af35e65fb0d45d8c"
		}
	},
	"jrnl-git": {
		"github.com/maebert/jrnl.git": {
			"protocols": [
				"https"
			],
			"branch": "HEAD",
			"sha": "2767567dc1144a2cc41d3ff651a3d28d07258ba8"
		}
	},
	"opendoas-git": {
		"github.com/Duncaen/OpenDoas.git": {
			"protocols": [
				"https"
			],
			"branch": "HEAD",
			"sha": "9a9495d672fb426010a6b52d637c30a0dbeb619f"
		}
	},
	"python-todo-t": {
		"github.com/kovetskiy/t.git": {
			"protocols": [
				"git"
			],
			"branch": "HEAD",
			"sha": "259867e9339dee662f5a5005f58b0c7503d99608"
		}
	},
	"python-ueberzug-git": {
		"github.com/seebye/ueberzug.git": {
			"protocols": [
				"https"
			],
			"branch": "master",
			"sha": "a8ac9c345c59625a5bc838a4dbc2f14047bf7161"
		}
	},
	"siji-git": {
		"github.com/stark/siji": {
			"protocols": [
				"https"
			],
			"branch": "HEAD",
			"sha": "c691f200c1c66e76daa2afc9cbbd1aa39045c906"
		}
	},
	"smart-wallpaper-git": {
		"github.com/Baitinq/smart-wallpaper.git": {
			"protocols": [
				"git"
			],
			"branch": "HEAD",
			"sha": "6fd818151aeb63164493f33a7ae87ff19f10ea94"
		}
	},
	"st-luke-git": {
		"github.com/LukeSmithxyz/st.git": {
			"protocols": [
				"https"
			],
			"branch": "HEAD",
			"sha": "4a9b405ab00c478683de4dc3316a2fd7772393a5"
		}
	},
	"surf-baitinq-git": {
		"github.com/Baitinq/surf.git": {
			"protocols": [
				"git"
			],
			"branch": "HEAD",
			"sha": "73311af365535bb6ea439591012ecff41a683e00"
		}
	},
	"trackless-git": {
		"github.com/Baitinq/trackless.git": {
			"protocols": [
				"git"
			],
			"branch": "HEAD",
			"sha": "657d359048077744dd35b1dde8d5c94b850ac269"
		}
	},
	"ucm_plbossart-git": {
		"github.com/plbossart/UCM.git": {
			"protocols": [
				"https"
			],
			"branch": "HEAD",
			"sha": "7eaea9902a70a8878fb33fd37237ea71c199ddb0"
		}
	},
	"xf86-input-cmt-setup": {
		"github.com/joebonrichie/xf86-input-cmt-conf.git": {
			"protocols": [
				"https"
			],
			"branch": "HEAD",
			"sha": "ab34935c1976b716cf0d4ff72a2956904afa6a3d"
		}
	},
	"xwinwrap-git": {
		"github.com/ujjwal96/xwinwrap": {
			"protocols": [
				"https"
			],
			"branch": "master",
			"sha": "ec32e9b72539de7e1553a4f70345166107b431f7"
		}
	}
}`

**Comment by Baitinq** [comment]
Ive tried rebuilding the packages and they are still not being tracked.

**Comment by Jguer** [comment]
what is your expected output? 
I have checked two packages in that vcs.json against their SHA upstream
```
git ls-remote https://github.com/LukeSmithxyz/st.git | grep 4a9b405ab00c478683de4dc3316a2fd7772393a5
```
```
git ls-remote https://github.com/vn-ki/anime-downloader.git | grep d7756a8fccdc6ab1bf40500147af50f4c00d40b5
```

And they are a match, meaning yay won't try and update these, what was your expected output?

https://github.com/Jguer/yay/issues/508 <- could potentially help

**Comment by Baitinq** [comment]
As an example the smart-wallpaper-git package should be updated, as there has been a new commit, but it is not.

**Comment by Jguer** [comment]
That's true, SHA doesn't match, can I ask you something experimental and not guaranteed to work, changing
```
	"smart-wallpaper-git": {
		"github.com/Baitinq/smart-wallpaper.git": {
			"protocols": [
				"git"
			],
			"branch": "HEAD",
			"sha": "6fd818151aeb63164493f33a7ae87ff19f10ea94"
		}
	},
```

to 

```
	"smart-wallpaper-git": {
		"github.com/Baitinq/smart-wallpaper.git": {
			"protocols": [
				"https"
			],
			"branch": "HEAD",
			"sha": "6fd818151aeb63164493f33a7ae87ff19f10ea94"
		}
	},
```

and if it doesn't work to
```
	"smart-wallpaper-git": {
		"github.com/Baitinq/smart-wallpaper.git": {
			"protocols": [
				"git"
			],
			"branch": "HEAD",
			"sha": "00000000000000000"
		}
	},
```

**Comment by Baitinq** [comment]
Neither of them work

**Comment by Jguer** [comment]
Ok, once I'm on a dev machine I'll test with `aur/smart-wallpaper-git` and your `vcs.json` to test where's the issue

**Comment by Baitinq** [comment]
Thanks a lot

**Comment by Baitinq** [comment]
@Jguer I should add that when you activate a VPN the packages do get updated.

**Comment by Jguer** [comment]
I could not reproduce this meanwhile, had a theory of trying to block the dns request to see if it would fail silently now. I'm guessing it's network related and the problem with yay here is it not warning you of what's actually wrong

**Comment by protist** [comment]
I had similar issues with `yay -Syu --devel` not working on some systems. Is there a fool-proof way to reset the database? I tried removing `~/.cache/yay/vcs.json` then `yay -Y --gendb`, but this didn't seem to work. Is the only way to `yay -S --rebuild <your-devel-packages>`, explicitly listing all packages?

**Comment by protist** [comment]
In the meantime, I'm just ignoring `--devel` and manually reinstalling all using yay's [naming logic](https://github.com/Jguer/yay/blob/80741791129994b0dde46e86fc9f4f62f2dbcc8d/upgrade.go#L3010), i.e.

    yay -S $(pacman -Qq | grep -E -- '-(git|svn|hg|bzr|nightly)$') 

There are certainly some packages being missed by `--devel`.
