### ISSUE TITLE
My package breaks when installed through yay

### ISSUE THREAD

**Issue by rhysperry111** [Jguer/yay#1019]
#### Affected Version
yay v9.2.1 - libalpm v11.0.3

#### Issue
I don't know what yay does differently, but when I install my package (fathom-git) manually by cloning with git and running 'makepkg -si' it installs correctly and when run, fathom doesn't throw any errors. But when I install it through yay, fathom shows errors when running.

What exactly does yay do other than clone and run makepkg?

#### Steps to reproduce
1. yay -S fathom-git
2. installs correctly
3. fathom throws error when run

**Comment by Morganamilo** [comment]
>fathom shows errors when running.

Which are?

**Comment by rhysperry111** [comment]
FATA[0000] Missing database migrations

**Comment by Morganamilo** [comment]
I have no idea how fathom works but it seems to rely on data in `src/`. If you build the package then delete `src/` you can reproduce this.
