### ISSUE TITLE
Option for a single automated clean build retry on PKGBUILD related failure?

### ISSUE THREAD

**Issue by mxmilkb** [Jguer/yay#1023]
System update just failed thusly;
```
...
==> Making package: udiskie-dmenu-git 9.451ec99-2 (Fri 13 Sep 2019 12:04:58 BST)
...
==> Starting pkgver()...
==> ERROR: pkgver is not allowed to contain colons, forward slashes, hyphens or whitespace.
==> ERROR: pkgver() generated an invalid version: 21.0.3.0-5-g37
...
```

I check the AUR entry, but apparently a fix was pushed last month. I retry with a clean build `y` and the build completes.

Possibly an option to perform a repull for the PKGBUILD on such a failure?

**Comment by Morganamilo** [comment]
Blame the packager for not adding an epoch when downgrading the pkgver: https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=udiskie-dmenu-git&id=e7f6a3d33e26f2a374f1a08af5f9c0bc2bb45abf

You could just use `--redownloadall` to prevent the issue from happening. Adding the option you want seems very very specific and not too useful.

**Comment by mxmilkb** [comment]
That's fair enough, I can look at scripting something, it's for automated updates on a headless box, trying to reduce points in the process where manual intervention is required.
