### ISSUE TITLE
-G/--getpkgbuild fails to download repo/ABS packages

### ISSUE THREAD

**Issue by AndydeCleyre** [Jguer/yay#1027]
#### Affected Versions
At least:
- `yay v9.2.1 - libalpm v11.0.3`
- `yay v9.2.1.r16.g1901138 - libalpm v11.0.3`
- `libarchive 3.4.0-2`

#### Issue

```bash
yay -G pacman
```

```
:: Querying AUR...
==> Failed to get pkgbuild: pacman: bsdtar: Error opening archive: Unrecognized archive format
```

It looks like it may not be querying the official repos at all, but I'm not sure. Same results for all official packages I've tried, but continues to work fine for the AUR.

```json
{
    "answerclean": "None",
    "answerdiff": "All",
    "buildDir": "/home/andy/Code/yaytmp/",
    "combinedupgrade": true,
    "makepkgbin": "/usr/bin/makepkg",
    "pacmanbin": "/usr/bin/pacman",
    "removemake": "yes",
    "tarbin": "/usr/bin/bsdtar"
}
```

**Comment by Jguer** [comment]
I will merge and release c1341a5 to fix this issue temporarily. `yay -G` is broken on release anyway, and this should only affect that part.
A better implementation will be done in the `yay-next` branch but some feedback on how it is right now is good as well
