### ISSUE TITLE
command-not-found hook and yay

### ISSUE THREAD

**Issue by tycho01** [Jguer/yay#1028]
Some other distros like Ubuntu use a `command-not-found` hook, enabling [suggestions](https://superuser.com/questions/787424/hook-into-command-not-found-handler-in-ubuntu) of installable packages:
```
wim@SDFA100461C:~$ thing
No command 'thing' found, did you mean:
 Command 'tping' from package 'lam-runtime' (universe)
 Command 'thin' from package 'thin' (universe)
thing: command not found
```

To go even further, [`thefuck`](https://github.com/nvbn/thefuck) has been used to 'correct' the last command and accept the suggestion to install for both `apt-get` and NixOS.

For Arch, I've found this Pacman-based [`find-the-command`](https://github.com/agura-lex/find-the-command) that aims to achieve something similar, which appears dead and (for me) dysfunctional.
So I was wondering: is there a working `yay` equivalent to this? Would a pacman/yay distinction there even hold any relevance?

**Comment by Morganamilo** [comment]
thefuck seems to support yay https://github.com/nvbn/thefuck/commit/201c01fc74d479d9e418d32c92a88b50b27728a7.

**Comment by tycho01** [comment]
awesome -- thanks!! :)
