### ISSUE TITLE
Question: How can I install packages without having to confirm?

### ISSUE THREAD

**Issue by Zeioth** [Jguer/yay#1033]
#### Issue
When you run

    yay packagename

You are prompted 4 times:

* To select the right package (OK)
* To cleanbuild
* To see the diff
* To ask you if you REALLY want to install it.

### My question is
There is some way to auto confirm all questions? (except the first one maybe). In yaourt [there was a way to do it](http://kissmyarch.blogspot.com/2012/05/two-simple-yaourt-tips.html).

Because I have to install 25 AUR packages quite often and I don't want to respond 100 questions every time. Thank you.

**Comment by StephenBrown2** [comment]
I would highly recommend reading the man page with `man yay`, as all the answers to your questions can be found there.

`yay packagename` will do a search and give you a list of matching packages. To avoid the first prompt if you know the exact package name, use `-S`, like `yay -S packagename`.

To avoid the second and third prompts, you can set the config options to give defaults and never prompt. See the current config with `yay -Yg` (https://github.com/Jguer/yay/blob/master/doc/yay.8#L105)

You can set answers with `yay --save --answerX`: https://github.com/Jguer/yay/blob/master/doc/yay.8#L225-L246
for example: `yay --save --answerclean All --answerdiff All`

and set the menu display options similarly: https://github.com/Jguer/yay/blob/master/doc/yay.8#L265-L311
for example: `yay --save --nocleanmenu --nodiffmenu`

I'll leave the rest an an exercise to the reader. Remember, `man` is your friend!

**Comment by Zeioth** [comment]
That answer my question, thank you!

**Comment by parkerlreed** [comment]
So close out the issue :P

**Comment by OriLiMu** [comment]
After some search on google, I found that the last question cant not be auto confirmed. 
![image](https://user-images.githubusercontent.com/11295355/150915435-fb683f3f-e54e-4fcb-a151-37ec9e021f5b.png)

You can check the answer here.

https://github.com/Jguer/yay/issues/713

**Comment by jose1711** [comment]
This seems to work for me for both repo and AUR packages:
```
echo y | LANG=C yay --noprovides --answerdiff None --answerclean None --mflags "--noconfirm" $PKGNAME
```

**Comment by ronylee11** [comment]
> This seems to work for me for both repo and AUR packages:
> 
> ```
> echo y | LANG=C yay --noprovides --answerdiff None --answerclean None --mflags "--noconfirm" $PKGNAME
> ```

Thank you so much!! Been looking for one-line solution for a long time
But i seem to have issues on installing make dependencies with echo y, currently it only works when i have all the make dependencies installed, it just skips the entire stage of grabbing make dependencies
Here's currently how i use it
```
LANG=C yay --noprovides --answerdiff None --answerclean None --mflags "--noconfirm" -S $(cat program-list)
```
where program-list is a list of programs i wanted, ( for my install script )
it is good enough to have loads of programs all installed in one go, but do u have any idea how to not skip confirming make dependencies? the (y/N) stage

**Comment by Offpics** [comment]
`yes | yay` works for me

**Comment by scipioni** [comment]
yes | LANG=C yay

**Comment by cherrynoize** [comment]
> I would highly recommend reading the man page with `man yay`, as all the answers to your questions can be found there.

Well, actually the `--noconfirm` option does not seem to appear anywhere in there.
