### ISSUE TITLE
croc fails to build

### ISSUE THREAD

**Issue by dax-dev** [Jguer/yay#1036]
#### Affected Version

yay v9.3.1.r3.g5b3ae06 - libalpm v11.0.3

#### Issue

'croc' fails to build on yay:
https://aur.archlinux.org/packages/croc/

it looks like the GOPATH export in 'prepare()' doesn't persist through the 'build()' step.

It works fine through 'makepkg', and it works if you edit the PKGBUILD to export the GOPATH in the 'build()' step.

**Comment by Jguer** [comment]
https://github.com/Jguer/yay/issues/1006

Should explain all there is to know on this topic. If you have any follow-up question, I'll be happy to try and answer.
