### ISSUE TITLE
yay cannot update to yay 9.3.1 from 9.2.1

### ISSUE THREAD

**Issue by chrisco23** [Jguer/yay#1037]
#### Affected Version
yay v9.2.1 - libalpm v11.0.3

#### Issue
Cannot build yay using 'yay'.  Please advise.

#### Steps to reproduce

1. type "yay"

#### Output
```
go build -v -gcflags=all=-trimpath=~/.cache/yay/yay/src/yay-9.3.1 -asmflags=all=-trimpath=~/.cache/yay/yay/src/yay-9.3.1 -ldflags=-extldflags=-zrelro -ldflags=-extldflags=-znow -ldflags '-s -w -X main.version=9.3.1' -o yay -mod=vendor
build io: cannot load io: open ~/.cache/yay/yay/src/yay-9.3.1/vendor/io: no such file or directory
make: *** [Makefile:51: build] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
Error making: yay
```

**Comment by Jguer** [comment]
Went back to v9.2.1, typed `yay`, no dice. Update worked.

- go/gcc-go version? (`go version`)

(as well, `yay-git` has a new make method which will probably work better`)

**Comment by chrisco23** [comment]
Thanks for the quick reply.

go version go1.13 linux/amd64

Are you recommending then that I uninstall yay and install yay-git?

btw, maybe I should have mentioned, I'm on a fully-updated Arch system.

**Comment by chrisco23** [comment]
I tried cloning the git repo and building, with the same failure about "cannot load io".

**Comment by chrisco23** [comment]
I have solved the problem (which was on my end), although knowing zero about go, I still don't understand exactly what the changes I made really accomplished.

At some point a long while back, for reasons I can't at all remember, I found myself putting these lines into my .bashrc.  Removing them solved the build.

```
export GOROOT=$HOME/go
export PATH=$PATH:$GOROOT/bin
export GOPATH=$HOME/gocode
export PATH=$PATH:$GOPATH/bin
```

Sorry for false alarm.
