### ISSUE TITLE
[Feature] support github link.

### ISSUE THREAD

**Issue by bartoszek** [Jguer/yay#1038]
Would be nice to have an option to clone and build PKGBUILD from `github`.
```sh
yay --giturl="https://github.com/bartoszek/AUR-optix.git"
```
This would allow user to have access to PKGBUILD hosted on github/gitlab etc. And allow devs to post patches on github and point users of _definitely most popular AUR helper_ , to single command to install them. :thinking:

**Comment by Jguer** [comment]
I was answering #1040 but what I wrote there really applies here as well as the technical challenges are the same.

About the concept itself: 

`PKGBUILD hosted on github/gitlab etc. And allow devs to post patches on github`, but why not just publish it on the AUR, isn't that what the AUR is for? I'm curious about the usecase where creating an AUR package is not an option.

`to single command to install them.` Isn't that what AUR helpers which use the AUR are for?

Also, wouldn't this contribute to fragmentation of the community?

**Comment by bartoszek** [comment]
You've misunderstood - What I meant was a solution to a specific issue when a dependency of my package is broken (and it could stay that way for a prolong time). I'm usually posting a working `PKGBUILD` to github and report patch to maintainer also putting pin on my package with a link to working `PKGBUILD@github`.
It would be nice to just post a comment with `yay --github $$url$$` as most users tent to have trouble with building packages with bare `makepkg` call... :thinking:

**Comment by AladW** [comment]
The main challenge is here due to the monolothic design - if you want to not use the AUR (and with that, a different workflow than what yay originally had in mind), you need to add extra flags and features to make it work. 

The alternative is what `git` does, i.e. split the workflow into high-level ("porcelain") and low-level ("plumbing") commands.
