### ISSUE TITLE
[Question] Install and update local packages

### ISSUE THREAD

**Issue by Baitinq** [Jguer/yay#1040]
Is it possible to have a local PKGBUILD that is not in the AUR (and you dont want it to be) but still be tracked and updated by yay?

Thanks a lot.

**Comment by Jguer** [comment]
Kinda duplicate of https://github.com/Jguer/yay/issues/934

It's related to this: 
https://github.com/Jguer/yay#yay-doesnt-install-dependencies-added-to-a-pkgbuild-during-installation

And the gist of it is:
`yay uses the AUR RPC for dependency resolution and not PKGBUILD parsing therefore AUR dependencies won't be computed from edited PKGBUILDs (or custom made and unpublished)`

So when it comes to installing, that's a cross. 

When it comes to updating, it would require extensive modifications (and tracking hashes like we do for devel packages) but PKGBUILD parsing isn't used for deps and `yay` would just complain that it couldn't find package info in the `AUR RPC`.

Right now I'm focusing just on keeping maintainability up, reorganizing and documenting  the code base and making the code more testable so we can implement features/enhancements without fear of breaking things in prod so you won't be seeing this feature any time soon.

**Comment by AladW** [comment]
What's "tracked and updated" in this context? Any packages are "tracked" by pacman, regardless of the AUR helper you use.
