### ISSUE TITLE
Packages installed as dependencies are marked as explicitly installed

### ISSUE THREAD

**Issue by lottspot** [Jguer/yay#1042]
#### Affected Version

```
$ yay -V
yay v9.3.1 - libalpm v11.0.3
```

#### Issue

When dependencies are installed for an AUR package from the Arch repository, their install reason is marked as "Explicitly Installed". Since these packages are actually installed as dependencies, it would be expected that their install reason is marked as "Installed as a dependency for another package" (the equivalent of installing using `pacman -S --asdeps`). Not sure whether this also affects dependencies installed from the AUR or not.

#### Steps to reproduce

1. Install any AUR package which requires dependencies from Arch repositories

#### Output

```
$ yay -S toggldesktop
:: There are 4 providers available for toggldesktop:
:: Repository AUR
    1) toggldesktop 2) toggldesktop-beta-bin 3) toggldesktop-bin 4) toggldesktop-dev-bin 

Enter a number (default=1): 1
:: Checking for conflicts...
:: Checking for inner conflicts...
[Repo: 6]  qt5-declarative-5.13.1-1  qt5-webchannel-5.13.1-1  qt5-location-5.13.1-1  qt5-webengine-5.13.1-3  poco-1.9.4-1  jsoncpp-1.9.1-1
[Repo Make: 2]  rhash-1.3.8-1  cmake-3.15.3-2
[Aur: 1]  toggldesktop-7.4.1020-1
# ... installation continues to completion ...
$ pacman -Qi jsoncpp
Name            : jsoncpp
Version         : 1.9.1-1
Description     : C++ library for interacting with JSON
Architecture    : x86_64
URL             : https://github.com/open-source-parsers/jsoncpp
Licenses        : MIT  custom:Public_Domain
Groups          : None
Provides        : libjsoncpp.so=21-64
Depends On      : gcc-libs
Optional Deps   : jsoncpp-doc: documentation
Required By     : toggldesktop
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 1666.00 KiB
Packager        : Levente Polyak <anthraxx@archlinux.org>
Build Date      : Fri 13 Sep 2019 02:16:07 PM EDT
Install Date    : Fri 04 Oct 2019 12:48:52 PM EDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by Jguer** [comment]
I found this issue in the `yay-next` branch but thought it could only be from the refactoring as #778 which touched the install system has been resting in `yay-git` for 3 months without any complaint.

This was preventable which really annoys me. I'll be reverting #778 until it's properly diagnosed, testing it automatically and manually and releasing a patched version
