### ISSUE TITLE
Question: Update features aka yaourt

### ISSUE THREAD

**Issue by waldauf** [Jguer/yay#1051]
Till now I'm using `yaourt` for system update/upgrade. I like it features like:
  * It shows me colored updated/upgraded packages.
  * It enables display description for all packages.
  * Asks me for manually choice of packages which I want to install.

Example:
```
$ yaourt -Syua
==> Package upgrade only (new release):
core/coreutils                         8.31-1                     1 -> 2
core/diffutils                         3.7-1                      1 -> 2
core/file                              5.37-2                     2 -> 3
core/grep                              3.3-1                      1 -> 2

==> Software upgrade (new version) :
core/archlinux-keyring                 20190827-1                 -> 20191007-1
core/filesystem                        2019.05-2                  -> 2019.10-1
core/linux                             5.3.4.arch1-1              -> 5.3.5.arch1-1
core/linux-headers                     5.3.4.arch1-1              -> 5.3.5.arch1-1


==> Continue upgrade ? [Y/n]
==> [V]iew package detail   [M]anually select packages
==> --------------------------------------------------

```
If I use `yay` I see this. But without color (which I have enabled in `/etc/pacman.conf`).
```
yay -Syu               
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
warning: terraform: ignoring package upgrade (0.12.9-1 => 0.12.10-1)
resolving dependencies...
looking for conflicting packages...

Package (46)                            Old Version                 New Version                 Net Change  Download Size

community/acpi_call                     1.1.0-251                   1.1.0-252                     0.00 MiB       0.01 MiB
core/archlinux-keyring                  20190827-1                  20191007-1                    0.19 MiB       0.80 MiB
extra/at-spi2-atk                       2.34.0-1                    2.34.1-1                      0.00 MiB       0.05 MiB
~
~

Total Download Size:    363.29 MiB
Total Installed Size:  1216.56 MiB
Net Upgrade Size:         0.78 MiB

:: Proceed with installation? [Y/n]
```

Many thx for help!

**Comment by Jguer** [comment]
> It shows me colored updated/upgraded packages.
Color in `/etc/pacman.conf` does that.
Yay also uses `test` to see if your terminal supports colors therefore `whereis test` is a good way to know if it's being overwritten by something else

> It enables display description for all packages.
?

> Asks me for manually choice of packages which I want to install.
`yay -Syu --combinedupgrade --save` makes it permanently have that behaviour (then you can just use `yay` or `yay -Syu`

**Comment by Jguer** [comment]
`[V]iew package detail` was never implemented in yay, so that would be a feature request

**Comment by waldauf** [comment]
For me (and I hope for many other admins) it will be useful feature. Do I create new feature request or will be used this thread?

**Comment by Jguer** [comment]
Let's create a new feature request just so I don't lose track of this, otherwise I'll forget this feature request exists.
Yes, this can be done by opening a side terminal and `yay -Qi <pkg>` but this seems if well done can be a life improvement with minimal effort.
