### ISSUE TITLE
[Question] Figuring out yay's 'provider' menu

### ISSUE THREAD

**Issue by elek95eel** [Jguer/yay#1057]
#### Affected Version

yay v9.3.3 - libalpm v11.0.3

#### Issue (but not really)
From my understanding of how the --provides switch works (if the package is from AUR, then the providers are assumed to be in the AUR only, but if it's a repo package then the providers are only queried from the repo) , is there a way or config option to somehow append the providers that are already in pacman's usual repos for packages that are in the AUR? (sorry if my explanation is wrong or misleading)

#### Example
```
$ yay -S mingw-w64-wine           
:: There are 11 providers available for wine:
:: Repository AUR
    1) wine-git 2) wine-ivb 3) wine-stable 4) wine-staging-fallout4-git 5) wine-staging-git 6) wine-staging-pba 7) wine-staging-pba-git 8) wine-unity3d-git 9) wine-valve 10) wine-valve-git 11) wine-vulkan-git 

Enter a number (default=1): 
```
but there are no providers listed already from the repos.

**Comment by Morganamilo** [comment]
You're probably forgot to enable multilib.

**Comment by elek95eel** [comment]
Thank you, that was the problem. Huge oversight on my part forgetting how Wine actually works on Linux.

**Comment by elek95eel** [comment]
Thank you, that was the problem. Huge oversight on my part forgetting how Wine actually works on Linux.
