### ISSUE TITLE
[Feature] preserve coherency.

### ISSUE THREAD

**Issue by bartoszek** [Jguer/yay#1058]
It would be great if `yay -Su` cross-reference upgraded Arch packages with dependencies of installed AUR packages and trigger rebuild of the overlapping set.
Concept proof:
```sh
# alias `yay -Su`
mapfile new < <(pacman -Su --print-format '%n';yay -Quq)
mapfile foreign < <(pacman -Qmq)
mapfile update < <(expac "%n\t%E" ${foreign[@]}|eval grep "$(printf -- " -e \" %s \"" ${new[@]})"|cut -f1|grep -v $(printf -- " -e %s" ${new[@]}))
yay -Su
yay --rebuild ${update[@]}
```

**Comment by bartoszek** [comment]
More robust solution would involve `link-level dependency detection` congruent to `namcap -i -r sodepends` to allow unlisted dependencies to trigger rebuild as well.

**Comment by AladW** [comment]
Some related discussion here: https://github.com/AladW/aurutils/issues/612
