### ISSUE TITLE
[FEATURE] Display packages description before update

### ISSUE THREAD

**Issue by waldauf** [Jguer/yay#1059]
In yaourt during system update `yaourt -Syu` I'm asked if I want to `[V]iew package detail`. If I type `v` description will be shown for every package. 
For me it's important feature because I'm trying to check all packages which are updated/installed. And I think it's useful feature for all Arch admins.

```
$ yaourt -Syu 
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
  marp : Orphan 
 Foreign packages: | 60 / 60

==> Software upgrade (new version) :
extra/yakuake                  19.08.1-1 -> 19.08.2-1
aur/kubectl-bin                1.15.4-1  -> 1.16.1-1

==> Continue upgrade ? [Y/n]
==> [V]iew package detail   [M]anually select packages
==> --------------------------------------------------
==> v

==> Software upgrade (new version) :
extra/yakuake                  19.08.1-1 -> 19.08.2-1
    A drop-down terminal emulator based on KDE konsole technology
aur/kubectl-bin                1.15.4-1  -> 1.16.1-1
    Kubernetes.io client binary

==> Continue upgrade ? [Y/n]
==> [V]iew package detail   [M]anually select packages
==> --------------------------------------------------
==> 
```

Thx for `yay`. At first look it seemed to me not to much useful in compare with `yaourt`. But after time I fell in love with. For example sorting packages from less important to the most important during searching is really great feature.

**Comment by bryce-lynch** [comment]
I wish both options (View package detail, and Manually select packages) were available in yay. I've tried --upgrademenu with -Syu but it doesn't seem to work.
