### ISSUE TITLE
yay fails if it can't access its config file

### ISSUE THREAD

**Issue by LiteracyFanatic** [Jguer/yay#1060]
#### Affected Version
yay v9.3.3 - libalpm v11.0.3

#### Issue
yay fails if it can't create or read its config file. This can happen if attempting to run yay as the nobody user which doesn't have a home directory. For context, I'm trying to use yay to download PKGBUILDs from a system configuration script being run as root by temporarily dropping to the unprivileged nobody user. Then I run `makepkg -s` as nobody and install as root with `pacman -U`.

I can work around this by creating a new unprivileged build user with a home directory or by keeping a list of the PKGBUILD URLs and manually downloading them with wget. Still, I don't think yay should fail if it can't read its config file. It would be better to print a warning and fall back to default values.

#### Steps to reproduce
Run `runuser -u nobody -- yay -G $AUR_PACKAGE_NAME`.

#### Output
```
Failed to create config directory '/.config/yay': mkdir /.config: permission denied
```

**Comment by Jguer** [comment]
> It would be better to print a warning and fall back to default values.
Well yay does fall back to default values, but then it wants to save them. Yes, I know it was an implementation shortcut that we're paying now in figuring out how to make a better config system.

What I can offer you immediately are some workarounds that may work. `yay` is sad not because it cannot read it's config but because it wants to create its directory.

```
	if configHome = os.Getenv("XDG_CONFIG_HOME"); configHome != "" {
		configHome = filepath.Join(configHome, "yay")
	} else if configHome = os.Getenv("HOME"); configHome != "" {
		configHome = filepath.Join(configHome, ".config/yay")
	} else {
		return fmt.Errorf("XDG_CONFIG_HOME and HOME unset")
	}

	if cacheHome = os.Getenv("XDG_CACHE_HOME"); cacheHome != "" {
		cacheHome = filepath.Join(cacheHome, "yay")
	} else if cacheHome = os.Getenv("HOME"); cacheHome != "" {
		cacheHome = filepath.Join(cacheHome, ".cache/yay")
	} else {
		return fmt.Errorf("XDG_CACHE_HOME and HOME unset")
	}

	configFile = filepath.Join(configHome, configFileName)
	vcsFile = filepath.Join(cacheHome, vcsFileName)
```
Here is the code that handles it, `yay` has no env whatsoever so it wants to create `/.config/yay` in root which it can't.
If you can set environment variables, set `$XDG_CONFIG_HOME`and `$XDG_CACHE_HOME` to `/tmp` or in alternative set `$HOME` to `/tmp` or another place where you have write permissions

**Comment by Morganamilo** [comment]
May make sense to wrap the config and such in a function.

```go
func Config() {
    if config == nil {
        config = loadConfig()
    }
    
    return config
}

**Comment by LiteracyFanatic** [comment]
Thank you for the suggestion. `setuser` won't let you fiddle with `$HOME`, but setting the XDG variables worked.

**Comment by k0ste** [comment]
If user account without home dir `yay` also catch this error and impossible to use.

```
[k0ste@router]$ yay --help
Failed to create config directory '/home/k0ste/.config/yay': mkdir /home/k0ste: permission denied
[k0ste@router]$ 
```

This very actual for systems with non-local users, e.g. with PAM LDAP.

**Comment by Jguer** [comment]
@k0ste  would you prefer yay to simply run without using a config file and displaying a warning about it?

**Comment by k0ste** [comment]
@Jguer I'm on Arch since 2013 and was use `yaourt` until his dead. I was never used any config files with exception of `/etc/makepkg.conf`.
So, If some users use some features with this config files - yes, your suggestion will cover this problem.

**Comment by k0ste** [comment]
Unstale

**Comment by k0ste** [comment]
unstale

**Comment by Jguer** [comment]
Doesn't happen in `yay-git`
