### ISSUE TITLE
yay nano default editor

### ISSUE THREAD

**Issue by qaron84** [Jguer/yay#1069]
#### Affected Version
all versions of yay

#### Issue
i cant change the default text editor from "vi" to "nano" when I'm using yay, in order to edit pkgbuilds.
I understand that maybe vi is more lightweight than nano, but i cant understand how it works. some people afraid to change their daily routines, others learned how things work in their own way and cant  or wont change...
I know this isnt a real issue, but its a feature change/addon.

#### Output

**Comment by yssmcl** [comment]
Have you seen https://github.com/Jguer/yay/issues/7?

**Comment by qaron84** [comment]
yea i edit the jay.json file in .config folder and on editor i changed to /usr/bin/nano, but nothing

**Comment by qaron84** [comment]
nevermind i went to trizen now... thx anyway :D

**Comment by Jguer** [comment]
`yay -Syu --editmenu --editor=nano --save`
Should fix your issue

**Comment by GarlandKey** [comment]
Solutions mentioned here no longer work.

'nano' is set as my default editor in both 'zsh' and 'bash' using environment variables. Using 'yay [command] --editmenu --editor=nano --save' doesn't work. When I need to edit the package file, it will only use 'vi' no matter what I do.
