### ISSUE TITLE
[Question] Don't put PKGBUILDs into cache

### ISSUE THREAD

**Issue by tarnh** [Jguer/yay#1076]
#### Affected Version
yay v9.3.3 - libalpm v11.0.3

#### Issue
If I download a PKGBUILD of a package which is in the repos and not from AUR it's placed in ~/.cache/yay/$name/trunk
I don't desire this behaviour and would like to disable it.

**Comment by Jguer** [comment]
Doesn't apply anymore as of `yay v9.4.2`
