### ISSUE TITLE
AUR Packages have been marked (Out-of-date 2019-10-22)

### ISSUE THREAD

**Issue by Master0ne** [Jguer/yay#1080]
Both AUR packages `aur/yay 9.3.3-1` and `aur/yay-bin 9.3.3-1` have just shown up as being marked **(Out-of-date 2019-10-22)**.

**Comment by Jguer** [comment]
Thanks for the warning, they've been unmarked

**Comment by Morganamilo** [comment]
I mean, technically yay is out of date in the AUR.

**Comment by Jguer** [comment]
Technically yay is only out of date now that I pushed the tag :sweat_smile: and a release asset is created. So yes, now it can be remarked

**Comment by Ferdi265** [comment]
I want to add here that `yay-git` is still out of date since the `dependencies` array needs to specify it's compatible with `pacman-5.2.0`

**Comment by Jguer** [comment]
Yes, `yay-git` will only be updated now with the released tag

**Comment by Jguer** [comment]
`yay-git` is updated to the latest tag and dependencies have been checked

**Comment by Jguer** [comment]
Updated PKGBUILDs are in http://github.com/Jguer/yay-PKGBUILD ready to be pushed, just haven't decided what's the best moment for it, right before hitting core would be the best but hard to time.
Worst case scenario is post core hitting.

**Comment by LinuxUserGD** [comment]
> Updated PKGBUILDs are in [http://github.com/Jguer/yay-PKGBUILD](https://github.com/Jguer/yay-PKGBUILD) ready to be pushed, just haven't decided what's the best moment for it, right before hitting core would be the best but hard to time.
> Worst case scenario is post core hitting.
> 
> EDIT: this is the best moment for `PKGBUILD` changes if you notice something

I don't use testing for core but only use `--devel --timeupdate``and yay shows that I need a newer pacman (`'pacman>=5.2'`). Don't know how to upgrade it, I tried `pacman-git` which seems to update it to 5.2 but it still shows as  `5.1.1.r221.g8f89e509-1`.

**Comment by Morganamilo** [comment]
Just wait for pacman-5.2 to hit core.

**Comment by munoah** [comment]
pacman 5.2 hit core, is there a sane way to update yay and pacman at the same time? 
right now i get the following if I do `yay -Syu` or `yay -S yay`:
```
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing pacman (5.2.0-2) breaks dependency 'pacman<=5.1.3' required by yay
````
