### ISSUE TITLE
Build from git master is broken

### ISSUE THREAD

**Issue by glitsj16** [Jguer/yay#1081]
#### Issue
Wanted to be ready for pacman 5.2 and tried building [yay-git](https://aur.archlinux.org/packages/yay-git/). Here's the output of the build() function:

```
go build -v -mod=vendor -ldflags '-s -w -linkmode external -extldflags "-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now" -X "main.version=9.3.3.r51.ge140386"'  -o yay
github.com/Jguer/go-alpm
vendor/github.com/Jguer/go-alpm/sync.go:18:9: could not determine kind of name for C.alpm_sync_get_new_version
```

Regards

**Comment by Morganamilo** [comment]
As of 2 hours ago, `yay-git` requires `pacman-5.2`.

**Comment by Morganamilo** [comment]
Although I just noticed yay-git has a `pacman<5.2` depend.

**Comment by glitsj16** [comment]
> if you use [testing] yay will work for this, otherwise, once pacman is updated in core, you'll be able to update yay-git.

Thanks for the speedy reply. I'll wait for pacman to hit core.

> Although I just noticed yay-git has a pacman<5.2 depend.

Noticed that too and changed it manually to pacman<5.3
