### ISSUE TITLE
Packager format wrong in package

### ISSUE THREAD

**Issue by thomai** [Jguer/yay#1085]
#### Affected Version

yay v9.4.0 - libalpm v12.0.0

#### Issue
During installation, the following warning shows up:
`==> WARNING: PACKAGER should have the format 'Example Name <email@address.invalid>'`

#### Steps to reproduce

1. `git clone https://aur.archlinux.org/yay.git`
2. `cd yay`
3. `makepkg -si`

**Comment by Jguer** [comment]
I believe that's the new makepkg version's doing. It's related to your entry of `PACKAGER` in `/etc/makepkg.conf` 
```
#-- Packager: name/email of the person or organization building packages
#PACKAGER="John Doe <john@doe.com>"
```

**Comment by Morganamilo** [comment]
As it happens I already made a patch for this yesterday. Don't expect to see it any time soon though.

https://patchwork.archlinux.org/patch/1289/
