### ISSUE TITLE
-G on a repo package creates '$HOME' directory and broken symlink

### ISSUE THREAD

**Issue by jpfkd** [Jguer/yay#1086]
#### Affected Version
yay v9.4.0.r0.gc0e78c8 - libalpm v12.0.0

#### Issue
When I use `yay -G` on a package in the repo, it creates a directory named '$HOME' and broken symlink to `/home/<username>/.cache/yay/<package name>/trunk` in current directory.

#### Steps to reproduce
1. yay -G pacman

#### Output
Contents of '$HOME' directory
```
% ls -aR '$HOME/'
'$HOME/':
./  ../  .cache/

'$HOME/.cache':
./  ../  yay/

'$HOME/.cache/yay':
./  ../  abs/

'$HOME/.cache/yay/abs':
./  ../  pacman/

'$HOME/.cache/yay/abs/pacman':
./  ../  .git/  repos/  trunk/

'$HOME/.cache/yay/abs/pacman/.git':
./  ../  branches/  config  description  HEAD  hooks/  index  info/  logs/  objects/  packed-refs  refs/

'$HOME/.cache/yay/abs/pacman/.git/branches':
./  ../

'$HOME/.cache/yay/abs/pacman/.git/hooks':
./                      fsmonitor-watchman.sample*  prepare-commit-msg.sample*  update.sample*
../                     post-update.sample*         pre-push.sample*
applypatch-msg.sample*  pre-applypatch.sample*      pre-rebase.sample*
commit-msg.sample*      pre-commit.sample*          pre-receive.sample*

'$HOME/.cache/yay/abs/pacman/.git/info':
./  ../  exclude

'$HOME/.cache/yay/abs/pacman/.git/logs':
./  ../  HEAD  refs/

'$HOME/.cache/yay/abs/pacman/.git/logs/refs':
./  ../  heads/

'$HOME/.cache/yay/abs/pacman/.git/logs/refs/heads':
./  ../  packages/

'$HOME/.cache/yay/abs/pacman/.git/logs/refs/heads/packages':
./  ../  pacman

'$HOME/.cache/yay/abs/pacman/.git/objects':
./  ../  info/  pack/

'$HOME/.cache/yay/abs/pacman/.git/objects/info':
./  ../

'$HOME/.cache/yay/abs/pacman/.git/objects/pack':
./  ../  pack-2d9b6c7bba01bd529de4fb90229d27fdcd7fc13a.idx  pack-2d9b6c7bba01bd529de4fb90229d27fdcd7fc13a.pack

'$HOME/.cache/yay/abs/pacman/.git/refs':
./  ../  heads/  tags/

'$HOME/.cache/yay/abs/pacman/.git/refs/heads':
./  ../  packages/

'$HOME/.cache/yay/abs/pacman/.git/refs/heads/packages':
./  ../  pacman

'$HOME/.cache/yay/abs/pacman/.git/refs/tags':
./  ../

'$HOME/.cache/yay/abs/pacman/repos':
./  ../  core-x86_64/

'$HOME/.cache/yay/abs/pacman/repos/core-x86_64':
./  ../  makepkg.conf  pacman.conf  PKGBUILD

'$HOME/.cache/yay/abs/pacman/trunk':
./  ../  makepkg.conf  pacman.conf  PKGBUILD
```

"absdir" being default
```
% yay -Pg |grep abs
	"absdir": "$HOME/.cache/yay/abs",
```

**Comment by Jguer** [comment]
Related to #1068 , `fs` as usual, unexpanded env variable by default. 

Workaround: 
use `yay -Syu --absdir /home/<insert your user>/.cache/yay/abs --save` and it will set it correctly,
I'll be fixing this for a patch now.

**Comment by jpfkd** [comment]
Still creates broken symlink.
```
% file pacman
pacman: broken symbolic link to /home/junpei/.cache/yay/pacman/trunk
```
"junpei" is my username. It lacks "abs" between "yay" and "pacman"?

Also, the command line you showed for a workaround doesn't work. (I assume the `-Syu` part is typo)
```
% yay --absdir /home/junpei/.cache/yay/abs --save
invalid option 'absdir'
```

**Comment by Morganamilo** [comment]
Looks like I broke this. But why is it a symlink anyway. It wasn't before. If we're going to copy asp to such a degree we may as well just depend on it.

**Comment by Jguer** [comment]
Ok, just saw the problem not such a simple fix, let's do it properly.
 
@Morganamilo can you take care of it now or want me to do it?

**Comment by Jguer** [comment]
@jpfkd does it work on `yay-git`?

**Comment by jpfkd** [comment]
I'm currently on `yay v9.4.1.r1.g203b493 - libalpm v12.0.0` and the issues in the previous comment remains true.

**Comment by Morganamilo** [comment]
I can do it but not right now :p 

So take your pick.

**Comment by Jguer** [comment]
On it already, fix is produced

**Comment by Morganamilo** [comment]
That's a genuine question BTW. Why symlink it?

**Comment by Jguer** [comment]
it was the fastest and most non disruptive way when ABS tar broke to keep the repo working but still offer a folder with just the files people wanted inside. The plan was for it to be a band aid, but it hasn't been fixed because I wanted a proper discussion on what was the best way to do it

**Comment by Morganamilo** [comment]
Couldn't you just copy instead of link?

**Comment by Jguer** [comment]
Yes, I can change it to copy now even, and track the repo in the cache sure.

**Comment by Jguer** [comment]
@jpfkd give it a roll on `yay-git`, everything should be working now

**Comment by jpfkd** [comment]
It's working.
```
% yay -G pacman
:: Querying AUR...
:: Downloaded PKGBUILD from ABS (1/1): pacman

% ls pacman
makepkg.conf  pacman.conf  PKGBUILD
```

```
% yay --save --absdir /home/junpei/.cache/yay/abs

% yay -Pg |grep absdir
	"absdir": "/home/junpei/.cache/yay/abs",
```
