### ISSUE TITLE
PACKAGER should have the format 'Example Name <email@address.invalid>'

### ISSUE THREAD

**Issue by GhostKraft** [Jguer/yay#1090]
_when installing packages from AUR using YAY constantly gives
a lot of warning:_
**==>  WARNING: PACKAGER should have the format 'Example Name <email@address.invalid>'**

![2019-10-24_07-41](https://user-images.githubusercontent.com/48885256/67454490-eeff0980-f632-11e9-9970-bca3abea7402.png)

Packages from the repository are installed normally, but warnings constantly appear.
Please tell me what these warnings are and how to remove them?

**Comment by Alexey104** [comment]
Having the same messages after recent yay update.

**Comment by bjauy** [comment]
Those are messages from makepkg after recent `pacman` update. Ask AUR package maintainers to update their packages.

From https://git.archlinux.org/pacman.git/tree/NEWS 

> - add routine for linting $PACKAGER to check that it has a
                  valid name and email address, and document the desired format
                  in makepkg.conf(5)
