### ISSUE TITLE
error while loading shared libraries: libalpm.so.12

### ISSUE THREAD

**Issue by nivaca** [Jguer/yay#1094]
I followed the instructions here (https://github.com/Jguer/yay/issues/1087), and reinstalled yay.
However, when I run it, I still get the error.
(I'm on Manjaro KDE 5.16.5)

**Comment by Morganamilo** [comment]
yay-bin targets pacman-5.2 which i guess manjaro does not have/

**Comment by 3DDario** [comment]
> yay-bin targets pacman-5.2 which i guess manjaro does not have/

Correct. Manjaro stable and testing have pacman-5.1.x in their repository

**Comment by Jguer** [comment]
I guess `sudo pacman -S yay` will fix your issue, I guess I'll have to make it clearer in all the instructions repos and more specifically manjaro need not apply.

**Comment by nivaca** [comment]
> I guess `sudo pacman -S yay` will fix your issue, I guess I'll have to make it clearer in all the instructions repos and more specifically manjaro need not apply.

Yeah, that did the trick. Thanks.
