### ISSUE TITLE
Feature: partially clean cache

### ISSUE THREAD

**Issue by japm48** [Jguer/yay#1096]
This is a feature request for a partial cleanup of the yay package cache: in particular, I would like to be able to clean the `~/.cache/yay` directory, while preserving only the built `.pkg.tar.xz` files  corresponding to the currently installed versions. This would be similar to what `pacman -Sc` does in the cache directory `/var/cache/pacman/pkg/`.

My particular use case is the following: I'm currently designing a program (which I'll hopefully release sooner or later...) to emulate `pkgfile` / `pacman -F` functionality for AUR packages that reads the AUR cache; also I would like it to (e.g.) compare the `/etc` config files with the original package contents. Therefore, I would find useful an option in between `rm -rf`ing the entire cache and keeping the older versions (which consumes too much space in the long run).

**Comment by Jguer** [comment]
For cleaning we're thinking of just going `git clean -fdx` on the repositories, which `yay -Sc` does, so I don't know quite well on how we'd implement this

Also if you are making an utility based on AUR cache I would recommend using `$AURDEST` for determining its location as well, since both `yay` and `aurutils` use it.

**Comment by Morganamilo** [comment]
This is what PKGDEST is for.

**Comment by Morganamilo** [comment]
By the way what do you plan to achieve with your goal? `pacman -Q[l|o]` works fine for me, so I've no real need to use `-F` on AUR packages. If you want that though maybe look into using a local repo for aur management.
