### ISSUE TITLE
Hard to Install and Failing Packages 

### ISSUE THREAD

**Issue by Morganamilo** [Jguer/yay#110]
This is a centralised issue to keep track of packages which are hard to install and can be used for testing purposes or fail to install and need to be fixed.

For testing purposes packages should be installed in a clean chroot with base and base-devel installed. This allows the most dependencies to be pulled and helps test dependency solving. It is also a good idea to test the dependency tree against pacaur to test if they match.

When testing packages good things to look out for are:

- Fast to download and build (packages like linux-ck would just take too long)
- Split packages
- Circular dependencies 
- Versioned dependencies (mkinitcpio>=0.7)
- huge amount of dependencies (both repo and AUR)

If you know a package fails to install under Yay the opposite should be done and you should have everything installed apart from the offending package(s). This helps narrow the cause of the failure down to as few packages as possible.

**Comment by maximbaz** [comment]
Here's one issue that doesn't reproduce on the latest release:

```
❯ yay ls++
2 aur/ls++-git 1:0.36.87.e17221c-1 (54)
    Colorized LS on steroids
1 community/ls++ 1:0.36-2
    Colorized LS on steroids
Type the numbers or ranges (e.g. 1-10) you want to install. Separate each one of them with a space.
Numbers: 1
error: argument '-' specified without input on stdin
Error installing repo packages.
```

**Comment by Morganamilo** [comment]
Are you sure you're running the latest master? this should have been fixed in #107

**Comment by maximbaz** [comment]
Ah, I didn't have today's new commits pulled - you are right, sorry for the noise

**Comment by maximbaz** [comment]
I feel like [fonts-meta-extended-lt](https://aur.archlinux.org/packages/fonts-meta-extended-lt/) would be a good package for testing, it has lots of small dependencies, both in repo and AUR. However, at this moment one of the dependencies ([ttf-impallari-cantora](https://aur.archlinux.org/packages/ttf-impallari-cantora/)) is broken and requires editing PKGBUILD and prepending `https://web.archive.org/web/20150719101220/` to the source link.

**Comment by Morganamilo** [comment]
This has been open for quite a while and not really gone anywhere. We've had plenty of time to test since then and everything I know of installs fine. Probably best to have failing packages in individual issues.
