### ISSUE TITLE
go version

### ISSUE THREAD

**Issue by hoopchen** [Jguer/yay#1103]
hi, I try to checkout master from github and install yay

```
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
```

It requires to upgrade my go version

```
resolving dependencies...
looking for conflicting packages...

Packages (1) go-2:1.13.3-1

Total Download Size:   122.42 MiB
Total Installed Size:  478.81 MiB

:: Proceed with installation? [Y/n] n
```

I donot want to upgrade my go version. I use go 1.12.7 to develop other projects.

Why `yay` requires the latest go version anyway?

**Comment by Morganamilo** [comment]
Given how it says `Total Installed Size:  478.81 MiB` with no mention of `Net Upgrade Size` It's clear you never had go installed at all.

**Comment by hoopchen** [comment]
I did have go installed

```
➜  ~ go version
go version go1.12.7 linux/amd64

➜  ~ which go
/usr/local/go/bin/go

```

I installed go through `wget` tarbar and unzip , not  `pacman`

**Comment by Morganamilo** [comment]
And as far as pacman is concerned it's not installed.

And even though I did assume it was the case, please don't leave you such crucial information in your post.

**Comment by hoopchen** [comment]
Thank you for pointing out this direction, apologize for losing this important information in the post. 

I will uninstall go and install go with pacman . Thank you.
