### ISSUE TITLE
Can't install yay: "cannot load encoding/json"

### ISSUE THREAD

**Issue by RyanAbraham** [Jguer/yay#1108]
#### Affected Version

N/A, trying to install latest version
go version go1.13.3 linux/amd64
5.3.7-arch1-2-ARCH

#### Issue
I'm trying to install yay for the first time on Arch. It keeps failing with the same error, and I'm really not sure how to proceed from here. I've tried cleaning the build, re-cloning, different makepkg flags, googling issues related to the error. I haven't been able to figure out anything that fixes it yet though.

#### Steps to reproduce

1. `git clone https://aur.archlinux.org/yay.git`
2. `cd yay`
3. `makepkg -si`

#### Output

```
rain@ArchRain /home/rain/dev                                                                                                                                                                                   
⚡ git clone https://aur.archlinux.org/yay.git
Cloning into 'yay'...
remote: Enumerating objects: 272, done.
remote: Counting objects: 100% (272/272), done.
remote: Compressing objects: 100% (194/194), done.
remote: Total 272 (delta 76), reused 272 (delta 76)
Receiving objects: 100% (272/272), 56.80 KiB | 424.00 KiB/s, done.
Resolving deltas: 100% (76/76), done.

rain@ArchRain /home/rain/dev                                                                                                                                                                                   
⚡ cd yay

rain@ArchRain /home/rain/dev/yay                                                                                                                                                                      master
⚡ makepkg -si
==> WARNING: PACKAGER should have the format 'Example Name <email@address.invalid>'
==> Making package: yay 9.4.2-1 (Wed 30 Oct 2019 03:56:57 PM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading yay-9.4.2.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   117    0   117    0     0    434      0 --:--:-- --:--:-- --:--:--   433
100  351k  100  351k    0     0   463k      0 --:--:-- --:--:-- --:--:--  463k
==> Validating source files with sha1sums...
    yay-9.4.2.tar.gz ... Passed
==> Extracting sources...
  -> Extracting yay-9.4.2.tar.gz with bsdtar
==> Starting build()...
go build -v -mod=vendor -ldflags '-s -w -linkmode external -extldflags "-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now" -X "main.version=9.4.2"' -gcflags all=-trimpath=/home/rain/dev/yay/src/yay-9.4.2 -asmflags all=-trimpath=/home/rain/dev/yay/src/yay-9.4.2 -o yay
build encoding/json: cannot load encoding/json: open /home/rain/dev/yay/src/yay-9.4.2/vendor/encoding/json: no such file or directory
make: *** [Makefile:47: yay] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by Morganamilo** [comment]
Do you do anything with go? Done anything weird? Does ~/go exists and does deleting it fix it?

**Comment by Jguer** [comment]
Output of `where go` and try using the `gcc-go` package to confirm it's related to the go compiler

**Comment by lacunahag** [comment]
+1 am having the exact same issue. To answer these questions:
> Do you do anything with go? Done anything weird? 

Have never installed Go on this machine. It's a pretty recently fresh install.

> Output of where go and try using the gcc-go package to confirm it's related to the go compiler

`$ which go` gives `/usr/bin/go`. 

### Some extra info
I initially got this error:
```
go: cannot find GOROOT directory: /home/jas/go/src/projects
```
which went away when I created the directory. I don't know anything about Go though so that may have been the wrong solution.

**Comment by Morganamilo** [comment]
Can't reproduce. Yay's PKGBUILD doesn't even touch ~/go on my machine.

Works both on my system and with extra-x86_64-build.

What if you delete `~/.cache/go-build`?

**Comment by lacunahag** [comment]
Fixed! I forgot I'd copied part of a .bashrc from another machine where weird things *were* being done with Go.

Try `$ unset GOROOT` for anyone else having this problem.

Thanks!

**Comment by RyanAbraham** [comment]
Works now after doing `unset GOROOT`, thanks so much!
