### ISSUE TITLE
Diffs no longer show correct change set

### ISSUE THREAD

**Issue by dgmulf** [Jguer/yay#1109]
#### Affected Version

yay v9.4*

#### Issue

Diffs are always presented as if installing a package for the first time, rather than showing changes relative to installed version, as previously.

#### Example Output

Note the starting endpoint (0000000)
```
diff --git /home/dgmulf/build/aur/signal-desktop-bin/PKGBUILD /home/dgmulf/build/aur/signal-desktop-bin/PKGBUILD
new file mode 100644
index 0000000..cd41edb
--- /dev/null
+++ /home/dgmulf/build/aur/signal-desktop-bin/PKGBUILD
@@ -0,0 +1,46 @@
+# Maintainer: Janek Thomaschewski <janek@jbbr.net>
+# Maintainer: Stephan Springer <buzo+arch@Lini.de>
+
+pkgname=signal-desktop-bin
[...]
```

**Comment by Morganamilo** [comment]
How we calculate diffs changed. Meaning the "from" point has been reset.

>Diffs are always presented as if installing a package for the first time, rather than showing changes relative to installed version, as previously.

This however should not be happening. Once you've reviewed a diff with the new system it should stick.

I'm guessing you didn't test the same package twice.

If you want to mark everything up to now as seen you can do

```sh
for dir in ~/.cache/yay/*; do
        git -C "$dir" update-ref AURSEEN HEAD
done
```

**Comment by dgmulf** [comment]
Thanks for the reply. I'm not sure if I've installed the same package twice with yay 9.4, but git command you provided doesn't seem to change anything. Perhaps it has to do with the fact that I'm using a custom build directory? (I changed the path in the for loop accordingly.)

**Comment by Morganamilo** [comment]
Whoops, I meant `AUR_SEEN`

**Comment by dgmulf** [comment]
Yep, that did the trick. Should yay automatically update the AUR_SEEN refs in the cache after upgrading from <v9.4?

**Comment by Morganamilo** [comment]
If yay was a system program then I would have written a simple alpm hook for it. With it being per user I don't really want to write all that into yay.

**Comment by Taijian** [comment]
Something I noticed that might be related to this: It seems to me that when updating AUR packages, yay will in 9.4 only update the package by ONE (1) step/revision at a time.

So, when I get notified by Arch-Update-Indicator that e.g. SampleAUR has an update available form x.y.2 -> x.y.4, then yay will show me the change notes for .2 to .4 but only install .3. Then, I get notified of the possible update from .3 to .4 and yay will pull and install another update, when run.

I'd kinda like to get the old behaviour back, where yay would just skip over releases that happened in between of it being run.

**Comment by simonbcn** [comment]
Same problem.

**Comment by simonbcn** [comment]
```
Arch Linux
yay v10.0.3 - libalpm v12.0.2
```

This failure is a serious lack of security.  It has been reported in October 2019 and no one has yet bothered to fix it?
The workaround doesn't solve anything:
```
~ $ cd ~/.cache/yay/fkill

~/.cache/yay/fkill $ git -C . update-ref AUR_SEEN HEAD

~/.cache/yay/fkill $ yay -S fkill
diff --git /home/juan/.cache/yay/fkill/.gitignore /home/juan/.cache/yay/fkill/.gitignore
new file mode 100644
index 0000000..91f1c10
--- /dev/null
+++ /home/juan/.cache/yay/fkill/.gitignore
@@ -0,0 +1,4 @@
+/*
+!/.gitignore
+!/PKGBUILD
+!/.SRCINFO
diff --git /home/juan/.cache/yay/fkill/PKGBUILD /home/juan/.cache/yay/fkill/PKGBUILD
new file mode 100644
index 0000000..7844800
--- /dev/null
+++ /home/juan/.cache/yay/fkill/PKGBUILD
@@ -0,0 +1,48 @@
+# Maintainer: Ivan Fonseca <ivanfon@riseup.net>
+
+# NPM package name
....
```

**Comment by simonbcn** [comment]
I have tested by deleting the entire `.cache/yay` directory and installing a program twice, the second time it should not show any difference but the same error.

**Comment by thibaultmol** [comment]
Feels like this doesn't happen on first install? 
if I install an aur package using yay, the first time it requires an update, It'll show the entire pgkbuild.
Second time it'll show the difference.
Yet the moment I installed it first, I already checked the whole pkgbuild.

Is this issue related?
