### ISSUE TITLE
zsh completion seems to not work

### ISSUE THREAD

**Issue by otaj** [Jguer/yay#1110]
#### Affected Version
yay v9.4.2.r8.g3fef09e - libalpm v12.0.0

#### Issue
Hi, for some reason, zsh completions seems to not work for me. I am not very well versed in zsh configuration, here are relevant options in my `~/.zshrc`

```
ZSH=/usr/share/oh-my-zsh/

export LANG=en_US.UTF-8

ZSH_CACHE_DIR=$HOME/.oh-my-zsh-cache
if [[ ! -d $ZSH_CACHE_DIR ]]; then
  mkdir $ZSH_CACHE_DIR
fi

source $ZSH/oh-my-zsh.sh


autoload -Uz +X compinit && compinit
autoload -Uz +X bashcompinit && bashcompinit

zstyle ':completion::complete:*' gain-privileges 1
zstyle ':completion:*' menu select
zstyle :compinstall filename '/home/otaj/.zshrc'
zstyle ':completion:*' rehash true
setopt COMPLETE_ALIASES
```

It is entirely possible, that it is only a misconfiguration, however, no completion related to yay is shown (removing packages, offering packages to install, nothing). Completion works in other places, as expected (namely pacman).

Thanks for any pointers regarding how to enable zsh completions.

**Comment by hjpotter92** [comment]
Having this same issue.

**Comment by Morganamilo** [comment]
Works for me.

What happens when you try to hit tab?
Have you reloaded your completions since starting yay?
Do pacman's completions work?

**Comment by hjpotter92** [comment]
Nothing happens on hitting tab.
```
┌┤✅├─┤ hjpotter92 ├─┤~├─┤ 🕧 12:35 PM │
└┴─ ⚡[..........] ┴─ ➜ yay -S swa
```

pacman's completions work out of the box:
```
┌┤✅├─┤ hjpotter92 ├─┤~├─┤ 🕧 12:36 PM │
└┴─ ⚡[..........] ┴─ ➜ pacman -S swa
swaks     sway      swaybg    swayidle  swaylock
```

On reloading completions, (`compinit -u`), the completions start working. But this is a session only solution. On opening a new window, the completions are gone again.

**Comment by Morganamilo** [comment]
>yay -S swa

That's package names. Do the opts complete? That's all I actually tested before posting.

**Comment by Morganamilo** [comment]
Although for the record packages to complete for me

```
morganamilo@Octavia ~ %  yay -S swa
swac-record                     swarp                           swayidle
swagger2openapi                 swar-red                        swayidle-git
swagger-codegen                 swars                           sway-interactive-screenshot
swagger-codegen-2               swatchbooker                    sway-keyboard-layout
swagger-codegen-git             swatchbooker-git                swaylock
swagger-dsl                     swatchdog                       swaylock-blur-bin
swagger-editor-git              swatchtime-git                  swaylock-blur-git
swagger-ui                      swatd-git                       swaylock-blur-multimonitor-git
swaks                           swath                           swaylock-delay-password-git
swallow-git                     sway                            swaylock-effects-git
swamp                           swaybg                          swaylock-fancy-git
swap                            swaybg-git                      swaylock-git
swapper                         swayblocks                      swaynagmode
swapspace                       sway-git                        sway-services-git
swarm                           swaygrab-helper                 swayshot
```

**Comment by hjpotter92** [comment]
On my other installations (office and laptop), the completions work for package list as well. On the home desktop, neither the opts nor package names are suggested when hitting tab.

There was a discussion around deletion of a lock or db file in `~/.cache/yay`, but there are only directories inside.

**Comment by Morganamilo** [comment]
>There was a discussion around deletion of a lock or db file in ~/.cache/yay

Not sure where you got that from...

What does `pacman -Ql yay` say?

The file mentioned is now called `~/.cache/yay/completion.cache`. Although before you delete it, for debugging purposes can you please show what is in there.

**Comment by hjpotter92** [comment]
```
┌┤✅├─┤ hjpotter92 ├─┤~├─┤ 🕐 12:49 PM │	
└┴─ ⚡[..........] ┴─ ➜ pacman -Ql yay      
yay /usr/
yay /usr/bin/
yay /usr/bin/yay
yay /usr/share/
yay /usr/share/bash-completion/
yay /usr/share/bash-completion/completions/
yay /usr/share/bash-completion/completions/yay
yay /usr/share/fish/
yay /usr/share/fish/vendor_completions.d/
yay /usr/share/fish/vendor_completions.d/yay.fish
yay /usr/share/man/
yay /usr/share/man/man8/
yay /usr/share/man/man8/yay.8.gz
yay /usr/share/zsh/
yay /usr/share/zsh/site-functions/
yay /usr/share/zsh/site-functions/_yay
```
The `completion.cache` file contents:

[completion.cache](https://github.com/Jguer/yay/files/3801310/comp.txt)

**Comment by hjpotter92** [comment]
> > There was a discussion around deletion of a lock or db file in ~/.cache/yay
> 
> Not sure where you got that from...

Reddit thread: https://www.reddit.com/r/archlinux/comments/8ocrr2/tab_completion_not_working_with_yay/

**Comment by Morganamilo** [comment]
Yes, they mention the file, but there's no mention of it being a lock file.

Anyway the file is populated. But I guess even if it was empty, that should only stop -S completion and not everything else.

Anyway I'm kinda lost unless you have anything weird in your zshrc.

Mine is just:

```sh
zstyle :compinstall filename '/home/morganamilo/.zshrc'

autoload -Uz compinit
compinit
```

For completion anyway.

**Comment by hjpotter92** [comment]
I have the default [oh-my-zsh template file][1] with a few extra plugins.


  [1]: https://github.com/robbyrussell/oh-my-zsh/blob/master/templates/zshrc.zsh-template

**Comment by hjpotter92** [comment]
And this is true for all of 3 machines with installations I have of yay.

**Comment by Morganamilo** [comment]
Can you back up your zshrc and replace it with mine?

**Comment by hjpotter92** [comment]
Running compinit does solve the issue, as I mentioned earlier. But it also slows down the bootup of shell.

**Comment by Morganamilo** [comment]
Now I'm no zsh expert, but don't you need compinit to ya know, make completion work?

(clearly not if pacman magically works without it, but I can't understand why it would be any other way)

**Comment by hjpotter92** [comment]
> Also what if you use an empty zshrc? I assume pacman and yay will both fail to complete.

Empty zshrc fails to autocomplete either of those.

> Also I guess I should have asked this sooner. Are you a new user and completion never worked? Or did they stop working?

Have been using yay for almost an year now. Recently, reinstalled arch on a new disk. The completions haven't worked since.

```
➜ yay --version
yay v9.4.2 - libalpm v12.0.1
```

My zshrc file is available here: https://github.com/hjpotter92/.files/blob/master/.zshrc

**Comment by hjpotter92** [comment]
> Also what if you use an empty zshrc? I assume pacman and yay will both fail to complete.

Empty zshrc fails to autocomplete either of those.

> Also I guess I should have asked this sooner. Are you a new user and completion never worked? Or did they stop working?

Have been using yay for almost an year now. Recently, reinstalled arch on a new disk. The completions haven't worked since.

```
➜ yay --version
yay v9.4.2 - libalpm v12.0.1
```

My zshrc file is available here: https://github.com/hjpotter92/.files/blob/master/.zshrc

**Comment by hjpotter92** [comment]
> Also what if you use an empty zshrc? I assume pacman and yay will both fail to complete.

Empty zshrc fails to autocomplete either of those.

> Also I guess I should have asked this sooner. Are you a new user and completion never worked? Or did they stop working?

Have been using yay for almost an year now. Recently, reinstalled arch on a new disk. The completions haven't worked since.

```
➜ yay --version
yay v9.4.2 - libalpm v12.0.1
```

My zshrc file is available here: https://github.com/hjpotter92/.files/blob/master/.zshrc

**Comment by hjpotter92** [comment]
> Also what if you use an empty zshrc? I assume pacman and yay will both fail to complete.

Empty zshrc fails to autocomplete either of those.

> Also I guess I should have asked this sooner. Are you a new user and completion never worked? Or did they stop working?

Have been using yay for almost an year now. Recently, reinstalled arch on a new disk. The completions haven't worked since.

```
➜ yay --version
yay v9.4.2 - libalpm v12.0.1
```

My zshrc file is available here: https://github.com/hjpotter92/.files/blob/master/.zshrc

**Comment by Morganamilo** [comment]
I guess it's time to go deeper and paste your ohmyzsh stuff?

Also what if you use an empty zshrc? I assume pacman and yay will both fail to complete.

**Comment by Morganamilo** [comment]
Also I guess I should have asked this sooner. Are you a new user and completion never worked? Or did they stop working?

**Comment by otaj** [comment]
Hi, for me, the completions do not work with your .zshrc file nor with `compinit -u`. I am a new yay user, I was using pikaur before, I started using yay 5 days ago.

**Comment by Morganamilo** [comment]
You loaded compinit before running it right? You also understand .zsh is sourced when zsh starts so you need to open a new terminal or source it manually to apply? Just covering the basics cause I don't really get what could be wrong.

Also as a last resort, reboot.

If anybody can reproduce pacman's completion working while yay's after a reboot then I'll take this all a bug.

Until them I'm gonna just say "initialise completion for completion to work duh".

**Comment by Kattus** [comment]
This seems highly related to https://github.com/robbyrussell/oh-my-zsh/issues/7642 and is not specific to yay.
I had to apply the workaround in there (deleting *.zcoredump on each startup) to make yay auto completion work, also applies to some other applications but not all.

**Comment by hjpotter92** [comment]
> This seems highly related to [robbyrussell/oh-my-zsh#7642](https://github.com/robbyrussell/oh-my-zsh/issues/7642) and is not specific to yay.
> I had to apply the workaround in there (deleting *.zcoredump on each startup) to make yay auto completion work, also applies to some other applications but not all.

Yes. That was it. After cleaning the `~/.zcompdump*` files and starting a new terminal, things are working fine. @otaj are you using oh-my-zsh as well?

**Comment by Morganamilo** [comment]
>  @otaj are you using oh-my-zsh as well?

I mean, did you read their zshrc?

Anyway looks like this is nothing to do with us thankfully.

**Comment by otaj** [comment]
Yes, I am using oh-my-zsh, that was it, thanks!

**Comment by jck** [comment]
I had this issue on zsh and the solution was to rm `~/.cache/yay/completion.cache`

**Comment by HydeFromT70s** [comment]
I had exactly the same issue and found that zsh-autocomplete plugin in .zshrc file was conflicting. After removing it from plugins yay auto completion works again.

EDIT: Actually yay's auto completion works fine with zsh-autocomplete plugin for me. The only thing has change is instead of TAB you need to use down arrow key to get auto completion.

**Comment by blackbookpro** [comment]
> I had this issue on zsh and the solution was to rm `~/.cache/yay/completion.cache`

That also worked for me! Thank you!!!

**Comment by CyanChanges** [comment]
> I had this issue on zsh and the solution was to rm `~/.cache/yay/completion.cache`

It worked for me, thanks!
