### ISSUE TITLE
Respect IgnorePkg/IgnoreGroup

### ISSUE THREAD

**Issue by X0rg** [Jguer/yay#1113]
### Affected Version

yay v9.4.2 - libalpm v12.0.1

#### Issue
Yay tries to update packages listed in `IgnorePkg`/`IgnoreGroup` (from `/etc/pacman.conf` file).

#### Steps to reproduce

One example with a part of my `/etc/pacman.conf` config file:
```
# Pacman won't upgrade packages listed in IgnorePkg and members of IgnoreGroup
#IgnorePkg   =
IgnoreGroup = local
```

And the list of packages in `local` group (e.g. a local meta-package):
```
$ pacman -Qqg local
app-cli
app-gui
```

#### Output

When I do a `yay -Syu`, I see that:
```
:: Searching databases for updates...
:: Searching AUR for updates...
:: Checking development packages...
 -> Missing AUR Packages:  app-cli  app-gui
```
It looks like Yay tries to update `app-cli` and `app-gui` packages while I would not want.
Yay should not try to update these packages, because they are in `local` group and this group is ignored by Pacman.

*** 

Yay current config:
```
yay -Pg 
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/yohan/.cache/yay",
	"absdir": "/home/yohan/.cache/yay/abs",
	"editor": "/usr/bin/nano",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"tarbin": "bsdtar",
	"redownload": "no",
	"rebuild": "no",
	"batchinstall": false,
	"answerclean": "None",
	"answerdiff": "Installed",
	"answeredit": "NotInstalled",
	"answerupgrade": "None",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": true,
	"timeupdate": false,
	"devel": true,
	"cleanAfter": false,
	"gitclone": true,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": false,
	"cleanmenu": false,
	"diffmenu": true,
	"editmenu": true,
	"combinedupgrade": false,
	"useask": false
}
```

**Comment by Morganamilo** [comment]
Yay does respect ignoregroup when it comes to actually upgrading packages. It looks like yay is querying the AUR before it filters out the ignored packages.

**Comment by Morganamilo** [comment]
Actually to print the warning `-> foo: ignoring package upgrade (1 => 2)` we do still need to query the AUR packages that are ignored. Maybe the warning for missing packages should just be suppressed for ignored stuff.

Although I can see that being kind of annoying due to alpm_pkg_should_ignore requiring an alpm_pkg_t. And when we query the AUR we're working with strings instead.

**Comment by X0rg** [comment]
@Morganamilo Thank you for your work! :beers:
