### ISSUE TITLE
yay with root password instead of sudo password

### ISSUE THREAD

**Issue by hifi25nl** [Jguer/yay#1114]
In systems where sudo password is not defined., could be possible to configure yay to use  root password instead of sudo password?

I was looking at /.config/yay/ but the directory is empty.

**Comment by Morganamilo** [comment]
You can configure what command is used for sudo. However sudo expects each argument separately `sudo echo foo`, while su want's it as one argument `su -c "echo foo"`. So you'll need some wrapper script to convert it.

`su -c "$*"` will probably work

**Comment by hifi25nl** [comment]
May be I was not clear.

Ok, I am installing an AUR package with yay.
 I start yay as user. 
Before installing the package yay is asking for my sudo password.  I on't have it. I don't want to set it. I don't want to make sudo password the same as root password...
I want yay ask me root password instead

**Comment by Morganamilo** [comment]
Well i'm sure you can probably configure sudo to do that. Although by default sudo uses your user password. Are you saying your user does not have a password configured?

**Comment by hifi25nl** [comment]
The systems I am managing (more than 100) don't have a sudo password, because sudo is not used by design (as in Ubuntu for example)
I am deciding if switching to yay is possible. Now with pamac (before with yaourt) I can use the root password, but I would prefer yay for the many options, the commands similar to pacman,, the reduced size in desktop-less systems
