### ISSUE TITLE
`yay -S` makes different result than `yay -G` then makepkg

### ISSUE THREAD

**Issue by palxex** [Jguer/yay#1116]
#### Affected Version
yay v9.4.2.r17.gb08e505 - libalpm v12.0.0

#### Issue
I'm trying to install compiz-core-git AUR on a deepin-manjaro machine, since I've installed same package on another machine, I thought it will be trivial, BUT it keeps fail and complain `Can not find package name : [==> Marco theme support disabled, rebuild with _use_marco=1 in the PKGBUILD if you want it]
` . After many tries( includes install/uninstall marco+-gtk2 - all failed, certainly) I tried another way: utilizing `yay -G` get the PKGBUILD, then mekepkg. I thought it will not work as the previous way, but it WORKS.

#### Steps to reproduce

1. yay -S compiz-core-git, always fail and complain `Can not find package name : [==> Marco theme support disabled, rebuild with _use_marco=1 in the PKGBUILD if you want it]
`
2. yay -G compiz-core-git, cd compiz-core-git, makepkg, the tar.bz2 builds well
3. I see no reason situation 1 and 2 should make difference.

Possible relevant info:
1. the package list on the success device:
[pkgs.succ.txt](https://github.com/Jguer/yay/files/3846376/pkgs.succ.txt)
2. the package list on the fail device: 
[pkgs.fail.txt](https://github.com/Jguer/yay/files/3846378/pkgs.fail.txt)

**Comment by Morganamilo** [comment]
It's probably because of https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=compiz-core-git#n84. Not only are they trying too set variables in the build function, but trying to tweak pkgname at runtime.

**Comment by palxex** [comment]
A question is, I just installed this aur successfully this August( not sure which version used that time, but should be latest, not git), and the aur.git shows the PKGBUILD was last changed in 2018. So it seems latest yay changes breaks it.

**Comment by Morganamilo** [comment]
> So it seems latest yay changes breaks it.

 Not necessarily, the breakage could come from upstream. Or given the pkgbuild modifies itself based on your system it could be that.

It's also possible it used to work with an older version of yay but not a newer one. But in any case, the pkgbuild does stupid things and is invalid. So I don't really care that yay fails to build it.

**Comment by Jguer** [comment]
If the PKGBUILD requires human hands to build
and the maintainer was a bit unskilled
Let it exalt:
the AUR helper is without guilt
