### ISSUE TITLE
Enhancing building speed by changing compression type

### ISSUE THREAD

**Issue by es20490446e** [Jguer/yay#1119]
Be aware of [this](https://gitlab.manjaro.org/applications/pamac/issues/651).

**Comment by Morganamilo** [comment]
makepkg controls the compression type, not yay.

**Comment by es20490446e** [comment]
You can choose your own with:
`PKGEXT='.pkg.tar' makepkg`

**Comment by Morganamilo** [comment]
Yes ***you*** can. But it's not yay's job to configure makepkg for you. Or worse, override the pkgext you have configured.

**Comment by es20490446e** [comment]
As specimen from the above link:
![image](https://user-images.githubusercontent.com/9594332/69357973-62258b00-0c86-11ea-8e2a-4687b10400d0.png)
![image](https://gitlab.manjaro.org/applications/pamac/uploads/94c416f7bf23e45bb7c10ab242f83272/DeepinScreenshot_select-area_20190915032741.png)

Ideally that shall be changed on the default makepkg.conf, but if I'm the one bringing the discussion they won't listen to me.

**Comment by Morganamilo** [comment]
If you prefer speed over size you're free to change it. If you don't care about reproducability, go multicore. There's no default to please everyone. The default doesn't really matter as it's trivial to change and arch users are expected to know their own tools.
