### ISSUE TITLE
After repo Sync Install the package

### ISSUE THREAD

**Issue by now-im** [Jguer/yay#112]
After I got the news that Pacaur is being dropped, I was looking for a hassle-free AUR helper and this may just be the one.
Now, I am very much familiar with a feature that is not available here. When I do,
`yay -Syu google-chrome`
It only syncs the repo and ignored the package. Pacman does that and Pacaur can also do that. I know open source is not a very rewarding place but do consider my request. Thanks.

**Comment by Morganamilo** [comment]
Already in master my friend ;)

**Comment by now-im** [comment]
sweet :beer:

**Comment by now-im** [comment]
I know this is quite a busy time for you. This is not working in the latest version.

**Comment by Morganamilo** [comment]
Seems to work on my end. Could you give more detail?

**Comment by now-im** [comment]
After the last build in aur it works. That is why I deleted the comment.

**Comment by Morganamilo** [comment]
Ah right, didn't refresh so it was still there for me.
