### ISSUE TITLE
yay failed to build some packages from AUR when ~/anaconda3 exists.

### ISSUE THREAD

**Issue by c02y** [Jguer/yay#1124]
#### Affected Version

`yay v9.4.2 - libalpm v12.0.1`

#### Issue
yay faild to build some packages such as pycharm-eap from AUR when `~/anaconda3/` exists. existed with the following error message:
~~~
build/temp.linux-x86_64-3.7/_pydevd_bundle/pydevd_cython.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1
==> ERROR: A failure occurred in build().
    Aborting...
Error making: pycharm-eap
~~~
When I tried rename my `~/anaconda3` to `~/anaconda3.bak` and start `yay -Syu` to update the pycharm-eap, it is OK.

#### Steps to reproduce

1. use yay to update the package installed AUR, such as `yay -Syu`
2. it will download the latest version or pycharm-eap
3. it will try to build it and install

#### Output

~~~
>> yay -Pg
{
        "aururl": "https://aur.archlinux.org",
        "buildDir": "/home/chz/.cache/yay",
        "absdir": "/home/chz/.cache/yay/abs",
        "editor": "",
        "editorflags": "",
        "makepkgbin": "makepkg",
        "makepkgconf": "",
        "pacmanbin": "pacman",
        "pacmanconf": "/etc/pacman.conf",
        "tarbin": "bsdtar",
        "redownload": "no",
        "rebuild": "no",
        "batchinstall": false,
        "answerclean": "",
        "answerdiff": "",
        "answeredit": "",
        "answerupgrade": "",
        "gitbin": "git",
        "gpgbin": "gpg",
        "gpgflags": "",
        "mflags": "",
        "sortby": "votes",
        "searchby": "name-desc",
        "gitflags": "",
        "removemake": "ask",
        "requestsplitn": 150,
        "sortmode": 0,
        "completionrefreshtime": 7,
        "sudoloop": true,
        "timeupdate": false,
        "devel": false,
        "cleanAfter": false,
        "gitclone": true,
        "provides": true,
        "pgpfetch": true,
        "upgrademenu": true,
        "cleanmenu": true,
        "diffmenu": true,
        "editmenu": false,
        "combinedupgrade": false,
        "useask": false
}
~~~

**Comment by Morganamilo** [comment]
This doesn't sound like anything yay would cause. Did you try building it yourself first?

**Comment by c02y** [comment]
No, I never build packages installed from AUR by myself, I always updates them using yay.

This issue happened multiple times when I tried to update my packages installed from AUR. I cannot just rename `~/anaconda3` every time when it happens.

So I posted this issue here.

BTW:
Manjaro

What else info can I provide, please tell me.

**Comment by Morganamilo** [comment]
Well clearly the only information is does this happen when you build manually. Like I said I don't say any way yay could cause this.

**Comment by chrisjbillington** [comment]
Did you have an activated conda environment when you ran yay? If so then all that conda compilers, python interpreter etc are being used instead of system ones.

If you permenently added the conda bin directory to your path, an AUR package failing to build will be the least of your problems!

**Comment by c02y** [comment]
@chrisjbillington 
> Did you have an activated conda environment when you ran yay? If so then all that conda compilers, python interpreter etc are being used instead of system ones.

No, I didn't activate conda env

> If you permenently added the conda bin directory to your path, an AUR package failing to build will be the least of your problems!
Yes, my PATH contains `~/anaconda/bin`, and my python is `~/anaconda/bin/python` instead the system ones.

------------------
**UPDATE**:
I just use `yay -G pycharm-eap` and `makepkg -si` to build/install it manually, and the same error message still exists, so I believe this is not the problem of yay but makepkg or the PKGBUILD.

Anyway, after googling for a while I found out a lot of people have this exact problem, but no solution but removing `~/anaconda/bin` from PATH is found so far.

I'll close it for now, will update it once I found the solution.

**Comment by chrisjbillington** [comment]
There is no other solution - having `~anaconda/bin` in your path shadows many system tools, it's never a good idea. With a conda env active (or `~anaconda/bin` in your path), you simply can't do system administration. It's not a bug, the point of a conda environment is to modify the environment to be something it's not.

One thing I've done when I was using conda was to alias ~/anaconda/bin/python to "python3". Then "python3" would start conda python, and I wouldn't have anything shadowed (other than "python3" which nothing uses since that's just a link to 'python' on Arch). That works pretty well.

Off topic, but what are you using conda for that you can't use system Python for? After moving from Ubuntu to Arch I found I didn't need conda anymore except for testing my code with other versions of things than what is on my system.

**Comment by c02y** [comment]
> Off topic, but what are you using conda for that you can't use system Python for? After moving from Ubuntu to Arch I found I didn't need conda anymore except for testing my code with other versions of things than what is on my system.

I started to use `~/anaconda/bin` in my PATH several years old, since when I use relatively old Linux distros(such as CentOS/RedHat) in my company, I cannot change the system, and I found some tools in the repo are very old(such as fish/tmux/tig/emacs/vim), in order to use new version of those tools, I have to manually compile/install from the latest source code, and it may fail because of some dependencies, then I found that it is very easy to install them using conda channel command, so I put `~/anaconda3/bin` in my PATH. 

Of cause I don't need it in my $PATH in some Linux distros such as Manjaro which currently I'm using, I'll try to set my PATH according to different distros in my configs of shells.
