### ISSUE TITLE
no candidate packages found when trying to clean cache using paccache

### ISSUE THREAD

**Issue by andersfylling** [Jguer/yay#1129]
#### Affected Version
yay v9.4.2 - libalpm v12.0.1

#### Issue
My yay cache is closing to 20GiB and I would really like to clean it up. It seems that paccache is the recommended way[[772](https://github.com/Jguer/yay/issues/772)]. But trying to apply it yields the error `no candidate packages found for pruning".

#### Steps to reproduce
1. paccache --cachedir="/home/anders/.cache/yay" -d
2. paccache --cachedir="/home/anders/.cache/yay" -dk 0
3. paccache --cachedir="/home/anders/.cache/yay" -dk 1

The output is the same when ran as root: `sudo paccache --cachedir="/home/anders/.cache/yay" -d`.

#### Output
`no candidate packages found for pruning`

**Comment by AndrejKorshikov** [comment]
Try something like this:
`for dir in $(ls --directory /home/anders/.cache/yay/*/); do paccache --dryrun --cachedir "${dir}" --keep 0; done`

or this:
`find "/home/anders/.cache/yay" -maxdepth 1 -mindepth 1 -type d -print0 | xargs -0 --max-lines=1 paccache --dryrun --keep 0 --cachedir`

Paccache does not look at subfolders, as far as I know.

**Comment by Morganamilo** [comment]
The best solution is to set PKGDEST, not loop paccache.
