### ISSUE TITLE
binutils and base-devel didn't include in the manual

### ISSUE THREAD

**Issue by Javanmardi** [Jguer/yay#1130]
This is not a real issue, it is more than a request. You can skip it.
For someone (like me) who just came to Arch Linux or any Arch base distro, yay is not familiar or ever used before and beside the fact that the recommended way to install is the git one I think you should include dependencies as well. 
I faced the problem on Manjaro 18.1.3 and 18.0 which this two dependencies weren't installed and the git's readme didn't include them. Please add it to the installation section:

`$ sudo pacman -S binutils`
`$ sudo pacman -S base-devel`

**Comment by parkerlreed** [comment]
It's assumed if you are dealing with the AUR at all that you have those packages already. 

Also binutils is part of base-devel.

**Comment by Javanmardi** [comment]
Sure, as I told I am new to Arch and I wanted some pre-built proprietary binaries. So, I guessed they do not need it.

> Also binutils is part of base-devel.

My bad!

**Comment by Jguer** [comment]
This seems like a good beginner issue , all that's needed is  a small text under Installation linking to the AUR page and drawing attention that base-devel is assumed install (but don't tell directly people to install it.)
