### ISSUE TITLE
index number of aur updates list is reverse

### ISSUE THREAD

**Issue by Superkeyv** [Jguer/yay#1134]
#### Affected Version

yay v9.4.2 - libalpm v12.0.1
#### Issue
while using cmd `yay -Syu ` to upgrade system.
for the aur package. the index of aur updates list is reverse.

I think the bug located line 357 of `/upgrade.go`

#### Steps to reproduce

1.
2.
3.

#### Output

:: Searching AUR for updates...
:: 2 Packages to upgrade.
2  aur/cutecom             0.50.0-0   -> 0.51.0-1
1  aur/oda-file-converter  19.8.0.0-2 -> 20.8.0.0-2
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)

**Comment by parkerlreed** [comment]
https://github.com/Jguer/yay/issues/975
