### ISSUE TITLE
Asking for all Y/n permission at once

### ISSUE THREAD

**Issue by now-im** [Jguer/yay#114]
This was one of the killer features that attracted advanced users towards `pacaur`. Previewing `PKGBUILD` and other permission should be asked altogether so that I can let my PC compile and install the application swhile doing other things.

**Comment by Jguer** [comment]
Already implemented in master, you can check the results here #109

**Comment by now-im** [comment]
Man what are you? Terminator!
Next one will be one hell of a release. Looking forward to it.

**Comment by Jguer** [comment]
For that you have to thank @Morganamilo, who implemented a lot of these changes while I was away

**Comment by now-im** [comment]
Thanks to everyone involved. I was quite worried to see pacaur shut down. Yaourt is not a very good project for regular users.
Other project is not even close. I used arch wiki to find an alternative. This was listed as the last entry when I lost all hopes. But this is just great. When its major development will be over this may even be better than pacaur.

**Comment by Morganamilo** [comment]
There are other good helpers out there too. I hear good things about Trizen. Aurutils seems to be good too although it's not for me.

Personally I'm working towards a Pacaur clone of sorts. My goals are:
- single binary
- ability to replace pacman for all usage
- easy to use, no setup required
- minimal user interaction

Other helpers have different goals so may not me for you but still, I think saying they are not even close does them a disservice.

**Comment by now-im** [comment]
Trizen depends on haskell and somehow I don't like it and the process is rather slow. Too much user intersection needed.
Yay is about ready to replace pacaur anyway. It is really sad to such a great open source project to die because there was no momentary incentive. 
Keep up guys. Thanks a lot.

**Comment by AladW** [comment]
>Trizen depends on haskell

Never thought I'd see the day someone confuses Perl with Haskell...
