### ISSUE TITLE
Add dependencies for installation

### ISSUE THREAD

**Issue by hofmannu** [Jguer/yay#1142]
Actually not an issue of `yay` itself but more of the documentation here. I think there are some dependencies to install `yay`. Maybe we should add them into the documentation. I just tried to install it on a fresh system and got the following error when I tried to run `makepkg -si`:

    ==> ERROR: Cannot find the fakeroot binary.
    ==> ERROR: Cannot find the strip binary required for object file stripping.

which indicates that `fakeroot` is one dependency. I just installed the whole `base-devel` group and then it ran through, so I am not sure what the core dependencies are but it would be good to have them listed here in the documentation within the section Installation. Also good to know for people who use scripts to set up their systems since it defines the installation order.

**Comment by Jguer** [comment]
https://wiki.archlinux.org/index.php/Arch_User_Repository#Getting_started
https://wiki.archlinux.org/index.php/PKGBUILD#makedepends
> Note: The group base-devel is assumed to be already installed when building with makepkg. Members of this group should not be included in makedepends array.
`base-devel` is a per-requesite

**Comment by UnlimitedCookies** [comment]
Sorry to bring up this stale issue again.

Why don't we add `fakeroot` to the dependencies? It is required for the core functionality of yay.

**Comment by Jguer** [comment]
https://wiki.archlinux.org/index.php/Arch_User_Repository#Getting_started
https://wiki.archlinux.org/index.php/PKGBUILD#makedepends

As written on the wiki:

> Note: The group base-devel is assumed to be already installed when building with makepkg. Members of this group should not be included in makedepends array.

It's required for a core functionality of makepkg and the group base-devel is assumed to be already installed when building with makepkg. I'm ok with adding a note to the `README.md` reminding users to have `base-devel` installed
