### ISSUE TITLE
Installation from SVN repo fails, probably because of proxy

### ISSUE THREAD

**Issue by elpres** [Jguer/yay#1143]
#### Affected Version
```
$ yay -V
yay v9.4.2 - libalpm v12.0.1
```

#### Issue

When trying to install a package that involves cloning an SVN repo, a connection error occurs which aborts the installation:

```
$ yay -S ttf-mac-fonts
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur: 1]  ttf-mac-fonts-20100901.134-1

:: Downloaded PKGBUILD (1/1): ttf-mac-fonts
:: Parsing SRCINFO (1/1): ttf-mac-fonts
==> Making package: ttf-mac-fonts 20100901.134-1 (Wed 08 Jan 2020 12:38:01 CET)
==> Retrieving sources...
  -> Cloning ttf-mac-fonts svn repo...
svn: E170013: Unable to connect to a repository at URL 'https://svn.code.sf.net/p/macbuntu/code/Macbuntu/fonts'
svn: E000111: Error running context: Connection refused
==> ERROR: Failure while downloading ttf-mac-fonts svn repo
    Aborting...
Error downloading sources: ttf-mac-fonts
```

My network is behind a proxy, which is configured properly everywhere where I encountered problems so far (environment variables, keeping them when running `sudo`, etc.). Cloning this particular repository also works by itself:

```
$ svn checkout https://svn.code.sf.net/p/macbuntu/code/Macbuntu/fonts
A    fonts/mac
A    fonts/gbk
A    fonts/latin
...
```

**Comment by Jguer** [comment]
See if this fixes your issue https://wiki.archlinux.org/index.php/Makepkg#Makepkg_fails_to_download_dependencies_when_behind_proxy

**Comment by elpres** [comment]
Well, the `env_keep` solution has been in place for a long time since it's needed whenever you do anything using `sudo`, and the default `XferCommand` uses wget that is configured to use the proxy through /etc/wgetrc. This SVN cloning issue is the only thing that doesn't work at the moment, everything else (installing from AUR using `.deb`s, GIT checkouts, etc.) works fine.
