### ISSUE TITLE
Local is newer than AUR (package "natron" and "openfx-*")

### ISSUE THREAD

**Issue by TheMrNomis** [Jguer/yay#1148]
#### Affected Version

yay v9.4.2.r20.g9e2713e - libalpm v12.0.1

#### Issue

Hi,
This is not an issue *per se*, but more of a suggestion.
The `natron` package (along with its dependencies `openfx-arena`, `openfx-gmic`, `openfx-io` and `openfx-misc`) have recently been updated from `v2.3.15 RC 10-1` to `RC 13-1`.
Yay however fails to see the the RC 13 as an update because the version string does not follow the same exact formatting : RC 10 is written as `2.3.15_rc.10-1` whereas RC 13 is `2.3.15_rc13-1` (notice the missing dot between "rc" and the following number).

I understand perfectly that this makes sense in a string comparison (`"2.3.15_rc.10-1" > "2.3.15_rc13-1"`) but IMO that does not make sense in a version number comparison.

Would it be possible to do the comparison on a "canonical form" of the version number string that would be robust to small typographic changes like this?

#### Steps to reproduce

1. have `natron v2.3.15_rc.10-1` installed
2. `$ yay -Syu`

#### Output

```
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
 -> coin-or-ipopt: local (1:3.12.13-1) is newer than AUR (3.13.0-1)
 -> natron: local (2.3.15_rc.10-1) is newer than AUR (2.3.15_rc13-1)
 -> openfx-arena: local (2.3.15_rc.10-1) is newer than AUR (2.3.15_rc13-1)
 -> openfx-gmic: local (2.3.15_rc.10-1) is newer than AUR (2.3.15_rc13-1)
 -> openfx-io: local (2.3.15_rc.10-1) is newer than AUR (2.3.15_rc13-1)
 -> openfx-misc: local (2.3.15_rc.10-1) is newer than AUR (2.3.15_rc13-1)
 -> Missing AUR Packages:  GoticoAntiqua-git  i3blocks-gaps-git  intel-vtune-amplifier  python-sip-pyqt5  python2-dukpy  python2-gmpy2  python2-pywavelets  python2-sip  python2-sphinx_rtd_theme  python2-whoosh  xf86-input-keyboard  xf86-input-mouse  xorg-server-xdmx
 -> Orphaned AUR Packages:  ect
 -> Flagged Out Of Date AUR Packages:  firefox-nightly  koreader-bin
 there is nothing to do
```

**Comment by aayush420** [comment]
Same problem, but with different packages

**Comment by yesenarman** [comment]
This is related to how libalpm's `alpm_pkg_vercmp` function compares version strings. The current algorithm seems to be borrowed from RedHat's RPM version compare.

I see a few possible ways to fix this:
1. Report this issue to libalpm developers and wait for it to be fixed in libalpm. But I personally doubt that libalpm devs will be willing to change this behavior, since it's not really broken outside AUR usecase.
2. Write custom version compare function in yay.
    - it can use the same algorithm as libalpm but also include a fix for this issue
    - or it can use it's own algorithm, e.g. it can be based on current `getVersionDiff` function
3. Somewhat hacky solution is normalizing version strings (e.g. always remove dot after 'rc') and then passing them to libalpm for comparison.
