### ISSUE TITLE
[Feature Request] Add support for the pacman files (-F) database

### ISSUE THREAD

**Issue by Java-C0der** [Jguer/yay#1150]
#### Affected Version
yay v9.4.2 - libalpm v12.0.1

#### Issue
If you want to know which remote packages own the file <code>foo</code>, you can do <code>pacman -F foo</code>. Additionally, to know which files the remote <code>Foo</code> program owns, you can do <code>pacman -Fl Foo</code>.

However, this behavior doesn't currently work with AUR packages, and it would be really nice to have this option, since, currently, if you need to know which files are owned by a remote AUR package, you have to visit its AUR page. Also, as far as I know, there is currently no way to know which remote AUR packages own a certain file.

This could be implemented by, for instance, adding something like a <code>aur.files</code> database to <code>/var/lib/pacman/sync</code>, which is how pacman does it: for each repository, it has a <code>.db</code> file for the sync (<code>-S</code>) database and a <code>.files</code> file for the files (<code>-F</code>) database.

Ideally, at that point, running, for example, <code>yay -F --repo foo</code> would be the same as <code>pacman -F foo</code>, <code>yay -F foo</code> would query the <code>aur.files</code> database as well as all of the repositories' <code>.files</code> database, and <code>yay -F --aur foo</code> would only query the  <code>aur.files</code> database.

**Comment by Morganamilo** [comment]
This is impossible. How do you plan to generate the AUR files database?

**Comment by Java-C0der** [comment]
> This is impossible. How do you plan to generate the AUR files database?

I don't know how pacman handles this internally, but I think you could probably write a script to go to every package's AUR page and fetch its owned files. This seems like a patchy solution, I don't know if there's an API for this, but I do know that yay currently stores every (as far as I know) AUR package's name in <code>~./cache/yay/completion.cache</code>.

**Comment by Morganamilo** [comment]
Pacman can get the file list from the database or the package itself. Neither exist on the AUR.

**Comment by Java-C0der** [comment]
> Pacman can get the file list from the database or the package itself. Neither exist on the AUR.

Yup, you're right. I could've sworn I had seen a "package contents" tab on the AUR website, but I've just checked and it turns out that's only there for the arch packages website. Well, in my defense, both pages look incredibly similar. :stuck_out_tongue: 
So, yeah, it seems that there currently isn't any way to do this, unfortunately... What a shame, this would be a really nice addition.
Thanks for your time, though. :+1:

**Comment by JohanChane** [comment]
Try this. It works.

```bash
alias yayfgrep="yay -Sl aur | awk '{print $2}' | yay -Ql | grep -E -i"
yayfgrep  '/bin/goldendict$'
```

**Comment by IslandC0der** [comment]
@JohanChane thank you for your suggestion, but isn't that the same as `yay -Qo <file>`?
I was talking about a command that allowed me to see which aur package owns a given file, **without said aur package being installed on the system.**
But as @Morganamilo said, that's impossible, since there's no file database for aur packages. Most of them don't even download the compiled source, so I don't know how one would go about implementing this (unless they added a way for package maintainers to upload a list of all the files generated after they've locally built the package, or something).

**Comment by JohanChane** [comment]
@IslandC0der Sorry, I forgot that i have installed Goldendict. And '-Q' and '-F' are different.
