### ISSUE TITLE
yay -Syu should show the upgrademenu

### ISSUE THREAD

**Issue by cloutierjo** [Jguer/yay#1151]
#### Affected Version

$ yay -V
yay v9.4.2 - libalpm v12.0.1

#### Issue
yay -Syu should show the upgrademenu when the upgrademenu option is true. Currently I'm only able to make it show on the yay -Syuw which is not much useful since the upgrade install will download the unselected package in any case.

On another note, I find it strange that the upgrade menu is shown after downloading all the packages and not before. In particular, when doing a large upgrade (kde!) it can take a long time between starting the upgrade command and getting the upgrade menu to show. If it was shown before the only delay would be the repo update and after doing our selection, the upgrade can complete "unatended" until the end.

**Comment by Jguer** [comment]
`yay -Syu --combinedupgrade --save`

and then you can continue using `yay -Syu` as normal

**Comment by cloutierjo** [comment]
I don't actually want combined upgrade, I only want repo update with the menu. I'm manually updating my aur package separately.

So to rephrase this issu, `yay -Syu --nocombinedupgrade --upgrademenu` should show the upgrade menu and with the `w` option it should be shown before the download. Also, `w` shouldn't trigger the update after the download is down, `w` is meant to be download only.

**Comment by Jguer** [comment]
So, only repo?

`yay -Syu --repo` should do only repo packages

**Comment by cloutierjo** [comment]
In fact, the actual solution to make it work as I want is to do `yay -Syu --repo --upgrademenu --combinedupgrade` does it really make sense to ask the combineupgrade but only with the repo package only to get the upgrade menu that is a completely unrelated option to the other two? It's possible to reduce that line by doing `yay -Syu --upgrademenu --combinedupgrade --save` and then  `yay -Syu --repo` for the following time, but I believe that's a work around for a real bug in the --upgrademenu option.

Second, the issue of the `w` option with `nocombinedupgrade` can only lead to errors by installing packages when the user only meant to download them or worst corrupted system if he cancels the update in the middle when he sees that the update is running and not only the download.

**Comment by Morganamilo** [comment]
The way yay works `--combinedupgeade` actually means: "also handle repo upgrades instead of simply letting pacman handle them".

That's why you need the flag for the upgrade menu to handle repo packages.

Yay also does not currently handle the -w flag. That's why it's just basically ignored.

**Comment by cloutierjo** [comment]
OK, I do understand that, and reading back the man pages clearly state that "This means the upgrade menu and pkgbuild review will be performed after the sysupgrade has finished." Yet it doesn't feel intuitive. I would let this open as feature requests to improve the usability. I could also add a separate issue to handle the -w option.

**Comment by simepy** [comment]
Hi,

So..., do have some way for print the `upgrademenu` without `--combinedupgrade` or other option, just with `yay --Syu` line `yaourt`

Thanks
