### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by Manu-sh** [Jguer/yay#1153]
`fakeroot`, `binutils` (strip) and `make` packages are also required but `makepkg -si` only ask to install `go` (and also a compiler gcc? is required)

**Comment by Kattus** [comment]
All these are part of base-devel, which is assumed you have when building packages, they should not be listed as dependencies.

https://wiki.archlinux.org/index.php/Arch_User_Repository#Prerequisites

**Comment by Manu-sh** [comment]
mmh okay
