### ISSUE TITLE
Yay does not persist edited PKGBUILDs for devel packages

### ISSUE THREAD

**Issue by otaj** [Jguer/yay#1156]
#### Affected Version
`yay v9.4.3.r0.g87fcfbf - libalpm v12.0.1`

#### Issue
Hi,

this is probably a feature request (and not a bug). I have a devel package (git version, more specifically [faiss-cuda-git](https://aur.archlinux.org/packages/faiss-cuda-git/), which allows setting GPU architecture of your hardware in order to speed-up builds (without being set, it builds for all GPU architectures supported by said package, not your hardware). When I perform install using `--editmenu` flag (and edit it to specific architecture), the edit is saved for the current build (as should be). However, next time I update the package using `yay -Syu --devel` (and don't edit `PKGBUILD`, since I expect the edit on clean install to be persistent), it uses "stock" `PKGBUILD` douwnloaded from AUR.

I believe it would be beneficial, to use this edited PKGBUILD, since the version in AUR did not change and the update is happening solely due to original git repo being updated.

It is entirely possible, that `yay` has a switch to do so and I have not discovered it yet. If that is the case, please point me to it

#### Steps to reproduce
1. Install devel package and edit PKGBUILD using yay facilities
2. Perform devel update sometime in the future, when the package is NOT updated in AUR, however the underlying repo is updated and therefore update is triggered.
3. Do not invoke the editmenu, because it is believed (in fact known, I am maintainer of the aforementioned package), that `PKGBUILD` was not updated

#### Current behavior
Step 3 uses stock `PKGBUILD` form AUR

#### Expected behavior
Step 3 should use edited `PKGBUILD` from building the package the first time

#### Config
<details markdown=1>
<summary markdown=1>

`yay -Pg`
</summary>

```
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/otaj/.cache/yay",
	"absdir": "/home/otaj/.cache/yay/abs",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"batchinstall": false,
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "yes",
	"sudobin": "sudo",
	"sudoflags": "",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": false,
	"timeupdate": false,
	"devel": true,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false
}
```
</details>

**Comment by chrisjbillington** [comment]
I may be wrong, but I believe you can do a git commit in `.cache/yay/<pkgname>` after making your edit, and then next update yay will not bomb out your changes with its `git pull`, which is what I think it is doing. This will even merge your changes when the PKGBUILD does change.
