### ISSUE TITLE
Store built & installed package in /var/cache/pacman/pkg

### ISSUE THREAD

**Issue by afg984** [Jguer/yay#116]
It would convenient for users to downgrade packages or distribute built packages if they are stored (copied) to `/var/cache/pacman/pkg`

I'm willing to implement, are there other thoughts?

**Comment by Morganamilo** [comment]
I've been a bit busy recently so I haven't really been working on Yay. One of the things in progress though it to not rebuild already built packages. Along with that I'd also like to change the default build dir from `/tmp` to `~/.cache`.

That should act similar to Pacman's caching. I don't think storing packages in `/var/cache/pacman/pkg` would actually be detected by Pacman unless we also had a repo to go with it.

**Comment by Jguer** [comment]
I'm all for changing the default build dir to ~/.cache for RAM safety reasons.

> That should act similar to Pacman's caching. I don't think storing packages in /var/cache/pacman/pkg would actually be detected by Pacman unless we also had a repo to go with it.

Seems to be the best approach in relation to this. Pains me a bit that this has to be done through a priviledged system call though

**Comment by afg984** [comment]
> Along with that I'd also like to change the default build dir from /tmp to ~/.cache.

I've ran into memory issues while building under `/tmp`, but also have experience of speeding up build times by operating on RAM instead of HDD (think of large projects like gcc, chromium)

Given that `buildDir` is configurable, `~/.cache` does seem like a safer default.

> Pains me a bit that this has to be done through a priviledged system call though

Considering that running `pacman -U` already requires root privilege, I don't think it's too bad :)

FYI, `pkgbuilder` and `aura` stores installed packages in `/var/cache/pacman/pkg`

**Comment by Morganamilo** [comment]
Caching is implemented in #152. Forgot to link from there.
