### ISSUE TITLE
Error cloning: destination path already exists and is not an empty directory

### ISSUE THREAD

**Issue by AlexWayfer** [Jguer/yay#1163]
#### Affected Version

```
yay v9.4.3 - libalpm v12.0.1
```

#### Steps to reproduce

1. `yay -S --needed yay`

#### Output

```
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur: 1]  yay-9.4.4-1

error cloning yay: fatal: destination path 'yay' already exists and is not an empty directory.
```

#### Work-around

Add `--cleanmenu`.

**Comment by Morganamilo** [comment]
Assume the same as #1161

**Comment by AlexWayfer** [comment]
I didn't think that explicit command for cache clean the same as update error due to updating a repo, but if you're sure — feel free to close. I resolved this issue by mentioned work-around, but I guess there may be non-one-time issues.

**Comment by mr-karan** [comment]
For people arriving on this via their search results:  a package was being mishandled and `yay -Sc` didn't clear the package in `$HOME/.cache/yay`. I had to manually `rm -rf ` it anf then it worked.

**Comment by Felipe-1980** [comment]
fatal: destination path 'projeto-landing-page' already exists and is not an empty directory.
preciso de ajuda
