### ISSUE TITLE
`yay --devel` doesn't do anything

### ISSUE THREAD

**Issue by dschrempf** [Jguer/yay#1165]
#### Affected Version
yay v9.4.4 - libalpm v12.0.1
(sorry not the git version)

#### Issue
`yay --devel` doesn't do anything; no output; return value 0.

I don't have a custom yay config.

`yay -Syu --devel` works as expected.

(maybe this is not a bug, but since I am always using `yay` without command arguments, I expected that it should work with the `--devel` flag alone!)

Edit: I was too fast. I executed `yay -Y --gendb`, and now the updates are not shown anymore. So `yay -Syu --devel` does also not work as expected. Maybe related to #902 or #1016 ?

**Comment by Jguer** [comment]
`yay` is `yay -Syu`, it's a shortcut but `yay --option` is `yay -Y --option`

**Comment by dschrempf** [comment]
OK, thank you. This is totally confusing. You/we may think of changing this behavior.

**Comment by Jguer** [comment]
`yay <package1> <package2> ` is yay/yogurt mode `-Y`, meaning `yay -Y <package1> <package2> `. 

Yay without any Operation specified was always meant to be the `-Y` operation (like yaourt did for example)

Then `yay` for `yay -Syu` was added as an inheritance for pacaur users. Let's just say the conjugation of both has never been harmonious. 

What I've thought of doing is continue to follow `-Syu` if no targets are specified as I think not many people use `yay --gendb` or `yay -c` as replacements for `yay -Y --gendb` or `yay -Yc`

**Comment by Jguer** [comment]
Just pushed a branch that implements this proposed behaviour

**Comment by Morganamilo** [comment]
I don't like this at all. I frequently use `yay --foo --save` and I also see it recommended/recommended it myself online.

**Comment by Jguer** [comment]
`yay --foo --save` will still work this way, it will just trigger an update after.

But I do understand it's a breaking change for current behavior but as well, I understand the point of this issue. The compromise seems even worse which would be reverting to `-Y` if `--save` is present :sweat_smile:

**Comment by Morganamilo** [comment]
I think how it works now is perfectly fine. I've never seen anybody complain about it before. I don't want to make this change just because it confused one person at first.

**Comment by dschrempf** [comment]
Hi, I understand that the current behavior is, nearly always, the most user-friendly. I use just `yay` most of the time, and I am done with it. On the other hand, it is also highly inconsistent. I am sure that I am not the only user who was hit by this inconsistency. Maybe, I am the only one who filed an issue.

Another fix would be to always explicitly require an operation such as `Y`, or `S` if an argument such as `devel` is provided. This would not break the behavior of `yay` alone, but of course many other scripts using `yay --devel`, and expecting to use `yay -Y --devel`.

At the very least, we should document this behavior. I just checked, and it is documented very well in the `man` page, and also on the `--help` output. One could move the two respective sentence from the bottom of the `--help` output to the `Usage` part, though.

Thanks @Jguer for providing `yay`, it is by far the user-friendliest AUR helper I have ever used!

**Comment by Jguer** [comment]
There's no quorum on the issue, we'll close it. I'll happily review doc changes though

**Comment by dschrempf** [comment]
I just set out to add some documentation on this, but saw that it is very well documented. I only changed the help message, feel free to accept the pull request, or not! While working on this and reading through the documentation I was wondering if `yay --devel`, which is `yay -Y --devel` does anything at all? Because, if `yay --devel` doesn't do anything, there should be an error message, and not a return code 0. Maybe this is the root of the confusion?

**Comment by Jguer** [comment]
`yay -Y --devel` / `yay --devel` set the `--devel` update flag to True which can then be used with `--save` to make it permanent. Although fruit of accidental design `yay -Y <options> --save` has been the way of saving settings for many users
