### ISSUE TITLE
When a -git package is installed and the AUR version have a longer hash than local one, consider storing and comparing to the longer hash to avoid rebuild/reinstall

### ISSUE THREAD

**Issue by Porkepix** [Jguer/yay#1168]
#### Affected Version
yay -V
yay v9.4.4 - libalpm v12.0.1

#### Steps to reproduce

1. Have the `dino-git` package installed from previously (https://aur.archlinux.org/packages/dino-git/)
2. Run a `yay -Syu` (yay is configured to automatically check and upgrade ` -git` packages

#### Output
yay want to upgrade `dino-git`:
`1  aur/dino-git             r640.3b0a27e-1 -> r640.3b0a27e1-1`

Problem is, if you check the last commit on the repo, the full hash is `3b0a27e14bcce3a06f0ac1199bb0acb5c3434444`.
For some reasons, the local package use and display one less digit so that the AUR updated formula have an additional `1`. This result in yay thinking there is an update to do when comparing versions, downloading all build dependencies, installing those, downloading the sources and preparing to build… to finally skip build and reinstalling package because only at that point it notices it's trying to build the exact same hash as we already have installed.

```
==> Making package: dino-git r640.3b0a27e1-1 (Thu 23 Jan 2020 06:25:14 AM CET)
==> Retrieving sources...
  -> Updating dino git repo...
Fetching origin
==> Validating source files with sha512sums...
    dino ... Skipped
cmake not satisfied, flushing install queue
==> Making package: dino-git r640.3b0a27e1-1 (Thu 23 Jan 2020 06:25:16 AM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating dino git repo...
Fetching origin
==> Validating source files with sha512sums...
    dino ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of dino git repo...
Cloning into 'dino'...
done.
==> Starting pkgver()...
==> Updated version: dino-git r640.3b0a27e-1
==> Sources are ready.
==> Making package: dino-git r640.3b0a27e-1 (Thu 23 Jan 2020 06:25:21 AM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Sources are ready.
==> dino-git-r640.3b0a27e-1 already made -- skipping build
==> Found git repo: github.com/dino/dino
loading packages...
warning: dino-git-r640.3b0a27e-1 is up to date -- reinstalling
```

**Comment by Morganamilo** [comment]
That's an issue with the package. They're the one who sets the version format.

**Comment by Porkepix** [comment]
Can't yay consider the long full hash as a fallback?

**Comment by Morganamilo** [comment]
Again, the package sets the version. It's just a string.
