### ISSUE TITLE
Proposal: have yay -Ps take a number to print longer list of largest packages

### ISSUE THREAD

**Issue by mortdeus** [Jguer/yay#1169]
I apologize if this isn't the correct way to submit proposals, but I was wondering if it was possible if we could perhaps have yay -Ps take a number or -v(-vv & -vvv) to make the list of "ten largest packages" longer. Or perhaps it would be cool if we could use slice indexing yay -Psv="[10-50]" to show the top 40? The problem im having right now is trying to manage the size of my archlinux install on a chromebook. And as you can see from this output most of the top ten largest packages are things i need. (including the noto fonts for a project im working on)

```
➜  ~ yay -Ps
Yay version v9.4.3.r0.g87fcfbf
===========================================
Total installed packages: 1137
Total foreign installed packages: 99
Explicitly installed packages: 335
Total Size occupied by packages: 6.0 GiB
===========================================
Ten biggest packages:
linux-firmware: 518.2 MiB
noto-fonts-extra: 321.9 MiB
noto-fonts-cjk: 294.4 MiB
google-chrome: 210.5 MiB
rust: 210.4 MiB
gcc-libs: 149.5 MiB
gcc: 144.8 MiB
clang: 98.3 MiB
noto-fonts: 91.2 MiB
webkit2gtk: 87.0 MiB
===========================================
:: Querying AUR...
 -> Missing AUR Packages:  xf86-input-keyboard
 -> Orphaned AUR Packages:  aseprite-darkflat-theme
`
```

**Comment by andykras** [comment]
`expac -HM '%m %n' | sort -n | tail -20`
