### ISSUE TITLE
RFC: Improve the creation of new lines

### ISSUE THREAD

**Issue by GloverDonovan** [Jguer/yay#117]
Hello,

I frequently come across commands that don't output the new line character when executed. I was going to make a pull request to fix the ones I noticed, but it looks like a lot of the messages have already been changed now (not sure if all of them use new lines, though).

Example of some older code that didn't use a new line (and therefore messed with terminal output):

```go
if len(q) != len(pkgName) {
    fmt.Printf("Some packages from list\n%+v\n do not exist.", pkgName)
}
```

One solution would be to just use `fmt.Println` everywhere. Another would be to create your own print functionality that automatically adds new lines as needed, similar to what I do [here](https://github.com/GloverDonovan/mica/blob/d87122b64782cc14066221b5fdd16ab59de9a0df/src/mica/classes/printer.cr#L51). Yet another solution would be to just test all possible output combinations for a new line character at the end.

Thoughts?

**Comment by Morganamilo** [comment]
The best solution is to just use the correct Print/Println/Printf when appropriate. Yes a lot of messages have changed and some formatting still needs to be done. Feel free to suggest changes and create a pr. Just make sure to always test against master.

**Comment by Jguer** [comment]
With the new color changes and formatting going over on #109, I believe this issue has gotten better, still free to create purely display pull requests.
