### ISSUE TITLE
Add TAR Support Back

### ISSUE THREAD

**Issue by mjruschak** [Jguer/yay#1173]
#### Affected Version
yay v9.4.4 - libalpm v12.0.1

#### Issue
Could the TAR support be added back?  --nogitclone option.  I found this really useful behind proxys.  It is nice to have alternatives for downloading dependencies.

Can this be reversed?  [PR](https://github.com/Jguer/yay/pull/1111)

**Comment by Morganamilo** [comment]
I don't really get how that would have helped. Tars were downloaded over https, now we git clone over https. Why do proxies not work now?

**Comment by Jguer** [comment]
even if it's refered as git@github (for example) in the PKGBUILD you can use
```
git config --global url."https://github.com/".insteadOf 'git@github.com:'
```

which should force it to use http

**Comment by mjruschak** [comment]
> I don't really get how that would have helped. Tars were downloaded over https, now we git clone over https. Why do proxies not work now?

It allowed me to pull in the sources without fussing with proxy, ssl chain issues specific to git.  On some proxies this can be a huge pain.  I believe it took the git program out of the equation all together but not 100% certain.  I just know in my particular situation it was used weekly.


> even if it's refered as git@github (for example) in the PKGBUILD you can use
> 
> ```
> git config --global url."https://github.com/".insteadOf 'git@github.com:'
> ```
> 
> which should force it to use http

I can try this.  I am just curious though and mean no disrespect.  Why remove it because of the assumption it was not often used? Especially if it was not harming anything.  I am just trying to understand if there was some other underlying cause that forced this decision?  Perhaps removing it brings benefits?  Was a shock today when my aliased command no longer worked :D

Appreciate the prompt replies and again great program!

**Comment by Morganamilo** [comment]
Every time we implemented something new we had to add checks all over to handle git and tar directories. Many of our features like diffs don't really work with tars, or take a lot of extra effort to implement compared to using git's built ins.

Also I've written a separate fetcher library that I may get around to merging at some point. It's written from the ground up with git in mind. It's a lot easier to write when you don't have to think about tars.

**Comment by mjruschak** [comment]
> Every time we implemented something new we had to add checks all over to handle git and tar directories. Many of our features like diffs don't really work with tars, or take a lot of extra effort to implement compared to using git's built ins.
> 
> Also I've written a separate fetcher library that I may get around to merging at some point. It's written from the ground up with git in mind. It's a lot easier to write when you don't have to think about tars.

That makes sense to me.  I will try fussing with my configuration to see if there is another way around the issue.   I am sure there is. I will also try the suggestion above tomorrow.  I understand why it was removed.

**Comment by mjruschak** [comment]
I have now fixed the issue in my git configuration.  Thank you also for the explanation as to why the tar support was removed. This issue can be closed.
