### ISSUE TITLE
Versioned dependencies not being found

### ISSUE THREAD

**Issue by acxz** [Jguer/yay#1177]
#### Affected Version
yay v9.4.4.r0.g3a5a6a7 - libalpm v12.0.1

#### Issue
When trying to install a package with a versioned dependency, the dependency is not being found.
For example in the package `gazebo-hg`, there is a dependency on `ogre=1.9`. This is provided by the `ogre-1.9` package on the AUR, but yay is not able to determine that `ogre-1.9` is the correct dependency it should pull.

#### Steps to reproduce

1. `yay -Syu gazebo-hg`

#### Output
```
==> Error: Could not find all required packages:
    ogre=1.9 (Wanted by: gazebo-hg)
```

**Comment by chrisjbillington** [comment]
Same thing here with [`tortoisehg`](https://aur.archlinux.org/packages/tortoisehg/). It depends on `mercurial>=5.3`, which is provided by [`mercurial-python3`](https://aur.archlinux.org/packages/mercurial-python3/), but yay can't grab the dependency automatically like it can for unversioned dependencies:

```bash
$ yay -S tortoisehg
:: There are 2 providers available for tortoisehg:
:: Repository AUR
    1) tortoisehg 2) tortoisehg-hg 

Enter a number (default=1): 
==> Error: Could not find all required packages:
    mercurial>=5.3 (Wanted by: tortoisehg)
```

**Comment by acxz** [comment]
Same thing happens with `python-mlflow`.

**Comment by Jguer** [comment]
It's hard to search for provides and this system needs to be redone for search on base term and then drilling down on provides, (which would be necessary for tortoise-hg `mercurial-python3`, which seems to not have the issue anymore) but I've added versioned packages in the dependency population if they exist, which fixes both packages that were failing
