### ISSUE TITLE
Remember --mflags on per-package basis

### ISSUE THREAD

**Issue by HaleTom** [Jguer/yay#1178]
### Feature request

Building `libc++`  without passing `--nocheck` has all 8 cores of my 8th gen i7 pinned to 100% for about half an hour.

Therefore, I need to build it with:

    yay -S --mflags --nocheck libc++

Is there a way to remember the `makepkg` flags on a per-package basis?

`yay v9.4.4 - libalpm v12.0.1`

**Comment by itsagoodbrain** [comment]
@HaleTom It's not exactly what you asked for, but what I did for your issue case was erase the check function from the PKGBUILD file and then commit it. 

I'm not sure if this is general for AUR helpers or yay specific but I haven't seen it advertised much. Found it in this issue https://github.com/Jguer/yay/issues/745#issuecomment-426701907

I've definitely found it useful for avoiding annoyances like the one you mention.
