### ISSUE TITLE
PKGBUILD does not exist

### ISSUE THREAD

**Issue by purringcat248** [Jguer/yay#1179]
#### Affected Version
idk, but it's the latest version as of 5/2/2020 at 15:12 PM

#### Issue

The repository apparently doesn't contain the PKGBUILD file, so I can't build it. Do I have to download PKGBUILD manually or something?

#### Steps to reproduce
1. `git clone https://github.com/Jguer/yay.git`
2. `cd yay`
3. `makepkg -si`

#### Output
1. `Cloning into 'yay'...'`
    `remote: Enumerating objects: 47, done.`
    `remote: Counting objects: 100% (47/47), done.`
    `remote: Compressing objects: 100% (36/36), done.`
    `remote: Total 5765 (delta 23), reused 23 (delta 10), pack-reused 5718`
    `Receiving objects: 100% (5765/5765), 4.96 MiB | 4.05 MiB/s, done.`
    `Resolving deltas: 100% (3403/3403), done.`

2. no output
3. `==> ERROR: PKGBUILD does not exist.`

**Comment by purringcat248** [comment]
on the steps to reproduce it's supposed to say `git clone https://github.com/Jguer/yay/yay.git` but i forgot to put git clone before "https://github.com/Jguer/yay"

**Comment by parkerlreed** [comment]
You need to clone the AUR git repo.

https://aur.archlinux.org/packages/yay/

**Comment by purringcat248** [comment]
I've cloned the package from the link you gave but there's only pkgbuild in there. I'm assuming I'm supposed to move that to the folder with all the other files?

**Comment by parkerlreed** [comment]
You need to install `base-devel`. No need to move any files. That PKGBUILD will pull in the files automatically with git.

Please follow the Arch wiki guide for building packages with makepkg https://wiki.archlinux.org/index.php/Arch_User_Repository

**Comment by purringcat248** [comment]
gonna install base-devel now, lemme see if this works
