### ISSUE TITLE
Manpage incorrect

### ISSUE THREAD

**Issue by Krutonium** [Jguer/yay#1180]
#### Affected Version
Doesn't matter the version, but `yay v9.4.4 - libalpm v12.0.1`
Also verified on `yay v9.4.4.r0.g3a5a6a7 - libalpm v12.0.1`
#### Issue

The Manpage for yay is incorrect. 

https://github.com/Jguer/yay/blob/master/doc/yay.8#L91

-c does not provide completion, it actually offers to remove all unneeded packages.

![yay -c_042](https://user-images.githubusercontent.com/3945538/74002514-4eacc680-493d-11ea-94c7-9abfb7f07621.png)

#### Steps to reproduce

1. yay -c

**Comment by Morganamilo** [comment]
Two lines up: `.SH SHOW OPTIONS (APPLY TO \-P AND \-\-SHOW)`

**Comment by Krutonium** [comment]
I'm an idiot.
