### ISSUE TITLE
Feature Request: Optionally disable IPv6 usage

### ISSUE THREAD

**Issue by mmoya** [Jguer/yay#1181]
Add a flag and/or a configuration option for disabling IPv6 when resolving hostnames.

**Comment by Jguer** [comment]
This seems something related to your setup. We don't touch the default network stack

**Comment by mmoya** [comment]
I don't get what you mean with 'touching the default nework stack'. Sometimes you have dual stack systems but some applications only support IPv4.

My feature request was meant to 'disable any IPv6 support' at the application level.

For example, you can add `-o Acquire::ForceIPv4=true` to `apt-get` and it will use IPv4 no matter if IPv6 is available in the underlying system. You can see a use case in [this Unix SE question][1].

You can see there is an option to use `/etc/gai.conf` for disabling IPv6 for certain hosts but that would be at the network level, not at the application level, requiring keeping an up-to-date list of network addresses for some mirrors.

[1]: https://unix.stackexchange.com/q/9940/5576
