### ISSUE TITLE
Question: Replace package provider

### ISSUE THREAD

**Issue by maujim** [Jguer/yay#1182]
#### Affected Version
yay v9.4.4 - libalpm v12.0.1
Note: this is on 5.4.6-2-MANJARO

#### Issue
Installed [`ros-melodic-desktop-full`](https://aur.archlinux.org/packages/ros-melodic-desktop-full/) a few weeks ago and one of the (indirect) dependencies is the `gazebo` package. This has two providers: [`gazebo`](https://aur.archlinux.org/packages/gazebo/) and [`gazebo-hg`](https://aur.archlinux.org/packages/gazebo-hg/). 

At the time, the `gazebo` build was failing for me but the `gazebo-hg` worked fine so I went with that one. However, the issue has since been fixed and I want to switch back to `gazebo`. Is there a way to do this using `yay` with uninstall and reinstalling all my packages that depends on `gazebo`?

**Comment by acxz** [comment]
@maujim I believe you can just run `yay -Syu gazebo` and that will prompt you `gazebo and gazebo-hg are conflicting packages, remove gazebo-hg [y/n]?` Pressing `y` will install `gazebo` and remove `gazebo-hg`. This is true for all packages for which their `conflicts=()` field matches.

**Comment by Jguer** [comment]
@acxz is correct on this
