### ISSUE TITLE
Issue using Yay to install Virtscreen 9.4.4 on Manjaro XFCE (5.4.14-2) (Works with Yaourt)

### ISSUE THREAD

**Issue by ghost** [Jguer/yay#1184]
#### Affected Version

yay v9.4.4 - libalpm v12.0.1

#### Issue

Trying to install the tool "virtscreen", I have logged an issue there also (https://github.com/kbumsik/VirtScreen/issues/53)

#### Steps to reproduce

yay -S virtscreen (clean build, no diffs shown)

#### Output

`==> Making package: virtscreen 0.3.1-1 (Mon 10 Feb 2020 09:43:34 GMT) ==> Retrieving sources... -> Cloning src git repo... Cloning into bare repository '/home/x/.cache/yay/virtscreen/src'... remote: Enumerating objects: 8, done. remote: Counting objects: 100% (8/8), done. remote: Compressing objects: 100% (8/8), done. remote: Total 915 (delta 2), reused 1 (delta 0), pack-reused 907 Receiving objects: 100% (915/915), 8.25 MiB | 5.02 MiB/s, done. Resolving deltas: 100% (575/575), done. ==> Validating source files with md5sums... src ... Skipped ==> Making package: virtscreen 0.3.1-1 (Mon 10 Feb 2020 09:43:38 GMT) ==> Checking runtime dependencies... ==> Checking buildtime dependencies... ==> Retrieving sources... -> Updating src git repo... Fetching origin ==> Validating source files with md5sums... src ... Skipped ==> Removing existing $srcdir/ directory... ==> Extracting sources... -> Creating working copy of src git repo... fatal: repository '/home/x/.cache/yay/virtscreen/src' does not exist ==> ERROR: Failure while creating working copy of src git repo Aborting... Error making: virtscreen `

**Comment by Morganamilo** [comment]
When makepkg clones a repo it creates a bare into srcdir, then when it comes time to build the package, makepkg makes a working copy called `src` that the pkgbuild sees.

My guess is because the pkgbuild sets the repo name to src, this causes the working copy to overwrite the actual repo.
