### ISSUE TITLE
Suggestion: remember and show AUR package build times

### ISSUE THREAD

**Issue by mooskagh** [Jguer/yay#1185]
I update packages quite often, weekly. As many AUR packages include building from source, they sometimes take up to a few hours to update. Because of that, I try to avoid updating long-building packages, but still would like to update shorter ones. To do that, I have to remember which packages take long to build and skip them when I don't have time.

It would be nice if yay could do for me.

So, here is the feature I think would be useful:

1. When building AUR package, store the time it took to build.
2. When asking which AUR packages to update, show how long it took to build previous time.
3. It would be nice if it was possible to setup "Everything that builds faster than XX minutes" as default (XX in config).

**Comment by chrisjbillington** [comment]
For what it's worth, the difference between the "build date" and "install date" output from `pacman -Qi`should give a good estimate of the build duration. Though it could be inaccurate in some cases like if it was waiting on confirmation to replace a conflicting package, or waiting on your sudo password.

So without too much work you could write a script that ran the output of `checkupdates-aur` through `pacman -Qi` and calculated the expected build time of each package. That would be a start!

**Comment by mooskagh** [comment]
Thanks for the suggestion!

Not sure how reliable it is though...
```
$ pacman -Qi python2-reportlab
Name            : python2-reportlab
Version         : 3.5.32-2
Description     : A proven industry-strength PDF generating solution
Architecture    : x86_64
URL             : https://bitbucket.org/rptlab/reportlab
Licenses        : BSD
Groups          : None
Provides        : None
Depends On      : freetype2  python2  python2-pip  python2-pillow
Optional Deps   : None
Required By     : sk1
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 9.41 MiB
Packager        : Antonio Rojas <arojas@archlinux.org>
Build Date      : Sat 09 Nov 2019 12:05:46 PM CET
Install Date    : Sun 08 Dec 2019 07:55:35 PM CET
```
That's the only pending update that I have so far, will look at other examples.

**Comment by chrisjbillington** [comment]
Haha, yes, well. It looks like `python2-reportlab` was not built on your computer at all, as it was dropped to the AUR 3 days ago - you presumably had installed it from the repos prior to that. So you're seeing the build date on Arch servers and the install date when you last updated. This situation would be another source of inaccuracy.

**Comment by RubenKelevra** [comment]
completely unrelated to the issue, but all python2 packages are expected to be dropped either to the aur or removed completely. So you might want to get rid of your python2 software as well since python2 is EOL. :)

**Comment by Jguer** [comment]
This does seem exactly what `pacman -Qi` `Build Date` is all about, just the little detail of where it was built to be accurate which you can see with `Packager`
