### ISSUE TITLE
`yay --sudoloop` is not equivalent to `yay -Syu --sudoloop`

### ISSUE THREAD

**Issue by cogitantium** [Jguer/yay#1188]
#### Affected Version
yay v9.4.4 - libalpm v12.0.1

#### Issue
Passing `yay --sudoloop` is not equivalent to `yay -Syu --sudoloop`, which I think would be the natural way to understand that command. Unfortunately, yay just exits early.

**Comment by parkerlreed** [comment]
I think the reasoning is: not passing in anything does -Syu. Passing in something overrides that so you then have to specify it.

For example someone could `yay --sudoloop --save` and not have to update their system. 

That would lead to unintended behavior.

**Comment by cogitantium** [comment]
You're right. I should've done a bit more reading before submitting this issue, saving the option to config is a much more elegant solution.

Thanks!
