### ISSUE TITLE
failed to commit transaction (conflicting files)

### ISSUE THREAD

**Issue by alan12345678** [Jguer/yay#1189]
v9.4.4

Just got this new message this morning. Yay's been working perfectly until now. I simply use `yay` IIRC that implies everything necessary.

Now that command is showing the following error:

`error: failed to commit transaction (conflicting files)
python-setuptools: /usr/lib/python3.8/site-packages/pkg_resources/py2_warn.py exists in filesystem
Errors occurred, no packages were upgraded.
Error installing repo packages
`

The offending file DOES NOT EXIST.

I have run both `yay -Rc` and `yay -Sc`, rebooted etc. but still get this message.

Is there a way around this issue? Do I have to intervene manually?

**Comment by Jguer** [comment]
https://wiki.archlinux.org/index.php/Pacman#%22Failed_to_commit_transaction_(conflicting_files)%22_error
