### ISSUE TITLE
implement --force 

### ISSUE THREAD

**Issue by forbi** [Jguer/yay#119]
For example, if I install software manually, and then I found out that there is a package for the same soft, I would install it with yay/Pacman. But it will report `x file already exists in filesystem` . I then would force the install with --force.

[arch wiki conflicting files](https://wiki.archlinux.org/index.php/Pacman#.22Failed_to_commit_transaction_.28conflicting_files.29.22_error)

**Comment by Jguer** [comment]
I believe --force would be passed over to pacman. 
For packages with makepkg, hum, changing to pacman -U would be preferable to fix that
