### ISSUE TITLE
Display the package which caused a dependencies conflict

### ISSUE THREAD

**Issue by babolivier** [Jguer/yay#1193]
#### Affected Version

yay v9.4.4 - libalpm v12.0.1

#### Issue

When trying to update all of my AUR packages, one caused a dependency conflict, which caused the update to be canceled:

```
$ yay -Syua
[...]
resolving dependencies...
looking for conflicting packages...
:: nodejs-lts-dubnium and nodejs are in conflict. Remove nodejs? [y/N] 
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: nodejs-lts-dubnium and nodejs are in conflict
```

However, it doesn't tell me which package caused the conflict (it might be one for something I don't use anymore so I can just uninstall it to resolve it).
Likewise (unlike yaourt) it doesn't tell me where it saved the `PKGBUILD` and `SRCINFO` files so I can't go look for that info by myself.
It would be great if either of these was visible, because otherwise I need to update each package one by one, which is a bit time consuming :/

**Comment by Ferdi265** [comment]
> it doesn't tell me where it saved the `PKGBUILD` and `SRCINFO` files.

`yay` clones all of the AUR packages it builds into `~/.cache/yay/<pkgname>` by default. You can find `PKGBUILD` and `.SRCINFO` files there
