### ISSUE TITLE
doas support

### ISSUE THREAD

**Issue by brainplot** [Jguer/yay#1194]
Hi! First off, I would like to thank you for the amazing work and effort you put into `yay`. It makes managing AUR packages a breeze!

I'm interested in replacing `sudo` with `doas` (a leaner alternative to `sudo`) on my system, but right now `yay-bin` is the only program that explicitly depends on `sudo` and effectively makes the move impossible; unless I keep both `sudo` and `doas`. I find that that would defeat the purpose of choosing a more minimal program, however.

Would it be possible for `yay` to support `doas` too? Or maybe even better to allow the user to set the program used to gain `root` privileges via an option in the config file, just in case a third alternative to `sudo` pops up in the future. That would avoid hard-coding the program used directly in `yay`'s source code.

**Comment by parkerlreed** [comment]
`--sudobin doas --save`

**Comment by brainplot** [comment]
Thanks! I wasn't aware of that option. There's still the problem of `yay` requiring `sudo`.
Also, I found out that `doas` needs to be invoked slightly differently. In fact, it requires two dashes before the command you want to execute with `root` privileges. (e.g. `doas -- pacman -Syu`) so if `yay` were to invoke `doas` the same way it does with `sudo`, the command would fail.

**Comment by Ferdi265** [comment]
@brainplot: you could solve this locally via a shim command in /usr/local/bin or similar:

```sh
#!/bin/sh
# this is /usr/local/bin/sudo
exec doas -- "$@"
```

it's not perfect, and will not work if programs try to use some of `sudo`s options, but for basic usage it should work.

**Comment by Morganamilo** [comment]
Or `yay --sudoargs -- --save`

**Comment by brainplot** [comment]
Thanks for the suggestions. I think I will use a combination of @parkerlreed and @Morganamilo's solutions.

At this point there's only the issue of the dependency on `sudo`. I guess I could code up a custom `PKGBUILD` that `provides` `sudo` in order to satisfy the dependency, as a temporary (or maybe permanent?) solution.

**Comment by L1pE** [comment]
`doas` is also available from the official repos as [opendoas](https://www.archlinux.org/packages/community/x86_64/opendoas/).

**Comment by RubenKelevra** [comment]
@brainplot or you can ask the maintainer of opendoas if he's willing to set this.

The best solution would be a virtual package like `cron` which can be set as a dependency but doesn't exist and the user needs to decide which package, which provides `cron` he wants.

**Comment by brainplot** [comment]
@RubenKelevra that would be ideal. Although a patch in `yay` which detects what the user has installed to elevate privileges would be nice since as is it would require the user to create a config file and change the `sudo` binary and arguments. I think that would make `yay` a bit less user-friendly since it works perfectly fine out of the box, otherwise.

On the other hand, if you've replaced `sudo` with `doas` on your system I guess you know what you're doing already.

**Comment by RubenKelevra** [comment]
> On the other hand, if you've replaced `sudo` with `doas` on your system I guess you know what you're doing already thus you'd know how to "fix" `yay`.

Or you just create a small package which adds the link from sudo to doas in the filesystem and sets 'replace = sudo' and 'provide = sudo' as well a dependency for opendoas.

This should fix all of your problems and is not application dependent.

**Comment by Kommynct** [comment]
Currently the only thing that doesn't seem to work is the --sudoloop command, is there any way to fix this? I'd like to just remove sudo.

**Comment by Jguer** [comment]
I think `--sudoloop` is run with `sudo -v`, is there an equivalent mechanism in doas to keep authentication?

**Comment by Kommynct** [comment]
https://github.com/Duncaen/OpenDoas/issues/29

**Comment by TheDcoder** [comment]
Just a note about the workaround, the `--sudobin` and `--sudoargs` were renamed in the latest version of `yay`, this is the correct command to save `doas` as replacement for sudo:
```
yay --sudo doas --sudoflags -- --save
```

**Comment by RubenKelevra** [comment]
@Jguer can you remove the dependency for `sudo` on the aur package please?

It should be an optional dependency and maybe opendoas should be another optional dependency, since yay can work with both :)

**Comment by RubenKelevra** [comment]
> Just a note about the workaround, the `--sudobin` and `--sudoargs` arguments were renamed in the latest version of `yay`, this is the correct command to save `doas` as replacement for sudo:
> 
> ```
> yay --sudo doas --sudoflags -- --save
> ```

I think yay should just check if no sudo is installed, but opendoas is, and just set this on the first run on such a system. :)

**Comment by TheDcoder** [comment]
> I think yay should just check if no sudo is installed, but opendoas is, and just set this on the first run on such a system. :)

Yes, this would be ideal, as well as making `sudo` and `opendoas` optional dependencies. I manually edited my `PKGBUILD` to remove `sudo`.

**Comment by RubenKelevra** [comment]
@TheDcoder you can also just remove sudo with `pacman -Sd sudo` which skips the dependency checks while doing this operation.

**Comment by TheDcoder** [comment]
@RubenKelevra Right, I did not take a look at all the options, but I did find out about `--assume-installed` option shortly after I made my modification.

**Comment by Kommynct** [comment]
Can we get a --doasloop that works with

--sudoupdateflags=true

As suggested in the post I linked? It's the only reason I still have sudo haha

**Comment by RubenKelevra** [comment]
I've discovered two issues when using opendoas instead of sudo with yay:


* sudoloop is running too slow, opendoas has a lower timeout when using `persis`
* running yay as root will return an error since it tries to run opendoas as root

**Comment by TheDcoder** [comment]
> Can we get a --doasloop that works with

@Kommynct OpenDoas currently has experimental support for persistant authorization, and it is not enabled by default, so it might be a good idea to add support for this feature until it is stable enough.

**Comment by Jguer** [comment]
So it seems for me from https://github.com/Duncaen/OpenDoas/issues/29 that running `doas true` with a shorter cycle than sudo loop would work? Is that right?

**Comment by TheDcoder** [comment]
@Jguer The `--with-timestamp` flag is also needed to enable timeout support, otherwise `doas` will prompt you for the password on each call. Also take note that this feature is **experimental** and **dangerous**:

> This feature is new and potentially dangerous, in the original doas, a kernel API is used to set and clear timeouts. This API is openbsd specific and no similar API is available on other operating systems. [Source](https://github.com/Duncaen/OpenDoas#peristtimestamptimeout)

**Comment by Jguer** [comment]
Ok, so I agree that this may need some aging time before support is implemented

**Comment by RubenKelevra** [comment]
Well, I don't see a reason why `yay` shouldn't support an experimental feature. I mean, when we don't experiment with it - it won't ever get stable, right? 🤔

**Comment by freed00m** [comment]
Does someone have a proper workaround?
Currently I set in yay config 

```
	"sudobin": "$HOME/.local/bin/yay-doas-wrapper",
```

and my wrapper is as follows
```
#!/bin/sh
#
#  This wrapper makes sure yay+pacui works with doas
#

if [ "$1" = "-v" ]
then
	shift
fi

if [ "$1" = "--" ]
then
	shift
fi

if [ -z "$1" ]
then
	exec doas echo
else
	exec doas "$@"
fi
```

also my doas conf
```
permit persist :wheel
```

**Comment by adam-devel** [comment]
You can install [doas-sudo](https://aur.archlinux.org/packages/opendoas-sudo/), it's symlink `/bin/sudo` to `/bin/doas`
which will make almost every program use `doas` instead of `sudo`

**Comment by atk91** [comment]
One more thing what can be done is to remove `sudo` from dependencies, since you still have `sudo` installed to use `yay`

**Comment by TheDcoder** [comment]
@atk91 Yes, it should be made an optional dependency along with `opendoas`

> since you still have `sudo` installed to use `yay`

Not strictly, you can use the `--assume-installed` option to force pacman to not install `sudo`.

**Comment by brainplot** [comment]
> Not strictly, you can use the `--assume-installed` option to force pacman to not install `sudo`.

You're technically right but I think we would all want a cleaner solution than that!

**Comment by Jguer** [comment]
> One more thing what can be done is to remove `sudo` from dependencies, since you still have `sudo` installed to use `yay`

Done as of yay `10.1.2-2` 

Any other way support for `doas` can be improved?

**Comment by freed00m** [comment]
@Jguer yay does put some flags to the sudobin that doas doesn't know.

`yay -Syu` does call `doas -v -- etc`
making doas fail with
```
doas: invalid option -- 'v'
usage: doas [-Lns] [-C config] [-u user] command [args]
```
Why not check if the sudobin is indeed a `sudo` and then append the flags

**Comment by y0ast** [comment]
Ideally also automatic switching the sudobin to doas if sudo isn’t installed and doas is.

**Comment by SowTag** [comment]
> yay --sudobin doas --save

This changed in the last yay versions. I had to use `yay --sudo doas --save` instead of --sudobin.

**Comment by stickyburn** [comment]
@Jguer since flag options do change and swapped flags dont throw any errors, could we atleast settle on a fixed, particular flag for `doas`? 
Or maybe we could have an option to set them on install? That would be quite nice and introduce people to both these cool technologies!

Open to help with what I can :)

**Comment by freed00m** [comment]
@yashank09 I agree with you.

What I feel would be the best is to develop a posix wrapper script that does what you say, and it could be shipped or as optional dependency with yay as well :) so if user want to use doas, it would raise a warning about flags and tell user to set sudobin to the wrapper.

If the choice would be to handle this in yay binary directly then I am fine with it also but it increases complexity to the binary.

**Comment by stickyburn** [comment]
@freed00m edited my answer a bit... Could/should I add a similar wrapper during install? and based on the response, it adds the flag or leaves it?

**Comment by Jguer** [comment]
My current approach would be:

1. On launch yay loads its settings as usual
2. yay checks if `sudobin` binary actually exists
3. if it's set to a custom option, fail, let the user fix it
4. If it's set to `sudo`, the default option, check if `doas` exists and use that instead
5. else fail, let the user fix it

----

If `sudo` is set to `doas`, clean up flags where needed

**Comment by freed00m** [comment]
> If `sudo` is set to `doas`, clean up flags where needed

How? what if user have something else that does conflict with the flags? For example custom wrapper. Or some other privilege escalating software.

It should add flags only if it the program can understand them.

**Comment by PQCraft** [comment]
Has anyone tried uninstalling sudo then running
```sh
ln -s /usr/bin/doas /usr/bin/sudo
```

**Comment by freed00m** [comment]
@PQCraft there is already a AUR package https://aur.archlinux.org/packages/opendoas-sudo/ and yes I am running it just fine.

For yay I wrap and filter some flags that doas can't do https://git.sr.ht/~freed00m/dotfiles/tree/master/item/.local/bin/yay-doas-wrapper not sure if that really needs to be done anymore.

**Comment by Jguer** [comment]
`yay` should now default to `doas` if it's the only privilege elevation tool installed. (available on `yay-git`), from my limited testing it should be working mostly fine, I'll be driving `doas` for a bit to make sure nothing is missing
