### ISSUE TITLE
Suggestion: have a way to continue interrupted AUR installs/builds.

### ISSUE THREAD

**Issue by mooskagh** [Jguer/yay#1199]
This is another suggestion to address the same issue as in #1185.

The problem is: many AUR packages are built from source, and for many packages it can take hours, making it inconvenient to update.
I couldn't find any existing solution to that (although I still think I missed something, as it probably affects many people and I though someone would already address it).

So idea is to be able to continue (redo) the interrupted build/install steps. Then this invocation of `yay --continue` could be done on startup or in anacron, allowing packages to finish installation even if it was earlier interrupted.

The workflow would be the following:
1. You run `yay` to update everything as usual, review PKGBUILD files if you want etc.
2. Packages start to be built and installed.
3. If the process is terminated (e.g. when the computer shuts down), it remembers the remaining steps.
4. After reboot, `yay --continue` is called from somewhere, and finishes steps which don't need human intervention.

**Comment by Titaniumtown** [comment]
YES!! I want this so bad

**Comment by HaleTom** [comment]
Related: #848

**Comment by HaleTom** [comment]
Related: Install as many packages as possible #1247
