### ISSUE TITLE
Unable to read Pacman conf: option LocalFileSigLevel outside of [options] section, at line 4

### ISSUE THREAD

**Issue by phiresky** [Jguer/yay#120]
Happens using `2.219.r73.gb69bab8-1` and `2.219-2` both.

There is no "LocalFileSigLevel" in line 4 in my pacman config.

The error goes away when i remove

`Include = /etc/pacman.d/ignore`
from my config, which is above (but not directly above) a LocalFileSigLevel directive:

![image](https://user-images.githubusercontent.com/2303841/35578714-3385a50e-05e5-11e8-8235-19481a9f5df2.png)

the `ignore` file is completely empty.

**Comment by Jguer** [comment]
Shot in the dark, I think go-alpm is not made to read Include files, I believe it's an upstream bug of go-alpm
