### ISSUE TITLE
How do I modify gcc flags before installation of a kernel using yay?

### ISSUE THREAD

**Issue by Joe23232** [Jguer/yay#1203]
I want to install `linux-clear` on my Arch based system https://aur.archlinux.org/packages/linux-clear/ via this command `yay -S linux-clear`.

I know for a fact that it will attempt to build `linux-clear` but I wanted to use a different set of flags as suggested by the Clear Linux developers.

I know that I can type `yay -S linux-clear --editmenu` but where do I go next to modify the default `gcc` flags?

**Comment by parkerlreed** [comment]
Treat the PKGBUILD like a bash script. 

If it has en existing section for the flags, edit that. If not add it into one of the prepare items (before the final `make` that compiles the kernel)

**Comment by Joe23232** [comment]
Hi @parkerlreed thanks for your response. I am sorry but I am kinda a noob over here. so after typing in `yay -S linux-clear --editmenu`, do I have to look for the section called `PKGBUILD`, right? How do I edit the text though cause it doesn't seem to allow me to edit the text?


> If not add it into one of the prepare items (before the final make that compiles the kernel)

Sorry what do you mean by that?

**Comment by xuiqzy** [comment]
@Joe23232 This is kind of an advanced modification you are doing to your system and it seems like you are missing a few fundamental things to understand the operation you are trying to do.
To understand how to do what you want to do, please read the Arch Wiki Pages of the Arch User Repository and how to install AUR packages manually (as everyone using the AUR in Arch is supposed to do), Arch wiki PKGBUILD site, read up about bash syntax and shell scripts, the EDITOR variable and the terminal text editor vim.
This should help you get started to understand everything that is going on :)
