### ISSUE TITLE
Permission denied on installation

### ISSUE THREAD

**Issue by fmauch** [Jguer/yay#1208]
#### Affected Version

Update from 9.4.4-1 to 9.4.6-2

#### Issue
I can't package yay as it gives me a "permission denied" error during `make install`

#### Steps to reproduce

1. Download the AUR package
2. Run `makepkg -s`

#### Output

```
> $ makepkg -s                                                                                                                                              [±master ✓]
==> Making package: yay 9.4.6-2 (Do 12 Mär 2020 09:01:00 CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading yay-9.4.6.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   117  100   117    0     0    731      0 --:--:-- --:--:-- --:--:--   731
100  295k  100  295k    0     0   287k      0  0:00:01  0:00:01 --:--:--  641k
==> Validating source files with sha1sums...
    yay-9.4.6.tar.gz ... Passed
==> Extracting sources...
  -> Extracting yay-9.4.6.tar.gz with bsdtar
==> Starting build()...
go build -v -mod=mod -ldflags '-s -w -linkmode external -extldflags "-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now" -X "main.version=9.4.6"' -modcacherw -gcflags all=-trimpath=/home/felix/.cache/yay/yay/src/yay-9.4.6 -asmflags all=-trimpath=/home/felix/.cache/yay/yay/src/yay-9.4.6 -o yay
go: downloading github.com/Morganamilo/go-pacmanconf v0.0.0-20180910220353-9c5265e1b14f
go: downloading github.com/Jguer/go-alpm v0.0.0-20191122171459-5cffc6e8fc69
go: downloading github.com/mikkeloscar/aur v0.0.0-20200113170522-1cb4e2949656
go: downloading github.com/Morganamilo/go-srcinfo v1.0.0
==> Entering fakeroot environment...
==> Starting package()...
install -Dm755 yay /home/felix/.cache/yay/yay/pkg/yay/usr/bin/yay
make: install: Permission denied
make: *** [Makefile:113: install] Error 127
==> ERROR: A failure occurred in package().
    Aborting..
```

When starting the `makepkg` command, the directory `/home/felix/.cache/yay/yay/pkg/` does not exist but is created during running `makepkg`. Running the `install` command from above manually works as expected. Running `make install` manually inside the package's downloaded source directory yields the same error. Replacing the `install` command with a `cp` command in the Makefile and then running `make install` manually works.

I used this command to run `make install` by hand:
```
felix@travelbook ~/.cache/yay/yay/src/yay-9.4.6
> $ make  VERSION=9.4.6 DESTDIR=/home/felix/.cache/yay/yay/pkg/yay PREFIX=/usr install                                                                      [±master ✓]
install -Dm755 yay /home/felix/.cache/yay/yay/pkg/yay/usr/bin/yay
make: install: Permission denied
make: *** [Makefile:113: install] Error 127
```

I'm not sure whether this is an actual yay bug, but I don't quite know where else to look and it is the only package where that occurred to me and I have quite a lot of AUR packages installed...

Edit:
Replacing the `install` statement with the full path seems to work:

```
.PHONY: install
install:
	which install
	/usr/bin/install -Dm755 ${BIN} ${DESTDIR}/${PREFIX}/bin/${BIN}
	install -Dm644 doc/${PKGNAME}.8 $(DESTDIR)$(PREFIX)/share/man/man8/${PKGNAME}.8
...
```
yields to
```
$ make  VERSION=9.4.6 DESTDIR=/home/felix/.cache/yay/yay/pkg/yay PREFIX=/usr install
which install
/usr/bin/install
/usr/bin/install -Dm755 yay /home/felix/.cache/yay/yay/pkg/yay//usr/bin/yay
install -Dm644 doc/yay.8 /home/felix/.cache/yay/yay/pkg/yay/usr/share/man/man8/yay.8
make: install: Permission denied
	make: *** [Makefile:115: install] Error 127
```
Here, it fails at the first non-replaced command. I am just wondering as `which install` yields the correct absolute path...

**Comment by xuedi** [comment]
i have a very simmilar issue, i am also not sure if a system thing or go/yay related, if i install is get:
`==> Making package: yay 9.4.6-2 (2020-03-24T00:57:02 CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found yay-9.4.6.tar.gz
==> Validating source files with sha1sums...
    yay-9.4.6.tar.gz ... Passed
==> Extracting sources...
  -> Extracting yay-9.4.6.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
go build -v -mod=mod -ldflags '-s -w -linkmode external -extldflags "-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now" -X "main.version=9.4.6"' -modcacherw -gcflags all=-trimpath=/home/xuedi/downloads/yay/src/yay-9.4.6 -asmflags all=-trimpath=/home/xuedi/downloads/yay/src/yay-9.4.6 -o yay
make: go: Permission denied
make: *** [Makefile:49: yay] Error 127
==> ERROR: A failure occurred in build().
    Aborting...
`

**Comment by Jguer** [comment]
@xuedi your issue seems different, do
```
which go
```
and
```
whereis go
```

I believe your `go` binary is not executable

**Comment by Jguer** [comment]
@fmauch  I cannot reproduce your issue, `whereis install` should show if there is more than 1 install bin, but it's kind of a weird issue that `which install` returns the right one

**Comment by fmauch** [comment]
That's interesting! I have a folder called `local_install/install` inside my home folder which I use as a local install prefix for some things.

This shows up in `whereis`:
```
whereis install
install: /usr/bin/install /home/felix/local_install/install /usr/share/man/man5/install.5 /usr/share/man/man1/install.1.gz
```

`/home/felix/local_install` is inside my `$PATH`, which is probably wrong, as it should be `~/local_install/install/bin` inside the `$PATH`. So, everything boils down to a false environment setup of mine. I still don't get, why make chooses to use the second entry, but well...

Thanks for your help @Jguer. From my perspective it is fine to close this.

**Comment by Jguer** [comment]
on my clean system `whereis install` returns the following:

`install: /usr/bin/install /usr/share/man/man1/install.1.gz /usr/share/man/man5/install.5`

I believe the underlying cause is clarified, still don't understand why `make` would pick your local version but well... sometimes it's better not to dig to deep into it.

Have a nice day
