### ISSUE TITLE
Missing CONTRIBUTING.md in project

### ISSUE THREAD

**Issue by zhengpd** [Jguer/yay#1211]
The FAQ in README says to read CONTRIBUTING.md before help out, but there's no such file. Maybe remove this FAQ entry for now.

**Comment by Jguer** [comment]
It's true, I have to write it actually instead, I have a good idea what should be our requirements now

**Comment by Jguer** [comment]
https://github.com/Jguer/yay/blob/next/CONTRIBUTING.md
