### ISSUE TITLE
Build files exist but still get compiled again

### ISSUE THREAD

**Issue by songangel72** [Jguer/yay#1215]
Version
yay v9.4.6 - libalpm v12.0.1

Issue
When building a package from the AUR which requires compilation of the source I ran into a problem and could not find any documentation about it.  The compilation was succesfull but some other error occurred with the install stage.  

I decided to try again in order to try to diagnose the problem.  Sure enough I get prompted that build files exist and am asked which files I want to clean build.  I choose None and it compiles again!  

Am I misunderstanding this behavior?  I would expect that if I choose None that yay would skip the compilation since the build files exist in the cache.  This particular package takes almost 30 minutes to build so I was hoping that it would jump straight to the install but it does not.

Steps to reproduce
N/A

Output
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/justin/.cache/yay",
	"absdir": "/home/justin/.cache/yay/abs",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"batchinstall": false,
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false
}

**Comment by Java-C0der** [comment]
From what I understand, the "clean build" option means that yay won't download the PKGBUILD and sources again.

**Comment by Java-C0der** [comment]
But I agree, there should be a way to not have it recompile everything if the compiled package already exists.

**Comment by ModProg** [comment]
Really annoying if you have a big package and it fails because of an already installed package.
