### ISSUE TITLE
Respect XDG_DOWNLOAD_DIR

### ISSUE THREAD

**Issue by pickfire** [Jguer/yay#1219]
#### Affected Version

yay v9.4.6 - libalpm v12.0.1

#### Issue
It ask for `~/Downloads` when I am using `~/usr/get` as replacement for that.

#### Steps to reproduce

1. `yay -S zoiper`
2. Download `zoiper`, in my case it gets downloaded to `~/usr/get` (my `XDG_DOWNLOAD_DIR`) rather than `~/Downloads`

#### Output

It does not recognize the downloaded file in `XDG_DOWNLOAD_DIR` but works for `~/Downloads`. `~/Downloads` should act as a fallback but `XDG_DOWNLOAD_DIR` should be used first.

**Comment by Jguer** [comment]
PKGBUILD issue, report it to the maintainer, they're not treating the sources correctly
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=zoiper

https://aur.archlinux.org/packages/zoiper/

**Comment by pickfire** [comment]
Thanks for pointing me to the right direction.
