### ISSUE TITLE
Argumment parsing passing yay options to pacman

### ISSUE THREAD

**Issue by Jguer** [Jguer/yay#122]
yay config options are being carried over to pacman on some operations when they should be parsed by yay.

Expected:
`yay -Syu --devel` 

Actual Result:
`pacman: unrecognized option '--devel'`

Workaround:
`yay -Y --devel`
`yay -Syu`

**Comment by jonathonf** [comment]
I've seen this with an i686 compile but not with one x86_64; I'll try another few compiles and see if it's consistent.
