### ISSUE TITLE
Print PKGBUILD to stdout

### ISSUE THREAD

**Issue by nycex** [Jguer/yay#1223]
yay v9.4.6 - libalpm v12.0.1
#### Feature Request
It'd be great if yay had the possibility to not just download the PKGBUILD to the cwd, but also to just display it to stdout. Often i want to look at how a package is built and find myself looking it up in the browser because i don't want to have the pkgbuild file saved, but just shown.

**Comment by Jguer** [comment]
Technically this does what you want but I would be careful where you run it :smile: .
```shell
yay -G ${PKGBUILD} && less ${PKGBUILD}/PKGBUILD && rm -rfv ${PKGBUILD}
```


I'm willing to implement this as a `-P` option.

**Comment by Jguer** [comment]
Implemented as `-Gp` by @nycex , thank you very much
