### ISSUE TITLE
Don't remove compiled packages that are installed when running yay -Sc

### ISSUE THREAD

**Issue by IslandC0der** [Jguer/yay#1224]
When you install a package using pacman, the compressed package that you download gets stored on the local package database <code>/var/cache/pacman/pkg/</code>. This is really useful, because it means you can reinstall a package anytime without an internet connection.
When yay builds a package from its <code>PKGBUILD</code> using <code>makepkg</code>, a compressed package is created on <code>~/.cache/yay/$package/</code>. However, these packages get deleted every time you run <code>yay -Sc</code>. Now, if you want to reinstall an aur package, you need to recompile it AND you also need an internet connection, since it has to download the sources again.
Therefore, it would be really nice to have a way to keep the compiled (compressed) package. To make things consistent with pacman, yay shouldn't delete those compiled packages that are installed when running <code>yay -Sc</code>. Similarly to pacman, this should only happen when running <code>yay -Scc</code>: these "backups" would then get deleted, even if they correspond to currently installed packages.

**Comment by unai-ndz** [comment]
Optionally a `--keep <number>` option for keeping the most recent package builds like `paccache` does.

**Comment by Jguer** [comment]
`*.pkg.*` should now be excluded from clean
