### ISSUE TITLE
fakeroot: error while starting the `faked' daemon.

### ISSUE THREAD

**Issue by geometryolife** [Jguer/yay#1227]
$ makepkg -si
==> Making package: yay 9.4.6-2 (Thu 02 Apr 2020 04:51:03 PM CST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found yay-9.4.6.tar.gz
==> Validating source files with sha1sums...
    yay-9.4.6.tar.gz ... Passed
==> Extracting sources...
  -> Extracting yay-9.4.6.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
make: Nothing to be done for 'build'.
==> Entering fakeroot environment...
fakeroot, while creating message channels: Function not implemented
This may be due to a lack of SYSV IPC support.
fakeroot: error while starting the `faked' daemon.
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
------------------------------------------------------------------------------------------------
I don't know how to fix this  error.
I use WSL(Arch linux).
I want to install yay, but above error appears.

**Comment by ghost** [comment]
For WSL try this:
https://github.com/Microsoft/WSL/issues/2465#issuecomment-619385604

For Termux try this:
https://github.com/sdrausty/TermuxArch/issues/83#issuecomment-451351053
