### ISSUE TITLE
[Feature request] Offload package building to a build server

### ISSUE THREAD

**Issue by Hubro** [Jguer/yay#1229]
I have multiple computers running arch. Most of them are weak, low power devices like laptops or NUCs, but I have one beast workstation with 16 CPU cores that chews through compilation tasks like they were nothing.

Would it in any way be possible to add an option to yay that makes it do all package downloading, compiling and packaging on a remote computer over SSH, then just download and install the packages locally at the end? (Runtime dependencies would of course have to be installed locally.)

Currently my lower power devices spend hours compiling every time I update them...

Any other tips on how to resolve this issue would be appreciated.

**Comment by Jguer** [comment]
Out of scope for yay but `distcc` should work pretty fine for it

https://wiki.archlinux.org/index.php/Distcc#For_use_with_makepkg

**Comment by Hubro** [comment]
> Out of scope for yay but `distcc` should work pretty fine for it
> 
> https://wiki.archlinux.org/index.php/Distcc#For_use_with_makepkg

Thanks for the tip. I tried it out, and it's definitely an improvement as it improves build times, but it's not ideal since it still pegs every core of the local PC at 100% through the entire build process, even when all compilation is relegated to other hosts, which quickly drains battery and heats up my ultrabook.

I suppose if I want to move all heavy tasks related to package building off my laptops completely, I would have to run my own package repo and set up some automation of building AUR packages and publishing them on the repo... That sounds like a gargantuan undertaking for another time.

**Comment by Jguer** [comment]
Your local PC goes to 100% even with `DISTCC_HOSTS` not including localhost?

**Comment by Hubro** [comment]
> Your local PC goes to 100% even with `DISTCC_HOSTS` not including localhost?

Correct.

**Comment by cmonty14** [comment]
Hi,
I would like to refresh this feature request because I think it would be beneficial for other users facing the same system landscape with multiple weak clients and a powerful server.

I think the approach with `distcc` is only successful if C or C++ is used for compiling which is not the case for all packages.

Therefore I think one approach could be this:
1. yay is delegating download, compilation and build to a central server
2. packages are not installed on this server
3. instead this central server acts as a proxy cache server, e.g. with [Pacoloco](https://github.com/anatol/pacoloco) or [Flexo](https://github.com/nroi/flexo)

The main challenge from my perspective is the task delegation to a central server.

**Comment by Jguer** [comment]
I think this problem has already been solved with repositories. I think aurutils ([gitHub](https://github.com/AladW/aurutils/), [bbs](https://bbs.archlinux.org/viewtopic.php?id=210621)) is probably a good place to start exploring setting this up. 

Repository setup seems to be the best for this hub and spoke model, it would be interesting to implement a separate CLI that can hook the built packages to a local repository.

**Comment by cmonty14** [comment]
I'm not sure if I understand correctly.
This local repository is then hosted on powerful server?
And weak clients add this repository to their configuration?

How will this ensure that all steps of package creation (download, compilation, build) are executed on central server?

**Comment by Jguer** [comment]
>  This local repository is then hosted on powerful server?

Yes

>  And weak clients add this repository to their configuration?

Yes

> How will this ensure that all steps of package creation (download, compilation, build) are executed on central server?

As long as you always execute the package creation (and adding to the the repository) first on the central server then all the client systems just pull built packages from the repository after
