### ISSUE TITLE
v2.297 lost its colors

### ISSUE THREAD

**Issue by muesli** [Jguer/yay#123]
The previous releases used to show colorful output on the terminal, e.g. when searching for packages. The latest release doesn't do that anymore. Is it expecting a config flag or a particular cli arg for that feature now?

**Comment by Jguer** [comment]
yay now follows pacman's config /etc/pacman.conf for colors.

You need to add Color to your options /etc/pacman.conf
Example (my pacman.conf):

```
#{{{ General options
    [options]
    HoldPkg      = pacman glibc
    CleanMethod  = KeepInstalled
    UseDelta     = 0.7
    Architecture = auto
#}}}

#{{{ Misc options
    UseSyslog
    Color
    TotalDownload
    CheckSpace
    VerbosePkgLists
#}}}

#{{{ Trust
    SigLevel           = Required DatabaseOptional
    LocalFileSigLevel  = Optional
    RemoteFileSigLevel = Required
#}}}

#{{{ Repositories
    [core]
    Include = /etc/pacman.d/mirrorlist

    [extra]
    Include = /etc/pacman.d/mirrorlist

    [community]
    Include = /etc/pacman.d/mirrorlist

    [multilib]
    Include = /etc/pacman.d/mirrorlist
#}}}

# vim:fdm=marker

```

**Comment by muesli** [comment]
Awesome, that's definitely an improvement! Quickly added the Color option to my pacman.conf and can confirm it's working just fine. Thanks for the detailed reply!

**Comment by huangcong12** [comment]
cool

**Comment by chalist** [comment]
Need to uncomment `Color` in `/etc/pacman.com` file. Thanks.

**Comment by andersfylling** [comment]
Not sure if this is an issue for other people, but while I have color enabled in pacman.conf, my output is still just mostly gray.
![image](https://user-images.githubusercontent.com/7851860/122649151-d65b3580-d12c-11eb-875a-830f5b383ce7.png)

**Comment by Jguer** [comment]
@andersfylling try `yay -Syu --combinedupgrade --save`

**Comment by andersfylling** [comment]
![image](https://user-images.githubusercontent.com/7851860/123231082-285add00-d4d8-11eb-8269-d22c2160fcb6.png)
It added a extra/new section that had colours, the rest is the same ^^,
