### ISSUE TITLE
exec: "gcc": executable file not found in $PATH make: *** [Makefile:49: yay] Error 2

### ISSUE THREAD

**Issue by matthill11** [Jguer/yay#1230]
#### Steps to reproduce

1. git clone https://aur.archlinux.org/yay.git
2. cd yay
3. makepkg -si

#### Output

[matthew@Manjaro yay]$ makepkg -si
==> Making package: yay 9.4.6-2 (Sat 04 Apr 2020 06:49:44 PM PDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found yay-9.4.6.tar.gz
==> Validating source files with sha1sums...
    yay-9.4.6.tar.gz ... Passed
==> Extracting sources...
  -> Extracting yay-9.4.6.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
go build -v -mod=mod -ldflags '-s -w -linkmode external -extldflags "-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now" -X "main.version=9.4.6"' -modcacherw -gcflags all=-trimpath=/home/matthew/yay/src/yay-9.4.6 -asmflags all=-trimpath=/home/matthew/yay/src/yay-9.4.6 -o yay
runtime/cgo
# runtime/cgo
exec: "gcc": executable file not found in $PATH
make: *** [Makefile:49: yay] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
[matthew@Manjaro yay]$

**Comment by parkerlreed** [comment]
`base-devel` is assumed installed if dealing with the AUR/makepkg at all.

**Comment by matthill11** [comment]
Got it! Thank you.
