### ISSUE TITLE
Putting AUR package versions in etckeeper 

### ISSUE THREAD

**Issue by stevenxxiu** [Jguer/yay#1233]
#### Affected Version
`yay v9.4.6 - libalpm v12.0.1`

#### Issue
Is there a way to put AUR package versions in etckeeper? Presently only the non-AUR package versions are in the commit message:

```
 committing changes in /etc made by "sudo pacman -S -u -y --config /etc/pacman.conf --"
    
    Package changes:
    -dvdauthor 0.7.2-7
    +dvdauthor 0.7.2-8
```

This won't include things like `sublime-text-dev`.

**Comment by AladW** [comment]
If you want pacman -Syu to update your AUR package versions, you're going to need to put those AUR packages in a (local) repository which yay doesn't support. So you can either figure out to make yay work with it or make `etckeeper` use a different command.
