### ISSUE TITLE
yay -Pu is redundant

### ISSUE THREAD

**Issue by IslandC0der** [Jguer/yay#1235]
<code>yay -Pu</code> does exactly the same thing as <code>yay -Qu</code>.
I can't think of anything to add to set them apart, so my suggestion would be to just remove <code>yay -Pu</code>.

**Comment by mokulus** [comment]
`man yay`
```
...
SHOW OPTIONS (APPLY TO -P AND --SHOW)
...
       -u, --upgrades
              Deprecated, use yay -Qu instead.
...
```
It has to stay at least for a while for backwards compatibility reasons.
