### ISSUE TITLE
options array of packages to always "!strip debug"?

### ISSUE THREAD

**Issue by mxmilkiib** [Jguer/yay#1237]
So if a cached PKGBUILD etc gets deleted, the next time the package is installed, it will automatically be build as if "!strip debug" were in the PKGBUILD.

**Comment by Jguer** [comment]
Have you checked your `/etc/makepkg.conf` and `OPTIONS` key?

**Comment by mxmilkb** [comment]
I don't want to build all VCS packages as debug packages, rather; a small subset of them.
