### ISSUE TITLE
I want easter eggs when the pacman "ILoveCandy" easter egg is active.

### ISSUE THREAD

**Issue by lan-vuhoang** [Jguer/yay#1240]
#### Issue
There's an easter egg in pacman.
If the Pacman "Color" option is active, yay will also be colored. And if you insert "ILoveCandy" into the Pacman option list, the Pacman progress bar will be Pacman eating pellets as it is operating. Could there be an easter egg like that in yay? 

#### Steps to reproduce

1.
2.
3.

**Comment by PackmanDude** [comment]
EL GATOOOO 😭😭😭😭😭😭
