### ISSUE TITLE
Request: use -w (print news flag) by default.

### ISSUE THREAD

**Issue by dessalines** [Jguer/yay#1241]
A recent arch update failed with the default yay command: https://www.reddit.com/r/archlinux/comments/g09b7c/nss35111_and_lib32nss35111_updates_require_manual/

Some pointed out in this thread, running `yay -Pw`, which showed the arch news for the update, which gave information about how to fix the error that update introduced. It makes sense for that to be the default, so users can know what actions to do if their arch update fails.

**Comment by benoliver999** [comment]
I would support this. If there is news, print it and do not update.

For now, I use this function:

    function yay() {
        if [[ "$#" != 0 ]]; then /usr/bin/yay "$@"; return; fi
        if [ $(/usr/bin/yay -Pw | tee /dev/tty | wc -l) = 0 ]; then /usr/bin/yay; fi
    }

**Comment by starquake** [comment]
> Before upgrading, users are expected to visit the Arch Linux home page to check the latest news, or alternatively subscribe to the RSS feed or the arch-announce mailing list.

https://wiki.archlinux.org/index.php/System_maintenance#Read_before_upgrading_the_system

I use [informant](https://aur.archlinux.org/packages/informant/) with a pre hook for this but including this in yay might be useful.
