### ISSUE TITLE
yay -Sdd doesn't work for aur packages

### ISSUE THREAD

**Issue by IslandC0der** [Jguer/yay#1242]
#### Issue
When running <code>pacman -Sdd _package_</code>, only the actual _package_ will be installed, and not its dependencies. However, you run <code>yay -Sdd _package_</code>, if that package is from the aur, the <code>-dd</code> flag will do nothing, and the dependencies will still be downloaded, compiled and installed. Obviously the make dependencies should still be downloaded, as otherwise you probably won't be able to compile the package (maybe add a <code>-ddd</code> flag for edge cases when you don't even want the make deps?), but for the sake of consistency the regular dependencies shouldn't be downloaded.

#### Steps to reproduce
I'm going to use <code>wine</code> for this example since I don't have it installed and it has a lot of dependencies, which highlights the issue, but you can use any package that has dependencies you don't currently have installed on your system.
1. Run <code>pacman -Sdd wine</code>. It will only attempt to download and install the package <code>wine</code>.
2. Now run <code>yay -Sdd wine-git</code>. This will not only download <code>wine</code> and its make dependencies, but also its regular dependencies.

#### Output
$ <code>pacman -Sdd wine</code>
looking for conflicting packages...

Package (1)    New Version  Net Change  Download Size

multilib/wine  5.5-1        496,91 MiB      53,68 MiB

Total Download Size:    53,68 MiB
Total Installed Size:  496,91 MiB

:: Proceed with installation? [Y/n] 

---------------------------------------------

$ <code>yay -Sdd wine-git</code>
:: There are 2 providers available for wine-git:
:: Repository AUR
    1) wine-git 2) wine-staging-git 

Enter a number (default=1): 1
:: Checking for conflicts...
:: Checking for inner conflicts...
[Repo: 54]  lib32-expat-2.2.9-1  lib32-zlib-1.2.11-2  lib32-bzip2-1.0.8-2  lib32-libpng-1.6.37-2  lib32-gcc-libs-9.3.0-1  lib32-pcre-8.44-1  lib32-libffi-3.3-2  lib32-util-linux-2.35.1-1  lib32-glib2-2.64.2-1  
. . . .
[Repo Make: 51]  libspiro-1:20190731-1  potrace-1.16-1  libuninameslist-20190701-1  fontforge-20200314-2  lib32-giflib-5.2.1-1  lib32-gmp-6.2.0-1  lib32-nettle-3.5.1-1  lib32-libtasn1-4.16.0-1
. . . .
[Aur: 1]  wine-git-4.20.r74.ga9c4b309f6-1

==> Remove make dependencies after install? [y/N]

**Comment by Jguer** [comment]
Hey @IslandC0der would you mind trying out #1473 , see if it fixes the issue?
