### ISSUE TITLE
late elevation

### ISSUE THREAD

**Issue by bphd** [Jguer/yay#1244]
#### Affected Version
Latest

#### Issue
`yay` asks for root rights way too late

Sometimes you run a big update and go take your coffee, `yay` will ask nothing and make his compilations... And when you're far away from keyboard he will launch `pacman` at the very end who asks fur `sudo` rights (so your passsword) and that expires fast. So you return and nothing has been done, you have to relaunch and stay by the computer watching for the exact moment the computer will ask for the pswd. For example it's particularly annoying with `ffmpeg-git` who is very slow to compile and that if you don't give the passsword, you have to recompile the whole thing

Nevermind, `yay` should ask the password at the very beginning if he know he will need rights at some point

#### Steps to reproduce

1.
2.
3.

#### Output

Link to downstream: https://aur.archlinux.org/packages/yay/#comment-739933

**Comment by crdx** [comment]
What about `--sudoloop`?

```
--sudoloop
       Loop sudo calls in the background to prevent sudo from timing out during long builds.

**Comment by ny-a** [comment]
I think there is `--sudoloop` option to solve this problem.

**Comment by bphd** [comment]
ty! But it should be the default most definitely

**Comment by ny-a** [comment]
You can configure it by `yay --save --sudoloop`

**Comment by Jguer** [comment]
Duplicate (or answered by): #147 , #1221
