### ISSUE TITLE
use aur only

### ISSUE THREAD

**Issue by mrsteve0924** [Jguer/yay#1245]
#### Affected Version
  yay v9.4.6 - libalpm v12.0.1

#### Issue
is there a PERMANENT CONFIGURATION SETTING that will make yay only use the aur? i couldn't find one in the man pages.  
i know i can use yay -a,  but i would rather just set it and forget it.

**Comment by IslandC0der** [comment]
You could add something like <code>alias yay='yay -a'</code> to your <code>.bashrc</code> file (or the equivalent if you're using a different shell). Don't forget to restart the shell afterwards. :)

**Comment by mrsteve0924** [comment]
good idea. but now, if i alias it like that, i have to type out yay -Syu when before i could just type yay.  and if i have to type out yay -Syu then i might has well just add the **a** at that point.

**Comment by IslandC0der** [comment]
Hmm, I see.
Hey, if it helps, I have <code>alias pacman='yay'</code>: that way I "use" <code>pacman</code> for everything and don't even have to think about whether a given package is from the aur or the repos. The syntax is the same, so there is no confusion.
