### ISSUE TITLE
No way to determine which package caused an error

### ISSUE THREAD

**Issue by dnut** [Jguer/yay#1246]
When a package build fails, I have to scroll up to the start to figure out what package had an error. Sometimes the compilation output prints many thousands of lines and it is not possible to do this. This is extremely frustrating since I can't fix the problem if I have no idea what caused it. yay should specify which package failed before it exits due to an error.

yay v9.4.2 - libalpm v12.0.1

**Comment by Jguer** [comment]
That's a very cool and concrete idea, I like it

**Comment by ranomier** [comment]
I love your idea!
A workaround would be to increase the scroll history.

But having to scroll is still bad. yay should gather all the errors while running and display them at the end.

**Comment by Jguer** [comment]
After some research, I want to bundle this with the "ignore failing packages" feature #1126 as the changes that will allow this will also allow that one

**Comment by Jguer** [comment]
implemented in `yay-git`

```json
  "newinstallengine": true,
```

in config will trigger this behavior (check `yay -Pg` for current config)
