### ISSUE TITLE
How to compile Yay as root, and is there any way to get pre-compiled packages ?

### ISSUE THREAD

**Issue by LothaireCliquennois** [Jguer/yay#1249]
Basically, everything's in the title, and it couldn't be more clear.

**Comment by Jguer** [comment]
1. http://allanmcrae.com/2015/01/replacing-makepkg-asroot/
2. https://github.com/WhyNotHugo/docker-makepkg/blob/master/Dockerfile - fair enough example
- Not possible, not my choice 

2. I don't host any repo with `yay` closest you can get is just getting the static binary from Releases
