### ISSUE TITLE
Newlines after questions

### ISSUE THREAD

**Issue by muesli** [Jguer/yay#125]
Is it intentional that yay now prints a newline after each question?

```
==> yay Directory exists. Clean Build? [y/N] 
y

==> Proceed with download? [Y/n] 

Downloading: yay-2.300-1
==> yay Edit PKGBUILD? [y/N] 

==> Proceed with install? [Y/n] 

==> Making package: yay 2.300-1 (Wed 31 Jan 18:16:27 CET 2018)
```

I don't mind too much one way or another (I think it looked a bit tidier before, though). I'm just not sure if the changed behavior is a bug or intentional.

Keep up the great work!

**Comment by Jguer** [comment]
Was me fixing colors, should work as expected now
