### ISSUE TITLE
Installation fails with lates build

### ISSUE THREAD

**Issue by abkrahn** [Jguer/yay#1250]
#### Issue
  -> Extracting yay-9.4.6.tar.gz with bsdtar
==> Starting build()...
go build -v -mod=mod -ldflags '-s -w -linkmode external -extldflags "-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now" -X "main.version=9.4.6"' -modcacherw -gcflags all=-trimpath=/home/andy/yay/src/yay-9.4.6 -asmflags all=-trimpath=/home/andy/yay/src/yay-9.4.6 -o yay
flag provided but not defined: -mod
usage: build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
make: *** [Makefile:49: yay] Error 2
==> ERROR: A failure occurred in build().

#### Steps to reproduce

1.
2.
3.

**Comment by Jguer** [comment]
2 Possible issues
Either you're not on `go 1.14` or you're using `gcc-go` which hasn't been update to `go 1.14`. Try a `sudo pacman -S go` before

**Comment by abkrahn** [comment]
Seems like I have the right version, but I also have /opt/go  which seems to contain the source..
[andy@thor ~]$ cat .bashrc
export GOPATH=/home/andy/git
export GOROOT=/opt/go/
export PATH=/usr/bin/go:/home/andy/bin:$PATH

/usr/bin/go  contains the 1.14.2 build.
andy@thor ~]$ go version
go version go1.14.2 linux/amd64

go build -v -mod=mod -ldflags '-s -w -linkmode external -extldflags "-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now" -X "main.version=9.4.6"' -modcacherw -gcflags all=-trimpath=/home/andy/.cache/yay/yay/src/yay-9.4.6 -asmflags all=-trimpath=/home/andy/.cache/yay/yay/src/yay-9.4.6 -o yay
go: downloading github.com/Jguer/go-alpm v0.0.0-20191122171459-5cffc6e8fc69
go: downloading github.com/mikkeloscar/aur v0.0.0-20200113170522-1cb4e2949656
go: downloading github.com/Morganamilo/go-pacmanconf v0.0.0-20180910220353-9c5265e1b14f
go: downloading github.com/Morganamilo/go-srcinfo v1.0.0
callbacks.go:4:2: package bufio is not in GOROOT (/usr/bin/src/bufio)
config.go:5:2: package bytes is not in GOROOT (/usr/bin/src/bytes)
config.go:6:2: package encoding/json is not in GOROOT (/usr/bin/src/encoding/json)
print.go:6:2: package encoding/xml is not in GOROOT (/usr/bin/src/encoding/xml)
../gopath/pkg/mod/github.com/!jguer/go-alpm@v0.0.0-20191122171459-5cffc6e8fc69/types.go:14:2: package errors is not in GOROOT (/usr/bin/src/errors)
callbacks.go:5:2: package fmt is not in GOROOT (/usr/bin/src/fmt)
parser.go:7:2: package html is not in GOROOT (/usr/bin/src/html)
../gopath/pkg/mod/github.com/!jguer/go-alpm@v0.0.0-20191122171459-5cffc6e8fc69/db.go:17:2: package io is not in GOROOT (/usr/bin/src/io)
../gopath/pkg/mod/github.com/!morganamilo/go-pacmanconf@v0.0.0-20180910220353-9c5265e1b14f/ini/ini.go:5:2: package io/ioutil is not in GOROOT (/usr/bin/src/io/ioutil)
pkg/completion/completion.go:6:2: package net/http is not in GOROOT (/usr/bin/src/net/http)
../gopath/pkg/mod/github.com/mikkeloscar/aur@v0.0.0-20200113170522-1cb4e2949656/aur.go:7:2: package net/url is not in GOROOT (/usr/bin/src/net/url)
pkg/completion/completion.go:7:2: package os is not in GOROOT (/usr/bin/src/os)
../gopath/pkg/mod/github.com/!morganamilo/go-pacmanconf@v0.0.0-20180910220353-9c5265e1b14f/cmd.go:5:2: package os/exec is not in GOROOT (/usr/bin/src/os/exec)
pkg/completion/completion.go:8:2: package path/filepath is not in GOROOT (/usr/bin/src/path/filepath)
../gopath/pkg/mod/github.com/!jguer/go-alpm@v0.0.0-20191122171459-5cffc6e8fc69/types.go:16:2: package reflect is not in GOROOT (/usr/bin/src/reflect)
package github.com/Jguer/yay/v9
	imports runtime: cannot find package
package github.com/Jguer/yay/v9
	imports github.com/Jguer/go-alpm
	imports runtime/cgo: cannot find package
depPool.go:4:2: package sort is not in GOROOT (/usr/bin/src/sort)
pkg/intrange/intrange.go:4:2: package strconv is not in GOROOT (/usr/bin/src/strconv)
pkg/intrange/intrange.go:5:2: package strings is not in GOROOT (/usr/bin/src/strings)
pkg/multierror/multierror.go:3:8: package sync is not in GOROOT (/usr/bin/src/sync)
package github.com/Jguer/yay/v9
	imports github.com/Jguer/go-alpm
	imports syscall: cannot find package
../gopath/pkg/mod/github.com/!jguer/go-alpm@v0.0.0-20191122171459-5cffc6e8fc69/package.go:30:2: package time is not in GOROOT (/usr/bin/src/time)
pkg/intrange/intrange.go:6:2: package unicode is not in GOROOT (/usr/bin/src/unicode)
../gopath/pkg/mod/github.com/!jguer/go-alpm@v0.0.0-20191122171459-5cffc6e8fc69/alpm.go:13:8: cannot find package "unsafe" in any of:
	/usr/bin/src/unsafe (from $GOROOT)
	/home/andy/.cache/yay/yay/src/gopath/src/unsafe (from $GOPATH)
make: *** [Makefile:49: yay] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
Error making: yay
