### ISSUE TITLE
Paginate searches

### ISSUE THREAD

**Issue by albfan** [Jguer/yay#1252]
#### Affected Version

```
$ yay -V
yay v9.4.6 - libalpm v12.0.1
```

#### Issue

paginate search can be done with:

    unbuffer yay -Ss <whatever> | less -r

**NOTE**: `unbuffer` and `-r` was added because `pacman.conf` has `Color` enabled.

As look for packages coincidences is a typical operation offer directly from yay could be helpful.

Not sure if pacman.conf should be the place for a `Pager=yes/no` `PagerCommand=less -R` or similar.

If implemented, this could be offered to override defaults:

    PAGER="less -r" yay -Ss <whatever>
    yay --pager -Ss <whatever>
    yay --no-pager -Ss <whatever>

#### Steps to reproduce

    yay -Ss <whatever>

is not paginated

**Comment by Jguer** [comment]
Hey, thanks for the suggestion,

I don't really want to include more shell outs on yay than needed, I think if command chaining works it should be preferred to adding more flags

**Comment by albfan** [comment]
Sure. Paginating is really common for command line, but I see your point.

Hope this helps others.
