### ISSUE TITLE
preserve go-cache between builds

### ISSUE THREAD

**Issue by RubenKelevra** [Jguer/yay#1254]
#### Affected Version
yay v9.4.6 - libalpm v12.0.1

#### Issue
I maintain a go package and I like to preserve the go cache to avoid having to download/rebuild all dependencies on each build.

Currently, the ${srcdir} will be cleared, when I create a folder for the go dependencies there yay will remove it.

Makepkg, on the other hand, preserves the folder and thus avoids that it has to be refetched and rebuild.

Is there a way to have a permanent cache folder?

**Comment by RubenKelevra** [comment]
I found a solution:

https://aur.archlinux.org/cgit/aur.git/commit/?h=go-ipfs-git&id=69b1336e7691185beb7506a1ee967f5055b63c3f

**Comment by Jguer** [comment]
This doesn't seem like a great thing to integrate on the `yay` PKGBUILD

I'll check if we can change `  export GOPATH="$srcdir"/gopath` to only set itself if not set, this would make people who set their `GOPATH` to actually use it

**Comment by RubenKelevra** [comment]
> I'll check if we can change ` export GOPATH="$srcdir"/gopath` to only set itself if not set, this would make people who set their `GOPATH` to actually use it

Well, my issue with that approach is, that you fill the global gopath with dependencies of packages you might have already removed from the system and it never gets cleaned up again.

Also a clean build request won't recompile the gopath packages.

The best thing would be to have yay create its own gopath and remove the dependencies for this one package with something like
`go clean -modcache -r "github.com/ipfs/go-ipfs/cmd/ipfs"`
or
`go clean -cache -r "github.com/ipfs/go-ipfs/cmd/ipfs"`
if there's a clean-build request.

This would reduce the necessary disk space if there are multiple packages using the same dependencies.

**Comment by RubenKelevra** [comment]
I think the easiest solution would be to map a yay go-cache with a symlink to "$srcdir"/gopath when building a go-package and set the go-path accordingly.

This way yay can remove the symlink afterward, but the go cache stays intact.

When the package should be clean build, we can run go clean for the specific application, to clean this part of the cache.
