### ISSUE TITLE
automatically skip & use own config

### ISSUE THREAD

**Issue by dkwo** [Jguer/yay#1255]
Not a bug, just a question (actually two):
1. is there a way to automatically skip updating a certain package (mathematica in my case)?
2. I have two packages (dwm and st) for which I use my own config: is there a way to tell yay to use it? at the moment I just get
`WARNING: This package can be configured in config.h. Copy the config.def.h that was just placed into the package directory to config.h and modify it to change the configuration. Or just leave it alone to continue to use default values.`

Thanks.

**Comment by Kattus** [comment]
For your first question, you can add it to `IgnorePkg` in pacman.conf.
For the second one.. don't think so, but don't quote me on that.

**Comment by dkwo** [comment]
Thank you.

>
