### ISSUE TITLE
Some complicated file ownership resolution problem

### ISSUE THREAD

**Issue by buckle2000** [Jguer/yay#1256]
#### Affected Version
yay v9.4.6 - libalpm v12.0.1 (not git version)

#### Issue
Let's say we have package A from AUR, package B from official repo, say, `community`.
Version 1 of A owns some file.
Version 2 of A depends on B but doesn't depend on that file. B owns that file.
When updating A, yay first invokes pacman to install B, and **then** installs the newer A. However, pacman is confused by this because it doesn't know package A nor the change of ownship of that file.

#### Steps to reproduce

1. Install `qmk 0.0.31-2` from AUR (remove `community/yapf` if it is installed)
2. Install `qmk 0.0.33-2` from AUR

#### Output
The output is something like this:
```
> pacman -S --needed yapf
Cannot install yapf because
/usr/lib/python3.8/site-packages/yapf/... (owned by qmk)
... (many lines like above) ...
```

#### Current workaround
Delete all of the files owned by the older package A, then run `yay -S A` again.

**Comment by Jguer** [comment]
This seems to me like a naughty package that's installing things it shouldn't, in that example it seems qmk is installing `yapf`.

It seems very right not to overwrite a file if it's installed by another package.

**Comment by buckle2000** [comment]
But shouldn't yay deal with this kind of problem by installing packages from AUR and official repo in a single pass?

`qmk` simply made those files to be handled by a new dependency, instead of vendor those files itself.
