### ISSUE TITLE
v8-r failing to build in yay, successful with makepkg

### ISSUE THREAD

**Issue by josswright** [Jguer/yay#1257]
#### Affected Version
`yay v9.4.6.r5.gddd1cc3 - libalpm v12.0.1`

#### Issue

The v8-r package from the AUR fails to build under `yay`, but works fine with makepkg.

The aur page at: https://aur.archlinux.org/packages/v8-r/ is recommending that, for yay, users just use `yay -G v8-r`, then build and install manually. There is some accurate-looking discussion of the problem there, but I couldn't see it reported as an issue here.
   

#### Steps to reproduce
`yay -S v8-r`

#### Output
The full output is huge, but the relevant part seems to be here:

    FAILED: libv8_libbase.so libv8_libbase.so.TOC 
    python "../../build/toolchain/gcc_solink_wrapper.py" --readelf="readelf" --nm="nm" --sofile="./libv8_libbase.so" --tocfile="./libv8_libbase.so.TOC" --output="./libv8_libbase.so" -- ../../../../../../../../../usr/bin/clang++ -shared -Wl,-soname="libv8_libbase.so" -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,defs -Wl,--as-needed -fuse-ld=lld -Wl,--icf=all -Wl,--color-diagnostics -m64 -rdynamic -Wl,-rpath=\$ORIGIN -Wl,-O2 -Wl,--gc-sections -o "./libv8_libbase.so" @"./libv8_libbase.so.rsp"
    Traceback (most recent call last):
      File "../../build/toolchain/gcc_solink_wrapper.py", line 151, in <module>
        sys.exit(main())
      File "../../build/toolchain/gcc_solink_wrapper.py", line 134, in main
        result, toc = CollectTOC(args)
      File "../../build/toolchain/gcc_solink_wrapper.py", line 44, in CollectTOC
        result, toc = CollectSONAME(args)
      File "../../build/toolchain/gcc_solink_wrapper.py", line 27, in CollectSONAME
        if 'SONAME' in line:
    TypeError: a bytes-like object is required, not 'str'
    [128/1671] CXX obj/src/inspector/inspector/v8-debugger.o
    [129/1671] CXX obj/test/unittests/cppgc_unittests_sources/garbage-collected_unittest.o
    [130/1671] CXX obj/test/unittests/cppgc_unittests_sources/gc-info_unittest.o
    [131/1671] CXX obj/src/inspector/inspector/v8-inspector-impl.o
    [132/1671] CXX obj/src/inspector/inspector/v8-debugger-agent-impl.o
    ninja: build stopped: subcommand failed

**Comment by Jguer** [comment]
`v8-r` uses variable exports in prepare

```
  export CC=/usr/bin/clang
  export CXX=/usr/bin/clang++

  # Switching to python2 system environment
  mkdir -p bin
  ln -sf /usr/bin/python2 ./bin/python
  ln -sf /usr/bin/python2-config ./bin/python-config
  msg2 "Using: `which python`"

  export PATH=${srcdir}/bin:`pwd`/depot_tools:"$PATH"
  export GYP_GENERATORS=ninja

```

That are not carried over to `build()` since we separate prepare and build stages.

probably
```
  export CC=/usr/bin/clang
  export CXX=/usr/bin/clang++
```

needs to be added to build()

**Comment by josswright** [comment]
Fantastic! Thank you for that.

For reference, it seems that the main issue is with the `ninja` tool not being made available in the `build()` step. I added all the exports in and it's just finished compiling in `yay`. (I suspect that only the final two might be required, but it didn't hurt to add them all.)

To be absolutely clear to anyone finding this issue, adding:

    export CC=/usr/bin/clang
    export CXX=/usr/bin/clang++

    export PATH=${srcdir}/bin:`pwd`/depot_tools:"$PATH"
    export GYP_GENERATORS=ninja

at the start of the `build()` function in the PKGBUILD made it work for me.

**Comment by josswright** [comment]
As the v8 packager is making it a point of pride that he doesn't support AUR helpers and so won't update the PKGBUILD, how fundamental is this separation of `prepare()` and `build()` to `yay`? Would it be possible for `yay` to carry over variable exports?

While this is just annoying in this case, I can imagine that other packages could easily cause the same problem. Is there anything bad that would happen if `yay` were to mimic the `makepkg` behaviour?

**Comment by Jguer** [comment]
Yay does mimic `makepkg` behaviour.
https://github.com/Jguer/yay/issues/893

**Comment by josswright** [comment]
Hi. I didn't mean to imply that yay wasn't behaving correctly. This specific case, though, is an `EXPORT` in the `prepare()` function that isn't then carried over to the `build()` function. This makes the PKGBUILD work in `makepkg` but fail in `yay`.

I was wondering whether there was any way to carry over the environment from `prepare()` to `build()`. The package author's argument is that because it works in `makepkg` he's not willing to alter the PKGBUILD to make it work in `yay`.

**Comment by josswright** [comment]
Okay, as `makepkg` has a `--noextract` option that runs the `build()` without `prepare()`, I'm going to try the argument to the package maintainer that this actually is a buggy PKGBUILD.
