### ISSUE TITLE
Option for bell/urgent when there is a prompt?

### ISSUE THREAD

**Issue by mxmilkb** [Jguer/yay#1258]
This would be handy in case the terminal is hidden.

(I have a terminal setup to make a bell an urgent.)

**Comment by Jguer** [comment]
duplicate #1031

**Comment by mxmilkb** [comment]
I was more thinking of Y/n prompts, and things happening at some random point during a big AUR update.

**Comment by drws** [comment]
@Jguer would you please review this one, especially in light of the comment above. It seems the issue was both duped and closed prematurely. It wouldn't be bad to have bell support in Yay for **all** prompts.
