### ISSUE TITLE
Suggestion: Make it possible to enable batchinstall by default 

### ISSUE THREAD

**Issue by LeSnake04** [Jguer/yay#1259]
I love the batchinstall command and would really appreciate when yay would create an /etc/yay.conf file, where I can add batchinstall=1 and all aur install using --batchinstall, execpt I add --nobatchinstall

**Comment by Jguer** [comment]
`yay -Y --batchinstall --save` should write to your `~/.config/yay/yay.json` that setting so it is used by default

**Comment by LeSnake04** [comment]
very nice option!
