### ISSUE TITLE
sudoloop asks for a password, even if user has password-less sudo

### ISSUE THREAD

**Issue by davidmehren** [Jguer/yay#1261]
#### Affected Version
`yay v9.4.7.r7.gdb3993b - libalpm v12.0.1`

#### Issue
If a user can use `sudo` without entering the password and has `sudoloop` enabled, `yay` nevertheless asks for a password.

The reason seems to be that `yay` uses `sudo -v`, which *always* asks for a password.

I'm not sure what would be a good solution to this problem, everything I can come up with is quite hacky (e.g. trying if `sudo whoami` returns `root` before running `sudo -v` for the first time).

#### Steps to reproduce
1. Enable password-less sudo for your user (e.g. add `<username> ALL=(ALL) NOPASSWD: ALL` to `/etc/sudoers`
2. Verify that you don't need to enter a password to use sudo.
3. Run an action in `yay` with `sudoloop` enabled, e.g. `yay -Syu --sudoloop`
4. You will be asked to enter your password.

**Comment by Jguer** [comment]
Well, it is indeed a bug, but a user without sudo password should not need sudoloop and it is turned off by default. 

It's a bit like turning the safety off, shooting yourself in the foot and then blaming the gun for having fired ( a better analogy may be needed).

If there's no easy unhacky fix for this I'm okay with leaving it with no fix.
