### ISSUE TITLE
cannot remove .cache/yay/(random)/: Permission denied

### ISSUE THREAD

**Issue by bcookatpcsd** [Jguer/yay#1264]
#### Affected Version

yay v9.4.7 - libalpm v12.0.1

#### Issue
building git packages with yay, leaves behind files the user cannot delete.

I built coredns-git and dnscrypt-proxy-git and the cache files 

  File: gen.go
  Size: 3215            Blocks: 8          IO Block: 4096   regular file
Device: 804h/2052d      Inode: 410463223   Links: 1
Access: (0444/-r--r--r--)  Uid: ( 1000/   user)   Gid: ( 1000/   user)
Access: 2020-05-08 11:50:05.140442459 -0400
Modify: 2020-05-08 11:50:05.140442459 -0400
Change: 2020-05-08 11:50:05.140442459 -0400
 Birth: 2020-05-08 11:50:05.140442459 -0400

/home/user/.cache/yay/dnscrypt-proxy-git/src/gopath/pkg/mod/golang.org/x/text@v0.3.2/width

 rm gen.go
rm: cannot remove 'gen.go': Permission denied

rm: remove write-protected regular file 'gen.go'? y
rm: cannot remove 'gen.go': Permission denied

#### Steps to reproduce

1. yay -S dnscrypt-proxy-git
2.
3.

**Comment by Jguer** [comment]
They use `  go build -ldflags="-s -w"` to build which defaults mod cache to readonly.

yay, for example, uses: `-modcacherw` to allow the cache to be removed. `git clean` respects file permissions and I don't think we should remove files which are marked as non removable. 

For me this is a PKGBUILD issue

**Comment by bcookatpcsd** [comment]
Thank you for the explanation and the response.. I wanted to mention that this never happened before.. since the last upgrade/update it has been.. 

Does that make a difference?

Thanks in advance.

**Comment by Jguer** [comment]
Probably because either they changed their dependency vendoring, either it was because the go cache mechanism, changed on `go1.13`, kicked in since you only recompiled the package after that update
