### ISSUE TITLE
Remove package from yay control/installed list

### ISSUE THREAD

**Issue by CactiChameleon9** [Jguer/yay#1266]
There is a packages I have installed a fork of (from github), as the old one is no longer maintained.... but yay prompts me to update it as the version code style is different (that's good normally). Is there any way I can stop yay from knowing it installed that package and therefore asking to update?

**Comment by Jguer** [comment]
:slightly_smiling_face: add it to the IgnorePkg of `/etc/pacman.conf`

**Comment by CactiChameleon9** [comment]
Even if is an aur package?

**Comment by Jguer** [comment]
yes, yay reads `/etc/pacman.conf` for those and options such as Color
