### ISSUE TITLE
[RFC] add --save option

### ISSUE THREAD

**Issue by Morganamilo** [Jguer/yay#127]
Only update the config file if `--save` is passed. Most of the time I and I assume others will setup a program how they like it and rarely ever change.

For example I like to keep `devel` off but sometimes I will check devel updates causing my config file to change. I could instead turn devel off with `yay --nodevel --save`. Then use yay normally and when I do want a devel update just do `yay -Syu --devel` without worrying about it sticking.

**Comment by Jguer** [comment]
Still don't have an opinion on this, I like yay's dynamic config as it is, I usually leave devel off and now sometimes I just use `yay -Syu --devel` and then `yay -Pg --nodevel`. 

I think a `--nosave` would be more useful for me than a `--save` but I really have no preference

**Comment by Morganamilo** [comment]
`--nosave` could work just as well as save. I think I still prefer `--save` though.

I have some plans to change how the config works and add a bunch of --flags. I'll be submitting an issue on it when I have it all thought out which will probably be a while. I think I'll close this for now and come back to It at a later time when I have more of a plan.
