### ISSUE TITLE
Retry sudo if timed out reading password or use GUI sudo if available

### ISSUE THREAD

**Issue by gabrc52** [Jguer/yay#1272]
#### Affected Version

yay v9.4.6 - libalpm v12.0.1

#### Issue

Since yay discourages running as root, I ran it as a normal user, and let it build my package in the background. When I returned to my terminal I found out yay was asking for my sudo password. Now I have to install my package again and wait for about 2 hours unless it's cached somewhere.

To improve user friendliness, I suggest retrying until the password is given, and use a GUI version of sudo such as pkexec / kdesu / gksu if ran on a GUI Desktop environment.

Where are the `.pkg.tar.xz` packages stored by `yay`? 

#### Steps to reproduce
1. Run`yay -S packagename`
2. Interact with it so it starts building the package
3. Don't do anything

#### Output

```
...
==> Leaving fakeroot environment.
==> Finished making: eclipse 4.15-6 (Thu 21 May 2020 07:54:01 PM CDT)
==> Cleaning up...
[sudo] password for gabriel: 
sudo: timed out reading password
```

**Comment by Jguer** [comment]
by default packages are stored in `~/.cache/yay/`

- sudo can be changed with `--sudobin gksu` and `--sudoargs=` (add --save to make it permanent, I don't know what `sudoargs` it would need)
- `--sudoloop` can be used to ask sudo at the beginning and letting it loop (not very secure, depends on your threat model)

**Comment by kuvaldini** [comment]
is there a way to configure sudo timeout to 36000sec?
