### ISSUE TITLE
Implement search and install by pkgbase

### ISSUE THREAD

**Issue by CHN-beta** [Jguer/yay#1273]
#### Affected Version
yay v9.4.7 - libalpm v12.0.1

#### Issue

Could not find AUR package `intel-parallel-studio-xe` using following command:

```bash
yay -Ss intel-parallel-studio-xe
```

`yay -S intel-parallel-studio-xe` also run in error.

But the package is actually in AUR:

https://aur.archlinux.org/pkgbase/intel-parallel-studio-xe

#### Steps to reproduce

Simply type `yay -Ss intel-parallel-studio-xe` then press Enter.

#### Output

There is no output.

yay config:

```bash
{
        "aururl": "https://aur.archlinux.org",
        "buildDir": "/home/chn/.cache/yay",
        "absdir": "/home/chn/.cache/yay/abs",
        "editor": "",
        "editorflags": "",
        "makepkgbin": "makepkg",
        "makepkgconf": "",
        "pacmanbin": "pacman",
        "pacmanconf": "/etc/pacman.conf",
        "redownload": "no",
        "rebuild": "no",
        "batchinstall": false,
        "answerclean": "",
        "answerdiff": "",
        "answeredit": "",
        "answerupgrade": "",
        "gitbin": "git",
        "gpgbin": "gpg",
        "gpgflags": "",
        "mflags": "",
        "sortby": "votes",
        "searchby": "name-desc",
        "gitflags": "",
        "removemake": "ask",
        "sudobin": "sudo",
        "sudoflags": "",
        "requestsplitn": 150,
        "sortmode": 0,
        "completionrefreshtime": 7,
        "sudoloop": false,
        "timeupdate": false,
        "devel": false,
        "cleanAfter": false,
        "provides": true,
        "pgpfetch": true,
        "upgrademenu": true,
        "cleanmenu": true,
        "diffmenu": true,
        "editmenu": false,
        "combinedupgrade": false,
        "useask": false
}
```

**Comment by Jguer** [comment]
https://aur.archlinux.org/packages/?O=0&SeB=nd&K=intel-parallel-studio-xe&outdated=&SB=n&SO=a&PP=50&do_Search=Go - is not found by AUR web

**Comment by CHN-beta** [comment]
> https://aur.archlinux.org/packages/?O=0&SeB=nd&K=intel-parallel-studio-xe&outdated=&SB=n&SO=a&PP=50&do_Search=Go - is not found by AUR web

So, it is a bug of AUR?

**Comment by Raymo111** [comment]
Can we reopen this issue? I'd like to see support for pkgbases added.

**Comment by Raymo111** [comment]
unstale

**Comment by Jguer** [comment]
I'm setting it as approved as I'd like to see this feature, but this needs to be implemented upstream (from previous research and a fast test right now 2022/02/11)

EDIT.PS: setting it as approved will stop stale bot from going rogue

**Comment by Raymo111** [comment]
Thanks!

**Comment by Jguer** [comment]
Closing as this has not been implemented by the RPC, this would be possible to implement in the metadata client but would cause it to have a "by" extension that the RPC client does not support
