### ISSUE TITLE
i/o timeout when building yay (proxy blocked)

### ISSUE THREAD

**Issue by WingDust** [Jguer/yay#1278]
#### Affected Version
  
  yay 9.4.7-1 
 

#### Steps to reproduce

 ```
[wingdust@cw soft]$ git clone https://aur.archlinux.org/yay.git
正克隆到 'yay'...
remote: Enumerating objects: 311, done.
remote: Counting objects: 100% (311/311), done.
remote: Compressing objects: 100% (225/225), done.
remote: Total 311 (delta 83), reused 311 (delta 83), pack-reused 0
接收对象中: 100% (311/311), 65.09 KiB | 0 字节/秒, 完成.
处理 delta 中: 100% (83/83), 完成.
[wingdust@cw soft]$ cd yay
[wingdust@cw yay]$ makepkg -si
==> 正在创建软件包：yay 9.4.7-1 (2020年05月27日 星期三 21时48分45秒)
==> 正在检查运行时依赖关系...
==> 正在检查编译时依赖关系
==> 获取源代码...
  -> 正在下载 yay-9.4.7.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   117  100   117    0     0     90      0  0:00:01  0:00:01 --:--:--    90
100  295k  100  295k    0     0   5171      0  0:00:58  0:00:58 --:--:--  2893
==> 正在验证 source 文件，使用sha256sums...
    yay-9.4.7.tar.gz ... 通过
==> 正在释放源码...
  -> 正在解压缩 yay-9.4.7.tar.gz，使用 bsdtar
==> 正在开始 build()...
go build -v -mod=mod -ldflags '-s -w -linkmode external -extldflags "-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now" -X "main.version=9.4.7"' -modcacherw -trimpath -o yay
go: github.com/Jguer/go-alpm@v0.0.0-20191122171459-5cffc6e8fc69: Get "https://proxy.golang.org/github.com/%21jguer/go-alpm/@v/v0.0.0-20191122171459-5cffc6e8fc69.mod": dial tcp 34.64.4.81:443: i/o timeout
make: *** [Makefile:50：yay] 错误 1
==> 错误： 在 build() 中发生一个错误。
    正在放弃...

```

**Comment by WingDust** [comment]
go version 
![image](https://user-images.githubusercontent.com/45911286/83035315-df81ec00-a06b-11ea-9102-586db9831004.png)

**Comment by ekvch** [comment]
Hi, have you had any luck installing yay since? I tried to reproduce the issue and installed it under the same instructions without any problems. 

That seems to be a glitch unrelated to yay itself. According to [a similar issue filed for golang](https://github.com/golang/go/issues/34548) it's probably a connection bug and hopefully a one-off error.

**Comment by WingDust** [comment]
can i install in other way

**Comment by WingDust** [comment]
I reinstalled it from [archlinuxcn / repo](https://github.com/archlinuxcn/repo) It installed work , I think Should add to README.md for Chinese Beginner.

**Comment by WingDust** [comment]
> Hi, have you had any luck installing yay since? I tried to reproduce the issue and installed it under the same instructions without any problems.
> 
> That seems to be a glitch unrelated to yay itself. According to [a similar issue filed for golang](https://github.com/golang/go/issues/34548) it's probably a connection bug and hopefully a one-off error.

**Comment by ekvch** [comment]
> can i install in other way

If there's another AUR helper you can install you can install yay from the AUR with that

**Comment by Jguer** [comment]
Probably the default `GOPROXY` is not connecting to your location, try setting an environment variable `GOPROXY`

for example:
```
echo "export GOPROXY=https://goproxy.cn" >> ~/.profile
source ~/.profile
```

**Comment by WingDust** [comment]
[wingdust@cw yay]$ makepkg -si 
==> 正在创建软件包：yay 9.4.7-1 (2020年05月29日 星期五 16时15分11秒)
==> 正在检查运行时依赖关系...
==> 正在检查编译时依赖关系
==> 获取源代码...
  -> 找到 yay-9.4.7.tar.gz
==> 正在验证 source 文件，使用sha256sums...
    yay-9.4.7.tar.gz ... 通过
==> 正在释放源码...
  -> 正在解压缩 yay-9.4.7.tar.gz，使用 bsdtar
==> 正在删除现存的 $pkgdir/ 目录...
==> 正在开始 build()...
go build -v -mod=mod -ldflags '-s -w -linkmode external -extldflags "-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now" -X "main.version=9.4.7"' -modcacherw -trimpath -o yay
go: downloading github.com/mikkeloscar/aur v0.0.0-20200113170522-1cb4e2949656
go: downloading github.com/Jguer/go-alpm v0.0.0-20191122171459-5cffc6e8fc69
go: downloading golang.org/x/crypto v0.0.0-20200317142112-1b76d66859c6
go: downloading github.com/Morganamilo/go-srcinfo v1.0.0
go: downloading github.com/Morganamilo/go-pacmanconf v0.0.0-20180910220353-9c5265e1b14f
go: downloading golang.org/x/sys v0.0.0-20190412213103-97732733099d
unicode
internal/race
runtime/internal/sys
internal/cpu
runtime/internal/atomic
sync/atomic
runtime/internal/math
unicode/utf8
encoding
math/bits
internal/testlog
unicode/utf16
container/list
internal/bytealg
math
crypto/internal/subtle
runtime/cgo
crypto/subtle
vendor/golang.org/x/crypto/cryptobyte/asn1
internal/nettrace
runtime
vendor/golang.org/x/crypto/internal/subtle
github.com/Jguer/yay/v9/pkg/stringset
sync
internal/reflectlite
github.com/Jguer/yay/v9/pkg/multierror
internal/singleflight
math/rand
errors
sort
io
strconv
internal/oserror
vendor/golang.org/x/net/dns/dnsmessage
syscall
bytes
hash
strings
hash/crc32
crypto/internal/randutil
reflect
crypto
crypto/hmac
bufio
crypto/rc4
vendor/golang.org/x/text/transform
vendor/golang.org/x/crypto/hkdf
path
github.com/Jguer/yay/v9/pkg/intrange
html
time
internal/syscall/execenv
internal/syscall/unix
internal/fmtsort
encoding/binary
context
internal/poll
encoding/base64
crypto/cipher
crypto/md5
crypto/sha512
crypto/ed25519/internal/edwards25519
os
crypto/sha1
crypto/sha256
encoding/pem
crypto/aes
crypto/des
vendor/golang.org/x/crypto/chacha20
vendor/golang.org/x/crypto/poly1305
vendor/golang.org/x/sys/cpu
path/filepath
fmt
net
vendor/golang.org/x/crypto/chacha20poly1305
os/exec
io/ioutil
github.com/Morganamilo/go-pacmanconf/ini
encoding/json
encoding/xml
github.com/Jguer/go-alpm
compress/flate
math/big
compress/gzip
encoding/hex
net/url
vendor/golang.org/x/crypto/curve25519
log
vendor/golang.org/x/text/unicode/norm
vendor/golang.org/x/text/unicode/bidi
vendor/golang.org/x/net/http2/hpack
crypto/rand
crypto/elliptic
encoding/asn1
crypto/ed25519
crypto/rsa
crypto/dsa
vendor/golang.org/x/text/secure/bidirule
vendor/golang.org/x/net/idna
mime
mime/quotedprintable
crypto/ecdsa
crypto/x509/pkix
vendor/golang.org/x/crypto/cryptobyte
net/http/internal
github.com/Morganamilo/go-pacmanconf
github.com/Morganamilo/go-srcinfo
vendor/golang.org/x/net/http/httpproxy
net/textproto
golang.org/x/sys/unix
crypto/x509
vendor/golang.org/x/net/http/httpguts
mime/multipart
crypto/tls
golang.org/x/crypto/ssh/terminal
net/http/httptrace
net/http
github.com/mikkeloscar/aur
github.com/Jguer/yay/v9/pkg/completion
github.com/Jguer/yay/v9
==> 正在进入 fakeroot 环境...
==> 正在开始 package()...
install -Dm755 yay /home/wingdust/soft/yay/pkg/yay/usr/bin/yay
install -Dm644 doc/yay.8 /home/wingdust/soft/yay/pkg/yay/usr/share/man/man8/yay.8
install -Dm644 completions/bash /home/wingdust/soft/yay/pkg/yay/usr/share/bash-completion/completions/yay
install -Dm644 completions/zsh /home/wingdust/soft/yay/pkg/yay/usr/share/zsh/site-functions/_yay
install -Dm644 completions/fish /home/wingdust/soft/yay/pkg/yay/usr/share/fish/vendor_completions.d/yay.fish
==> 正在清理安装...
  -> 正在删除 libtool 文件...
  -> 正在清除不打算要的文件...
  -> 正在移除静态库文件...
  -> 正在从二进制文件和库中清除不需要的系统符号...
  -> 正在压缩 man 及 info 文档...
==> 正在检查打包问题...
==> 正在创建软件包"yay"...
  -> 正在生成 .PKGINFO 文件...
  -> 正在生成 .BUILDINFO 文件...
  -> 正在生成 .MTREE 文件...
  -> 正在压缩软件包...
==> 正在离开 fakeroot 环境。
==> 完成创建：yay 9.4.7-1 (2020年05月29日 星期五 16时15分22秒)
==> 正在安装软件包 yay，使用 pacman -U...
[sudo] wingdust 的密码：
正在加载软件包...
警告：yay-9.4.7-1 已经为最新 -- 重新安装
正在解析依赖关系...
正在查找软件包冲突...

软件包 (1) yay-9.4.7-1

全部安装大小：  6.25 MiB
净更新大小：  0.00 MiB

:: 进行安装吗？ [Y/n] y
(1/1) 正在检查密钥环里的密钥                                                              [####################################################] 100%
(1/1) 正在检查软件包完整性                                                                [####################################################] 100%
(1/1) 正在加载软件包文件                                                                  [####################################################] 100%
(1/1) 正在检查文件冲突                                                                    [####################################################] 100%
(1/1) 正在检查可用存储空间                                                                [####################################################] 100%
:: 正在处理软件包的变化...
(1/1) 正在重新安装 yay                                                                    [####################################################] 100%
:: 正在运行事务后钩子函数...
(1/1) Arming ConditionNeedsUpdate...
@Jguer  It's work

**Comment by WingDust** [comment]
it's should be add README.md for Chinese beginner @Jguer

**Comment by Jguer** [comment]
`export GOPROXY="https://goproxy.io"` 
is `goproxy.io`unblocked and working @WingDust ?

**Comment by Alumniminium** [comment]
For my Iranian friends who can't use any of the above proxies: 
Have a pre-compiled package `wget https://cdn.her.st/bin/yay.tar && sudo pacman -U yay.tar`
**Everyone else please for the love of god, try the proxies first, I don't have unlimited bandwidth on that server and I'll most likely forget about this post**
