### ISSUE TITLE
light terminal background support

### ISSUE THREAD

**Issue by ijanos** [Jguer/yay#128]
Hi there, the current colors are pretty hard to read in a light-on-dark terminal. An alternative color setting would be appreciated. Cheers.

**Comment by Jguer** [comment]
Can you screenshot some of the current bad contrasts? I believe I know the cause of the problem

**Comment by ijanos** [comment]
Maybe the hard-to-read was a bit hyperbole on my part, sorry about that :) what the grey has really low contrast, the yellow is hard to read and some random things have a dark background, I don't know if that is intentional but it does not look good in my opinion. 

![yay1](https://user-images.githubusercontent.com/175447/35665354-36930966-0726-11e8-99e7-b624f83c8434.png)
![yay02](https://user-images.githubusercontent.com/175447/35665356-384a6e52-0726-11e8-942c-892aae5d64f3.png)
