### ISSUE TITLE
--overwrite flag not working at all

### ISSUE THREAD

**Issue by sovanyio** [Jguer/yay#1280]
#### Affected Version
yay v9.4.7 - libalpm v12.0.1

#### Issue
`--overwrite` flag is not working as expected. The same flag _does_ work with `pacman -S`. Noticed this after trying to move from a pip installed python package to the arch package. (Yes I am aware that `*` is not recommended but I JUST did this and feel that this one python package is a relatively safe usage :), other globs did not work either, including `*.py`, and `{package}/*.py`). My partner and I have been noticing this a lot recently, didn't see an existing issue that seemed relevant to this. For AUR packages, we have resorted to manually deleting the conflicting files (though the better way would be to find the cached package and use the working pacman command).

#### Steps to reproduce
1. Have a package file conflict
2. Attempt to install through yay via search, `yay python-matplotlib --overwrite '*'`.
3. Use pacman instead to avoid overwrite flag ignored `pacman -S python-matplotlib ---overwrite '*'`

#### Output
Don't think this is necessary, but the failure with yay and success with pacman are here: https://pastebin.com/tLTUgeMq

**Comment by gitfib** [comment]
I've just tried with `--needed` and indeed it doesn't pass the flags when searching
By the way, you can use `yay -S python-matplotlib --overwrite '*'` instead, which would work
