### ISSUE TITLE
I somehow broke ZSH tab completion

### ISSUE THREAD

**Issue by soup6020** [Jguer/yay#1287]
#### Affected Version
yay v9.4.7.r13.g11db63f - libalpm v12.0.1
#### Issue
ZSH completion no longer functions correctly for me. Pressing tab after `yay -S <letters here>` only leads to repo names being completed, not packages. This happened once in the past, and I don't remember how I managed to fix it. I've tried clearing the cache to no avail.

#### Config
```{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/ezra/.cache/yay",
	"absdir": "/home/ezra/.cache/yay/abs",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 1,
	"sudoloop": false,
	"timeupdate": false,
	"devel": true,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false
}```

**Comment by soup6020** [comment]
Option completion works, just not packages. Pacman completion functions perfectly.

**Comment by hughwilliams94** [comment]
I am currently seeing this too.

**Comment by soup6020** [comment]
![image](https://user-images.githubusercontent.com/26074452/84119062-b6a51380-a9e8-11ea-8aee-398b3d4a0618.png)

**Comment by Jguer** [comment]
Fixed in `yay-git`, you can do a `yay -Pcc` to force a refresh of the package cache used for completions.

**Comment by soup6020** [comment]
Working now, thanks

**Comment by ChasingZenith** [comment]
Today, I install yay following the instruction on README.md, but the completion does not work for me, even after `yay -Pcc`.
But I find that after I enable the zsh plugin `zsh-completions` in my `oh-my-zsh` configuration, completion works for me. So does `pikaur`.
