### ISSUE TITLE
Recent localisation changes breaks "is newer than" listing

### ISSUE THREAD

**Issue by kattjevfel** [Jguer/yay#1289]
#### Affected Version
yay v9.4.7.r15.g4af542e - libalpm v12.0.1

#### Issue
With 732f1a5412cd196433b960164c03e9a63d59c4bd or newer, the second "is newer than" listing (by yay) produces an extra newline:
```
:: Searching AUR for updates...
 -> babl: local (0.1.78-1) is newer than extra (0.1.74-1)

 -> gegl: local (0.4.24-1) is newer than extra (0.4.22-3)

 -> gimp: local (2.10.20-1) is newer than extra (2.10.18-8)

 -> iptables: local (1:1.8.5-2) is newer than core (1:1.8.5-1)

 -> lib32-dbus: local (1.12.18-1) is newer than multilib (1.12.16-2)

:: Checking development packages...
```
With db3993b83bff4ab250de7ee22b19a0998f73d3b3 or below it shows as it should.

**Comment by Jguer** [comment]
Sorrry, Is the presented text the desired behavior or the current behaviour

**Comment by kattjevfel** [comment]
Sorry for not being clear, the presented text is the current behavior.

**Comment by Jguer** [comment]
Can't confirm, the entry handled by `yay` seems fine. I think the ones you presented are handled by pacman 

```
$ yay -Syu                       
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Searching databases for updates...
:: Searching AUR for updates...
 -> yay: local (10.0.0-1) is newer than AUR (9.4.7-1)
:: Starting full system upgrade...
 there is nothing to do
```

**Comment by kattjevfel** [comment]
That wouldn't make any sense since downgrading yay to db3993b83bff4ab250de7ee22b19a0998f73d3b3 makes it behave as it should.

Here's yet another test (disabled testing repos to get some output): https://gist.github.com/kattjevfel/6e186703a6b7428ced1abb7330024b04
The first one is handled by pacman and the second by yay, maybe it only shows when multiple packages are listed?

Also tested without config.json so it's not my config.

**Comment by Jguer** [comment]
Ah, I think it may be the go-alpm callbacks, I'll have a look at it
