### ISSUE TITLE
[aur] bad format output -Si

### ISSUE THREAD

**Issue by papajoker** [Jguer/yay#1293]
#### Affected Version
yay v10.0.0 - libalpm v12.0.1

#### Issue

`-Si` aur only, return hidden char bold `\033[1m` before each field
so not same output for repo and aur !

```
LANG=C yay -Si castero daily-wallpaper-git faune-font pacman vlc | awk '/.Name/ {print $0}'
Name            : castero
Name            : daily-wallpaper-git
Name            : faune-font
```

```
LANG=C yay -Si castero daily-wallpaper-git faune-font pacman vlc | awk '/^Name/ {print $0}'
Name            : pacman
Name            : vlc
```

**Comment by bulletmark** [comment]
I call `yay` in a custom script which breaks with this new version. If you want to include formatting chars in the output can you please add a command line option to suppress them, e.g. like `--color=never` does.

**Comment by papajoker** [comment]
is no color but always bold ([1m) for field name
pkg/text/print.go [PrintInfoValue](https://github.com/Jguer/yay/blob/next/pkg/text/print.go#L48)()

**Comment by Jguer** [comment]
Fixed in https://github.com/Jguer/yay/commit/d0450179f9e11cb38aaa9e6cc6624e8b197f726b
