### ISSUE TITLE
[AUR] PKGBUILD adjustments for PIE executable

### ISSUE THREAD

**Issue by yochananmarqos** [Jguer/yay#1296]
#### Affected Version
10.0.0

#### Issue
There is no longer a `go-pie` Arch package as `go` now supports PIE. See the updated [Go package guidelines](https://wiki.archlinux.org/index.php/Go_package_guidelines).

```
  EXTRA_GOFLAGS="-trimpath -buildmode=pie -mod=readonly -modcacherw" \
```

**Comment by Jguer** [comment]
Fixed on https://github.com/Jguer/yay/commit/f0aa4e0b5a9935e7a50e9872464e6883b9fac5ac , should take place next release
