### ISSUE TITLE
Some messages are not visible when term have white background

### ISSUE THREAD

**Issue by gzugmeyer** [Jguer/yay#13]
For exemple, in LocalStatistics method, the warnings use black background color, and default foreground color. In a white on black term, the message is written black on black ! 

https://github.com/Jguer/yay/blob/1ebe472123fbb35c86f217e7e6df0b6dbedfe3c0/actions.go#L228

```go
fmt.Printf("\x1b[1;31;40mWarning: \x1B[1;33;40m%s\x1b[0;;40m is orphaned.\x1b[0m\n", res.Name)
```

**Comment by Jguer** [comment]
Forgot about light terminal users, will fix.
