### ISSUE TITLE
Colouring and blinking text to get user attention is not working

### ISSUE THREAD

**Issue by kirk86** [Jguer/yay#1301]
#### Affected Version
yay v9.4.7 - libalpm v12.0.1

#### Issue
Doesn't work similar to yaourt. Meaning that text is not properly colourised nor it blinks on important messages like out of data packages.

yay -Ss teamviewer

#### Output
![image](https://user-images.githubusercontent.com/2902390/84647348-36f0da80-aefb-11ea-99de-99070e5f2106.png)

**Comment by Jguer** [comment]
Hey, have you verified if colored output is enabled? https://github.com/Jguer/yay#yay-does-not-display-colored-output-how-do-i-fix-it

**Comment by kirk86** [comment]
Thanks, that did enable colours but there's no text blinking similar to yaourt, is there anything similar?

**Comment by papajoker** [comment]
not blink but colors, you can view [screenshots](https://github.com/Jguer/yay#images)

**Comment by kirk86** [comment]
@papajoker Yeah I understand, I thought maybe there was some hidden option to enable blinking similar to enabling colouring. Anyways I'm closing this for now since it seems like only colouring is supported.
