### ISSUE TITLE
[Feature] Diff view of PKGBUILD on upgrade

### ISSUE THREAD

**Issue by rporter220** [Jguer/yay#131]
I have begun to use yay as my primary AUR utility since pacaur is now unmaintained. 
This tool has been a great replacement!

One thing that I do miss is the ability to see the difference of a PKGBUILD file on an upgrade.

As suggested, I normally check out the PKGBUILD file to ensure that the download sources are good and to see that everything is generally in order. Currently, yay allows you to open an editor on installation/upgrade to review or modify the PKGBUILD file before installation. This is great for installations. On upgrades, I found it helpful for the diff between the new and old PKGBUILD to be shown so I could quickly see what was changed and not have to review the entire PKGBUILD file.

I could see this added two different ways, but open to discussion/thought

1. Default behavior that on upgrade it asks if you want to view the diff output (y/N). If N is chosen, the installation starts as it does now. If Y is chosen, the diff output is shown and an additional prompt is shown asking to edit the file.

2. Have this as an additional parameter that can be passed when an upgrade is called (--diff) or something like that.

With number 1, I know it would add an additional step for people that want to see the diff output, but for other users it would not add any additional steps. Also, I think the people looking at the diff output would think this was an acceptable trade off.

With number 2, The people that cared for this option could either use the parameter when calling yay or easily make an alias.

Thank you for your time and work that you do for the community.

**Comment by notramo** [comment]
Currently PKGBUILDS are stored in `/tmp/yaytmp-<UID>`, which is deleted after shutdown. This feature would require to change this directory to e.g. `~/.cache/yay`.

**Comment by Jguer** [comment]
Master branch is putting them in ~/.cache/yay by default now

**Comment by Morganamilo** [comment]
So now that we have git this should be easy to implement. The question is how to show them? A config setting to prefer diffs but fallback to the full pkgbuild on stuff downloaded via tarball? Sounds like the way to go unless any one has another idea.

**Comment by vinipsmaker** [comment]
> The question is how to show them?

And different than yaourt, the diff of all changes should be shown (not only the `PKGBUILD` file). It's important to see if install files and embedded patches had changed too.

Git diff is a major time-saver to verify packages from AUR after each change and it's kind hard to do this verification process w/o `git diff` if you have too many AUR packages installed.

**Comment by Morganamilo** [comment]
Git diff will handle this all for us, so it should work on all tracked files including .installs and all that. No need to worry about it.

**Comment by MarcusRiemer** [comment]
> A config setting to prefer diffs but fallback to the full pkgbuild on stuff downloaded via tarball?

Personally I would have expected this to be a new option in the `PKGBUILDs to edit?`-step:

    ==> PKGBUILDs to edit?
    ==> [N]one [D]iff [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)

But thinking about this again it might conflict with the idea of editing. Maybe the step could be called "verify" instead? That is at least what I use it for.

**Comment by Morganamilo** [comment]
I did play around with the idea of allowing the user to edit diffs. It turns out to be a mess and you're likely to break the diff or cause a merge conflict.

A d option would force the user to view all diffs then, so I don't really want that,
