### ISSUE TITLE
[Solution] Clock skew. Makefile Error 2. Failure occurred in package. 

### ISSUE THREAD

**Issue by Lzok** [Jguer/yay#1312]
This is not a particular issue with yay, but I encountered it while I was trying to install yay and spent a couple of hours to catch the problem. I want to share it here, maybe it could be helpful for others.

#### Setup
VirtualBox machine with a clean bare bones Arch Linux.

#### Affected Version
Version does not matters.

#### Issue
The issue was given while I executed `makepkg -siL` (-L for logs)
![yay1](https://user-images.githubusercontent.com/45211582/85178081-fe7f3280-b253-11ea-8e37-011b3a3642ea.png)

#### Steps to reproduce
```bash
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -siL
```

#### Problem walkthrough
After I saw the error shown previously in the Issue section, I checked the log file `(yay-10-0.1-1-x86_64-build.log)` and it had an error message: `make: warning: Clock skew detected. Your build may be incomplete`
![yay2](https://user-images.githubusercontent.com/45211582/85178376-ba406200-b254-11ea-8c7f-b86b85337e67.png)

#### Solution
After my research, I understood the problem is because the time configuration of the VM.
Before:
![yay4](https://user-images.githubusercontent.com/45211582/85178464-ec51c400-b254-11ea-98b2-20aedd8fe725.png)

To fix this, I follow the instructions of this section https://wiki.archlinux.org/index.php/System_time#Troubleshooting

```bash
sudo pacman -S ntp
# My timezone is Buenos Aires. You can look for yours running timedatectl list-timezones
timedatectl set-timezone America/Argentina/Buenos_Aires
sudo ntpd -qg
sudo hwclock --systohc
```

After:
![yay6](https://user-images.githubusercontent.com/45211582/85178556-28852480-b255-11ea-804c-6d0741ed2156.png)

Then I ran `makepkg -si` again and it worked flawlessly.
![yay7](https://user-images.githubusercontent.com/45211582/85178589-39ce3100-b255-11ea-914b-aa9676eb38db.png)

Maintainers:
Feel free to close this Issue if you think it is providing good information. Let me know if you want me to post it in the AUR web package also.
Hope this issue non-yay related is not a problem.

Cheers.

**Comment by Jguer** [comment]
Hey @Lzok , thanks for the writeup, I'm sure it will be useful to someone.

Seems to be a warning from `make` itself? Maybe there's an appropriate page to add this on the Archwiki as well

**Comment by Lzok** [comment]
@Jguer No problem!

Hmm I am not sure but seems like that. The Clock stew warning didn't always appear at the same time.
Sometimes I could see more links than others (builds) being processed before the warning appeared.
