### ISSUE TITLE
[Question] Something to let makepkg download AUR dependencies with yay?

### ISSUE THREAD

**Issue by radium226** [Jguer/yay#1313]
Hello,

I wondered how It's possible to use yay when makepkg download It's dependencies. 

I have a PKGPBUILD in one of my repo and I try to build it thought my CI on each commit, but I'm trying not to download dependencies being packages from AUR beforehand (but it does not work as makepkg use pacman and not yay).

Do you have an idea? Thanks (and thanks for this software too)!

**Comment by grandchild** [comment]
Hi there,

`man makepkg` will tell you that makepkg has an environment variable called `PACMAN` that you can set to `yay`. It will then call that binary to resolve missing dependencies with `-s`. No change in yay needed, imo.

**Comment by radium226** [comment]
I wasn't aware of that! It's exactly what I was  looking for, thanks a lot!
