### ISSUE TITLE
Dispaly package name on error?

### ISSUE THREAD

**Issue by mxmilkiib** [Jguer/yay#1314]
So when a user who is doing a full AUR upgrade sees;
```
==> ERROR: A failure occurred in check().
```
they don't have to manually scroll back up and locate the package name. Maybe something like;

```
==> ERROR: A failure occurred in check() of premake-git
```

**Comment by grandchild** [comment]
Hi,

That error is in the output of makepkg, and not from yay: https://git.archlinux.org/pacman.git/tree/scripts/makepkg.sh.in#n357
So it would have to be changed in the pacman repository.
