### ISSUE TITLE
--noconfirm doesn't work anymore with -Sc

### ISSUE THREAD

**Issue by novns** [Jguer/yay#132]
Since last update to yay v2.303 `yay -Sc --noconfirm` asks for confirmation:

```
yay -Sc --noconfirm
Packages to keep:
  All locally installed packages

Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove all other packages from cache? [Y/n] 
```

**Comment by Morganamilo** [comment]
This is because --noconfirm is a yay setting and a pacman setting so it's being filtered out.

Adding this as a special case would be pretty easy. Don't know if there's a better way to do it though.

**Comment by Jguer** [comment]
It is a special case though, as far as I know noconfirm is saved in the config structure, on pass to Pacman we can add the flag in case it's present in the config struct

**Comment by Morganamilo** [comment]
Yes that's what I was thinking. `--noconfirm` is a global so it should be safe to put it in passToPacman for every command.

**Comment by ajays-in** [comment]
Used --noconfirm with yay in a script a couple of weeks back. Just to see it being restricted to be a global setting few days later! Wonderful timing! Maybe it was meant to push me to create a Github account and make this post

**Comment by Morganamilo** [comment]
I haven't really had time to do much but I should really get to this. Give me a minute.
