### ISSUE TITLE
Error fetching <package>: fatal: unable to access '....': Could not resolve host

### ISSUE THREAD

**Issue by neihtfool** [Jguer/yay#1321]
#### Affected Version

yay v9.4.7 - libalpm v12.0.1
#### Issue
When running ```yay -Syu``` the process results in errors for multiple packages. It is unable to access the respective Git Clone URL because the host aur.archlinux.org could not be resolved.

#### Steps to reproduce

1. Run ```yay -Syu```

#### Output

```
:: PKGBUILD up to date, Skipping (1/10): yay
:: PKGBUILD up to date, Skipping (2/10): nerd-fonts-terminus
:: PKGBUILD up to date, Skipping (3/10): libfprint-git
:: Downloaded PKGBUILD (4/10): skypeforlinux-stable-bin
:: Downloaded PKGBUILD (5/10): zoom
:: Downloaded PKGBUILD (6/10): ttf-iosevka
:: Downloaded PKGBUILD (7/10): visual-studio-code-bin
error fetching mongodb-bin: fatal: unable to access 'https://aur.archlinux.org/mongodb-bin.git/': Could not resolve host: aur.archlinux.org
error fetching optimus-manager: fatal: unable to access 'https://aur.archlinux.org/optimus-manager.git/': Could not resolve host: aur.archlinux.org
error fetching libcurl-openssl-1.0: fatal: unable to access 'https://aur.archlinux.org/libcurl-openssl-1.0.git/': Could not resolve host: aur.archlinux.org
```

**Comment by JojiiOfficial** [comment]
Maybe DNS problems? Can you run `nslookup aur.archlinux.org`?

**Comment by neihtfool** [comment]
Thanks for the response. Here is my output:
```
nslookup aur.archlinux.org
Server:		192.168.2.1
Address:	192.168.2.1#53

Non-authoritative answer:
Name:	aur.archlinux.org
Address: 5.9.250.164
Name:	aur.archlinux.org
Address: 2a01:4f8:160:3033::2
```

**Comment by grandchild** [comment]
Wait, so it did download the first 7 PKGBUILDs and then failed? That seems like your DNS or network is only intermittently down.
Does this happen every time, or was this only once?

**Comment by neihtfool** [comment]
Sorry for the late response.

At the time of that post, this happened every time. I can't really tell if the network was intermittently down, since everything else like playing online games was totally fine. Just running ```yay -Syu``` would result in the descripted problem.

However, today, it's working perfectly fine. I am connected to the wifi network in the floor beneath mine (our 'main' router from the internet provider is in the basemend and for each floor we set up a wifi-router connected to said main router).

Seems it really was an issue on my wifi network. Although that was the first time that this problem ever happened to me.

**Comment by grandchild** [comment]
@neihtfool, thanks for following up and closing the issue. Glad to see it's not happening anymore.
