### ISSUE TITLE
Using different `$GNUPGHOME`

### ISSUE THREAD

**Issue by velleto** [Jguer/yay#1326]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use an alternative `$GNUPGHOME` (instead of `~/.gnupg`) for AUR packages, to keep developer keys separate from my personal keys.

A solution already exists for this: calling

    GNUPGHOME=/path/to/preferred/gnupghome yay -S zfs-dkms

works flawlessly. It is just a little cumbersome to write a shell alias (`alias yay="GNUPGHOME=/path yay"`) or write a `yay` wrapper (for scripts) that ensures this is always set. Especially because I prefer adding my personal programs to the end of my `$PATH`, so I couldn't even override the `yay` binary that way and would have to call my wrapper something else (e.g `myay`).

**Describe the solution you'd like**
It would be great, if this could be configured from the `config.json` file directly.

**Additional context**
I have tried configuring this using existing functionality by setting

      "gpgflags": "--homedir=/path/to/preferred/gnupghome",

in my `config.json`, and the keys _successfully import_. I can check this by running 

     gpg --homedir /path/to/preferred/gnupghome -k

However, when it comes to verifying the signatures, `yay` fails saying

    zfs-0.8.4.tar.gz ... FAILED (unknown public key 6AD860EED4598027)
    ==> ERROR: One or more PGP signatures could not be verified!

even though `gpg --homedir /path/to/preferred/gnupghome -k` lists this key as being present.

**Describe alternatives you've considered**
I have also tried writing a gpg wrapper

    #!/bin/bash
    export GNUPGHOME=/path/to/preferred/gnupghome
    gpg "$@"

making it executable and configuring `yay` to use this as the `gpg` program. Alas, this doesn't work either.

Passing the path with `--gpgdir` (one of pacman's options) also doesn't work (although I'm not sure if this is even what I want. Was pulling at strings at this point).

**Solution Proposition**
`man gpg` rather cryptically says 

> It is only recognized when given on the command line.

about the `--homedir` option. I'm not really sure what this means, and is potentially the source of why yay can import the keys correctly, but not verify the keys later (Looking at `yay`'s source code, it looks like importing the gpg keys is done by `yay` in `keys.go` but verifying the signatures isn't?)

So I would propose --- if this is possible --- to add  a new field to `config.json` that accepts the GNUPG environment variable.

**Yay version**
`yay v10.0.2 - libalpm v12.0.2`

Thank you for your efforts!

Edit: Just to be clear, this has nothing to do with the `zfs-dkms` package. It was just used as an example.

**Comment by Morganamilo** [comment]
--gpgflags changes the flags yay passes to gpg. Makepkg does not get these flags. You can configure that in makepkg.conf.
