### ISSUE TITLE
fish shell '-U' completion support

### ISSUE THREAD

**Issue by dontdieych** [Jguer/yay#1328]
Currently it looks like does not complete to pkg file name in fish shell.

Manjaro

yay 10.0.2-2
fish 3.1.2-2

Thanks.

**Comment by grandchild** [comment]
This seems to be a bug report, not a feature request.

**Comment by Jguer** [comment]
Synced fish completions with upstream, which should fix some bugs with this, namely for people that skip compression 

b864d43
