### ISSUE TITLE
`yay -Si` print format should be like pacman

### ISSUE THREAD

**Issue by Hill-98** [Jguer/yay#1332]
The current print format of `yay -Si` is bad in a non-English environment (such as the following), while the print format of pacman is very good. Even in the English environment, the print format is still not as good as pacman.

![1.png](https://i.loli.net/2020/06/28/mDIOBSdN1ho3k7u.png)
![2.png](https://i.loli.net/2020/06/28/wRXIAOfxNdcG5vp.png)

We should be able to learn from upstream to make the printing behavior of yay and pacman consistent.

**Comment by grandchild** [comment]
For reference, this issue was pruned from #1310

**Comment by lwlf** [comment]
Has this issue been fixed? If fixed, how will I configure and enable it? 
@Jguer
