### ISSUE TITLE
pentium4 missing from arch in PKGBUILD in AUR

### ISSUE THREAD

**Issue by poizan42** [Jguer/yay#1336]
#### Affected Version

10.0.3-1 (or all I guess)

**Describe the bug**
The PKGBUILD file in AUR declares support for i686 but not pentium4. Having sse2 support does not seem to break anything though. Everything seems to be working fine if I just add pentium4 to the arch declaration.

**To Reproduce**
Clone from AUR and run makepkg -si on a system running arch32 with architecture set to pentium4.

**Expected behavior**
yay is built and installed

**Output**
```
$ makepkg -si
==> ERROR: yay is not available for the 'pentium4' architecture.
```

**Comment by grandchild** [comment]
Excuse my ignorance but what kind of architecture is "pentium4"? I thought that i686 basically means all of 32bit x86. How is "pentium4" any different?

And which Arch-/Pacman-based distro are you using that declares itself as "pentium4"?

**Comment by poizan42** [comment]
arch32 is built as i484, i686 and pentium4. pentium4 means sse2 support, see https://archlinux32.org/architecture/

**Comment by grandchild** [comment]
Ah, I see. Still I would argue that this is a topic for https://aur.archlinux.org/packages/yay

**Comment by poizan42** [comment]
> Ah, I see. Still I would argue that this is a topic for https://aur.archlinux.org/packages/yay, and not the software repo. But both are maintained by @Jguer, so you might still have your way. ;)

From that page:

> I cannot delete the spam comments appearing regularly in this page, which has also led me to disable notifications from here. I remind that the best way to receive support or report a problem is through the Upstream URL.

**Comment by grandchild** [comment]
Sorry, didn't see that comment right away. Fair enough.

**Comment by Jguer** [comment]
I will include this `pkgbuild` fix in the next minor release of yay
