### ISSUE TITLE
[2.303] Can't replace conflicting package

### ISSUE THREAD

**Issue by jonathonf** [Jguer/yay#134]
Possibly related to the implementation for https://github.com/Jguer/yay/issues/114 (e.g. `--noconfirm`), `yay` will automatically answer N when faced with a package conflict, e.g.:
```
==> Installing package freetype2-ultimate5 with pacman -U...
loading packages...
resolving dependencies...
looking for conflicting packages...
:: freetype2-ultimate5 and freetype2 are in conflict. Remove freetype2? [y/N] 
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: freetype2-ultimate5 and freetype2 are in conflict
==> WARNING: Failed to install built package(s).
==> Cleaning up...
```
Ideally `yay` should wait for user input here.

**Comment by Jguer** [comment]
True, ideally `yay` should wait for user input here.

But what I'll try to do is search for conflicts before the package is even built and present it near the `EDIT PKGBUILD`, that should take care of the simplest cases at least.

**Comment by Jguer** [comment]
28515c8beb5da851f8c37bf7aa70e210e0e2163d fixes this issue.  Only tested with AUR cases for now.
![screenshot from 2018-02-07 12-38-49](https://user-images.githubusercontent.com/8071073/35916932-04bbb932-0c04-11e8-810e-fad87b74e728.png)
