### ISSUE TITLE
How to uninstall yay?

### ISSUE THREAD

**Issue by naddika** [Jguer/yay#1343]
How to uninstall yay?

**Comment by grandchild** [comment]
Hi,

yay is a package just like any other package, so the Archwiki page for [pacman in the section "Removing packages"](https://wiki.archlinux.org/index.php/Pacman#Removing_packages) will help you.

Your question makes it seem that you are new to Archlinux. If you have further questions about Arch, please use the [forums](https://bbs.archlinux.org/), it even has a [beginner-friendly section](https://bbs.archlinux.org/viewforum.php?id=23).

But remember: Always **search first, before asking a question**, someone might have had the same problem as you -- and found an answer!

**Comment by HoussamEddineBoukhalfa** [comment]
run the commend : 
**sudo pacman -R yay**

**Comment by vbuglov** [comment]
> run the commend : **sudo pacman -R yay**

$ sudo pacman -R yay
error: target not found: yay

**Comment by mb6ockatf** [comment]
having:
```
$ yay
yay: error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory
$ sudo pacman -Rcs yay
error: target not found: yay

**Comment by calzateu** [comment]
@vbuglov and @mb6ockatf, you can check the following issue:
#2393

**Comment by JediMndCntrl** [comment]
Your close.....
Try this command: sudo pacman -Rns yay

Let me know if it works....

**Comment by ingoau** [comment]
I used `yay-bin` instead of just `yay` and it worked. This is if you install from AUR `yay-bin`
