### ISSUE TITLE
"yay -Qu" should show formatted output

### ISSUE THREAD

**Issue by rightaway** [Jguer/yay#1346]
`yay --sync --combinedupgrade --sysupgrade` shows the output of available packages to upgrade in a very nice looking and useful way. It shows things in columns categorized by type of repository, and in color, with appropriate highlighting.

That output is what should appear for `yay -Qu`. Or there should be another command that just shows this output.

Sometimes I want to just see what the latest updates are and not actually update anything. There should be a command to just do this which doesn't prompt for a Y/N, exactly how `yay -Qu` does, but with the same excellent formatting of the other command.

**Comment by squalou** [comment]
Hi,
my 2 cents here : `yay -Qu` should stick to pacman-style output, or else it may break lots of custom scripts around.

On the other hand : a nicer display using another command switch would be nice.
