### ISSUE TITLE
When updating, make it prompt sudo only once

### ISSUE THREAD

**Issue by Andy3153** [Jguer/yay#1348]
Hello.
When you use `yay -Syu` to upgrade your packages, it upgrades both the packages in the official repos and the packages in the AUR. When it upgrades the packages in the AUR, it first builds them, and then it installs them, requesting the password for sudo almost everytime you upgrade a new package since the sudo password times out. This happens ever since I started to use yay, most likely ever since it was created. That means that if you have to upgrade a lot of AUR packages, you can't just walk away and let it do its job, you have to babysit it and type your sudo password everytime it times out. And, no, **I don't want to change the time after which sudo times out**, i just want it to ask for my password only once.

Now, I kind of have a solution, but it would make you type your password two times
The solution would be: you first execute the command, it requests for the sudo password and it upgrades packages in the official repos. Then, it downloads and compiles all the AUR programs, and instead of installing them when they finish compiling, it installs them all at the end after all of them are done, and that's when it requests the sudo password the second time. 
This method is decent enough, and it's almost not annoying at all. But, for example, when you upgrade all the packages using `pamac-gtk`, it requests the password only once, so there has to be a way to make yay do the same

**Comment by Morganamilo** [comment]
`yay --help | grep sudoloop`

**Comment by Andy3153** [comment]
Why wouldn't that be on by default though? I can't think of anything that would make it a bad decision

**Comment by Jguer** [comment]
https://github.com/Jguer/yay/issues/147#issuecomment-366024535 Here it is :slightly_smiling_face:

**Comment by Andy3153** [comment]
Yeah, I could see how that can become a bad thing now. But, isn't there any way of making sudo time out when requested? A quick search didn't give me much answers, but if that would be possible, it would be easy to make yay force sudo to timeout after getting any signal that would close out of it, and that security problem would be solved too

**Comment by grandchild** [comment]
> force sudo to timeout after getting any signal

@Andy3153: Just to drive this home before this ticket should be closed: I don't have to do Ctrl+C, I can open another terminal and kill yay with SIGKILL, and programs _can't catch that_, so there's no way to shut sudo down too. Bam, root access!
