### ISSUE TITLE
yay-git saves settings failed

### ISSUE THREAD

**Issue by arenekosreal** [Jguer/yay#1352]
#### Affected Version

yay v10.0.4.r24.g3b2bb28 - libalpm v12.0.2

**Describe the bug**
Execute `yay --aururl "https://aur.tuna.tsinghua.edu.cn" --save` and terminal returns "\<nil\>". If I replace `yay-git` with `yay`, this problem can be solved. I am using Manjaro on RaspberryPi 4.
**To Reproduce**
Execute `yay --aururl "https://aur.tuna.tsinghua.edu.cn" --save`  in terminal.
**Expected behavior**
Replace AUR URL with mirror site and save changes to file to make it also be applied next time.
**Output**
Terminal output:
```
# zhanghua @ raspberrypi in ~ [17:04:46]
$ yay --aururl "https://aur.tuna.tsinghua.edu.cn" --save
<nil>
```
yay config:
```
# zhanghua @ raspberrypi in ~ [17:05:47]
$ yay -Pg
{
        "aururl": "https://aur.archlinux.org",
        "buildDir": "/home/zhanghua/.cache/yay",
        "absdir": "/home/zhanghua/.cache/yay/abs",
        "editor": "",
        "editorflags": "",
        "makepkgbin": "makepkg",
        "makepkgconf": "",
        "pacmanbin": "pacman",
        "pacmanconf": "/etc/pacman.conf",
        "redownload": "no",
        "rebuild": "no",
        "answerclean": "",
        "answerdiff": "",
        "answeredit": "",
        "answerupgrade": "",
        "gitbin": "git",
        "gpgbin": "gpg",
        "gpgflags": "",
        "mflags": "",
        "sortby": "votes",
        "searchby": "name-desc",
        "gitflags": "",
        "removemake": "ask",
        "sudobin": "sudo",
        "sudoflags": "",
        "requestsplitn": 150,
        "sortmode": 0,
        "completionrefreshtime": 7,
        "sudoloop": false,
        "timeupdate": false,
        "devel": false,
        "cleanAfter": false,
        "provides": true,
        "pgpfetch": true,
        "upgrademenu": true,
        "cleanmenu": true,
        "diffmenu": true,
        "editmenu": false,
        "combinedupgrade": false,
        "useask": false,
        "batchinstall": false
}
```

**Comment by mattheusv** [comment]
Seems that runtime.ConfigPath is not filled on next branch

On v10.0.4 tag runtime.ConfigPath is loaded on [`MakeRuntime` ](https://github.com/Jguer/yay/blob/v10.0.4/pkg/settings/runtime.go#L73)function


On next branch we don't have more [`MakeRuntime`](
https://github.com/Jguer/yay/blob/next/pkg/settings/runtime.go) function, and the runtime config is loaded on [`NewConfig` ](https://github.com/Jguer/yay/blob/next/pkg/settings/config.go#L195) function but ConfigPath is not set

**Comment by AdsonCicilioti** [comment]
The problem continue in 

```
$ yay --version                                        
yay v10.1.0 - libalpm v12.0.2
```
I've try set my yay preferences with:
```
yay --sortby popularity --topdown --nodiffmenu --save     
<nil>
```

**Comment by gabevenberg** [comment]
same here. --save returns <nil>

**Comment by gabevenberg** [comment]
As a temporary workaround, first run
`mkdir ~/.config/yay`

**Comment by 991688344** [comment]
1. create the directory ： `sudo mkdir  ~/.config/yay`
2. run `yay -P -g` and **Copy the output of the command !!**
3. create the file: `sudo vim ~/.config/yay/config.json`
4. change file permissions： `sudo chmod 777 ~/.config/yay/config.json`
5. run `vim  ~/.config/yay/config.json` and Paste the content you just copied
6. run `yay --aururl "https://aur.tuna.tsinghua.edu.cn" --save`
7. run `yay -P -g` to check if it works

**Comment by Jguer** [comment]
> `yay --sortby popularity --topdown --nodiffmenu --save `

I tested this on an existing `config.json` and a clean `.config` folder without issues on `yay 10.1.1`, closing for now
