### ISSUE TITLE
Minor typo in French translation.

### ISSUE THREAD

**Issue by iago-lito** [Jguer/yay#1354]
```
==> ATTENTION : Des messages destinés à attirer votre attention sont apparus lors de la vérification des signatures.
    Veuillez vous assurer que vous leurs faites confiance.
```
The last `leurs` should read `leur` instead, but I can't find the location of this message within the repo. Is it somewhere upstream?

It would translate as something like `WARNING: Some messages supposed to catch your attention / steal your focus appeared during signatures verification. Make sure you trust them.`

(thank you for yay <3)

**Comment by Jguer** [comment]
I believe this is in pacman's translation files. You can use https://www.transifex.com/toofishes/archlinux-pacman/ to help improve the translations. :smile:
