### ISSUE TITLE
AUR is unavailable at this moment

### ISSUE THREAD

**Issue by rkmax** [Jguer/yay#1361]
#### Affected Version
yay v10.0.4 - libalpm v12.0.2

**Describe the bug**
When try to install a package, eg: `yay -S android-studio-canary` the response is always AUR is unavailable at this moment but AUR it seems working properly

**To Reproduce**
Just try to install something

**Expected behavior**
Install the package as regular

**Output**

```
$ yay -Pg

{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/rkmax/.cache/yay",
	"absdir": "/home/rkmax/.cache/yay/abs",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false
}

```

**Comment by JojiiOfficial** [comment]
Lots of people are having issues with the AUR lately. I assume they're having problems with the git server/backend. I've been told that there is a mirror of the AUR but I don't know the address.

**Comment by rkmax** [comment]
now started to work again I assume is like you said some git backend having issues. thx then Ithink I can close this one
