### ISSUE TITLE
yay build server?

### ISSUE THREAD

**Issue by rayzorben** [Jguer/yay#1364]
Not sure if this is a stupid question. I have some lower end hardware, and higher end hardware. When installing something from yay that is built from source, would it be possible for yay to farm that work off to one of my higher end machines? Not only that, but if I am installing something on my laptop I don't want to be blocked at 100% CPU for 3 hours, would prefer one of my servers to do that work and then install the package when it is done.

**Comment by JojiiOfficial** [comment]
I had the exact same issue. I wrote a [system](https://github.com/RemoteBuild) to build AUR packages remotely on a Server. With a [CLI client](https://github.com/RemoteBuild/RemoteBuildClient), you can control the jobs running on the server (Creating, pausing, resuming and cancelling jobs). It is not yet documented, because I didn't see the need of such a system by other people than me. Let me know if you're interested.

**Comment by rayzorben** [comment]
> I had the exact same issue. I wrote a [system](https://github.com/JojiiOfficial/Remotebuild) to build AUR packages remotely on a Server. With a [CLI client](https://github.com/JojiiOfficial/RemoteBuildClient), you can control the jobs running on the server (Creating, pausing, resuming and cancelling jobs). It is not yet documented, because I didn't see the need of such a system by other people than me. Let me know if you're interested.

I'm definitely interested! Not sure I could contribute more than testing, but I would be glad to try it out.

**Comment by JojiiOfficial** [comment]
Since I created it most likely for me, I have to add the documentations and other stuff to make it work better for other systems. I'm doing this in my free time so it might take some time. If you're interested, I'll tell you when I'm done.

**Comment by rayzorben** [comment]
> Since I created it most likely for me, I have to add the documentations and other stuff to make it work better for other systems. I'm doing this in my free time so it might take some time. If you're interested, I'll tell you when I'm done.

No worries, i'll keep an eye on it and see how it is going.

**Comment by itsTyrion** [comment]
> Since I created it most likely for me, I have to add the documentations and other stuff to make it work better for other systems. I'm doing this in my free time so it might take some time. If you're interested, I'll tell you when I'm done.

Starred/watched. Building on a 6 core root server/incoming Ryzen build should be "a bit" faster than torturing the i5-2410M in my Laptop :D
