### ISSUE TITLE
A flag to also install optional deps?

### ISSUE THREAD

**Issue by JadenJSJ** [Jguer/yay#1368]
**Is your feature request related to a problem? Please describe.**
I always need to manually install optional deps by retyping them.

**Describe the solution you'd like**
Add a flag to install optional deps
Or as a question whether you want yay to install them for you.

Example:
yay -S**od** glances
:: Install Optional Dependencies? [Y/n] **Y**

If there is already a flag to do this im sorry, i found a flag -Si but it didn't work.

**Comment by grandchild** [comment]
It's rarely the case that you want to just blanket-install _all_ optdepends.

An interesting proposal would be to show a list of packages (just like plain `yay` search does), with two lines, both the package description and the feature they provide to the package (if that line is given in the optdepends list), and then select just like other packages. I'd like that too, that would enable the optdepends section in packages a lot. :)

**Comment by JojiiOfficial** [comment]
To follow the current schema of yay, I'd use `--optdepends` or `--optmenu` to give the result you were talking about (but keep `-o` as short flag) . `--optmenu` could be a menu like the AUR packages update menu where you can pick the optional depending packages by using numbers (maybe with their explanation next to them). But I would like to allow choosing multiple packages at once. If `--noconfirm` is passed, in my opinion all optionally depending packages should be installed.

I like the Idea and would be happy to see such a feature in yay too!

**Comment by BlueskyFR** [comment]
Can this be opened back?

**Comment by damster101** [comment]
I never understood why none of all the CLI AUR helpers have an option to prompt you for optional dependencies. It's such an obvious feature, and I miss it on a regular basis.
