### ISSUE TITLE
Custom Certificate Authority

### ISSUE THREAD

**Issue by ibrokemypie** [Jguer/yay#137]
Sometimes traffic must go through networks which require a custom ssl certificate authority as they resign all pages. How can yay be used in such an environment, as it currently complains such as the following
```
Get https://api.github.com/repos/jaagr/polybar/branches: x509: certificate signed by unknown authority

```

**Comment by Jguer** [comment]
I would get guess golang uses the cacertificates of the system through a not very deep research I find this:
[https://golang.org/src/crypto/x509/root_linux.go](https://golang.org/src/crypto/x509/root_linux.go)

```
// Possible certificate files; stop after finding one.

var certFiles = []string{

	"/etc/ssl/certs/ca-certificates.crt",                // Debian/Ubuntu/Gentoo etc.

	"/etc/pki/tls/certs/ca-bundle.crt",                  // Fedora/RHEL 6

	"/etc/ssl/ca-bundle.pem",                            // OpenSUSE

	"/etc/pki/tls/cacert.pem",                           // OpenELEC

	"/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem", // CentOS/RHEL 7

}
```

Guess you have to add the CA to the CA-trust of the system ( I've had this issue with pacman due to work proxies and it involved messing with the system)

**Comment by nifisher** [comment]
If I'm not mistaken, that would set a universal acceptance of the unkown authority for every ssl request being made on my system as opposed to it being allowed in just this case, correct?

Why would I want to do that?   In my environment, I know who the unknown authority is (my employer's man-in-the-middle) and am accepting of the matter in this case, but would not necessarily want it in all cases on this system.  Telling yay to ignore the cert error but it still flagging for everything else would be a superior approach i feel.

**Comment by grandchild** [comment]
@nifisher: But the authority is not unknown, is it? You do trust your employer's certificate. (Or at least your system is expected to.)

I found this though: https://forfuncsake.github.io/post/2017/08/trust-extra-ca-cert-in-go-app/ , which boils down to, I think:
```go
rootCAs, err := x509.SystemCertPool()
if err != nil || rootCAs == nil {
	rootCAs = x509.NewCertPool()
}
certs, err := ioutil.ReadFile(localCertFile)
rootCAs.AppendCertsFromPEM(certs)
```

That could do what the people above want...

(I'd still argue that if you have an employer that does stuff like SSL resigning and you install packages with it, then there's not much to gain by limiting other apps on your system, but :shrug:)

**Comment by nifisher** [comment]
>> (I'd still argue that if you have an employer that does stuff like SSL resigning and you install packages with it, 
>> then there's not much to gain by limiting other apps on your system, but shrug)

I don't disagree that it seems an arbitrary line to draw... I know my employer is MITM and if i don't care here, should I care elsewhere..

But my laptop is not always on my employers network and there are connections that I am willing to make in that case that I don't want to make on site.   Or at least, I want to take extra precautions if I do know that the man is watching.   Silent acceptance at the system level would make that more difficult.

**Comment by grandchild** [comment]
I'd encourage people who want to, to try the draft at #1387 :)
@nifisher @ibrokemypie @sohimaster
