### ISSUE TITLE
Install off YAY

### ISSUE THREAD

**Issue by BlockHackTk** [Jguer/yay#1371]
#### Affected Version

**> ==> Création du paquet yay 10.0.4-1 (mar. 22 sept. 2020 12:48:11)**

_Describe the bug_
**> Not really a bug, during installation, I have this question asked me:
`:: yay et yay-git sont en conflit. Supprimer yay-git ? [o/N]`

Could you explain to me? Thx in advance

And this is my first installation of an ARCH (Manjaro) after 10 years under Debian & Co** 

_To Reproduce_
**`makepkg -sri`**

Expected behavior
**Just trying install YAY**

Output

[romhtk@romhtk-3680fau yay]$ makepkg -sri
==> Création du paquet yay 10.0.4-1 (mar. 22 sept. 2020 12:48:11)
==> Vérification des dépendances pour l’exécution…
==> Vérification des dépendances pour la compilation…
==> Récupération des sources…
  -> Téléchargement de yay-10.0.4.tar.gz…
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   118  100   118    0     0    551      0 --:--:-- --:--:-- --:--:--   553
100  333k  100  333k    0     0   451k      0 --:--:-- --:--:-- --:--:--  451k
==> Validation des fichiers source avec sha256sums…
    yay-10.0.4.tar.gz ... Réussite
==> Extraction des sources…
  -> Extraction de yay-10.0.4.tar.gz avec bsdtar
==> Lancement de build()…
go build -v -trimpath -mod=readonly -modcacherw -ldflags '-s -w -extldflags "-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now" -X "main.yayVersion=10.0.4" -X "main.localePath=/usr/share/locale/"' -buildmode=pie -o yay
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/Morganamilo/go-srcinfo v1.0.0
go: downloading golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
go: downloading github.com/mikkeloscar/aur v0.0.0-20200113170522-1cb4e2949656
go: downloading github.com/leonelquinteros/gotext v1.4.0
go: downloading github.com/Morganamilo/go-pacmanconf v0.0.0-20180910220353-9c5265e1b14f
go: downloading github.com/Jguer/go-alpm v0.0.0-20200405152916-a3feea4322e9
go: downloading github.com/stretchr/testify v1.6.1
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading golang.org/x/sys v0.0.0-20200625212154-ddb9806d33ae
golang.org/x/sys/internal/unsafeheader
github.com/Jguer/yay/v10/pkg/completion
github.com/Jguer/yay/v10/pkg/settings
gopkg.in/yaml.v3
golang.org/x/sys/unix
golang.org/x/crypto/ssh/terminal
github.com/stretchr/testify/assert
github.com/Jguer/yay/v10/pkg/text
github.com/Jguer/yay/v10/pkg/news
github.com/Jguer/yay/v10/pkg/query
github.com/Jguer/yay/v10/pkg/dep
github.com/Jguer/yay/v10/pkg/pgp
github.com/Jguer/yay/v10
==> Entre dans l’environnement fakeroot…
==> Lancement de package()…
msgfmt po/pt.po -o po/pt.mo
msgfmt po/pt_BR.po -o po/pt_BR.mo
msgfmt po/en.po -o po/en.mo
msgfmt po/es.po -o po/es.mo
msgfmt po/eu.po -o po/eu.mo
msgfmt po/fr_FR.po -o po/fr_FR.mo
msgfmt po/ja.po -o po/ja.mo
msgfmt po/pl_PL.po -o po/pl_PL.mo
msgfmt po/ru_RU.po -o po/ru_RU.mo
msgfmt po/zh_CN.po -o po/zh_CN.mo
install -Dm755 yay /home/romhtk/TunSafe/yay/pkg/yay/usr/bin/yay
install -Dm644 doc/yay.8 /home/romhtk/TunSafe/yay/pkg/yay/usr/share/man/man8/yay.8
install -Dm644 completions/bash /home/romhtk/TunSafe/yay/pkg/yay/usr/share/bash-completion/completions/yay
install -Dm644 completions/zsh /home/romhtk/TunSafe/yay/pkg/yay/usr/share/zsh/site-functions/_yay
install -Dm644 completions/fish /home/romhtk/TunSafe/yay/pkg/yay/usr/share/fish/vendor_completions.d/yay.fish
for lang in pt pt_BR en es eu fr_FR ja pl_PL ru_RU zh_CN; do \
	install -Dm644 po/${lang}.mo /home/romhtk/TunSafe/yay/pkg/yay/usr/share/locale/$lang/LC_MESSAGES/yay.mo; \
done
==> Nettoyage de l’installation…
  -> Suppression des fichiers libtool…
  -> Suppression des fichiers indésirables…
  -> Suppression des fichiers de bibliothèques statiques…
  -> Nettoyage des symboles inutiles dans les fichiers binaires et les bibliothèques…
  -> Compression des pages de man/info…
==> Recherche des erreurs d’empaquetage…
==> Création du paquet « yay »…
  -> Génération du fichier .PKGINFO…
  -> Génération du fichier .BUILDINFO…
  -> Génération du fichier .MTREE…
  -> Compression du paquet…
==> Quitte l’environnement fakeroot.
==> Création terminée : yay 10.0.4-1 (mar. 22 sept. 2020 12:48:45)
==> Installation du paquet yay avec pacman -U…
chargement des paquets…
résolution des dépendances…
recherche des conflits entre paquets…
`:: yay et yay-git sont en conflit. Supprimer yay-git ? [o/N]`

**Comment by JojiiOfficial** [comment]
It looks like you already have yay-git installed. Remove it first or agree to the replace dialog if you want the non git version.

**Comment by BlockHackTk** [comment]
Thank you @JojiiOfficial
I was just wondering what were the differences between the two packages.
I deleted yay-git

**Comment by Jguer** [comment]
@BlockHackTk `yay-git` builds from the `next branch` of this repo, it includes the latest changes to yay and it can break. `yay` builds from the tags of this repository and is only updated when I feel comfortable about the stability of features in `next`
