### ISSUE TITLE
Way to Force Yay to not spit questions on AUR Building

### ISSUE THREAD

**Issue by furtabs** [Jguer/yay#1372]
**Is your feature request related to a problem? Please describe.**
A way to bulk update AUR Packages without the spam of yes and no questions and your sudo password being timed out.

**Describe the solution you'd like**
Essentially what i wrote above. Babysitting 50 AUR pacakge updates is a main

**Describe alternatives you've considered**
maybe running yay in multiple threads i dont really know.

**Additional context**
This stuff

```zsh
==> Remove make dependencies after install? [y/N]
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
[sudo] password for user: 
:: Proceed with installation? [Y/n]
```
And it repeats for every AUR Package

**Comment by furtabs** [comment]
Essentially if i run a 
```zsh
yay -Syyuu
```
i would want it to affect AUR packages as well. maybe not always saying yes but the default

**Comment by grandchild** [comment]
How about
```yay -Syu --noconfirm --combinedupgrade```
?

This basically means "don't ask me anything" and "upgrade AUR packages together with official packages".

Would that solve your issue?
