### ISSUE TITLE
build without install - yay -Sw does not work

### ISSUE THREAD

**Issue by idanyadgar** [Jguer/yay#1373]
**Is your feature request related to a problem? Please describe.**
I need to download a package with it's dependencies without installing them.
For example downloading vmware-workstation with its dependency vmware-keymap

**Describe the solution you'd like**
yay -Sw vmware-workstation which will download and build vmware-workstation and vmware-keymap packages.

**Comment by grandchild** [comment]
@jguer It's not a feature request, it's a bug. `yay -Sw yay-git` for example, will proceed to install after build.

**Comment by cuihaoleo** [comment]
I guess this is the same bug so I am not opening a new issue.

When I do `-Syuw`, yay needlessly asks me to select `Packages to exclude` after downloading all updates, as if it's going to install packages. No matter what I choose, it ends up doing nothing because of `-w`.

Demo:
```
$ yay -Syuw
:: Synchronizing package databases...
......
:: Starting full system upgrade...
......
:: Proceed with download? [Y/n] y
......
:: Searching databases for updates...
:: Searching AUR for updates...
:: 1 Packages to upgrade.
1  core/nano  5.5-1 -> 5.6-1
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
==> 
 there is nothing to do
```
