### ISSUE TITLE
GPG fails with General Error

### ISSUE THREAD

**Issue by IGBC** [Jguer/yay#1374]
#### Affected Version
latest

**Describe the bug**
On my latest arch install yay fails to download gpg keys. GPG returns "general error" this persists with GPG unless a keyserver is manually specified.

**To Reproduce**
install a fresh arch 
(I am using base, linux-lts, linux firmware) 

install yay ontop of that

attempt to install a package from the AUR

**Expected behavior**
yay installs the package

**Output**
cant't computer doesn't have a web browser yet (see yay is broken)

relevent line is gpg: failed to receive key: general error.

**Comment by grandchild** [comment]
That are a bit too few data points to go on. We need to figure out what GPG's problem is exactly.

* Does yay ask you to import any specific keys? If yes, note the fingerprint and try:
* `gpg --recv-keys [key-fingerprint]`

Does that result in a more detailed error?

**Comment by theonlyfoxy** [comment]
Hello @IGBC.
1. Can you try a different keyserver or different port? Such as `hkp://p80.pool.sks-keyservers.net:80`
2. If step above didn't work try to import the key manually and paste the results if possible.

**Comment by ahgilbert** [comment]
I see this error as well. `gpg --recv-keys` did not lead to a more useful error message. Snip below. `FCF...8D8` was copied from the failed invocation `yay -S ffmpeg-full`

```
$ uname -a
Linux chomps 5.6.15-1-MANJARO #1 SMP PREEMPT Wed May 27 20:38:56 UTC 2020 x86_64 GNU/Linux
$ yay --version
yay v10.0.4 - libalpm v12.0.2
$ gpg --recv-keys -vv FCF...8D8
gpg: keyserver receive failed: General error
```

Edit to add: After manually invoking `gpg --recv-keys --keyserver keys.openpgp.org FCF...8D8` I did successfully install `ffmpeg-full`

**Comment by grandchild** [comment]
Well if standalone GPG gives the same error, it's hardly a yay issue. In that case I can only suspect it has something to do with the way your local gpg is set up. (And I do commiserate, it's tedious to debug... :unamused:)

**Comment by mpriestman** [comment]
I think I might have had a similar error on my machine. Again, it was a clean install of Arch Linux. Trying to install `dropbox` with `yay` gave the same `general error` from `gnupg`. Trying to manually import they key directly using `gnupg` also failed with the same error. Running `sudo pacman-key --refresh-keys` failed with a similar error.

I think the problem is that somewhere the default keyservers that Arch was configured with just aren't working at the moment. To fix, I had to edit `/etc/pacman.d/gnupg/gpg.conf` and specify a different keyserver (e.g. `keyserver hkp://keyserver.ubuntu.com`). This seemed to fix the problem. I also had to make the same edit to my per-user '~/.gnupg/gpg.conf`.

So I'm pretty sure this isn't related to `yay` per-se, but I have no idea where to actually report the problem to as I'm not sure where the default keyservers are actually specified on the system.

**Comment by IGBC** [comment]
> I think I might have had a similar error on my machine. Again, it was a clean install of Arch Linux. Trying to install `dropbox` with `yay` gave the same `general error` from `gnupg`. Trying to manually import they key directly using `gnupg` also failed with the same error. Running `sudo pacman-key --refresh-keys` failed with a similar error.
> 
> I think the problem is that somewhere the default keyservers that Arch was configured with just aren't working at the moment. To fix, I had to edit `/etc/pacman.d/gnupg/gpg.conf` and specify a different keyserver (e.g. `keyserver hkp://keyserver.ubuntu.com`). This seemed to fix the problem. I also had to make the same edit to my per-user '~/.gnupg/gpg.conf`.
> 
> So I'm pretty sure this isn't related to `yay` per-se, but I have no idea where to actually report the problem to as I'm not sure where the default keyservers are actually specified on the system.

this fixed my issue, subsequently several hours later the affected PC suffered a hardware failure and died. Please do not ask further questions as I am unable to assist further, due to the PC being dead.

**Comment by Jguer** [comment]
PC is dead, issue solved

**Comment by xxRockOnxx** [comment]
I'm having the same issue.

```
:: (1/2) Parsing SRCINFO: python3-threaded_servers
:: (2/2) Parsing SRCINFO: quickserve

:: PGP keys need importing:
 -> EC3CBE7F607D11E663149E811D1F0DC78F173680, required by: python3-threaded_servers  quickserve
==> Import? [Y/n] 
:: Importing keys with gpg...
gpg: keyserver receive failed: General error
problem importing keys
```

Already tried adding the key myself but it did not worked.

```
sudo gpg --keyserver pool.sks-keyservers.net --recv-keys EC3CBE7F607D11E663149E811D1F0DC78F173680
gpg: key 1D1F0DC78F173680: "Xyne. (key #3) <xyne@archlinux.ca>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

**Comment by meredrica** [comment]
@mpriestman thanks for the hints. i couldn't figure out where the configs are. can't believe this is still broken on arch

**Comment by IGBC** [comment]
I believe the upstream issue is arch's keyservers are still down. I am using ubuntu's for now
