### ISSUE TITLE
Install package from Arch Official Repos if available

### ISSUE THREAD

**Issue by CodeWithShreyans** [Jguer/yay#1376]
A requested package be installed from Arch Official Repos through Pacman if the same package is available and up to date with the AUR package.
So there will be no need to use Pacman at all anymore.

**Comment by grandchild** [comment]
This is already how it works, no?

If I run `yay -S linux` it will (re)install that package.

Or maybe I misread your issue?

> the same package is available [in] the AUR

There aren't supposed to be any AUR package with the same name as official packages, right? I never actually checked and just assumed this...

Yay also handles the case when a package becomes official (i.e. moves out of the AUR into *community*).

**Comment by CodeWithShreyans** [comment]
I am not completely sure about any of this but this was just an idea that popped in my head.
You may or may not be right, sorry but I don't know? 🙂🙂

**Comment by grandchild** [comment]
> So there will be no need to use Pacman at all anymore.

Well, case in point: I don't (well, very rarely) use pacman anymore. So I guess what you want is already reality. Try it sometime.

**Comment by Jguer** [comment]
I do not understand this issue unfortunately, yay should already work as a drop in replacement of pacman in most situations

**Comment by CodeWithShreyans** [comment]
Ok
