### ISSUE TITLE
Add a command line parameter so that the packages can be installed one by one

### ISSUE THREAD

**Issue by ghost** [Jguer/yay#1377]
**Is your feature request related to a problem? Please describe.**

When I install too many dependencies and they are all AUR packages, I often cannot download the source code due to network reasons. At this time, I will cancel the installation and rerun the installation command.

At this time, the installer will re-detect the previously downloaded software package, which is unusually slow.

**Describe the solution you'd like**

Build and install the software immediately after downloading the source code of the package

**Describe alternatives you've considered**

1. Manually download the source code of each failed package
2. Re-execute the installation command again and again until the installation is successful
3. Part-by-part installation target software

**Additional context**

None

**Comment by ghost** [comment]
e.g. ros-noetic-desktop-full

**Comment by grandchild** [comment]
`man yay` provides:

```
       --nobatchinstall
              Always install AUR packages immediately after building them.
```

Wouldn't that do what you want?

**Comment by grandchild** [comment]
You can even make it the permanent default by saving the flag to the config:

```shell
$ yay --save --nobatchinstall
$ grep batchinstall .config/yay/config.json
	"batchinstall": false
```

**Comment by grandchild** [comment]
> re-detect the previously downloaded software package, which is unusually slow

But that's a curious detail. You mean, the complete package source has already been downloaded and yay takes a long time to find that it has those files already? How slow is slow exactly? One or two seconds? Or more?

**Comment by ghost** [comment]
> But that's a curious detail. You mean, the complete package source has already been downloaded and yay takes a long time to find that it has those files already? How slow is slow exactly? One or two seconds? Or more?
>

It takes 3-5 seconds or more to check whether the source code of a software package has been downloaded.

When the software I installed depends on hundreds of AUR software packages, the time consumed in this operation is terrible when it is interrupted and reinstalled in the middle
