### ISSUE TITLE
How I could use powerpill with yay?

### ISSUE THREAD

**Issue by zoedsoupe** [Jguer/yay#1380]

**Comment by grandchild** [comment]
Hi there,

I haven't used powerpill, but if it's a full-featured pacman-wrapper you could try this:

```shell
PACMAN=powerpill.py yay
```
What this does:
By defining the `PACMAN` environment variable for yay as `powerpill.py`, yay will do all its pacman business through that executable. Maybe this works? Let us know! :)

**Comment by zoedsoupe** [comment]
Thank you! It worked!

**Comment by AchmadFathoni** [comment]
This is more elegant solution.

1. Run 'yay -Syu --save`
2. Open `~/.config/yay/config.json` and change pacman binary program line to powerpill or `"pacmanbin": "powerpill"`
