### ISSUE TITLE
yay -Fl doesn't work

### ISSUE THREAD

**Issue by onetruffle** [Jguer/yay#1381]
#### Affected Version

**Description**
`yay -Fl` must return the paths of all the files to be installed when yay is run.  Now I understand that the AUR isn't a regular pacman package repository in that it contains no AUR.files.gz or something like that. However, it is supposed to work for regular package repositories which it doesn't.

**To Reproduce**
Run `yay -Fl <pkg>`

**Expected behavior**
`yay -Fl <pkg>` must work, just like `pacman -Fl <pkg>`.

**Output**
No output, return code 1

**Comment by Jguer** [comment]
```sh
❯ yay -Fl vi
vi usr/
vi usr/bin/
vi usr/bin/edit
vi usr/bin/ex
vi usr/bin/vedit
vi usr/bin/vi
vi usr/bin/view
vi usr/lib/
vi usr/lib/ex/
vi usr/lib/ex/expreserve
vi usr/lib/ex/exrecover
vi usr/share/
vi usr/share/licenses/
vi usr/share/licenses/vi/
vi usr/share/licenses/vi/LICENSE
vi usr/share/man/
vi usr/share/man/man1/
vi usr/share/man/man1/edit.1.gz
vi usr/share/man/man1/ex.1.gz
vi usr/share/man/man1/vedit.1.gz
vi usr/share/man/man1/vi.1.gz
vi usr/share/man/man1/view.1.gz
vi var/
vi var/lib/
vi var/lib/ex/

❯ pacman -Fl vi
vi usr/
vi usr/bin/
vi usr/bin/edit
vi usr/bin/ex
vi usr/bin/vedit
vi usr/bin/vi
vi usr/bin/view
vi usr/lib/
vi usr/lib/ex/
vi usr/lib/ex/expreserve
vi usr/lib/ex/exrecover
vi usr/share/
vi usr/share/licenses/
vi usr/share/licenses/vi/
vi usr/share/licenses/vi/LICENSE
vi usr/share/man/
vi usr/share/man/man1/
vi usr/share/man/man1/edit.1.gz
vi usr/share/man/man1/ex.1.gz
vi usr/share/man/man1/vedit.1.gz
vi usr/share/man/man1/vi.1.gz
vi usr/share/man/man1/view.1.gz
vi var/
vi var/lib/
vi var/lib/ex/
```

Can't reproduce, I don't remember if it applies to `-Fl` but have you used `pacman -Fy` lately?

**Comment by grandchild** [comment]
FYI: Simulating a lack of `yay -Fy` looks like this for me:
```
$ sudo rm /var/lib/pacman/sync/core.files
$ yay -Fl curl
warning: database file for 'core' does not exist (use '-Fy' to download)
error: package 'curl' was not found
```
... and not like "no output, retval 1".

**Comment by onetruffle** [comment]
Okay, that's weird. Works fine on a different system. I'll reopen if I find something.
