### ISSUE TITLE
Allow --noconfirm and --diff-noconfirm

### ISSUE THREAD

**Issue by HaleTom** [Jguer/yay#1389]
**Is your feature request related to a problem?**

I want to be able to install a package without user interaction in the general case, but if there is a diff, then I want operations to pause until the user accepts it (since a lack of acceptance is a security risk. 

**Describe the solution you'd like**

* Have `--noconfirm` answer `Y` to the `Install [Y/n]` prompt except if any new diffs were displayed (safe by default).
* If diffs would were displayed, have `--diff-noconfirm` continue automatically anyway (for those who want to be risky) 

**Describe alternatives you've considered**

The only alternative seems to be to use `--answerdiff=None` which hides a diff if it exists, and introduces a possible security hole.

**Additional context**
This came up about while trying to make a work-around for #848 / #1199 / #1247 / #1385, which I explain [here](https://github.com/Jguer/yay/issues/1247#issuecomment-709711598).

`"Proceed with install?" appears with --noconfirm` #830  suggested `--answerdiff=None` which I consider to be a security hole.

**Comment by grandchild** [comment]
Would this flag still be useful if #848 would be fixed?
