### ISSUE TITLE
Long delay after pacman sync

### ISSUE THREAD

**Issue by JojiiOfficial** [Jguer/yay#1390]
Version: Latest git commit (next branch)

Introduced with [this commit](https://github.com/Jguer/yay/commit/005b29373d4d1820a567ab8e81fffe62d04ed75b#diff-7bbd5c30244087905cdb86823f1e41b96c8cb2f22a38b113ab365188dded908dL12) the functions `GetRemotePackages` and `GetPackageNamesBySource` (inside `pkg/query/filter.go`) take almost precisely 5s to finish on my machine, which leads to a total delay of around 10s after syncing the databases [here](https://github.com/Jguer/yay/blob/next/install.go#L99). I can't tell exactly if this is only a bug on my machine or a general bug but since there is no issue for it I created this one. 

This commit was added after v10.0.4, which means v10.0.4 (all commits added before the linked one above) are unaffected of this bug under the same circumstances (same installation, same packages, etc...).

**Comment by Jguer** [comment]
I believe it's one place where find satisifiers is used where a direct get was used before. I just need to find it...

**Comment by John-Gee** [comment]
I confirm the issue on my computers and someone else's, so it's definitely not just you.

**Comment by c0dera** [comment]
Can confirm issue.

**Comment by mindyourlifeguide** [comment]
Confirm issue.

**Comment by AtifChy** [comment]
confirm issue

**Comment by alexgantera** [comment]
confirm issue

**Comment by atreyasha** [comment]
Confirm issue

**Comment by ghost** [comment]
Confirm issue. Is only around 3s for me though, and on my server it's just 1-2s oddly.

**Comment by stonespheres** [comment]
Confirm issue, very long wait here.

**Comment by mixedCase** [comment]
Hey everyone, the issue already has a `Status: Confirmed` label (now In progress), no need to further confirm.

**Comment by Jguer** [comment]
@JojiiOfficial this issue should be fixed on `yay-git` as of https://github.com/Jguer/yay/commit/8d9fed2ad02942ddd3ad8e06146e2cfaa537c313 can you confirm?

**Comment by jonpas** [comment]
I can confirm, nice work!

**Comment by JojiiOfficial** [comment]
Works for me too. Good Job!

**Comment by Morganamilo** [comment]
Yeah, Dbs are actual hashmaps. and using .pkg() on a db does a quick lookup. You really don't wanna try to find packages by iteration.

**Comment by Jguer** [comment]
> Yeah, Dbs are actual hashmaps. and using .pkg() on a db does a quick lookup. You really don't wanna try to find packages by iteration.

yeah, I think we had that loop for something else and it ended up going into the Executor as the remote packages implementation by distraction.

I'm tagging a release to get this closed
