### ISSUE TITLE
Missing python2 packages on install

### ISSUE THREAD

**Issue by szymongalka** [Jguer/yay#1391]
![image](https://user-images.githubusercontent.com/72341542/96369283-473eed80-1159-11eb-9736-1b54c4c10160.png)

PS. Fresh Arch installation

**Comment by Meister1593** [comment]
I have pretty much the same issue, it seems that yay can't resolve any dependency (including from repos) of package if it has AUR dependencies.
One more guy (from discord) can confirm this too. This happens on fresh yay installation.
Switched to pikaur for now.

**Comment by fried-ice** [comment]
Can confirm.
It fails finding native pacman packages for dependencies.

New Arch Linux installation:

```
Pacman v5.2.2 - libalpm v12.0.2
yay v10.0.4 - libalpm v12.0.2
```

**Comment by Nayr438** [comment]
Can confirm. yay can not seem to resolve dependencies from the official repos when installing from the AUR.
Attempts to find all dependencies in AUR.

**Comment by szymongalka** [comment]
Yay get today 2 new updates, try to upgrade it
Edit: New update dont change anything

**Comment by lachlanshoesmith** [comment]
+1, same issue on a fresh Arch install. I cannot reproduce this issue on another pre-existing Arch setup running yay v10.0.4.

**Comment by szymongalka** [comment]
Has anyone tried to install an earlier version of yay?

**Comment by Nayr438** [comment]
> Has anyone tried to install an earlier version of yay?

yes. It made no difference. 
makepkg and trizen resolve without issue.

**Comment by szymongalka** [comment]
Then I'm curious why I don't want to work. I don't want to change yay to any other program because I have been using it since the beginning of my adventure with arch.

**Comment by Meister1593** [comment]
@by-speece try pikaur, it has quite nice features compared to yay (like, building with AUR dependencies from PKGBUILD)
only downside i've seen is slow tab completion, but search in pikaur is presented too, so...

**Comment by Jguer** [comment]
To people having this issue, is `yay-git` working for you? I cannot really reproduce this issue

**Comment by szymongalka** [comment]
@Jguer 
I try test it, give me a moment
Edit: yay-git work
Edit2: The problem occurs on fresh instances of arch. If tomorrow I will feel good, I will put a fresh arch on the virtual machine and check if the problem persists. In general, the problem is said to only occur on a fresh arch.

**Comment by by-speece** [comment]
It work

**Comment by Meister1593** [comment]
@Jguer 
yay-git works fine

**Comment by DGatere** [comment]
@Jguer 
Was also experiencing the issue and yay-git works fine

**Comment by marek-lach** [comment]
> @Jguer
> Was also experiencing the issue and yay-git works fine

For me, even `yay-git` doesn't work properly. It always wants to update the same package to the exact version to which it had updated just a minute ago. In other words, it doesn't seem to recognise that an update has occured, even if it performs it?

**Comment by Jguer** [comment]
> For me, even `yay-git` doesn't work properly. It always wants to update the same package to the exact version to which it had updated just a minute ago. In other words, it doesn't seem to recognise that an update has occured, even if it performs it?

This seems like a separate issue, please open a new issue

Closing this issue as there's not much detail on how to reproduce, was just a good opportunity for a release

**Comment by Nayr438** [comment]
yay-git / branch next works fine on a clean install.

**Comment by techtycho** [comment]
Enabling multilib worked for me..

**Comment by shonfeder** [comment]
I'm hitting this problem:

```
yay --version
yay v11.1.1 - libalpm v13.0.1
```

```
sudo yay -Syu
...
==> 
 -> Could not find all required packages:
	python2-mock (Wanted by: python2-automat -> python2-m2r)
	python2-pytest-runner (Wanted by: python2-automat -> python2-m2r)
	python2-pytest-runner (Wanted by: python2-hyperlink)
	python2-wcwidth (Wanted by: python2-automat -> python2-pytest)
	python2-importlib-metadata (Wanted by: python2-automat -> python2-pytest)
	python2-atomicwrites (Wanted by: python2-automat -> python2-pytest)
	python2-funcsigs (Wanted by: python2-automat -> python2-pytest)
	python2-pathlib2 (Wanted by: python2-automat -> python2-pytest)
	python2-setuptools-scm (Wanted by: python2-automat)
	python2-setuptools-scm (Wanted by: python2-automat -> python2-pytest)
	python2-py (Wanted by: python2-automat -> python2-pytest)
	python2-pluggy (Wanted by: python2-automat -> python2-pytest)
	python2-more-itertools (Wanted by: python2-automat -> python2-pytest)
```

It seems to sync with the package repo, but can't actually update packages.

**Comment by grandchild** [comment]
@shonfeder all of the mentioned packages don't actually exist in the AUR (anymore) -- they are all Python2 packages, which is well EOL. For example, if you have a look at [python2-automat](https://aur.archlinux.org/packages/python2-automat) you'll see that one direct dependency is missing and several transitive dependencies are red as well (e.g. [python2-m2r](https://aur.archlinux.org/packages/python2-m2r)). So these errors are actual packages missing, not a `yay` error.

Both packages responsible for the error (python2-automat & python2-hyperlink) have Python3 versions in the official repos: [python-automat](https://archlinux.org/packages/extra/any/python-automat/) & [python-hyperlink](https://archlinux.org/packages/extra/any/python-hyperlink/). Any specific reason you need their Python2 version? If the reason is because your python code is Python2, then you're out of luck and you will only get more of these errors as time goes on and more and more Python2 versions of packages will get dropped. `yay` cannot help you here.
