### ISSUE TITLE
Is there a way to automatically edit a specific package PKGBUILD file in a certain pre-determined way before installing?

### ISSUE THREAD

**Issue by simdimdim** [Jguer/yay#1392]
**Is your feature request related to a problem? Please describe.**
The title says it all, and if it doesn't exist I'm wish if it were a feature.

**Describe the solution you'd like**
Have a dir where I could drop alternative PKGBUILD per package or patch files for them, or just run a hook before the actual build/install of the package begins (after the dl)

**Describe alternatives you've considered**
Have a way for yay to call a custom script when a specific package is being updated

**Additional context**
None

**Comment by Morganamilo** [comment]
Commit your changes to the pkgbuild.

**Comment by simdimdim** [comment]
> Commit your changes to the pkgbuild.

What do you mean/How?

**Comment by Morganamilo** [comment]
Are you family with git at all? Each AUR package is a git repo. So when you edit the pkgbuild commit the changes. Then yay will merge the updates instead of overwriting.

**Comment by simdimdim** [comment]
> Are you family with git at all? Each AUR package is a git repo. So when you edit the pkgbuild commit the changes. Then yay will merge the updates instead of overwriting.

1) Not a package I uploaded
2) not a package I want to have a copy of locally outside the yay cache
3) not sure even if I ignore 1 and 2 doing that would work for future updates to the package to begin with

**Comment by Morganamilo** [comment]
You commit the changes. But not push them.  You don't need to be the maintainer to do that.

The copy in cache is what you're committing to.

**Comment by simdimdim** [comment]
Hm, would try I guess, tho if there's another option I'd probably like it more.

**Comment by Morganamilo** [comment]
AUR packages are already git based so It's really the best tool for the job. Also git is smart and can merge stuff and detect conflicts.

**Comment by simdimdim** [comment]
Works fine for the time being. Thanks. If it breaks for some reason, I'll be back to ask again :)

@Morganamilo would that be affected by cleanBuild btw?
P.S. Apparently it would, oh well.
