### ISSUE TITLE
Fish completion for -S only shows AUR

### ISSUE THREAD

**Issue by ghost** [Jguer/yay#1406]
#### Affected Version

yay v10.1.0.r3.g7d080df - libalpm v12.0.2

**Describe the bug**

`yay -S <TAB>` should show official packages as it used to.

**To Reproduce**

`yay -S sud<TAB>` does not show `sudo` in the list.

**Expected behavior**

`yay -S sud<TAB>` should show `sudo` in the list.

**Output**

**Comment by rien333** [comment]
Works for me. What shell are you usng?

**Comment by ghost** [comment]
> Works for me. What shell are you usng?

Fish

**Comment by Jguer** [comment]
@billop Run `yay -Pcc` and retry, your completion cache should be reset with it

`cat ~/.cache/yay/completion.cache` will show what's in it
