### ISSUE TITLE
AUR builds fail with cleanafter enabled

### ISSUE THREAD

**Issue by muesli** [Jguer/yay#141]
Installing `aur/code` fails, because the sources seem to be deleted before the package finishes building.

**Comment by EmberQuill** [comment]
I've been trying for days to figure out why `yay -Syu` isn't properly updating AUR packages. This ended up being the culprit. Disabling cleanafter immediately resolved the issue. It looks like it downloads the PKGBUILD and other build files, but then deletes the whole folder prior to downloading the sources. It tries to chdir to that folder and fails, then aborts the build process and moves on.
