### ISSUE TITLE
Store package files in separate directory in cache

### ISSUE THREAD

**Issue by BlackZork** [Jguer/yay#1413]
**Is your feature request related to a problem? Please describe.**
When purging cache I would like to preserve the last version of package created by yay and delete everything else. It would be much easier to do it if packages created by yay would be stored in separate directory - just like /var/pacman/cache/pkg.

**Describe the solution you'd like**
Create separate directory in cache for generated packages. Something like:
~/.cache/yay/pkg
~/.cache/yay/build

Move generated packages to pkg/ directory before installing.

**Comment by Morganamilo** [comment]
See PKGDEST in makepkg.conf.

**Comment by Zulgrib** [comment]
There's no reasons to store system wide cache to ~, packages are installed for the system, not your specifically your user.

**Comment by grandchild** [comment]
That is the build cache. And since it's your user that's building the packages, and not the system user, it does make sense.

The installed packages are still cached in `/var/cache/pacman/pkgs/`.

**Comment by BlackZork** [comment]
Ok, PKGDEST solves it.
