### ISSUE TITLE
Database already registered

### ISSUE THREAD

**Issue by airda2895** [Jguer/yay#1414]
#### Affected Version

Unable to check it out, but it's the latest since I have re-installed it.

**Describe the bug**
When I run any command with yay, I always get this message: `Database already registered`.

I cannot even check yay version. I have tried re-installing yay and the issue persists.
**Output**
![image](https://user-images.githubusercontent.com/45570407/98756525-0ab68880-23cb-11eb-9f8d-5979ac218f40.png)

**Comment by grandchild** [comment]
Could it be you have the same issue as #912, namely that you have a duplicate repository in your `/etc/pacman.conf`?

In the future please search open _and closed_ issues, thank you. I know Github defaults to only open issues (why I will never know, but it is like this) -- so remove `is:open` from the search bar when searching issues :slightly_smiling_face:

**Comment by airda2895** [comment]
Thanks @grandchild... Yes, apparently I've had a duplicate repository in there. I have commented it and now it works! 

And ok, I will try to search for open and closed issues the next time. :)

**Comment by t1gu1** [comment]
On Sway, after I install yay, I got that error and I had to comment these lines.

```bash
#[manjaro-sway]
#SigLevel = PackageRequired
#Server = https://packages.manjaro-sway.download/$arch
```

and keep

```bash
[multilib]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist
```
