### ISSUE TITLE
package with dot in name not found

### ISSUE THREAD

**Issue by papajoker** [Jguer/yay#1415]
#### Affected Version

yay v10.1.0 - libalpm v12.0.2

**Describe the bug**
package with version in name not found

**To Reproduce**
```
yay -Si  aspnet-runtime-3.1 aspnet-targeting-pack-3.1 dotnet-runtime-3.1 dotnet-sdk-3.1 dotnet-targeting-pack-3.1
```

**Comment by lwlf** [comment]
Please, remove version number, and try to again.
like: 
```
yay -Si  aspnet-runtime aspnet-targeting-pack dotnet-runtime dotnet-sdk dotnet-targeting-pack
```

**Comment by papajoker** [comment]
ok is not the name but in pkgbuild
aspnet-runtime-2.2 , aspnet-runtime-3.0 hare ok but only last 3.1 not work

**Comment by lwlf** [comment]
> ok is not the name but in pkgbuild
> aspnet-runtime-2.2 , aspnet-runtime-3.0 hare ok but only last 3.1 not work

Pacman does not accept version number input. And you always get the latest versions in pacman.
Of course, archlinux maintains a historical repository, for more info, see: [Arch Linux Archive](https://wiki.archlinux.org/index.php/Arch_Linux_Archive)

**Comment by papajoker** [comment]
no ! here is not the package version in name but the main version of app as gtk2..gtk3 or for java jdk6..jdk12

pikaur -Si  aspnet-runtime-3.1 is valid
https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=aspnet-runtime-3.1 is valid

**Comment by lwlf** [comment]
> no ! here is not the package version in name but the main version of app as gtk2..gtk3 or for java jdk6..jdk12
> 
> pikaur -Si  aspnet-runtime-3.1 is valid
> https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=aspnet-runtime-3.1 is valid

I tried it and it was exactly as you say.
If you use aur, you need to use the 'yay -aSi' command. 
Similar commands: 
```
yay -aS
```
```
yay -aSs
```

**Comment by lwlf** [comment]
Parameter 'a' is to use only aur. 
Yay priority use pacman.
