### ISSUE TITLE
connection reset by peer

### ISSUE THREAD

**Issue by arley3013** [Jguer/yay#1417]
yay -S xxx-lock
Get "https://aur.archlinux.org/rpc.php?arg%5B%5D=xxx-lock&type=info&v=5": read tcp 192.168.42.169:55588->95.216.144.15:443: read: connection reset by peer
[1]    57974 exit 1     yay -S xxx-lock
❯ yay -Pg
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/arley/.cache/yay",
	"absdir": "/home/arley/.cache/yay/abs",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false
}

**Comment by grandchild** [comment]
Does it still persist? The URL works for me. Maybe the AUR had a short outage?

**Comment by grandchild** [comment]
If it really was an AUR outage, maybe a more telling error message would be in order, something along the lines of:

_"AUR is unreachable. This might be an error with your network configuration, or the AUR API server might be having issues. Try accessing [[representative AUR test URL]] in a browser or from another network. If the error also occurs elsewhere, try waiting a few minutes, or report the problem at [[AUR support place]]"_

**Comment by Jguer** [comment]
> If it really was an AUR outage, maybe a more telling error message would be in order, something along the lines of:
> 
> _"AUR is unreachable. This might be an error with your network configuration, or the AUR API server might be having issues. Try accessing [[representative AUR test URL]] in a browser or from another network. If the error also occurs elsewhere, try waiting a few minutes, or report the problem at [[AUR support place]]"_

@grandchild  this would be a nice addition

**Comment by ido** [comment]
FYI, this is happening to me now consistently and seems to be AUR SSH connection rate limiting.  A possible fix for this is to use a [ControlMaster] for connection multiplexing.

[ControlMaster]: https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Multiplexing
