### ISSUE TITLE
[Feature Request] Bring back old feature where `yay` with no arguments defaults to `yay -Syu`

### ISSUE THREAD

**Issue by Jont828** [Jguer/yay#1418]
**Is your feature request related to a problem? Please describe.**
I really liked the feature in older versions of yay where calling `yay` without any flags would default to `yay -Syu`

**Describe the solution you'd like**
I can't tell if the feature has been removed, but by default `yay` no longer defaults to `yay -Syu`. I would like to see the feature come back, or possibly allow it to be toggled in a config file.

**Comment by xeruf** [comment]
```sh
❯ yay --version
yay v10.1.0 - libalpm v12.0.2
```
For me it still defaults to `Syu`

**Comment by Jont828** [comment]
Hmm, I reinstalled yay and it seemed to work as expected, must have been some strange local error. Thanks for pointing it out! I even wrote a function to default the behavior.

```
function yay() {
    if [ -z "$1" ]; then
        command yay -Syu --sudoloop
    else
        command yay $@ --sudoloop
    fi
}
```
