### ISSUE TITLE
Add option to use tab as separator in listings

### ISSUE THREAD

**Issue by xeruf** [Jguer/yay#1419]
**Is your feature request related to a problem? Please describe.**
I use `yay` together with `fzf` to search through package lists, both for installation as well as removal.
While trying to use the same function for both, I realized that with `-Pc` the packages and extra info (repo) are separated by a Tab, whereas `-Q` separates the version with a space.

**Describe the solution you'd like**
I'd like to have both use the same delimiter, preferably Tab. Since it is probably unwanted to change the default for `-Q` for pacman-compatibilty, it would probably need to be a separate flag.

Maybe there are similar requests out there that together would warrant an option for a `nocompatible` mode, which makes `yay` more internally consistent at the expense of adding slight differences to pacman.

**Describe alternatives you've considered**
Split the result by space and tab, but that makes the function unnecessarily lengthy.

**Comment by Morganamilo** [comment]
`-Pc` is only really for internal use. I would use `-Sl`.

**Comment by xeruf** [comment]
Ah thanks, wasn't aware of that :+1: 
Still, having an option to have that listing tab-separated would be nice as well ;)
