### ISSUE TITLE
Add option to prefix -Q listing with repo

### ISSUE THREAD

**Issue by xeruf** [Jguer/yay#1421]
**Is your feature request related to a problem? Please describe.**
Follow-up to #1419 - I'd like to be able to use `-Q` and `-Sl` interchangeably - one for offline/installed listing and the other for online listing i.e. to find installation candidates.

**Describe the solution you'd like**
One point misaligning them is that `-Sl` prefixes each package with the repo, while `-Q` doesn't, but I think it could be useful for both.

**Comment by Morganamilo** [comment]
We just do what pacman does ¯\\\_(ツ)\_/¯
