### ISSUE TITLE
notify if a git package installed from aur has been updated in the official repositories

### ISSUE THREAD

**Issue by ghost** [Jguer/yay#1425]
### Is your feature request related to a problem? Please describe.
i'll give an example - i had to install `mako-git` because it has an important feature upstream but has not seen a release since january. `mako` is in the community repo

### Describe the solution you'd like

would like some kind of notification if the packe in the community repo updates so i can delete `mako-git` and install `mako`

### Describe alternatives you've considered

dunno, i just checked and there's no rss feed for individual packages on packages.archlinux.org. anybody have an idea how to track package updates?

**Comment by Jguer** [comment]
@basedtho that is a very specific feature which I find you'll be less useful than running `yay -Syu --devel` to update `mako-git` in case there are new commits on it
