### ISSUE TITLE
the order in which the parameters are passed about GitFlags.

### ISSUE THREAD

**Issue by pqiaohaoq** [Jguer/yay#1426]
### Affected Version

yay v10.1.1
### Reproduction Steps
1. set `"gitflags": "--depth 1"` in `${HOME}/.config/yay/config.json`
2. yay

### Expected behavior

install the package.

### Output

![telegram-cloud-document-1-5035162346339696890](https://user-images.githubusercontent.com/15377472/99961246-032eb080-2dc9-11eb-9407-687c2bef2e6d.jpg)

### Code

https://github.com/Jguer/yay/blob/f24e21105e44ac411eb536e889b061769ac5a60a/pkg/settings/exe/passers.go#L16-L31

Maybe it's the order in which the parameters are passed.

Why not using `--depth 1 ` by default?

**Comment by Morganamilo** [comment]
Git flags are passed before the specific command `git $FLAGS command` and not `git command $FLAGS`.

As for why not using depth 1? Why would we. I doubt it would make any noticeable difference and may break diffs.
