### ISSUE TITLE
sudoflags breaks yay

### ISSUE THREAD

**Issue by G4Zz0L1** [Jguer/yay#1427]
### Affected Version
yay v10.1.1 - libalpm v12.0.2

### Describe the bug
I can't get `sudoflags` option to work with `-E`. I've found nothing online or in the man with this flag. I don't understand how it works in the source, so I'd like to ask if it's a bug or if I'm doing something wrong.

### Reproduction Steps
1. add `-E` to `sudoflags` option in `config.json` file
2. run `yay -Syu`

### Expected behavior
yay runs normally

### Output
![image](https://user-images.githubusercontent.com/13220636/99976571-e59b2000-2da3-11eb-9970-e95b6ec450dc.png)

```
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/g4zz0l1/.cache/yay",
	"absdir": "/home/g4zz0l1/.cache/yay/abs",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "all",
	"rebuild": "tree",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "name",
	"searchby": "",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "-E",
	"requestsplitn": 150,
	"sortmode": 1,
	"completionrefreshtime": 7,
	"sudoloop": true,
	"timeupdate": true,
	"devel": true,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": true,
	"combinedupgrade": true,
	"useask": true,
	"batchinstall": true
}

```

**Comment by grandchild** [comment]
These lines
https://github.com/Jguer/yay/blob/f24e21105e44ac411eb536e889b061769ac5a60a/exec.go#L30-L33
add the config's sudo flags, and `-v`, to the sudo-loop command. But `-E` is incompatible with `-v`, and the latter is used to extend the sudo auth cache time.

Most flags in `man sudo` do not look like they would be needed to make `sudo -v` work. Removing the config sudo flags, and simply passing `-v` only to the sudo loop fixes the issue for me:
```go
func updateSudo() {
    for {
        err := config.Runtime.CmdRunner.Show(exec.Command(config.SudoBin, "-v"))
```

But then, there might be a ton of corner cases where some flag or other is needed for `-v`...

**Comment by grandchild** [comment]
Oh, and disabling `sudoloop` is also a workaround for the issue.

**Comment by G4Zz0L1** [comment]
What if I need the sudoloop to remain active (for longer compilation) but I also need the `-E` to pass environment variable to sudo?

**Comment by grandchild** [comment]
Then you'll have to wait for a fix.

**Comment by grandchild** [comment]
Or edit `exec.go` with the change above yourself, run `make` and use the resulting `yay` binary instead of the official one...

**Comment by G4Zz0L1** [comment]
Ok, I'll wait for a fix then, I've installed it from the aur package.

**Comment by grandchild** [comment]
@Jguer what do you think, re https://github.com/Jguer/yay/issues/1427#issuecomment-732271547 ?

**Comment by Jguer** [comment]
> @Jguer what do you think, re [#1427 (comment)](https://github.com/Jguer/yay/issues/1427#issuecomment-732271547) ?

I would have liked to make sudo loop compatible with other `su` options but it seems it's a hard task (or at least involves adding a lot more flags). For now let's atleast get sudoloop back to working with `sudo` by not passing any extra flags

**Comment by G4Zz0L1** [comment]
So, it seems it will be fixed? I still have sudoloop to false because of that sudoflags to "-E" and occasionally on long aur compilation it times out.

**Comment by grandchild** [comment]
I'll cook up a PR next week.
