### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by CodeWithShreyans** [Jguer/yay#1428]
Is there a way to switch packages for example if the AUR package name changes from Spotify to Spotify-bin?

**Comment by Morganamilo** [comment]
There's no way to detect this so It can't really be handled.

**Comment by grandchild** [comment]
What Morgan said.

But generally there should be no issue simply uninstalling the one and installing the other package. If the authors of the other package are thorough they will even conflict with the first package and the first one will be uninstalled as part of installing the other one. Unfortunately this doesn't seem to be the case for the `spotify` package.

**Comment by CodeWithShreyans** [comment]
Ok, thanks. BTW, Spotify was just an example.
