### ISSUE TITLE
[Request] More verbose install error feedback

### ISSUE THREAD

**Issue by manen** [Jguer/yay#1429]
### Is your feature request related to a problem? Please describe.
Yes. I'm always very frustrated when I install multiple AUR packages at a time and all I get back is: "no packages match search". 

### Describe the solution you'd like
yay should tell me which packages it can't find in the AUR

**Comment by Morganamilo** [comment]
Please include an example.

**Comment by manen** [comment]
Sure. I ran this command to get fonts for my Arch Linux install:  
```bash
yay ttf-abkai borna-fonts fonts-tlwg lohit-fonts ttf-amiri ttf-ubraille ttf-paratype otf-gfs opensiddur-hebrew-fonts ttf-ancient-fonts
```
and it only gave me "no packages match search", so I manually had to take the command apart to this:  
```bash
yay borna-fonts && yay fonts-tlwg && yay lohit-fonts && yay ttf-amiri && yay ttf-ubraille && yay ttf-paratype && yay otf-gfs && yay opensiddur-hebrew-fonts
```
just to find out which packages yay can't find.

**Comment by Morganamilo** [comment]
`yay foo bar` searches for packages matching foo AND bar

**Comment by manen** [comment]
Oh. Okay then, sorry, closing
