### ISSUE TITLE
Can't build anything when trying to install anything

### ISSUE THREAD

**Issue by kordru** [Jguer/yay#1431]
### Affected Version
yay v10.0.4 - libalpm v12.0.2

### Describe the bug
I can't install anything due to an error in build()

### Reproduction Steps
1. yay (anything)
2. it will download everything
3. error occurs at build()

### Expected behavior
It should fully install anything i try to install.

### Output
(An example is me trying to install polybar)
https://pastebin.com/raw/Z3aQKWRF

**Comment by kido5217** [comment]
From log:
`    cc1plus: error: bad value (‘native=generic’) for ‘-march=’ switch
`

What's your `CFLAGS` value in `/etc/makepkg.conf` ? Paste a whole file if you can.

**Comment by kordru** [comment]
i just did stuff to pacman and fixed it,
