### ISSUE TITLE
Tweak README for installation of yay in Manjaro

### ISSUE THREAD

**Issue by Maskedman99** [Jguer/yay#1435]
Installation of yay in manjaro can be done via pacman ( yay is available in manjaro's community repo ). 
It would be nice if this is mentioned in the README file. 
When installing via pacman, manjaro users don't need to install Go. 
Also this will avoid pacman showing warning that the installed version of yay is greater than the one available in the community repo.

**Comment by Jguer** [comment]
I'm okay to add this but it will include a disclaimer on how sometimes manjaro lags releases for a bit.
