### ISSUE TITLE
Yay hangs after parsing SRCINFO

### ISSUE THREAD

**Issue by 9p4** [Jguer/yay#1440]
### Affected Version

yay v10.1.2.r0.g7d849a8 - libalpm v12.0.2

### Describe the bug

After parsing the SRCINFO, Yay installs the requirements, but hangs after Pacman installs the packages. I need to ^C then restart the process to install the program. After ^C, the package is installed, so the dependency hang doesn't happen. 

### Reproduction Steps
1. Install a package with yay that doesn't have dependencies fulfilled
2. Yay gets stuck after dependency package(s) is/are installed
3. ^C, rerun yay command to finish install

### Expected behavior

I expected the installation of the package to continue as normal, and not hang.

### Output

```sh
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/username/.cache/yay",
	"absdir": "/home/username/.cache/yay/abs",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false
}

```

**Comment by grandchild** [comment]
Which package(s) exactly did you try to install?

**Comment by 9p4** [comment]
The most recent one I had issues with was `rizin-git`, but it happens for every other package that I'd installed using Yay from the AUR that needed to install dependencies

**Comment by grandchild** [comment]
It's strange, I just tested it earlier, and I didn't have that problem. And so far you're the only one that's brought up this problem, and if most people had this this bugtracker would surely be full of them by now. This leads me to think it's something specific on your machine.

So let's try and figure out what it could be.

Does it ever happen with pacman-packages? Have you tried installing anything with just pacman, and see if the post-transaction hooks are not completing or something?

**Comment by 9p4** [comment]
Installing with just pacman works fine, it is when pacman is run by yay under two conditions (SRCINFO dependencies, flushing install queue) where yay hangs.

**Comment by cmorgenstern** [comment]
I am experiencing the same issue - tested with a clean chroot build of yay and the following additional options that I use for all of my invocations of yay:

`yay --editmenu --nodiffmenu --save`

Also tested without these and yay is still hanging after the pacman installation of dependencies. I have to interrupt the entire process with ^C and then re-run the target package installation command. 

I initially wondered if it was an issue with a specific post-transaction hook, but none of the same hooks are hanging during plain pacman installations. I tested using `rizin-git` but this issue occurs with any package installed via yay that does not have its dependencies fulfilled.

Current yay config:

```
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/user/.cache/yay",
	"absdir": "/home/user/.cache/yay/abs",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": false,
	"editmenu": true,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false
}
```

**Comment by benjarobin** [comment]
I think this is the same issue as mine (Otherwise I will create a new issue). I did realize a very quick analyze (I don't really know go and the source of yay...)

When yay "hang" is it executing `sudo pacman -D --asdeps --config /etc/pacman.conf -- pkg`
But this function is called using `config.Runtime.CmdRunner.Capture()` instead of `show()` function: https://github.com/Jguer/yay/blob/HEAD/install.go#L40
My `sudo` is configured to ask for the root password each time (so not cached, ...). But since the prompt to enter the password is captured, yay hang indefinitely waiting for the sudo command to return. This can be easily seen using `htop` with tree mode.

Edit 1: `config.Runtime.CmdRunner.Capture()` cannot be used with `sudo`.
So the quick fix is very easy, but we will see pacman output.

Edit 2: And if pacman output is not desired, just add `-q` option when calling pacman
