### ISSUE TITLE
LC_MESSAGES environment variable should be used to determine the output language

### ISSUE THREAD

**Issue by PaulFridrick** [Jguer/yay#1442]
Hello !

According to the Arch wiki, the LC_MESSAGES environment variable should determine the user interface language : https://wiki.archlinux.org/index.php/Locale

However with this command :
`LANG=fr_FR.UTF-8 LC_MESSAGES=en_GB.UTF-8 yay -Syu`

The yay output is in french while the pacman output is in english :
```
:: Synchronising package databases...
 core is up to date
 extra is up to date
 community is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Recherche de mises à jour dans les bases de données...
:: Recherche des mises à jour AUR...
 il n'y a rien à faire
```

It would be nice to have a consistent output language in yay and pacman :)

Regards

**Comment by Jguer** [comment]
Thanks @PaulFridrick , I'll see what can be done about it
