### ISSUE TITLE
How to install local packages?

### ISSUE THREAD

**Issue by sharpordie** [Jguer/yay#1444]
I would like to do the same with yay instead of trizen.

```
directory=$(mktemp -d) && cd "${directory}"
trizen -G vmware-workstation
sed -i "s/#_enable_macOS_guests=y/_enable_macOS_guests=y/g" "${directory}/vmware-workstation/PKGBUILD"
trizen -S -l --noconfirm vmware-workstation
cd "${HOME}"
```

**Comment by grandchild** [comment]
How about:
```shell
directory=$(mktemp -d) && cd "${directory}"
yay -G vmware-workstation
sed -i "s/#_enable_macOS_guests=y/_enable_macOS_guests=y/g" "${directory}/vmware-workstation/PKGBUILD"
cd vmware-workstation
makepkg -si
cd "${HOME}"
```

**Comment by grandchild** [comment]
(Thanks for `mktemp`, TIL, nice trick 🙂 )

**Comment by sharpordie** [comment]
The problem is that makepkg does not handle the dependencies.  
So if I understand correctly it's not possible with only yay. Right?

**Comment by grandchild** [comment]
There is the workaround of using the `PACMAN` env var for `makepkg`, but it doesn't work out of the box because yay refuses to be run as root, which pacman requires.

This person made a writeup in a similar issue with their workaround: https://github.com/Jguer/yay/issues/1351#issuecomment-698023920
