### ISSUE TITLE
Could not find required packages

### ISSUE THREAD

**Issue by Techman69** [Jguer/yay#1445]
https://cdn.discordapp.com/attachments/797214611799277608/798232026238287952/unknown.png
 
I'm using arch linux with deepin desktop this happens when Installing broadcom wl ck

**Comment by grandchild** [comment]
Yeah, well, the package `broadcom-wl-ck` requires `linux-ck` **<5.3**. But `linux-ck` is _well_ beyond that version at `5.10.6-1`.

`yay -Si broadcom-wl-ck | grep "Last Modified"`:  Sat 12 Oct 2019 04:48:38 PM CEST

I guess the `broadcom-wl-ck` package should be updated.

**Comment by grandchild** [comment]
https://aur.archlinux.org/packages/broadcom-wl-ck#comment-711526 says to use [`broadcom-wl-dkms`](https://archlinux.org/packages/community/x86_64/broadcom-wl-dkms/) from the official repos, which (being a DKMS package) will build automatically for your specific kernel.

**Comment by grandchild** [comment]
For more info, see https://wiki.archlinux.org/index.php/Dynamic_Kernel_Module_Support

**Comment by Techman69** [comment]
Thanks and sorry for the late reply
