### ISSUE TITLE
exit code 127 on yay -T, same as pacman -T

### ISSUE THREAD

**Issue by soloturn** [Jguer/yay#1455]
### Is your feature request related to a problem? Please describe.
#1444 hins on how to install local packages, and #1351 details a little more on one challenge with exit code 1 if a dependency is not there.

### Describe the solution you'd like
please give same exist code on same parameter as pacman. here, for yay -T, give 127 instead of 1.

127 error code is defined here:
https://git.archlinux.org/pacman.git/tree/lib/libalpm/po/en_GB.po#n579

**Comment by julixau** [comment]
I have submitted a PR. 

However (as noted in the PR) this will not enable makepkg to install aur package using `makepkg -s` since yay will refuse to install aur packages as root, which makepkg does at all times :disappointed:
