### ISSUE TITLE
Yay isn't handling correctly packages with a sufix such as "beta"

### ISSUE THREAD

**Issue by Porkepix** [Jguer/yay#1464]
### Affected Version
yay v10.1.2 - libalpm v12.0.2

### Describe the bug
One package on AUR was using the beta versions earlier (https://aur.archlinux.org/packages/rutorrent/) but now offers the non-beta version. However, yay doesn't list it to update, and forcing reinstall (` yay -S rutorrent`) reuses the beta package already built

### Reproduction Steps
1. Install the beta version or have it installed
2. List updates with `yay -Syu`: it won't appear
3. Try to force the update through `yay -S rutorrent`: it'll reuse the beta package already built

### Expected behavior
It should be possible to update easily the package

### Output

```sh
$ yay -Si rutorrent
:: Querying AUR...
Repository      : aur
Name            : rutorrent
Version         : 3.10-1
```

```sh
$ yay -Qi rutorrent
Name            : rutorrent
Version         : 3.10_beta-1
```

```sh
$ yay -S rutorrent
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  rutorrent-3.10-1

  1 rutorrent                        (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: PKGBUILD up to date, Skipping (1/1): rutorrent
  1 rutorrent                        (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: (1/1) Parsing SRCINFO: rutorrent

==> Making package: rutorrent 3.10_beta-1 (Sat 20 Feb 2021 01:38:43 PM CET)
==> Retrieving sources...
  -> Found rutorrent-3.10_beta.tar.gz
  -> Found apache.example.conf
  -> Found apache.example.site.conf
==> Validating source files with sha256sums...
    rutorrent-3.10_beta.tar.gz ... Passed
    apache.example.conf ... Passed
    apache.example.site.conf ... Passed
==> Making package: rutorrent 3.10_beta-1 (Sat 20 Feb 2021 01:38:49 PM CET)
[…]
```

Notice the `PKGBUILD` said to be up to date.

EDIT:
Actually, `yay -Syu` even tells it to be newer:
```
 -> rutorrent: local (3.10_beta-1) is newer than AUR (3.10-1)
```

**Comment by grandchild** [comment]
This is a packaging problem. `3.10` is considered older than `3.10_beta`, as confirmed by pacman's `vercmp`:
```
$ vercmp
vercmp (pacman) v5.2.2

Compare package version numbers using pacman's version comparison logic.

Usage: vercmp 

Output values:
< 0 : if ver1 < ver2
0 : if ver1 == ver2
> 0 : if ver1 > ver2


$ vercmp 1.2 1.2_beta
-1
```

Refer to https://wiki.archlinux.org/index.php/PKGBUILD#pkgver for more details.

**Comment by Porkepix** [comment]
Despite that, is it normal for `yay -S` (and not `-U`) to not build and install the last one available on AUR?

**Comment by grandchild** [comment]
Yes absolutely. I sometimes have a more recent version installed because I updated it myself before the maintainer does. And I wouldn't want yay to _downgrade_ my local package unless explicitly asked to do so!

And for *-git packages that's even the norm, because the pkgver gets incremented locally when newer commits become available -- without any update to the package itself.
