### ISSUE TITLE
[Security] GitHub Actions

### ISSUE THREAD

**Issue by Ry0taK** [Jguer/yay#1468]
Hello yay contributors!
I'm a security researcher who is working on OSS security.

While doing a research related to supply chain attack, I noticed that some repositories are vulnerable to repository hijacking. (This issue has been mitigated by me and GitHub.)
Since the root cause of this issue hasn't been fixed, I'd like to let you know what you should do.

In [multiarch-build.yml](https://github.com/Jguer/yay/blob/b9d3992f13d4499989a7399569ad61b8463ea4cf/.github/workflows/multiarch-build.yml#L131), it uses `commitsar-app/release-notary` action to create the release note.
However, as this repository has been renamed to `aevea/release-notary`, this repository is vulnerable to repository hijacking.
While it's working properly as there is a feature named [Repository redirects](https://github.blog/2013-05-16-repository-redirects-are-here/), `commitsar-app` could be claimed by anyone, and allows repository hijacking once someone published new release. (I already claimed this username, so it can't be abused anymore.)
To fix it, just replace `commitsar-app/release-notary` to `aevea/release-notary` so it can reference original action directly.
(For more context, I've written an article that describes this problem (It's written in Japanese): https://blog.ryotak.me/post/github-actions-supplychain/)

Best Regards,
RyotaK

**Comment by Jguer** [comment]
Hey @Ry0taK , thanks for the heads up, I'll be fixing it before the next release

**Comment by Jguer** [comment]
Fixed as of ca60c15911edf7d84145001fc731fcf1dac577be

**Comment by Ry0taK** [comment]
@Jguer Thank you so much for fixing it ;)
