### ISSUE TITLE
Add option to set diff tool

### ISSUE THREAD

**Issue by d-air1** [Jguer/yay#1470]
### Is your feature request related to a problem? Please describe.
I was looking for a way to show side by side diffs with colored output to make changes easier to read. I read that you used git diff. I thought that I could set the appropriate variables to use an external diff tool with git, but had no success.

### Describe the solution you'd like
I would like for there to be an option like the "--editor" or "--sudo" command, so that I could set the diff tool to something like kdiff3.

**Comment by Jguer** [comment]
Hey @d-air1 , it seems to be possible to set kdiff as diff tool for git:
https://stackoverflow.com/questions/33308482/git-how-configure-kdiff3-as-merge-tool-and-diff-tool

Other examples of changing the diff tool for git:
- https://github.com/so-fancy/diff-so-fancy
- https://github.com/dandavison/delta

**Comment by d-air1** [comment]
Thanks. I'll give those solutions a try.
