### ISSUE TITLE
Add asciicinema video to README.md

### ISSUE THREAD

**Issue by ghost** [Jguer/yay#1471]
https://github.com/morganamilo/paru has a nice introductary demo. I'd love if yay has similar

Also, those screenshots look gorgues. Can u share the Xresources?

**Comment by Jguer** [comment]
You're right, the `README.md` is lacking a bit of attention, as for the colorscheme, I've switch to something more mellow now but I think it should be this one

https://github.com/Jguer/dotfiles/commit/4dbe98acacb0fd5233e6fd4d9657ed963795617f#diff-57f6d128322d1914b8eadddc3117a36f5e5a14d2057e897dcd22096629eb59ef

EDIT: or this one https://github.com/Jguer/dotfiles/commit/167bac7f6fb682c17e63eaed338caf8ce60180da#diff-57f6d128322d1914b8eadddc3117a36f5e5a14d2057e897dcd22096629eb59ef

**Comment by Jguer** [comment]
@bnainar added
