### ISSUE TITLE
Yay fails when downloading a dependency from the repos 

### ISSUE THREAD

**Issue by chrisjbillington** [Jguer/yay#1472]
### Affected Version
`yay v10.1.2.r30.g3d58587 - libalpm v12.0.2`

### Describe the bug
For the specific case of `linux-versioned-bin` on the AUR, `yay` seemingly attempts to download a dependency of one of the packages defined in the PKGBUILD. This fails, but was also unexpected - it's not a make dependency so it should not be downloaded unless that specific package is being installed (the issue occurs when one of the other packages is being installed).

### Reproduction Steps
1. `sudo pacman -Rs linux linux-headers pahole # sorry, you can reinstall them afterwards!`
2. `yay -S linux-versioned-bin`
3. See below error output

### Expected behavior
`yay` should install `linux-versioned-bin` and its dependency defined in the same pkgbase (`linux5.11.6.arch1-1-bin` as of today, but the version number in the package name increments with every release - that's the deal with this package, that each kernel version has a unique package name so different versions can be installed simultaneously).

Instead, `yay` gives an error, seemingly about downloading the source for `pahole`, which is one of the dependencies of the headers package `linux5.11.6.arch1-1-headers-bin defined in the same PKGBUILD`. However, `pahole` is a repository package, and not a source file of this PKGBUILD. And it is a runtime dependency of the headers package, not a makedepend, so I wouldn't have expected it to be downloaded at build time anyway. Also the command I gave `yay` should not result in the headers package being installed anyway - just the kernel package. So this was unexpected for multiple reasons (I'm also confused as to why it fails - the URL for pahole that curl gives an error about looks valid to me).

I have checked that a plain `makepkg` works fine for building the packages in this PKGBUILD.

Also, if I manually install `pahole` prior to attempting to install `linux-versioned-bin` with `yay`, then `yay` runs without error.

### Output
```sh
$ yay -S linux-versioned-bin
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:2]  linux-versioned-bin-5.11.6.arch1-1 (linux5.11.6.arch1-1-bin linux-versioned-bin)

:: Downloaded PKGBUILD (1/1): linux-versioned-bin (linux5.11.6.arch1-1-bin linux-versioned-bin)
  1 linux-versioned-bin (linux5.11.6.arch1-1-bin linux-versioned-bin) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: (1/1) Parsing SRCINFO: linux-versioned-bin (linux5.11.6.arch1-1-bin linux-versioned-bin)
==> Making package: linux-versioned-bin 5.11.6.arch1-1 (Mon 15 Mar 2021 09:31:21)
==> Retrieving sources...
  -> Downloading linux-5.11.6.arch1-1-x86_64.pkg.tar.zst...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 92.7M  100 92.7M    0     0  2180k      0  0:00:43  0:00:43 --:--:-- 3485k
  -> Downloading linux-headers-5.11.6.arch1-1-x86_64.pkg.tar.zst...
curl: (3) URL using bad/illegal format or missing URL
==> ERROR: Failure while downloading file:///var/cache/pacman/pkg/pahole-1.20-1-x86_64.pkg.tar.zst
https://archlinux.mirror.digitalpacific.com.au/core/os/x86_64/linux-headers-5.11.6.arch1-1-x86_64.pkg.tar.zst
    Aborting...
error downloading sources: linux-versioned-bin (linux5.11.6.arch1-1-bin linux-versioned-bin)
```

**Comment by Morganamilo** [comment]
It's not possible to distinguish between build and runtime dependencies so yay has to assume they're all build helps and install them.

**Comment by chrisjbillington** [comment]
I see, yes you are correct that ordinary depends may or may not be required for running `makepkg`, so yay must install them in case they are. I understand now why `yay` is trying to install the dependency, and the remaining issue is that it fails.

Installing `pahole` manually using pacman works, so yay is presumably not doing the right thing to install it. I suppose it's possible I have a malfunctioning mirror or something like that, and pacman falls back to other mirrors whereas `yay` doesn't, or something like that. In any case I wouldn't have expected `yay` to try to manually download dependencies and thought it would merely be using `pacman`.

**Comment by chrisjbillington** [comment]
Actually, you can see in the error I posted above that the file is not being downloaded from my mirror - it's already in the `pacman` cache (so it's obviously not a network error). If I clear the cache, I instead get the following error trying to download `pahole` from my mirror:

```shell
$ yay -S linux-versioned-bin
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:2]  linux-versioned-bin-5.11.6.arch1-1 (linux5.11.6.arch1-1-bin linux-versioned-bin)

:: Downloaded PKGBUILD (1/1): linux-versioned-bin (linux5.11.6.arch1-1-bin linux-versioned-bin)
  1 linux-versioned-bin (linux5.11.6.arch1-1-bin linux-versioned-bin) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: (1/1) Parsing SRCINFO: linux-versioned-bin (linux5.11.6.arch1-1-bin linux-versioned-bin)
==> Making package: linux-versioned-bin 5.11.6.arch1-1 (Mon 15 Mar 2021 11:54:10)
==> Retrieving sources...
  -> Downloading linux-5.11.6.arch1-1-x86_64.pkg.tar.zst...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 92.7M  100 92.7M    0     0  1550k      0  0:01:01  0:01:01 --:--:-- 2390k
  -> Downloading linux-headers-5.11.6.arch1-1-x86_64.pkg.tar.zst...
curl: (3) URL using bad/illegal format or missing URL
==> ERROR: Failure while downloading https://archlinux.mirror.digitalpacific.com.au/extra/os/x86_64/pahole-1.20-1-x86_64.pkg.tar.zst
https://archlinux.mirror.digitalpacific.com.au/core/os/x86_64/linux-headers-5.11.6.arch1-1-x86_64.pkg.tar.zst
    Aborting...
error downloading sources: linux-versioned-bin (linux5.11.6.arch1-1-bin linux-versioned-bin)
```

**Comment by chrisjbillington** [comment]
Apologies, actually I do see the same problem when running `makepkg`, so this is not a problem with `yay`. Sorry for the noise!
