### ISSUE TITLE
yay -Qdt results in exit status 1

### ISSUE THREAD

**Issue by dr-br** [Jguer/yay#1475]
### Affected Version

```sh
> yay -V
yay v10.2.0 - libalpm v12.0.2
```

### Describe the bug
A `yay -Qdt` results in `exit status 1`. Functionality seems not to be affected.
`sudo pacman -Qdt` works (no orphans on my system)

### Expected behavior
no `exit status 1` output

### Output

```sh
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/__/.cache/yay",
	"absdir": "/home/__/.cache/yay/abs",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false
}
```

**Comment by matthewarmand** [comment]
Came here to report the same thing, same version info as OP. I also experimented with sending the `q` output to `/dev/null` and this had no effect in dampening that message:

```
$ yay -Qtdq
exit status 1

$ yay -Qtdq > /dev/null
exit status 1
```

**Comment by grandchild** [comment]
Note: This only happens if no orphans are present. `yay` does not report `exit status 1` when there is other output.

**Comment by grandchild** [comment]
@matthewarmand that message is not output to stdout, which is the output you are redirecting to `/dev/null` but it's stderr instead.

To hide that you have to redirect the stderr filedescriptor, which is `2`:
```shell
yay -Qtd 2> /dev/null
```

(N.B. When you want to hide both stdout (fd: `1`) and stderr (fd: `2`) you have to be a bit more creative:
```shell
[command that outputs to both stdout and stderr] > /dev/null 2>&1
```
The last part says "stderr (`2`) gets redirected (`>`) to the target of (`&`) stdout (`1`)"

**Comment by matthewarmand** [comment]
>Note: This only happens if no orphans are present. yay does not report exit status 1 when there is other output.

Correct, presumably because yay is not returning an exit code of 1 (or any other non-zero exit code) in that case.

>that message is not output to stdout, which is the output you are redirecting to /dev/null but it's stderr instead.

Yeah I figured that was the case, just wanted to call it out in case it helped find/debug the problem. Thanks for the tip! I might use your suggestion to clean up my script output, or I'll just wait for this fix :)

**Comment by Jguer** [comment]
@matthewarmand @dr-br I've added a fix on `yay-git` would you mind trying it out?

**Comment by matthewarmand** [comment]
@Jguer I just installed `yay-git` and tried it and it works for me! When no orphans present it still returns the exit code to the shell
but the `exit status 1` text is no longer printed. Looks great, thanks!

**Comment by dr-br** [comment]
@Jguer :+1: 
(works)

**Comment by Jguer** [comment]
Closing this issue then :smile: , expect a yay release soon
