### ISSUE TITLE
Dependencies should be installed with --asdeps option

### ISSUE THREAD

**Issue by moshiur-raj** [Jguer/yay#1480]
### Affected Version
yay v10.2.0 - libalpm v12.0.2

### Describe the bug
I tried installing tutanota-desktop-bin. The dependencies were installed first and then yay started downloading tutanota. However the download failed. I tried listing the dependencies using pacman -Qtdq but I did not get the dependencies for tutanota. I checked the pacman log and it seems yay installed the dependencies without --asdeps option.

### Reproduction Steps
1.yay -S tutanota-desktop-bin
2.ctrl+c before the package is installed
3.pacman -Qtdq

### Expected behavior
dependencies should be installed with --asdeps option

### Output
```sh
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/moshiur/.cache/yay",
	"absdir": "/home/moshiur/.cache/yay/abs",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "doas",
	"sudoflags": "",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false
}

```

**Comment by Jguer** [comment]
'nss' 'libxss' 'libxtst' 'libappindicator-gtk3' 'libnotify' 'openssl' are the dependencies for tutanota-desktop, would you mind pointing out which were installed in your case? 

I'll try and reproduce this issue

**Comment by moshiur-raj** [comment]
Only `libappindicator` was needed.

![image](https://user-images.githubusercontent.com/36466700/112666966-ec878b80-8e86-11eb-9f46-4402d9bf2159.png)

As you can see from the `tail` command `--asdeps` was not used which is why `pacman -Qtd` did not show any packages.

EDIT: I totally missed the last line. It seems --asdeps was used later? Why does `pacman -Qtd` not work then ?

**Comment by Jguer** [comment]
Can you check `pacman -Qi libappindicator-gtk3`? It should tell you if it's a required by for something or an optional for which would make it not appear in  `pacman -Qtd`

**Comment by moshiur-raj** [comment]
Ah, It was optional for electron. Still this is a problem. If I want to install an AUR package and the installation fails then I'm left with unwanted dependencies.
Can you add a feature that removes newly installed dependencies if the installation was not successful?
