### ISSUE TITLE
Error installing yay

### ISSUE THREAD

**Issue by andreluizs** [Jguer/yay#1482]
### Describe the bug
When try to install yay i have an error.

### Reproduction Steps
1. git clone https://aur.archlinux.org/yay.git
2. cd yay && makepkg -si --noconfirm

![yay-error](https://user-images.githubusercontent.com/7385294/112724539-a1a35d80-8ef2-11eb-92d7-d25c6514dc9c.png)

**Comment by Jguer** [comment]
Seems to be working here, momentary GitHub hiccup?

**Comment by andreluizs** [comment]
You're right, I think it was my connection.
Thank you and sorry for that.
