### ISSUE TITLE
Error installing yay - Gocenter sunset

### ISSUE THREAD

**Issue by akss13** [Jguer/yay#1487]
### Describe the bug

yay installation aborts with an error. Possibly a go issue. 
### Reproduction Steps
1. pacman -S --needed git base-devel
2. git clone https://aur.archlinux.org/yay.git
3. cd yay && makepkg -si

### Expected behavior

yay should install without any errors.

### Output

```sh
➜  yay git:(master) makepkg -si
==> Making package: yay 10.2.0-1 (Mon 12 Apr 2021 08:10:16 PM IST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Installing missing dependencies...
resolving dependencies...
looking for conflicting packages...

Packages (1) go-2:1.16.3-1

Total Installed Size:  597.59 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                                                                                                                 [#######################################################################################] 100%
(1/1) checking package integrity                                                                                                               [#######################################################################################] 100%
(1/1) loading package files                                                                                                                    [#######################################################################################] 100%
(1/1) checking for file conflicts                                                                                                              [#######################################################################################] 100%
(1/1) checking available disk space                                                                                                            [#######################################################################################] 100%
:: Processing package changes...
(1/1) installing go                                                                                                                            [#######################################################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
==> Retrieving sources...
  -> Found yay-10.2.0.tar.gz
==> Validating source files with sha256sums...
    yay-10.2.0.tar.gz ... Passed
==> Extracting sources...
  -> Extracting yay-10.2.0.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
pacman>6
go build -v -trimpath -modcacherw  -ldflags '-s -w -extldflags "-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now" -X "main.yayVersion=10.2.0" -X "main.localePath=/usr/share/locale/"' -buildmode=pie -o yay
go: github.com/Jguer/go-alpm/v2@v2.0.2: reading https://gocenter.io/github.com/%21jguer/go-alpm/v2/@v/v2.0.2.mod: 405 Not Allowed
make: *** [Makefile:112: yay] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
➜  yay git:(master)
```

**Comment by akss13** [comment]
I have done a fresh install, the problem still persists.

**Comment by per7ance** [comment]
Try these solution steps [at here](https://github.com/Jguer/yay/issues/1489) with x86_64 one.

**Comment by Jguer** [comment]
https://status.gocenter.io/

Related to the gocenter's phase out, yay-git should install correctly, I'll be making a patch release soon enough

**Comment by martin-dos-santos** [comment]
> https://status.gocenter.io/
> 
> Related to the gocenter's phase out, yay-git should install correctly, I'll be making a patch release soon enough

Great!, I'm trying to install yay too and I got this error, can I ask what is the benefit of using gocenter as GOPROXY?

**Comment by Jguer** [comment]
> > https://status.gocenter.io/
> > Related to the gocenter's phase out, yay-git should install correctly, I'll be making a patch release soon enough
> 
> Great!, I'm trying to install yay too and I got this error, can I ask what is the benefit of using gocenter as GOPROXY?

`yay` AUR package has been updated and should be working now.

gocenter was set as the default go proxy for chinese users that generally have github and the default goproxy blocked. I've set direct as the preferred method for now, until I get some reports from blocked users

**Comment by martin-dos-santos** [comment]
> > > https://status.gocenter.io/
> > > Related to the gocenter's phase out, yay-git should install correctly, I'll be making a patch release soon enough
> > 
> > 
> > Great!, I'm trying to install yay too and I got this error, can I ask what is the benefit of using gocenter as GOPROXY?
> 
> `yay` AUR package has been updated and should be working now.
> 
> gocenter was set as the default go proxy for chinese users that generally have github and the default goproxy blocked. I've set direct as the preferred method for now, until I get some reports from blocked users

Thanks for taking the time to answer, it's working great now :).
