### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by danny88br** [Jguer/yay#1488]
### Affected Version
d3bc19a0034cccb1fa19765c9eb51c7d776394e7

### Describe the bug
unable to build

### Reproduction Steps
pacman -S --needed git base-devel
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

### Expected behavior
installable pkg

### Output
```go build -v -trimpath -modcacherw  -ldflags '-s -w -extldflags "-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now" -X "main.yayVersion=10.2.0" -X "main.localePath=/usr/share/locale/"' -buildmode=pie -o yay
go: github.com/Jguer/go-alpm/v2@v2.0.2: reading https://gocenter.io/github.com/%21jguer/go-alpm/v2/@v/v2.0.2.mod: 405 Not Allowed
make: *** [Makefile:112: yay] Error 1
==> ERROR: A failure occurred in build().
    Aborting...

```

**Comment by per7ance** [comment]
Try these solution steps [at here](https://github.com/Jguer/yay/issues/1489) with x86_64 one.

**Comment by Jguer** [comment]
https://status.gocenter.io/

Related to the gocenter's phase out, `yay-git` should install correctly, I'll be making a patch release soon enough

**Comment by Jguer** [comment]
Closing in favor of #1487 that was open first
