### ISSUE TITLE
Sort upgrade menu by pacman.conf order

### ISSUE THREAD

**Issue by mindyourlifeguide** [Jguer/yay#1491]
How do I enable [this](https://github.com/Jguer/yay/issues/289#issuecomment-376019964) sorting?
#289 #290 

![image](https://user-images.githubusercontent.com/35348648/115058037-760e0480-9eed-11eb-82ad-81afab15e7ae.png)

**Comment by Morganamilo** [comment]
What does it look like for your currently?

**Comment by mindyourlifeguide** [comment]
@Morganamilo Now it looks like this:
 - community
 - core
 - extra
 - aur

And there should be
 - core
 - extra
 - community
 - aur
![image](https://user-images.githubusercontent.com/35348648/115220017-c0230000-a110-11eb-9c97-bf6aa94d9ef5.png)

**Comment by Morganamilo** [comment]
What's your pacman.conf look like?

**Comment by mindyourlifeguide** [comment]
![image](https://user-images.githubusercontent.com/35348648/115220674-7c7cc600-a111-11eb-8cb6-73d2ea9ec358.png)
![image](https://user-images.githubusercontent.com/35348648/115220691-8272a700-a111-11eb-830e-1a662ee12ed7.png)

**Comment by Morganamilo** [comment]
You know what, I get the same thing. My guess is some one broke the sorting :P

**Comment by mindyourlifeguide** [comment]
Can I fix it somehow?

**Comment by Morganamilo** [comment]
I made a PR for it to relive old times heh.

**Comment by mindyourlifeguide** [comment]
@Morganamilo Thank you very much!
