### ISSUE TITLE
Can't Build. GOPROXY is blocked

### ISSUE THREAD

**Issue by starsareintherose** [Jguer/yay#1496]
### Describe the bug

Can't install
### Reproduction Steps.
Same as the install guide

### Expected behavior

can use it 
### Output

```sh
pacman>6
go build -trimpath -mod=readonly -modcacherw  -ldflags '-X "main.yayVersion=10.2.1" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay
```
and then stop
and produce `error while build()`

**Comment by WryBin** [comment]
I'm in the same situation as you

**Comment by Morganamilo** [comment]
Please post the full error.

**Comment by starsareintherose** [comment]
> I'm in the same situation as you

Could you provide any deltails, I actually installed it via other methods

**Comment by Jguer** [comment]
I feel it's the change of go proxy, can you please post your full log and if you have any go environment variables set such as `GOPROXY`, `GOROOT` or `GOPATH`?

**Comment by starsareintherose** [comment]
==> 正在创建软件包：yay 10.2.1-1 (2021年04月26日 星期一 00时21分37秒)
==> 正在检查运行时依赖关系...
==> 正在检查编译时依赖关系
==> 获取源代码...
  -> 找到 yay-10.2.1.tar.gz
==> 正在验证 source 文件，使用sha256sums...
    yay-10.2.1.tar.gz ... 通过
==> 正在释放源码...
  -> 正在解压缩 yay-10.2.1.tar.gz，使用 bsdtar
==> 正在删除现存的 $pkgdir/ 目录...
==> 正在开始 build()...
pacman>6
go build -trimpath -mod=readonly -modcacherw  -ldflags '-X "main.yayVersion=10.2.1" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay
go: golang.org/x/sys@v0.0.0-20210309074719-68d13333faf2: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/guoyi/yay/src/gopath/pkg/mod/cache/vcs/da0444fc0003f84a590bd6521553c0531086778bca13ec63ace9e0dd258f4b51: exit status 128:
        error: RPC 失败。curl 92 HTTP/2 stream 5 was not closed cleanly before end of the underlying stream
        error: 预期仍然需要 45167 个字节的正文
        fetch-pack: unexpected disconnect while reading sideband packet
        fatal: 过早的文件结束符（EOF）
        fatal: fetch-pack：无效的 index-pack 输出
make: *** [Makefile:112：yay] 错误 1
==> 错误： 在 build() 中发生一个错误。

**Comment by WryBin** [comment]
This is mine. I'm just following the official tutorial and when I type makepkg -si, I get an error like this:

==> Making package: yay 10.2.1-1 (Sun 25 Apr 2021 01:05:19 AM CST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found yay-10.2.1.tar.gz
==> Validating source files with sha256sums...
    yay-10.2.1.tar.gz ... Passed
==> Extracting sources...
  -> Extracting yay-10.2.1.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
pacman>6
go build -trimpath -mod=readonly -modcacherw  -ldflags '-X "main.yayVersion=10.2.1" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay
go: github.com/davecgh/go-spew@v1.1.1: reading github.com/davecgh/go-spew/go.mod at revision v1.1.1: unknown revision v1.1.1
make: *** [Makefile:112: yay] Error 1
==> ERROR: A failure occurred in build().
    Aborting...

I'm using a KDE desktop and I had almost no software installed or do some other configuration.

**Comment by arenekosreal** [comment]
> ==> 正在创建软件包：yay 10.2.1-1 (2021 年 04 月 26 日 星期一 00 时 21 分 37 秒)
> ==> 正在检查运行时依赖关系...
> ==> 正在检查编译时依赖关系
> ==> 获取源代码...
> -> 找到 yay-10.2.1.tar.gz
> ==> 正在验证 source 文件，使用 sha256sums...
> yay-10.2.1.tar.gz ... 通过
> ==> 正在释放源码...
> -> 正在解压缩 yay-10.2.1.tar.gz，使用 bsdtar
> ==> 正在删除现存的 $pkgdir/ 目录...
> ==> 正在开始 build ()...
> pacman>6
> go build -trimpath -mod=readonly -modcacherw -ldflags '-X "main.yayVersion=10.2.1" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay
> go: golang.org/x/sys@v0.0.0-20210309074719-68d13333faf2: invalid version: git fetch -f origin refs/heads/_:refs/heads/_ refs/tags/_:refs/tags/_ in /home/guoyi/yay/src/gopath/pkg/mod/cache/vcs/da0444fc0003f84a590bd6521553c0531086778bca13ec63ace9e0dd258f4b51: exit status 128:
> error: RPC 失败。curl 92 HTTP/2 stream 5 was not closed cleanly before end of the underlying stream
> error: 预期仍然需要 45167 个字节的正文
> fetch-pack: unexpected disconnect while reading sideband packet
> fatal: 过早的文件结束符（EOF）
> fatal: fetch-pack：无效的 index-pack 输出
> make: *** [Makefile:112：yay] 错误 1
> ==> 错误： 在 build () 中发生一个错误。

这是网络连接的问题，找找网上的资料设置`GOPROXY`或者直接设置全局代理
This is because you have connection problem. You can search for ways to set `GOPROXY` or set global proxy directly.

**Comment by starsareintherose** [comment]
> > ==> 正在创建软件包：yay 10.2.1-1 (2021 年 04 月 26 日 星期一 00 时 21 分 37 秒)
> > ==> 正在检查运行时依赖关系...
> > ==> 正在检查编译时依赖关系
> > ==> 获取源代码...
> > -> 找到 yay-10.2.1.tar.gz
> > ==> 正在验证 source 文件，使用 sha256sums...
> > yay-10.2.1.tar.gz ... 通过
> > ==> 正在释放源码...
> > -> 正在解压缩 yay-10.2.1.tar.gz，使用 bsdtar
> > ==> 正在删除现存的 $pkgdir/ 目录...
> > ==> 正在开始 build ()...
> > pacman>6
> > go build -trimpath -mod=readonly -modcacherw -ldflags '-X "main.yayVersion=10.2.1" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay
> > go: golang.org/x/sys@v0.0.0-20210309074719-68d13333faf2: invalid version: git fetch -f origin refs/heads/_:refs/heads/_ refs/tags/_:refs/tags/_ in /home/guoyi/yay/src/gopath/pkg/mod/cache/vcs/da0444fc0003f84a590bd6521553c0531086778bca13ec63ace9e0dd258f4b51: exit status 128:
> > error: RPC 失败。curl 92 HTTP/2 stream 5 was not closed cleanly before end of the underlying stream
> > error: 预期仍然需要 45167 个字节的正文
> > fetch-pack: unexpected disconnect while reading sideband packet
> > fatal: 过早的文件结束符（EOF）
> > fatal: fetch-pack：无效的 index-pack 输出
> > make: *** [Makefile:112：yay] 错误 1
> > ==> 错误： 在 build () 中发生一个错误。
> 
> 这是网络连接的问题，找找网上的资料设置`GOPROXY`或者直接设置全局代理
> This is because you have connection problem. You can search for ways to set `GOPROXY` or set global proxy directly.

Thanks, solved
