### ISSUE TITLE
Set a custom User Agent

### ISSUE THREAD

**Issue by grazzolini** [Jguer/yay#1498]
### Is your feature request related to a problem? Please describe.
No.

### Describe the solution you'd like
For yay to use a custom UA when making requests to the AUR. Right now it uses go-http-client as UA.

### Describe alternatives you've considered
None.

**Comment by Morganamilo** [comment]
What would the use for this be?

**Comment by grazzolini** [comment]
Recently we had issues with Pamac hammering the AUR, and we took advantage that it sent a custom UA to be able to block it and mitigate the issue. If yay sends an UA, it makes it easier to spot issues and know where to report problems.

**Comment by Morganamilo** [comment]
Right. You'll probably need https://github.com/mikkeloscar/aur to add support as all requests go through that.

**Comment by grazzolini** [comment]
Ah, I didn't knew yay was using that wrapper.

**Comment by Jguer** [comment]
@grazzolini this should implemented as of the latest release. Please warn me if anything's wrong or could be done to ease triaging

**Comment by grazzolini** [comment]
@Jguer thanks for implementing this. I already see on the logs the custom yay user agent.
