### ISSUE TITLE
Add additional AUR URLs instead of overwriting it

### ISSUE THREAD

**Issue by TypoMustakes** [Jguer/yay#1507]
### Is your feature request related to a problem? Please describe.

It sucks whenever I have an idea for an AUR package that would be extremely useful to me specifically, but then I remember that the package could get removed from the AUR because it was meant for my personal use (for example, a package for my dotfiles so I could just `yay -Sy my-dotfiles` to sync them across all my devices).

### Describe the solution you'd like

The idea is that instead of overwriting a single value with an entirely new one, the user would be able to add additional AUR URLs, for example, personal remote git repositories containing PKGBUILDs. This would probably be the most convenient if the user could just add their URL to a configuration file, similarly to `/etc/pacman.conf`

### Describe alternatives you've considered

There's already a flag within yay, `--aururl` that is a close enough solution, however this overwrites the default value of aur.archlinux.org and I'd always have to add the flag whenever I run a command in yay. 

### Additional context

None

**Comment by Morganamilo** [comment]
I don't think adding this would benefit anyone other than you to be honestp and even then are you really going to setup your own aurweb for this? It's quite a fidely thing to set up.

You could just keep these packages in git. Or a local repo.

**Comment by Jguer** [comment]
Hey @MiskolcziRichard , the user's AUR URL would have to answer according to https://wiki.archlinux.org/title/Aurweb_RPC_interface. It doesn't seem very feasible for a user to implement this.

As @Morganamilo suggested, a local repository may be the best solution for this unless you're considering another usage scenario

**Comment by Deshdeepak1** [comment]
Yeah, I was trying to build a local aur repo too using --aururl. Would implementing RPC is impossible?
