### ISSUE TITLE
List unavailable AUR packages while updating

### ISSUE THREAD

**Issue by DougTy** [Jguer/yay#151]
Other AUR helpers will tell me what packages aren't available in AUR while updating with `-Syu`:
`:: <package> is not present in AUR -- skipping`

I see that this is shown in `yay -Ps`, however I would request that it's also (perhaps optionally?) shown while updating with `yay -Syu` as it can be very useful to know when AUR packages are removed and I need to go and replace them with something else.

Thanks! Really liking this as a pacaur replacement so far.

**Comment by Morganamilo** [comment]
`yay -Ps` does list them for you. Would it add much value to also list it when updating?

**Comment by DougTy** [comment]
Yes, I think so. Listing unavailable packages while updating can be very useful as AUR packages do occasionally disappear when they're renamed or replaced with something else, and I'd like to be alerted to this kind of issue as soon as possible. `yay -Ps` isn't something that I'd run frequently, whereas I run `yay -Syu` every day.

**Comment by linkjayy** [comment]
I agree with Doug. Having this in the pacman/pacaur-like command list would be good. 

I think you can expect more people to use yay as pacaur dies off from being unmaintained. It would be nice to prepare and stick with the pacman-like commands.

**Comment by Jguer** [comment]
Well, `yay` had that behaviour at the beginning when it did all the RPC communication by itself,  if I remember correctly there's almost no performance hit on adding this, I'm okay with adding it back.

**Comment by Morganamilo** [comment]
I've been fiddling around with this. I was thinking of wrapping rpc.Info with a function that prints orphans, out of date and missing. Then we can constantly get the message on `-G` `-Si` `-S` and so on.

**Comment by Jguer** [comment]
Yes, that's a nice way of doing, it should also do request partition so it doesn't face the `request too long` problem.

 I'm going to release 2.350 as a stabler version so we can go back to breaking stuff without worry.

**Comment by Morganamilo** [comment]
Oh if its not too late I'd like to fix one more bug I noticed today from #145.

**Comment by Morganamilo** [comment]
Sent the pr, it's two lines so hopefully its all good.

**Comment by Morganamilo** [comment]
Looks like i was too late, don't worry about rushing out 2.351.

**Comment by Jguer** [comment]
Let's push out 2.351 then.

**Comment by Morganamilo** [comment]
You can but I' prefer to just wait it out personally I would always wait 24 hours after a commit to make a new release to make sure nothing new comes up. This is tiny though so should be fine.

**Comment by Jguer** [comment]
It's such a tiny commit it won't cause problem, but there will probably some last minute patching needed once 2.350 is on the AUR so I'll push it once the first issues pop up

**Comment by Morganamilo** [comment]
while working on this I realised `pacaur -S activinspire-sk` hangs forever. Is this the same for everyone?

**Comment by Morganamilo** [comment]
It looks like I found the problem maybe. As for as I could tell rpc.Info is meant to return In the same order as the names you put in with anything missing left out. The code assumes this. When I send an rpc.Info with the names 
```go
names := []string{"gstreamer0.10-good-plugins", "bin32-jre" ,"lib32-gstreamer0.10-base" ,"lib32-openssl098"}
```
I get back
```go
[bin32-jre gstreamer0.10-good-plugins lib32-gstreamer0.10-base lib32-openssl098]
```
Which is out of order. I don't know why this is but its likely why I get unexpected behaviour and pacaur just hangs.

This is not a vender issue either. If you try 
```
https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=gstreamer0.10-good-plugins&arg[]=bin32-jre&arg[]=lib32-gstreamer0.10-base&arg[]=lib32-openssl098
```
Directly it still comes out of order. Maybe I've misunderstood and order is not guaranteed. I'll look into this.

**Comment by Morganamilo** [comment]
I really should have opened this in a separate issue really.

rpc.Info order is not defined so that solves that.
