### ISSUE TITLE
yay -S $PACKAGE_LIST results in error (only one operation may be used at a time)

### ISSUE THREAD

**Issue by marcosrdac** [Jguer/yay#1510]
### Affected Version
yay v10.2.2 - libalpm v12.0.2

### Describe the bug
I have a variable with multiple package names, let's call it PACKAGE_LIST. When I use `pacman -Syu $PACKAGE_LIST`, results go as expected: each of the packages are installed. Doing an analogous line with yay with `yay -Syu $PACKAGE_LIST` returns the error "only one operation may be used at a time".

### Reproduction Steps
1. define the variable PACKAGE_LIST (`PACKAGE_LIST="polybar keepmenu"`)
2. run `yay -Syu $PACKAGE_LIST`

### Expected behavior
Polybar and keepmenu to be sequentially installed.

### Output
```
only one operation may be used at a time
```

### Edit (2021-06-01)

As @benjarobin pointed out, the shell plays an important role on this issue.
I use usually write for pure **dash**, and the error occurs in this shell. I could perceive the same happens in **bash**, but it does not happen in **zsh**.

**Comment by benjarobin** [comment]
Are you sure that you run both commands (yay and pacman) from the same shell?
Doing the following operations is not working (under zsh, but works under bash):
```
PACKAGE_LIST="pacman gcc"
pacman -Si $PACKAGE_LIST
```
But the following operations are working (under zsh, and under bash):
```
PACKAGE_LIST=(pacman gcc)
pacman -Si "${PACKAGE_LIST[@]}"
```
Or do something like this (if you really have to use `PACKAGE_LIST="pacman gcc"`)
```
PACKAGE_LIST="pacman gcc"
pacman -Si $(echo $PACKAGE_LIST)
```
***Also*** I cannot reproduce the following Yay output : `only one operation may be used at a time`

**Comment by marcosrdac** [comment]
I am using dash, and the error happens in this shell. The same thing happens in bash on my PC. It doesn't in zsh though.

Your tip on using echo did not work here, giving me the same `only one operation may be used at a time`, but a similar approuch did the job, by getting arguments from stdin (needs a "-" at the end of the yay command):

```
echo $PACKAGE_LIST | yay -Si -
```

**Comment by marcosrdac** [comment]
Oh... My mistake, guys. I actually put a "pacman -Syu" string into the package list. So the full command was expanded like:

```
yay -Syu polybar  ... pacman -Syu ... keepmenu
```

and then, indeed, two operations were being asked to be used at an only command.

Thank you for your time, @benjarobin.
