### ISSUE TITLE
Install local PKGBUILD, equivalent to paru -Ui

### ISSUE THREAD

**Issue by Spixmaster** [Jguer/yay#1512]
I want to build a local PKGBUILD and install it. With paru it would be `paru -Ui` in the suitable working directory.

Is this already possible? I read through the man page several times and did not find it.

**Comment by Optiligence** [comment]
`makepkg -i`?

**Comment by Spixmaster** [comment]
@Optiligence That is possible of course but the problem with that is that AUR dependencies cannot be resolved.

**Comment by Optiligence** [comment]
ahh, fair enough

**Comment by HLFH** [comment]
also the other issue is with meta packages like `postfix`, I suppose a `makepkg -si` would install all packages:

> postfix-3.7.4-4  postfix-cdb-3.7.4-4  postfix-ldap-3.7.4-4  postfix-lmdb-3.7.4-4  postfix-mysql-3.7.4-4  postfix-pcre-3.7.4-4  postfix-pgsql-3.7.4-4 postfix-sqlite-3.7.4-4

I am only interested at installing `postfix` and `postfix-mysql` from the local meta package.

**Comment by HLFH** [comment]
I am wondering if yay v12 fixed that. https://github.com/Jguer/yay/pull/1826

Now testing yay v12:
```
yay -S yay-git
```

`yay-git` is using the `next` branch.

**Comment by Jguer** [comment]
This is implement in yay v12 indeed (available only on `yay-git`) for now.

The command is `yay -Bi <directory of PKGBUILD+SRCINFO>`

**Comment by HLFH** [comment]
@Jguer Good start and great job but it does not work for my specific issue/test with meta packages: https://github.com/Jguer/yay/issues/1899 and https://github.com/Jguer/yay/issues/1900.

**Comment by DUOLabs333** [comment]
@Jguer yay-git still returns version 11.3, though.
