### ISSUE TITLE
libalpm.so.12: cannot open shared object file ( Installed pacman without yay rebuild)

### ISSUE THREAD

**Issue by AlexApps99** [Jguer/yay#1519]
### Affected Version
`yay -V`
`yay: error while loading shared libraries: libalpm.so.12: cannot open shared object file: No such file or directory`

### Describe the bug
Using yay in any way results in the following error message:
`yay: error while loading shared libraries: libalpm.so.12: cannot open shared object file: No such file or directory`
Yes, I keep it up to date.

### Reproduction Steps
1. Have latest pacman
2. Try to use yay

### Expected behavior
Yay should work

### Output
```sh
  0 [lxb ~]$ yay -V
yay: error while loading shared libraries: libalpm.so.12: cannot open shared object file: No such file or directory
127 [lxb ~]$ yay -Pg
yay: error while loading shared libraries: libalpm.so.12: cannot open shared object file: No such file or directory
127 [lxb ~]$ yay --help
yay: error while loading shared libraries: libalpm.so.12: cannot open shared object file: No such file or directory
127 [lxb ~]$ yay
yay: error while loading shared libraries: libalpm.so.12: cannot open shared object file: No such file or directory
127 [lxb ~]$ pacman --version

 .--.                  Pacman v6.0.0 - libalpm v13.0.0
/ _.-' .-.  .-.  .-.   Copyright (C) 2006-2021 Pacman Development Team
\  '-. '-'  '-'  '-'   Copyright (C) 2002-2006 Judd Vinet
 '--'
                       This program may be freely redistributed under
                       the terms of the GNU General Public License.
```

**Comment by ahmubashshir** [comment]
you beat me to it :3

**Comment by SamLukeYes** [comment]
Rebuilding `yay` from AUR manually solves this problem.
https://wiki.archlinux.org/title/Arch_User_Repository#Installing_and_upgrading_packages

```fish
$ yay -V
yay v10.2.2 - libalpm v13.0.0
```

**Comment by ahmubashshir** [comment]
but, the question is, "Is the current yay api compatible with pacman 6?"

**Comment by Liupold** [comment]
quick fix:
```
cd /tmp && git clone 'https://aur.archlinux.org/yay.git' && cd /tmp/yay && makepkg -si && cd ~ && rm -rf /tmp/yay/
```

**Comment by mikoxyz** [comment]
> but, the question is, "Is the current yay api compatible with pacman 6?"

I mean, it seems to work perfectly, so probably?

**Comment by JoveYu** [comment]
you can use cached repo to rebuild
```
cd ~/.cache/yay/yay
git pull
makepkg -si
```

**Comment by Jguer** [comment]
Yes, yay is fully compatible with pacman 6, `yay-bin` needs to be rebuilt which I'll do in short order once the daily image gets rebuilt. I've bumped the pkgbuild so the people who are not so fast with their upgrades get the opportunity to rebuild yay alongside the pacman upgrade.

**Comment by hazelshantz** [comment]
yay also gets removed on endeavourOS when updating and installing pacman v6.0 . seems like reinstalling it via another aur helper/manually solves this issue.

**Comment by IBArbitrary** [comment]
There was an update for yay, when the update for pacman was released. I first updated pacman instead, and got this issue. I wonder if I had first updated yay it would've been smooth.

**Comment by picobyte** [comment]
There are some overzealous clashing defaults preventing building yay, build() stops with:
```go: downloading github.com/davecgh/go-spew v1.1.1
# runtime/cgo
cc1: error: '-fstack-check=' and '-fstack-clash_protection' are mutually exclusive; disabling '-fstack-check=' [-Werror]
cc1: all warnings being treated as errors
```
This shouldn't be a warning or be turned into an error. I cannot find any of these flags set in the package files.

Edit: removing -fstack-clash-protection (temporarily?) from CFLAGS in /etc/makepkg.conf resolved this

**Comment by Morganamilo** [comment]
That may be due to changes to the default makepkg.conf

**Comment by Michael-F-Bryan** [comment]
The above instructions seem to fail because the `"six"` flag doesn't seem to exist. Has anyone else encountered this?

```console
$ go version
go version go1.16.4 linux/amd64

$ cd /tmp && git clone 'https://aur.archlinux.org/yay.git' && cd /tmp/yay && makepkg -si && cd ~ && rm -rf /tmp/yay/
Cloning into 'yay'...
remote: Enumerating objects: 386, done.
remote: Counting objects: 100% (386/386), done.
remote: Compressing objects: 100% (286/286), done.
remote: Total 386 (delta 97), reused 385 (delta 97), pack-reused 0
Receiving objects: 100% (386/386), 81.15 KiB | 201.00 KiB/s, done.
Resolving deltas: 100% (97/97), done.
==> Making package: yay 10.2.2-4 (Thu 03 Jun 2021 18:43:55)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading yay-10.2.2.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   118  100   118    0     0    181      0 --:--:-- --:--:-- --:--:--   180
100  346k  100  346k    0     0   254k      0  0:00:01  0:00:01 --:--:-- 2339k
==> Validating source files with sha256sums...
    yay-10.2.2.tar.gz ... Passed
==> Extracting sources...
  -> Extracting yay-10.2.2.tar.gz with bsdtar
==> Starting build()...
go build -tags six -ldflags '-X "main.yayVersion=10.2.2" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay
go: parsing $GOFLAGS: non-flag "six"
make: *** [Makefile:112: yay] Error 1
==> ERROR: A failure occurred in build().
    Aborting...

$ git log -1
commit a1b41b2b440ce48a64f8a12e34b32cc7f1d269c4
Author: jguer <me@jguer.space>
Date:   Tue Jun 1 08:19:40 2021 +0200

    upgpkg: yay 10.2.2-4

    bump pkgrel
```

**Comment by hazelshantz** [comment]
i had to install yay-git in order to use it again. the yay that is on the official repos still conflicts with pacman

**Comment by cyruzin** [comment]
> quick fix:
> 
> ```
> cd /tmp && git clone 'https://aur.archlinux.org/yay.git' && cd /tmp/yay && makepkg -si && cd ~ && rm -rf /tmp/yay/
> ```

Thanks, that fixed the issue :)

**Comment by microo8** [comment]
> There are some overzealous clashing defaults preventing building yay, build() stops with:
> 
> ```
> # runtime/cgo
> cc1: error: '-fstack-check=' and '-fstack-clash_protection' are mutually exclusive; disabling '-fstack-check=' [-Werror]
> cc1: all warnings being treated as errors
> ```
> 
> This shouldn't be a warning or be turned into an error. I cannot find any of these flags set in the package files.
> 
> Edit: removing -fstack-clash-protection (temporarily?) from CFLAGS in /etc/makepkg.conf resolved this

how to do it non-temporarily?
