### ISSUE TITLE
Feature request: Pass arguments to pacman

### ISSUE THREAD

**Issue by richie-tt** [Jguer/yay#1521]
### Is your feature request related to a problem? Please describe.
I'm working on module for [SaltStack](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.pkg.html#module-salt.modules.pkg) which will support YAY as another package manager for Archlinux.

I would like to pass some arguments to the [pacman](https://archlinux.org/pacman/pacman.8.html) application instead to edit the `pacman.conf` configuration on user machine. For example:  `--noconfirm` or `--color never`

### Describe the solution you'd like
My proposal is to add the support for `pacmanflags`

`--pacmanflags    <flags> Pass arguments to pacman`

example:

```sh
yay -S vim --pacmanflags "--noconfirm"
```

**Comment by Jguer** [comment]
`--noconfirm` is passed to the pacman executable
