### ISSUE TITLE
Unable to build: Permission denied error

### ISSUE THREAD

**Issue by dshoreman** [Jguer/yay#1522]
### Installed Versions
* libalpm **v12.0.2**
* pacman **v5.2.2**
* yay **v10.2.2**
* git **2.31.1**
* go **1.16.4**

### Summary

Some time ago I had an issue building yay, so I switched to yay-bin. Since yay-bin will need a rebuild for pacman 6, I'm trying to switch back to the source version *before* I upgrade Pacman to avoid issues after.

* **When installing yay from source, the `go build` command fails with a *Permission denied* error**
* https://github.com/Jguer/yay/issues/1208#issuecomment-603763094 suggests maybe go isn't executable where someone had similar output, but that's not the case here

#1208 was the closest issue I could find, so the problem is most likely my setup, but where's the best place to start looking?

#### Attempts
I've tried the following, all with the same results:
* `yay -S yay`
* clone from AUR and `makepkg -si`
* clone from GitHub and `make`

### Output
```bash
==> Starting build()...
pacman>6
go build -trimpath -mod=readonly -modcacherw  -ldflags '-X "main.yayVersion=10.2.2" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay
make: go: Permission denied
make: *** [Makefile:112: yay] Error 127
==> ERROR: A failure occurred in build().
    Aborting...
error making: yay
```

```sh
$ which install; whereis install; ls -lh $(which go)
/usr/bin/install
install: /usr/bin/install /usr/share/man/man5/install.5.gz /usr/share/man/man1/install.1.gz
lrwxrwxrwx 1 root root 18 May  6 21:08 /usr/bin/go -> /usr/lib/go/bin/go

$ ls -lh /usr/lib/go/bin/go
-rwxr-xr-x 1 root root 14M May  6 21:08 /usr/lib/go/bin/go
```

**Comment by dshoreman** [comment]
Okay, running `go build` manually without any options *appears* to work (that is, it downloaded the deps and spat out a binary which works well enough to run `./yay -V`).

Trying some other make commands, I noticed anything that goes through go (such as `make clean`) gives the same error.

**Comment by dshoreman** [comment]
Fixed by updating my .zshrc to include an `export GO=/usr/bin/go` line.

@Jguer If go is already in my `$PATH`, shouldn't it work *without* being explicitly defined? Not too fussed, as it now works, but I'm curious if it's a bug or simply my system... feel free to close

**Comment by Jguer** [comment]
That's a weird behavior, I've never seen this happen.

yay's makefile includes a 

```
GO ?= go
``` 

but it should normally resolve to `/usr/bin/go` after

**Comment by Jguer** [comment]
@dshoreman I see your dotfiles include a `export GOBIN="$HOME/.local/bin/go"` , I'd check if it conflicts with `makepkg` when it enters fakeroot

**Comment by dongho-jung** [comment]
I had the same issue today, and I fixed as follows

I'm happy now :D

> Fixed by updating my .zshrc to include an `export GO=/usr/bin/go` line.
> 
> @Jguer If go is already in my `$PATH`, shouldn't it work _without_ being explicitly defined? Not too fussed, as it now works, but I'm curious if it's a bug or simply my system... feel free to close
