### ISSUE TITLE
A failsafe should exist to not uninstall pacman

### ISSUE THREAD

**Issue by Porkepix** [Jguer/yay#1524]
### Affected Version
yay 10.2.2

### Reproduction Steps
In a tentative to update yay without breaking pacman dependency, and therefore having to uninstall yay first to update pacman and then reinstall yay, I tried to only update yay at first from the AUR yay-bin.

The result as presented by yay was the following:

```
Package conflicts found:
 -> Installing yay-bin will remove: pacman (libalpm.so<13-64)
 -> Conflicting packages will have to be confirmed manually
```

I obviously didn't continued, but I'm afraid doing so would severely break the system.

### Expected behavior
yay could probably offer a failsafe to avoid such situation if deemed relevant.

**Comment by Morganamilo** [comment]
HoldPkg is that failsafe.
