### ISSUE TITLE
go: parsing $GOFLAGS: non-flag "six"

### ISSUE THREAD

**Issue by OneOfOne** [Jguer/yay#1525]
Trying to build from `yay-git` and getting:

```sh
go build -tags six -ldflags '-X "main.yayVersion=10.2.3.r0.g6e70e2a" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay
go: parsing $GOFLAGS: non-flag "six"
```

This line in `Makefile` is not working right?

```sh
GOFLAGS ?= -trimpath -mod=readonly -modcacherw
GOFLAGS += $(shell pacman -T 'pacman>6' && echo "-tags six")
```

```
$ go version
go version go1.16.4 linux/amd64
```

**Comment by Jguer** [comment]
@OneOfOne can you clone the repository and try executing `go build -tags six -ldflags '-X "main.yayVersion=10.2.3.r0.g6e70e2a" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay`?

do you have a custom GOPATH or any other GO env variable set?

**Comment by OneOfOne** [comment]
Apparently I did, fixed it locally.

Thanks for your work on yay.

**Comment by Maryse47** [comment]
@Jguer I can reproduce the issue when I set `GOFLAGS="-buildmode=pie -trimpath -ldflags=-linkmode=external -mod=readonly -modcacherw"` in makepkg.conf (this line was taken from [wiki recommendations](https://wiki.archlinux.org/title/Go_package_guidelines#Flags_and_build_options) for go packages.

I see you use similar flags already although I wonder if it's possible to make it work with global `GOFLAGS` as well as not every go project uses those. I guess there are more people who do the same. Alternatively maybe it's possible to unset `GOFLAGS` within PKGBUILD first to make sure there won't be clashes.

**Comment by OneOfOne** [comment]
It's the `GOFLAGS +=` that breaks it, without that it works fine, that might be a Makefile bug or something.

**Comment by OneOfOne** [comment]
Update, copy pasting the failing command and running it in the src folder runs fine.
