### ISSUE TITLE
Rate Limit Reached

### ISSUE THREAD

**Issue by GuptaAnant** [Jguer/yay#1526]
### Describe the bug
<!-- So, I am not sure why this error came but after Pacman 6.0, it conflicted with yay. So I removed yay no problem. Then I installed yay again by the standard makepkg method. But when I ran **yay** again, it came with an issue with AUR packages when it started updating it ```
:: Searching AUR for updates...
Rate limit reached
```
Even if I want to install an AUR package, it won't work
 -->

### Reproduction Steps
1.
2.
3.

### Expected behavior
<!-- Either install or update package-->

### Output
<!-- 
Rate Limit Reached
-->

**Comment by Jguer** [comment]
Not enough information
