### ISSUE TITLE
--news option may skip same-day news released after upgrade

### ISSUE THREAD

**Issue by renatocoutinho** [Jguer/yay#1529]
### Affected Version
yay v10.2.3 - libalpm v13.0.0

### Describe the bug
When using yay -Pw, news are considered new only if they are more recent than last build of native packages, but if news are released on the same day **after** the build, they are skipped and not seen by the user before the next upgrade.

This may be rare but did happen to me, and for me the whole point of yay -Pw is to not get caught "off-guard"; also, "redundant" news created by this change would also be rare.

### Reproduction Steps
1. upgrade the system on date D
2. news posted on date D after upgrade
3. yay -Pw doesn't show any news

### Expected behavior
yay -Pw should include news from the same day as last build date.

**Comment by Jguer** [comment]
Unable to reproduce in test written in 84e872ebe3e5b275f78bb33539546abbfada4573
