### ISSUE TITLE
Add a switch to easily update -git packages during normal pacman update.

### ISSUE THREAD

**Issue by RedAnon** [Jguer/yay#1530]
### Is your feature request related to a problem? Please describe.

Manually updating -git AUR packages and keeping track of them is tedious.
### Describe the solution you'd like

It would be nice to have a feature that updates -git packages during normal update. For example having a switch that can be add into my usual "yay -Syyu" and turns it into "yay-Syyug" the -g signifying that all -git packages have to be rebuilt.
### Describe alternatives you've considered

Well you can do it manually. That's what I use now. grep the packages from pacman and then manually update them. It's tedious tho.
The other alternative is to spam all the AUR maintainers so they change the versioning of their -git packages so they always seem out of date. Also not ideal.

**Comment by grandchild** [comment]
Did you mean `--devel`?

From `man yay`:
```
--devel
    During sysupgrade also check AUR development packages for updates. Currently only Git
    packages are supported.

    Devel checking is done using git ls-remote. The newest commit hash is compared against
    the hash at install time. This allows devel updates to be checked almost instantly and
    not require the original pkgbuild to be downloaded.

    The slower pacaur-like devel checks can be implemented manually by piping a list of
    packages into yay (see examples).
```
