### ISSUE TITLE
Changing default answer

### ISSUE THREAD

**Issue by protist** [Jguer/yay#1531]
### Is your feature request related to a problem? Please describe.
When installing a package, if the config has `"removemake": "ask"`, then the default answer is "N".

```
==> Remove make dependencies after install? [y/N] 
```

Is there a way to make the default answer "Y"? I know that we can automatically pick yes by making the config `"removemake": "yes"`, but this suppresses the question.

### Describe the solution you'd like
My understanding is there are three options. From the `man` page:

       --askremovemake
              Ask to remove makedepends after installing packages.

       --removemake
              Remove makedepends after installing packages.

       --noremovemake
              Do not remove makedepends after installing packages.

It would be great if there were an option to `--askremovemake`, but with "Y" as default.

### Describe alternatives you've considered
None that I can think of. I guess just picking `removemake` and manually overriding it when necessary.

**Comment by protist** [comment]
"further activity"

**Comment by n-st** [comment]
This is still a useful proposition. What's needed to help it move along?

**Comment by protist** [comment]
More spam to feed the bot spam

**Comment by n-st** [comment]
Still relevant.

**Comment by grandchild** [comment]
> What's needed to help it move along?

Someone has to implement a PR for it.
If a maintainer doesn't pick up an issue and the issue is not closed, that means it's in that in-between state of "not interesting enough, but not a bad idea".

This is where outside effort is needed to make it happen, or it just won't happen. Perhaps that means _you_, dear reader, have to give it a try? 🙂

**Comment by n-st** [comment]
Still relevant.
