### ISSUE TITLE
sudo yay -Syu broke my system

### ISSUE THREAD

**Issue by Steve-Dusty** [Jguer/yay#1532]
### Affected Version
Using the newest yay version

### Describe the bug
I errored ```
(cheese:274648): Clutter-CRITICAL **: 19:07:01.263: Unable to initialize Clutter: Unable to initialize the Clutter backend: no available drivers found.

** (cheese:274648): ERROR **: 19:07:01.263: cheese-application.vala:89: Unable to initialize libcheese-gtk

zsh: trace trap (core dumped) cheese```  after running cheese.
### Reproduction Steps
1. sudo yay -Syu
2. cheese

### Expected behavior
Should give the error above

**Comment by AchmadFathoni** [comment]
```
(cheese:274648): Clutter-CRITICAL **: 19:07:01.263: Unable to initialize Clutter: Unable to initialize the Clutter backend: no available drivers found.

** (cheese:274648): ERROR **: 19:07:01.263: cheese-application.vala:89: Unable to initialize libcheese-gtk

zsh: trace trap (core dumped) cheese
```
I think it is a driver problem and not yay's fault. You should file bug to the cheese upstream developer instead.

**Comment by kescherCode** [comment]
Beyond that, yay does give you a funny little warning when you do this...
```
 -> Avoid running yay as root/sudo.
```

**Comment by Jguer** [comment]
Not really a yay issue on this
