### ISSUE TITLE
yay not passing through SSH key passphrase entry(/pinentry) prompt?

### ISSUE THREAD

**Issue by ido** [Jguer/yay#1538]
### Affected Version
`yay v10.2.3 - libalpm v13.0.0`

### Describe the bug
When using `yay` to update AUR packages (e.g. `yay -Syua`), if a passphrase is needed for my ssh key to access AUR (which is a separate IdentityFile configured in my `.ssh/config`), then `yay` does not pass through the passphrase prompt and instead seems to hang.  I *think* that's what's going on, given that `yay -> git -> ssh` is in pstree where it gets stuck.  There is an SSH passphrase prompt happening somewhere, but it seems to not have access to my tty.

### Reproduction Steps
1. `ssh-add -D # remove all identities from ssh-agent`
2.  `yay -Syua # update from AUR with yay when configured for AUR via git+ssh`.

### Expected behavior
I expected to be prompted to enter my SSH key passphrase.  Note that this only occurs with inline pinentry/passphrase entry (the default), not with pinentry GUI modes, when using git+ssh.  

### Output
```sh
$ yay -Syua                                                                                                                [20/20]
:: Searching AUR for updates...
[...snip...]
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
==>
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:16] [...snip...]
[...waits forever without further output...]
```

**Comment by Morganamilo** [comment]
Does this happen with --nodevel?

**Comment by ido** [comment]
Problem persists with `--nodevel`.  (To be clear, once I `ssh-add` my AUR ssh key to my ssh-agent, everything works fine.)

As a side note, `yay` also seems to barf if the SSH connection is reset/interrupted, and does not retry the git clone.  (That's harder to reproduce, though.)

**Comment by ido** [comment]
Problem persists.

**Comment by dannyMendozaa** [comment]
Same problem here, did you find a way to avoid yay asking for passphrase?
