### ISSUE TITLE
--nocleanafter still delete src folder

### ISSUE THREAD

**Issue by AchmadFathoni** [Jguer/yay#1539]
### Affected Version
`yay v10.2.3.r9.gd6cb4c5 - libalpm v13.0.0`

### Describe the bug
After successfully build AUR packages using `--nocleanafter`, the `src` folder is still being deleted.

### Reproduction Steps
1. `yay -Syu --nocleanafter --devel`

### Expected behavior
`--nocleanfter` disables package sources cleaning after successful build which mean `src` folder is note deleted.

**Comment by Morganamilo** [comment]
--cleanafter is about deleting the clone dir afterwards. `-c` is always passed to makepkg.

**Comment by AchmadFathoni** [comment]
Well, @Morganamilo Do you know any AUR helper that doesn't pass `-c`? I have pretty big AUR package which have frequent update and I am avoiding to clean build it every time.

**Comment by Morganamilo** [comment]
Some probably don't no one has asked for it with yay before :P

**Comment by AchmadFathoni** [comment]
> --cleanafter is about deleting the clone dir afterwards. `-c` is always passed to makepkg.

What is clone dir?


> Some probably don't no one has asked for it with yay before :P

Nah, some people asked that, just ignored. #798, #1039

**Comment by Morganamilo** [comment]
When you `git clone htts://aur.archlinux.org/foo`

Also blame the sale bot for that.

**Comment by AchmadFathoni** [comment]
> When you `git clone htts://aur.archlinux.org/foo`

`--cleanafter` never affect `~/.cache/yay/foo` 

> Also blame the sale bot for that.

Did stale bot gain consciousness and install itself?

**Comment by Morganamilo** [comment]
> --cleanafter never affect ~/.cache/yay/foo

Well it should. It actually runs `git clean` in the dir. Not deletes it.

> Did stale bot gain consciousness and install itself?

No but I also didn't install it and I'm not involved enough any more to bother arguing against it. I just answer issues some times.
