### ISSUE TITLE
Auto remove unneeded packages

### ISSUE THREAD

**Issue by boris-stepanov** [Jguer/yay#1540]
Hey!

Other PMs like apt have a very convenient way to treat orphan libraries: mark them as auto installed and call autoremove. In Pacman and Yay we are forced to imitate autoremove with ugly constructions like `pacman -Qtdq | pacman -Rns -`. Sometimes you cannot tell if some specific package can be safely removed, so `pacman -Rscn <some lib>` is not a safe solution.

It would be nice, if you add a simple flag for the `R` option to remove orphans.

**Comment by Morganamilo** [comment]
You mean `yay -c`?

**Comment by boris-stepanov** [comment]
Uh, didn't check -Y flag. Yeah, that's it, thank you!
