### ISSUE TITLE
Unable to download PKGBUILD from ABS

### ISSUE THREAD

**Issue by zhmars** [Jguer/yay#1541]
### Affected Version

`yay v10.2.3 - libalpm v13.0.0`

### Describe the bug

Yay fail to download PKGBUILD from ABS due to `git.archlinux.org` retired.

Ref: https://lists.archlinux.org/pipermail/arch-devops/2021-July/000527.html

### Reproduction Steps
1. `yay -G wget`

### Expected behavior

 Downloads PKGBUILD from ABS

### Output

```sh
:: Querying AUR...
failed to get pkgbuild: wget: error fetching wget: fatal: unable to access 'https://git.archlinux.org/svntogit/packages.git/': Could not resolve host: git.archlinux.org
```

**Comment by edacval** [comment]
https://lists.archlinux.org/pipermail/arch-dev-public/2021-June/030466.html

**Comment by omgold** [comment]
The location of the sources repo has changed. They can now be found at:

https://github.com/archlinux/svntogit-packages.git
https://github.com/archlinux/svntogit-community.git

**Comment by zhmars** [comment]
The error has been fixed in v10.3.0. Thanks!

I just found the message `Querying AUR...` seems wrong here since the package was downloaded from ABS. Am I supposed to create a new issue for that?

**Comment by k0ste** [comment]
Still not works

```python
[k0ste@k0ste tmp]$ yay -V
yay v10.3.0 - libalpm v13.0.0
[k0ste@k0ste tmp]$ yay -G netdata
:: Querying AUR...
failed to get pkgbuild: netdata: error fetching netdata: fatal: unable to update url base from redirection:
  asked for: https://git.archlinux.org/svntogit/community.git/info/refs?service=git-upload-pack
   redirect: https://gitlab.archlinux.org/explore/groups
```

**Comment by yochananmarqos** [comment]
> The error has been fixed in v10.3.0.

Oh really? 🤔

```
❯ yay -G chromium
:: Querying AUR...
failed to get pkgbuild: chromium: error fetching chromium: fatal: unable to update url base from redirection:
  asked for: https://git.archlinux.org/svntogit/packages.git/info/refs?service=git-upload-pack
   redirect: https://gitlab.archlinux.org/explore/groups
```

**Comment by zhmars** [comment]
I'm not sure why you still get the error. But it works for me at least.

```sh
$ yay -V
yay v10.3.0 - libalpm v13.0.0
$ yay -G netdata
:: Querying AUR...
(1/1) Downloaded PKGBUILD from ABS: netdata
```

**Comment by yochananmarqos** [comment]
It works for me from the AUR, but not some ABS packages. `chromium` fails while `firefox` works.

```
❯ yay -V
yay v10.3.0 - libalpm v13.0.0
```

```
❯ yay -G netdata
:: Querying AUR...
(1/1) Downloaded PKGBUILD from ABS: netdata
```

```
❯ yay -G chromium
:: Querying AUR...
failed to get pkgbuild: chromium: error fetching chromium: fatal: unable to update url base from redirection:
  asked for: https://git.archlinux.org/svntogit/packages.git/info/refs?service=git-upload-pack
   redirect: https://gitlab.archlinux.org/explore/groups
```

```
❯ yay -G firefox
:: Querying AUR...
(1/1) Downloaded PKGBUILD from ABS: firefox

```

**Comment by zhmars** [comment]
~~If you are using `yay` package, could you try [`yay-bin`](https://aur.archlinux.org/packages/yay-bin) in AUR? I'm using it for all packages mentioned above without issues~~.

Update:
The issue seems caused by ABS cache. (`$XDG_CACHE_HOME/yay/abs`, fall back to`$HOME/.cache/yay/abs`)

@yochananmarqos, Could you clean the cache diretory and try again?

**Comment by yochananmarqos** [comment]
@zhmars Aha! Yep, removing `~/.cache/yay/abs/chromium/` resolved the issue. Thanks for the tip!

**Comment by yochananmarqos** [comment]
@zhmars Aha! Yep, removing `~/.cache/yay/abs/chromium/` resolved the issue. Thanks for the tip!

**Comment by k0ste** [comment]
@zhmars yes, this helps!
`yay` have a option to clean cache?

**Comment by grandchild** [comment]
yes. the same as pacman: `yay -Sc`

**Comment by Jguer** [comment]
Fixed in the latest version
