### ISSUE TITLE
Certificate Signed by Unknown Authority

### ISSUE THREAD

**Issue by xjwellsx** [Jguer/yay#1542]
### Affected Version

10.2.3.r9.gd6cb4c5-1
### Describe the bug

When running makepkg -si an error is thrown stating that the certificate is signed by an unknown authority.
### Reproduction Steps
1.  git clone https://aur.archlinux.org/yay-git.git
2. cd yay-git
3. makepkg -si
4. error

### Expected behavior

The package to be built and installed.
### Output

 makepkg -si

==> Making package: yay 10.2.3-1 (Fri 02 Jul 2021 10:20:39 AM EDT)

==> Checking runtime dependencies...

==> Checking buildtime dependencies...

==> Retrieving sources...

  -> Found yay-10.2.3.tar.gz

==> Validating source files with sha256sums...

    yay-10.2.3.tar.gz ... Passed

==> Extracting sources...

  -> Extracting yay-10.2.3.tar.gz with bsdtar

==> Removing existing $pkgdir/ directory...

==> Starting build()...

go build -trimpath -mod=readonly -modcacherw -tags six -ldflags '-X "main.yayVersion=10.2.3" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay

go: github.com/Jguer/go-alpm/v2@v2.0.5: Get "https://proxy.golang.org/github.com/%21jguer/go-alpm/v2/@v/v2.0.5.mod": x509: certificate signed by unknown authority

make: *** [Makefile:112: yay] Error 1

==> ERROR: A failure occurred in build().

    Aborting...

**Comment by Jguer** [comment]
Probably you're behind a corporate proxy (or a very insecure network), it is safer if this is not allowed
