### ISSUE TITLE
Hide certain entries from "Missing AUR Packages" list

### ISSUE THREAD

**Issue by tim-tx** [Jguer/yay#1551]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Allow a list in the config that hides entries from the "Missing AUR Packages" list. For example, if we have `Missing AUR Packages:  pkg1 pkg2`, and in `config.json` I then add something like `hide_missing: "pkg1,pkg3"`, we would afterward see `Missing AUR Packages:  pkg2` 

### Describe alternatives you've considered

None

### Additional context

My use case is that I have several PKGBUILDs that I wrote just for local use, I have no interest in submitting them to AUR, and they're cluttering up the "Missing..." list. I'd rather keep that list for potentially anomalous packages, or things that I might want to remove at some point, or things that I should maybe check at some point if an AUR package exists.

**Comment by Jguer** [comment]
I think adding to `IgnorePkg` in `/etc/pacman.conf` should implement this

**Comment by tim-tx** [comment]
Can confirm that it does.
