### ISSUE TITLE
[Localization] Chinese characters make the colons out of order

### ISSUE THREAD

**Issue by SamLukeYes** [Jguer/yay#1553]
### Affected Version
yay v10.3.0.r0.g4a93199 - libalpm v13.0.0

### Describe the bug
When using `yay -Si` to display the infomation of a package from AUR in Chinese, the colons are out of order. Each Chinese character is twice as wide as a common English letter, making the colon moving 1 space rightwards.

### Reproduction Steps
Run `yay -Sia yay` with zh_CN locale setting.

### Expected behavior
The colons should be in order. For example, when running `yay` in English, the colons are in order:
```sh
$ LANG=en_US.utf-8 yay -Sia yay
:: Querying AUR...
Repository      : aur
Name            : yay
Keywords        : arm  AUR  go  helper  pacman  wrapper  x86
Version         : 10.3.0-1
Description     : Yet another yogurt. Pacman wrapper and AUR helper written in go.
URL             : https://github.com/Jguer/yay
AUR URL         : https://aur.archlinux.org/packages/yay
Groups          : None
Licenses        : GPL3
Provides        : None
Depends On      : pacman>5  git
Make Deps       : go
Check Deps      : None
Optional Deps   : sudo
Conflicts With  : None
Maintainer      : jguer
Votes           : 1513
Popularity      : 48.939978
First Submitted : Thu 06 Oct 2016 01:20:04 AM CST
Last Modified   : Wed 14 Jul 2021 12:51:50 AM CST
Out-of-date     : No
```

Also, packages in repositories are not affected, as pacman deals with Chinese characters properly:
*The markdown preview of GitHub also breaks the order of colons when Chinese characters are included, so I have to use a screenshot.*
![image](https://user-images.githubusercontent.com/12882091/125551597-6bca0faf-08b3-4caf-a89d-8ed14d077928.png)

### Output
![image](https://user-images.githubusercontent.com/12882091/125552339-086d6aac-9b70-489f-a3f4-b08a100a0d41.png)

**Comment by zhmars** [comment]
Duplicate of #1332 (part of fixes) #1416 (stale)

Not sure it is helpful, pacman fixed this by [commit#4533c6a](https://gitlab.archlinux.org/pacman/pacman/-/commit/4533c6a8e0f39c7707e671b7f9687607b46f1417), see [FS#59229](https://bugs.archlinux.org/task/59229) for more detail.

**Comment by jdholtz** [comment]
This seems to be fixed for me now. I am using `Alacritty` with the `wqy-zenhei` font.  Here is the output I get:
![2022-12-20-090201_1182x739_scrot](https://user-images.githubusercontent.com/89617856/208697840-a370eabf-1171-4548-a5b8-9241038f9787.png)
![2022-12-20-090320_1364x626_scrot](https://user-images.githubusercontent.com/89617856/208698184-5285882f-32cf-4dbd-8101-d3be5d826767.png)
@SamLukeYes can you check if this error occurs on the latest version of `yay`? This issue could be terminal specific

**Comment by jdholtz** [comment]
This issue actually seems to be duplicated by #1799, which is fixed, so I think this can be closed now.

**Comment by SamLukeYes** [comment]
I've been not using yay for a long time. Closing as it seems to be fixed.
