### ISSUE TITLE
Yay cannot connect to git

### ISSUE THREAD

**Issue by erfoon** [Jguer/yay#1555]
### Affected Version
yay v10.3.0 - libalpm v13.0.0

### Describe the bug
After a system update of about a month ago I could no longer update my AUR packages using yay.
Here is what I get in console for any upgrade or install (this for google-chrome for example):

```error merging google-chrome: fatal: No remote for the current branch.```

### Expected behavior
It should install or upgrade the AUR packages like before.

OS: Manjaro

Loom:
https://www.loom.com/share/3e69e7a1d4164e37930131cbb4a60b0a

**Comment by Jguer** [comment]
Unable to reproduce.

Potential leads:
- `.gitconfig` issues
- corrupt yay cache

Potential workarounds:
- remove .gitconfig and retry
- remove `~/.cache/yay` and retry
