### ISSUE TITLE
Discrepancy of output

### ISSUE THREAD

**Issue by ananthu-sk** [Jguer/yay#1556]
### Affected Version
```
yay -V                                                                                                                   
yay v10.3.0 - libalpm v13.0.0
```

### Describe the bug
![Screenshot_from_2021-07-18_21:41:47](https://user-images.githubusercontent.com/25929911/126074621-267d9653-2fed-466e-987e-fc08f17fca00.png)

2 issues are there-

- I had installed custom packages using makepkg and pkgbuild without helpers. 
Eg - `linux-zen-custom, linux-zen-custom-headers, picom-custom`
But yay is only detecting `picom-custom` as can be seen in the screenshot (`missing AUR Packages`)
- Only `-> virtualbox-ext-oracle: ignoring package upgrade (6.1.16-1 => 6.1.22-1)` line have some color while colors are missing in rest.

### Reproduction Steps
1.Install packages using makepkg and pkgbuild without helpers.
2.yay -Syua

### Expected behavior

- Yay should detect all missing AUR packages.
- Every output should be colored or none colored

**Comment by kwaun** [comment]
Same issue. I'm using IgnorePkg directive in pacman.conf too. The non-colored version numbers come from the packages I added to this directive. The non-ignored packages are colored as expected. 
It only happens with ordinary packages (non-AUR). Updatable AUR packages are showed colored as expected even if they are in the IgnorePkg list.

yay v11.2.0 - libalpm v13.0.1

**Comment by Jguer** [comment]
https://github.com/Jguer/yay/blob/3ef4664d992aaabcf9497714b18da2eade4afb5d/pkg/upgrade/sources.go#L56 requires a bunch of refactoring before being able to remove the color when color is enabled from the version diff>

Closing for now, unless someone wants to handle it
