### ISSUE TITLE
[Localization] yay doesn't refer to either LC_ALL or LANGUAGE

### ISSUE THREAD

**Issue by octaltree** [Jguer/yay#1571]
### Affected Version
yay v10.3.1 - libalpm v13.0.0

### Describe the bug
I want to get messages such as "nothing to do" by specifying English from the environment variable since I use yay from the configuration management tool. LC_MESSAGES and LANG are referenced, but I'd like to see them fall back to LC_ALL and LANGUAGE as well, as many other aur helpers do.

https://github.com/kewlfft/ansible-aur/pull/60

### Reproduction Steps

1. Set the default language to something other than English
cat /etc/locale.conf
```
LANG=ja_JP.UTF-8
```
locale
```
LANG=ja_JP.UTF-8
LC_CTYPE="ja_JP.UTF-8"
LC_NUMERIC="ja_JP.UTF-8"
LC_TIME="ja_JP.UTF-8"
LC_COLLATE="ja_JP.UTF-8"
LC_MONETARY="ja_JP.UTF-8"
LC_MESSAGES="ja_JP.UTF-8"
LC_PAPER="ja_JP.UTF-8"
LC_NAME="ja_JP.UTF-8"
LC_ADDRESS="ja_JP.UTF-8"
LC_TELEPHONE="ja_JP.UTF-8"
LC_MEASUREMENT="ja_JP.UTF-8"
LC_IDENTIFICATION="ja_JP.UTF-8"
LC_ALL=
```
yay -S --noconfirm --needed --cleanafter -u --aur| tail -n 1
```
 何もすることがありません
```

2. Execute with additional enviroments
<details>
<summary>desired results</summary>
env LC_MESSAGES=C yay -S --noconfirm --needed --cleanafter -u --aur| tail -n 1
```
 there is nothing to do
```
env LANG=C yay -S --noconfirm --needed --cleanafter -u --aur| tail -n 1
```
 there is nothing to do
```

</details>

env LC_ALL=C yay -S --noconfirm --needed --cleanafter -u --aur| tail -n 1
```
 何もすることがありません
```
env LANGUAGE=C yay -S --noconfirm --needed --cleanafter -u --aur
```
 何もすることがありません
```

### Expected behavior
I'm not familiar with gettext, but I'd like you to refer to LC_ALL.
<details>
<summary>Other than yay, aur helpers have behavior based on or mimicking gettext and refer to LC_ALL, LANG, LANGUAGE</summary>

### makepkg
makepkg --help| head -n 3
```
makepkg (pacman) 6.0.0

pacman で使用するための互換性のあるパッケージを作成
```
env LC_ALL=C makepkg --help| head -n 3
```
makepkg (pacman) 6.0.0

Make packages compatible for use with pacman
```

LC_ALL is referenced.

### paru
I installed with `yay -S paru-git`.
paru -Su --aur
```
:: AUR の更新を確認しています
:: 開発の更新を確認しています
:: AUR にないパッケージ: linux-latest
:: out of date とマークされている: luacheck
:: 孤児: hts-engine
 何もすることがありません
```
env LC_ALL=C paru -Su --aur
```
:: Looking for AUR upgrades
:: Looking for devel upgrades
:: packages not in the AUR: linux-latest
:: marked out of date: luacheck
:: orphans: hts-engine
 there is nothing to do
```
LC_ALL is referenced.

### pacaur
pacaur is in status archived.
I installed with `yay -S aurman-git`.
pacaur --help | head -n 3
```
使い方: pacaur <オペレーション> [オプション] [パッケージ] -- pacaur(8) も参照
オペレーション:
 pacmanの拡張
```
env LC_ALL=C pacaur --help | head -n 3
```
usage:  pacaur <operation> [options] [target(s)] -- See also pacaur(8)
operations:
 pacman extension
```
LC_ALL is referenced.

### trizen
trizen is only available in English. https://github.com/trizen/trizen/issues/49

### pikaur
I installed with `yay -S pikaur-git`.
pikaur -Su --aur
```
:: AUR 全体の更新を開始...
リポジトリのパッケージデータベースを読み込み中...
ローカルのパッケージデータベースを読み込み中...
AUR のパッケージ情報を読み込み中...
:: 警告: 次のパッケージは AUR に存在しません:
    linux-latest
:: 実行すべき処理はありません。
```
env LC_ALL=C pikaur -Su --aur
```
:: Starting full AUR upgrade...
Reading repository package databases...
Reading local package database...
Reading AUR packages info...
:: warning: Following package cannot be found in AUR:
    linux-latest
:: Nothing to do.
```
LC_ALL is referenced.

### aurman
I installed with `yay -S aurman`.
aurman -Su --aur
```
:: システム全体の更新を開始...
警告: manjaro-hello: ローカル (0.6.7-2) の方が extra よりも最新です (0.6.6-6)
 何も行うことがありません

~~ initializing aurman...
~~ the following packages are neither in known repos nor in the aur
:: linux-latest-5.10-1
~~ calculating solutions...
:: nothing to do... everything is up to date
```

env LC_ALL=C aurman -Su --aur
```
:: Starting full system upgrade...
warning: manjaro-hello: local (0.6.7-2) is newer than extra (0.6.6-6)
 there is nothing to do

~~ initializing aurman...
~~ the following packages are neither in known repos nor in the aur
:: linux-latest-5.10-1
~~ calculating solutions...
:: nothing to do... everything is up to date ```
```

env LC_ALL=ja_JP.UTF-8 LANG=ja_JP.UTF-8 LC_MESSAGES=ja_JP.UTF_8 LANGUAGE=ja_JP.UTF-8 aurman -Su --aur
```
:: システム全体の更新を開始...
警告: manjaro-hello: ローカル (0.6.7-2) の方が extra よりも最新です (0.6.6-6)
 何も行うことがありません

~~ initializing aurman...
~~ the following packages are neither in known repos nor in the aur
:: linux-latest-5.10-1
~~ calculating solutions...
:: nothing to do... everything is up to date
```
aurman is only available in English. It appears that `--aur` is ignored
</details>

### Output

```sh
{
        "aururl": "https://aur.archlinux.org",
        "buildDir": "/home/octaltree/.cache/yay",
        "absdir": "/home/octaltree/.cache/yay/abs",
        "editor": "",
        "editorflags": "",
        "makepkgbin": "makepkg",
        "makepkgconf": "",
        "pacmanbin": "pacman",
        "pacmanconf": "/etc/pacman.conf",
        "redownload": "no",
        "rebuild": "no",
        "answerclean": "",
        "answerdiff": "",
        "answeredit": "",
        "answerupgrade": "",
        "gitbin": "git",
        "gpgbin": "gpg",
        "gpgflags": "",
        "mflags": "",
        "sortby": "votes",
        "searchby": "name-desc",
        "gitflags": "",
        "removemake": "ask",
        "sudobin": "sudo",
        "sudoflags": "",
        "requestsplitn": 150,
        "sortmode": 0,
        "completionrefreshtime": 7,
        "sudoloop": false,
        "timeupdate": false,
        "devel": false,
        "cleanAfter": false,
        "provides": true,
        "pgpfetch": true,
        "upgrademenu": true,
        "cleanmenu": true,
        "diffmenu": true,
        "editmenu": false,
        "combinedupgrade": false,
        "useask": false,
        "batchinstall": false
}
```

**Comment by Jguer** [comment]
https://www.ibm.com/docs/en/aix/7.2?topic=variables-environment-precedence-example Implementation basis
