### ISSUE TITLE
yay creates directory in cwd whenever it is used

### ISSUE THREAD

**Issue by cinatic** [Jguer/yay#1583]
### Affected Version
`yay v10.3.1 - libalpm v13.0.0`

### Describe the bug

hi not sure if this is even a bug but some weeks ago i had to build something in a seperate directory, i am not really sure what exactly but i think i used what has been suggested here https://github.com/Jguer/yay/issues/840 to do so

`yay -Syu --builddir=vrnavi --save`

now i am getting whereever i call yay a directory vrnavi even if i not setting the builddir anymore. i also can not figure out where this is coming from there is nothing in /etc, $HOME or var lib mentioning ***vrnavi***

the directory is only created when i use yay and not when i use e.g. pacman directly

### Reproduction Steps

-

### Expected behavior

-

### Output

-

**Comment by cinatic** [comment]
ok well, i just read through the cli help and the settings are saved interesting didn't expected this, so changing to something like `yay --builddir=/tmp/yay --save` helps

**Comment by Morganamilo** [comment]
Well just don't pass --save if you don't want the settings to save...
