### ISSUE TITLE
Make package names bold in search output?

### ISSUE THREAD

**Issue by groutr** [Jguer/yay#1586]
### Is your feature request related to a problem? Please describe.
I frequently search for packages and the output of `yay -Ss` makes it difficult to scan quickly. The package name and description blend together and makes the listing difficult to jump from reading each description to finding the package name.

### Describe the solution you'd like
Would it be possible to bold the line with package name? This would increase the visibility of the package name and whether or not it is installed. Underline might work as well. Currently the package name blends in with the description (see screenshot below).

### Alternative features
Adding a newline between each package listing would also help, but might make some outputs with lots of packages super long. I like the compactness of the current listing.

### Additional context
![yaypkg](https://user-images.githubusercontent.com/10678620/130067775-4fe606d8-12ee-40d0-83ff-2de94d11d92a.png)

**Comment by Morganamilo** [comment]
We copy pacman's formatting so what they do we do.
