### ISSUE TITLE
`yay -Syuua` does not downgrade AUR packages if local is newer than AUR

### ISSUE THREAD

**Issue by BujuArena** [Jguer/yay#1590]
### Affected Version

`yay v10.3.1 - libalpm v13.0.0`

### Describe the bug

`yay -Syuua` does not downgrade AUR packages if local is newer than AUR.

### Reproduction Steps

1. Have an AUR package installed.
2. Have the maintainer of that AUR package lower the version number.
3. Try to downgrade that package using `yay -Syuua`.

### Expected behavior

The package which has a newer version installed locally than AUR is expected to be downgraded the same way that non-AUR packages are downgraded when using `uu` in the command line.

### Output

```sh
[alex@alex-pc ~]$ yay -Syuua
:: Searching AUR for updates...
:: Checking development packages...
 -> pygtk: local (2.24.0-16) is newer than AUR (2.24.0-12)
 -> python2-gobject2: local (2.28.7-7) is newer than AUR (2.28.7-6)
 -> Orphaned AUR Packages:  fiddler
 -> Flagged Out Of Date AUR Packages:  slack-desktop
 there is nothing to do
[alex@alex-pc ~]$
```

**Comment by Jguer** [comment]
I'm not even sure this is a "normal" custom of the AUR (I see issues that could pop up from this with devel packages), but I can't find info on the wiki. For standard repository packages the behavior is known so I'm trying to find arguments against implementing this for AUR

**Comment by BujuArena** [comment]
Maybe make it only work when the user explicitly requests it, like with `uu` and `a` together, and document that.  The problem is just that `yay` can't do it currently.

I don't see how this is a feature request and not a bug though, since the documentation for `uu` does not explicitly discount the AUR.

**Comment by BujuArena** [comment]
This is still relevant.  See my previous comment.

**Comment by Jguer** [comment]
Stale should stay away from this issue now. And I do agree that it would make sense to support it
