### ISSUE TITLE
FR for docs: installation instructions for Ubuntu

### ISSUE THREAD

**Issue by jcollum** [Jguer/yay#1591]
I'm sure it would save people some time. Radarr (common movie catalog app) suggests using `yay` for installation. I'm all for that, but I can't find any install instructions for Ubuntu.

**Comment by jcollum** [comment]
Oh a few minutes of research says this is not possible. Sorry. Closing.

**Comment by Jguer** [comment]
No problem @jcollum :slightly_smiling_face:  Maybe it's time to give Arch Linux a chance

**Comment by jcollum** [comment]
If installing things on Arch doesn't involve manipulating text files I'm
all in. I'm still amazed at how much manual labor is involved in installing
things in linux, a decade after I first looked at it.
