### ISSUE TITLE
Version Handling Improvement

### ISSUE THREAD

**Issue by mpalermo73** [Jguer/yay#1596]
### Affected Version

```
-> % yay -V
yay v10.3.1 - libalpm v13.0.0
```

### Describe the bug

If package has a letter in the version, it appears to be ignored.  In this case zoomn is the focus of the report.  The rest is there just for command output completeness.

```
:: Searching AUR for updates...
 -> zoom: local (5.7.6-1) is newer than AUR (5.7.6a-1)
 -> Orphaned AUR Packages:  nodejs-hackmyresume  python2-mutagen
 -> Flagged Out Of Date AUR Packages:  minecraft-launcher
 there is nothing to do
```

### Expected behavior

zoom version `5.7.6-1` should be getting upgraded to version `5.7.6a-1` 

THANK YOU!

**Comment by Morganamilo** [comment]
The aur maintainer has the versioning wrong. The version should be `5.7.6.a-1` for alpm to recognise it as newer.
