### ISSUE TITLE
Cron job `yay -Syu` as root doesn't work for AUR packages

### ISSUE THREAD

**Issue by jac-cbi** [Jguer/yay#1597]
### Affected Version

yay v10.3.1 - libalpm v13.0.0

### Describe the bug

I build, run, and maintain many servers on my home network.  I have a strict automated update / upgrade policy.  I'd rather have a box fail to reboot than have an out-of-date system running on the local network.  Between Gentoo, Arch, and now Artix this process has always worked well, with a reasonable level of security. Gentoo's `emerge` utility is run as `root`, and drops privileges to the `portage` user for downloading and building all packages.  Arch's `pacman`, since it doesn't build packages, runs as `root`.

In both cases, `root` is necessary due to installing packages.  To be blunt, this is the *nix way.  `sshd` launches as root (due to listening on port 22, and reading host keys from `/etc/`), and drops privileges for each connection.  There are plenty of other examples of this security best practice (Apache httpd, nginx, postfix to name a few).

I've found `yay` to be the best AUR helper except in one regard:  It's stubborn refusal to run as `root` and drop privileges as needed.  I've seen the other issues around this topic.  And I wholeheartedly agree that software should *not* be downloaded and built as the `root` user.

But I can't type in my unprivileged user's password at 3am when the cron job runs.  And unlike other reporters of this issue, adding a user to `sudoers` with `NOPASSWD` is not an option.  For exactly the reasons we all agree on.

Please consider permitting `yay` to be called as `root` and dropping privileges to `nobody` or `yay` user for downloading, and building AUR packages.

### Reproduction Steps

1. Call `yay -Syu` as root with upgrades available to an installed AUR package, e.g. `netatalk`
2. Watch `yay` happily install Arch/Artix updates, then blow up for the AUR updates
3. Cry a little bit at the email reports each morning from each affected server

### Expected behavior

`yay` happily runs as `root` and reasonably drops privileges to a dedicated user account, say `yay`, for downloading and building AUR packages.

Respectfully,

Jason.

**Comment by jac-cbi** [comment]
Quick side note:  I've now had to run `yay -Su` for the third time because of a proper `sudo` timeout.  The situation is that I'm having to manually call `yay` every once in a while to update AUR packages (due to the above issue).  It takes a while to build, so I switch to a different desktop, and do more interesting things.  Then I miss the prompt... sigh.

Fixing this issue would have the advantage of providing a better user experience for long AUR builds as well.

**Comment by Jguer** [comment]
:+1: This feature will be implemented in a commit added to #1595 with systemd-run,

I'm closing this issue to track on the main issue https://github.com/Jguer/yay/issues/69

**Comment by jac-cbi** [comment]
IIUC, `systemd-run` restricts what a process running as root is permitted to do.  This is, I guess, ok.  But it is systemd-centric.   Will `yay` still spawn a subprocess and drop privileges?  That would make it a more secure tool, especially in Artix / ARMtix.
