### ISSUE TITLE
How can i update all package installed via aur?

### ISSUE THREAD

**Issue by thanhngvpt** [Jguer/yay#16]
Hi all.
Yay seem good to me now, thanks for created it. But some time i want to upgrade all packages installed from aur, any command such as with yaourt `yaourt -Syyu --aur`.
Many thanks.

**Comment by Jguer** [comment]
Been testing now. The behavior of `yaourt -Syyu --aur` seems to be the default behavior of `yay -Syu` that updates the package repositories if needed and checks for updates on all AUR packages.

Was this your question?

**Comment by thanhngvpt** [comment]
Many thanks @Jguer exactly what i want?
