### ISSUE TITLE
Can I just use yay instead of pacman?

### ISSUE THREAD

**Issue by Brannua** [Jguer/yay#1601]
Hello, What are the essential differences between yay and pacman? Besides,where can I get these informations from?Thanks a lot.

**Comment by Morganamilo** [comment]
Yay is designed to act the same as pacman but also adding support for the AUR where appropriate. The man page lists what is extended to support the AUR.

**Comment by Brannua** [comment]
> Yay is designed to act the same as pacman but also adding support for the AUR where appropriate. The man page lists what is extended to support the AUR.

Thanks for your reply, can I just use yay instead of pacman? Will there be problems if I only use yay instead of pacman?

**Comment by Jguer** [comment]
> > Yay is designed to act the same as pacman but also adding support for the AUR where appropriate. The man page lists what is extended to support the AUR.
> 
> Thanks for your reply, can I just use yay instead of pacman? Will there be problems if I only use yay instead of pacman?

- You can use yay instead of pacman (at least that's the objective).
- There should not be problems as for repository operations yay calls pacman (if there is a problem feel free to open an issue about it :smiley: )

**Comment by Brannua** [comment]
> > > Yay is designed to act the same as pacman but also adding support for the AUR where appropriate. The man page lists what is extended to support the AUR.
> > 
> > 
> > Thanks for your reply, can I just use yay instead of pacman? Will there be problems if I only use yay instead of pacman?
> 
> * You can use yay instead of pacman (at least that's the objective).
> * There should not be problems as for repository operations yay calls pacman (if there is a problem feel free to open an issue about it smiley )

Thank you ~
