### ISSUE TITLE
use su instead of sudo if the user is not a sudoer

### ISSUE THREAD

**Issue by adrinjalali** [Jguer/yay#1602]
Right now if I run `yay` from a user which is not a sudoer (which is the case with all my users on my machines), `yay` would try to run with `sudo`, and of course it'd fail.

It would be nice for the tool to run with `su` instead of `sudo` if the current user is not a sudoer.

The background is that for security reasons the user which is used by the user on a daily basis, has to be different and have a different password from a user which has sudoer privileges. Therefore I'd do those commands as root with `su` instead.

Also note that the good old `yaourt` had this behavior as well.

**Comment by Jguer** [comment]
Already implemented in `yay-git` in https://github.com/Jguer/yay/commit/c8fcdeae5b168d7a3eb3d805ee823d0fd5658b85 . Should be in the next release of yay
