### ISSUE TITLE
local is not newer than AUR

### ISSUE THREAD

**Issue by yarons** [Jguer/yay#1605]
### Affected Version

yay v10.3.1 - libalpm v13.0.1

### Describe the bug

Package version appears as if the local is newer than AUR but the opposite is correct.

### Reproduction Steps

1. Run `yay -Syyu` with zoom preinstalled
2. The following message appears:
`zoom: local (5.7.6-1) is newer than AUR (5.7.6a-1)`

### Expected behavior

Looking at the git it looks like the version with a is in fact newer than the one without a:
https://aur.archlinux.org/cgit/aur.git/log/?h=zoom

**Comment by Morganamilo** [comment]
The maintainer has the incorrect pkgver format.

**Comment by yarons** [comment]
Seems legit, thanks.
