### ISSUE TITLE
Warn about out of sync mirrors

### ISSUE THREAD

**Issue by Phyks** [Jguer/yay#1606]
Hi,

### Is your feature request related to a problem? Please describe.

Some official Arch repositories are out of sync. This is the case from http://archlinux.de-labrusse.fr/ which is the first server listed in the "France" output of the archlinux.org mirrorlist tool: https://archlinux.org/mirrorlist/?country=all&country=FR&protocol=http&protocol=https&ip_version=4.

See http://archlinux.de-labrusse.fr/, last sync was more than 6 months ago, in March of 2021.

### Describe the solution you'd like

I would like yay to fetch the lastsync/lastupdate value from the used repository and display a clear warning whenever this value has a large offset (say > 24h for instance) to warn user about using out of sync repositories and then probably missing last updates / using softwares with security issues. 

### Additional context

Thanks!
Best,

**Comment by Jguer** [comment]
Reflection points to consider:

- Difference between sourcing Arch mirrors and Arch ARM mirrors
- Seems no API endpoint is available, scraping is possible but we don't want to put any undue pressure on the mirror list page (it's probably not made to be hit as many times as the AUR RPC)

**Comment by HalJordan** [comment]
I use reflector for this already. It will give you the latest N number of mirrors based on when they were last updated, then sort them by speed. I have this run on a cron so it's not poking all of those every time I go to install a package.

**Comment by Jguer** [comment]
Closing as an upstream issue, no API exists to monitor server status and scraping would be uneven between ARM and x64
