### ISSUE TITLE
Yay unable to resume certain interrupted packages

### ISSUE THREAD

**Issue by naclander** [Jguer/yay#1607]
Downloading an aur package ( regolith-full ), interrupting it, and then trying to install it again via yay shows the following failure:

```
  -> Downloading paper-icon-theme_1.5.723-201905252133~daily~ubuntu19.04.1_all.deb...
** Resuming transfer from byte position 2592768
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 39.4M    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
==> ERROR: Failure while downloading https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+files/paper-icon-theme_1.5.723-201905252133~daily~ubuntu19.04.1_all.deb
```

I believe this AUR package downloads multiple packages ( deb files ), and this is not resumable, which yay tries to do.

This feature of yay usually works fine,  but is yay able to handle this particular curl error, and retry the download from the beginning instead of relying on what is in the cache?

The current workaround for this is to run `yay -Sc` before retrying.

**Comment by rupansh** [comment]
Its better to remove the specific folder for the package in `~/.cache/yay` instead of clearing the whole cache

**Comment by grandchild** [comment]
Or you could ask yay for a "clean build" on that package:

```shell
yay -Syu --cleanmenu
# or
yay -S --cleanmenu regolith-full
```
and then answering the menu in a way that makes a clean build for the specific package that is problematic.

You can also always have yay ask for a clean build (I have this turned on):
```shell
yay --cleanmenu --save
```

**Comment by ilario** [comment]
Seems a duplicate of #1222 and I just observed it.
In my case, the download got interrupted due to the faulty internet connectivity.
Do you think that yay could catch this error and re-download the whole file or at least include, in the error message, a suggestion on how to solve the issue?
