### ISSUE TITLE
Performing incorrect action ask for sudo if it needs privileges

### ISSUE THREAD

**Issue by notramo** [Jguer/yay#161]
Removing nonexistent package launches `sudo`, then prints that package don't exists. Running `sudo` isn't needed.

**Comment by Morganamilo** [comment]
Pacman also needs sudo to remove non existing packages.

**Comment by notramo** [comment]
Yes, I noticed, but why couldn't be Yay a more comfortable tool?

**Comment by Morganamilo** [comment]
You're free to make a pr yourself. This is very low priority for me though so it will be a while before I get around to it if I do.
