### ISSUE TITLE
fatal: cannot change to 'clean': No such file or directory

### ISSUE THREAD

**Issue by mrsteve0924** [Jguer/yay#1610]
### Affected Version
yay v11.0.0 - libalpm v13.0.1

### Describe the bug
after pacman finishes installing file i get this error
output of pacman...

![yay](https://user-images.githubusercontent.com/37476191/136677289-73c518c2-b7a6-4dfa-a9fc-cf7e5faa8b68.png)

package does get installed. i do have makepkg saving packages to another location other than the yay default location if that matters. 

$ yay -Pg
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/fakeman/.cache/yay",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "A",
	"answerdiff": "n",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "pkexec",
	"sudoflags": "",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": true,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false

**Comment by Jguer** [comment]
Hey @mrsteve0924 , I've found the issue, seems to have been a small forgetful moment. Thanks for reporting the issue
