### ISSUE TITLE
yay fails to create custom build directory ("buildDir": "/tmp/yay") 

### ISSUE THREAD

**Issue by tam1m** [Jguer/yay#1612]
### Affected Version
yay v11.0.1.r0.g52efaeb - libalpm v13.0.1

### Describe the bug

yay doesn't create the build directory if it does not exist and fails

### Reproduction Steps

1.set `"buildDir": "/tmp/yay",` in config.json
2. try to install some package with yay -S package

### Expected behavior

yay creates `buildDir` if it does not exist and uses it

### Output

```sh
:: Checking for conflicts...
:: Checking for inner conflicts...
->
Package conflicts found:
-> Installing yay-bin will remove: yay-git (yay)
-> Conflicting packages will have to be confirmed manually
[Aur:1]  yay-bin-11.0.1-1

:: (0/1) Downloaded PKGBUILD: yay-bin
-> error fetching yay-bin: fatal: cannot change to '/tmp/yay': No such file or directory
context: exit status 128
```

```json
{
"aururl": "https://aur.archlinux.org",
"buildDir": "/tmp/yay",
"editor": "kate",
"editorflags": "",
"makepkgbin": "makepkg",
"makepkgconf": "",
"pacmanbin": "pacman",
"pacmanconf": "/etc/pacman.conf",
"redownload": "no",
"rebuild": "yes",
"answerclean": "",
"answerdiff": "",
"answeredit": "",
"answerupgrade": "",
"gitbin": "git",
"gpgbin": "gpg",
"gpgflags": "",
"mflags": "",
"sortby": "popularity",
"searchby": "name-desc",
"gitflags": "",
"removemake": "ask",
"sudobin": "sudo",
"sudoflags": "",
"requestsplitn": 150,
"sortmode": 0,
"completionrefreshtime": 1,
"sudoloop": true,
"timeupdate": false,
"devel": true,
"cleanAfter": false,
"provides": true,
"pgpfetch": true,
"upgrademenu": true,
"cleanmenu": true,
"diffmenu": true,
"editmenu": true,
"combinedupgrade": false,
"useask": false,
"batchinstall": true
}
```

**Comment by Jguer** [comment]
I confirm this bug, we're no longer ensuring the creation of the build dir but we're not giving proper warning that it doesn't exist.

To fix:

- [ ] yay defaults to a prefixed temp dir in case a persistent build dir is not available
- [ ] If the build dir specified in `~/.config/yay/config.json` doesn't exist, warn that the dir does not exist and use a prefixed temp dir.

Workaround:

Change the builddir value in `~/.config/yay/config.json`

Affected:

Users with an old config of yay that used to default to `/tmp/yay`. thanks for the  continued use :sweat_smile: 

---

EDIT: revised below, `/tmp/yay` usage is too important

**Comment by Digitalone1** [comment]
Why would you not ensure the creation? 

I had to downgrade yay because of this bug. Please fix for the users that don't want the buidDir on their SSD.

**Comment by tam1m** [comment]
Well, thank you for the continued development of yay. It's awsome! ;)

But, I agree with Digitalone1. Why should yay not just create `buildDir` if it doesn'n exist? What was the reasoning for the changed behaviour?

I am also biulding my packages in tmpfs on purpose

**Comment by Morganamilo** [comment]
For reference pacman will create its own cachedir if it doesn't exist.

**Comment by Jguer** [comment]
This was changed due to `systemd-run` inclusion that insists in creating its own build dir due to permissions/ownership. 

It is clear now that this will not work well for some users (I underestimated the amount of users using `/tmp/yay` as build directory).
 
I will change the behavior so build dir creation is assured (unless it's `/var/cache/yay` which systemd-run uses).

**Comment by Jguer** [comment]
Tentative fix in `yay-git`, will push out a patch bump soon but first I'd like to try and implement a regression test
