### ISSUE TITLE
Make yay package search hyphen-agnostic

### ISSUE THREAD

**Issue by dginovker** [Jguer/yay#1616]
### Is your feature request related to a problem? Please describe.

`yay -s lunarclient` yields no results, but [searching](https://aur.archlinux.org/packages/?O=0&K=Lunarclient) the AUR for `lunarclient` finds the package `lunar-client`

### Describe the solution you'd like

`yay -s lunarclient` should find `lunar-client` like the AUR itself does

### Describe alternatives you've considered

[Requesting](https://aur.archlinux.org/packages/lunar-client/) the owner of the lunar-client AUR package to include the keyword `lunarclient` in the package description

### Additional context

This would help other packages as well :smile:

**Comment by mattalxndr** [comment]
What would be really cool is if there was a multi keyword search. I'm constantly running commands like this:

Say I wanted to find a python interface for Pulseaudio:

```shell
yay -Ss pulse | paste - - | grep -i python
```

Would be nice to have the search fuzzy enough to handle something like:

```shell
yay -Ss 'pulse python'
```

That's probably a feature request I'd file at the pacman repo though. Then maybe it'll trickle down.

**Comment by Morganamilo** [comment]
Yay ands together all keywords by default.

**Comment by Morganamilo** [comment]
Also -s on its own is not a thing. If you meant -S then that only matches exact package or provides.

**Comment by mattalxndr** [comment]
> Yay ands together all keywords by default.

I didn't even think to try, silly me.

> Also -s on its own is not a thing. If you meant -S then that alias matches exact package or provides.

Not sure what you're referring to. The small "s" in `yay -Ss pulse` is just short for `--search pulse`, so these are equivalent:

```shell
yay -Ss pulse
yay --sync --search pulse
```

Seems like this is what you're saying, I'm just confused about why you're saying it.

**Comment by Morganamilo** [comment]
The original issue used yay -s
