### ISSUE TITLE
doas is not being used while compiling; directly jumps to su if didn't find sudo

### ISSUE THREAD

**Issue by whoisYoges** [Jguer/yay#1618]
**_### doas_** works fine while using yay; but doesn't work while compiling/installing yay.

yay searches for **sudo** while compiling; 
if it didn't find sudo it uses su, but many of us have been using [opendoas](https://archlinux.org/packages/community/x86_64/opendoas/) in place of sudo.

So it would be better if it search and use opendoas (doas) if it didn't find sudo before going to su while compiling/ installing yay as well.

## While compiling; as you can see below  it directly uses su if it didn't find sudo.

$ git clone https://aur.archlinux.org/yay.git
Cloning into 'yay'...
remote: Enumerating objects: 414, done.
remote: Counting objects: 100% (414/414), done.
remote: Compressing objects: 100% (305/305), done.
remote: Total 414 (delta 106), reused 413 (delta 106), pack-reused 0
Receiving objects: 100% (414/414), 86.09 KiB | 456.00 KiB/s, done.
Resolving deltas: 100% (106/106), done.
$ cd yay
$ ls                                                                                                                          
PKGBUILD
$ makepkg -si                                                                                                                 
**_==> WARNING: Cannot find the sudo binary. Will use su to acquire root privileges._**
==> Making package: yay 11.0.2-1 (Wed 20 Oct 2021 07:02:35 PM +0545)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading yay-11.0.2.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   118    0   118    0     0    195      0 --:--:-- --:--:-- --:--:--   195
100  358k  100  358k    0     0   219k      0  0:00:01  0:00:01 --:--:-- 1409k
==> Validating source files with sha256sums...
    yay-11.0.2.tar.gz ... Passed
==> Extracting sources...
  -> Extracting yay-11.0.2.tar.gz with bsdtar
==> Starting build()...
go build -trimpath -mod=readonly -modcacherw -ldflags '-X "main.yayVersion=11.0.2" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay
go: downloading github.com/Jguer/aur v1.0.0
go: downloading github.com/Jguer/go-alpm/v2 v2.0.6
go: downloading github.com/Morganamilo/go-pacmanconf v0.0.0-20210502114700-cff030e927a5
go: downloading github.com/Morganamilo/go-srcinfo v1.0.0
go: downloading github.com/leonelquinteros/gotext v1.5.0
go: downloading golang.org/x/term v0.0.0-20210927222741-03fcf44c2211
go: downloading github.com/pkg/errors v0.9.1
go: downloading golang.org/x/sys v0.0.0-20211007075335-d3039528d8ac
go: downloading golang.org/x/text v0.3.7
==> Entering fakeroot environment...
==> WARNING: Cannot find the sudo binary. Will use su to acquire root privileges.
==> Starting package()...
msgfmt po/pt.po -o po/pt.mo
msgfmt po/pt_BR.po -o po/pt_BR.mo
msgfmt po/en.po -o po/en.mo
msgfmt po/es.po -o po/es.mo
msgfmt po/eu.po -o po/eu.mo
msgfmt po/fr_FR.po -o po/fr_FR.mo
msgfmt po/ja.po -o po/ja.mo
msgfmt po/pl_PL.po -o po/pl_PL.mo
msgfmt po/ru_RU.po -o po/ru_RU.mo
msgfmt po/zh_CN.po -o po/zh_CN.mo
msgfmt po/ko.po -o po/ko.mo
install -Dm755 yay /home/invalid/Gitclones/yay/pkg/yay/usr/bin/yay
install -Dm644 doc/yay.8 /home/invalid/Gitclones/yay/pkg/yay/usr/share/man/man8/yay.8
install -Dm644 completions/bash /home/invalid/Gitclones/yay/pkg/yay/usr/share/bash-completion/completions/yay
install -Dm644 completions/zsh /home/invalid/Gitclones/yay/pkg/yay/usr/share/zsh/site-functions/_yay
install -Dm644 completions/fish /home/invalid/Gitclones/yay/pkg/yay/usr/share/fish/vendor_completions.d/yay.fish
for lang in pt pt_BR en es eu fr_FR ja pl_PL ru_RU zh_CN ko; do \
	install -Dm644 po/${lang}.mo /home/invalid/Gitclones/yay/pkg/yay/usr/share/locale/$lang/LC_MESSAGES/yay.mo; \
done
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "yay"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: yay 11.0.2-1 (Wed 20 Oct 2021 07:02:55 PM +0545)
==> Installing package yay with pacman -U...
**_Password:_**

## Using yay after installing; as you can see below, doas is being used when it didn't find sudo befor jumping to su.
$ yay -Sy
**_doas (invalid@y0935h) password:_**

**Comment by Jguer** [comment]
Hey @YogeshLamichhane , this issue is related to the `makepkg` util and not `yay`.

You may find related links that might help guide your request [here](https://wiki.archlinux.org/title/Pacman_development)

**Comment by whoisYoges** [comment]
@Jguer Thanks!
Finally found a solution.

should use: PACMAN_AUTH=(doas)
in /etc/makepkg.conf
