### ISSUE TITLE
Wrong option parsing

### ISSUE THREAD

**Issue by notramo** [Jguer/yay#163]
- Yay ignores nonexisting option (e.g. `yay -Sű`).
- Conflicting (or ambigous) actions are ignored, and performed wrong.
  - `yay -Sy crystal --info exa` synchronizes the database, and prints info about `crystal` and `exa` packages, however this is ambigous, because the user may want to update the database, install `crystal`, and view info about `exa`. In this case, one operation should be permitted only.
  - `yay -Syui` ignores the `-i` option.

**Comment by Morganamilo** [comment]
Flags are not ordered `yay -Sy crystal --info exa` is not ambiguous. You asked for `--info` so it give you info. It doesn't matter if `crystal` comes before it.

**Comment by Jguer** [comment]
Seems like a non issue, closing until it generates real problems
