### ISSUE TITLE
AUR package with local commit: `fatal: Not possible to fast-forward, aborting`

### ISSUE THREAD

**Issue by Zoddo** [Jguer/yay#1635]
### Affected Version

yay v11.0.2 - libalpm v13.0.1

### Describe the bug

I have an AUR package on which I've made a change in its PKGBUILD, and committed it in the cached repository.

When trying to update this package with `yay -Suy`, I get the following error:
```
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  teamviewer-15.23.9-1

:: (0/1) Downloaded PKGBUILD: teamviewer
removing untracked AUR files from cache...
:: Cleaning (1/1): /home/zoddo/.cache/yay/teamviewer
 -> error fetching teamviewer: fatal: Not possible to fast-forward, aborting. 
         context: exit status 128
```

It looks like yay is running `git pull` with the `--ff-only` flag.  
Manually running `git pull` in the `~/.cache/yay/teamviewer` directory works as expected.

### Reproduction Steps

1. Install a package and make a change in the PKGBUILD
2. Commit that change to the local repository to preserve it for future updates
3. Try to update the package to a new version

### Expected behavior

yay runs `git pull`, and new commits are automatically merged into the local repository.

### Output

See above for outputs

<details>
  <summary><code>yay -Pg</code></summary>

```json
{
    "aururl": "https://aur.archlinux.org",
    "buildDir": "/home/zoddo/.cache/yay",
    "editor": "",
    "editorflags": "",
    "makepkgbin": "makepkg",
    "makepkgconf": "",
    "pacmanbin": "pacman",
    "pacmanconf": "/etc/pacman.conf",
    "redownload": "no",
    "rebuild": "no",
    "answerclean": "",
    "answerdiff": "",
    "answeredit": "",
    "answerupgrade": "",
    "gitbin": "git",
    "gpgbin": "gpg",
    "gpgflags": "",
    "mflags": "",
    "sortby": "votes",
    "searchby": "name-desc",
    "gitflags": "",
    "removemake": "ask",
    "sudobin": "sudo",
    "sudoflags": "",
    "requestsplitn": 150,
    "sortmode": 0,
    "completionrefreshtime": 7,
    "sudoloop": false,
    "timeupdate": false,
    "devel": false,
    "cleanAfter": true,
    "provides": true,
    "pgpfetch": true,
    "upgrademenu": true,
    "cleanmenu": false,
    "diffmenu": true,
    "editmenu": true,
    "combinedupgrade": false,
    "useask": false,
    "batchinstall": false
}
```
</details>

<details>
  <summary><code>git config -l --show-origin --show-scope</code> in ~/.cache/yay/teamviewer</summary>

```
global	file:/home/zoddo/.gitconfig		user.name=Zoddo
global	file:/home/zoddo/.gitconfig		user.email=git@zoddo.fr
global	file:/home/zoddo/.gitconfig		user.signingkey=43E8D68722C7D376
global	file:/home/zoddo/.gitconfig		core.autocrlf=false
global	file:/home/zoddo/.gitconfig		rerere.enabled=true
global	file:/home/zoddo/.gitconfig		commit.gpgsign=true
global	file:/home/zoddo/.gitconfig		pull.rebase=true
global	file:/home/zoddo/.gitconfig		includeif.gitdir:~/.cache/yay/.path=~/.cache/yay/.gitconfig
global	file:/home/zoddo/.cache/yay/.gitconfig	commit.gpgsign=false
global	file:/home/zoddo/.cache/yay/.gitconfig	pull.rebase=false
local	file:.git/config		core.repositoryformatversion=0
local	file:.git/config		core.filemode=true
local	file:.git/config		core.bare=false
local	file:.git/config		core.logallrefupdates=true
local	file:.git/config		remote.origin.url=https://aur.archlinux.org/teamviewer.git
local	file:.git/config		remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
local	file:.git/config		branch.master.remote=origin
local	file:.git/config		branch.master.merge=refs/heads/master
```
</details>

**Comment by grandchild** [comment]
I think the suggested workflow for local changes is to _not_ commit. Otherwise I believe the following would happen:

<img width="489" alt="yay-continuous-merge" src="https://user-images.githubusercontent.com/770029/141653837-c0fccfbc-4f38-4dc5-9197-08e662ab1eb8.png">

I might be wrong...

The other possibility would be to use `git pull --rebase`, possibly even the new `git pull --rebase --autostash` (to gracefully handle local uncommitted changes).

**Comment by Morganamilo** [comment]
No this is supported. It worked when I implemented it. Not sure if that's been changed.

**Comment by Jguer** [comment]
This might have been from mutualizing several git calls, this should be restored to `git pull --rebase --autostash`

**Comment by Jguer** [comment]
Must have been when `-G` an `-S` pkgbuild fetching got merged, they should now both have the same behavior with `--rebase` and `--autostash`
