### ISSUE TITLE
Can't install a package when using a different builddir

### ISSUE THREAD

**Issue by DarkRedman** [Jguer/yay#1637]
### Affected Version

yay v11.0.1 - libalpm v13.0.1

### Describe the bug

Can't install a yaourt package if the builddir is different than the default one. The zip file will be missing, because it doesn't download it when the builddir is different even if use flags such as --rebuild --redownload.
I tried it by installing the package davinci-resolve

### Reproduction Steps

1. Open terminal
2. Type : `yay --rebuild --builddir=<mybuilddir> --redownload --rebuild -S davinci-resolve`
3. Choose default option 1 (4 packages are available)

### Expected behavior

I expect it to download the zip file containing the sources before building it and installing it even if the builddir is different.
My guess is it's still checking if the source files is already in default builddir even I use the flags.

### Output

The error output

```sh
==> Création du paquet davinci-resolve 17.4.1-1 (ven. 19 nov. 2021 12:06:50)
==> Récupération des sources…
==> ERREUR : DaVinci_Resolve_17.4.1_Linux.zip n’a pas été trouvé dans le répertoire de travail et n’est pas un URL.
 -> erreur lors du téléchargement des sources : davinci-resolve 
	 context: exit status 1 
	 

/run/media/<username>/My Passport/temp_buildir/davinci-resolve/PKGBUILD: ligne 93 : [: /run/media/<username>/My : opérateur binaire attendu
==> Création du paquet davinci-resolve 17.4.1-1 (ven. 19 nov. 2021 12:06:51)
==> Vérification des dépendances pour l’exécution…
==> Vérification des dépendances pour la compilation…
==> Récupération des sources…
==> ERREUR : DaVinci_Resolve_17.4.1_Linux.zip n’a pas été trouvé dans le répertoire de travail et n’est pas un URL.
 -> erreur lors de la construction : davinci-resolve
 ```
 
 The second part of the error with binary operator and  the fact it doesn't consider the full "/run/media/<username>/MyPassport/temp_buildir/" either using the double quotes or escaping the whitespace with a \ character is weird!

Yay -pg

```sh
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/<username>/.cache/yay",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false
}
```

**Comment by Jguer** [comment]
Should be solved with the latest `pkgbuild` dir fixes with -Bi
