### ISSUE TITLE
Yay garbles command line output with 'cannot load shared object file' under certain conditions

### ISSUE THREAD

**Issue by redcathode** [Jguer/yay#1641]
### Affected Version

`yay v11.0.2 - libalpm v13.0.1` but I feel like the "bug" is present in most/all yay versions

### Describe the bug

If a library sudo depends on receives a soname bump, said library is upgraded before sudo is, and `sudoloop` is set to true, yay's output will be garbled with `cannot open shared object file` until sudo itself is upgraded. I suppose this is less a bug and more a design flaw, but I figure it's still worth creating an issue for.

### Reproduction Steps

1. Run a system upgrade where a library sudo depends on receives a soname bump.
2. Wait for said library to be upgraded
3. Watch in horror

### Expected behavior

Proposed solution: if sudo fails more than 5 times consecutively, stop trying to call it.

### Output
[Console output](http://ix.io/3FPi)
[.config/yay/config.json](http://ix.io/3FPk)

**Comment by Jguer** [comment]
Yeah, it's more of an oversight than a bug, but should be easy to implement :+1:
