### ISSUE TITLE
Allow rebuild of whole AUR dependency tree

### ISSUE THREAD

**Issue by Blutkoete** [Jguer/yay#1644]
### Is your feature request related to a problem? Please describe.

Currently, Boost 1.76 is coming in. ROS Noetic is an example of a big bunch of AUR packages depending on Boost. Currently, I manually rebuild these packages against Boost in the correct order so that later upgrades to packages higher up in the dependency chain do not fail because one of their dependencies still exposes Boost 1.75 to link against as INTERFACE/PUBLIC.

### Describe the solution you'd like

I'd like to have a flag that allows me to rebuild an AUR package and all of its dependencies and - optionally, much more complicated to implement - only those that had a dependency updated.

Case A:
-----------

```
$ yay --rebuild-tree ros-noetic-desktop-full
```

Case B:
-----------

```
$ yay --rebuild-tree ros-noetic-desktop-full --if-depends boost
```
or

```
$ yay --rebuild-tree --if-depends-changed ros-noetic-desktop-full
```

These are just rough ideas for the argument names.

Case A kind of equals running "yay --Runs ros-noetic-desktop-full" followed by "yay -S ros-noetic-desktop-full".

### Describe alternatives you've considered

Case A kind of equals running "yay --Runs ros-noetic-desktop-full" followed by "yay -S ros-noetic-desktop-full".

### Additional context

I have limited Go experience, but I could try to contribute if the feature sounds interesting for you.

**Comment by Morganamilo** [comment]
What are you asking for that rebuild tree does not already provide?

**Comment by Blutkoete** [comment]
I'm sorry. I screwed up reading the man page because I didn't expect to find that option below "Permanent Configuration Options".

Sorry for the noise & thank you for your work.
