### ISSUE TITLE
Change package dependency

### ISSUE THREAD

**Issue by joaonunatings** [Jguer/yay#1648]
### Affected Version
yay v11.0.2 - libalpm v13.0.1

### Describe the bug
Change package dependency for example: mssql-server 15.0.4188.2-2 needs libldap<=2.4.59
AUR has libldap24 2.4.59-1. I want to change mssql-server dependency from libldap to libldap24.
I have already set --setmenu. Everytime I try to upgrade mssql-server I get this:

### Output

```sh
 -> Could not find all required packages:
	libldap<=2.4.59 (Wanted by: mssql-server)
```

**Comment by joaonunatings** [comment]
Nevermind, I fixed using `yay -G mssql-server` edited _mssql-server/PKGBUILD_ and changed _'libldap<=2.4.59'_ to _libldap24_.
Then `make -si`.

**Comment by Morganamilo** [comment]
If libldap24 has a provide for libldap you wouldn't even need to edit the dep.

**Comment by joaonunatings** [comment]
@Morganamilo  true, that's also a solution, unfortunately _libldap24_ PKGBUILD doesn't have a _provides_ field.

Get _libldap24_ PKGBUILD and add:
`provides=('libldap=2.4.59')`
