### ISSUE TITLE
yay interferes with sudo password prompt

### ISSUE THREAD

**Issue by IamCarbonMan** [Jguer/yay#165]
When installing AUR packages, yay's output and y/n prompts don't wait for sudo to finish, and the two overrun each other. Here's what I mean: https://asciinema.org/a/SCqiNqjNsbo8oqARE0wZsCD2D

**Comment by Morganamilo** [comment]
This should be fixed. You running the latest version?

**Comment by Morganamilo** [comment]
Actually my bad I don't think it's released yet. Feel free to try the -git version. New release should be out very soon.

**Comment by IamCarbonMan** [comment]
I am using the git version, and yay -Syu returns nothing to do.

**Comment by Morganamilo** [comment]
Actually after double checking it is in the regular release not just the -git.

Try `yay -Suy --devel`

**Comment by IamCarbonMan** [comment]
That did make AUR upgrades work, but yay-git was not one of them.

**Comment by Morganamilo** [comment]
Strange, could be #88 or maybe something else. `yay -S yay-git` will force and update.

**Comment by Morganamilo** [comment]
Assuming that fixed it for you, reopen if it's still a problem.
