### ISSUE TITLE
How to make yay generate autocompletion cache 

### ISSUE THREAD

**Issue by xuestrange** [Jguer/yay#1658]
### Affected Version
yay v11.0.2 - libalpm v13.0.1
### Describe the bug
I deleted the yay cache directory `/home/user/.cache/yay/`, then yay autocompletion can't work.
Is there any way to generate or download yay autocompletion cache mannually? like a line of command.

### Reproduction Steps

1. delete directory `/home/user/.cache/yay/`

### Output

``` bash
{
	"aururl": "https://aur.tuna.tsinghua.edu.cn",
	"buildDir": "/home/xue/.cache/yay",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false
}

```

**Comment by Jguer** [comment]
Normally yay will download it the first time you want to complete again, can you force a refresh with `yay -Pcc` and see if this works?

**Comment by xuestrange** [comment]
> Normally yay will download it the first time you want to complete again, can you force a refresh with `yay -Pcc` and see if this works?

Works! :smile:
