### ISSUE TITLE
[RFC] Use time based method to check devel packages

### ISSUE THREAD

**Issue by Morganamilo** [Jguer/yay#166]
Instead of storing the latest commit we would instead use the build time of the package and check it against the time of the latest commit. The build time is stored inside the pacman package so no need for a yay_vcs file.

I could see this failing if a new commit is pushed during build.
1. Start build
2. New commit
3. Build finishes, build date is marked as now but a new commit came out before build date

Although if that happens you're either really unlucky or the repo is being updated so often a new commit will come in soon and trigger an update.

So it's not full proof but it does remove the need for a cache file and --gendb and would be an easy fix for #88 although it shouldn't be too hard to fix without migrating away from this feature.

We could also go the pacaur route and unconditional update every package ended in -git|-hg|-nightly and so on. If we keep the other devel method it might be worth adding this too as `--forcedevel` or something.

**Comment by Jguer** [comment]
I like that idea, hadn't thought about it but it's very intelligent. 
I don't like the idea of unconditional update of every package, but the time based seems like a good option and the issue present is a minor thing.

**Comment by Morganamilo** [comment]
Hopefully we can skip the github api and get the time of the latest commit directly via git which would open this up to supporting more pkgs. Still non git pkgs would still never update.

With the `--forcedevel` it wouldn't be too bad seems as it would only target pkgs with specific suffixes. Better still we can choose not to update the package after we run `pkgver()` and see if it's newer than the installed variant.

**Comment by Morganamilo** [comment]
Looking around if we kept the hash method we can drop the github api and use git directly.

```
git ls-remote https://github.com/Jguer/yay HEAD
```
Will get the latest commit from the default branch.

```
git ls-remote https://github.com/Jguer/yay <branch>
```
Will do the same for whatever branch you choose.

Sadly I don't think it's possible to get the time of the hash.

**Comment by hcorion** [comment]
:+1: I would appreciate a forcedevel option, as some of my -git packages still don't update when they do have updates (rpcs3-git, dolphin-emu-git)

**Comment by Morganamilo** [comment]
I'm still thinking about how exactly we could do it. Pacaur just matched packages ending in `git/hg/nightly` and so on. A more full-proof way is to download all installed AUR packages, run the `pkgver()` function to check if there's an update but that would take a while.

PS if you're running the latest `yay-git`  then ``yay -S `yay -Qqs -- -git` `` Should update all `-git` packages.

**Comment by notramo** [comment]
What about using the `--timedevel` option for this? It is more descriptive than `--forcedevel`
Also, I think the `git ls-remote` solution is good, and it should be implemented with `--commitdevel` (or similar).

**Comment by Morganamilo** [comment]
The idea behind `--forcedevel` was to check every single `-git -hg -nightly` for updated regardless of time. `--timedevel` would be a totally separate option. I don't think there's much point implementing both the ls-remote and the time based method. One should work well enough. Having multiple might just lead to confusion.

**Comment by Jguer** [comment]
Agree on not adding more than one method. There's precedent on
```
--timeupdate         Check package's modification date and version
--notimeupdate       Check only package version change
```

but for now we shouldn't make the VCS base more complex since it will only create more issues in the issue tracker
