### ISSUE TITLE
Implementing yay as a protocol

### ISSUE THREAD

**Issue by Suleman-Elahi** [Jguer/yay#1660]
### Is your feature request related to a problem? Please describe.

Right now, one should stay/open the terminal to give the installation command manually. It could be changed by implementing yay as a protocol that will receive package name/version and will install it. Just like magnet links.

### Describe the solution you'd like

 It would be nice to have a `yay:` protocol. Later some browser extension can be created that will add an "Install" button on AUR pages of packages. Using the install button anyone would be able to install packages in a click. Just like Chrome extensions or torrent/magnet links.

### Describe alternatives you've considered

Right now, no solution exists for this. This functionality however exists for Suse, where you can click on the Install button on Suse packages repo website to install them.

### Additional context

Actually, it came to me as an idea while working on Python daemons. I wish there would be an install button on AUR package page. So, I was thinking of creating a daemon that will install a package after receiving the install instructions from the AUR website (through the "Install Now" button that will be added to it using a Chrome/Firefox extension). But then I though having a continuously running daemon on system might be an overkill. So thought of suggesting it as a built-in feature for yay.

![image](https://user-images.githubusercontent.com/24384996/147470674-2665afdd-2818-4a54-8f08-4dc6315a6b8f.png)

Thanks

**Comment by perdakovich** [comment]
@Suleman-Elahi 

this could be solved as well by a more broader `term://` protocol, that would allow the browser to pass any command, including `yay -S package`, directly to the user's preferred terminal emulator. 
in fact, it  already exists and works like a charm: https://github.com/evgvs/terminal-url-handler
