### ISSUE TITLE
--editmenu option keeps you from starting the installation, it will say that the user aborted it

### ISSUE THREAD

**Issue by 41zu** [Jguer/yay#1667]
### Affected Version

yay --version -> yay v11.1.0 - libalpm v13.0.1

### Describe the bug

--editmenu option keeps you from starting the installation, it will say that the user aborted it

### Reproduction Steps

1. yay -S linux-amd --editmenu --sudoloop
2. Confirm cleaning build dir
3. Show no diffs
4. Confirm editing all PKGBUILDs
5. Confirm to continue the installation
6. Confirm dialog says the user aborted it

### Expected behavior

with the previous version it continued the installation

### Output

:: Prüfe auf mögliche Konflikte...
:: Prüfe auf mögliche interne Konflikte...
[Repo Make:3]  xmlto-0.0.28-4  docbook-xml-4.5-9  docbook-xsl-1.79.2-7
[Aur:1]  linux-amd-5.15.v.13-1

==> Abhängigkeiten nach der Installation entfernen? [J/N] J
  1 linux-amd                       (Installiert)(Build-Dateien sind vorhanden)
==> Pakete für neuen Build?
==> [N] Keine [A]lle [Ab]brechen [I]nstalliert [No]nicht installiert oder (1 2 3, 1-3, ^4)
==> A
:: Lösche (1/1): /home/dominik/.cache/yay/linux-amd
:: (1/1) PKGBUILD heruntergeladen: linux-amd
  1 linux-amd                       (Installiert)(Build-Dateien sind vorhanden)
==> Diffs zeigen?
==> [N] Keine [A]lle [Ab]brechen [I]nstalliert [No]nicht installiert oder (1 2 3, 1-3, ^4)
==> N
:: (1/1) SRCINFO geparst: linux-amd
  1 linux-amd                       (Installiert)(Build-Dateien sind vorhanden)
==> Welche PKGBUILDs editieren?
==> [N] Keine [A]lle [Ab]brechen [I]nstalliert [No]nicht installiert oder (1 2 3, 1-3, ^4)
==> A

==> Mit der Installation fortfahren? [J/N] J
 -> Abbruch durch den Benutzer

My config output with yay -Pg:
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/dominik/.cache/yay",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"requestsplitn": 150,
	"completionrefreshtime": 7,
	"bottomup": true,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false,
	"singlelineresults": false
}

**Comment by 41zu** [comment]
btw confirming with Y does not help either

**Comment by bitwave** [comment]
have the same problem with normal `yay` call to upgrade/update system and a german locale. `J` and `Y` does not work as intended.

**Comment by Hetti** [comment]
Can confirm!
Current workaround: press "Enter" at the dialog and it will continue/install the package.

**Comment by Rosentti** [comment]
Is the EDITOR environment variable defined to a valid editor like nano or vim?

**Comment by Jguer** [comment]
> ==> Mit der Installation fortfahren? [J/N] J 

I'm pretty sure it's because this menu is expecting y/n and with localisation it was translated (as it should be) to j/n. 

This is probably a bug on treating the received input to take into account the locale

**Comment by 41zu** [comment]
> Is the EDITOR environment variable defined to a valid editor like nano or vim?

Yes. 

>>> echo $EDITOR

/usr/bin/nano

**Comment by 41zu** [comment]
> > ==> Mit der Installation fortfahren? [J/N] J
> 
> I'm pretty sure it's because this menu is expecting y/n and with localisation it was translated (as it should be) to j/n.
> 
> This is probably a bug on treating the received input to take into account the locale

I tried it with the new yay version "yay v11.1.1 - libalpm v13.0.1" and there is no change in behavior. 

Here is the output tried with confirming it with Y, but tried J too.

>>> yay -S linux-amd --editmenu

:: Prüfe auf mögliche Konflikte...
:: Prüfe auf mögliche interne Konflikte...
[Repo Make:1]  xmlto-0.0.28-4
[Aur:1]  linux-amd-5.16.v.7-1

==> Abhängigkeiten nach der Installation entfernen? [J/N] J
  1 linux-amd                       (Build-Dateien sind vorhanden)
==> Pakete für neuen Build?
==> [N] Keine [A]lle [Ab]brechen [I]nstalliert [No]nicht installiert oder (1 2 3, 1-3, ^4)
==> A
:: Lösche (1/1): /home/dominik/.cache/yay/linux-amd
:: (1/1) PKGBUILD heruntergeladen: linux-amd
  1 linux-amd                       (Build-Dateien sind vorhanden)
==> Diffs zeigen?
==> [N] Keine [A]lle [Ab]brechen [I]nstalliert [No]nicht installiert oder (1 2 3, 1-3, ^4)
==> N
:: (1/1) SRCINFO geparst: linux-amd
  1 linux-amd                       (Build-Dateien sind vorhanden)
==> Welche PKGBUILDs editieren?
==> [N] Keine [A]lle [Ab]brechen [I]nstalliert [No]nicht installiert oder (1 2 3, 1-3, ^4)
==> A

==> Mit der Installation fortfahren? [J/N] Y
 -> Abbruch durch den Benutzer

**Comment by DrKittens** [comment]
@41zu can you run

`yay -G --save --editor nano` as your config dump from yay shows no editor defined.

Would be interesting to learn if explicitly populating it remediates the issue

**Comment by 41zu** [comment]
@DrKittens Sorry for the long wait. 

I have now set the editor setting as you told me. 
yay -Pg:
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/dominik/.cache/yay",
	"editor": "nano",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"requestsplitn": 150,
	"completionrefreshtime": 7,
	"bottomup": true,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false,
	"singlelineresults": false,
	"version": "11.1.2"
}

Sadly no change in behaviour :(

**Comment by Aeysol** [comment]
The problem is the german localization. Someone translated the lowercase *no* and *yes* to *Nein* and *Ja* with the first letter in uppercase. yay [takes the first letter of the translation](https://github.com/Jguer/yay/blob/next/pkg/text/text.go#L61=) and converts it to uppercase when it is the default option. Because both options are then in uppercase, the response of the user - which is converted to lowercase before evaluation - never matches and therefore pressing enter is the only option left that succeeds.
