### ISSUE TITLE
yay -Syu --devel stuck at Checking development packages

### ISSUE THREAD

**Issue by mindrunner** [Jguer/yay#1668]
### Affected Version

`yay v11.1.0 - libalpm v13.0.1`

### Describe the bug

Running `yay` with `--devel` parameter results in an endless wait for  `Checking development packages...`

### Reproduction Steps

1. Run yay -Syu --devel
2. Grab a coffee
3. Grab another one

### Expected behavior

Yay updates devel packages

### Output

```sh
[le@p5750]: ~/temp>$ yay -Syu --devel 
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
:: Checking development packages...

```

**Comment by agorgl** [comment]
Stumbled into this too, same version

**Comment by Morganamilo** [comment]
https://github.com/Morganamilo/paru/issues/464

**Comment by mindrunner** [comment]
Not sure if that is related. For me it was `stupid me`. Local issue, since `4` other boxes did upgrade fine.

Clearing `~/.cache/yay/` did the trick
