### ISSUE TITLE
Development package version check fails for packages with source = 'git://github.com/...' 

### ISSUE THREAD

**Issue by bimmlerd** [Jguer/yay#1669]
### Affected Version

`yay v11.1.0 - libalpm v13.0.1`

### Describe the bug

Due to github.com no longer accepting the unauthenticated git protocol ([link](https://github.blog/2021-09-01-improving-git-protocol-security-github/)), the version check for development packages fails for packages which have a `source` of the form `git://github.com/...`. 

` -> devel check for package failed: '/usr/bin/git ls-remote git://github.com/sddm/sddm.git develop' encountered an error`

### Reproduction Steps

1. `yay -Syu --devel`

### Expected behavior

development package check succeeds

### Output

```sh
[config (master *)]$ yay -Syu --devel
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 sublime-text is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
:: Checking development packages...
 -> devel check for package failed: '/usr/bin/git ls-remote git://github.com/agl/jbig2enc.git HEAD' encountered an error
 -> devel check for package failed: '/usr/bin/git ls-remote git://github.com/brenns10/homework.git HEAD' encountered an error
 -> devel check for package failed: '/usr/bin/git ls-remote git://github.com/sddm/sddm.git develop' encountered an error
```

Manually:
```sh
[config (master *)]$ /usr/bin/git ls-remote git://github.com/agl/jbig2enc.git HEAD
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

**Comment by bimmlerd** [comment]
After a bit of investigation: This is probably not really a bug in yay, since the URL comes from the PKGBUILD. 

However, it might be nice if yay was smart enough to not attempt checking the version via the unauthenticated git protocol, since it does parse the URL properly already anyway ([here](https://github.com/Jguer/yay/blob/next/pkg/vcs/vcs.go#L135), I believe, via [vcs.go](https://github.com/Jguer/yay/blob/next/pkg/vcs/vcs.go#L92)). It also seems to prefer this protocol? Not entirely sure about that.

**Comment by chrisjbillington** [comment]
makepkg can't deal with such PKGBUILDs now, so presumably the PKGBUILDs will have to change to `git+https` or whatnot. Potentially nothing needs to be done in `yay` since these PKGBUILDs are unusable until they are fixed no matter what yay does.

```
$ makepkg
==> Making package: pixelscale-git 4.3835e97-3 (Tue 11 Jan 2022 22:32:39)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found hqx.sh
  -> Found xbr.sh
  -> Cloning libxbr-standalone git repo...
Cloning into bare repository '/home/bilbo/.cache/yay/pixelscale-git/libxbr-standalone'...
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
==> ERROR: Failure while downloading libxbr-standalone git repo
    Aborting...
```

**Comment by bimmlerd** [comment]
> makepkg can't deal with such PKGBUILDs now, so presumably the PKGBUILDs will have to change to git+https or whatnot. 

Fair point, closing.

**Comment by Porkepix** [comment]
Got one package here where `vcs.json` never was updated, despite the `PKGBUILD` that updated, I had to manually edit/regenerate the `vcs` file, is that intended behavior or should it have been updated automatically?

See last two commits here: https://aur.archlinux.org/cgit/aur.git/log/?h=airgeddon-git
