### ISSUE TITLE
-Ss option with two word argument fails with `no query was executed`

### ISSUE THREAD

**Issue by burjui** [Jguer/yay#1674]
yay v11.1.0.r4.g09695c6 - libalpm v13.0.1:
```sh
$ yay -Ss cargo watch
 -> no query was executed
```
```sh
$ pacman -Ss cargo watch
community/cargo-watch 8.1.2-1
    Utility for Cargo to compile projects when sources change
```

**Comment by djvs** [comment]
I thought I was going nuts.  And it works sometimes too.

**Comment by OracleToes** [comment]
so this isn't just me.. A bunch of other stuff got messed up with my computer today and I thought it was related, thanks.

**Comment by trumoose** [comment]
> so this isn't just me.. A bunch of other stuff got messed up with my computer today and I thought it was related, thanks.

see #1684
