### ISSUE TITLE
Yay fails to add PGP keys

### ISSUE THREAD

**Issue by fyrak1s** [Jguer/yay#1678]
### Affected Version
yay v11.1.0 - libalpm v13.0.1

### Describe the bug

Now I have noticed this not the first time. Sometimes yay just fails to import the PGP keys after confirming to do so.
Now I have proof of this with the `ranger-sixel`package.
Yay just wouldn't let me install the package and ask me every time to import the pgp keys.
I then installed `paru`, which also asked me to import those keys, which worked flawlessly and the package installed.

Now using yay again to reinstall the package is not problem. So yay had just failed at the import step.

### Reproduction Steps

1. `yay -S ranger-sixel`
2. Agree to import the keys
3. Installation aborts

### Expected behavior

Yay should correctly import the pgp keys.

**Comment by grandchild** [comment]
Can't confirm:
```
$ yay -S ranger-sixel

[...]
 
:: (1/1) Parsing SRCINFO: ranger-sixel

:: PGP keys need importing:
 -> 1E9B36EC051FF6F7FFC969A7F08CE1E200FB5CDF, required by: ranger-sixel
 -> 66FA95C0F1619BDA520A41F60D63346A5D15D055, required by: ranger-sixel
==> Import? [Y/n] 
:: Importing keys with gpg...
gpg: key 0D63346A5D15D055: 5 duplicate signatures removed
gpg: key 0D63346A5D15D055: 5 signatures reordered
gpg: key 0D63346A5D15D055: public key "toonn <toonn@toonn.io>" imported
gpg: key F08CE1E200FB5CDF: public key "hut <hut@hut.pm>" imported
gpg: Total number processed: 2
gpg:               imported: 2
```

**Comment by fyrak1s** [comment]
Oh ok that is weird. I had this issue multiple times recently (yay failing to import PGP keys)

Maybe I will report back once it happens again? Or might there be something misconfigured on my part?

**Comment by Jguer** [comment]
#1374 https://github.com/Jguer/yay/issues/1022 gpg is a bit weird and if I remember correctly some users complained about issues with the default keyserver. One of these issues might help you @Nuc1eoN

**Comment by fyrak1s** [comment]
Thank you both. I am gonna close this issue for now, but should I experience it in the future again, I will halt and come back to this issue, or create a new one.

**Comment by RobLW** [comment]
Constantly get this. Very annoying. I have my keys in there when I do gpg --list-keys. So I assume the error message just means I need to install this persons key but that always fails.

![image](https://github.com/Jguer/yay/assets/34024337/a9ca2df0-2954-4b02-8ee6-04b82b837ff7)

**Comment by Jguer** [comment]
Hey @RobLW , this is probably an issue with your gpg config.

Probably you can try creating a `~/.gnupg/dirmngr.conf` with the following:

```ini
keyserver hkps://keyserver.ubuntu.com:443
```
