### ISSUE TITLE
Why does yay often refuses to accept my sudo password?

### ISSUE THREAD

**Issue by mcurly** [Jguer/yay#1681]
As  a consequence I've uninstalled yay, because I  think of this as a major issue (a security breach?? maybe!). But @Jguer do look into it, because maybe others suffer from this as well.

Sorry I couldn't be more specific...

**Comment by mcurly** [comment]
Hello again @Jguer , I've migrated to `paru` and I had no such issues with it.

But the issue must be already reported somewhere else, because, `sudo` was just updated on my up-to-date archlinux system. Perhaps the problem wasn't fully related to `yay`, but it interconnected with it and did _manifest_ in `sudo` not taking my password,

Either way I don't have the skills (yet) to debug it.

And yes, **I'll close** this issue.

_Needless to say_ ... (_unfortunately_) I am not using `yay` in the near future... Sorry...

**Comment by Morganamilo** [comment]
I very much doubt it's a yay issue. Pam is a bit overly strict and will lock you out for a bit with I think 3 wrong passwords.

**Comment by mcurly** [comment]
@Morganamilo , maybe I should've stressed out that I was fully paying attention to password typing. Yes I am certain that there was something wrong with that process, either with the requesting application `yay`, or with the authentication infrastructure...


I positively say that I was fully paying attention to the authentication process because this "_let's call it surprising behavior_" had already occurred to me before, I mean, then I was more relaxed and didn't make much of it, since I know as well that it could have been caused by my wrong typing, then...

But this time I can assure you that it wasn't, because I've even `su` 'ed and confirmed (retyped my user password with command: `passwd <my_user_name>`)...

And, then stubborn as I am, I tried the same `yay` command, with the same exact outcome... Failed authentication...

Lastly, did you, @Morganamilo try to further investigate this or is it just an opinion of yours?

Either way, thank you for your input.


Regards.

**Comment by Morganamilo** [comment]
passwd will change your password but it won't unlock the account. The behaviour sucks imo but that's just how it is out of the box. I can't confirm it's your issue but it's often people's issue.

**Comment by mcurly** [comment]
@Morganamilo authentication infrastructure is what it is... (As with everything)...

And, (with my _stubbornness..._, forgive me for being _blunt_), I didn't unlock my account, nor did I wait for the default lock period to timeout. I moved forward with `git` cloning `paru`, and then `makepkg -si` inside the cloned directory. There, when `makepkg` prompted for the password, authentication failed again. Then I made use of the `su` to be able to use `pacman -U` to install `paru` package, which, succeeded, of course.

So maybe yay isn't the culprit at all.

I'll just have to wait a little longer and see if this kind of odd thing happens elsewhere.

Meanwhile, my stubbornness will stick with `paru` and lookout for similar events.

Sorry if this seemed to much...

Regards

**Comment by kaiyazeera** [comment]
Sometimes, I run into this problem, too, like today. It's very irritating when this happens but I am not sure what is happening there.

**Comment by kaiyazeera** [comment]
https://serverfault.com/questions/424775/sudo-rejects-password-that-is-correct/1039192#1039192

Actually, this was the problem in my case, so it really is an upstream issue. LukeLR's answer worked for me.

**Comment by xuzh0u** [comment]
``

> https://serverfault.com/questions/424775/sudo-rejects-password-that-is-correct/1039192#1039192
> 
> Actually, this was the problem in my case, so it really is an upstream issue. LukeLR's answer worked for me.

Thanks a lot! It also works for me (manjaro).
