### ISSUE TITLE
Unable to query aur

### ISSUE THREAD

**Issue by tianmeng-xiu** [Jguer/yay#1687]
Unable to query aur
-> response decoding failed: invalid character '<' looking for beginning of value

**Comment by xaotag** [comment]
see #1684

**Comment by Jguer** [comment]
Closing this issue as fixed on `yay-git` and on imminent release after some fast QA.  

https://github.com/Jguer/yay/pull/1685#issuecomment-1030619756

Fixed by https://github.com/Jguer/yay/pull/1685
