### ISSUE TITLE
Response decoding failed: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by onurbbr** [Jguer/yay#1688]
### Affected Version

yay v11.1.0 - libalpm v13.0.1

### Error output

[onur@archlinux ~]$ yay -Syyu --devel --timeupdate
:: Synchronizing package databases...
 core                                                                                                              138.1 KiB   133 KiB/s 00:01 [#######################################################################################] 100%
 extra                                                                                                            1555.2 KiB   605 KiB/s 00:03 [#######################################################################################] 100%
 community                                                                                                           6.1 MiB   764 KiB/s 00:08 [#######################################################################################] 100%
 multilib                                                                                                          149.1 KiB   143 KiB/s 00:01 [#######################################################################################] 100%
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
 -> response decoding failed: invalid character '<' looking for beginning of value
response decoding failed: invalid character '<' looking for beginning of value

### Describe the bug

This error pops up at the start of AUR update

### Reproduction Steps

1. run 'yay -Syyu --devel --timeupdate'
2. Wait until try to update aur packages
3. See error.

### Expected behavior

Making the update seamless.

### Output

{
        "aururl": "https://aur.archlinux.org",
        "buildDir": "/home/onur/.cache/yay",
        "editor": "",
        "editorflags": "",
        "makepkgbin": "makepkg",
        "makepkgconf": "",
        "pacmanbin": "pacman",
        "pacmanconf": "/etc/pacman.conf",
        "redownload": "no",
        "rebuild": "no",
        "answerclean": "",
        "answerdiff": "",
        "answeredit": "",
        "answerupgrade": "",
        "gitbin": "git",
        "gpgbin": "gpg",
        "gpgflags": "",
        "mflags": "",
        "sortby": "votes",
        "searchby": "name-desc",
        "gitflags": "",
        "removemake": "ask",
        "sudobin": "sudo",
        "sudoflags": "",
        "requestsplitn": 150,
        "completionrefreshtime": 7,
        "bottomup": true,
        "sudoloop": false,
        "timeupdate": false,
        "devel": false,
        "cleanAfter": false,
        "provides": true,
        "pgpfetch": true,
        "upgrademenu": true,
        "cleanmenu": true,
        "diffmenu": true,
        "editmenu": false,
        "combinedupgrade": false,
        "useask": false,
        "batchinstall": false,
        "singlelineresults": false
}

**Comment by ZeroDot1** [comment]
I have exactly the same problem.

**Comment by craigbarnes** [comment]
This is a duplicate of #1682.

**Comment by ethan-halsall** [comment]
The aur API was down, should be working now, I think...

**Comment by ZeroDot1** [comment]
> The aur API was down, should be working now, I think...

Yes, it works again, I think this can be closed.

Thank you very much for your work.

**Comment by ddbb07** [comment]
This was solved in #1685

**Comment by ddbb07** [comment]
And the api wasn't down, there was an update to the api which removed the endpoint that yay was using, the guys maintaining the AUR api implemented a temporary fix which will be removed in a month, this will give time so yay users will be able to update.

**Comment by onurbbr** [comment]
Then I'll close. Thank you guys.
