### ISSUE TITLE
response decoding failed: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by Dhongli** [Jguer/yay#1700]
I have updated yay to the latest, but the error in the title still appears

![图片](https://user-images.githubusercontent.com/37902035/152685928-7949c640-20fa-4de7-b555-feb9080e4bba.png)
and looked at the yay binary, there is no 'php' in it

**Comment by Dhongli** [comment]
![图片](https://user-images.githubusercontent.com/37902035/152686305-60408720-5970-442d-94e5-894cc8440932.png)

**Comment by Jguer** [comment]
Hey @Dhongli , can you post the output of `yay -Pg`, I feel it might be related to your `aururl` setting

**Comment by Dhongli** [comment]
@Jguer 

Thanks,It's working. When I replace aururl with this:
"aururl": "https://aur.archlinux.org", 
![图片](https://user-images.githubusercontent.com/37902035/152707151-45ceaa86-74cf-4432-a62a-c00da7bfa9a2.png)
