### ISSUE TITLE
Error clearing package cache in ~/.cache/yay/ if localization is not English

### ISSUE THREAD

**Issue by DeadNumbers** [Jguer/yay#1702]
### Affected Version
`yay v11.1.1 - libalpm v13.0.1`

### Describe the bug
The cache is not cleared if the system locale is not latin.

<details>
<summary>Spoiler</summary>

```bash
 .cache/yay » pwd
/home/user/.cache/yay
 .cache/yay » ls
completion.cache  vcs.json  yay-git
 .cache/yay » yay -Scc

Каталог для кэша: /var/cache/pacman/pkg/
:: Удалить ВСЕ файлы из кэша? [y/N] y
удаление всех файлов из кэша... 

Каталог базы данных: /var/lib/pacman/
:: Удалить неиспользуемые репозитории? [Y/n] y
удаление неиспользуемых репозиториев...

Каталог сборки: /home/user/.cache/yay
==> Вы хотите удалить все пакеты AUR из кэша? [Д/н] y
 .cache/yay » ls
completion.cache  vcs.json  yay-git
 .cache/yay » LANG=en_US.UTF-8 yay -Scc         

Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove ALL files from cache? [y/N] y
removing all files from cache...

Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n] y
removing unused sync repositories...

Build directory: /home/user/.cache/yay
==> Do you want to remove ALL AUR packages from cache? [Y/n] y
removing AUR packages from cache...
 .cache/yay » ls
completion.cache  vcs.json
 .cache/yay » yay -V                   
yay v11.1.1 - libalpm v13.0.1
 .cache/yay » 
```
</details>

### Reproduction Steps
1) Download any PKGBUILD's to ~/.cache/yay/
2) try clean cache with russian locale `LANG=ru_RU.UTF-8 yay -Scc`

**Comment by avently** [comment]
Hello, @Jguer. I wanted to create similar issue but this one is almost the same as needed. The problem here as you can see is `yay` use russian characters `[Д/н]` instead of `[Y/n]` in some places. So basically yay expects the user to print `д` or `н` which is not good at all. 
To have localized messages == super cool.
To have localized answers Y/n == not cool since every command in terminal is written using english alphabet.

The situation happens with Proceed installation dialog too, for example, in addition to what @DeadNumbers said.
I have yay-11.2.0 installed. If it's already fixed, please, tell.

**Comment by Jguer** [comment]
What we can do for this case is have yay always accept y/Y n/N in addition to what's provided by localization. I think that might be the best way to solve it

**Comment by avently** [comment]
@Jguer what the purpose of localized [Y/n]? 

In terminal we all use english letters to call commands. Switching between languages just makes situation harder than using english to answer.
I mean it overcomplicates yay development and looks strange/weird actually for the user.
I like your idea about supporting Y/n, however this info will not be known by users. And almost all of them will keep trying to press localized answers which will make situation uncomfortable for them on a daily basis.

**Comment by Jguer** [comment]
I would prefer not to support it, but pacman supports it so it's awkward if only half of a given prompt supports it

Example:

- uncomment `de_DE.UTF-8` from `/etc/locale.gen`
- `sudo locale-gen`
- `env LANG=de_DE.UTF-8 yay -Scc`

Half of these come from the `pacman` command directly and the other half from `yay`

**Comment by Jguer** [comment]
`yay-git` should fix this issue currently

- Default to y/n if localised yes/no are not latin characters (there may be a better encoding range to verify its 'typeability'
- Always accept y/n either way

feedback is appreciated :smile:

**Comment by avently** [comment]
Yeah, works good in RU locale! At least for Proceed installation step and `Do you want to remove ALL AUR packages from cache` step. Shows y/n in this case, great.
Thank you
