### ISSUE TITLE
Possible answer characters are all in capital letters

### ISSUE THREAD

**Issue by Tmkrth** [Jguer/yay#1708]
Hello!

Since yay 11.1.0 one cannot visibly distinguish between default option and other option in questions anymore, yay prints all characters in capitals, for example "Y/N". 

It works like before, but should look like "Y/n" or "y/N" again.

Regards,

**Comment by Jguer** [comment]
Hey @Tmkrth are you using a locale different than en_US?

**Comment by Tmkrth** [comment]
Yes, indeed, de_DE.UTF-8 is used. Didn't think to test with English.

Starting yay with LANG=C does show "Y/n" correctly.

Do I need to do something to have it like that in my locale, too?

**Comment by Jguer** [comment]
Hey @Tmkrth , this should be fixed in `yay-git` and yay `v11.3.0`. Feel free to ping if it's not the case
