### ISSUE TITLE
Install package error

### ISSUE THREAD

**Issue by jiangtao69039** [Jguer/yay#1711]
i want to install idesk and use command:
 yay -S idesk

then get a error message: 
 -> response decoding failed: invalid character '<' looking for beginning of value

**Comment by tianheg** [comment]
did you upgrade yay to latest version

the latest version fix it https://github.com/Jguer/yay/releases/tag/v11.1.1

**Comment by jiangtao69039** [comment]
how should i install from this release?  i pre installed by "sudo pacman -S yay"

**Comment by tianheg** [comment]
which version do you use about yay, is it v11.1.1?

**Comment by tianheg** [comment]
if not, you can run `yay -S yay` to upgrade

**Comment by jiangtao69039** [comment]
![Screenshot_2022-02-14-01-34-36_2240x1400](https://user-images.githubusercontent.com/20572131/153767301-2ad954fe-fc73-4f43-b6e4-835688327c28.png)

**Comment by tianheg** [comment]
#1682 here is others met same question like you, it has been solved

**Comment by tianheg** [comment]
you already have the latest version of yay, do you mind run a system upgrade like `yay -Syu` to test work or not?

**Comment by jiangtao69039** [comment]
i change aururl is resolved.

**Comment by jiangtao69039** [comment]
its seem like a problem of chinese mirrors

**Comment by leyafo** [comment]
> its seem like a problem of chinese mirrors

Hi, @jiangtao69039. 
Can you display the `aururl`? how to resolve this problem.

**Comment by jiangtao69039** [comment]
> > its seem like a problem of chinese mirrors
> 
> Hi, @jiangtao69039. Can you display the `aururl`? how to resolve this problem.

yay --aururl "https://aur.archlinux.org" --save
