### ISSUE TITLE
Don't clone entire git repository when compiling a library from git

### ISSUE THREAD

**Issue by ryuukk** [Jguer/yay#1713]
Right now it wastes time/bandwidth downloading ENTIRE git repo

This is not necessary, and should only clone what is needed

**Comment by Jguer** [comment]
Closing as duplicate https://github.com/Jguer/yay/issues/972

**Comment by ryuukk** [comment]
Why the one you mention is also closed?

**Comment by grandchild** [comment]
Because in that ticket it is explained how it's not yay that's cloning the source repo, but makepkg. So it's not a yay issue.
