### ISSUE TITLE
Allow building from offical repositories

### ISSUE THREAD

**Issue by DUOLabs333** [Jguer/yay#1714]
### Is your feature request related to a problem? Please describe.
I use Arch Linux ARM, which lags behind Arch Linux sometimes. However, their PKGBUILD is automatically updated when Arch's does. So, I would like if I could build `yay -S <package>`.

### Describe the solution you'd like
If the name of the package isn't in the AUR, look for the PKGBUILD in the main repository (maybe offer configuration options?) then build it.

**Comment by grandchild** [comment]
It's not clear to me what is needed. Do you want to (re-)build packages from the official repos yourself for ARM from the x64-Archlinux PKGBUILDs? If that is the case you should have a look at [ABS](https://wiki.archlinux.org/title/Arch_Build_System), because yay helps with building AUR packages, not official ones.

I'm not sure what the `yay` maintainers' stance is on a feature request to support ABS.

**Comment by DUOLabs333** [comment]
Technically, I want to build from ALARM's repositories, since sometimes it differs from Arch.

**Comment by antdking** [comment]
This is useful in other situations, where you want to customise build flags (e.g. `-march=native`) without the overhead of spinning up an entry in the AUR.

I'll be digging into more details in a few weeks, but this could help with automating the management of a personal repository down the road, where you want to potentially compile official dependencies against the AUR itself.
Somewhat niche, but would have been incredibly useful while we were stuck on GCC 11.1.

**Comment by grandchild** [comment]
How does ABS not do all of this?

**Comment by DUOLabs333** [comment]
@grandchild I wanted to be able to manage both repositories by the same program.

**Comment by DUOLabs333** [comment]
Keep issue open.

**Comment by Jguer** [comment]
`yay -G` + `yay -Bi` should allow you to do this behavior (+ .SRCINFO generation)

**Comment by DUOLabs333** [comment]
This pulls from Arch Linux's repositories, not ALARM's (maybe it should depend on `uname`?).
