### ISSUE TITLE
Please abort pacman subprocess when received user interrupt

### ISSUE THREAD

**Issue by asuka-mio** [Jguer/yay#1734]
### Describe the bug

My network environment isn't very well, I execute yay to upgrade and it stuck due to poor network, then i used to press Ctrl + C to interrupt this process, but pacman subprocess is still alive, then what can i do is to kill pacman process and delete db.lck or wait for pacman exit, which is really annoying.

### Reproduction Steps

1. have a poor network
2. execute yay to upgrade but it will stuck due to network
3. press Ctrl + c to abort and pacman is still alive

### Expected behavior

When i press Ctrl C, yay and pacman both exit just like when i execute sudo pacman -Syu and press Ctrl + C to abort

### Output

```sh

```

**Comment by Jguer** [comment]
There may be an issue in signal propagation (there were some hacks around it already), to research
