### ISSUE TITLE
Incorrect output downloading 2 or more packages from AUR

### ISSUE THREAD

**Issue by Vochomaster** [Jguer/yay#1741]
### Affected Version

yay v11.1.2 - libalpm v13.0.1

### Describe the bug

Updating 2 packages from AUR there are 2 information headers when download starts and subsequent output is not in the expected format

### Reproduction Steps

1. Ensure there is more than 1 package to update by executing `yay -Qua`
2. If output from last command shows 2 or more packages, execute `yay`

### Expected behavior

Output just one information header and keep statistics on their corresponding lines

### Output

![image](https://user-images.githubusercontent.com/57856657/161840585-a038576d-3fe0-468c-8a3c-650d8bac778c.png)

System specs:
 * Operative system: EndeavourOS
 * Kernel: 5.17.1-arch1-1
 * Desktop: Cinnamon 5.2.7
 * Terminal: gnome-terminal 3.42.2-2

**Comment by killajoe** [comment]
same with using xfce4-terminal i will go to test others too but seems to be some "newline" issue on yay itself?

It can be reproduced also by building two AUR builds at the same time if they are both will download source tarballs ;) 

But it is reported already here:

#https://github.com/Jguer/yay/issues/1640

and here:

#https://github.com/Jguer/yay/issues/1620
