### ISSUE TITLE
yay -Fl does not work with AUR packages

### ISSUE THREAD

**Issue by ajgringo619** [Jguer/yay#1743]
`yay -Fl package_name` works as designed when querying non-AUR packages, but fails when querying non-AUR packages:
```
$ yay -Fl vmware-workstation
error: package 'vmware-workstation' was not found
 -> exit status 1
```
Is this by design?

**Comment by Morganamilo** [comment]
AUR packages are pkgbuilds and therefore do not have files.

**Comment by ajgringo619** [comment]
OK, thanks.
