### ISSUE TITLE
Build all AUR packages before single pacman -U execution

### ISSUE THREAD

**Issue by cmonty14** [Jguer/yay#1769]
Hello,
this is a feature request for yay that I'm using successfully in Arch Linux.

My system is configured with BTRFS as root filesystem, and I'm using its snapshot feature when pacman is executed.
This function is based on [snapper](https://wiki.archlinux.org/title/snapper), and I have deployed "Wrapping pacman transactions in snapshots": [snap-pac](https://archlinux.org/packages/?name=snap-pac), [snap-pac-grub](https://aur.archlinux.org/packages/snap-pac-grub/)

Grub is updated accordingly and includes these snapshots; this function is provided by package [grub-btrfs](https://archlinux.org/packages/community/any/grub-btrfs/).

The downside of this setup using yay (or any other AUR helper) is that for every single AUR package a new snapshot will be generated whereas a package upgrade with `pacman -Suy` will generate only a single snapshot, means pacman upgrades all packages in a single execution.

**Feature request:**
yay is not not installing any single AUR package after build, but all packages are build first and then a single `pacman -U` command is executed instead.

THX

**Comment by Morganamilo** [comment]
--batchinstall

**Comment by cmonty14** [comment]
> --batchinstall

Thanks for providing this solution.
