### ISSUE TITLE
how can i add commands to compilation?

### ISSUE THREAD

**Issue by makuru-org** [Jguer/yay#1771]
Im using a laptop and for power reasons my default cpu governor is power save but i want it to switch to performance when it is compiling like [gamemode](https://github.com/FeralInteractive/gamemode) can do for games like this "gamemoderun example.sh", how can i configure something similar with yay?

**Comment by grandchild** [comment]
And does `gamemode` not work?

**Comment by Jguer** [comment]
Closing due to low engagement
