### ISSUE TITLE
Option to disable fetching AUR news

### ISSUE THREAD

**Issue by xxxserxxx** [Jguer/yay#1772]
### Is your feature request related to a problem? Please describe.

I use a VPN. Frequently, yay fails to install packages from AUR because of the pre-install step `Fetching news`, as AUR returns a "too many requests" error. This makes upgrading packages either a) impossible, b) forces me to disable my VPN simply to install packages, c) most often results in me having to manually install each AUR update, one after the other, sometimes multiple times for each package.

### Describe the solution you'd like

I'd like a switch to disable the step that checks for news.

**Comment by Morganamilo** [comment]
That doesn't really relate. The news stuff doesn't even connect to the aur. What's likely happened is you made too many requests and got your IP with the VPN on banned.

**Comment by xxxserxxx** [comment]
I'm not sure what's responsible for news; I asked in an Arch forum and they said it was something related to AUR, and was coming from the helper (in my case, yay).

Yes, it's related to the VPN; like almost every non-private VPN, I share an exit node with many other people; however, the step that *always* fails is the pre-install "Fetching news" step that happens with every AUR package. It doesn't always happen, but whenever I get a failure due to "too many requests," it's always after everything is downloaded and compiled and just before installation:

```
:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                        [----------------------------] 100%
(1/1) checking package integrity                      [----------------------------] 100%
(1/1) loading package files                           [----------------------------] 100%
(1/1) checking for file conflicts                     [----------------------------] 100%
(1/1) checking available disk space                   [----------------------------] 100%
:: Running pre-transaction hooks...
(1/1) Checking for unread news posts...
No news is good news.
```

This time didn't fail, but it's this near-to-last **Running pre-transaction hooks** step. I'd like to be able to skip this. 

Is this *not* something yay is doing? I see nothing in the `PKGBUILD`s that explicitly run this command, and it appears it's run for every -- and only for -- AUR packages.

**Comment by Morganamilo** [comment]
You've installed some news pacman hook. This is not something yay is doing.

**Comment by Jguer** [comment]
Feature request for news is here https://github.com/Jguer/yay/issues/1751 , as @Morganamilo said yay doesn't do this, you might want to check your `/usr/share/libalpm/hooks/`

**Comment by xxxserxxx** [comment]
Newsie puts hooks in there. Which, I believe, I installed because at some point my system was refusing to upgrade anything until I read the news.

Thank you.
