### ISSUE TITLE
Feature request: measure build time for informing the user next time

### ISSUE THREAD

**Issue by drws** [Jguer/yay#1778]
### Describe the solution you'd like

It would be great to have an indication of when the current build started and how much time it took the last time this package was built. I'm not sure about the practical UI implementation, maybe a line could be printed if a certain control sequence is sent.

### Describe alternatives you've considered

Many of us are probably doing at least a part of what's described manually. I'm putting the idea here in case some developer finds it useful to have.

**Comment by drws** [comment]
Stale bot, please go away.

**Comment by Jguer** [comment]
Closing due to low engagement. 

Thanks for opening a feature request
