### ISSUE TITLE
Pacman cache automatic cleaning

### ISSUE THREAD

**Issue by notramo** [Jguer/yay#178]
Similarly, hogy the Pamac package manager does it in Manjaro.
It has a config option how many previous versions of a package should it keep, and if there are more versions of the package than configured, automatically removes the oldest versions.

**Comment by Morganamilo** [comment]
I was planning to implement `-Sc` and `-Scc` Maybe this could also be added as an extension of clean after.

**Comment by usommerl** [comment]
In my opinion it is not really necessary to implement this in yay. You can already setup automatic cache cleaning with a combination of pacman hooks and paccache ([See this thread](https://bbs.archlinux.org/viewtopic.php?pid=1694743#p1694743)). I have been using such a setup for quite some time and it works with any pacman wrapper.

**Comment by Morganamilo** [comment]
Does that also clear the Yay cache though? and is is smart enough to only clean aur packages that are not installed?

**Comment by Morganamilo** [comment]
I've avoiding implementing this until I know whats happening with git clone. With git clone you could run `git clean -dfx` to easily clean downloaded sources while keeping the PKGBUILD, .SRCINFO and local sources=().

Still a PKGBUILD download isn't very big so if we nuke the directory and re-download just like how clean build currently works It wont be that bad.

We could even parse the sources in .SRCINFO and only delete downloaded files, effectively doing `git clean -dfx` 

My current plan for `-Sc` is to delete downloaded sources for all packages and (if not `-Scc`) keep x amount of the already built packages installed with `--keepcached` or something.

CleanAfter would then call -Sc but only on the packages that where affected during `-S`

**Comment by Morganamilo** [comment]
Now that there's full support for PKGDEST, I'm not going to suggest to use `paccache` instead. It's part of `pacman-contrib` and very powerful.

`yay -Sc` still works for PKGBUILD cleaning and package cleaning given you have not set PKGDEST.

**Comment by NobbZ** [comment]
Can we have a version of `-Sc` where I do not have to manually hit `nnyy`?

**Comment by Morganamilo** [comment]
In the -git version you could do `yay -Sca --noconfirm` should do it.

**Comment by NobbZ** [comment]
Thank you. Any eta when it will be in `yay` or `yay-bin`? I prefer to stick with released software.

**Comment by Jguer** [comment]
Release changelog is drafted if you want to take a look.
