### ISSUE TITLE
Library dependencies don't work - required packages are not found

### ISSUE THREAD

**Issue by GithubUser5462** [Jguer/yay#1781]
### Affected Version

yay v11.2.0 - libalpm v13.0.1

### Describe the bug

"Library dependencies" don't work.

### Reproduction Steps

1. Try to install [AUR syncthingtray](https://aur.archlinux.org/packages/syncthingtray) with `yay -S syncthingtray`

### Expected behavior

yay successfully finds the required packages and installs the software,

### Output

```sh
error: could not find all required packages:
    libqtutilities.so (wanted by: syncthingtray)
    libqtforkawesome.so (wanted by: syncthingtray)
    libc++utilities.so (wanted by: syncthingtray)
```
### P.S.
It used to work, this seems to be the breaking change ["Use library dependencies"](https://aur.archlinux.org/cgit/aur.git/commit/?h=syncthingtray&id=68f912923f8905234d59314cf6fc770345629e9d).

The workaround is to install the packages manually.
```sh
yay -S c++utilities;
yay -S qtutilities;
yay -S qtforkawesome;
yay -S syncthingtray;
```

**Comment by Jguer** [comment]
Just realized these are provided by AUR packages. Unfortunately, as far as I know, at this point in time the AUR does not support searching by provides (resulting in an awkward provides searcher that has already given some issues).

Would like to get this implemented, ideas welcome

**Comment by grandchild** [comment]
After spelunking a bit in AURweb I found that there's a stalled MR underway: https://gitlab.archlinux.org/archlinux/aurweb/-/merge_requests/483 . The author says they aren't working on it "for some time". But from the existing review it seems the missing pieces are mostly test coverage?

**Comment by grandchild** [comment]
More high-level discussion here: https://gitlab.archlinux.org/archlinux/aurweb/-/issues/307
Seems that both the author and the maintainer are otherwise occupied since a few months. :/

**Comment by AladW** [comment]
I think a new RPC version is a dead end. For an alternative approach see here: https://gitlab.archlinux.org/archlinux/aurweb/-/issues/172#note_73474

**Comment by grandchild** [comment]
> I think a new RPC version is a dead end.

@AladW, in your opinion, is that because it has no/not enough technological merit? Or because the metadata repo solution will likely be picked and implemented over releasing a new API version including the "extend search" MR?

**Comment by AladW** [comment]
Both. The current `provides` v6 proposal leads to an [excessive amount of requests](https://gitlab.archlinux.org/archlinux/aurweb/-/issues/307#note_63764); like `yay`'s heuristic, it relies on doing a `search` for each dependency. And the metadata repo solution is relatively simple to implement on the server side, unlike a new RPC version which has to last for years to come.

**Comment by AladW** [comment]
Some good news: https://gitlab.archlinux.org/archlinux/aurweb/-/issues/307#note_76090

**Comment by Jguer** [comment]
Thanks for the updates @AladW , that looks promising 

I've been playing with the local [metadata cache](https://github.com/Jguer/yay/blob/jguer/local-pkgbuild-install/pkg/metadata/metadata_aur.go). I like the scenario of having this locally cached

**Comment by AladW** [comment]
There's also some improvements for metadata archives planned, i.e. a git archive for them where changes can be retrieved incrementally (instead of retrieving the full archive after a fixed time). This reduces traffic on aurweb and can be hosted on various mirrors as well. See https://gitlab.archlinux.org/archlinux/aurweb/-/merge_requests/526

**Comment by Jguer** [comment]
I was thinking having an endpoint with the checksum of the metadata would probably also avoid retrieving the metadata archive when it has no differences to the local copy

EDIT: (haven't checked if this is already implemented)

**Comment by AladW** [comment]
Right, etag and HTTP Last Modified is available. It's pretty much guaranteed that these change every 5 minutes though (the interval that the archives are generated), and in the worst case you have 7mb of client traffic every 5 minutes. 

With `git` that reduces to a few kilobytes per fetch.

**Comment by moson-mo** [comment]
> Unfortunately, as far as I know, at this point in time the AUR does not support searching by provides (resulting in an awkward provides searcher that has already given some issues).

@Jguer `provides` search was added in the meanwhile.
There are quite some new `by` parameters available now:

```
name
name-desc
depends
checkdepends
optdepends
makedepends
maintainer
submitter
provides
conflicts
replaces
keywords
groups
comaintainers
```
maybe one or another is helpful for you 😉 

https://github.com/Jguer/aur/pull/6

**Comment by Jguer** [comment]
Thanks @moson-mo , I'll take a look at the PR in the `aur` lib and I have in my TODO to also take a look at the metadata archive as git implementation :smile:

**Comment by moson-mo** [comment]
> metadata archive as git

Those are pretty much a dead-end for AUR-Helper clients imho.
It will certainly add some complexity but if you want to go that route, make sure to shallow clone/fetch, otherwise it's killer... :wink:

**Comment by AladW** [comment]
Agreed, I tried an implementation (https://github.com/AladW/aurutils/blob/4e9685fd0f45415b220ab8b23d488a867c69e93a/lib/aur-pkglist, https://github.com/AladW/aurutils/blob/4e9685fd0f45415b220ab8b23d488a867c69e93a/lib/aur-pkglist--merge) but it was too slow vs. the tar archives and uses a lot of space client-side

> @Jguer provides search was added in the meanwhile.

Just to note this has some UI considerations as well, e.g. for packages like [yuzu](https://aur.archlinux.org/packages/yuzu). If you prompt naively for every dependency with multiple providers, it will result in a lot of added prompts for such packages.

**Comment by Jguer** [comment]
@AladW 53MB for the raw storage is not much (I can imagine the git repository being somewhat heavier), it also does not provide astounding speed improvements (it's quite effective for resolving provides though).

Closing this issue, on `yay-git`, `syncthingtray` now works with both the AUR metadata cache and the AUR RPC provides endpoint with the following config.json entry:

```json
  "newinstallengine": true,
```

(aur/yuzu is a nice test case)
![image](https://user-images.githubusercontent.com/8071073/220217777-04ada14a-238e-41d2-86ec-d8bc46c71361.png)
