### ISSUE TITLE
feature request: Handle pkgbuild from local

### ISSUE THREAD

**Issue by unknowndevQwQ** [Jguer/yay#1782]
### Is your feature request related to a problem? Please describe.

When writing a pkgbuild that is not uploaded to aur, if the pkgbuild contains dependencies from aur, you need to handle them manually

### Describe the solution you'd like

Handling local pkgbuild is not very different from aur, you may need to specify the path manually/use the pkgbuild of the working directory

### Describe alternatives you've considered

Just install dependencies that do not exist in the repository

**Comment by grandchild** [comment]
I think `makepkg` already does what you want:

```shell
makepkg PACMAN=yay -s
```

**Comment by grandchild** [comment]
Closing due to lack of feedback
