### ISSUE TITLE
Improve wording of some AUR package status messages

### ISSUE THREAD

**Issue by fiechr** [Jguer/yay#1783]
### Is your feature request related to a problem? Please describe.

`Missing AUR packages: ...` may lead to the impression that the listed AUR packages are somehow missing on the local system.
`Orphaned AUR packages: ...` again, may lead to the impression, that the packages are orphaned packages on the local system.

### Describe the solution you'd like

Change/Improve the messages, to, for example:

```
-> Packages not in AUR (anymore?):  somelocal-package another-package
-> Currently unmaintained AUR packages:  openssh-askpass
-> Flagged out of date AUR packages:  kde-servicemenus-rootactions prusa-slicer-git
```

### Describe alternatives you've considered

n/a

### Additional context

As a new user of `yay`, I was unsure about what it meant myself, so I started searching and found other people that apparently had the same problem, understanding what these descriptions mean, exactly. Certainly not a major issue, but still worth mentioning, I think.

**Comment by grandchild** [comment]
I agree about "missing" packages. Not 100% sure about the replacement phrase here.
"Packages missing from AUR"?
"Not found in AUR"?

I am less certain about changing "orphaned" packages. On the one hand, it is the term used on the AUR. Introducing a new term might increase inconsistency & confusion in another spot, even though it will probably make it clearer here. On the other hand I do really like "unmaintained" more than "orphaned".

**Comment by fiechr** [comment]
I agree, it's important to replace it only if it really is necessary and useful. Maybe others have better ideas considering the wording.

I was thinking like "Why are the orphaned?", because they don't have a maintainer assigned anymore.
Or "Why are the missing?", because the installed package's names couldn't be found in the AUR.

"Missing" sounds more like a error or warning message, when in fact it's perfectly normal, if someone has local packages installed or packages installed that where once in the AUR, but aren't anymore.
