### ISSUE TITLE
About the merge of Chinese Simplified translation

### ISSUE THREAD

**Issue by lakejason0** [Jguer/yay#1787]
### Is your feature request related to a problem? Please describe.
So now there are *two* Chinese Simplified on Transifex of this project, which is causing duplicate translations.

I (lakejason0) didn't notice it until I was accepted into `zh-Hans`, rather than `zh_CN`. I, of course, had to translate everything back to apply my fix on previous translation of `zh_CN` (the string`Packages to upgrade.` have a number before it in practice, and in Chinese we need to add a quantifier), as well as translate the strings that previously aren't translated.

### Describe the solution you'd like
merge `zh-Hans.po` to `zh_CN.po` (so that after the content of `zh-Hans.po` is also in `zh_CN.po`, `zh-Hans.po` will no longer exist, and all translations afterwards will be in `zh_CN.po`), do things alike to the transifex project. Accept me to translate `zh_CN`.

**Comment by Jguer** [comment]
:/ This might have been an oversight on my part when accepting collaborators, I really don't enjoy transifex's UI/UX 

I'll accept you in zh_CN.po and set it you as a coordinator, I'll merge zh-Hans into zh_CN and delete zh-Hans in github and transifex

**Comment by Jguer** [comment]
@lakejason0 should be all fixed now if you want to verify :slightly_smiling_face:
