### ISSUE TITLE
yay 11.3.0-1 build fails on archlinuxarm aarch64 [fakeroot, while creating message channels: Function not implemented]

### ISSUE THREAD

**Issue by RaichuBender** [Jguer/yay#1796]
### Reproduction Steps

1. Download the latest archlinuxarm root þar.gz and install using 'Linux Deploy' Android application
2. `ssh` into `<user>@localhost` and enter password
3. Follow the install instructions on the official archlinuxarm website to import the GPG keys and setup `sudo`
4. `sudo pacman -Syu`
5. Run the install command:
```sh
sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
```

### Expected behavior

Yet Another Yoghurt installs as expected
### Output

```c
thomas in 🌐 localhost in yay on  master
❯ makepkg -si
==> Making package: yay 11.3.0-1 (Wed 17 Aug 2022 05:03:01 PM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found yay-11.3.0.tar.gz
==> Validating source files with sha256sums...
    yay-11.3.0.tar.gz ... Passed
==> Extracting sources...
  -> Extracting yay-11.3.0.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
make: Nothing to be done for 'build'.
==> Entering fakeroot environment...
fakeroot, while creating message channels: Function not implemented
This may be due to a lack of SYSV IPC support.
fakeroot: error while starting the `faked' daemon.
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
```

**Comment by RaichuBender** [comment]
Excuse me, I marked this with the wrong label. It's not really a bug. Should have marked with `help-wanted`

**Comment by grandchild** [comment]
It seems that other people doing this are experimenting with `fakeroot-tcp`:
https://superuser.com/questions/1408340/in-arch-linux-wsl-windows-subsystem-for-linux-what-is-the-workaround-for

Can you try installing `fakeroot-tcp`, manually as outlined in the answer in the link above, and then try again?

**Comment by grandchild** [comment]
I'm closing this for now, but feel free to reopen if you have new information. Thank you! 🙂
