### ISSUE TITLE
Chinese characters are not aligned when using yay -Si

### ISSUE THREAD

**Issue by QiE2035** [Jguer/yay#1799]
### Affected Version

yay v11.3.0 - libalpm v13.0.1.

### Describe the bug

Chinese characters are not aligned when using `yay -Si`.

### Reproduction Steps

1. Change the language to Chinese.
2. `yay -Si aur/yay`

### Expected behavior

Chinese characters are aligned like this:

![image](https://user-images.githubusercontent.com/18079122/185847082-14e30894-9eb6-4559-abfa-99e851feb19b.png)

### Output

![image](https://user-images.githubusercontent.com/18079122/185847202-8b2635e4-0c39-456e-b83d-978a72222495.png)

```json
{
        "aururl": "https://aur.archlinux.org",
        "buildDir": "/tmp/yay/",
        "editor": "",
        "editorflags": "",
        "makepkgbin": "makepkg",
        "makepkgconf": "",
        "pacmanbin": "powerpill",
        "pacmanconf": "/etc/pacman.conf",
        "redownload": "no",
        "rebuild": "no",
        "answerclean": "",
        "answerdiff": "",
        "answeredit": "",
        "answerupgrade": "",
        "gitbin": "git",
        "gpgbin": "gpg",
        "gpgflags": "",
        "mflags": "",
        "sortby": "votes",
        "searchby": "name-desc",
        "gitflags": "",
        "removemake": "ask",
        "sudobin": "sudo",
        "sudoflags": "",
        "requestsplitn": 150,
        "completionrefreshtime": 7,
        "maxconcurrentdownloads": 0,
        "bottomup": true,
        "sudoloop": false,
        "timeupdate": false,
        "devel": false,
        "cleanAfter": false,
        "provides": false,
        "pgpfetch": true,
        "upgrademenu": true,
        "cleanmenu": true,
        "diffmenu": true,
        "editmenu": false,
        "combinedupgrade": false,
        "useask": false,
        "batchinstall": false,
        "singlelineresults": false,
        "separatesources": true,
        "version": "11.3.0"
}

```

### How to solve

I think this is because In a monospaced font, the width of a Chinese character should be equal to the width of **two** English characters (full-width and half-width), but yay may simply judge the number of characters without paying attention to this problem, so This leads to unaligned output, so properly judging the character width problem when formatting the output may help to solve this problem.

**Comment by Jguer** [comment]
Closed by https://github.com/Jguer/yay/pull/1803 , thanks @linweiyuan
