### ISSUE TITLE
Select dependency

### ISSUE THREAD

**Issue by Jguer** [Jguer/yay#18]
Sometimes more than one package provides the dependency. Displaying a menu with options would be nice.

Example: jre

**Comment by afg984** [comment]
There is an issue regarding this: https://bugs.archlinux.org/task/49090

I believe it's currently impossible without using the web interface

![image](https://user-images.githubusercontent.com/4318379/31106121-b3917890-a81b-11e7-88b0-b3880409ed70.png)

**Comment by vith** [comment]
It would be useful to at least stop automatically answering the prompt generated by pacman that lets you choose between options from your binary repos:

```console
==> Installing missing dependencies...
:: There are 3 providers available for java-runtime:
:: Repository extra
   1) jre7-openjdk  2) jre8-openjdk  3) jre9-openjdk

Enter a number (default=1): 
resolving dependencies...
looking for conflicting packages...

Packages (3) java-runtime-common-3-1  jre7-openjdk-headless-7.u151_2.6.11-1
             jre7-openjdk-7.u151_2.6.11-1
```

**Comment by Morganamilo** [comment]
It should. Are you using noconfirm?

**Comment by vith** [comment]
I don't believe so, I'm just doing `yay fontweak`.
```console
❯ jq .noconfirm ~/.config/yay/config.json 
false
```

**Comment by Morganamilo** [comment]
To do everything in one go yay generates a dependency tree before hand and effectively calls `pacman -S  java-runtime-common  jre7-openjdk-headless jre7-openjdk-7` If we were to let you choose mid install that would edit the dependency tree.

I'll need to think of a different way to output it that would allow changes and build/install all in one step.

**Comment by Morganamilo** [comment]
My initial thought right now is to include the direct dependencies of the initial `pacman -S` before a dep tree is generated. This will make the [repo] and [repomake] always be empty because they're installed before hand. But we won't be running `--noconfirm` so the user should still get to see the output and prompted so I think it could work.

**Comment by Morganamilo** [comment]
This should be fixed now for repo packages at least.
