### ISSUE TITLE
Installing python-acme-git does not update VCS entry

### ISSUE THREAD

**Issue by Morganamilo** [Jguer/yay#181]
the python2-acme repo has a lot of branches, 272 currently. The GitHub API will only list a certain amount of items per page. Because of this the master branch does not show up on the first page so Yay never finds the master branch to get the commit from.

You could traverse the pages with `?page=`  and increase the page size up to 100 with `?per_page` But I think a better solution is moving to a git `ls-remote` method described in #166.

**Comment by Jguer** [comment]
That is a super edge case but I still think #166 is a win even if it didn't fix #181

**Comment by Morganamilo** [comment]
I ended up brainstorming a couple of ideas in #166 which one do you mean? the `git ls-remote` is my current choice because it does not rely on the GitHub API which would fix #79 and allow us to expand --devel to any git repo even if it's not on GitHub.

Currently I'm working on #88 which I believe is working fine but I got stuck for ages as to why it wasn't working and it ended up being this #181. I am only working on #88 currently though. Not going to do anything with #166 until we have something more planned out.

**Comment by Jguer** [comment]
Now that I see `git ls-remote https://github.com/Jguer/yay HEAD` I like it even more, because it's git general instead of github specific
