### ISSUE TITLE
vcs.json is not updated when package is removed due to conflict resolution

### ISSUE THREAD

**Issue by kasper93** [Jguer/yay#1810]
### Affected Version

Tested with current HEAD (cd4462761a3b67ebc7ae3bb51cff0c1b0345504a)

### Describe the bug

vcs.json is not updated when package is removed due to conflict resolution

### Reproduction Steps

1. `yay -S yay-git`
2. `yay -S yay`
3. `grep yay-git vcs.json`

Now non-existent package yay-git will still be there.

### Expected behavior

I would expect vcs.json to be kept clean of orphans, which can be only manually removed. It is very common pattern to go back to non-aur/non-git version of a package,

**Comment by Jguer** [comment]
the `vcs.json` will be cleaned on the next pass of `yay -Syu --devel` in this case, the only thing that's a bit awkward currently is that a git ls is still done to the uninstalled git repository one last time
