### ISSUE TITLE
Execute script (e.g. backup) before certain packages are upgraded

### ISSUE THREAD

**Issue by khenderick** [Jguer/yay#1816]
### Is your feature request related to a problem? Please describe.

Upgrading certain "high-risk" packages (e.g. kernel, video drivers, systemd, ...) may cause issues. Although not often, it happens sometimes that after a kernel upgrade something goes horribly wrong and I end up having to boot from USB/ISO trying to figure out what went wrong (which packages were upgraded) and try to downgrade them.

### Describe the solution you'd like

It would be nice to be able to configure a script that yay should execute (preferably as root) right before it would start an upgrade including one or more of a configurable set of packages.

In my particular case, I'd love to run a script taking a few ZFS snapshots before the kernel, zfs, video drivers, systemd & bootloader are upgraded. In case of an emergency, I can simply roll back to that snapshot.

### Describe alternatives you've considered

Currently, when I notice those packages are about to be upgraded, I open another terminal window and manually take the snapshot.

**Comment by Jguer** [comment]
we could bundle this with a pre-build command implementation of #336

**Comment by grandchild** [comment]
Wouldn't simple pacman hooks be a perfect fit for this?

The [the `pacman-hooks` man page](https://man.archlinux.org/man/alpm-hooks.5.en) explains it all, and look into `/usr/share/libalpm/hooks/` for examples.
Put your own hooks into `/etc/pacman.d/hooks`. If you use the `[Action] When = PreTransaction` time, it should be able to do what you want. You can have as many `[Trigger] Target = <package>` entries as you want.

**Comment by Jguer** [comment]
Yeah, on the specific usecase of backups this seems to be well supported already (ex: https://aur.archlinux.org/packages/timeshift-autosnap)

**Comment by khenderick** [comment]
I wasn't aware of this. I think this covers my use-case completely, thanks for the suggestion @grandchild.
