### ISSUE TITLE
Option to trigger man-db.service when there are package changes

### ISSUE THREAD

**Issue by drws** [Jguer/yay#1818]
### Is your feature request related to a problem? Please describe.

`man-db.service` runs daily due to `man-db.timer` which might not be the optimal way in some cases. The timer can be masked if undesired, but `man-db.service` still needs to be run at appropriate times. Best after any package-related changes are made (package additions, removals or updates).

### Describe the solution you'd like

An option that enabled triggering of `man-db.service` after package additions, removals or updates.

### Describe alternatives you've considered

Afaik there are no general-purpose hooks that could be used for this. Manually running the service after `yay` seems to be best for now.

**Comment by grandchild** [comment]
(This is actually a pacman question, not a yay question.)

You can actually write your own pacman package upgrade hooks.
Have a look at [the `pacman-hooks` man page](https://man.archlinux.org/man/alpm-hooks.5.en) and look into `/usr/share/libalpm/hooks/` for examples. Put your own hooks into `/etc/pacman.d/hooks`.
The path for man-page files is `/usr/share/man` -- you could watch that one for changes in a hook that runs whatever `man-db.service` runs (or, even more clever, run that service!).

**Comment by drws** [comment]
An `alpm` hook is probably the best solution, but Arch `man-db` package maintainers [refuse](https://bugs.archlinux.org/task/76280) to support it. Currently the best option is to simply manually install it and mask the `man-db.timer`. This is still an opportunity for `yay` to provide more flexible package management to the user.

**Comment by grandchild** [comment]
Well, "refuse" is a strong word. It seems they decided that a man-db update takes too long to be run every time post packet upgrades.

But it's good you can just use [the original hook](https://github.com/archlinux/svntogit-packages/blob/aba1f0c1fae603044c056933ff9224c1bd2fc5cf/trunk/man-db.hook) and mask the service like you said 🙂

**Comment by drws** [comment]
Well, when recently asked, a sounding _no_ was provided in the first answer. Their decision seems reasonable for a default general-purpose behavior, but it's a clumsy solution. Fortunately it's not a common one with `man-db.timer` being the only _unneeded_ one in my systems.

What seems less reasonable is why an additional option that is even better in principle and also needed in some less common scenarios wouldn't be included, especially since it already was before. So yeah, _refuse_ is maybe a bit strong, but also pretty accurate for now. Giving it a last try there with re-emphasis that it could be an additional/alternative option.
