### ISSUE TITLE
Bug with new install algorithm

### ISSUE THREAD

**Issue by notramo** [Jguer/yay#182]
```
 ~ >>> yay -S tokei-git
:: Querying AUR...
[Repo Make: 2]  rust  rust
[Aur: 1]  tokei-git
```
There are two `rust` packages listed. However, it installs this stuff properly.

**Comment by Morganamilo** [comment]
At a glance:
`rust` has a makedepends on itself.
`tokei-git` requires `rust` and `cargo` but `rust` provides `cargo`

Those are likely contenders. I'll look more into it later.
