### ISSUE TITLE
Missing colors in mkinitcpio hook output when upgrading linux modules.

### ISSUE THREAD

**Issue by Cornul11** [Jguer/yay#1820]
### Affected Version
yay v11.3.0 - libalpm v13.0.1

### Describe the bug
Running `mkinitcpio` standalone will include colours in its output, however, when the said hook is called and executed during the installation of a package that requires rebuilding the initramfs, it does not include any colours in its output.

### Reproduction Steps

1. Run `yay` upgrading/updating a linux module.
2. Observe `mkinitcpio` output.

### Expected behavior

Expected highlighted text and colors in the output of `mkinitcpio`.

**Comment by grandchild** [comment]
```shell
$ mkinitcpio
# [colored output]

$ mkinitcpio | cat
# [uncolored output]

$ man mkinitcpio | grep color
       -n, --nocolor
           Disable color output.
# sadly, mkinitcpio doesn't provide a positive color flag 🙁
```
`mkinitcpio` (like many other programs) detects if it's connected directly to a terminal, and only outputs terminal color escape codes if it is. Disabusing it of that notion is [notoriously hacky](https://unix.stackexchange.com/questions/249723/how-to-trick-a-command-into-thinking-its-output-is-going-to-a-terminal) and I'm not sure including such a hack into yay's call of mkinitcpio is worth the results.

**Comment by Cornul11** [comment]
> ```shell
> $ mkinitcpio
> # [colored output]
> 
> $ mkinitcpio | cat
> # [uncolored output]
> 
> $ man mkinitcpio | grep color
>        -n, --nocolor
>            Disable color output.
> # sadly, mkinitcpio doesn't provide a positive color flag 🙁
> ```
> 
> `mkinitcpio` (like many other programs) detects if it's connected directly to a terminal, and only outputs terminal color escape codes if it is. Disabusing it of that notion is [notoriously hacky](https://unix.stackexchange.com/questions/249723/how-to-trick-a-command-into-thinking-its-output-is-going-to-a-terminal) and I'm not sure including such a hack into yay's call of mkinitcpio is worth the results.

Would it make sense to bring this up in the `mkinitcpio` repo?

**Comment by grandchild** [comment]
Sure, you should certainly try! 🙂
If they do implement a `--color` option, it'd be easy to use it in yay.

**Comment by grandchild** [comment]
Wait a second, yay doesn't even call `mkinitcpio`. The pacman hook does. So if anything this option (if it's added) would have to be used in that hook.

Closing this issue as it's a pacman/libalpm request, if anything.
