### ISSUE TITLE
Yay doesn't update packages by default with --color=auto

### ISSUE THREAD

**Issue by singiamtel** [Jguer/yay#1821]
### Affected Version

yay v11.3.0 - libalpm v13.0.2

### Describe the bug

Yay doesn't update packages when calling it as `yay --color=auto`. I have that as an alias, and it means I have to use `yay -Syu` rather than `yay`

### Reproduction Steps

1. `alias yay="yay --color=auto"` in your shell
2. Run yay
3. Nothing happens

### Expected behavior

Yay updates the packages independently of using --color=auto

### Output

```sh
sh-5.1$ yay
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
^C
Interrupt signal received


sh-5.1$ alias yay="yay --color=auto"
sh-5.1$ yay
sh-5.1$
```

**Comment by grandchild** [comment]
Hi, it seems several things are coming together here:

1. yay only does an implicit `-Syu` if called with no other arguments (any other flag will have the same "issue").
1. `--color=...` is a pacman flag, so cannot be set in the yay config.
   - Is there a specific reason you don't want to set `Color` in `/etc/pacman.conf`?
1. You probably want to do both `yay search terms` and `yay` both with that one alias, so I'm assuming aliasing to `yay=yay --color=auto -Syu` is not really an option?

Two possibilities:
1. extend yay's behavior to do "search or -Syu" also when some list of config flags is given, or
1. keep the current behavior and use `Color` in `/etc/pacman.conf` (which would make the alias redundant).

I'm not sure whether that behavior change would be desired, @Jguer?

**Comment by singiamtel** [comment]
I didn't know that you could set Color in pacman.conf, that works! Thanks for the quick reply

**Comment by Jguer** [comment]
@grandchild I agree that since `/etc/pacman.conf` is respected this should not be an issue. 

When there are any arguments the behavior of `yay` changes from operation `-Syu` to `-Y`. 

We could respect these options if there are no targets mentioned, but I'm not sure if it would help for any other scenario?

**Comment by grandchild** [comment]
While any yay- or pacman-specific lowercase option to `-Syu` would be a candidate for this, I also think this is a non-issue, and shouldn't be done.
