### ISSUE TITLE
Wrong variable name in voting instructions

### ISSUE THREAD

**Issue by somepaulo** [Jguer/yay#1822]
Instructions for AUR voting in [README.md](https://github.com/Jguer/yay/blob/next/README.md) say that `AUR_USER` environment variable shold be set. However, this throws an error. At least on Arch Linux. The actual environment variable name is `AUR_USERNAME`. Setting it makes voting work.

**Comment by Jguer** [comment]
Completely right @somepaulo , thanks for reporting it
