### ISSUE TITLE
override PKGBUILD architecture/merge arm64 and aarch64

### ISSUE THREAD

**Issue by UltraBlackLinux** [Jguer/yay#1825]
### Is your feature request related to a problem? Please describe.

Today I wanted to install ferdium-bin on my aarch64 device. The pkgbuild only has support for arm64 (which is the same)

### Describe the solution you'd like

Add a cli argument to change the architecture for the pkgbuild

### Describe alternatives you've considered

Always editing the pkgbuild is very tedious. You could however also merge aarch64 and arm64 to circumvent such problems.

**Comment by grandchild** [comment]
This is what I'm seeing:
```
 -> The following packages are not compatible with your architecture:
  ferdium-bin
:: Try to build them anyway? [Y/n] y
```
Yay doesn't ask you this?

Is `arm64` even a valid architecture identifier? I haven't heard of it, and it looks like it's just the informal name for `aarch64`.
I think the PKGBUILD of ferdium-bin should be fixed to replace `arm64` with `aarch64`.

And in regards to "merging" the architectures, that's not something yay can do. If anything it's `makepkg` but I don't think they'd do it either. The package should be fixed in any case.

**Comment by grandchild** [comment]
I made a comment on the package's AUR page.

**Comment by UltraBlackLinux** [comment]
> This is what I'm seeing:
> 
> ```
>  -> The following packages are not compatible with your architecture:
>   ferdium-bin
> :: Try to build them anyway? [Y/n] y
> ```
> 
> Yay doesn't ask you this?
> 
> Is `arm64` even a valid architecture identifier? I haven't heard of it, and it looks like it's just the informal name for `aarch64`. I think the PKGBUILD of ferdium-bin should be fixed to replace `arm64` with `aarch64`.
> 
> And in regards to "merging" the architectures, that's not something yay can do. If anything it's `makepkg` but I don't think they'd do it either. The package should be fixed in any case.

It does ask that. The problem with overriding that is, that it wont be able to find the package since its downloads are "arch-locked".

aarch64 seems to be arch-linux-specific since I have never seen that anywhere else. The commonly used name seems to be arm64.

**Comment by grandchild** [comment]
> arch-linux-specific

Not really: https://en.wikipedia.org/wiki/AArch64

**Comment by grandchild** [comment]
And the package is already fixed: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ferdium-bin
🙂

**Comment by grandchild** [comment]
If you can confirm that it works for you, I can close this issue.

**Comment by grandchild** [comment]
For completeness:

It does seem that Debian calls it `arm64` while at the same time explicitly mentioning that it's called `aarch64` elsewhere, such as in GNU platform triplets, binutils and in "other distros". https://wiki.debian.org/Arm64Port

Fedora also seems to call it aarch64 primarily: https://fedoraproject.org/wiki/Architectures/ARM

**Comment by UltraBlackLinux** [comment]
well whatever it is after all, thank you for informing the package maintainer, it indeed works now :)
