### ISSUE TITLE
Highlight color diff between old and new versions is missing?

### ISSUE THREAD

**Issue by Zesko** [Jguer/yay#1827]
### Describe the bug

I see the video of yay in this README: https://asciinema.org/a/399431 to show the highlight diff between old and new versions.

But I do not see the highlight anymore. I already enabled `Color` and `VerbosePkgLists`  in `/etc/pacman.conf`, it works for other messages, but not versions.

yay version:  v11.3.0

![Screenshot_20221112_104342](https://user-images.githubusercontent.com/17826352/201468449-51e1a181-99ba-424b-91d4-21f50aa33d0d.png)

### Expected behavior

yay should show the highlight of version like the description in README.

**Comment by Zesko** [comment]
See PR #329 in 2018.
I realize it was for the old Pacman text format.

**Comment by Zesko** [comment]
```
$ yay -Syu --combinedupgrade
```

or

```
$ yay -Syu --upgrademenu --combinedupgrade
```

Both show the highlight of versions

**Comment by AlexWayfer** [comment]
> @Jguer added Type: Question Status: Expected Behavior 

Should not we capture this case and output?

**Comment by Jguer** [comment]
The screenshot menu is output by pacman, reimplementing it would mean displaying a custom display before the early pacman call that's made in `--nocombinedupgrade`.

The new install engine doesn't implement this early pacman call as of yet and repo packages are always installed all together before AUR packages (reasoning https://github.com/Jguer/yay/commit/3bdb534), hopefully this code path doesn't exist in yay v12
