### ISSUE TITLE
`sudo` timeout after long build necessitates long rebuild

### ISSUE THREAD

**Issue by dagelf** [Jguer/yay#1831]
### Affected Version
yay v11.3.0 - libalpm v13.0.2

### Describe the bug

After a long build and before install, yay asks for `sudo` access. If this is not provided within the default timeout, it terminates, and the whole build needs to be done from scratch. This is a bug as it affects the primary function of `yay`, because of an assumption about a secondary utility `sudo`. It can work around this by just running `sudo` in a loop. 

If it does for some reason need to automatically time out, it could detect whether it has been run interactively, and if so    increase the loop time to a a day or two, or however long a long build can take on still in use hardware.

A potential workaround is to allow `yay` to run `sudo` without authentication, but this would be a tyrannical default. 

### Expected behavior

When something is built, it should not have to be rebuilt simply because someone wasn't present at the terminal at the time when the process was ready for the install step.

**Comment by grandchild** [comment]
Yay caches builds. So as a quick fix (which I always use) just do
```shell
yay -U ~/.cache/yay/foo/foo-0.0.0-0-x86_64.pkg.tar.zstd
```

If you want a more convenient but [more insecure](https://github.com/Jguer/yay/issues/147#issuecomment-366024535) option, you can enable `--sudoloop`. It's off by default for reasons explained in the linked issue.
