### ISSUE TITLE
-> runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by weyoun6** [Jguer/yay#1834]
### Affected Version
yay v11.3.1 - libalpm v13.0.2

### Describe the bug
On endevouros running yay does updates of non-aur packages, then outputs:

:: Searching databases for updates...
:: Searching AUR for updates...
 -> runtime error: index out of range [0] with length 0
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x19
main.main.func2()
        github.com/Jguer/yay/v11/main.go:187 +0x53
panic({0x562cdbf1d100, 0xc000308048})
        runtime/panic.go:884 +0x212
github.com/Jguer/yay/v11/pkg/query.AURInfo({0x562cdbf3fb50?, 0xc00001a0a8}, {0x562cdbf3eae0?, 0xc00005f880}, {0xc0002e9e00, 0x1, 0x1}, 0xc000141050, 0x96)
        github.com/Jguer/yay/v11/pkg/query/aur_info.go:73 +0x813
main.upList({0x562cdbf3fb50?, 0xc00001a0a8}, 0xc000141050, {0x562cdbf426c8, 0xc00006a3c0}, 0x0, 0x88?)
        github.com/Jguer/yay/v11/upgrade.go:72 +0x3ae
main.sysupgradeTargets({0x562cdbf3fb50, 0xc00001a0a8}, {0x562cdbf426c8, 0xc00006a3c0}, 0xc0?)
        github.com/Jguer/yay/v11/upgrade.go:242 +0xeb
main.install({0x562cdbf3fb50?, 0xc00001a0a8}, 0xc00016a360, {0x562cdbf426c8?, 0xc00006a3c0}, 0x0?)
        github.com/Jguer/yay/v11/install.go:127 +0xeb1
main.handleSync({0x562cdbf3fb50, 0xc00001a0a8}, 0xc00016a360, {0x562cdbf426c8, 0xc00006a3c0})
        github.com/Jguer/yay/v11/cmd.go:350 +0x77d
main.handleCmd({0x562cdbf3fb50, 0xc00001a0a8}, 0xc00016a360, {0x562cdbf426c8?, 0xc00006a3c0?})
        github.com/Jguer/yay/v11/cmd.go:177 +0x3c8
main.main()
        github.com/Jguer/yay/v11/main.go:193 +0x845

### Reproduction Steps
I am really not sure. Sorry. I have a second endevouros machine which does not give this issue. Both are updated.

### Expected behavior
Either no out of date AUR packages found, or it updates AUR packages

### Output

The bad machine:

[fountains@tip ~]$ yay -Pg
{
        "aururl": "https://aur.archlinux.org",
        "aurrpcurl": "",
        "buildDir": "/home/fountains/.cache/yay",
        "editor": "",
        "editorflags": "",
        "makepkgbin": "makepkg",
        "makepkgconf": "",
        "pacmanbin": "pacman",
        "pacmanconf": "/etc/pacman.conf",
        "redownload": "no",
        "rebuild": "no",
        "answerclean": "",
        "answerdiff": "",
        "answeredit": "",
        "answerupgrade": "",
        "gitbin": "git",
        "gpgbin": "gpg",
        "gpgflags": "",
        "mflags": "",
        "sortby": "votes",
        "searchby": "name-desc",
        "gitflags": "",
        "removemake": "ask",
        "sudobin": "sudo",
        "sudoflags": "",
        "requestsplitn": 150,
        "completionrefreshtime": 7,
        "maxconcurrentdownloads": 0,
        "bottomup": true,
        "sudoloop": false,
        "timeupdate": false,
        "devel": false,
        "cleanAfter": false,
        "provides": false,
        "pgpfetch": true,
        "upgrademenu": true,
        "cleanmenu": true,
        "diffmenu": true,
        "editmenu": false,
        "combinedupgrade": false,
        "useask": false,
        "batchinstall": false,
        "singlelineresults": false,
        "separatesources": true,
        "version": "11.3.1"
}

The good machine:

{
        "aururl": "https://aur.archlinux.org",
        "aurrpcurl": "",
        "buildDir": "/home/fountains/.cache/yay",
        "editor": "",
        "editorflags": "",
        "makepkgbin": "makepkg",
        "makepkgconf": "",
        "pacmanbin": "pacman",
        "pacmanconf": "/etc/pacman.conf",
        "redownload": "no",
        "rebuild": "no",
        "answerclean": "",
        "answerdiff": "",
        "answeredit": "",
        "answerupgrade": "",
        "gitbin": "git",
        "gpgbin": "gpg",
        "gpgflags": "",
        "mflags": "",
        "sortby": "votes",
        "searchby": "name-desc",
        "gitflags": "",
        "removemake": "ask",
        "sudobin": "sudo",
        "sudoflags": "",
        "requestsplitn": 150,
        "completionrefreshtime": 7,
        "maxconcurrentdownloads": 0,
        "bottomup": true,
        "sudoloop": false,
        "timeupdate": false,
        "devel": false,
        "cleanAfter": false,
        "provides": false,
        "pgpfetch": true,
        "upgrademenu": true,
        "cleanmenu": true,
        "diffmenu": true,
        "editmenu": false,
        "combinedupgrade": false,
        "useask": false,
        "batchinstall": false,
        "singlelineresults": false,
        "separatesources": true,
        "version": "11.3.1"
}

**Comment by Jguer** [comment]
Hey @weyoun6 could you install `yay-git` and try it out?

**Comment by weyoun6** [comment]
Hi @Jguer. I installed yay-git with:

git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

It works without error now. I'm still not sure what went south e.g. with my other machine being fine. Oh well! Thanks anyway. It seems I have a solution.

**Comment by weyoun6** [comment]
I noticed that during the build, it pulled in some go files. Maybe something got broken in go on the one machine.

**Comment by grandchild** [comment]
Interesting. You didn't really install `yay-git` with that, you (re)installed `yay` proper. But hey, if it works... 🙂

**Comment by weyoun6** [comment]
Er,  yeah. Good point. I can live with it.
