### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by edgars-cirulis** [Jguer/yay#1838]
### Affected Version

➜  ~ yay -V 
yay v11.3.1.r60.g7612bb5 - libalpm v13.0.2

### Describe the bug

Crashes at end

### Reproduction Steps

1. Compile yay from git
2. yay -S google-chrome / tried mesa-git same problem
3. Error!?

### Expected behavior

Package installs.

### Output

```sh

➜  ~ yay -S google-chrome
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  google-chrome-107.0.5304.121-1

:: (1/1) Downloaded PKGBUILD: google-chrome
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> N
==> Making package: google-chrome 107.0.5304.121-1 (Fri 25 Nov 2022 11:56:13 PM EET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading google-chrome-stable_107.0.5304.121-1_amd64.deb...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 89.0M  100 89.0M    0     0  10.1M      0  0:00:08  0:00:08 --:--:-- 11.2M
  -> Found eula_text.html
  -> Found google-chrome-stable.sh
==> Validating source files with sha512sums...
    google-chrome-stable_107.0.5304.121-1_amd64.deb ... Passed
    eula_text.html ... Passed
    google-chrome-stable.sh ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting google-chrome-stable_107.0.5304.121-1_amd64.deb with bsdtar
==> Sources are ready.
==> Making package: google-chrome 107.0.5304.121-1 (Fri 25 Nov 2022 11:56:39 PM EET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Entering fakeroot environment...
==> Starting package()...
  -> Extracting the data.tar.xz...
  -> Moving stuff in place...
  -> Fixing Chrome desktop entry...
  -> Removing Debian Cron job, duplicate product logos and menu directory...
==> Tidying install...
  -> Removing empty directories...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "google-chrome"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Adding install file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: google-chrome 107.0.5304.121-1 (Fri 25 Nov 2022 11:57:22 PM EET)
==> Cleaning up...
 -> runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x19
main.main.func2()
        github.com/Jguer/yay/v11/main.go:138 +0x53
panic({0x557893a3eee0, 0x557893cabdd0})
        runtime/panic.go:884 +0x212
main.buildInstallPkgbuilds({0x557893aa4f70?, 0xc000028128}, 0xc00012bcb0, {0x557893aa8c18, 0xc00029a000}, 0xc0000f2180, 0xc00051da40, 0x0?, 0x1, 0xc0000254a0, ...)
        github.com/Jguer/yay/v11/install.go:787 +0x1fed
main.install({0x557893aa4f70?, 0xc000028128}, 0xc00012bcb0, {0x557893aa8c18?, 0xc00029a000}, 0x11?)
        github.com/Jguer/yay/v11/install.go:349 +0x26f4
main.handleSync({0x557893aa4f70, 0xc000028128}, 0xc00012bcb0, {0x557893aa8c18, 0xc00029a000})
        github.com/Jguer/yay/v11/cmd.go:373 +0x79d
main.handleCmd({0x557893aa4f70, 0xc000028128}, 0xc00012bcb0, {0x557893aa8c18?, 0xc00029a000?})
        github.com/Jguer/yay/v11/cmd.go:177 +0x3fd
main.main()
        github.com/Jguer/yay/v11/main.go:144 +0x87a
➜  ~ 


```

**Comment by stuie1952** [comment]
Just experienced exact same issue.

**Comment by Matir** [comment]
I believe this was introduced in this commit: https://github.com/Jguer/yay/commit/9f67d10d5c1abbb7e695ab142b6e867010998b9a

It only occurs if installing a package not in the yay cache.

`yay` attempts to build a list of pkg build dirs involved here: https://github.com/Jguer/yay/blob/next/install.go#L203, but the download of the PKGBUILD actually occurs here: https://github.com/Jguer/yay/blob/next/install.go#L256 (after building the list)

This results in the srcinfos map being nil in buildInstallPkgbuilds, leading to a nil ptr deref here:

```
> main.buildInstallPkgbuilds() ./install.go:787 (hits goroutine(1):1 total:1) (PC: 0xa313d6)
   782:			)
   783:	
   784:			for _, pkg := range base {
   785:				wg.Add(1)
   786:	
=> 787:				go config.Runtime.VCSStore.Update(ctx, pkg.Name, srcinfo.Source, &mux, &wg)
   788:			}
   789:	
   790:			wg.Wait()
   791:		}
   792:	
(dlv) p srcinfo
*github.com/Morganamilo/go-srcinfo.Srcinfo nil
(dlv) p srcinfos
map[string]*github.com/Morganamilo/go-srcinfo.Srcinfo []
```

**Comment by edgars-cirulis** [comment]
> I believe this was introduced in this commit: [9f67d10](https://github.com/Jguer/yay/commit/9f67d10d5c1abbb7e695ab142b6e867010998b9a)
> 
> It only occurs if installing a package not in the yay cache.
> 
> `yay` attempts to build a list of pkg build dirs involved here: https://github.com/Jguer/yay/blob/next/install.go#L203, but the download of the PKGBUILD actually occurs here: https://github.com/Jguer/yay/blob/next/install.go#L256 (after building the list)
> 
> This results in the srcinfos map being nil in buildInstallPkgbuilds, leading to a nil ptr deref here:
> 
> ```
> > main.buildInstallPkgbuilds() ./install.go:787 (hits goroutine(1):1 total:1) (PC: 0xa313d6)
>    782:			)
>    783:	
>    784:			for _, pkg := range base {
>    785:				wg.Add(1)
>    786:	
> => 787:				go config.Runtime.VCSStore.Update(ctx, pkg.Name, srcinfo.Source, &mux, &wg)
>    788:			}
>    789:	
>    790:			wg.Wait()
>    791:		}
>    792:	
> (dlv) p srcinfo
> *github.com/Morganamilo/go-srcinfo.Srcinfo nil
> (dlv) p srcinfos
> map[string]*github.com/Morganamilo/go-srcinfo.Srcinfo []
> ```

So I assume a temp fix is by reverting the commit, or there can be simple quick haox to prevent failing?

**Comment by edgars-cirulis** [comment]
Also why they don't test before pushing anything "I am only assuming that"

**Comment by Jguer** [comment]
Thanks for the triage @Matir, this issue comes from local PKGBUILD support in the new engine not having an easy to infer PKGBUILD dir (same in https://github.com/Jguer/yay/issues/1840) ,  I'll take a look at it
