### ISSUE TITLE
Warn the user in case of partial upgrade

### ISSUE THREAD

**Issue by iTrooz** [Jguer/yay#1846]
### Is your feature request related to a problem? Please describe.

I recently realized that running `yay` without completing the upgrade (for example by pressing [n] when asking to upgrade) caused a partial upgrade. I do that often, for example because I realize the upgrade size is too much and I need to wait a few day to be at home

### Describe the solution you'd like

I think adding a warning message would help, so users know that they are in a partial upgrade scenario and should not use `yay|pacman -S`. The message could tell user they just did a partial upgrade, and to upgrade their system as soon as possible. I propose to add this when the user enter [n] with `yay -Syu` or `yay`, when an error occur during the upgrade and pacman/yay exits (these two cases should be covered by the pacman exit code), and when using `-Sy` without `u`

### Describe alternatives you've considered

I've considered directly asking for this feature in `pacman`, but I think it would be refused, because "the users should already have read the man and know how and how not to use it". `yay` seems more focused on user-friendliness, hence why I am asking here

### Additional context

I am ready to submit a PR for this, I just would like to know if you agree with the feature first

**Comment by grandchild** [comment]
I don't think that aborting the _repo packages_ upgrade when asked to proceed qualifies as "partial upgrade" -- in that case no packages get upgraded, right? And just being outdated is not "illegal" 😉 in Arch Land.

In terms of AUR a partial upgrade can indeed occur but I'm also unsure how the term "partial upgrade" applies to AUR packages. It's not impossible to get problems because of that, but AUR package version interdependencies are just much less rigid, most of the time.

**Comment by iTrooz** [comment]
> I don't think that aborting the repo packages upgrade when asked to proceed qualifies as "partial upgrade" -- in that case no packages get upgraded, right? 

My apologies, I was confused.
I now agree that this in itself is not a partial upgrade, but I still think a warning message would be a good addition, to warn the user not to use `yay|pacman -S` until they fully update their system, to not cause an *actual* partial upgrade.
What do you think ?

I'm also not sure about AUR packages, but as you said, dependencies versions should be more flexible, so it shouldn't be problematic not to warn the user

**Comment by grandchild** [comment]
Hm I'm not convinced this is something that really causes a lot of trouble. I often install some package with `pacman -S foo` even though I didn't run `-Syu` before. This has never been an issue except for maybe 404ing when the package was upgraded between the latest sync and the time of my installation (so... within the last day, usually). If you regularly run updates this doesn't really bite you. And if it does, then you get a 404 for the package download, and this will prompt you to -- at least -- run `-Sy`.

I'm sorry but I really don't see the need for an explicit error message here. The ratio of  "how much of an issue could it be" vs. "how often does this happen during normal operation" is just not high enough, imo.

Other people want to chime in with a different opinion?

**Comment by iTrooz** [comment]
> Hm I'm not convinced this is something that really causes a lot of trouble. I often install some package with pacman -S foo even though I didn't run -Syu before.

I think I'm not explaining myself very well, so let me illustrate with a concrete example :
```
# Run a container running an ArchLinux filesystem from 6 months ago, 2022/06/26
$ docker run --rm -it archlinux:base-devel-20220626.0.64095 bash

# Try to upgrade all packages, but then cancel
$ echo "n" | pacman -Syu

# Let's simulate we install a package that depend on openssl>=3
$ yes | pacman -S --asdeps "openssl>=3"

# Pacman is now broken
$ pacman --help
pacman: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

IIRC `yay` does no different than `pacman -Syu`, or at least it still seems to update the database

This is the case I would like to prevent, by printing a message "Warning: you just updated the database without updating all installed packages ! You should update your installed packages before installing something new" (maybe other solutions could be discussed, such as storing the database state and showing a message when the user *actually does the partial upgrade*)

EDIT : Example Dockerfile: https://gist.github.com/iTrooz/251d085c5fb2d852533c37edcd5f3d08

> Other people want to chime in with a different opinion?

I agree, after all maybe I'm the only one who would "need" this feature
