### ISSUE TITLE
Dependency resolution fails for syncthingtray

### ISSUE THREAD

**Issue by xeruf** [Jguer/yay#1855]
### Affected Version

❯ yay -V
yay v11.3.1 - libalpm v13.0.2

### Describe the bug

yay does not resolve soname dependencies, see https://github.com/Martchus/PKGBUILDs/issues/156

### Reproduction Steps

1. `yay -S syncthingtray`

### Expected behavior

yay resolves and installs the dependencies

### Output

It somehow does not find the packages, even though they are in the repos:

```sh
❯ yay -S syncthingtray
 -> Could not find all required packages:
        libqtutilities.so (Wanted by: syncthingtray)
        libqtforkawesome.so (Wanted by: syncthingtray)
        libc++utilities.so (Wanted by: syncthingtray)
❯ yay -Si qtutilities
:: Querying AUR...
Repository                    : aur
Name                          : qtutilities
Keywords                      : None
Version                       : 6.10.0-1
Description                   : Common Qt related C++ classes and routines used by my applications such as dialogs, widgets and models
URL                           : https://github.com/Martchus/qtutilities
AUR URL                       : https://aur.archlinux.org/packages/qtutilities
Groups                        : None
Licenses                      : GPL
Provides                      : libqtutilities.so
Depends On                    : libc++utilities.so  qt5-base
Make Deps                     : cmake  ninja  qt5-tools  mesa
Check Deps                    : None
Optional Deps                 : qtutilities-doc
Conflicts With                : None
Maintainer                    : Martchus
Votes                         : 33
Popularity                    : 1.145316
First Submitted               : Thu 27 Aug 2015 09:16:07 PM CEST
Last Modified                 : Wed 02 Nov 2022 04:13:15 PM CET
Out-of-date                   : No
```

**Comment by Jguer** [comment]
Hey @xeruf, provides search is still not implemented in the legacy engine using RPC v5. 

I've tested it on `yay-git` and it works using the new engine (you need to add `"newinstallengine": true` to `~/.config/yay/config.json`)

Support for provides search should be introduced to the legacy engine with RPC v6 (still not implemented)

**Comment by Jguer** [comment]
With #1856 this package now works in the legacy engine as well in `yay-git`. (`yay -Y --provides --save` is necessary in configs with provides search disabled)
