### ISSUE TITLE
[RFC] Proposed Issue template

### ISSUE THREAD

**Issue by Jguer** [Jguer/yay#188]
Added `\` so comments are displayed

#### Affected Version
\
\

#### Affected Command
\
\
\

#### Expected Results
\

#### Actual Results
\

**Comment by Morganamilo** [comment]
- You should probably mention to try the -git version first before submitting an issue.
- Might want to put `yay -V` in backticks.
- Personally I always find the `Expected Results` `Actual Results` to be a bit annoying and preachy but that's probably just me. I see it used elsewhere a bunch so it can't be that bad.
