### ISSUE TITLE
Warning about the consequences when there is not enough space

### ISSUE THREAD

**Issue by Ygarr** [Jguer/yay#1894]
It`s look like lowpriority or unneeded, but some times it`s ruin your system.
All you see as a result "failed to install not enough space" when it is too late to stop execution...
Just add  comparing цшер Mb дуае  before Y/n selection.

**Comment by Jguer** [comment]
Implementing this would require knowing how much size the entire install/upgrade would take, there's no easily implementable mechanism for this AFAIK
