### ISSUE TITLE
Retaining older binaries in the yay cache

### ISSUE THREAD

**Issue by kjk11** [Jguer/yay#1896]
I used to be able to keep old binaries in yay's cache directory. However, since the latest release, having a non-empty cache subdirectory results in the following error: 

```
 -> error fetching librewolf-bin: fatal: destination path 'librewolf-bin' already exists and is not an empty directory.
         context: exit status 128
```
I have to delete the contents of the directory in order for yay to download the PKGBUILD and the sources correctly. I have tried the the development branch, which shows the same behaviour. Is it possible to revert to how things worked previously? I am running the latest version of Arch Linux.

**Comment by Jguer** [comment]
Hey @kjk11 can you give more complete logs and context? I don't understand the scenario causing yay to error

**Comment by kjk11** [comment]
**Affected Version**

yay v11.3.2 - libalpm v13.0.2

**Comment by kjk11** [comment]
**Affected version**
```
yay v11.3.2 - libalpm v13.0.2
```
**Describe the bug**

See above. Updating works fine, if I ~/.cache/yay/palemoon is an empty directory or does not exist. If, however, there are old binaries left in the directory, yay gives the following output. 

**Output**
```
:: Checking for conflicts...
:: Checking for inner conflicts...
[Repo Make:8]  cbindgen-0.24.3-1  dump_syms-2.1.1-1  imake-1.0.9-1  llvm-15.0.7-1  wasi-libc-1:0+314+a1c7c2c-1  wasi-compiler-rt-15.0.7-1  wasi-libc++-15.0.7-2  wasi-libc++abi-15.0.7-2
[Aur:1]  librewolf-109.0-1

:: Remove make dependencies after install? [y/N] y
  1 librewolf                        (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: (0/1) Downloaded PKGBUILD: librewolf
 -> error fetching librewolf: fatal: destination path 'librewolf' already exists and is not an empty directory.
         context: exit status 128
```
**Steps to reproduce**

``` mkdir ~/.cache/yay/librewolf && touch ~/.cache/yay/librewolf/file && yay -S librewolf```

Let me know how to get any other information you require!

**Comment by grandchild** [comment]
Does this happen for every package?

This sounds like something is removing git information from these folders, specifically probably simply deleting the `.git` subfolders. Can you confirm that the problematic packages/folders don't have `.git` subfolders?

**Comment by kjk11** [comment]
Yes, indeed I can reproduce the error without a .git directory. Just touching an empty file in the subfolder or having a PKGBUILD is enough. And yes, it seems to happen with every package.

**Comment by grandchild** [comment]
And is there anything on your system that might remove these? I haven't heard of things that do this, but I could imagine some over-eager disk cleaner utility or script or something?

**Comment by grandchild** [comment]
Or, @Jguer is there some part of yay that might remove .git folders in the cache through some unusual combination of circumstances?

**Comment by kjk11** [comment]
Should downloading the sources not work regardless of whether a ```.git``` directory is already present or not?

**Comment by Jguer** [comment]
> Or, @Jguer is there some part of yay that might remove .git folders in the cache through some unusual combination of circumstances?

That's weird, only `git clean` is used on cleaning the `PKGBUILD` dir, so it would require the `.git` to be present.

@kjk11 do you have changes in your `~/.gitconfig`?

> Should downloading the sources not work regardless of whether a .git directory is already present or not?

Downloading sources is `PKGBUILD` specific, if the file is present, source downloading will work


```
:: (0/1) Downloaded PKGBUILD: librewolf
 -> error fetching librewolf: fatal: destination path 'librewolf' already exists and is not an empty directory.
         context: exit status 128
```

is expected behavior though, if no `.git` is present we don't want override the users' own files with a fresh clone

**Comment by grandchild** [comment]
The error you're seeing is not during downloading of the sources, but before that, during download of the PKGBUILD (and other accompanying files) from the AUR. Those files are in a git repo, which is either cloned (on first access/install) or pulled (on subsequent updates).

So the error is either something awry on @kjk11's system or in yay...

**Comment by kjk11** [comment]
@grandchild, thank you, there is indeed something specific to my system that removes the ```.git``` directory. I found the culprit now. I am pretty sure that previously the files were simply overwritten, when no .git directory was present. However, if that is not the intended behaviour, then this issue can be closed. Thank you for your help.
