### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by Jguer** [Jguer/yay#19]
The bloat is here. 

Plan for config file:
- When a user uses a cli arg like --topdown the setting will be saved and it won't be necessary to cast it again.
- The config file will have a option to disable this type of setting keeping.
- Since yay already uses encoding/json, it will be config.json. I would prefer another format, I would even prefer to use a framework but I'm worried about binary size
- -noconfirm won't be saved after use, but it will be possible to toggle it in config.json ( at the user's responsibility)

Options:
- Menu orientation
- Pacman bin
- Build Location
- Makepkg Options

**Comment by ineu** [comment]
Another useful feature of yaourt is to toggle PKGBUILD-related questions on/off. I believe it's not the same as the `--noconfirm` option

**Comment by Jguer** [comment]
Configuration file is implemented and stable, new options for the configuration file should be separate issues from now on.
