### ISSUE TITLE
Error download git source 

### ISSUE THREAD

**Issue by you-oops-dev** [Jguer/yay#1907]
### Affected Version
yay v11.3.2 - libalpm v13.0.2

### Describe the bug

yay does not clone sources to vim-lightline-git, as well as to vim-json-git
And everything is fine when you build it manually
```
git clone https://aur.archlinux.org/vim-lightline-git.git
cd vim-lightline-git
makepkg -scCi
```

### Reproduction Steps

1. ```yay -S vim-lightline-git```

### Output

```
 -> Cloning lightline.vim git repo...
Cloning into bare repository '/home/docker/.cache/yay/vim-lightline-git/lightline.vim'...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.3]: errno=Connection timed out

==> ERROR: Failure while downloading vim-json git repo
    Aborting...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.3]: errno=Connection timed out

==> ERROR: Failure while downloading lightline.vim git repo
    Aborting...
```

**Comment by dan-online** [comment]
Solved with this: https://github.com/Jguer/yay/issues/1729#issuecomment-1071317934

**Comment by you-oops-dev** [comment]
Uh-huh, I see. I didn't look at the comments under the package: https://aur.archlinux.org/packages/vim-lightline-git#comment-897865

**Comment by you-oops-dev** [comment]
I wonder how long ago the change in makepkg?
Just here was working and then bam no longer working decided to address the description of the bug, and yay here it turns out not to do.

**Comment by you-oops-dev** [comment]
I'm closing with the next message:
This is not a bug yay, but a bug of maintainers who didn't replace 
```source=("git://... .git")``` 
with 
```source=(git+https://... .git)```.
A warning to everyone for the future, **check the PKGBUILD section of the source**.
@dan-online thx 

I'll close issues it in a day, in case anyone has something to say.
