### ISSUE TITLE
Transparent celtral cache/builder node for home network?

### ISSUE THREAD

**Issue by HubKing** [Jguer/yay#1908]
### Is your feature request related to a problem? Please describe.
N/A

### Describe the solution you'd like
I have 3 computers running the same Linux distribution and having the same CPU architecture, so the packages they are using are the same ones. Yet, the 3 computers each download the same packages from the distribution's server hundreds of kilometres away. This is especially problematic, because Arch is a rolling-release and the updates often are large. Also, a lot of packages in AUR need building (downloading a package for another distribution, decompress, repackaging for AUR, etc) or compiling,  and the results are cached. On a laptop with limited resources, this quickly eats up the system disk space, and generates a lot of noise/heat.

When a user has multiple homogeneous (same distribution/same CPU architecture)  Linux computers that use yay in his home network, I think all the problems above can be easily (easy for the user) solved, if yay had some sort of way to cooperate with other instances of yay on the same network. That is, designate one yay node as a server, and all other yay nodes get packages from the server node, and delegate building/compiling/caching to the server node. All the user needs to do is just specifying the yay node on computer with a fast CPU and large disk space, and all the caching/remote building/remote compiling can be transparent to the user. Microsoft Windows 10/11 sort of does this already (enabled by default), although I do not like it because it gives user no control over which computer is to be the server.

Would this be difficult for yay to do?

### Describe alternatives you've considered

I have searched the web, and people were suggesting things like creating one's own repository on one of one's computers, creating private packages, and building the package on the computer, and make other computers subscribe to this private packages, but this seems unnecessarily complex.

**Comment by grandchild** [comment]
https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#Network_shared_pacman_cache

**Comment by grandchild** [comment]
In particular this subsection: https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#Distributed_read-only_cache
There seem to be a variety of tools available that share the built packages on a local network.

**Comment by HubKing** [comment]
> In particular this subsection: https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#Distributed_read-only_cache There seem to be a variety of tools available that share the built packages on a local network.

This only covers the caching part, and prebuilt packages, not AUR building/compiling caches, does it? 

Also, what I want is caching only the packages that were requested by at least one of my computers so that the same package would not be downloaded from a remote server again, not caching all the packages of the distribution (i.e., basically creating my own mirror server). Does it work like the former?

**Comment by grandchild** [comment]
> This only covers the caching part ...

I'd imagine it'd be easy just as easy to share `$XDG_CACHE_DIR/yay` with these tools as it is to share `/var/cache/pacman`. Maybe I'm wrong, but it doesn't sound too difficult. I'd use Syncthing to do it, but the tools listed there would probably be smarter about it.

>  caching only the packages that were requested by at least one of my computers [...] Does it work like [that]?

Yes they seem to do just that. The section is [explicitly mentioned as a preferred method](https://wiki.archlinux.org/title/DeveloperWiki:NewMirrors#Notes_about_private_mirrors) over running your own full mirror.

**Comment by grandchild** [comment]
I'm pushing back a bit on this, because adding a network-syncing component to `yay` feels a lot like scope creep, and something that an extra tool is perfectly capable of handling. (Not to speak of the complexity issues that arise from writing _any_ multi-node networking code 😨)

**Comment by HubKing** [comment]
> I'm pushing back a bit on this, because adding a network-syncing component to `yay` feels a lot like scope creep, and something that an extra tool is perfectly capable of handling. (Not to speak of the complexity issues that arise from writing _any_ multi-node networking code 😨)

Well, if it is very complicated or there is an easy-to-use separate software (i.e., all the user has to do is specifying the IP address of the server node), then I think this feature needs not be in yay. I thought (maybe wrongly) it was not be that difficult because it just has to tell other instance to do the thing (since they are the same yay, it could be just a simple command) and copying files over the network.

**Comment by grandchild** [comment]
If you do try out some of the available syncing software, do let us know how it went, and what you settled for! We may add it to the documentation.
