### ISSUE TITLE
error obtaining VCS status: exit status 128

### ISSUE THREAD

**Issue by 1Joel-cs** [Jguer/yay#1909]
I cloned https://aur.archlinux.org/yay.git but makepkg -si exited with the above error.  

Today, trying to figure out what was happening, I uninstalled yay, deleted the tar file and yay directory and started over.  This time everything worked as it should and I am unable to reproduce the error, so please disregard this issue.

**Comment by adamency** [comment]
FYI: The actual issue on my end was that the yay folder had some files owned by root and the solution was to `chown -R` the folder. A file permissions issue was most likely your problem (which would have been eliminated with the steps you describe) and also most likely that of other people coming here.
