### ISSUE TITLE
Support for proxy variables

### ISSUE THREAD

**Issue by MehradN** [Jguer/yay#1911]
### Is your feature request related to a problem? Please describe.
When using proxy variables (`all_proxy`, `ftp_proxy`, `http_proxy`, `https_proxy` and `no_proxy`), yay kind of ignores them.
Yay does indeed use these variables when installing AUR packages, but it will be ignored when installing repo packages.
The reason for that is because yay uses sudo to call pacman commands (at least it's what seems to be happening) and sudo will ignore your environment variables and will use the root user environment variables instead. This problem is also present when running commands such as `sudo pacman -Syu` and there is a work around for that, which yay doesn't use.

### Describe the solution you'd like
A solution for the `sudo pacman -Syu` is to redefine those environment variables after the sudo before the pacman.
For example if I have these two environment variables set:
```
declare -x http_proxy="http://127.0.0.1:8889/"
declare -x https_proxy="http://127.0.0.1:8889/"
```
I can run this command instead to fix the problem:
```
sudo http_proxy="http://127.0.0.1:8889/" https_proxy="http://127.0.0.1:8889/" pacman -Syu
```
A more automatic approach is: (Please take this one with a grain of salt. I'm not an expert in bash, but it does seem to work as intended)
```
sudo http_proxy=$http_proxy https_proxy=$https_proxy pacman -Syu
```

A solution can be to add an argument (for example `--proxy`) which will check for the proxy variables, and if they exist, will pass them to sudo.

### Describe alternatives you've considered
An alternative solution to the problem is to use the `-E` argument in sudo, which will keep the environment variables.
```
sudo -E pacman -Syu
```
So you can add an argument (for example `--keepenv`) which will make call sudo with `-E`.
However I like this one less, because it will copy all of the environment variables, and it might cause unwanted problems.

Another approach is to make the user specify the variables that they want to be passed to sudo, it can be achieved by adding an argument (for example `--keepvar`).
This approach is way more versatile, however this will solve the proxy problem in a more annoying way, because then the commands will look like this:
```
yay -S package-name --keepvar "all_proxy;ftp_proxy;http_proxy;https_proxy;no_proxy"
```

### Additional context
I don't have much knowledge in bash and pacman and the way yay works behind the scene, so sorry if some of these are impossible to implement, but having any of these can be very nice and useful, since currently for using a proxy, we are forced to call yay for aur packages only.

**Comment by Jguer** [comment]
`yay -Syu --sudoflags=-E` should work in that case

`yay -Syu --sudoflags=-E --save` should make it permanent.

I'm not sure making this a default option would have side effects and thereby I'm reticent to do it

**Comment by MehradN** [comment]
It works, thank you!
Also it seems like using the following command, we can pass only the proxy variables, heavily reducing the risk of causing unwanted side effects.
```
yay -Syu --sudoflags="http_proxy=$http_proxy https_proxy=$https_proxy no_proxy=$no_proxy"
```
It would be nice to have an alias for it, but I understand if you are against adding such alias.

**Comment by Jguer** [comment]
I agree but this won't work for `doas` or `su`, as such I prefer to leave in unmodified for now. 

Thanks for opening the issue though, I think other people struggle with this
