### ISSUE TITLE
yay not update packages from aur

### ISSUE THREAD

**Issue by oberkut** [Jguer/yay#1912]
### Affected Version

yay v11.3.2 - libalpm v13.0.2

### Describe the bug

Update packages from aur not work

### Reproduction Steps

1. yay -Syu

### Expected behavior

Update packages

### Output
{
	"aururl": "https://aur.archlinux.org",
	"aurrpcurl": "",
	"buildDir": "/home/berkut/.cache/yay",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"requestsplitn": 150,
	"completionrefreshtime": 7,
	"maxconcurrentdownloads": 0,
	"bottomup": true,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"provides": false,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false,
	"singlelineresults": false,
	"separatesources": true,
	"version": "11.3.2"
}

```sh
request failed: Get "https://aur.archlinux.org/rpc?arg%5B%5D=anydesk-bin&arg%5B%5D=audio-recorder&arg%5B%5D=brisk-menu&arg%5B%5D=chocolate-doom&arg%5B%5D=cpu-x&arg%5B%5D=davfs2&arg%5B%5D=debtap&arg%5B%5D=downgrade&arg%5B%5D=downgrader-git&arg%5B%5D=extremetuxracer&arg%5B%5D=far2l-git&arg%5B%5D=gconf&arg%5B%5D=gksu&arg%5B%5D=gtk-clearlooks-compact&arg%5B%5D=gtk-theme-switch2&arg%5B%5D=gzdoom&arg%5B%5D=jmtpfs&arg%5B%5D=libgksu&arg%5B%5D=libpamac-aur&arg%5B%5D=mate-screensaver-hacks&arg%5B%5D=mate-tweak&arg%5B%5D=mawk&arg%5B%5D=metis&arg%5B%5D=musictube&arg%5B%5D=package-query&arg%5B%5D=pamac-aur&arg%5B%5D=papirus-mate-icon-theme&arg%5B%5D=pyradio&arg%5B%5D=python-pep517&arg%5B%5D=python-pygame-git&arg%5B%5D=python-pynput&arg%5B%5D=python-sge&arg%5B%5D=python-uniseg&arg%5B%5D=python-xsge&arg%5B%5D=remmina-plugin-rdesktop&arg%5B%5D=retux&arg%5B%5D=rustdesk-bin&arg%5B%5D=snap-pac-grub&arg%5B%5D=snapper-gui-git&arg%5B%5D=stratagus&arg%5B%5D=stress-ng&arg%5B%5D=ttf-monapo&arg%5B%5D=ttf-mplus&arg%5B%5D=ttf-nanum&arg%5B%5D=ttf-tw&arg%5B%5D=ttf-vlgothic&arg%5B%5D=tuxracer&arg%5B%5D=wargus&arg%5B%5D=wine-installer&arg%5B%5D=xbindkeys_config-gtk2&arg%5B%5D=yaourt&arg%5B%5D=yay-bin&arg%5B%5D=zmusic&type=info&v=5": net/http: TLS handshake timeout

```

**Comment by Jguer** [comment]
> net/http: TLS handshake timeout

Normally indicates network issues, check proxy forwarding env variables and DNS resolvers
