### ISSUE TITLE
Explicit use of doas instead of sudo

### ISSUE THREAD

**Issue by ghost** [Jguer/yay#1913]
### Is your feature request related to a problem? Please describe.

A few days ago, Arch Linux has converted `base-devel` to a meta package, see the [Arch Announcement](https://archlinux.org/news/switch-to-the-base-devel-meta-package-requires-manual-intervention/) on this topic.

This has caused sudo to always be pulled as a dependency whenever building a package within Arch Linux, and currently, yay only uses opendoas as a backup to when sudo is not within the path. Sudo can no longer be uninstalled like I used to do it, as it now is depended on by the meta package, and thus sudo must always exist, and thus, yay will never resort to opendoas.

### Describe the solution you'd like

Configuration file or command line argument to allow yay to explicitly use opendoas instead of sudo, as I do not have sudo setup and I do not wish to use sudo!

### Describe alternatives you've considered

I am not considering alternatives, sudo is bloated, and is not something I want to use for updating packages, I would rather use the much lighter weight, opendoas.

**Comment by Jguer** [comment]
`~/.config/yay/config.json`
```json
{
  "sudobin": "doas"
}
```

Should fix yay to always use doas

**Comment by ghost** [comment]
That works, thank you :)

I hope this does not cause any issuess because opendoas does not have the same flags as sudo, and does not support all the features sudo does.

**Comment by Jguer** [comment]
`"sudoflags": "",` is normally set to empty so it should not be an issue. The only feature that becomes unavailable is `sudoloop` which shouldn't be used anyway
