### ISSUE TITLE
Reduces time and internet data consumption when git cloning

### ISSUE THREAD

**Issue by gaetan1903** [Jguer/yay#1934]
### Is your feature request related to a problem? Please describe.

the git clone is too slow and consumes a lot of internet data when the repository is with a very large number of commits and branches

### Describe the solution you'd like

use --depth 1 when git clone the repository

### Describe alternatives you've considered

I think you don't need any history for the repository? well, why not clone just a single history to reduce and speed up cloning
### Additional context

if possible with git the cloning only the default branch, this very helpul too

**Comment by Jguer** [comment]
Closing duplicate of https://github.com/Jguer/yay/issues/972

**Comment by nikelborm** [comment]
implemented here https://github.com/Jguer/yay/pull/2348
