### ISSUE TITLE
yay ignores --mflags

### ISSUE THREAD

**Issue by drws** [Jguer/yay#1935]
### Affected Version

`yay v11.3.2 - libalpm v13.0.2`

### Describe the bug

Yay is ignoring `--mflags` again. This is basically a resurrection of #1397.

### Reproduction Steps

This is just a single example of `--mflags` issue.

1. Run `yay -S --mflags --nocheck ...`.
2. Observe `check()`s still being executed.

### Expected behavior

`--mflags` are passed to `makepkg`.

**Comment by Jguer** [comment]
Can you try `yay-git`?

Also what is your shell? you might need `yay -S --mflags="--nocheck" ...`

EDIT: unable to reproduce on both yay and yay-git

**Comment by drws** [comment]
`bash` and `--mflags="--nocheck"` solves it, thank you. Shouldn't it work without the quotes?

**Comment by Jguer** [comment]
I tested it on bash and fish on kitty and they both worked. Might be some globbing setting you have in your bash profile or bashrc.

At the same time it's just visually confusing

`yay --mflags --nocheck --noextract -Pg`

Do you want to pass to makepkg only noextract or nocheck and noextract?

`yay --mflags --combinedupgrade --noconfirm -Pg` 

Maybe you wanted to pass "" to makepkg and `--combinedupgrade` to yay.

PS: you can use this command to see what yay interpreted `yay --mflags --nocheck -Pg`

**Comment by drws** [comment]
I figured before that `yay` just passes everything after `--mflags` to `makepkg`. Quotes are indeed clearer. Also, I shouldn't have any special globbing and `yay --mflags --nocheck -Pg` returns `"mflags": "--nocheck"`. The issue happens with [`python2`](https://aur.archlinux.org/packages/python2) for example.
