### ISSUE TITLE
How can I have a colored output

### ISSUE THREAD

**Issue by pantuts** [Jguer/yay#194]
#### yay v2.303

In the README, images included has colorized output. In my machine it does not have any colors. May I know how can I configure to have it output with colors?

![selection_012](https://user-images.githubusercontent.com/894185/36832538-d5c67ce2-1d66-11e8-937b-607762ba45c1.png)

**Comment by muesli** [comment]
@Jguer Since this seems to become a common question, maybe it should be mentioned in the README?

**Comment by Jguer** [comment]
Truth, I'll add it
