### ISSUE TITLE
Building package ungoogled-chromium takes very long time

### ISSUE THREAD

**Issue by cmonty14** [Jguer/yay#1941]
Hello,

can you please advise how to accelerate the build of package [ungoogled-chromium](https://aur.archlinux.org/packages/ungoogled-chromium)?

I deployed a VM with 16 sockets and 64GB RAM, and it takes ~60 min. until build is complete.

THX

**Comment by grandchild** [comment]
This is probably as good as it gets. Building browsers (any browser, Chromium, Firefox, etc.) from source is notorious for taking a long time. If you do this repeatedly, you might get _some_ benefit from tools like [ccache](https://wiki.archlinux.org/title/Ccache) though.

Also, not relevant to yay. This question is better asked on the Archlinux forums.
