### ISSUE TITLE
Cache sudo password upfront

### ISSUE THREAD

**Issue by Ghibranalj** [Jguer/yay#1942]
### Is your feature request related to a problem? Please describe.
I often want to install a package that requires long compilation time . Eg. llvm-git, clang-git. It would be nice if i can input my sudo password upfront so that i can leave my package installation overnight

Im always frustrated when i download/compile/install a package that requires a long time and when i just leave my machine overnight the package doesnt get installed because it was requesting my sudo password and i was away.

### Describe the solution you'd like
Add a flag that will make yay ask for sudo upfront and just kind of cache it.

add a flag `--passwd` or anything. when you use this flag yay will ask for password upfront

### Describe alternatives you've considered
Running yay with sudo (which you cant do)

**Comment by grandchild** [comment]
There are plenty of previous issues around this problem: #147 for example. See [my comment](https://github.com/Jguer/yay/issues/1831#issuecomment-1321243403) in #1831 for two workarounds.
