### ISSUE TITLE
[newengine] Only selecting an AUR package to update doesn't work anymore if dependencies are not selected

### ISSUE THREAD

**Issue by Porkepix** [Jguer/yay#1952]
### Affected Version

`yay v11.3.1.r124.g3d5a43c - libalpm v13.0.2`

### Describe the bug

The new engine present dependencies in the list of updates to do. For that reason using the exclusion mechanism to cherry-pick one or two AUR packages and nothing else doesn't work anymore as it used to do with the previous engine

### Reproduction Steps

1. Have a couple of updates to do including AUR packages with build dependencies not installed
2. Cherry-pick one of those AUR packages
3. Notice yay telling there's nothing to do

### Expected behavior

It should behave as it used to do and do the selected update

### Output

```sh
$ yay -Syu
:: Searching AUR for updates...
:: Checking development packages...
:: Searching databases for updates...
:: 11 Packages to upgrade.
[…]
 4  community/go                                   -> 2:1.20.1-1
[…]
 1  devel/yay-git           11.3.1.r124.g3d5a43c-1 -> latest-commit
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
 -> May cause partial upgrades and break systems
==> ^1
 there is nothing to do
```

This issue is a consequence of https://github.com/Jguer/yay/issues/1932 but the choice can be to fix this issue while keeping the behavior from #1932, reason for the new issue.

Also, question to @Jguer: I searched and found nothing like that, would it be something interesting and with some value to have an issue or something else where all the differences/different behavior between this old and new engine could be listed, especially to see which one of them are a deliberate choice, which ones are not, and for the latter which ones should be kept and which ones should be considered as real issues and fixed?

I've actually noticed at least one or two other differences like these which should maybe or maybe not be reported since you asked me to do some tests with the engine and git releases, and as it seems to some big piece of work, it might be nice having some labeling for that and place where some information on the topic can be found.

**Comment by Jguer** [comment]
This is an unintended behavior indeed, selecting only yay should have kept go as well (as it's a necessary make dep)



> Also, question to @Jguer: I searched and found nothing like that, would it be something interesting and with some value to have an issue or something else where all the differences/different behavior between this old and new engine could be listed, especially to see which one of them are a deliberate choice, which ones are not, and for the latter which ones should be kept and which ones should be considered as real issues and fixed?

That would make sense, I'm still drafting up man page and docs on what will be deprecated with the old engine for v12

**Comment by Jguer** [comment]
> I've actually noticed at least one or two other differences like these which should maybe or maybe not be reported since you asked me to do some tests with the engine and git releases, and as it seems to some big piece of work, it might be nice having some labeling for that and place where some information on the topic can be found.

Some of these might be side effects or just oversight, if you can create them as fast draft issues, I can tell if it's intended or needs more details

**Comment by Porkepix** [comment]
> That would make sense, I'm still drafting up man page and docs on what will be deprecated with the old engine for v12

So is an issue centralizing that something to be expected with everything changing that we should mention there? If not, should any noticed change in behavior be reported? (Here I've for example dev repositories from AUR packages relisted *after* their build, reconfirmation of their build and so on.

> Some of these might be side effects or just oversight, if you can create them as fast draft issues, I can tell if it's intended or needs more details

Okay, will do at least for the repos re-displayed, any particular naming you would like to see on such issues?
