### ISSUE TITLE
`yay` shows update for non`-git` package as `latest-commit`

### ISSUE THREAD

**Issue by Gigas002** [Jguer/yay#1964]
### Affected Version

`yay v11.3.1.r132.g210512a - libalpm v13.0.2`
`yay v11.3.2 - libalpm v13.0.2`

### Describe the bug

Non `-git` package is shown updated with `latest-commit` version. [Here's](https://aur.archlinux.org/packages/proton-ge-custom) an example with such behavior

### Reproduction Steps

1. `yay`
2. see `1  devel/proton-ge-custom              2:GE.Proton7.50-4 -> latest-commit` though package wasn't updated and is not `-git`

### Expected behavior

No updates detected for non `-git` packages if these haven't been pushed directly by author

**Comment by Jguer** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=proton-ge-custom#n105

Hey @Gigas002, Part of the dependencies of this package are not fixed, they are git clones of repositories, therefore they can change even when the PKGBUILD ver does not. 

Yay is not checking packages that are suffixed with `-git`, it's checking packages that contain git repos as sources

**Comment by Gigas002** [comment]
I see. Thanks for explanation!
