### ISSUE TITLE
failed to build 

### ISSUE THREAD

**Issue by djemilbakhti** [Jguer/yay#1967]
==> Making package: yay-git 11.3.1.r134.gdfa7ed5-1 (Tue 14 Mar 2023 12:35:29 PM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating yay git repo...
==> Validating source files with sha256sums...
    yay ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of yay git repo...
Cloning into 'yay'...
done.
Switched to a new branch 'makepkg'
==> Starting pkgver()...
==> Sources are ready.
==> Making package: yay-git 11.3.1.r134.gdfa7ed5-1 (Tue 14 Mar 2023 12:35:41 PM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
go build -trimpath -mod=readonly -modcacherw  -ldflags '-X "main.yayVersion=11.3.1.r134.gdfa7ed5" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay
go: downloading github.com/Jguer/aur v1.2.3
go: downloading github.com/Jguer/go-alpm/v2 v2.2.0
go: downloading github.com/Jguer/votar v1.0.0
go: downloading github.com/Morganamilo/go-srcinfo v1.0.0
go: downloading github.com/deckarep/golang-set/v2 v2.2.0
go: downloading github.com/leonelquinteros/gotext v1.5.2
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/hashicorp/go-multierror v1.1.1
go: downloading github.com/Morganamilo/go-pacmanconf v0.0.0-20210502114700-cff030e927a5
go: downloading github.com/adrg/strutil v0.3.0
go: downloading golang.org/x/term v0.6.0
go: downloading golang.org/x/sys v0.6.0
go: downloading golang.org/x/text v0.8.0
go: downloading github.com/hashicorp/errwrap v1.1.0
go: downloading github.com/itchyny/gojq v0.12.12
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/ohler55/ojg v1.17.5
go: downloading github.com/itchyny/timefmt-go v0.1.5
# github.com/Jguer/go-alpm/v2
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.0/db_six.go:29:103: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t value in argument to _Cfunc_alpm_find_group_pkgs
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.0/deps.go:26:75: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_handle_t) as *_Ctype_struct__alpm_handle_t value in argument to _Cfunc_alpm_find_dbs_satisfier
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.0/deps.go:26:75: cannot use _cgo1 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t value in argument to _Cfunc_alpm_find_dbs_satisfier
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.0/deps.go:43:78: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t value in argument to _Cfunc_alpm_find_satisfier
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.0/package_six.go:42:53: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t value in argument to _Cfunc_alpm_list_count
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.0/package_six.go:43:34: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t value in argument to _Cfunc_alpm_list_msort
make: *** [Makefile:113: yay] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: yay-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
yay-git - exit status 4

**Comment by Jguer** [comment]
Hey @djemilbakhti do you have pacman-git installed?

**Comment by djemilbakhti** [comment]
> Hey @djemilbakhti do you have pacman-git installed?

yes

**Comment by jdholtz** [comment]
Hey @djemilbakhti, yay was able to successfully build on my machine with version `11.3.1.r135.g16b9516-1`. It seems like this issue could've been fixed in commit 7bc4a66. Could you verify that the build is still failing on the latest commit?

**Comment by djemilbakhti** [comment]
> Hey @djemilbakhti, yay was able to successfully build on my machine with version `11.3.1.r135.g16b9516-1`. It seems like this issue could've been fixed in commit [7bc4a66](https://github.com/Jguer/yay/commit/7bc4a666e663b55ec569bbf8e0a6e42e355becbc). Could you verify that the build is still failing on the latest commit?

 build is still failing

**Comment by jdholtz** [comment]
Looking back, that commit does not look like it would potentially fix the build error.

**Comment by Jguer** [comment]
I was able to build yay-git `11.3.1.r135.g16b9516-1` with the latest pacman-git `6.0.1.r119.g262aa6c2-1`

can you check the output of `pacman -Qi pacman-git`, you may be running an outdated version

**Comment by jdholtz** [comment]
As a side note, I did not have pacman-git installed when Yay was built. Just the latest version of pacman.

**Comment by djemilbakhti** [comment]
rename pacman-git  in PKGBUILD  to pacman 
 yay-git build  failed
if don't rename pacman-git yay-git build successfully

**Comment by Jguer** [comment]
yay is checking if you have `pacman-git` installed to decide whether or not to use the extensions (`pacman -T 'pacman-git'`), so if you install `pacman-git` as `pacman` it will fail 


If there's a better suggestion for pacman-git detection, here's the full line from the makefile

`FLAGS += $(shell pacman -T 'pacman-git' >/dev/null 2>&1 && echo "-tags next")`

**Comment by djemilbakhti** [comment]
Thank you for explaining
