### ISSUE TITLE
No change in .SRCINFO is considering no change happened into PKGBUILD ; CleanBuild doesn't clean them

### ISSUE THREAD

**Issue by Porkepix** [Jguer/yay#1975]
### Affected Version

`yay v11.3.1.r135.g16b9516 - libalpm v13.0.2`

### Describe the bug

An AUR package I installed updated the PKGBUILD to fix an issue, and while doing so, `pkgrel` was bumped into `.SRCINFO`, but the `PKGBUILD`'s `pkgrel` was forgotten.

The result is that while `yay` was seeing a `-2` available to update to, it was still build a `-1` package, resulting in every `yay -Syu` trying to update it again.

I contacted the maintainer, and the  `PKGBUILD`'s `pkgrel` is now bumped too.

But it seems as the `.SRCINFO` got no change, it consider the `PKGBUILD` didn't changed either and doesn't download the most recent one:
`:: PKGBUILD up to date, skipping download: foobar`

I even try to tell yay to CleanBuild it, but while it throws everything else, `.SRCINFO` and `PKGBUILD` are kept.

### Expected behavior

PKGBUILD should also be checked for changes. Clean build could also clean `.SRCINFO` and/or `PKGBUILD`.

**Comment by Jguer** [comment]
```go
func (preper *Preparer) needToCloneAURBase(installInfo *dep.InstallInfo, pkgbuildDir string) bool {
	if preper.cfg.ReDownload == "all" {
		return true
	}

	srcinfoFile := filepath.Join(pkgbuildDir, ".SRCINFO")
	if pkgbuild, err := gosrc.ParseFile(srcinfoFile); err == nil {
		if db.VerCmp(pkgbuild.Version(), installInfo.Version) >= 0 {
			text.OperationInfoln(
				gotext.Get("PKGBUILD up to date, skipping download: %s",
					text.Cyan(*installInfo.AURBase)))
			return false
		}
	}

	return true
}
```

yay compares on the .SRCINFO to verify the local cloned version.
`--redownloadall` can be used in these cases

**Comment by Porkepix** [comment]
What do you mean exactly? This is on purpose to consider that any change to the `PKGBUILD` should also means a change in the `.SRCINFO`? Couldn't, like, a hash of the PKGBUILD be compared, if it can be fetched?
`paru` seems to always fetch the `PKGBUILD`, I guess (or didn't encountered a similar issue)

**Comment by Jguer** [comment]
https://github.com/Morganamilo/paru/blob/4780e94bb58b932416a8ed3d6453f9b640672155/src/download.rs#L446-L459 paru seems to do the same as yay.

> This is on purpose to consider that any change to the PKGBUILD should also means a change in the `.SRCINFO`?

yes, normally you should not even need to manually touch the `.SRCINFO` (`makepkg --printsrcinfo`) and as such you should not finish with a `.SRCINFO` ahead of the `PKGBUILD`.

Closing as there is no straightforward way to compensate for this packaging mistake
