### ISSUE TITLE
error when loading zsh competions

### ISSUE THREAD

**Issue by pExeen** [Jguer/yay#2]
i have an error :  `/home/dsh/.zsh/yay-competion.zsh:68: no matches found: *-d[Skip dependency checks]`.
It this line : ` 68 _pacman_opts_remove=(`

**Comment by Jguer** [comment]
Will take a look into it. Still haven't added yay's options to zsh completion, so I'll also take the opportunity to add them as well.

**Comment by pExeen** [comment]
ok thank you :)

**Comment by AndydeCleyre** [comment]
yay `1.101`:

```bash
/usr/share/zsh/site-functions/_yay:71: no matches found: *-d[Skip dependency checks]
```

**Comment by Jguer** [comment]
What command were you trying to complete?
I am unable to reproduce it on a fresh zsh install.

**Comment by AndydeCleyre** [comment]
My bad, I was improperly loading zsh completions, this should be re-closed.

Any plans to add completions for installed packages for `-Q[x]` and `-R[s]`?

**Comment by Jguer** [comment]
fish and bash have it but zsh doesn't. That's a bug.
