### ISSUE TITLE
New engine doesn't clean recursive make dependencies when asked to 

### ISSUE THREAD

**Issue by Porkepix** [Jguer/yay#2025]
### Affected Version

yay v11.3.1.r139.gca12cd7 - libalpm v13.0.2

### Describe the bug

Cleaning make dependencies doesn't clean make dependencies of dependencies (no recursivity) with new engine.

### Reproduction Steps

1. Install an AUR package with not installed make dependencies that'll pull other dependencies with them. Here for example it make depends on `npm`, `nodejs` and `rust`, but they'll also pull `node-gyp`, `nodejs-nopt` and `semver` with them.
2. Answer yes to the question of whether it should clean make dependencies at the end
3. See that it doesn't remove every make dependencies it installed (here, it removed `npm` and `rust`, but not `nodejs` nor the recursive dependencies)

### Expected behavior

Every make dependency that was installed should also be removed the same way.

### Output

Relevant parts:

```sh
7  extra/rust                            -> 1:1.68.2-1
5  community/nodejs                      -> 19.8.1-1
4  community/npm                         -> 8.19.2-1
```
Here you can see that some dependencies are appearing, but not all of them, as by recursivity, the dependencies that'll really be installed are those:
`Packages (6) node-gyp-9.3.1-1  nodejs-nopt-7.1.0-1  semver-7.3.8-1  nodejs-19.8.1-1  npm-8.19.2-1  rust-1:1.68.2-1`

```sh
checking dependencies...
debug: looking for unsatisfied dependencies
debug: checkdeps: transaction would break 'nodejs' dependency of 'node-gyp'
debug: checkdeps: transaction would break 'nodejs' dependency of 'nodejs-nopt'
debug: checkdeps: transaction would break 'nodejs' dependency of 'semver'
warning: removing nodejs from target list
:: nodejs optionally requires npm: nodejs package manager
debug: sorting by dependencies
debug: started sorting dependencies
debug: sorting dependencies finished

Packages (2) npm-8.19.2-1  rust-1:1.68.2-1

Total Removed Size:  522.54 MiB

:: Do you want to remove these packages? [Y/n]
```

Debug output of what it really removes, and as you can see, the recursive dependencies are not part of it, neither is `nodejs` because of them.

**Comment by Jguer** [comment]
#2039 should fix this @Porkepix, hopefully you can confirm it.

Also took the opportunity to apply the same fix to `-Yc`

**Comment by Porkepix** [comment]
> #2039 should fix this @Porkepix, hopefully you can confirm it.
> 
> Also took the opportunity to apply the same fix to `-Yc`

Looks fixed, indeed.
Didn't knew about `yay -Yc`, how does it compare to this alias I did, from Arch's wiki? `alias yay_clean_orphans='yay -Qtdq | yay -Rns -'`

**Comment by Jguer** [comment]
Should be the same result, `yay -Ycc` will also remove optional depends (do not recommend :sweat_smile:)
