### ISSUE TITLE
Newengine regularly shows messages about signal and context deadline when checking dev packages

### ISSUE THREAD

**Issue by Porkepix** [Jguer/yay#2036]
### Affected Version

yay v11.3.1.r139.gca12cd7 - libalpm v13.0.2

### Describe the bug

When running `yay -Syu` to check your updates, regularly, messages such as ` -> signal: killed` or ` -> context deadline exceeded` will appear. I'll provide below debug logs, but those messages are displayed even in non-debug mode.

### Reproduction Steps

1. Run `yay -Syu` with registered devel packages
2. Sometimes those messages will appear

### Expected behavior

We shouldn't get those messages and if they're symptoms of underlying issues, those should get a fix.

### Output

Below, anonymized excerpt of the relevant logs. Sometimes there are no messages, sometimes there are less, sometimes more, itt's not always the same.

```sh
[DEBUG:runner] capturing /usr/bin/git ls-remote https://git.server/org/repo.git HEAD
 -> signal: killed
[DEBUG:runner] capturing /usr/bin/git ls-remote https://git.server/org/repo.git HEAD
 -> context deadline exceeded
[DEBUG:runner] capturing /usr/bin/git ls-remote https://git.server/org/repo.git HEAD
 -> context deadline exceeded
```

**Comment by Jguer** [comment]
Those were made visible as sometimes people would complain of yay getting stuck when in reality the `git ls-remote` was taking long to connect.

I'll add a reference that it relates to the dev package update checks and which one.

(can you actually run `/usr/bin/git ls-remote https://git.server/org/repo.git HEAD`, normally it's related to something in the global `.gitconfig` or slow connection)

**Comment by Porkepix** [comment]
> Those were made visible as sometimes people would complain of yay getting stuck when in reality the `git ls-remote` was taking long to connect.
> 
> I'll add a reference that it relates to the dev package update checks and which one.
> 
> (can you actually run `/usr/bin/git ls-remote https://git.server/org/repo.git HEAD`, normally it's related to something in the global `.gitconfig` or slow connection)

The check with manual command works well. As explained, the number of errors is random and depends, likely from system load and/or I/O wait in my case, not network nor server issue. My `.gitconfig` is close to default.
Maybe can it have some larger timeout or something?

But if I understand you correctly, this is not new to this newengine, this was just made more visible outside of the debug flag?

**Comment by Jguer** [comment]
> But if I understand you correctly, this is not new to this newengine, this was just made more visible outside of the debug flag?

yes, this would happen before the message was not surfaced

**Comment by Jguer** [comment]
I'm still marking this as a bug as the timeouts were just not close to realistic. The linked PR should fix this. 

:+1:
