### ISSUE TITLE
yay 12.0.0 regression: "invalid option: '--clean' and '--refresh' may not be used together"

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [Jguer/yay#2049]
### Affected Version
v12.0.0

### Describe the bug
Entering `yay -c` or `yay --clean` causes:
error: invalid option: '--clean' and '--refresh' may not be used together

### Reproduction Steps

1. `yay -c` or `yay --clean`

### Expected behavior
Clean of unneeded packages.

### Output
`error: invalid option: '--clean' and '--refresh' may not be used together`

```sh

```

**Comment by Jguer** [comment]
Hey @ChristophSchmidpeter this was an intended change to allow something like

`yay --devel` (`yay -Syu --devel` to work)

`yay -Y --gendb` and `yay -Yc` should be used instead.

I'll add it to the release notes

I did find a bug that the wrong `--help` is being displayed and the right help is only being displayed in `-Y --help`. I'll make a patch for this

**Comment by Sherlock-Holo** [comment]
@Jguer is thera a new version with the patch? I'm using 12.0.4 version but `yay -c` still can't use

**Comment by Jguer** [comment]
Hey @Sherlock-Holo , use `yay -Yc` instead. 

yay does not default to `-Y` in the absence of an operation argument anymore to allow extra options to be passed to either the upgrade prompt or the yogurt selection menu

**Comment by meredrica** [comment]
This should probably be added to error message, this is extremely confusing

**Comment by Samueru-sama** [comment]
Add this to the error message, it is very confusing.

**Comment by Jguer** [comment]
Error message was removed as part of https://github.com/Jguer/yay/pull/2347 after almost a year of deprecation

**Comment by wzyou** [comment]
yay -Sc

**Comment by overflo23** [comment]
I found this after some trying and want to suggest to change the error output from

error: invalid option: '--clean' and '--refresh' may not be used together
 -> exit status 1

to:
"use -Sc to clean the cache"

the current behaviour is confusing and the error output is plain wrong as --clean and --refresh were not used together in the first place.


PS: thank you for the nice software. :*

**Comment by ChristophSchmidpeter** [comment]
@overflo23 In that case you need to create a new ticket/feature request
