### ISSUE TITLE
yay_vcs can not handle packages with multiple VCS sources

### ISSUE THREAD

**Issue by Morganamilo** [Jguer/yay#205]
I just started looking into moving over to the `git ls-remote` method and after looking through the code realised Yay can not handle packages with have multiple VCS sources in the packagebuild such as [brackets-git](https://aur.archlinux.org/packages/brackets-git/).

The easiest way to handle this is to change  `Info.URL` and `Info.SHA` to a `[]string` but this would make the old yay_vcs.json file incomparable with the new one. 

Maybe instead it would work if we allow duplicate package entries in the JSON. That would let us keep the format but would be a bit hanky and annoying to search through.

Instead I think we should move to a new file altogether `vcs.json` the `yay_` was a bit unneeded given that it was already in `~/.config/yay`. A new file would mean the user will start fresh but they can then `--gendb` their database back and it should work as before. The old file can be left unused without a problem or deleted by the user.

If we do decide on a new format I purpose something like this:
```json
{
	"brackets-git": [
		{
			"url": "https://api.github.com/repos/adobe/brackets-shell",
			"sha": "8ee733b4bf686e177a1e594616c22009c2bb777c"
		},
		{
			"url": "url2",
			"sha": "sha2"
		}
	],
	"another-package-git": [
		{
			"url": "url1",
			"sha": "sha1"
		}
	]
}
```

Also if we're moving files anyway maybe it would make more sense to have it in `~/.cache` than `~/.config`?

**Comment by Morganamilo** [comment]
Working on it I've settled on:
```json
{
	"brackets-git": {
		"github.com/adobe/brackets-shell.git": {
			"protocols": [
				"git",
				"https"
			],
			"branch": "HEAD",
			"sha": "8ee733b4bf686e177a1e594616c22009c2bb777c"
		},
		"github.com/adobe/brackets.git": {
			"protocols": [
				"git",
				"https"
			],
			"branch": "HEAD",
			"sha": "d0213b2f8e27b05f9d6e024e70fecd70cb84d854"
		}
	},
	"yay-git": {
		"github.com/Jguer/yay/": {
			"protocols": [
				"git",
				"https"
			],
			"branch": "HEAD",
			"sha": "01afc61f0d8662ee8c4f2356ee43ff67172331ef"
		}
	}
}
```

In go it looks like:
```go
var savedInfo vcsInfo

type vcsInfo map[string]shaInfos
type shaInfos map[string]shaInfo
type shaInfo struct {
        Protocols []string `json:"protocols"`
        Brach string `json:"branch"`
        SHA string `json:"sha"`
}
```

The file looks way less readable but has a couple of improvements:
- Can support multiple VCS sources in one package
- Tracks what protocols the packages support and tries each one until one succeeds
- Tracks the branch tracked specified in the pkgbuild

I'm a sucker for anything key pair, too much Lua I guess.

**Comment by Jguer** [comment]
>  too much Lua I guess

I know what you mean

- move to vcs.json :white_check_mark: 
- new file format and struct :white_check_mark:

**Comment by Morganamilo** [comment]
What about to move to `~/.cache`?

**Comment by Jguer** [comment]
@Morganamilo yes, forgot to include that but it makes more sense to put it in .cache
