### ISSUE TITLE
yay v12.0.1 regression: query outdated packages has additional output

### ISSUE THREAD

**Issue by jonpas** [Jguer/yay#2057]
### Affected Version

yay v12.0.1 - libalpm v13.0.2

### Describe the bug

`yay -Qum` in yay v12 outputs additional information which breaks `yay -Qum | wc -l` used for getting a count of outdated packages.

### Reproduction Steps

1. Run `yay -Qum | wc -l`.
2. Observe output being at least `2` even if no packages are outdated.

### Expected behavior

`yay -Qum` to output only outdated packages.

### Output

v11 example output:
```sh
$ yay -Qum
:: Searching AUR for updates...
:: Searching databases for updates...
 -> linux: ignoring package upgrade (6.2.8.arch1-1 => 6.2.9.arch1-1)
 -> linux-headers: ignoring package upgrade (6.2.8.arch1-1 => 6.2.9.arch1-1)
mergerfs 2.34.1-1 -> 2.35.0-1
yay-bin 11.3.2-1 -> 12.0.1-1
```
v12 example output:
```sh
$ yay -Qum
mergerfs 2.34.1-1 -> 2.35.0-1
yay-bin 11.3.2-1 -> 12.0.1-1
```

**Comment by Jguer** [comment]
wouldn't `yay -Qumq | wc -l` the correct command to use?

**Comment by jonpas** [comment]
I tend to agree, although most people I see on various forums are using `yay -Qum`.

I did try `yay -Qumq` as well, but in cases where you have ignored packages, it also produces output:
```sh
$ yay -Qumq
 -> linux: ignoring package upgrade (6.2.8.arch1-1 => 6.2.9.arch1-1)
 -> linux-headers: ignoring package upgrade (6.2.8.arch1-1 => 6.2.9.arch1-1)
```
which it did not before v12.

**Comment by Jguer** [comment]
I've checked against the output of pacman. I would not advice piping `pacman -Qu` neither but I see why it's being done. 
Will fix it

**Comment by Jguer** [comment]
#2060 should fix it and I'll release another patched version to avoid having changes pile up.

**Comment by jonpas** [comment]
Thanks!
