### ISSUE TITLE
yay 12.0.1 - error: invalid option '-s'

### ISSUE THREAD

**Issue by ArthurBorsboom** [Jguer/yay#2058]
yay on Arch Linux does not seem to work anymore with the following command.

```
yay -s photo collage
```

I have ran it twice. The first time it build the package and stopped with the invalid option error.
The second time it didn't build the package, since it was already created.
See below for details of the second run.

```
arthur@pb450:~$ yay -s photo collage
2 aur/collage-git 22.07.r8.gbcd9bec-1 (+0 0.00) 
    A command-line tool to create a collage from a collection of photos/images.
1 aur/photocollage 1.4.5-2 (+6 0.00) 
    Graphical tool to make photo collage posters.
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 1
AUR Explicit (1): photocollage-1.4.5-2
:: PKGBUILD up to date, skipping download: photocollage
==> Making package: photocollage 1.4.5-2 (Mon 03 Apr 2023 21:51:31)
==> Retrieving sources...
  -> Found photocollage-1.4.5.tar.gz
==> Validating source files with sha256sums...
    photocollage-1.4.5.tar.gz ... Passed
:: (1/1) Parsing SRCINFO: photocollage
==> Making package: photocollage 1.4.5-2 (Mon 03 Apr 2023 21:51:32)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found photocollage-1.4.5.tar.gz
==> Validating source files with sha256sums...
    photocollage-1.4.5.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting photocollage-1.4.5.tar.gz with bsdtar
==> Sources are ready.
 -> photocollage-1.4.5-2 already made -- skipping build
==> Making package: photocollage 1.4.5-2 (Mon 03 Apr 2023 21:51:34)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Sources are ready.
error: invalid option '-s'
 -> error installing: [/home/arthur/.cache/yay/photocollage/photocollage-1.4.5-2-any.pkg.tar.xz] - exit status 1
```

**Comment by Jguer** [comment]
Hey again @ArthurBorsboom, what is the option `-s`?

What was the expected behavior that is not done by `yay photo collage`?

**Comment by ArthurBorsboom** [comment]
I always use ```yay -s``` as 'search by keyword(s)'.
I have just tried ```yay photo collage``` and it seems to work fine.
The strange thing is that the behavior has recently changed.

I looked up the manual of pacman ```man pacman``` and it shows this is a pacman command-line option.

```
-s, --search <regexp>
           Search each locally-installed package for names or descriptions that match regexp. When including multiple search terms, only packages with descriptions
           matching ALL of those terms are returned.
```

I am not sure what the right behavior should be.
Somewhere I feel that yay should mimmick the behavior of pacman as much as possible.
But that is just my interpretation of how yay should work. :)
Next to the fact that this used to work before.

What are your thoughts about this ?

**Comment by Jguer** [comment]
Yay will always search by keywords in yogurt mode (`yay <targets>`/`yay -Y <targets>`), it should not require any option :slightly_smiling_face:

**Comment by ArthurBorsboom** [comment]
Okay. I am all fine with that.

I was just surprised that something didn't work anymore that worked before.

Out of curiosity, do you have any idea why this worked before and not
anymore?

**Comment by Jguer** [comment]
From memory, `yay -Y <target>` was throwing away a lot of options and not passing them to pacman after. Now they are passed along (which was the objective)

**Comment by aguirrem** [comment]
Ha! I came here for this exact same issue. I have been using -s since I learned about yay :shrug:
