### ISSUE TITLE
Implement tests for -Qu/q

### ISSUE THREAD

**Issue by Jguer** [Jguer/yay#2061]
Definition of Done:

- [ ] Implement output tests for `-Qu` and `-Quq`. It should be possible to test it like other tests present in `sync_test.go`

**Comment by smolx** [comment]
@Jguer , on your PR review:
> The only case I think would miss would be asserting empty update list to make sure an error is returned (so that then the exit error is 1)

While looking into yay's return codes for different test cases with empty update list, I came across with discrepancy with pacman's behavior. For example, when we have some native packages to update, but no foreign ones:
```
$ yay -Qum
$ echo $?
0
$ sudo pacman -Qum
$ echo $?
1
```

Should yay return 1 as exit code as well? May I try to fix this?

**Comment by Jguer** [comment]
Hey @smolx , yes this exit code should match :slightly_smiling_face:, if you can fix it that would be great
