### ISSUE TITLE
yay --clean bug

### ISSUE THREAD

**Issue by IamRezaMousavi** [Jguer/yay#2062]
I can't clean my system :(

![Screenshot from 2023-04-04 05-11-55](https://user-images.githubusercontent.com/83984878/229664939-89b316d3-73bc-4eb6-90d9-72a72f718bb1.png)

**Comment by kanna5** [comment]
Try `yay -Y --clean`

**Comment by kolayne** [comment]
The workaround worked for me

**Comment by IamRezaMousavi** [comment]
> Try `yay -Y --clean`

It's worked for me

But empty `--clean` command  still has a bug

**Comment by IamRezaMousavi** [comment]
is this command use `sudo pacman -Qtdq | sudo pacman -Rns -` too??
(for cleaning all unnecessary packages in system)

**Comment by Jguer** [comment]
closing as intended change https://github.com/Jguer/yay/releases/tag/v12.0.0 

duplicate of https://github.com/Jguer/yay/issues/2049
