### ISSUE TITLE
I can no longer just get a list of upgradable packages

### ISSUE THREAD

**Issue by frankspace** [Jguer/yay#2064]
### Affected Version

yay v12.0.2 - libalpm v13.0.2

### Describe the bug

After upgrading yay from 11.3.2, either `yay -Syu` or `yay -Syu --aur` doesn't actually display a list of anything, it just prompts me to select a repository for java-runtime=8:

```
:: Searching AUR for updates...
:: There are 2 providers available for java-runtime=8:
:: Repository world
    1) jre8-openjdk 
:: Repository extra
    2) jre8-openjdk
```

I presume that's because I use Artix, so there is actually a choice of repositories.  Is yay trying to just go ahead and build packages without my permission?

### Reproduction Steps

Just enter `yay -Syu --aur`.

### Expected behavior

I expect a list of packages that are newer than those on AUR, followed by missing, orphaned, and out-of-date packages; followed by an enumerated list of AUR packages that I could upgrade.  I realize some changes were made in version 12, but I can't for the life of me figure out how to just get a list of upgradeable packages.  (For what it's worth: I always directly download pkgbuilds and compile them directly, but yay was excellent at giving me info about the status of AUR packages as noted above; I can't figure out how to get that functionality back.)

### Output

yay -Pg
{
        "aururl": "https://aur.archlinux.org",
        "aurrpcurl": "https://aur.archlinux.org/rpc?",
        "buildDir": "/home/frank/.cache/yay",
        "editor": "",
        "editorflags": "",
        "makepkgbin": "makepkg",
        "makepkgconf": "",
        "pacmanbin": "pacman",
        "pacmanconf": "/etc/pacman.conf",
        "redownload": "no",
        "rebuild": "no",
        "answerclean": "",
        "answerdiff": "",
        "answeredit": "",
        "answerupgrade": "",
        "gitbin": "git",
        "gpgbin": "gpg",
        "gpgflags": "",
        "mflags": "",
        "sortby": "name",
        "searchby": "name-desc",
        "gitflags": "",
        "removemake": "no",
        "sudobin": "sudo",
        "sudoflags": "",
        "version": "12.0.2",
        "requestsplitn": 150,
        "completionrefreshtime": 7,
        "maxconcurrentdownloads": 0,
        "bottomup": true,
        "sudoloop": false,
        "timeupdate": false,
        "devel": false,
        "cleanAfter": false,
        "provides": true,
        "pgpfetch": true,
        "upgrademenu": true,
        "cleanmenu": true,
        "diffmenu": true,
        "editmenu": false,
        "combinedupgrade": false,
        "useask": false,
        "batchinstall": false,
        "singlelineresults": false,
        "separatesources": true,
        "newinstallengine": true,
        "debug": false,
        "rpc": true
}

**Comment by Jguer** [comment]
Yay is trying to present you all the packages it will install after you selected the needed dependencies.

In this case one of your AUR upgrades requires the install of a make dependency and as such yay is asking you which one.

Once https://github.com/Jguer/yay/pull/2072 is merged `yay -Quq` and `yay -Quqq` should show you all the packages to be installed in case of an upgrade.

**Comment by Jguer** [comment]
#2073 should help with this

**Comment by Jguer** [comment]
> I presume that's because I use Artix, so there is actually a choice of repositories. Is yay trying to just go ahead and build packages without my permission? 

It is not objective that yay just goes ahead and builds packages without your permission. That would be a regression, it's just trying to display you an accurate list after of what it will install (even as a make dependency)
