### ISSUE TITLE
Show "May cause partial upgrades and break systems" only after user will exclude some package

### ISSUE THREAD

**Issue by gladykov** [Jguer/yay#2067]
### Is your feature request related to a problem? Please describe.

Right now it is shown before excluding any package, scaring users and occupying space:
https://forum.endeavouros.com/t/update-may-cause-partial-upgrades-and-break-systems/39274/18
https://old.reddit.com/r/EndeavourOS/comments/12bno54/psa_yay_now_prints_a_new_reminder/

### Describe the solution you'd like

1. Show it after user will deselect/exclude package
2. Make it less scary: `Warning: Partial upgrades may break your system. To abort press Ctrl+C`

### Alternative

Sounds like overkill, but: maybe make showing this warning configurable

**Comment by Jguer** [comment]
I'm afraid once past that point, a lot of text will scroll and the warning will be lost. 

I've tried making it less scary by pointing out the action must be taken for it to be unsafe, which it can be when applied to repo packages specially #2074
