### ISSUE TITLE
yay -c failed

### ISSUE THREAD

**Issue by Kayzwer** [Jguer/yay#2069]
### Affected Version

yay v12.0.2 - libalpm v13.0.2

### Describe the bug

yay -c failed

### Reproduction Steps

just run "yay -c"

### Expected behavior

[~]$ yay -c
and list out all useless dependencies

### Output

```sh
error: invalid option: '--clean' and '--refresh' may not be used together
 -> exit status 1
```

**Comment by 0xarch** [comment]
Try using ```yay -Yc``` instead of ```yay -c``` \(mentioned in  [Release 12.0](https://github.com/Jguer/yay/releases/tag/v12.0.0)\)

**Comment by Jguer** [comment]
closing as intended change https://github.com/Jguer/yay/releases/tag/v12.0.0 

duplicate of https://github.com/Jguer/yay/issues/2049
