### ISSUE TITLE
[yay v12] -Qua option now also shows needed (make)dependencies to apply updates.

### ISSUE THREAD

**Issue by Antiz96** [Jguer/yay#2076]
### Affected Version

This behavior happens since `v12.0.0` as far as I'm aware. But at the time I'm writing this report, I'm running `yay v12.0.3 - libalpm v13.0.2`.

### Describe the bug

Before v12.x.x, `yay -Qua` used to only list AUR packages that are available for update. Now it also lists *make* dependencies that need to be installed to the system in order to perform the update _(even if they come from official repos, for what it's worth)_.

### Reproduction Steps

1. Downgrade to (or install) `yay v12.0.2`
2. Remove the orphaned `go` make dependency from your system
3. `yay -Qua` will list both `yay` and `go`

### Expected behavior

The pre v12 behavior felt more coherent in my opinion: `yay -Qua` only lists the actual AUR packages that are available for update without additionally listing the needed *make* dependencies. 
Regarding the example listed in [Reproduction Steps](#reproduction-steps), I expected `yay -Qua` to only return `yay` and not `go`.

### Output

I use the default config:
```sh
{
        "aururl": "https://aur.archlinux.org",
        "aurrpcurl": "https://aur.archlinux.org/rpc?",
        "buildDir": "/home/rcandau/.cache/yay",
        "editor": "",
        "editorflags": "",
        "makepkgbin": "makepkg",
        "makepkgconf": "",
        "pacmanbin": "pacman",
        "pacmanconf": "/etc/pacman.conf",
        "redownload": "no",
        "rebuild": "no",
        "answerclean": "",
        "answerdiff": "",
        "answeredit": "",
        "answerupgrade": "",
        "gitbin": "git",
        "gpgbin": "gpg",
        "gpgflags": "",
        "mflags": "",
        "sortby": "votes",
        "searchby": "name-desc",
        "gitflags": "",
        "removemake": "ask",
        "sudobin": "sudo",
        "sudoflags": "",
        "version": "12.0.3",
        "requestsplitn": 150,
        "completionrefreshtime": 7,
        "maxconcurrentdownloads": 0,
        "bottomup": true,
        "sudoloop": false,
        "timeupdate": false,
        "devel": false,
        "cleanAfter": false,
        "provides": true,
        "pgpfetch": true,
        "upgrademenu": true,
        "cleanmenu": true,
        "diffmenu": true,
        "editmenu": false,
        "combinedupgrade": false,
        "useask": false,
        "batchinstall": false,
        "singlelineresults": false,
        "separatesources": true,
        "newinstallengine": true,
        "debug": false,
        "rpc": true
}
```

**Comment by Jguer** [comment]
I agree with your assessment , in -S yay is modifying the system the user needs to know what is going to be installed (even if temporarily).

In -Qu the user is only interested in what packages need updating, not the details of how it actually gets done. The -Qua point is also very relevant.

Thanks for opening this issue, it will be fixed.
