### ISSUE TITLE
Why did we have to butcher yay?

### ISSUE THREAD

**Issue by ghost** [Jguer/yay#2077]
I've been using Arch for 5 years. A simple yay once a week and have not had one issue.
I won't say that this new update caused me errors, because it didn't. It works. But it looks like complete and total dog****!!! A complete eyesore for users. "May break systems" is not a message you should see during the regular update process unless the user tries to prompt a partial upgrade. We can't even see the individual sizes of packages anymore.
The lead developer of EndeavourOS has just said they are even considering switching to Paru because they initially went with yay because of how clean and simple it was, but now it looks terrible in comparison. Please, please keep the algorithm but revert the other changes, it was one of the things making Arch simple for users out there, now it just looks like another complicated unstable mess.

**Comment by EXCV31** [comment]
Fully agree. yay always been simple and easy, now it's unnecessarily contrived and unreadable.

**Comment by furai** [comment]
I for one can't see the "outdated" AUR messages any more.  I'm not sure what's up but definitely yay currently feels like in alpha/beta quality from user perspective. But I guess we'll slowly get there.

**Comment by Jguer** [comment]
Hey, a lot of this discussion seems linked to https://github.com/Jguer/yay/issues/2078 `--nocombinedupgrade`

@furai can you create a new issue for the `Flagged out of date and Packages not in AUR`? That is to fix for sure.

I'd written this in another issue but I'll paste it: if you'd like to provide feedback to yay before it makes out of development cycle and into patching cycle, it helps if you install `yay-git` and update it with --devel. No promises of stability but it helps improve the tagged release.
