### ISSUE TITLE
yay version 12 - usage changes

### ISSUE THREAD

**Issue by UffeJakobsen** [Jguer/yay#2080]
With `yay` version 12.0+ something has fundamentally changed with `yay`

Previously (pre version 12) it was possible to run `yay` without any arguments just to have `yay`update the official repo packages.

Now `yay` (version 12+) insists to handle official packages and AUR packages as one

With that change it gets quite difficult to have `yay` only update the official repo packages and not AUR packages.

Quoting `yay -h` output:
```
If no operation is specified 'yay -Syu' will be performed
```
By that statement i would assume that `yay` and `pacman` would perform the same operation...

I've been a happy user of `yay` for many years - switched from `yaourt` to `yay` - but the recent changes seems to change ease-of-use  things that I was happy about with `yay`

It would be nice if the previous way of working could be reestablished - or if some short/easy option could be introduced to keep `yay`away from looking at AUR packages (suggestion: a new option `-A`)

**Comment by John-Gee** [comment]
Can't you use the config file to tell it not to check aur?

**Comment by UffeJakobsen** [comment]
> Can't you use the config file to tell it not to check aur?

I have no idea - and even if that is possible then the cases where I actually would like to update AUR will become the problem...

The whole point here is that `yay` (v12) have changed so drastically that all the appealing things about yay are gone.

**Comment by Jguer** [comment]
Hey @uffejakobsen , thanks for opening this issue, I think I can help you with this as yay already does all of these.

**I want to only upgrade repo packages**:

- `yay -Syu --repo` (or `yay --repo`, that now works in this version)

- you can write "aur" in the exclude prompt and `aur` packages will be excluded. This would be the same as the first part in the default v11 

**I want to only upgrade AUR packages**:

- `yay -Syu --aur` or `yay -Syua` (or `yay -a`/`yay --aur`

**Comment by UffeJakobsen** [comment]
Thanks for your reply

Quote:
> **I want to only upgrade repo packages**:
> 
>     * `yay -Syu --repo` (or `yay --repo`, that now works in this version)
> 

I would really prefer if there also was a short single letter option for `--repo` - as this is the thing that I use most in yay (several times per day - on many systems)

**Comment by Jguer** [comment]
A short option was not added as the obvious ones `-r` and `-s` were already taken. 

I'd be completely open to ideas on this

**Comment by UffeJakobsen** [comment]
Thanks for your reply
Quite:
> A short option was not added as the obvious ones `-r` and `-s` were already taken.

How about uppercase ? `-R` or `-S` - or even `-A` to indicate the opposite or `-a` ?

**Comment by UffeJakobsen** [comment]
Wait - I realize that uppercase `-S` and `-R` maybe impossible due to pass-through to pacman... or am I wrong...

But `-A` would still work - I think...

**Comment by John-Gee** [comment]
> 
> > **I want to only upgrade repo packages**:
> > ```
> > * `yay -Syu --repo` (or `yay --repo`, that now works in this version)
> > ```
> 
> I would really prefer if there also was a short single letter option for `--repo` - as this is the thing that I use most in yay (several times per day - on many systems)

Just FYI shell aliases are great, I have plenty for pacman as I was tired of writing "pacman -" so often, in this case you could have for example something like: alias yay="yay -Syu --repo". (Of course improving the base software is better so all can benefit.)

**Comment by Jguer** [comment]
Uppercase options are reserved for defining operations in pacman and yay which is why it would be best to avoid them.

Currently the only thing I can come up with is `-x` (excludes aur) as there will probably be no option that needs to start with `x` and exclude package is already covered by `--ignore` as well.

---

By the way, if you'd like to provide feedback to yay before it makes out of development cycle and into patching cycle, it would be great if you could install `yay-git` and update it with `--devel`. No promises of stability but it helps improve the tagged release

**Comment by UffeJakobsen** [comment]
> Currently the only thing I can come up with is `-x` (excludes aur) as there will probably be no option that needs to start with `x` and exclude package is already covered by `--ignore` as well.
> 

I'll vote for `-x` then :+1:  :-)

**Comment by uffejakobsen** [comment]
Just a short note about this issue - the changes introduced in v12.0.4 seems to change `yay` behavior back to that of pre-v12 - which is good news. Now it is again possible to perform system package `--repo' upgrades without any arguments to yay and then just skip the pending AUR upgrades - thanks :-)
