### ISSUE TITLE
Introduce short option for --repo

### ISSUE THREAD

**Issue by Jguer** [Jguer/yay#2082]
### Is your feature request related to a problem? Please describe.

Created from https://github.com/Jguer/yay/issues/2080

Introduce a short option for the existing long option `--repo`

### Describe the solution you'd like

`-n` as in `native` is the proposed short option but open to suggestions

### Describe alternatives you've considered

`-s` and `-r` and already in use by `--root` and `--search`

**Comment by Jguer** [comment]
`-x` is used for `--regex` in `-F`, although it's still available for `-S` and regex is behind `--search`/`-s` it might be confusing if you already associate with regex.

**Comment by Arzumify** [comment]
What about -Syun for
noaur

**Comment by Jguer** [comment]
Actually a good point but instead of `noaur` there's a `-n` in query options that applies well

```
       -n, --native
           Restrict or filter output to packages that are found in the sync database(s).
           This is the inverse filter of --foreign.
```

EDIT:

Here's the entry for foreign

```
       -m, --foreign
           Restrict or filter output to packages that were not found in the sync
           database(s). Typically these are packages that were downloaded manually and
           installed with --upgrade.
```

**Comment by starquake** [comment]
I'm not entirely sure what the last comment means. Are you saying `-n` is not an option because it is already used? Any suggestions for another letter?

When a letter has been decided I want to try and implement it.

EDIT: Or are you saying that the functionality of `--repo` can be replaced by the `-n` functionality and the `-a` functionality replaced by `--foreign` ?

**Comment by VishnuSanal** [comment]
hi, is this still active? I would like to work on this. I am a bit new here & looking forward to contributing :)

**Comment by Arzumify** [comment]
Yup
