### ISSUE TITLE
Error: Wrong parameter: '--clean' and '--refresh' cannot be used at the same time

### ISSUE THREAD

**Issue by SpiritOTHawk** [Jguer/yay#2086]
### Affected Version
yay v12.0.3 - libalpm v13.0.2

### Describe the bug
error: wrong parameter: '--clean' and '--refresh' cannot be used at the same time. But i dont use --refresh

### Reproduction Steps

1. open terminal
2.  run yay --clean

### Expected behavior
Unnecessary dependencies must be deleted

### Output

```sh
Error: Wrong parameter: '--clean' and '--refresh' cannot be used at the same time

```

**Comment by Jguer** [comment]
closing as intended change https://github.com/Jguer/yay/releases/tag/v12.0.0

duplicate of https://github.com/Jguer/yay/issues/2049
