### ISSUE TITLE
Create $XDG_CONFIG_HOME/yay if it doesn't exist

### ISSUE THREAD

**Issue by heyitswither** [Jguer/yay#209]
> $ yay -S linux-git

> open /home/tucker/.config/yay/vcs.json: no such file or directory

This is on yay-git 3.440.r4.g251d31c-1 (current commit as of opening this issue)

Works fine after I manually create ~/.config/yay

**Comment by Morganamilo** [comment]
Fixed in #210.

P.S. Whats with the weird pkgver on `yay-git`?

**Comment by Jguer** [comment]
`git describe --long --tags | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'` from the `PKGBUILD`

This PS is also a nice place to warn about this but the current `yay` package is not using `make` because the current makefile method is reading the number of commits of the PKGBUILD and not yay

**Comment by Morganamilo** [comment]
The current pkgver and pkgver on yay-git is 99 and 3 respectively. It should defiantly not be like that. @heyitswither is the maintainer.

I knew out version format was major.commitnumber but I never thought about what that means, requiring the git repo to build the package. Any chance you want to change that to a more traditional major.minor or major.minor.bugfix? Doing it during the bump to v4 will make sure the new format is always newer than the old one.
