### ISSUE TITLE
network issues should go to stderr

### ISSUE THREAD

**Issue by x70b1** [Jguer/yay#2094]
### Affected Version

yay v12.0.3 - libalpm v13.0.2

### Describe the bug

It seems like the feature that network issues are printed to stderr is broken atm. I am not sure how long.
This message outputs to stdout.

` * request failed: Get "https://aur.archlinux.org/rpc?arg...`

### Reproduction Steps

1. disable network connection
2. `yay -Qum 2> /dev/null`
3. prints the unexpected error

**Comment by Jguer** [comment]
Thanks for reporting this @x70b1, oversight when refactoring the logging system
