### ISSUE TITLE
Yay fails if sudo password request times out.

### ISSUE THREAD

**Issue by kotenok2000** [Jguer/yay#2097]
### Affected Version

yay v12.0.3 - libalpm v13.0.2
### Describe the bug
Yay fails if user wasn't present to input sudo password and sudo password request times out.

### Reproduction Steps

1.Install gnunet with  yay -S gnunet from standard user
2. do not follow progress
3. yay fails when sudo times out 

### Output
[sudo] password for user:
sudo: timed out reading password
sudo: a password is required
 -> error installing: [/home/user/.cache/yay/gnunet/gnunet-0.19.4-1-x86_64.pkg.tar.zst] - exit status 1

{
        "aururl": "https://aur.archlinux.org",
        "aurrpcurl": "https://aur.archlinux.org/rpc?",
        "buildDir": "/home/user/.cache/yay",
        "editor": "",
        "editorflags": "",
        "makepkgbin": "makepkg",
        "makepkgconf": "",
        "pacmanbin": "pacman",
        "pacmanconf": "/etc/pacman.conf",
        "redownload": "no",
        "rebuild": "no",
        "answerclean": "",
        "answerdiff": "",
        "answeredit": "",
        "answerupgrade": "",
        "gitbin": "git",
        "gpgbin": "gpg",
        "gpgflags": "",
        "mflags": "",
        "sortby": "votes",
        "searchby": "name-desc",
        "gitflags": "",
        "removemake": "ask",
        "sudobin": "sudo",
        "sudoflags": "",
        "version": "12.0.3",
        "requestsplitn": 150,
        "completionrefreshtime": 7,
        "maxconcurrentdownloads": 0,
        "bottomup": true,
        "sudoloop": false,
        "timeupdate": false,
        "devel": false,
        "cleanAfter": false,
        "provides": true,
        "pgpfetch": true,
        "upgrademenu": true,
        "cleanmenu": true,
        "diffmenu": true,
        "editmenu": false,
        "combinedupgrade": false,
        "useask": false,
        "batchinstall": false,
        "singlelineresults": false,
        "separatesources": true,
        "newinstallengine": true,
        "debug": false,
        "rpc": true
}
```sh

```

**Comment by regalialong** [comment]
Doesn't `--sudoloop` exist to help with timeouts? I've noticed it's disabled in your config, maybe it helps for this.

**Comment by kotenok2000** [comment]
Why isn't it enabled by default?

**Comment by Jguer** [comment]
Hey, https://github.com/Jguer/yay/issues/147 has a very long discussion about this.
