### ISSUE TITLE
yay -c doesn't work

### ISSUE THREAD

**Issue by sanngridhr** [Jguer/yay#2099]
### Affected Version

yay v12.0.3 - libalpm v13.0.2

### Describe the bug

`yay -c` straight up doesn't work

### Expected behavior

Cleaning up unneeded packages

### Output

```fish
❯ yay -c --debug
[DEBUG:runner] running /usr/bin/sudo -v
[DEBUG:runner] running /usr/bin/sudo -B pacman --debug -S -c -y -u --config /etc/pacman.conf --
[DEBUG:runner] running /usr/bin/sudo -v
помилка: недійсний параметр: "--clean" і "--refresh" не можна використовувати разом
 -> exit status 1
```

**Comment by FriendsNone** [comment]
Can confirm on my side, with the same version. `-c` and `--clean` does not work.

**Comment by petrzjunior** [comment]
Duplicate of https://github.com/Jguer/yay/issues/2049

**Comment by sanngridhr** [comment]
Thanks
