### ISSUE TITLE
ABS is being deprecated

### ISSUE THREAD

**Issue by SolarAquarion** [Jguer/yay#21]
You're going to need to use git for Yay -G and other ABS packages

**Comment by Jguer** [comment]
Yay 2 will require git anyway so I guess I'll just port everything over to git. AUR and ABS.

**Comment by Jguer** [comment]
Yay uses `"https://projects.archlinux.org/svntogit/packages.git/snapshot/packages/" + pkg.Name() + ".tar.gz"` and not `rsync://rsync.archlinux.org/abs`and I can't find any mention of svntogit snapshots being deprecated or pointing to rsync. 

Do you have any information on this?

**Comment by SolarAquarion** [comment]
So only the abs and the rsync stuff is being deprecated
