### ISSUE TITLE
Order of `$EDITOR` and `$VISUAL` is inconsistent with docs

### ISSUE THREAD

**Issue by smac89** [Jguer/yay#2101]
### Affected Version

yay v12.0.3 - libalpm v13.0.2

### Describe the bug

When `yay` chooses an editor from the environment, the docs says that the order is `$EDITOR`, followed by `$VISUAL`, however the opposite is observed

### Reproduction Steps

1. Set `EDITOR` environment variable to `/usr/bin/micro`
2. Set `VISUAL` environment variable to `/usr/bin/subl`
3. Install an AUR package and try to edit the `PKGBUILD`

### Expected behavior

`yay` should have used the `$EDITOR` first, followed by `$VISUAL`

> --editor \<command>
               Editor to use when editing PKGBUILDs. If this is not set the EDITOR environment variable will be checked, followed by VISUAL. If none of these are set Yay will prompt the user for an editor.

### Output

```sh
yay -S nginx-mainline-mod-lua lua51 lua-cjson luarocks
AUR Explicit (2): nginx-mainline-mod-lua-1:0.10.23-1, lua-cjson-2.1.0-5
AUR Dependency (3): nginx-mainline-mod-ndk-0.3.2-1, lua-resty-core-1:0.1.25-1, lua-resty-lrucache-0.13-1
Sync Explicit (2): luarocks-3.9.2-1, lua51-5.1.5-9
Sync Make Dependency (4): lua-5.4.4-3, lua53-5.3.6-1, lua52-5.2.4-5, nginx-mainline-src-1.23.4-1
Sync Dependency (1): luajit-2.1.0.beta3.r471.g505e2c03-1
:: PKGBUILD up to date, skipping download: nginx-mainline-mod-lua
:: PKGBUILD up to date, skipping download: lua-cjson
:: PKGBUILD up to date, skipping download: nginx-mainline-mod-ndk
:: PKGBUILD up to date, skipping download: lua-resty-core
:: PKGBUILD up to date, skipping download: lua-resty-lrucache
  5 nginx-mainline-mod-lua           (Build Files Exist)
  4 lua-cjson                        (Build Files Exist)
  3 nginx-mainline-mod-ndk           (Build Files Exist)
  2 lua-resty-core                   (Build Files Exist)
  1 lua-resty-lrucache               (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
  5 lua-resty-lrucache               (Build Files Exist)
  4 nginx-mainline-mod-lua           (Build Files Exist)
  3 lua-cjson                        (Build Files Exist)
  2 nginx-mainline-mod-ndk           (Build Files Exist)
  1 lua-resty-core                   (Build Files Exist)
==> PKGBUILDs to edit?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 5
Timeout waiting for detached instance to start: No such file or directory
 -> editor did not exit successfully, aborting: exit status 1
```

In the above case, it tries to use `subl`, but since I'm running the command on a headless server, the sublime window is unable to open. However, it should have used `$EDITOR`.

---

Tbh, I think the correct solution is to just update the docs. The behavior of choosing `VISUAL` first before `EDITOR` makes sense on desktop, which is probably where  a majority of arch users will use `yay`.

**Comment by Jguer** [comment]
Hey @smac89 , I've fixed up the doc to at least be according to the implementation. 

Thanks for opening this issue
