### ISSUE TITLE
Checksum calculated for old file in cache

### ISSUE THREAD

**Issue by Blutkoete** [Jguer/yay#2106]
### Affected Version
yay v12.0.3 - libalpm v13.0.2

I haven't tried yay-git yet.

### Describe the bug
I'm the maintainer of the [ecal](https://aur.archlinux.org/packages/ecal) package in the AUR. I noticed that if update the PKGBUILD on one my PCs and upload it and then try to install the updated package on another computer via yay, it reports a failed checksum check. Deleting the ecal-fat-source.tar.gz file from .cache/yay/ecal resolves the problem, so it appears that yay isn't redownloading ecal-fat-source.tar.gz.

### Reproduction Steps

1.  Install ecal 5.11.3 via yay (of course this is currently not possible, maybe we can find a solution here together)
2. Try to update to ecal 5.11.4 via yay

### Expected behavior
It should work, as cloning the AUR repo and using makepkg works as expected.

**Comment by moson-mo** [comment]
You'll have the same issue when using plain `makepkg`.  
It won't re-download files if they are already existing (yay also just uses `makepkg` when building the package).

Your tarball with the sources should have a unique name like:

`source=("$pkgname-$pkgver.tar.gz::https://github.com/eclipse-ecal/ecal/releases/download/v${pkgver}/ecal-fat-source.tar.gz")`

**Comment by Blutkoete** [comment]
Sorry for the noise and thank you for showing me how to do it correctly. My clean-up script made me believe it's working with makepkg because my clean-up script always deleted the sources.
