### ISSUE TITLE
Still can't install package groups

### ISSUE THREAD

**Issue by tippl** [Jguer/yay#211]
#### Affected Version
yay v3.440.r7.gedfc941 - lastest yay-git release at the time of posting this issue.

#### Issue
I have found #185 describing similar issue. In that issue `yay -S mate` returned package missing from AUR. This has been fixed, but it still doesn't pass the group to pacman.

#### Steps to reproduce
```
$ yay -S mate
There is nothing to do
```
Current yay-bin also asks for a sudo password before returning `There is nothing to do`, but the result is the same.

**Comment by tippl** [comment]
Did a bisect on this, the regression seems to have happened in 0b6e4e087243cfe4c5a9bee48f76de2adfc79d8a.

**Comment by Morganamilo** [comment]
Sorry about that, groups are not a thing I install often so I tend to forget about them, I'll make sure to test them whenever making install changes in the future.

Anyway it's fixed now, hopefully it stays that way.

**Comment by da-edra** [comment]
Is there a way to install package groups from the AUR using yay?

**Comment by Morganamilo** [comment]
Nope.
