### ISSUE TITLE
Correct diffs are not shown when updating packages from AUR

### ISSUE THREAD

**Issue by t-kowalewski** [Jguer/yay#2131]
### Affected Version

yay v12.0.4 - libalpm v13.0.2

### Describe the bug

Updating packages from AUR and selecting Diffs to show option "All" or "Not installed", prints out everything with plusses, basically treating such process as clean install and not update.
Selecting "Installed" option - right away proceeds with package installation, and is not printing diffs at all.

In addition yay doesn't mark such packages as **(installed)**, informing that only build files exist.

yay cache is untouched and contains old versions of the packages.
### Reproduction Steps

1. run `yay`
2.  select needed AUR package
3. Packages to clean build? - None
4. Diffs to show? - All, Not Installed or Installed
### Expected behavior

yay should output correct diffs for package being updated and not treat such operation as clean install
### Output

[ it shows that PKGBUILD is already up to date because I've stopped previous update process. Nonetheless diffs will be wrong even if new version of PKGBUILD is being downloaded during updating ] 
```sh
yay
:: Synchronizing package databases...
 endeavouros is up to date
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Searching AUR for updates...
:: Searching databases for updates...
:: 1 Packages to upgrade/install.
1  aur/postman-bin  10.12.0-1 -> 10.13.0-1
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
 -> Excluding packages may cause partial upgrades and break systems
==> 
AUR Explicit (1): postman-bin-10.13.0-1
:: PKGBUILD up to date, skipping download: postman-bin
  1 postman-bin                      (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
  1 postman-bin                      (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> A
diff --git /home/tony/.cache/yay/postman-bin/.gitignore /home/tony/.cache/yay/postman-bin/.gitignore
new file mode 100644
index 0000000..c4c48b4
--- /dev/null
+++ /home/tony/.cache/yay/postman-bin/.gitignore
@@ -0,0 +1,5 @@
+*
+!.gitignore
+!PKGBUILD
+!.SRCINFO
+!postman.desktop
diff --git /home/tony/.cache/yay/postman-bin/PKGBUILD /home/tony/.cache/yay/postman-bin/PKGBUILD
new file mode 100644
index 0000000..dec62be
--- /dev/null
+++ /home/tony/.cache/yay/postman-bin/PKGBUILD
@@ -0,0 +1,39 @@
+# Maintainer: Jay Ta'ala <jay@jaytaala.com>
+# Contributor: Claudio d'Angelis <claudiodangelis at gmail dot com>
+pkgname=postman-bin
+pkgver=10.13.0
+pkgrel=1
+pkgdesc="Build, test, and document your APIs faster"
+provides=('postman')
+conflicts=('postman')
+arch=('x86_64' 'aarch64')
+url="https://www.getpostman.com"
+options=(!strip)
+license=('custom')
+source_x86_64=(
+       "postman-${pkgver}-linux-x64.tar.gz::https://dl.pstmn.io/download/version/${pkgver}/linux64"
+       "postman.desktop"
+)
+source_aarch64=(
+       "postman-${pkgver}-linux-arm64.tar.gz::https://dl.pstmn.io/download/version/${pkgver}/linux_arm64"
+       "postman.desktop"
+)
+depends=(libxss nss gtk3)

```

**Comment by jdholtz** [comment]
Yay saves the last time you looked at a PKGBUILD diff. Next time you view it, Yay will show the diff from the previous saved commit to the most recent commit (HEAD). Therefore, if it shows all plusses, you most likely have never viewed that diff before so it is showing you the entire file. Do you expect the diff to show only the updates since the last pull or the behavior Yay currently has?

I can also verify that selecting Installed does not select already installed AUR packages.

**Comment by jdholtz** [comment]
Hey @t-kowalewski, does the attached PR and my comment above fully resolve the issue you are having?

**Comment by JurgenCruz** [comment]
I may have the same question as OP. I was expecting that if I do an update it would show me the diff in PKGBUILD from the last version, not the last time I asked for the diff. In the past I used pamac to install AUR packages and inspected the PKGBUILD then, then when I tried with yay, it was showing me all as new lines. so now that I have selected to show the diff it will now correctly only show differences during an update, correct?

Thanks.

**Comment by jdholtz** [comment]
> so now that I have selected to show the diff it will now correctly only show differences during an update, correct?

Yay will show all the changes in the PKGBUILD since the last time you viewed the diff with Yay. If you view it every time there is a new update to that AUR package then yes, Yay will only show the differences for that update.

**Comment by mkurz** [comment]
> Yay will show all the changes in the PKGBUILD since the last time you viewed the diff with Yay. If you view it every time there is a new update to that AUR package then yes, Yay will only show the differences for that update.

@jdholtz Where/how does yay save when you viewed the diff the last time?
I could not find anything in the `~/.cache/yay/<package>` (git) folder nor in `~/.config/yay/`.
Thanks!

**Comment by jdholtz** [comment]
> @jdholtz Where/how does yay save when you viewed the diff the last time?

Yay saves the position where you last reviewed the diff using the `YAY_DIFF_REVIEW` commit object. If you're interested, there's code for it in `pkg/menus/diff_menu.go` starting [here](https://github.com/Jguer/yay/blob/ec837c831d7171005934ff099ba4c9b12f8a2976/pkg/menus/diff_menu.go#L122).

**Comment by mkurz** [comment]
@jdholtz Thanks, that's interesting. However `YAY_DIFF_REVIEW` is wrong, the correct name of the commit object is `AUR_SEEN` now.  It was renamed in de4860463388df28ba5546f6ea072afdbe92c066 and then 21d0f33d.
To fix this I opened:
- #2535

Also I checked in one of my packages in the yay cache:
```
$ git rev-parse --verify AUR_SEEN
5538128146f1e6a2bedc532f32a05c459c989ca5
$ git rev-parse --verify YAY_DIFF_REVIEW
fatal: Needed a single revision
```

**Comment by j4k0xb** [comment]
I was also expecting that it shows the difference to the currently installed version (or fetch both PKGBUILDs from the aur in case it's missing in `.cache/yay`).

Could this be done as the default behavior or as a setting?

**Comment by jam-jarr** [comment]
This would be nice as a cli option considering recent AUR security issues
