### ISSUE TITLE
Operations on both official repos and AUR

### ISSUE THREAD

**Issue by oshmoz** [Jguer/yay#2132]
### Is your feature request related to a problem? Please describe.

It's the stupidest thing, and maybe something I missed in the man pages. How can I use a simple operation (Let's say -Qu) on both official repos and AUR. yay with no parameters will output the packages need updating from both repos and AUR, but yay -Qu will do only repo or only aur. 

### Describe the solution you'd like

yay -Qu --aur --repo

### Additional context

If it's something I missed in the man, just erase this issue.

Thanks for this great utility.

**Comment by Jguer** [comment]
`yay -Qu` by default operates on repo and AUR (no flags necessary).

I am unable to reproduce this if you can offer some extra information like `yay -Pg` and `yay -Qu --debug`

**Comment by oshmoz** [comment]
My mistake, I apologize. Please close this issue.
I think that the reason of my mistake is the different ordering of the packages in the Yay vs. Yay -Qu commands.

![image](https://user-images.githubusercontent.com/128575/234890061-1d688479-e307-4382-b4ca-9c5cb7e211e0.png)

Thank you.

**Comment by Jguer** [comment]
No problem @oshmoz, happy it's working fine for you
