### ISSUE TITLE
Installing explicit java version still prompts for java-environment

### ISSUE THREAD

**Issue by emersion** [Jguer/yay#2135]
### Affected Version

yay v12.0.4 - libalpm v13.0.2

### Describe the bug

When installing `jdk11-openjdk` and an AUR package which depends on `java-environment`, yay will prompt the user about which java to pick, and without user interaction will install the latest one.

Happened here: https://builds.sr.ht/~emersion/job/977230

### Reproduction Steps

`yay -S jdk11-openjdk android-sdk`

### Expected behavior

yay should not prompt for java.

### Output

```
:: There are 4 providers available for java-environment:
:: Repository extra
    1) jdk-openjdk 2) jdk11-openjdk 3) jdk17-openjdk 4) jdk8-openjdk 

Enter a number (default=1): 

:: There are 4 providers available for java-environment:
:: Repository extra
    1) jdk-openjdk 2) jdk11-openjdk 3) jdk17-openjdk 4) jdk8-openjdk 

Enter a number (default=1): 

Sync Explicit (2): unzip-6.0-19, jdk11-openjdk-11.0.19.u7-1
Sync Dependency (9): libx11-1.8.4-1, freetype2-2.13.0-1, libxtst-1.2.4-1, lib32-gcc-libs-12.2.1-2, lib32-glibc-2.37-2, libxrender-0.9.11-1, jdk-openjdk-20.0.1.u9-2, libxext-1.3.5-1, fontconfig-2:2.14.2-1
AUR Explicit (4): android-sdk-26.1.1-2, android-sdk-platform-tools-34.0.1-1, android-sdk-cmdline-tools-latest-9.0-1, android-sdk-build-tools-r34.0.0-1
```

**Comment by Jguer** [comment]
#2147 fixes this issue through caching of provides and the mechanism of sync targets always getting resolved before aur targets. 

TODO/Research: A cleaner fix would be to add all targets to the graph first and then start resolving dependencies.

Thanks for opening up the issue, if you spot any issues related with CI workflows, don't hesitate to open an issue

**Comment by emersion** [comment]
Thank you!
