### ISSUE TITLE
Running with --aur targets repo packages 

### ISSUE THREAD

**Issue by drws** [Jguer/yay#2149]
### Affected Version
yay v12.0.4 - libalpm v13.0.2

### Describe the bug
Even with `--aur` Yay proposes to update repository packages. I believe this happens when a repo dependency needs to be installed before AUR build and when Pacman is ran it wants to update everything.

### Reproduction Steps

1. Run an update with Yay, limited to AUR packages with `--aur`
2. In case a dependency from repository needs to be installed, updates for all packages are proposed alongside.

### Expected behavior
Only the required dependencies are installed in this step.

**Comment by Jguer** [comment]
Hey @drws , can you share an example of this?

**Comment by drws** [comment]
It's not an everyday occurrence that a package in AUR gets an update that requires new repository dependencies, but there was a case about a month ago with [`script-communicatior`](https://aur.archlinux.org/packages/script-communicator) that required new `qt6-*` depdendencies.

If you don't have it on your system, please try to install it and Yay will probably need to install some repo deps. Since there's not really much difference between install/reinstall/update, the issue will probably present itself (when Pacman asks you to confirm installation of repo dependencies).

**Comment by Jguer** [comment]
```
yay -Syu --aur script-communicator
```

on yay-git presents the following

```
:: 3 dependencies will also be installed for this operation
   extra/qt6-multimedia   -> 6.5.0-1
   extra/qt6-serialport   -> 6.5.0-1
   extra/qt6-tools        -> 6.5.0-4
   (make dependency of script-communicator)

:: 1 package to upgrade/install.
1  aur/script-communicator             -> 6.01-1
```

These packages are required by the AUR package and would need to be pulled anyway

**Comment by drws** [comment]
The issue is not when Yay asks in the beginning, but when you arrive at Pacman asking you to confirm installation of (make)deps. It wants to update other repo packages there as well.

Also, there's a small grammatic error in Yay's output in your example (should be _make dependenc**ies**_). And an extra dot in the line below (after _install_).

**Comment by Jguer** [comment]
:+1: I see the issue now, let me take a look at it, well spotted

**Comment by jdholtz** [comment]
Hey @Jguer, I found a fix for this which is to remove the `-u` or `upgrades` if the target mode is `ModeAUR`. I can fix it in two places:
1. In `installSyncPackages` (aur_install.go) which would remove the arguments when installing sync dependencies
2. In `BuildPacmanCmd` (cmd_builder.go) which would remove the upgrade arguments every time `--aur` is specified. This option might be better to capture all potential issues like this, but I'm not familiar enough with the code base to know if this will have unintended side effects

I can submit a PR for this if you think one of these options is sufficient to fix this issue.

**Comment by Jguer** [comment]
I think `installSyncPackages` might be the best place indeed to avoid all of these side effects. 
If there are more weird behaviors like this we can rethink the fix after
