### ISSUE TITLE
set --noconfirm as default

### ISSUE THREAD

**Issue by materemias** [Jguer/yay#2158]
### Describe the solution you'd like

yay --noconfirm works the way I prefer my updates mostly, could this flag set to be the default?

**Comment by Jguer** [comment]
Setting this option by default would allow unreviewed builds of AUR packages to occur, this is too risky.

```json
{
  "doubleconfirm": false
}
```

There is this option in the `~/.config/yay/config.json` that might be give a nice inbetween experience

**Comment by materemias** [comment]
Hey, thanks for the tip, do I understand it right that once confirmed it won't show the upgrade menu again?
Also conflicting packages cannot be resolved with this as of now right?

**Comment by Jguer** [comment]
> Hey, thanks for the tip, do I understand it right that once confirmed it won't show the upgrade menu again?

yes

>  Also conflicting packages cannot be resolved with this as of now right?

yes, that's to fix unfortunately :slightly_smiling_face:

**Comment by materemias** [comment]
Perfect, thanks!
