### ISSUE TITLE
Exit if usatisfied dependencies of excluded packages are present.

### ISSUE THREAD

**Issue by simon-r** [Jguer/yay#2159]
### Affected Version

yay v12.0.4 - libalpm v13.0.2

### Describe the bug

Yay, exits if required and unsatisfied dependencies of excluded packages are present.

### Reproduction Steps

For example, I've got this situation with the following packages:

```
10  aur/intel-oneapi-compiler      2023.0.0_25370-2 -> 2023.1.0_46305-2
 9  aur/intel-oneapi-dpl           2022.0.0_25335-1 -> 2022.1.0_43490-1
 8  aur/intel-oneapi-mpi                            -> 2021.9.0_43482-1
```
require:
```
 intel-oneapi-common=2023.1.0
 intel-oneapi-tbb>=2021.9.0
 intel-oneapi-dpcpp-debugger>=2023.1.0
 intel-oneapi-dev-utilities>=2021.9.0
```

They are stored in the community repo and are currently outdated.

1. ```yay -Syu --aur```
2. Select the numbers of the packages to be excluded ... 8-10

Yay exit with the error:
```
 -> could not find all required packages: intel-oneapi-dpcpp-debugger >=2023.1.0
could not find all required packages: intel-oneapi-dev-utilities >=2021.9.0
could not find all required packages: intel-oneapi-tbb >=2021.9.0
could not find all required packages: intel-oneapi-common =2023.1.0
```

### Expected behavior

Yay, must remove from the list of dependencies the dependencies of the excluded packages.

**Comment by Jguer** [comment]
Hey @simon-r , can you try this in `yay-git`?

**Comment by simon-r** [comment]
With yay-git, there are still some problems with the dependencies of the dependencies.
```
-> could not find all required packages: intel-oneapi-dev-utilities >=2021.9.0
could not find all required packages: intel-oneapi-tbb >=2021.9.0
could not find all required packages: intel-oneapi-dpcpp-debugger >=2023.1.0
```


==================

If I'm using yay vanilla the list of dependencies is the following:
```
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
 -> Excluding packages may cause partial upgrades and break systems
==> 5-8
 -> could not find all required packages: intel-oneapi-tbb >=2021.9.0
could not find all required packages: intel-oneapi-dpcpp-debugger >=2023.1.0
could not find all required packages: intel-oneapi-dev-utilities >=2021.9.0
could not find all required packages: intel-oneapi-common =2023.1.0

```

**Comment by smolx** [comment]
It appears to be the same issue as #2127.

**Comment by Jguer** [comment]
https://github.com/Jguer/yay/pull/2203 seems to fix this. @simon-r could you try the latest version of `yay-git`?
