### ISSUE TITLE
Cannot run program -v: No such file or directory

### ISSUE THREAD

**Issue by izzy8799** [Jguer/yay#2160]
### Affected Version

yay v12.0.4 - libalpm v13.0.2

### Describe the bug

Starts spamming with an incomprehensible error.

### Reproduction Steps

```yay --sudo pkexec --noconfirm -q --sudoloop```

### Expected behavior

All Pacman and AUR packages should be updated by asking for the password once via pkexec.

### Output

```
Cannot run program -v: No such file or directory
 -> exit status 127
```
(Spamming with it endlessly.)

**Comment by Jguer** [comment]
Hey @izzy8799 , normally `sudoloop` only supports `sudo`, I'm not sure pkexec supports this mechanism
