### ISSUE TITLE
Not preserving of installation reasons when package is reinstalled

### ISSUE THREAD

**Issue by smolx** [Jguer/yay#2164]
### Affected Version

`yay v12.0.4.r23.gec15a5b - libalpm v13.0.2`

### Describe the bug

Yay doesn't preserve the installation reason of reinstalled package. As said in [pacman wiki](https://wiki.archlinux.org/title/Pacman#Installation_reason), "when reinstalling a package, the current installation reason is preserved by default".
This unexpected behavior is present for at least AUR and Repo packages.

### Reproduction Steps And Output

```sh
$ yay -S --asdeps autojump
...
$ yay -Qi autojump | grep Reason
Install Reason  : Installed as a dependency for another package
$ yay -S autojump
...
$ yay -Qi autojump | grep Reason
Install Reason  : Explicitly installed
```

### Expected behavior

Install reason is preserved.

**Comment by Jguer** [comment]
That's a fair point, there's no explicit contract of having the same behavior but it would make sense to do it. It should not be very hard to have it during graphing

**Comment by drws** [comment]
This is possibly related to #2167.

**Comment by smolx** [comment]
@Jguer Do you mind if I try to find a solution to this issue?

**Comment by Jguer** [comment]
:+1: Go ahead @smolx , I don't think it should add a lot of complexity. 

#2167 is more related to the `Install` being called even when the graph is empty
