### ISSUE TITLE
Is there a way to automatically install and uninstall "base-devel" for builds?

### ISSUE THREAD

**Issue by Delgan** [Jguer/yay#2172]
Hi.

I understand that the `base-devel` meta-package is an implicit dependency to build any AUR package.

However, it contains several packages that I don't use except during `yay` builds. After an AUR installation, I always choose to remove the "make" dependencies, but this obviously does not remove the pre-required packages present in `base-devel`.

I would like to know if there exists a workaround to automatically install `base-devel` and automatically uninstall it after using `yay`? Or maybe some kind of custom hook?

**Comment by AladW** [comment]
You can write a trivial wrapper:
```
pacman -S base-devel
yay "$@"
pacman -R base-devel
```

**Comment by Delgan** [comment]
Thanks for the suggested workaround @AladW!

Using a bash wrapper is indeed a viable solution.
Unfortunately, it has some drawbacks, like obfuscating output of `--help` because of unnecessary `pacman` steps, and breaking auto-completion feature. 

It makes sense to me to optionally treat `base-devel` as the rest of a package's explicit build dependencies, but if it doesn't to you, then that's fine, feel free to close this ticket. :+1:
Otherwise, I could work on a PR.

**Comment by Jguer** [comment]
I think this does not fit with the project for a few reasons: 

1. the AUR is pretty adamant on having base-devel installed. It would be bad to incentive behavior that removes it 
2. I can see the scenario where for some reason base-devel doesn't install and as such packages don't build and the user is not aware of why.
3. Probably most users won't clean their pkg cache after so they'll still have `base-devel` packages in their cache, not winning them a lot of space
4. If they clean their pkg cache, it would just be putting more pressure on mirrors to save users some sys space while being wasteful on data transfer (carbon footprint impact/mobile data users/...). 

I understand some integrated environments have indeed very limited storage and any optimization there helps but I don't think we should push this behavior for users.

I'm going to close this issue as won't implement but I welcome arguments on how this benefits users and the community.
