### ISSUE TITLE
yay uses the discontinued svn2git mirror

### ISSUE THREAD

**Issue by christian-heusel** [Jguer/yay#2176]
### Affected Version

```
yay v12.0.4 - libalpm v13.0.2
````

### Describe the bug

When using `yay -G` to obtain sources for a pkgbuild this uses the discontinued svn2git mirror still.

### Reproduction Steps

1. Try to obtain the latest source for `devtools`: `yay -G devtools`
2. change in the newly created folder
3. See that the pkgbuild is out of date since it is taken from svn2git:
    ```
    $ grep pkgver trunk/PKGBUILD
    pkgver=20230307
    ```

### Expected behavior

See the [announcement for the git migration](https://archlinux.org/news/git-migration-announcement/): 

> The svn2git mirror will no longer be updated.

Instead it is expected now that yay clones from `https://gitlab.archlinux.org/archlinux/packaging/packages/devtools.git` as described in the wiki: https://wiki.archlinux.org/title/Arch_build_system#Using_git_directly.

**Comment by moson-mo** [comment]
@Jguer You'd need to apply some regex magic on top of the pkgbase name to construct proper URL's.

See: https://gitlab.archlinux.org/archlinux/devtools/-/blob/6ce666a1669235749c17d5c44d8a24dea4a135da/src/lib/api/gitlab.sh#L95

This is what I'm doing: https://github.com/moson-mo/pacseek/blob/50aecf6de9bfa6ba321a564a57f7d57097caedec/internal/pacseek/pkgbuild.go#L18

For example, try: `yay -G mysql++` 😉

**Comment by Jguer** [comment]
I see, the implementaion was maybe too naive :joy:
I'll reimplement it probably with the regex substitution

**Comment by moson-mo** [comment]
> I'll reimplement it probably with the regex substitution

Filed a PR for this: https://github.com/Jguer/yay/pull/2191
