### ISSUE TITLE
Is yay supposed to respect MAKEFLAGS env var?

### ISSUE THREAD

**Issue by Simbi0z** [Jguer/yay#2192]
### Affected Version
yay v12.0.5 - libalpm v13.0.2

### Describe the bug

`export MAKEFLAGS="-j2"`
and then
`yay -Syu --devel`
yay does not respect the env variable, /etc/makepkg.conf var is not overridden.

### Expected behavior

compile with MAKEFLAGS="-jx" threads

edit1: I am compiling qt5-webkit btw.

**Comment by Jguer** [comment]
Hey @Simbi0z , does `makepkg` support it?

**Comment by Simbi0z** [comment]
> Hey @Simbi0z , does `makepkg` support it?

For anyone wondering: No.
https://man.archlinux.org/man/makepkg.8.en#ENVIRONMENT_VARIABLES
Anyhow, at least there is a `MAKEPKG_CONF="/path/to/file"` for overriding the whole  /etc/makepkg.conf  file.
