### ISSUE TITLE
no config.json file

### ISSUE THREAD

**Issue by mrsteve0924** [Jguer/yay#2213]
### Affected Version

yay v12.0.5 - libalpm v13.0.2

### Describe the bug

shouldnt the default config.json file be available after install?  I don't see it in $HOME/yay or $HOME/.config/yay

or does the file only get created after using  the  --save flag

**Comment by Jguer** [comment]
Hey @mrsteve0924 , the config.json only gets created by the user or by `--save`

**Comment by mrsteve0924** [comment]
OK @Jguer . thanks for the reply.
