### ISSUE TITLE
How to makepkg one-off aur packages in tmpfs?

### ISSUE THREAD

**Issue by playgithub** [Jguer/yay#2230]
e.g. 
```
$ ls ~/.cache/yay
completion.cache  vcs.json  vscodium-bin
```
Here `vscodium-bin` will only used once, so it's better to be in `tmpfs` to save ssd.
But `completion.cache` and `vcs.json` might be reused, so it's better to be on harddisk.

Anyway for `yay` to achive this?

**Comment by Jguer** [comment]
Hey, you should be able to set the `builddir` option in the config or using `yay ... --builddir <path>` 

```man
--builddir <dir>
              Directory to use for Building AUR Packages. This directory is also used as the
              AUR cache when deciding if Yay should skip builds.
```

**Comment by playgithub** [comment]
`yay --save --builddir <dir>` generates config in `~/.config/yay/config.json`
