### ISSUE TITLE
Cycled update yay -Syyuu

### ISSUE THREAD

**Issue by AvenCores** [Jguer/yay#2235]
### Affected Version

yay v12.1.0 - libalpm v13.0.2

### Describe the bug

When using yay -Syuu, this utility endlessly prompts to update two packages from aur, although with yay -Syuu everything is already clean.

![image](https://github.com/Jguer/yay/assets/64781822/0c9faccd-4799-4b4a-bfcd-675f2978667e)

### Reproduction Steps

1. yay -S meridius-bin-git captdriver-git
2. yay -Syyuu

### Expected behavior

It will give the same result as yay -Syu, i.e. no updates found.

### Output

[avencores@archlinux ~]$ yay -Syyuu
[DEBUG:runner] running /usr/bin/sudo pacman -S -y -y --config /etc/pacman.conf --
[sudo] пароль для avencores: 
:: Обновление баз данных пакетов...
 core                                                     132,5 KiB   182 KiB/s 00:01 [##################################################] 100%
 extra                                                      8,3 MiB  2,85 MiB/s 00:03 [##################################################] 100%
 multilib                                                 140,6 KiB   896 KiB/s 00:00 [##################################################] 100%
[DEBUG:db] populating db executor package caches. sync_len 895 remote_len 17
:: Поиск обновлений в AUR...
[DEBUG:runtime] packages to query [aic94xx-firmware captdriver-git google-chrome lib32-nvidia-390xx-utils libxnvctrl-390xx meridius-bin-git meteo-gtk minecraft-launcher nvidia-390xx-dkms nvidia-390xx-settings nvidia-390xx-utils upd72020x-fw video-downloader visual-studio-code-bin wd719x-firmware yay-bin zapzap]
[DEBUG:runtime] rpc request https://aur.archlinux.org/rpc?arg%5B%5D=aic94xx-firmware&arg%5B%5D=captdriver-git&arg%5B%5D=google-chrome&arg%5B%5D=lib32-nvidia-390xx-utils&arg%5B%5D=libxnvctrl-390xx&arg%5B%5D=meridius-bin-git&arg%5B%5D=meteo-gtk&arg%5B%5D=minecraft-launcher&arg%5B%5D=nvidia-390xx-dkms&arg%5B%5D=nvidia-390xx-settings&arg%5B%5D=nvidia-390xx-utils&arg%5B%5D=upd72020x-fw&arg%5B%5D=video-downloader&arg%5B%5D=visual-studio-code-bin&arg%5B%5D=wd719x-firmware&arg%5B%5D=yay-bin&arg%5B%5D=zapzap&type=info&v=5
[DEBUG:grapher] meridius-bin-git provides: meridius
:: Поиск обновлений в базе данных...
:: 2 dependencies will also be installed for this operation.
   extra/asar      -> 3.2.3-1
   (make dependency of meridius-bin-git)
   extra/gendesk   -> 1.0.9-3
   (make dependency of meridius-bin-git)

:: 2 packages to upgrade/install.
2  aur/captdriver-git    r170.6271924-1 -> r138.a3036a4-1
1  aur/meridius-bin-git  v3.0.5-1       -> v2.9.7-1
==> Пакеты для исключения: (пример: "1 2 3", "1-3", "^4" или имя в репозитории)
 -> Excluding packages may cause partial upgrades and break systems
==>

**Comment by jdholtz** [comment]
This is expected behavior. See `man pacman` for information on passing two `u`'s:

> Pass this option twice to enable package downgrades; in this case, pacman will select sync packages whose versions do not match with the local versions. This can be useful when the user switches from a testing repository to a stable one.

Because `-git` packages don't always have the latest commit version in their PKGBUILD, passing double `u` to yay will try to install the versions specified in the PKGBUILD (or the last version you installed before the latest if you have upgraded it previously).

For instance, you can see that the PKGBUILD in captdriver-git has version `r138.a3036a4` and the PKGBUILD in meridius-bin-git has version `v2.9.7`. Yay wants to downgrade the packages from the latest git commit to these versions (which follows the behavior specified in the pacman manpage).

Edit: See [this](https://github.com/Jguer/yay/issues/2059#issuecomment-1494998158) comment as well
