### ISSUE TITLE
When updating I get 'Packages not in AUR: (packages...)

### ISSUE THREAD

**Issue by gemini4545** [Jguer/yay#2236]
### Affected Version

yay -V
 `yay v12.0.4 - libalpm v13.0.2` 

### Describe the bug

 yay is giving me this warning every time I go to update:  
 -> Packages not in AUR: manjaro-documentation-en  manjaro-firmware  nerd-fonts-noto-sans-mono  noto-fonts-compat  python-pep517  systemd-fsck-silent

### Reproduction Steps

1. yay to update

### Expected behavior
Update the softwares

### Output
Packages not in AUR: manjaro-documentation-en  manjaro-firmware  nerd-fonts-noto-sans-mono  noto-fonts-compat  python-pep517  systemd-fsck-silent
<!-- the out put ->

**Comment by Jguer** [comment]
Hey @gemini4545 , those packages are not in the AUR and probably not in your repos anymore (did you disable the manjaro repositories?).

yay will not be able to update those packages if they're neither in your synced repositories neither in the AUR

**Comment by gemini4545** [comment]
> Hey @gemini4545 , those packages are not in the AUR and probably not in your repos anymore (did you disable the manjaro repositories?).
> 
> yay will not be able to update those packages if they're neither in your synced repositories neither in the AUR

Hey @Jguer , 
I didn't disable any manjaro repositores. (Almost a newly installed system that didn't update for a while)
If those packages were not in the AUR neither in my repos, how were they installed?
Or, were those packages installed long before and now removed from the AUR?  If so, can I remove them as while without any infulence to the system?
