### ISSUE TITLE
man page missing mflags

### ISSUE THREAD

**Issue by Richard-Payne** [Jguer/yay#2240]
### Affected Version
yay v12.0.4 - libalpm v13.0.2

### Describe the bug
re: https://github.com/Jguer/yay/issues/1858

It is stated that the man page only contains yay specific options, and hence, does not include the makepkg options.  This is fine, but the yay page makes no mention of the mflags at all.  Should the yay man page not have an entry for mflags that explains that it is used to pass arguments to makepkg?  

I notice that some of the examples use mflags, but there is no definition for it.

**Comment by Jguer** [comment]
Hey Richard, is there something missing in https://github.com/Jguer/yay/blob/next/doc/yay.8#L503 ?

**Comment by Richard-Payne** [comment]
No that seems reasonable.  It doesn't show up on the man page from the terminal though.
