### ISSUE TITLE
yay doesn't resolve makedeps soon enough

### ISSUE THREAD

**Issue by drws** [Jguer/yay#2252]
### Affected Version

yay v12.1.0 - libalpm v13.0.2

### Describe the bug

Trying to install the package [`linuxtv-dvb-apps`](https://aur.archlinux.org/packages/linuxtv-dvb-apps), which has a makedep [`mercurial`](https://archlinux.org/packages/extra/x86_64/mercurial/). This dependency provides a binary `hg`, needed to obtain the source packages.

During building Yay throws a strange error:

    ==> Retrieving sources...
      -> Cloning dvb-apps hg repo...
    /usr/share/makepkg/source/hg.sh: line 50: hg: command not found

After this error, the process continues, successfully builds the package and installs it.

### Reproduction Steps

1. `mercurial` shouldn't be installed before.
2. Install an affected package with: `yay -Syu linuxtv-dvb-apps`
3. Observe a seemingly show-stopping error and a successful build afterwards.

### Expected behavior

No error is produced.

**Comment by jdholtz** [comment]
This appears to be a duplicate of #2237 as they both fail while attempting to fetch sources using commands that are unavailable on the system prior to the attempt.

**Comment by drws** [comment]
Indeed. Thank you for reporting!
