### ISSUE TITLE
yay -Si missing lots of information

### ISSUE THREAD

**Issue by drws** [Jguer/yay#2255]
### Affected Version

yay v12.1.2 - libalpm v13.0.2

### Describe the bug

`yay -Si` displays repository-related package information (and is different from `yay -Qi`). However, it is lacking many information fields:

- `Architecture`
- `Package Base`
- `Replaces`
- `Required By`
- `Optional For`
- `Open Requests`

### Reproduction Steps

1. `yay -Si yay`

### Expected behavior

Output to include this very basic information.

**Comment by Jguer** [comment]
Hey @drws , we're limited by what the RPC returns here ex: https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=yay . You might want to check if a request already exists in https://gitlab.archlinux.org/archlinux/aurweb

**Comment by drws** [comment]
It [does now](https://gitlab.archlinux.org/archlinux/aurweb/-/issues/485). Also, `PackageBase` is already implemented. Please add it to `-Si`.

**Comment by Jguer** [comment]
`PackageBase` is not shown for repository packages ex:`yay -Si linux`. You can already have access to the `PackageBase` via ex:`yay -Sii yay`

**Comment by Jguer** [comment]
I went and searched a bit deeper as we do get some of this information already

https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=yay-bin

https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=linux-ck

- [ ] Architecture
- [x] Package Base
- [x] Replaces
- [ ] Required By
- [ ] Optional For
- [ ] Open Requests

`Package Base` and `Replaces` are already provided. 

`PackageBase` is show in -Sii (ex: `yay -Sii yay-bin`)

`Replaces` is missing from `-Si` (ex: linux-ck)

I don't think the RPC will be capable of returning `Required By` and `Optional For`. Maybe Architecture is the most glaring miss but there's probably some explanation for the omission as the info is available in `.SRCINFO`

**Comment by Jguer** [comment]
I'll add the missing `Replaces` to the AUR -Si
