### ISSUE TITLE
Dash '-' argument to read from stdin appears to be broken

### ISSUE THREAD

**Issue by zkrx** [Jguer/yay#2258]
### Affected Version

yay v12.1.2.r1.g7483393 - libalpm v13.0.2

### Describe the bug

The dash '-' argument to read from stdin appears to be broken. It yields, on first prompt:
`==>  -> read /dev/stdin: file already closed`

When upgrading my system, I rebuild all AUR packages to avoid issues with updated dynamic libraries. To do this, I've always used the following command which used to work:
`pacman -Qqm | yay -S -`

### Reproduction Steps

`echo zoom | yay -S -`

### Expected behavior

Yay should prompt user and proceed to update packages from stdin as usual.

### Output

```sh
[user@laptop ~]$ echo zoom | yay -S -
AUR Explicit (1): zoom-5.15.5-1
:: PKGBUILD up to date, skipping download: zoom
  1 zoom                                     (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>  -> read /dev/stdin: file already closed
```

**Comment by jdholtz** [comment]
I am not able to reproduce this issue with either command. I'm using the latest build from `yay-git` (yay v12.1.2.r2.g8916cd1 - libalpm v13.0.2). Could you try with the latest build and see if it works as you expect it to?

**Comment by zkrx** [comment]
Indeed, I am not able to reproduce with `yay-git`. Thanks and sorry for the noise.

**Comment by zkrx** [comment]
Indeed, I am not able to reproduce with yay-git. Thanks and sorry for the noise.
