### ISSUE TITLE
Option to always edit PKGBUILD

### ISSUE THREAD

**Issue by notramo** [Jguer/yay#226]
With this option provided, it wouldn't ask to edit, but open it in the editor. It should have an opposite option, that never asks, but skips editing. (e.g. `--edit`, `--noedit`).

**Comment by Morganamilo** [comment]
Number menus for editing should be coming soonish and will reduce the amount of keys you need to press. I'll wait for that feature to be added and see if you think this is still needed.

**Comment by Morganamilo** [comment]
The install process has changed to be less spammy with questions. I don't really see these flags being needed with how low hassle it should be to just hit enter once. Try it and tell me if you'd still want these flags.

**Comment by notramo** [comment]
The new install process is very cool, however I would like to skip the second (PKGBUILD editing) prompt with this flag (automatically answer `All`).

**Comment by Morganamilo** [comment]
Alright I'll see about passing a flag that answers for you.

**Comment by notramo** [comment]
What about predefining the answer with the command line option? This would allow to choose many answers.
E.g. `--editanswer All`, or `--editanswer NotInstalled`

**Comment by Morganamilo** [comment]
That's what I was thinking of. Wasn't sure whether to make it actually choose for you or set the default then you just hit enter. But hitting enter for you would probably be what most people want.

**Comment by notramo** [comment]
I think both could be choosed. If the command line flag contains a newline: `"NotInstalled\n"`, it should be automatically accepted, if not, it should be only set to default.

**Comment by samosaara** [comment]
IMHO still making the user still hit enter is pretty silly, the point of me setting a flag with default answer beforehand is to skip the question/automatize/minimize input. All the answers should be chosen for me given the command line flag preset.

**Comment by Morganamilo** [comment]
I guess that how it should be. I for sure didn't want to attach "\n" to the end because that's tedious. Just having it hit enter for you is probably the best way to do it. A new flag can always be added to toggle the enter hitting alongside the default answer if people want it.

**Comment by samosaara** [comment]
Oh wow, wait, you intend on implementing this the gnu-utils's `yes` way, instead of actually adapting the decision flow to be aware of the cmd-line flag and not ask for input?

**Comment by Morganamilo** [comment]
No I intend to make it read the flag if set rather than stdin. This allows options `all` `abort` `installed` to be passed just like how the user can enter manually. As a side effect this would allow users to enter numbers. I might explicitly disallow this but I do not know right now.

The mention of "\n" comes from https://github.com/Jguer/yay/issues/226#issuecomment-372474176

**Comment by AlexWayfer** [comment]
It'd ideal, if this option will appear in configuration file.

**Comment by Morganamilo** [comment]
You should be able to do `yay --answeredit all --save` to always edit pkgbuilds. `yay --noansweredit --save` to remove the answer. Mentioning it here because there's no documentation right now.
