### ISSUE TITLE
incremental compilation

### ISSUE THREAD

**Issue by faqin** [Jguer/yay#2261]
pacman -S  gcc11 --editmenu
replace "make" with  "make -j 8 "

but there is a error ：internal compiler error: Segmentation fault

I want build it again,How to incrementally compile instead of full recompile

**Comment by Jguer** [comment]
Hey @faqin, `pacman` does not support `--editmenu` or recompiling sync packages.

You can check https://wiki.archlinux.org/title/Arch_build_system#Usage to familiarize how to recompile sync packages
