### ISSUE TITLE
can't install yay

### ISSUE THREAD

**Issue by dcihon** [Jguer/yay#2275]
### Affected Version

yay-12.1.2.tar.gz

### Describe the bug

`[demo@archlinux yay]$ makepkg -si
==> Making package: yay 12.1.2-1 (Sun 10 Sep 2023 08:20:34 AM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found yay-12.1.2.tar.gz
==> Validating source files with sha256sums...
    yay-12.1.2.tar.gz ... Passed
==> Extracting sources...
  -> Extracting yay-12.1.2.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
go build -trimpath -mod=readonly -modcacherw  -ldflags '-X "main.yayVersion=12.1.2" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay
go: downloading github.com/Jguer/aur v1.2.3
go: downloading github.com/Jguer/votar v1.0.0
go: downloading github.com/Jguer/go-alpm/v2 v2.2.1
go: downloading github.com/Morganamilo/go-srcinfo v1.0.0
go: downloading github.com/deckarep/golang-set/v2 v2.3.0
go: downloading github.com/leonelquinteros/gotext v1.5.2
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/Morganamilo/go-pacmanconf v0.0.0-20210502114700-cff030e927a5
go: downloading github.com/adrg/strutil v0.3.0
go: downloading github.com/hashicorp/go-multierror v1.1.1
go: downloading golang.org/x/term v0.10.0
go: downloading golang.org/x/sys v0.10.0
clean.go:9:2: github.com/Jguer/aur@v1.2.3: Get "https://proxy.golang.org/github.com/%21jguer/aur/@v/v1.2.3.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:39348->[::1]:53: read: connection refused
cmd.go:11:2: github.com/Jguer/go-alpm/v2@v2.2.1: Get "https://proxy.golang.org/github.com/%21jguer/go-alpm/v2/@v/v2.2.1.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:39348->[::1]:53: read: connection refused
vote.go:9:2: github.com/Jguer/votar@v1.0.0: Get "https://proxy.golang.org/github.com/%21jguer/votar/@v/v1.0.0.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:39348->[::1]:53: read: connection refused
pkg/text/errors.go:3:8: github.com/leonelquinteros/gotext@v1.5.2: Get "https://proxy.golang.org/github.com/leonelquinteros/gotext/@v/v1.5.2.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:39368->[::1]:53: read: connection refused
pkg/text/print.go:12:2: golang.org/x/sys@v0.10.0: Get "https://proxy.golang.org/golang.org/x/sys/@v/v0.10.0.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:40141->[::1]:53: read: connection refused
pkg/settings/runtime.go:20:2: github.com/Jguer/aur@v1.2.3: Get "https://proxy.golang.org/github.com/%21jguer/aur/@v/v1.2.3.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:39348->[::1]:53: read: connection refused
pkg/settings/runtime.go:21:2: github.com/Jguer/aur@v1.2.3: Get "https://proxy.golang.org/github.com/%21jguer/aur/@v/v1.2.3.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:39348->[::1]:53: read: connection refused
pkg/intrange/intrange.go:8:2: github.com/deckarep/golang-set/v2@v2.3.0: Get "https://proxy.golang.org/github.com/deckarep/golang-set/v2/@v/v2.3.0.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:39368->[::1]:53: read: connection refused
pkg/query/metric.go:7:2: github.com/adrg/strutil@v0.3.0: Get "https://proxy.golang.org/github.com/adrg/strutil/@v/v0.3.0.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:49987->[::1]:53: read: connection refused
pkg/query/query_builder.go:13:2: github.com/adrg/strutil@v0.3.0: Get "https://proxy.golang.org/github.com/adrg/strutil/@v/v0.3.0.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:49987->[::1]:53: read: connection refused
pkg/query/source.go:7:2: github.com/hashicorp/go-multierror@v1.1.1: Get "https://proxy.golang.org/github.com/hashicorp/go-multierror/@v/v1.1.1.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:49987->[::1]:53: read: connection refused
pkg/vcs/mock.go:7:2: github.com/Morganamilo/go-srcinfo@v1.0.0: Get "https://proxy.golang.org/github.com/%21morganamilo/go-srcinfo/@v/v1.0.0.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:39368->[::1]:53: read: connection refused
pkg/settings/pacman.go:9:2: github.com/Morganamilo/go-pacmanconf@v0.0.0-20210502114700-cff030e927a5: Get "https://proxy.golang.org/github.com/%21morganamilo/go-pacmanconf/@v/v0.0.0-20210502114700-cff030e927a5.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:41295->[::1]:53: read: connection refused
pkg/settings/pacman.go:10:2: golang.org/x/term@v0.10.0: Get "https://proxy.golang.org/golang.org/x/term/@v/v0.10.0.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:50826->[::1]:53: read: connection refused
local_install.go:21:2: github.com/pkg/errors@v0.9.1: Get "https://proxy.golang.org/github.com/pkg/errors/@v/v0.9.1.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:39368->[::1]:53: read: connection refused
make: *** [Makefile:117: yay] Error 1
==> ERROR: A failure occurred in build().
    Aborting...`

### Reproduction Steps

1. makepkg -si
2.
3.

### Expected behavior

yay gets installed

### Output
see above

```sh

```

**Comment by Jguer** [comment]
closing as duplicate https://github.com/Jguer/yay/issues/2262
