### ISSUE TITLE
Update yay to version 12.1.3 fails with connection refused errors

### ISSUE THREAD

**Issue by Rumbah2** [Jguer/yay#2281]
### Affected Version
yay v12.1.2 - libalpm v13.0.2

### Describe the bug

When I try to update yay from v12.1.2 to 12.1.3 on arch linux with yay I get an error message and the update fails. Some links seem to be wrong (connection refused).

### Reproduction Steps

1. on Arch Linux use: yay -Syu to update yay to 12.1.3
2. I get the error "Fehler beim Erstellen: yay-exit status 4" (error on creation: yay-exit status 4)

### Expected behavior

Yay gets updated

### Output

yay -Syu
:: Paketdatenbanken werden synchronisiert …
 core ist aktuell
 extra ist aktuell
 community ist aktuell
:: Durchsuche AUR nach Updates...
:: Durchsuche Datenbanken nach Updates...
:: 1 package to upgrade/install.
1  aur/yay  12.1.2-1 -> 12.1.3-1
==> Pakete zum Ausschließen: (z.B. "1 2 3", "1-3", "^4" oder Repo-Name)
 -> Das Ausschließen von Paketen kann zu teilweisen Aktualisierungen führen und Systeme beschädigen.
==>
AUR Explicit (1): yay-12.1.3-1
:: PKGBUILD ist auf dem neuesten Stand, überspringe Herunterladen: yay
  1 yay                                      (Installiert) (Build-Dateien sind vorhanden)
==> Pakete für neuen Build?
==> [N] Keine [A]lle [Ab]brechen [I]nstalliert [No]nicht installiert oder (1 2 3, 1-3, ^4)
==>
  1 yay                                      (Installiert) (Build-Dateien sind vorhanden)
==> Unterschiede zeigen?
==> [N] Keine [A]lle [Ab]brechen [I]nstalliert [No]nicht installiert oder (1 2 3, 1-3, ^4)
==>
==> Erstelle Paket: yay 12.1.3-1 (Fr 15 Sep 2023 17:47:20 CEST)
==> Empfange Quellen...
  -> yay-12.1.3.tar.gz gefunden
==> WARNUNG: Überspringe Überprüfung der PGP-Signaturen der Quell-Dateien.
==> Überprüfe source Dateien mit sha256sums...
    yay-12.1.3.tar.gz ... Erfolg
:: (1/1) SRCINFO geparst: yay
==> Erstelle Paket: yay 12.1.3-1 (Fr 15 Sep 2023 17:47:23 CEST)
==> Prüfe Laufzeit-Abhängigkeiten...
==> Prüfe Buildtime-Abhängigkeiten...
==> Empfange Quellen...
  -> yay-12.1.3.tar.gz gefunden
==> Überprüfe source Dateien mit sha256sums...
    yay-12.1.3.tar.gz ... Erfolg
==> Entferne existierendes $srcdir/ Verzeichnis...
==> Entpacke Quellen...
  -> Entpacke yay-12.1.3.tar.gz mit bsdtar
==> Quellen sind fertig.
==> Erstelle Paket: yay 12.1.3-1 (Fr 15 Sep 2023 17:47:28 CEST)
==> Prüfe Laufzeit-Abhängigkeiten...
==> Prüfe Buildtime-Abhängigkeiten...
==> WARNUNG: Verwende bestehenden $srcdir/ Baum
==> Entferne existierendes $pkgdir/ Verzeichnis...
==> Beginne build()...
go build -trimpath -mod=readonly -modcacherw  -ldflags '-X "main.yayVersion=12.1.3" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay
go: downloading github.com/Jguer/aur v1.2.3
go: downloading github.com/Jguer/votar v1.0.0
go: downloading github.com/Jguer/go-alpm/v2 v2.2.1
go: downloading github.com/Morganamilo/go-srcinfo v1.0.0
go: downloading github.com/leonelquinteros/gotext v1.5.2
go: downloading github.com/deckarep/golang-set/v2 v2.3.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading golang.org/x/sys v0.10.0
go: downloading github.com/Morganamilo/go-pacmanconf v0.0.0-20210502114700-cff030e927a5
go: downloading github.com/adrg/strutil v0.3.0
go: downloading github.com/hashicorp/go-multierror v1.1.1
go: downloading golang.org/x/term v0.10.0
clean.go:8:2: github.com/Jguer/aur@v1.2.3: Get "https://proxy.golang.org/github.com/%21jguer/aur/@v/v1.2.3.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:43595->[::1]:53: read: connection refused
cmd.go:11:2: github.com/Jguer/go-alpm/v2@v2.2.1: Get "https://proxy.golang.org/github.com/%21jguer/go-alpm/v2/@v/v2.2.1.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:43595->[::1]:53: read: connection refused
vote.go:8:2: github.com/Jguer/votar@v1.0.0: Get "https://proxy.golang.org/github.com/%21jguer/votar/@v/v1.0.0.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:43595->[::1]:53: read: connection refused
pkg/text/errors.go:3:8: github.com/leonelquinteros/gotext@v1.5.2: Get "https://proxy.golang.org/github.com/leonelquinteros/gotext/@v/v1.5.2.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:58909->[::1]:53: read: connection refused
pkg/db/ialpm/alpm.go:11:2: github.com/Morganamilo/go-pacmanconf@v0.0.0-20210502114700-cff030e927a5: Get "https://proxy.golang.org/github.com/%21morganamilo/go-pacmanconf/@v/v0.0.0-20210502114700-cff030e927a5.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:54706->[::1]:53: read: connection refused
pkg/intrange/intrange.go:8:2: github.com/deckarep/golang-set/v2@v2.3.0: Get "https://proxy.golang.org/github.com/deckarep/golang-set/v2/@v/v2.3.0.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:58909->[::1]:53: read: connection refused
pkg/query/metric.go:7:2: github.com/adrg/strutil@v0.3.0: Get "https://proxy.golang.org/github.com/adrg/strutil/@v/v0.3.0.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:54706->[::1]:53: read: connection refused
pkg/query/query_builder.go:13:2: github.com/adrg/strutil@v0.3.0: Get "https://proxy.golang.org/github.com/adrg/strutil/@v/v0.3.0.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:54706->[::1]:53: read: connection refused
pkg/query/source.go:7:2: github.com/hashicorp/go-multierror@v1.1.1: Get "https://proxy.golang.org/github.com/hashicorp/go-multierror/@v/v1.1.1.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:40780->[::1]:53: read: connection refused
pkg/dep/dep_graph.go:10:2: github.com/Morganamilo/go-srcinfo@v1.0.0: Get "https://proxy.golang.org/github.com/%21morganamilo/go-srcinfo/@v/v1.0.0.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:58909->[::1]:53: read: connection refused
pkg/runtime/runtime.go:20:2: github.com/Jguer/aur@v1.2.3: Get "https://proxy.golang.org/github.com/%21jguer/aur/@v/v1.2.3.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:43595->[::1]:53: read: connection refused
pkg/runtime/runtime.go:21:2: github.com/Jguer/aur@v1.2.3: Get "https://proxy.golang.org/github.com/%21jguer/aur/@v/v1.2.3.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:43595->[::1]:53: read: connection refused
pkg/runtime/pacman.go:10:2: golang.org/x/term@v0.10.0: Get "https://proxy.golang.org/golang.org/x/term/@v/v0.10.0.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:40780->[::1]:53: read: connection refused
local_install.go:23:2: github.com/pkg/errors@v0.9.1: Get "https://proxy.golang.org/github.com/pkg/errors/@v/v0.9.1.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:58909->[::1]:53: read: connection refused
print.go:16:2: golang.org/x/sys@v0.10.0: Get "https://proxy.golang.org/golang.org/x/sys/@v/v0.10.0.zip": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:52833->[::1]:53: read: connection refused
make: *** [Makefile:117: yay] Fehler 1
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
 -> Fehler beim Erstellen: yay-exit status 4
 -> Die folgenden Pakete konnten nicht installiert werden. Ein manueller Eingriff ist erforderlich:
yay - exit status 4

**Comment by danao81** [comment]
Same here!

**Comment by Jguer** [comment]
Duplicate of https://github.com/Jguer/yay/issues/2262

This is normally a DNS issue.

`yay-bin` should still install correctly even without DNS/GOPROXY fixed.

```sh
pacman -S --needed git base-devel
git clone https://aur.archlinux.org/yay-bin.git
cd yay-bin
makepkg -si
```
