### ISSUE TITLE
yay keeps prompting me to update git packages. But they're already built from the latest commit from master

### ISSUE THREAD

**Issue by awsms** [Jguer/yay#2286]
### Affected Version

yay v12.1.3.r2.g299aa1e - libalpm v13.0.2

### Describe the bug

Everytime I run yay -Syu, I'll be presented with packages to update (to name them: rpcs3-git, btop-git, dolphin-emu-git and many others) that have already been compiled from the latest commit on master. Note that yay won't always prompt me with the same packages, it's random really.
I've been experiencing this issue for a week now. I didn't really pay attention at first, but when I keep seeing the same packages being updated over and over again, with "warning: package_name already made -- skipping build" at the end of the prompt.
So I checked the said-programs repos, and noticed there hasn't been new commits for days at the time of updating.

### Reproduction Steps

1. Install a -git package, btop-git for ex
2. Once installed, if I run yay again, I'll be prompted to update the package

### Expected behavior

Programs compiled from latest-commit shouldn't appear at all

### Output

https://paste.ec/paste/4sF889MX#8NCC1ZA9jilGuaTSkKWM2BO0pTtNb8iSatjFMByNPe4

```sh
{
	"aururl": "https://aur.archlinux.org",
	"aurrpcurl": "https://aur.archlinux.org/rpc?",
	"buildDir": "/home/me/.cache/yay",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"version": "12.1.2",
	"requestsplitn": 150,
	"completionrefreshtime": 7,
	"maxconcurrentdownloads": 0,
	"bottomup": true,
	"sudoloop": false,
	"timeupdate": false,
	"devel": true,
	"cleanAfter": false,
	"keepSrc": false,
	"provides": true,
	"pgpfetch": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": true,
	"useask": false,
	"batchinstall": false,
	"singlelineresults": false,
	"separatesources": true,
	"debug": false,
	"rpc": true,
	"doubleconfirm": true,
	"rebuild": "no"
}

```

**Comment by awsms** [comment]
https://github.com/Morganamilo/paru/issues/674#issuecomment-1036257646

It's caused by poorly maintained packages. Not sure if something could be done about it.

**Comment by xiota** [comment]
> It's caused by poorly maintained packages. Not sure if something could be done about it.

Inform maintainers of affected packages that `.SRCINFO` should *not* be manually edited, but generated with command:
```bash
makepkg --printsrcinfo > .SRCINFO
```
