### ISSUE TITLE
Undeleted cache

### ISSUE THREAD

**Issue by owochle** [Jguer/yay#2295]
### Affected Version
yay v12.1.3 - libalpm v13.0.2

### Describe the bug
![image](https://github.com/Jguer/yay/assets/62758885/1a37fe2f-8257-4146-8e62-3068b4efa259)

### Reproduction Steps
I'm not sure how it happened, but it happened, most probably like this :
1. Download a bunch of thing (most probably sources needing compile)
2. See the cache fill up and never clear 

### Expected behavior
For the cache to be emptied regularly, or if it's a disabled by default option, maybe enable it by default.

**Comment by Jguer** [comment]
`yay -Scc` cleans the cache

`--cleanafter` can also be used to remove untracked files after install

`--save` can be used to make cleanafter permanent or you can edit your config.json to include

```json
"cleanafter": true
```
