### ISSUE TITLE
Dep added to community 

### ISSUE THREAD

**Issue by Morganamilo** [Jguer/yay#232]
Dep has (or is soon to be) moved from the AUR and into community. Do you have any plans or changes because of this?

It should be possible to remove `vendor/, add dep as a dependency to the pkgbuild and do the dependency fetching there. I tend to prefer this because it keeps our repo cleaner and removes stuff that does not need to be in there.

**Comment by Jguer** [comment]
I have tried `godep` from the repos, everything as expected but I think it breaks the promise of yay to add a new dependency like this. 

I don't like the current solution, the code in vendor doesn't belong here and I think git submodules could be a solution in our particular case.

On the other hand, I know the people using `yay` and not `yay-bin` are probably go developers who don't mind having huge behemoth that is the go compiler installed and probably `godep` as a make dependency as well.

 I'm divided on this, what we have currently works (and the build time is much shorter on pkgbuild I think). I would like another opinion on this before adding a new make dep.

**Comment by Morganamilo** [comment]
You're using `dep` to manage the dependencies right? `godep` is depreciated. Names are similar I know but I did mean just `dep` is now in the official repos when it was previously only in the AUR.

**Comment by Jguer** [comment]
*`golang-dep` in the aur , `community/dep`

**Comment by Morganamilo** [comment]
Ah okay. I thought the avoidance of dependencies was only for non repo dependencies. I guess this doesn't change anything then. closing.
