### ISSUE TITLE
avoid multiple executions of makepkg for the same PKGBUILD

### ISSUE THREAD

**Issue by linuxmetel** [Jguer/yay#2340]
### Is your feature request related to a problem? Please describe.

I wanted to install some themes for GRUB, so I tried installing packages in [grub-themes-git](https://aur.archlinux.org/pkgbase/grub-themes-git) from AUR.

```bash
$ yay -S `cat grub-themes-git-package-list`
```

However, this command seems to do like this for the 57 package (I translated from Japanese so there may be different from the original version):

```
==> Making package: grub-themes-git 2022.10.30.r35.g000171d-1 (09/01/2024 01:03:04)
==> Checking the runtime's dependencies...
==> Checking the dependencies in the building time...
==> Retrieving the source...
  -> Syncing grub2-themes git repo...
==> Validating sources file with sha256sums...
    grub2-themes ... skipped
==> Deleting the existing $srcdir/ directory...
==> Expanding the source...
  -> Copying grub2-themes git for building...
Cloning into 'grub2-themes'...
done.
==> Starting pkgver()...
==> Prepared the source
 -> grub-themes-git-2022.10.30.r35.g000171d-1 has already existed -- Skipping to build
```

Each process took a lot, and the sum reached hours on my machine.

### Describe the solution you'd like

I think that yay command should skip preparing and building process for the packages whose PKGBUILD has been executed (in the same yay command's execution). In other words, I think that one PKGBUILD should be executed just once in single yay command's execution.

And also it may be a radical solution to implement the functionality for installing by pkgbase.

**Comment by Ferdi265** [comment]
I'm currently hitting this with `ttf-ms-win11-auto`. updating takes very long since each subpackage is built every time.

Since I've contributed to yay before, I can try to patch yay to fix this and see if there is an easy/obvious solution to this.

**Comment by Ferdi265** [comment]
My fix PR seems to work pretty well with `ttf-ms-win11-auto`, build times are reduced by a lot. I also tested the package @linuxmetel  had the original issue with:

> ```
> $ yay -S `cat grub-themes-git-package-list`
> ```

This runs in under 9 minutes on my machine now.
