### ISSUE TITLE
ERROR: Unknown download protocol: git

### ISSUE THREAD

**Issue by Troublemaker114112** [Jguer/yay#2342]
### Affected Version

yay v12.2.0 - libalpm v13.0.2
git version 2.43.0

### Describe the bug

After I reinstalled Git, Git can run normally, but I found the following error when using Yay：
==> ERROR: Unknown download protocol: git

### Reproduction Steps
yay -S xxx

### Output

-->

```sh
==> Making package: delta 20060803-3 (Fri 19 Jan 2024 01:46:36 PM CST)
==> Retrieving sources...
==> ERROR: Unknown download protocol: git
    Aborting...
 -> error downloading sources: /home/mi/.cache/yay/delta
         context: exit status 1


:: (1/1) Parsing SRCINFO: delta
==> Making package: delta 20060803-3 (Fri 19 Jan 2024 01:46:37 PM CST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
==> ERROR: Unknown download protocol: git
    Aborting...
 -> error making: delta-exit status 1
 -> Failed to install the following packages. Manual intervention is required:
delta - exit status 1

```

**Comment by jdholtz** [comment]
I am not able to reproduce this on `yay v12.2.0.r1.g643830f - libalpm v13.0.2` with the same git version (I am using the `yay-git` AUR package). If you try yay-git, is this issue still reproducible? Also, the PKGBUILD for delta fails in build() (even using just makepkg).

**Comment by Troublemaker114112** [comment]
The issue still reproducible when I used the yay-git。 Additionally, I encounter this problem when using yay to download any AUR package.

==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
==> Making package: lightdm-elephant-greeter-git r12.bfa6ea4-1 (Mon 22 Jan 2024 02:46:36 PM CST)
==> Retrieving sources...
==> ERROR: Unknown download protocol: git
    Aborting...
 -> error downloading sources: /home/mi/.cache/yay/lightdm-elephant-greeter-git
         context: exit status 1


:: (1/1) Parsing SRCINFO: lightdm-elephant-greeter-git
resolving dependencies...
looking for conflicting packages...

**Comment by jdholtz** [comment]
If you download the PKGBUILD manually and run `makepkg -si`, does the package build correctly or do you get the same error?

**Comment by clsty** [comment]
This sounds more likely a broken makepkg config.

You'd better check out the following files:
- `/etc/makepkg.conf` , and find `VCSCLIENTS` in it.
- `/usr/share/makepkg/source/git.sh` and search `git` in it.

Or, try to install `base-devel` with pacman again.

**Comment by Troublemaker114112** [comment]
It is indeed the issue，I  lose /usr/share/makepkg/source/git.sh.
Now, I have resolved the problem by reinstalling Pacman using the command 'sudo pacman -S pacman.' Thank you.

**Comment by Troublemaker114112** [comment]
It is indeed the issue，I lose /usr/share/makepkg/source/git.sh.
Now, I have resolved the problem by reinstalling Pacman using the command 'sudo pacman -S pacman.' Thank you.
