### ISSUE TITLE
[docs] add --noconfirm option to manpages

### ISSUE THREAD

**Issue by mb6ockatf** [Jguer/yay#2343]
### Affected Version
`yay v12.2.0.r5.gb81d34d - libalpm v13.0.2`

### Describe the bug

no mention of this flag in man pages; https://github.com/Jguer/yay/issues/1033#issuecomment-1860397521

### Reproduction Steps

```bash
man yay
```

**Comment by jdholtz** [comment]
The `--noconfirm` flag is also part of Pacman and Pacman flags are only in Yay's manpage if it has extended functionality within Yay. Is there a description you want to see in the manpage that isn't already in Pacman's manpage?

The flag in Pacman's manpage:
```
--noconfirm
           Bypass any and all “Are you sure?” messages. It’s not a good idea to 
           do this unless you want to run pacman from a script.
```

**Comment by mb6ockatf** [comment]
oh, now it's clear

**Comment by 3xploiton3** [comment]
![image](https://github.com/Jguer/yay/assets/19517680/df4b962e-32b3-4a6b-8d68-8215561936ec)

**Comment by jdholtz** [comment]
@3xploiton3 the noconfirm flag is in the Pacman manpage, not the Yay manpage. See my comment [here](https://github.com/Jguer/yay/issues/2343#issuecomment-1902513166).
