### ISSUE TITLE
Can I run --gendb after using yay for a long time?

### ISSUE THREAD

**Issue by Rafi1018** [Jguer/yay#2345]
It seems yay recommends to run these commands after installing it which I didn't noticed & have used yay alot. So should I run these 3 commands now or just use it like I use ?
[These are the commands is I'm talking about](https://github.com/Jguer/yay?tab=readme-ov-file#development-packages-upgrade)

TIA

**Comment by Jguer** [comment]
You can continue using yay as is. The entries are also generated on installing the package in question.

If you think there's some git packages that you haven't updated since you installed yay you can run your normal devel update (yay -Syu --devel) and then run cache generation.
