### ISSUE TITLE
"Missing dependencies: jdk17-openjdk" for `makedepends=('jdk17-openjdk'` despite `makepkg -s` building just fine?

### ISSUE THREAD

**Issue by ipaqmaster** [Jguer/yay#2369]
### Affected Version

yay v12.2.0.r18.gaa6cad7 - libalpm v13.0.2

### Describe the bug

Recently an AUR package I maintain (elasticsearch) has started causing problems for others. It seems AUR helpers are unable to resolve `jdk17-openjdk`. Though, `makepkg -s` resolves it just fine and builds the project.

This has been tested in a docker container with a new rootfs for a true clean build. `makepkg -s` has no trouble resolving both the make and regular dependencies but `yay` for example throws:

```
==> Making package: elasticsearch 8.12.1-1 (Fri Feb  9 19:17:35 2024)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Missing dependencies:
  -> jdk17-openjdk
==> ERROR: Could not resolve all dependencies.
 -> error making: elasticsearch-exit status 8
 -> Failed to install the following packages. Manual intervention is required:
elasticsearch - exit status 8
```

I've had no luck troubleshooting for a few nights now trying to determine exactly what the issue is and would appreciate any advise. Using `--debug` reveals it's this call: `makepkg --nobuild -f -C --ignorearch` causing the error to appear (Explicitly the `makepkg --nobuild` part) but I don't follow why the package experiences build problems with these helpers but not when its asked to deal with packages itself.

### Reproduction Steps

1. Install yay from source, pkgbuild or from a build repository
2. `yes "$(echo)" | yay -aS elasticsearch` (Brutal quick example, regular yay calls also experience this problem)
3. Get output thrown above while it looks for dependencies.

### Expected behavior

jdk17-openjdk to install for the build and the package sources to start downloading before gradle builds the software. This all happens just fine when `cd ~/.cache/yay/elasticsearch` then `makepkg -s` are called.

### Output

<As per larger snippet above>

```sh

```

**Comment by ipaqmaster** [comment]
This seems to have repaired via other means. `makepkg --nobuild` (And what `yay ` calls: `makepkg --nobuild -f -C --ignorearch`) no longer causes the error cited. Something somewhere in some package must have gotten fixed over the weeks.

**Comment by 4norak** [comment]
Still happens for me. I manually added `-s` to the `mflags` and that seems to do the trick but without it, the build fails with `Missing dependencies: jdk17-openjdk`
