### ISSUE TITLE
/usr/share/makepkg/tidy/strip.sh: line 48: debugedit: not found command

### ISSUE THREAD

**Issue by haowaiwai** [Jguer/yay#2370]
### Affected Version

yay v12.2.0 - libalpm v13.0.2

### Describe the bug

/usr/share/makepkg/tidy/strip.sh: 行 48: debugedit: 未找到命令

### Reproduction Steps

yay

### Expected behavior

update visual-studio-code-bin 1.86.1-1

### Output

==> 正在清理安装...
  -> 正在删除 libtool 文件...
  -> 正在清除不打算要的文件...
  -> 正在移除静态库文件...
  -> 正在从二进制文件和库中清除不需要的系统符号...
/usr/share/makepkg/tidy/strip.sh: 行 48: debugedit: 未找到命令

**Comment by Jguer** [comment]
Hey @haowaiwai , this seems to be an issue with your `/etc/makepkg.conf` (maybe an extra option in `OPTIONS`)

**Comment by AckslD** [comment]
I had the same issue yesterday and installed `debugedit` to solve it but not sure why it wasn't pulled in as a dependency.
