### ISSUE TITLE
Compiling issue on Arch32

### ISSUE THREAD

**Issue by coreybruce** [Jguer/yay#2378]
### Affected Version

yay 12.3.0-1

### Describe the bug

Fails to build
```
go build -trimpath -mod=readonly -modcacherw  -ldflags '-X "main.yayVersion=12.0.0" -X "main.localePath=/usr/local/share/locale/" -linkmode=external' -buildmode=pie -o yay
go: errors parsing go.mod:
/home/corey/yay-12.3.0/go.mod:43: unknown directive: toolchain
make: *** [Makefile:117: yay] Error 1
```

12.2.0 works but after the update it broke for me on Arch32

**Comment by Jguer** [comment]
Hey @coreybruce , what's the output of `go version`? seems you might have an old version of the go compiler

**Comment by MarcPlace** [comment]
Can also confirm the same issue on my system running Archlinux32. 
`[root@lms ~]# go version`
`go version go1.20.7 linux/386`
Unfortunately there is no newer version in Archlinux32 repository available yet.

**Comment by coreybruce** [comment]
I have version go1.20.7, I assume it's a version behind on the requirements of the current version?

**Comment by MrCapone** [comment]
@coreybruce as temporary solution you can install precompiled yay-bin.

**Comment by coreybruce** [comment]
> yay-bin

Unfortunately yay-bin only supplies binaries for 'x86_64' 'aarch64' 'armv7h'

the temporary solution I did was download the last version of the pkgbuild file 12.2.0 and built the package with ```makepkg -i```

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=yay&id=e8811123596419ca2f3c2135b0ff7807ab94eb3b

**Comment by MrCapone** [comment]
In PKGBUILD we have
makedepends=('go>=1.19')
so 1.20.7 should be completely enough

**Comment by MarcPlace** [comment]
> In PKGBUILD we have makedepends=('go>=1.19') so 1.20.7 should be completely enough

The problem seems to be in "go.mod" as stated above. Changing line 41 to "go 1.20" and removing line 43 ("toolchain go1.21.6") completely did the trick also for me. Compiles now successfully on Archlinux32.

**Comment by hjpotter92** [comment]
I'm on amd64; and facing the same issue:
```
┌┤✅├─┤ hjpotter92 ├─┤~/./y/yay├─┤ 🕡 06:19 PM │
└┴─ ⚡[▶▶▶▶▶▶▶▶▶▶] ┴─ ➜ pwd
/home/hjpotter92/.cache/yay/yay

┌┤✅├─┤ hjpotter92 ├─┤~/./y/yay├─┤ 🕡 06:21 PM │
└┴─ ⚡[▶▶▶▶▶▶▶▶▶▶] ┴─ ➜ go version
Alias tip: gove
go version go1.22.0 linux/amd64

┌┤✅├─┤ hjpotter92 ├─┤~/./y/yay├─┤ 🕡 06:21 PM │
└┴─ ⚡[▶▶▶▶▶▶▶▶▶▶] ┴─ ➜ makepkg -si
==> Making package: yay 12.3.0-1 (Friday 01 March 2024 06:21:24 PM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found yay-12.3.0.tar.gz
==> Validating source files with sha256sums...
    yay-12.3.0.tar.gz ... Passed
==> Extracting sources...
  -> Extracting yay-12.3.0.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
go build -trimpath -mod=readonly -modcacherw  -ldflags '-X "main.yayVersion=12.3.0" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay
go: errors parsing go.mod:
/home/hjpotter92/.cache/yay/yay/src/yay-12.3.0/go.mod:43: unknown directive: toolchain
make: *** [Makefile:117: yay] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by coreybruce** [comment]
> I'm on amd64; and facing the same issue:
> 
> ```
> ┌┤✅├─┤ hjpotter92 ├─┤~/./y/yay├─┤ 🕡 06:19 PM │
> └┴─ ⚡[▶▶▶▶▶▶▶▶▶▶] ┴─ ➜ pwd
> /home/hjpotter92/.cache/yay/yay
> ┌┤✅├─┤ hjpotter92 ├─┤~/./y/yay├─┤ 🕡 06:21 PM │
> └┴─ ⚡[▶▶▶▶▶▶▶▶▶▶] ┴─ ➜ go version
> Alias tip: gove
> go version go1.22.0 linux/amd64
> ┌┤✅├─┤ hjpotter92 ├─┤~/./y/yay├─┤ 🕡 06:21 PM │
> └┴─ ⚡[▶▶▶▶▶▶▶▶▶▶] ┴─ ➜ makepkg -si
> ==> Making package: yay 12.3.0-1 (Friday 01 March 2024 06:21:24 PM)
> ==> Checking runtime dependencies...
> ==> Checking buildtime dependencies...
> ==> Retrieving sources...
>   -> Found yay-12.3.0.tar.gz
> ==> Validating source files with sha256sums...
>     yay-12.3.0.tar.gz ... Passed
> ==> Extracting sources...
>   -> Extracting yay-12.3.0.tar.gz with bsdtar
> ==> Removing existing $pkgdir/ directory...
> ==> Starting build()...
> go build -trimpath -mod=readonly -modcacherw  -ldflags '-X "main.yayVersion=12.3.0" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay
> go: errors parsing go.mod:
> /home/hjpotter92/.cache/yay/yay/src/yay-12.3.0/go.mod:43: unknown directive: toolchain
> make: *** [Makefile:117: yay] Error 1
> ==> ERROR: A failure occurred in build().
>     Aborting...
> ```

That's odd, what version of go do you have when you do ```go version``` ?

**Comment by hjpotter92** [comment]
hey @coreybruce ; it's the 2nd shell output above: `go version go1.22.0 linux/amd64`

**Comment by coreybruce** [comment]
Well I didn't expect it to also affect x64

**Comment by Jguer** [comment]
Hey everyone, I've removed the toolchain directive (added automatically by go) and I'll update the PKGBUILD to specify go >= 1.21.x

**Comment by koenigstag** [comment]
Any updates ?

**Comment by coreybruce** [comment]
> Hey everyone, I've removed the toolchain directive (added automatically by go) and I'll update the PKGBUILD to specify go >= 1.21.x

So does this new version fix the issue?

**Comment by MarcPlace** [comment]
Today Archlinux and Archlinux32 has rolled out yay v12.3.1. Works and compiles now without any issues on both architectures (x86 and x86_64), Thank you @Jguer for the fix.

**Comment by coreybruce** [comment]
Just updated to the latest version of yay without any issues and got the latest version of go from a update, this is now resolved so I will be closing this issue unless anyone else has any issues they are free to re-open this issue report.
