### ISSUE TITLE
yay fails to compile and run with pacman 6.1 

### ISSUE THREAD

**Issue by bittin** [Jguer/yay#2393]
yay: error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory

https://aur.archlinux.org/packages/yay-git (so think you need to update your package to use the new version of libalpm

yay fails with the new pacman 6.1 thats now in testing on Arch Linux: https://archlinux.org/packages/core-testing/x86_64/pacman/

**Comment by sibwaze** [comment]
i'm experiencing the same issue after updating my arch on testing mirrors

**Comment by DawfukFR** [comment]
same (+1)

**Comment by Jguer** [comment]
`yay 12.3.1-2` compiles with tag `next` if `libalpm.so=14-64` is detected now.

If you've upgraded pacman separately from yay (or upgraded yay separately from pacman) a manual rebuild should succeed.

I will push another revision update once pacman 6.1 hits core to try and cover as many users as possible in the combined upgrade

**Comment by bittin** [comment]
@Jguer yep that worked thank you :)

**Comment by aaronliu0130** [comment]
6.1 hit core an hour ago

**Comment by dev-rfc** [comment]
I have the same error as above, and cannot rebuild it, it gives me the error bellow:

`==> ERRO: Cannot find the debugedit binary required for including source files in debug packages.
`

**Comment by aaronliu0130** [comment]
That's a different error. Try either disabling the automatic `makepkg`ing of debug packages or installing core/debugedit.

**Comment by dev-rfc** [comment]
> That's a different error. Try either disabling the automatic `makepkg`ing of debug packages or installing core/debugedit.

It was already installed, but manually removing yay and yay-debug did the trick. Thank you.

**Comment by benedikt-bartscher** [comment]
This seems to still be broken on arm64

**Comment by aaronliu0130** [comment]
Did you rebuild it from source?

**Comment by benedikt-bartscher** [comment]
yes i did, against tag `12.3.3`

**Comment by aaronliu0130** [comment]
And https://github.com/Jguer/yay/releases/download/v12.3.3/yay_12.3.3_aarch64.tar.gz doesn't work either? What does it say?

**Comment by benedikt-bartscher** [comment]
just for reference:
```bash
Linux runner-mz9yhyrmk-project-982-concurrent-0-830shogr 6.1.0-17-arm64 #1 SMP Debian 6.1.69-1 (2023-12-30) aarch64 GNU/Linux
uid=1001(builder) gid=1001(builder) groups=1001(builder)
builder
NAME="Arch Linux ARM"
PRETTY_NAME="Arch Linux ARM"
ID=archarm
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinuxarm.org/"
DOCUMENTATION_URL="https://archlinuxarm.org/wiki"
SUPPORT_URL="https://archlinuxarm.org/forum"
BUG_REPORT_URL="https://github.com/archlinuxarm/PKGBUILDs/issues"
LOGO=archlinux-logo

$ yay --version
yay: error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory
```

I will try the release binarys now

**Comment by Jguer** [comment]
When `12.3.3` was tagged arm archlinux was still on pacman 6.0. I'll tag a new version to rebuild for 6.1

**Comment by benedikt-bartscher** [comment]
Thanks, @Jguer works perfectly fine now!

**Comment by thisven** [comment]
> If you've upgraded pacman separately from yay (or upgraded yay separately from pacman) a manual rebuild should succeed.

`yay`! That worked like a charm. :star_struck:

**Comment by johnzzon** [comment]
Here's a tip to temporarily fix yay in order to cleanBuild:

```
$ yay -Sua
yay: error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory

# Symlink libalpm 14 to 13 so yay can use that
$ sudo ln -s /usr/lib/libalpm.so.14.0.0 /usr/lib/libalpm.so.13

# Reinstall yay/yay-git, make sure you choose clean build
$ yay -S yay-git

# Clean up your temporary symlink
$ sudo rm /usr/lib/libalpm.so.13
```

This all worked great for me. Hope it helps someone else.

**Comment by aaronliu0130** [comment]
Are you sure we need the .0.0 after the 14?

**Comment by eugenioventura** [comment]
Im having problems to compile yay and the error message reffers to a dependency of pacman>6.1... my pacman is up to date (ran sudo pacman -Syy) and when I ask for the version, it says Pacman v6.0.2 - libalpm v13.0.2 (not 6.1)

When I run makepkg -si, i get the following (pt-BR sorry):

=> ERRO: "pacman" falhou em instalar dependências não encontradas.
==> Dependências faltando:
  -> pacman>6.1
==> Verificando as dependências de tempo de compilação...
==> ERRO: Não foi possível resolver todas as dependências.

Can u help me??

**Comment by aaronliu0130** [comment]
What distro are you using? The latest pacman is in fact 6.1

**Comment by XeemPad** [comment]
> Here's a tip to temporarily fix yay in order to cleanBuild:
> 
> ```
> $ yay -Sua
> yay: error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory
> 
> # Symlink libalpm 14 to 13 so yay can use that
> $ sudo ln -s /usr/lib/libalpm.so.14.0.0 /usr/lib/libalpm.so.13
> 
> # Reinstall yay/yay-git, make sure you choose clean build
> $ yay -S yay-git
> 
> # Clean up your temporary symlink
> $ sudo rm /usr/lib/libalpm.so.13
> ```
> 
> This all worked great for me. Hope it helps someone else.

when reinstalling yay, I'm stuck on the same error:
`:: yay-git-12.3.5.r0.g2ff794d-1 and yay-12.3.1-1 are in conflict. Remove yay? [y/N] `
It doesn't matter what I choose - the installation fails. 
When choosing cleanBuild mode I type a (all).

If I agree to remove yay:
`(2/2) checking keys in keyring                     [##########################] 100%
(2/2) checking package integrity                   [##########################] 100%
(2/2) loading package files                        [##########################] 100%
(2/2) checking for file conflicts                  [##########################] 100%
error: failed to commit transaction (conflicting files)
yay-git-debug: /usr/lib/debug/usr/bin/yay.debug exists in filesystem (owned by yay-debug)
Errors occurred, no packages were upgraded.
 -> error installing: [/home/emil/.cache/yay/yay-git/yay-git-12.3.5.r0.g2ff794d-1-x86_64.pkg.tar.zst /home/emil/.cache/yay/yay-git/yay-git-debug-12.3.5.r0.g2ff794d-1-x86_64.pkg.tar.zst] - exit status 1
`

If I disagree:
`error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: yay-git-12.3.5.r0.g2ff794d-1 and yay-12.3.1-1 are in conflict
 -> error installing: [/home/emil/.cache/yay/yay-git/yay-git-12.3.5.r0.g2ff794d-1-x86_64.pkg.tar.zst /home/emil/.cache/yay/yay-git/yay-git-debug-12.3.5.r0.g2ff794d-1-x86_64.pkg.tar.zst] - exit status 1
`

**Comment by aaronliu0130** [comment]
Which repo do you normally install yay from? Why do you need yay-debug?

**Comment by JR1994** [comment]
> > Here's a tip to temporarily fix yay in order to cleanBuild:
> > ```
> > $ yay -Sua
> > yay: error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory
> > 
> > # Symlink libalpm 14 to 13 so yay can use that
> > $ sudo ln -s /usr/lib/libalpm.so.14.0.0 /usr/lib/libalpm.so.13
> > 
> > # Reinstall yay/yay-git, make sure you choose clean build
> > $ yay -S yay-git
> > 
> > # Clean up your temporary symlink
> > $ sudo rm /usr/lib/libalpm.so.13
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This all worked great for me. Hope it helps someone else.
> 
> when reinstalling yay, I'm stuck on the same error: `:: yay-git-12.3.5.r0.g2ff794d-1 and yay-12.3.1-1 are in conflict. Remove yay? [y/N] ` It doesn't matter what I choose - the installation fails. When choosing cleanBuild mode I type a (all).
> 
> If I agree to remove yay: `(2/2) checking keys in keyring [##########################] 100% (2/2) checking package integrity [##########################] 100% (2/2) loading package files [##########################] 100% (2/2) checking for file conflicts [##########################] 100% error: failed to commit transaction (conflicting files) yay-git-debug: /usr/lib/debug/usr/bin/yay.debug exists in filesystem (owned by yay-debug) Errors occurred, no packages were upgraded. -> error installing: [/home/emil/.cache/yay/yay-git/yay-git-12.3.5.r0.g2ff794d-1-x86_64.pkg.tar.zst /home/emil/.cache/yay/yay-git/yay-git-debug-12.3.5.r0.g2ff794d-1-x86_64.pkg.tar.zst] - exit status 1 `
> 
> If I disagree: `error: unresolvable package conflicts detected error: failed to prepare transaction (conflicting dependencies) :: yay-git-12.3.5.r0.g2ff794d-1 and yay-12.3.1-1 are in conflict -> error installing: [/home/emil/.cache/yay/yay-git/yay-git-12.3.5.r0.g2ff794d-1-x86_64.pkg.tar.zst /home/emil/.cache/yay/yay-git/yay-git-debug-12.3.5.r0.g2ff794d-1-x86_64.pkg.tar.zst] - exit status 1 `

I ran into the same issue removing yay-debug resolved it for me.

**Comment by Trit34** [comment]
> Which repo do you normally install yay from? Why do you need yay-debug?

The latest versions of makepkg are set to generate a `*-debug` package by default. You have to manually edit `/etc/makepkg.conf` to disable the relevant parameter. The line:

```
OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge debug lto)
```

must be changed to:

```
OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug lto)
```

**Comment by aaronliu0130** [comment]
So yay automatically installs every single pkg file made, not just the ones we asked to install?

**Comment by calzateu** [comment]
When trying to rebuild it it throws the following error:
`==> ERRO: Cannot find the debugedit binary required for including source files in debug packages.`

But @Trit34's solution worked for me :)

**Comment by DonCammne** [comment]
Thus the steps to solve the problems are:

1.  Change the /etc/makepkg.conf with "!debug" 
2.  `sudo ln -s /usr/lib/libalpm.so.14.0.0 /usr/lib/libalpm.so.13`
3.  `yay -S yay-git`
4.  Choose to remove yay?
5.  `sudo rm /usr/lib/libalpm.so.13`
6.  Change the /etc/makepkg.conf back to "debug"?
7.  Anything else? Is it correct that now I have yay-git and not yay?

Thanks!

**Comment by PoisonFrog** [comment]
> 7\. Anything else? Is it correct that now I have yay-git and not yay?

I think it works with regular yay package instead of yay-git. It worked for me.

**Comment by aaronliu0130** [comment]
It works with any package you used to install yay. It's just that yay-git is the most commonly-used one.

**Comment by DonCammne** [comment]
Thanks a lot for the responses!

So considering that I need to do a clean rebuild, should I use yay-git instead of yay (thus following the steps described)?

**Comment by karma-riuk** [comment]
> So considering that I need to do a clean rebuild, should I use yay-git instead of yay (thus following the steps described)?

It depends on whether you want the stable version of yay or the latest version on the git repo. You chose which ever one you prefer

**Comment by nuno-aj-aniceto** [comment]
> Thus the steps to solve the problems are:
> 
> 1. Change the /etc/makepkg.conf with "!debug"
> 2. `sudo ln -s /usr/lib/libalpm.so.14.0.0 /usr/lib/libalpm.so.13`
> 3. `yay -S yay-git`
> 4. Choose to remove yay?
> 5. `sudo rm /usr/lib/libalpm.so.13`
> 6. Change the /etc/makepkg.conf back to "debug"?
> 7. Anything else? Is it correct that now I have yay-git and not yay?
> 
> Thanks!

thank you !

**Comment by petrizzo** [comment]
Hi! In my case, removing yay-git solved all this mess. After that, I could upgrade the system without any issues.

**Comment by johnr14** [comment]
Trying to install yay in a distrobox with arch:latest gives an error  : 
```
==> Making package: yay 12.3.5-1 (Thu Apr 11 12:52:56 2024)
==> Checking runtime dependencies...
==> Installing missing dependencies...
error: target not found: pacman>6.1
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> pacman>6.1
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
```

and 
```
sudo pacman -S pacman
warning: pacman-6.0.2-8 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) pacman-6.0.2-8

Total Download Size:   0.90 MiB
Total Installed Size:  4.72 MiB
Net Upgrade Size:      0.00 MiB
```

So this bug is still a problem **because distrobox uses archive.archlinux.org/repo/2024/02/01**...

Could there be **a check on build to downgrade yay** to a version compatible with current installed pacman ?

**Comment by im-ecorp** [comment]
> `yay 12.3.1-2` compiles with tag `next` if `libalpm.so=14-64` is detected now.
> 
> If you've upgraded pacman separately from yay (or upgraded yay separately from pacman) a manual rebuild should succeed.
> 
> I will push another revision update once pacman 6.1 hits core to try and cover as many users as possible in the combined upgrade

TY it works for me

**Comment by CFdefense** [comment]
If anyone is having issues and none of these solutions are working for you. I found this solution in linking libalpm 15 to 14 and using that instead. `sudo ln -s /usr/lib/libalpm.so.15.0.0 /usr/lib/libalpm.so.14`. This worked for me while repackaging and changing the build file did not.

**Comment by sjakk** [comment]
> If anyone is having issues and none of these solutions are working for you. I found this solution in linking libalpm 15 to 14 and using that instead. `sudo ln -s /usr/lib/libalpm.so.15.0.0 /usr/lib/libalpm.so.14`. This worked for me while repackaging and changing the build file did not.

thanks!

**Comment by 3a33d** [comment]
> > If anyone is having issues and none of these solutions are working for you. I found this solution in linking libalpm 15 to 14 and using that instead. `sudo ln -s /usr/lib/libalpm.so.15.0.0 /usr/lib/libalpm.so.14`. This worked for me while repackaging and changing the build file did not.
> 
> thanks!

Attempted to do this, but it's still not working. Anyone have any advice?

**Comment by PoisonFrog** [comment]
> Attempted to do this, but it's still not working. Anyone have any advice?

Reinstall yay. Build it again.

**Comment by 3a33d** [comment]
> 
> Reinstall yay. Build it again.

Disregard my post entirely, I'm an idiot and simply didn't read my error well enough. I had a random file located in /usr/ that was breaking my build. zz Sorry.

**Comment by cachius** [comment]
Tale of a casual Arch user:
```
# Got this error when running yay on a rarely used system
yay: error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory
# Created symlink to installed version of libalpm
sudo ln -s /usr/lib/libalpm.so.14 /usr/lib/libalpm.so.13

# Tried to upgrade yay and got a downgrade warning
yay -S yay
Sync Explicit (1): yay-10.1.2-1
Warnung: Downgrade des Paketes yay (12.1.3-1 => 10.1.2-1)

# Turns out I have the aviallon repo with ancient softeware version included in  /etc/pacman.conf
yay -Ss yay
aviallon/yay 10.1.2-1 (1.0 MiB 4.1 MiB) (Installiert: 12.1.3-1)
    Yet another yogurt. Pacman wrapper and AUR helper written in go.
aur/yay 12.4.2-1 (+2266 24.49) (Installiert: 12.1.3-1)
    Yet another yogurt. Pacman wrapper and AUR helper written in go.

# Explicitly specifying the repo works
yay -S aur/yay
```
I wonder how to prefer aur over aviallon per default. And doubt that Arch is the right choice for a rarely used system
