### ISSUE TITLE
Arch AUR yay-bin package built incorrectly for ARM armv7

### ISSUE THREAD

**Issue by bulletmark** [Jguer/yay#2404]
I reported this in the comments on the Arch `yay-bin` AUR page.

The current AUR `yay-bin` package for armv7h seems to have been incorrectly built against the old libalpm. Pacman on my ARM Pi2 has updated to 6.1.0-3 but after building and installing the latest 12.3.4-1 package manually I still get:
```
$ yay
yay: error while loading shared libraries: libalpm.so.13: cannot open shared object 
```

I suspect the reason is because Pacman 6.1 took 2 extra days before it was released on Arch ARM and I am guessing jguer built the ARM v7 binary in that 2 day window on his ARM v7 box assuming it had updated to pacman 6.1 but it had not.

**Comment by ViToni** [comment]
Maybe not only ARM related as I get the very same message on x86.

**Comment by ml50us** [comment]
i have the same issue here with this kernel
6.6.22-2-rpi #1 SMP Wed Mar 20 14:46:54 MDT 2024 armv7l GNU/Linux
when im trying to build yay : 
"gcc: error: unrecognized command-line option '-mno-omit-leaf-frame-pointer'; did you mean '-fno-omit-frame-pointer'?"

and after launching yay-bin:
"yay: error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory"

**Comment by CloverGit** [comment]
I updated pacman to 6.1.0-3 separately (from 6.0.2-9), and the same problem happened (x86_64).
In pacman 6.1.0-3, the symbolic link `/usr/lib/libalpm.so.13` has been updated to `/usr/lib/libalpm.so.14`.
I resolved this problem by recomplie and install yay.

**Comment by bulletmark** [comment]
@ml50us your first comment is about the `yay` package and is the bug described in #2402 and #2403. Your second comment is about `yay-bin` package and is the issue I describe here. They are separate packages.

@CloverGit AUR helpers like `yay` and `paru` must be manually updated when a `libaplm` update happens if the helper was not updated at the same time. That is normal, and not what this bug is about.

**Comment by Jguer** [comment]
:+1: will rebuild the arm versions, a cached image of the builder might have been used
