### ISSUE TITLE
package: debugedit not document but required

### ISSUE THREAD

**Issue by ulfgebhardt** [Jguer/yay#2407]
### Affected Version

yay v12.3.4.r0.ga1d530c - libalpm v14.0.0

### Describe the bug

When I updated via `yay -Syu` things got stuck on updating `yay`.

### Reproduction Steps

I found myself here:
![image](https://github.com/Jguer/yay/assets/1238238/123ff7be-d415-4f9a-9333-8a129c486bc4)

I manually pulled the latest master `git pull`
![image](https://github.com/Jguer/yay/assets/1238238/12508e66-b2c3-435e-80c6-2089fe67c96b)

Now I am running `makepkg -si`
![image](https://github.com/Jguer/yay/assets/1238238/833cb9e9-c39c-40ee-937e-993de056458f)

Running: `sudo pacman -S debugedit` solved things.
![image](https://github.com/Jguer/yay/assets/1238238/d0f83c11-546d-41b2-822c-f2fa22e521a6)

Running ` makepkg -si`
![image](https://github.com/Jguer/yay/assets/1238238/f6df6974-6168-4a15-8779-f4204157d6bc)
![image](https://github.com/Jguer/yay/assets/1238238/47f232e9-36fd-4ced-afcd-d22c773dbcab)

### Expected behavior

Things should work out of the box running `yay -Syu`.
All dependencies should be documented and auto installed.
There is no reference to `debugedit` in the README.md

### Solution

`sudo pacman -S debugedit` and manual pulling latest master

### Related Issues
- https://github.com/Jguer/yay/issues/2393
- https://github.com/Jguer/yay/issues/2370
- https://github.com/Jguer/yay/issues/2394

### Update

Pivoted from a bare git installation to installing `yay` via `pacman`. In my particular case I used yay to install yay - weird, I know: `yay -S yay` 
![image](https://github.com/Jguer/yay/assets/1238238/e425c61b-bf30-4bcb-94db-38a5bc3feeeb)

Finding this error:
![image](https://github.com/Jguer/yay/assets/1238238/335b72bd-0e67-4eb9-97d1-eabc91535d3c)

Solved by: `yay -R yay-git-debug`
![image](https://github.com/Jguer/yay/assets/1238238/d327fa21-d2ea-4e85-9f0f-320f541df0df)

Running `yay -S yay`
![image](https://github.com/Jguer/yay/assets/1238238/22515a23-08d3-4823-9929-da4ae15272b9)

### Credits
Solved by:
- https://itsfoss.community/t/archlinux-problems-with-yay-after-system-upgrade/11818/9
- https://github.com/Jguer/yay/issues/2370#issuecomment-1953028187
- Update inspired by: https://github.com/Jguer/yay?tab=readme-ov-file#other-distributions

### Notes

I love `yay` - while my report may sound a bit harsh
> Things should work out of the box running `yay -Syu`

that's just because that how it tends to behave - makes you a bit hotheaded when it doesn't.

Keep up the good work ❤️

**Comment by Jguer** [comment]
Hi @ulfgebhardt , debugedit is part of base-devel, a pre-requirement to using the AUR, as such it is not included in the default depends. 

This started to be an "issue" when debug was added as a default option in /etc/makepkg.conf
