### ISSUE TITLE
Can't update yay to version 12.3.4 - Error in build()

### ISSUE THREAD

**Issue by BlackRabbitLP** [Jguer/yay#2408]
### Affected Version

yay v12.3.1 - libalpm v14.0.0

### Describe the bug

While updating yay via the yay-version from 12.3.1 to 12.3.4, the build stops by calling github.com/Jguer/go-alpm/v2

### Reproduction Steps

1. run yay -Syyu
2. rebuild
3. don't show differences

Alternative: This error also occures, when I try to rebuild yay manually via git clone and makepkg -sri

### Expected behavior

I would hope, the build would run without error and yay would update, but it doesn't.

### Output

go build -trimpath -mod=readonly -modcacherw  -ldflags '-X "main.yayVersion=12.3.4" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay
go: downloading github.com/Jguer/votar v1.0.0
go: downloading github.com/Jguer/go-alpm/v2 v2.2.1
go: downloading github.com/Jguer/aur v1.2.3
go: downloading github.com/Morganamilo/go-srcinfo v1.0.0
go: downloading github.com/deckarep/golang-set/v2 v2.6.0
go: downloading golang.org/x/sys v0.18.0
go: downloading github.com/leonelquinteros/gotext v1.5.2
go: downloading github.com/Morganamilo/go-pacmanconf v0.0.0-20210502114700-cff030e927a5
go: downloading github.com/adrg/strutil v0.3.1
go: downloading github.com/hashicorp/go-multierror v1.1.1
go: downloading golang.org/x/term v0.18.0
go: downloading golang.org/x/text v0.14.0
go: downloading github.com/ohler55/ojg v1.21.4
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/itchyny/gojq v0.12.14
go: downloading github.com/itchyny/timefmt-go v0.1.5
go: downloading github.com/hashicorp/errwrap v1.1.0
# github.com/Jguer/go-alpm/v2
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/db_six.go:29:103: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t value in argument to _Cfunc_alpm_find_group_pkgs
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/deps.go:26:75: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_handle_t) as *_Ctype_struct__alpm_handle_t value in argument to _Cfunc_alpm_find_dbs_satisfier
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/deps.go:26:75: cannot use _cgo1 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t value in argument to _Cfunc_alpm_find_dbs_satisfier
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/deps.go:43:78: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t value in argument to _Cfunc_alpm_find_satisfier
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/package_six.go:42:53: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t value in argument to _Cfunc_alpm_list_count
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/package_six.go:43:34: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t value in argument to _Cfunc_alpm_list_msort
make: *** [Makefile:115: yay] Fehler 1
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
 -> Fehler beim Erstellen: yay-exit status 4
 -> Die folgenden Pakete konnten nicht installiert werden. Ein manueller Eingriff ist erforderlich:
yay - exit status 4

**Comment by Jguer** [comment]
missing `-tags=next`, do you have an entry for `GOFLAGS` in your env?

**Comment by BlackRabbitLP** [comment]
> missing `-tags=next`, do you have an entry for `GOFLAGS` in your env?

The output of go env shows this for GOFLAGS:
`GOFLAGS=''`

**Comment by Jguer** [comment]
yay 12.3.5 should not require any extra options to compile for libalpm14

**Comment by BlackRabbitLP** [comment]
> yay 12.3.5 should not require any extra options to compile for libalpm14

Thanks, this did the trick :)
