### ISSUE TITLE
[Request] Throw an error in case the user is root and the operation will execute makepkg

### ISSUE THREAD

**Issue by eyal0803** [Jguer/yay#241]
Simple as that.

I accidentally tried installing a package while being root and I got the error (telling me I shouldn't install as root) only after the download.

I might be missing/not knowing something as I didn't look much into it, so if the current procedure (downloading packages and throwing and error after) is fine then please close this issue.

**Comment by Morganamilo** [comment]
It might be a good idea to throw an error before an AUR install. Everything else `-Q`, `-Ss`, `-S repopkg`, will work as root so I don't think an error for every operation should be added.

**Comment by eyal0803** [comment]
What I meant was throwing the error even before the download. No doubt that the error should be there.

**Comment by Morganamilo** [comment]
By 'AUR install' I meant the whole process not specifically the install. Sorry if the wording was not the best.

**Comment by eyal0803** [comment]
So, if I understand you correctly, you support the idea?

**Comment by Morganamilo** [comment]
There's also actually allowing root and implementing #69 but I don't have a clear way to do it right now.

**Comment by Morganamilo** [comment]
Yeah I support that idea.

**Comment by Jguer** [comment]
This is a regression as yay used to do this. Yay supporting operation as root is something interesting but currently a bit unfeasible so for now let's re-add the root block on -S with aur targets and yogurt menu with aur selections

**Comment by Morganamilo** [comment]
This is a regression? I thought just a warning was always be behaviour.

**Comment by Jguer** [comment]
Answered while in transit, but if memory serves yay would os.Exit(1) if run as root in yay v1 and v2
