### ISSUE TITLE
gcc build error: unrecognized command-line option '-mno-omit-leaf-frame-pointer'

### ISSUE THREAD

**Issue by engageintellect** [Jguer/yay#2411]
### Describe the bug

I am getting the following error when trying to build the latest main branch commit of yay in  Arch ARM on Raspberry PI:

```
pi@arch ~/yay (master)> makepkg -si
==> Making package: yay 12.3.5-1 (Mon 25 Mar 2024 01:42:10 AM PDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found yay-12.3.5.tar.gz
==> Validating source files with sha256sums...
    yay-12.3.5.tar.gz ... Passed
==> Extracting sources...
  -> Extracting yay-12.3.5.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
go build -trimpath -mod=readonly -modcacherw -ldflags '-X "main.yayVersion=12.3.5" -X "main.localePath=/usr/share/locale/" -linkmode=external -compressdwarf=false' -buildmode=pie -o yay
# runtime/cgo
gcc: error: unrecognized command-line option '-mno-omit-leaf-frame-pointer'; did you mean '-fno-omit-frame-pointer'?
make: *** [Makefile:114: yay] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
```

Here are my CFLAGS in /etc/makepkg.conf:
```
CFLAGS="-march=armv7-a -mfloat-abi=hard -mfpu=neon -O2 -pipe -fstack-protector-strong -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security \
       -fstack-clash-protection \
       -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer"
```

### Reproduction Steps

1. git clone https://aur.archlinux.org/yay.git
2. cd yay
3. makepkg -si

### Expected behavior

I would expect it to build without errors. This worked fine a couple of week ago when I initially installed yay on this machine.
There are 2 others that have mentioned this issue here: [https://aur.archlinux.org/packages/yay](url)

**Comment by hammer065** [comment]
The file `/etc/makepkg.conf` added `-mno-omit-leaf-frame-pointer` to the list of `CFLAG`s (line 48 in the default config), which get used for all `makepkg` invoked builds. As this compiler flag is not supported for (some) ARM targets and therefore is not present, all C compiler / linker invocations will fail.

The simple fix is to simply remove the flag from the config.

**Comment by engageintellect** [comment]
> The file `/etc/makepkg.conf` added `-mno-omit-leaf-frame-pointer` to the list of `CFLAG`s (line 48 in the default config), which get used for all `makepkg` invoked builds. As this compiler flag is not supported for (some) ARM targets and therefore is not present, all C compiler / linker invocations will fail.
> 
> The simple fix is to simply remove the flag from the config.

Thanks for your response, bro. This solved my issue. 🤙
