### ISSUE TITLE
pacman>6.1 in PKGBUILD

### ISSUE THREAD

**Issue by amunrarara** [Jguer/yay#2438]
### Describe the bug

When running `makepkg -si`, an error is returned:

==> ERROR: 'pacman' failed to install missing dependencies.
   -> pacman>6.1

Pacman's current version is 6.0.2, however, so this always fails.

### Reproduction Steps

1. Clone the repo
2. Run `makepkg -si`
3. Boo :-(

### Output

```sh

```

**Comment by pararti** [comment]
Try edit your PKGBUILD file on line 12, change 'pacman>6.1' to 'pacman>6.0'

**Comment by Jguer** [comment]
Closing as pacman 6.1 is in core

**Comment by zhengyi0414** [comment]
same to！
how to fix it？

**Comment by andygeorge** [comment]
> pacman 6.1 is in core

Sadly, this isn't the case for SteamOS, so `yay` does currently break when trying to build. `paru` installed just fine, though.
