### ISSUE TITLE
Option to use aria instead of curl to download sources

### ISSUE THREAD

**Issue by DhruvaSambrani** [Jguer/yay#2446]
### Is your feature request related to a problem? Please describe.

With low/slow connectivity, downloads have to be restarted. It would be nice if we could use the continue feature from [`aria2`](https://github.com/aria2/aria2).

### Describe the solution you'd like

command line option `--use-aria2` to enable feature. Or if stable, default to aria when binary found, curl otherwise.

**Comment by Jguer** [comment]
Hey @DhruvaSambrani , 

You can configure makepkg to use aria2 for downloads by editing your /etc/makepkg.conf file. Check the documentation for DLAGENTS option for details on how to add aria2. https://man.archlinux.org/man/makepkg.conf.5#OPTIONS

Downloads executed by yay are very small and done by git
