### ISSUE TITLE
Yay makedepends on `make`, which is not in listed as a dependency in the PKGBUILD

### ISSUE THREAD

**Issue by kolayne** [Jguer/yay#2451]
The `make` package is missing in the `makedepends` list of yay's `PKGBUILD`

**Comment by camilosm** [comment]
The [AUR wiki](https://wiki.archlinux.org/title/Arch_User_Repository#Prerequisites), section 2.1, states that you should have `base-devel` installed, which includes `make:`

> Note: Packages in the AUR assume that [base-devel](https://archlinux.org/packages/?name=base-devel) is installed in the build environment.

**Comment by kolayne** [comment]
Oops! My bad, you're right. 

I wish `makepkg` enforced it, though. Or, at least, gave me a warning when I'm missing `base-devel`...
