### ISSUE TITLE
`yay -Si` prints nothing, while `pacman -Si` prints information for all available packages

### ISSUE THREAD

**Issue by brainwo** [Jguer/yay#2456]
### Affected Version

yay v12.3.5 - libalpm v14.0.0

### Describe the bug

As the title suggest, `yay -Si` doesn't print anything

### Reproduction Steps

1. Run `yay -Si` in terminal
2. Nothing is happening
3. Run `pacman -Si` in terminal
4. Prints all the package information

### Expected behavior

Should print information like `pacman -Si` but with added AUR packages

### Output

```json
{
	"aururl": "https://aur.archlinux.org",
	"aurrpcurl": "https://aur.archlinux.org/rpc?",
	"buildDir": "/home/brian/.cache/yay",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "/bin/sudo",
	"sudoflags": "",
	"version": "12.3.5",
	"requestsplitn": 150,
	"completionrefreshtime": 7,
	"maxconcurrentdownloads": 0,
	"bottomup": true,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"keepSrc": false,
	"provides": true,
	"pgpfetch": true,
	"cleanmenu": true,
	"diffmenu": false,
	"editmenu": true,
	"combinedupgrade": true,
	"useask": false,
	"batchinstall": false,
	"singlelineresults": false,
	"separatesources": true,
	"debug": true,
	"rpc": true,
	"doubleconfirm": true,
	"rebuild": "no"
}
```

**Comment by alchemicalkube** [comment]
Yeah same issue here as well. Trying to figure out what the cause is at the moment. Will update here if I find a fix in the source. Can't find any recent changes on this file that could've effected it. Does it work with previous versions for you?

Main thing I've noticed is in 
```go
func syncInfo(ctx context.Context, run *runtime.Runtime,
	cmdArgs *parser.Arguments, pkgS []string, dbExecutor db.Executor) error
```

Most vars that I suspect pass data are all empty when printing them, unsure as to why, I'm not experienced with the source yet.

**Comment by alchemicalkube** [comment]
So it seems its this little block here:
```go
if len(repoS) != 0 {
    arguments := cmdArgs.Copy()
    arguments.ClearTargets()
    arguments.AddTarget(repoS...)

    err = run.CmdBuilder.Show(run.CmdBuilder.BuildPacmanCmd(ctx,
    arguments, run.Cfg.Mode, settings.NoConfirm))
    if err != nil {
        return err
    }
}
```

`aurS`, `repoS` and `pkgS` vars are all empty. Removing the len check on `repoS` allows this command to run successfully. Additionally, I don't know exactly what the purpose of those are for, considering that the passed targets for `aur` or `repo` is empty nonetheless.

I know that it will run `packageSlices(...)` to seperate the `aur` and `repo` data, but is seems unnecessary as `pkgS` is empty when passed to `syncInfo()`, so it's essentially doing nothing in this case. I'm not exactly sure why the `len` check is in place for `repoS` in the first place, unless someone is able to enlighten me?

Edit:

Looks like `repoS` is used when you parse a specific package, i.e `yay -Si nodejs`

**Comment by Jguer** [comment]
https://github.com/Jguer/yay/pull/2459 

This should fix it, care to try it?

**Comment by alchemicalkube** [comment]
> #2459
> 
> This should fix it, care to try it?

Yep! That works. Put your code in and built, works perfect now. Thank you! Similar to the fixes I had locally but I didn't know about `InstalledRemotePackageNames` and if it would be correct for this source :(

![Peek 2024-06-20 16-23](https://github.com/Jguer/yay/assets/21239633/d0eebce5-47fa-4a9a-b336-ef9c530fce98)

**Comment by Jguer** [comment]
It was not straightforward logic @Xeckt,if you see a better way to refactor it I'll be happy to take a look. Thanks for your investigation still, without it I wouldn't have seen the issue as fast

**Comment by alchemicalkube** [comment]
@Jguer 

Since the `packageSlices` func depends on `pkgS` to make sure `aurS` and `repoS` either/or populated, could we not run the len check on `pkgS` before running `packageSlices`? Then `PackageSlices` won't operate on nil slices every time and actually operate as intended, basically just took your fixes and moved them so we only need to do a single check without touching anything else:

```go
pkgS = query.RemoveInvalidTargets(run.Logger, pkgS, run.Cfg.Mode)

if len(pkgS) == 0 {
    pkgS = dbExecutor.InstalledRemotePackageNames()
}

aurS, repoS := packageSlices(pkgS, run.Cfg, dbExecutor)
```
Subsequently we can then remove the new `||` checks in place here and it would still work:
```go
if len(repoS) != 0 {
		arguments := cmdArgs.Copy()
		arguments.ClearTargets()
		arguments.AddTarget(repoS...)

		err = run.CmdBuilder.Show(run.CmdBuilder.BuildPacmanCmd(ctx,
			arguments, run.Cfg.Mode, settings.NoConfirm))
		if err != nil {
			return err
		}
	}
```
Unless I am missing something here?

**Comment by Jguer** [comment]
in that case repoS will be empty as all Remote packages installed will be aur. This will then cause the `pacman -Si` to be skipped 

pkgS - Target packages
aurS - Target AUR packages
repoS - Target Repo packages

Unfortunately, cramming all of the repo packages into pkgS if pkgs==0 will probably make this display very slow

**Comment by alchemicalkube** [comment]
Understood! Thanks for explaining!

**Comment by jdholtz** [comment]
> Should print information like pacman -Si but with added AUR packages

Just updated to the latest commit. However, running `yay -Si` only prints AUR packages. Is this expected behavior? I quoted the expected behavior from the author of this issue that they think it should print all repo and AUR packages. I would also expect that `yay -Sia` prints only AUR packages and `yay -Si --repo` would only print the same info as `pacman -Si` but that isn't the case with this fix (it only every prints packages from the AUR repository). Am I misunderstanding the `-Si` flag?

**Comment by alchemicalkube** [comment]
> > Should print information like pacman -Si but with added AUR packages
> 
> Just updated to the latest commit. However, running `yay -Si` only prints AUR packages. Is this expected behavior? I quoted the expected behavior from the author of this issue that they think it should print all repo and AUR packages. I would also expect that `yay -Sia` prints only AUR packages and `yay -Si --repo` would only print the same info as `pacman -Si` but that isn't the case with this fix (it only every prints packages from the AUR repository). Am I misunderstanding the `-Si` flag?

You're absolutely right, the `repoS` slice is empty. Looks like I got too eager in the beginning and didn't double check!

Could it be that the fix:
```go
if len(repoS) == 0 && len(aurS) == 0 {
		aurS = dbExecutor.InstalledRemotePackageNames()
	}
```
needs to be:
```go
if len(repoS) == 0 && len(aurS) == 0 {
		aurS = dbExecutor.InstalledRemotePackageNames()
		repoS = dbExecutor.InstalledSyncPackageNames()
}
```
As that seems to work, from what I can tell:
![Peek 2024-06-21 16-58](https://github.com/Jguer/yay/assets/21239633/49e853ae-1372-4593-81a9-c9352084f189)

**Comment by jdholtz** [comment]
That fix partially works. However, it doesn't work when using the `-a, --aur` and `--repo` flags. This patch should have the intended behavior. I can make a quick PR to fix it.
```diff
        aurS, repoS := packageSlices(pkgS, run.Cfg, dbExecutor)
 
        if len(repoS) == 0 && len(aurS) == 0 {
-               aurS = dbExecutor.InstalledRemotePackageNames()
+               if run.Cfg.Mode != parser.ModeRepo {
+                       aurS = dbExecutor.InstalledRemotePackageNames()
+               }
+
+               if run.Cfg.Mode != parser.ModeAUR {
+                       repoS = dbExecutor.InstalledSyncPackageNames()
+               }
        }
 
        if len(aurS) != 0 {
```

**Comment by alchemicalkube** [comment]
Lovely! Makes more sense now you show me
