### ISSUE TITLE
Localization bug in ru_RU translation of "%n packages to upgrade/install" string

### ISSUE THREAD

**Issue by ratijas** [Jguer/yay#2463]
### Affected Version

`yay v12.3.5 - libalpm v14.0.0`

### Describe the bug

There is a localization issue, at least with `ru_RU` translation of `yay`: `%!(EXTRA string=пакеты)`.

![image](https://github.com/Jguer/yay/assets/6737986/657ad924-a069-4560-bd29-21c256cd506d)

It works fine with `en_US` though: `:: 60 packages to upgrade/install.`

### Reproduction Steps

1. Run yay with a `ru_RU` locale/language

### Expected behavior

Did not expect to see i18n artifacts.

### Output

```sh
❯ yay
[sudo] пароль для ratijas: 
:: Обновление баз данных пакетов...
 core                                                121.1 KiB   256 KiB/s 00:00 [----------------------------------------------] 100%
 extra                                                 7.9 MiB  1259 KiB/s 00:06 [----------------------------------------------] 100%
 multilib                                            138.9 KiB  1014 KiB/s 00:00 [----------------------------------------------] 100%
 sublime-text is up to date
:: Поиск обновлений пакетов AUR...
:: Проверка пакетов разработки...
:: Поиск обновлений в базах данных...
:: 60 обновить/установить.%!(EXTRA string=пакеты)
60  core/libksba                 1.6.6-1          -> 1.6.7-1
59  extra/android-udev           20240221-1       -> 20240625-1
[...]
```

**Comment by Jguer** [comment]
This issue can be fixed through https://www.transifex.com/yay-1/yay/ for any interested in picking this up

**Comment by ratijas** [comment]
This looks like a bad string puzzle. How are the words supposed to conjugate in this sentence? "60 packages to upgrade/install" where "60 packages" is a one piece string as far as I can see it in the screenshot is conjugated at all.

**Comment by ratijas** [comment]
I made basic changes to 2 strings on trasifex. I don't know if they need to be reviewed by anyone, but I pressed Save Changes on them.

**Comment by Jguer** [comment]
They've now been merged: https://github.com/Jguer/yay/pull/2481 
You can test it out on `yay-git`
