### ISSUE TITLE
Beautify output using pterm?

### ISSUE THREAD

**Issue by markg85** [Jguer/yay#2466]
### Is your feature request related to a problem? Please describe.

The way yay presents download status is just fine as-is. Still, if someone has time and has a bit of an artistic feeling then why not make this progress a little more beautiful?

### Describe the solution you'd like

I got inspired by this because python's pip is showing a rather visual fancy progressbar in the terminal. Turns out that pip is using [rich](https://pypi.org/project/rich/) to do this. As far as i could find, there's not a "rich for go" to accomplish the same. But there is [pterm](https://github.com/pterm/pterm) which has a lot of fancy tools to make this process a bit more viauslly appealing.

An example of what you can do with rich (so not applicable)
![image](https://github.com/Jguer/yay/assets/49061/86c7a3c0-996f-470e-a7eb-93347fe1184a)

But in pterm you could do this:
![Animation](https://raw.githubusercontent.com/pterm/pterm/master/_examples/progressbar/multiple/animation.svg)

But there's many more options. Do look over the pterm examples and be inspired :)

**Comment by jdholtz** [comment]
Most of the actual downloading (every package besides AUR) is done by invoking pacman. Therefore, it may not be feasible to add this progress bar through Yay.

Yay doesn't currently have any progress bars (the progress is printed by makepkg and pacman). Is there a part of Yay where you would like to see a progress bar?

**Comment by markg85** [comment]
Ah, didn't know that. I guess there is nothing for `yay` to do then. Thank you for the into! Closed this issue.
