### ISSUE TITLE
yay -s to install?

### ISSUE THREAD

**Issue by Squirreljetpack** [Jguer/yay#2489]
### Affected Version
yay --version
yay v12.3.5 - libalpm v14.0.0

### Describe the bug

yay -s displays:

```
yay -s expac
 -> Avoid running yay as root/sudo.
3 aur/expac-git 9.2.g6be7fe1-1 (+37 0.00) (Out-of-date: 2024-01-01)
    pacman database extraction utility
2 extra/texlive-mathscience 2024.2-2 (3.7 MiB 18.2 MiB) [texlive] (Installed)
    TeX Live - Mathematics, natural sciences, computer science packages
1 extra/expac 10-10 (13.6 KiB 29.4 KiB)
    alpm data (pacman database) extraction utility
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==>  -> EOF
```
I like the display, and option to select which to install.
But it seems it's not supported?

### Reproduction Steps
yay -s

### Expected behavior

After being given a prompt we are allowed to install with it.
Actually I tested paru and they output a formatted list:
```
paru -s expac
1 extra/expac 10-10 [13.65 KiB 29.38 KiB]
    alpm data (pacman database) extraction utility
2 extra/texlive-mathscience 2024.2-2 [0 B 18.18 MiB] [Installed] (texlive)
    TeX Live - Mathematics, natural sciences, computer science packages
3 aur/expac-git 9.2.g6be7fe1-1 [+37 ~0.00] [Out-of-date: 2024-01-01]
    pacman database extraction utility
:: Select packages (eg: 1 2 3, 1-3):
:: 2 3
extra/texlive-mathscience
aur/expac-git
```
This would be cool too.
It seems -s is not actually an option for pacman, but it seems nice to have.

**Comment by Jguer** [comment]
-s passes an option into the system `yay expac` should provide the desired behavior if understand it correctly
