### ISSUE TITLE
Yay doesn't check for AUR package when used with pacman 7.0 / libalpm15

### ISSUE THREAD

**Issue by FredBezies** [Jguer/yay#2500]
### Affected Version

yay 12.3.5

### Describe the bug

After pacman 7.0 landed on core-testing, I rebuild yay to use libalpm15. But I noticed AUR package are not checked correctly. I noticed that when I had to grab and build zsh-powerlevel10k 1.20.0-4. Yay doesn't detect there was an upgrade.

### Reproduction Steps

1. Have an archlinux with testing repositories activated
2. Build yay on it
3. Check all packages with a yay -Syu

### Expected behavior

Telling user there is an update.

### Output

```sh

```

**Comment by Jguer** [comment]
I tried to reproduce this using yay v12.3 -> 12.4 and was not able to reproduce with pacman v7.0.0

Was also not able to find the affected package mention (closest is https://aur.archlinux.org/packages/zsh-theme-powerlevel10k-git which is linked in official github and is a devel package and as such should be updated with yay -Syu --devel, assuming that it was originally installed with yay or --gendb was done when yay was installed)

If you can post reproduction steps for this issue, I'll try it again

**Comment by odomingao** [comment]
I've also managed to upgrade aur packages just fine with yay v12.4.1 - libalpm v15.0.0.

**Comment by FredBezies** [comment]
I'm unable to reproduce the bug, whatever version of Yay I'm using. And the package I was speaking of can be found here : https://aur.archlinux.org/packages/zsh-theme-powerlevel10k

So let's close this bug. No need to keep it opened.

**Comment by ChangqingW** [comment]
> I tried to reproduce this using yay v12.3 -> 12.4 and was not able to reproduce with pacman v7.0.0
> 
> Was also not able to find the affected package mention (closest is https://aur.archlinux.org/packages/zsh-theme-powerlevel10k-git which is linked in official github and is a devel package and as such should be updated with yay -Syu --devel, assuming that it was originally installed with yay or --gendb was done when yay was installed)
> 
> If you can post reproduction steps for this issue, I'll try it again

The `-git` AUR package have not been updated for years, am I correct in assuming that `yay` and most AUR helper would not rebuild the package if the linked Github repo updated? Unless the actual AUR package itself is updated?

**Comment by v1993** [comment]
> The `-git` AUR package have not been updated for years, am I correct in assuming that `yay` and most AUR helper would not rebuild the package if the linked Github repo updated? Unless the actual AUR package itself is updated?

Mostly wrong: while this is not the default behavior of `yay`, `--devel`/`--gendb` flags specifically exists to allow checking for upstream repo changes; similar functionality is present in other AUR helpers as it's extremely useful - AUR VCS packages should not be updated just for new upstream commits and thus may stay unchanged for years on an active project if build system/dependencies/versioning stay the same.
