### ISSUE TITLE
Build error on 'msgfmt' syntax error

### ISSUE THREAD

**Issue by tijko** [Jguer/yay#2506]
### 12.4.1.r0.g3a118b76-1

1. git clone https://aur.archlinux.org/yay-git.git
2. cd yay-git makepkg -si

### Running makepkg -si
```
msgfmt po/en.po -o po/en.mo
po/en.po:368: missing 'msgstr' section
po/en.po:368:36: syntax error
msgfmt: found 2 fatal errors
make: *** [Makefile:134: po/en.mo] Error 1
==> ERROR: A failure occurred in package().
```

Having used this a fair amount I am familiar with how the 'prompt menu' looks so I just copied the line style from [line 372 in en.po](https://github.com/Jguer/yay/blob/84d8f1b7b3bc7448f24abd57f48ff0e9dfbdb388/po/en.po#L372)

**Comment by Jguer** [comment]
fixed by #2507
