### ISSUE TITLE
yay 12.4.1 still fails with "error while loading shared libraries: libalpm.so.14" on armv7h

### ISSUE THREAD

**Issue by afunix** [Jguer/yay#2508]
### Affected Version

```
# pacman -Qi yay
Name            : yay-bin
Version         : 12.4.1-1
...
```

### Describe the bug

yay fails to run on Archlinux for arm:
```
# yay -h
yay: error while loading shared libraries: libalpm.so.14: cannot open shared object file: No such file or directory
```

### Reproduction Steps

```
$ git clone https://aur.archlinux.org/yay-bin.git
$ cd yay-bin
$ makepkg -s
# pacman -U ./yay-bin-12.4.1-1-armv7h.pkg.tar.xz
# yay -h
```

### Expected behavior

yay shows help

### Output

```
# yay -h
yay: error while loading shared libraries: libalpm.so.14: cannot open shared object file: No such file or directory

# uname -a
Linux pikvm0 6.6.45-7-rpi #1 SMP Mon Sep  2 09:16:27 UTC 2024 armv7l GNU/Linux

# ldd /usr/bin/yay
	linux-vdso.so.1 (0xbefcd000)
	libalpm.so.14 => not found
	libresolv.so.2 => /usr/lib/libresolv.so.2 (0xb6616000)
	libc.so.6 => /usr/lib/libc.so.6 (0xb6491000)
	/lib/ld-linux-armhf.so.3 => /usr/lib/ld-linux-armhf.so.3 (0xb6eee000)

# pacman -Qi pacman
Name            : pacman
Version         : 7.0.0.r3.g7736133-1
...
```

**Comment by m040601** [comment]
Yes it is confirmed, same thing here Arch Linux ARM "armv7h"


reported here, https://aur.archlinux.org/packages/yay-bin#comment-991232

**Comment by alibaghernejad** [comment]
The same issue here after updating the Archlinux packages:
Linux cosmicomics 6.10.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000 x86_64 GNU/Linux

Removing and reinstalling the yay fix the problem for me:
```shell
sudo pacman -Rns yay-bin yay-bin-debug
sudo pacman -S --needed git base-devel
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
```

**Comment by Jguer** [comment]
`yay 12.4.2-1` has been built against an updated build image today which should include the latest ARM pacman version

**Comment by tuanlc** [comment]
> The same issue here after updating the Archlinux packages: Linux cosmicomics 6.10.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000 x86_64 GNU/Linux
> 
> Removing and reinstalling the yay fix the problem for me:
> 
> ```shell
> sudo pacman -Rns yay-bin yay-bin-debug
> sudo pacman -S --needed git base-devel
> git clone https://aur.archlinux.org/yay.git
> cd yay
> makepkg -si
> ```

This works. Thank @alibaghernejad !

**Comment by xxxtrashcion** [comment]
> The same issue here after updating the Archlinux packages: Linux cosmicomics 6.10.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000 x86_64 GNU/Linux
> 
> Removing and reinstalling the yay fix the problem for me:
> 
> ```shell
> sudo pacman -Rns yay-bin yay-bin-debug
> sudo pacman -S --needed git base-devel
> git clone https://aur.archlinux.org/yay.git
> cd yay
> makepkg -si
> ```

Receiving this upon inputting the first command.

```
error: target not found: yay-bin
error: target not found: yay-bin-debug
```

**Comment by alibaghernejad** [comment]
> > The same issue here after updating the Archlinux packages: Linux cosmicomics 6.10.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000 x86_64 GNU/Linux
> > Removing and reinstalling the yay fix the problem for me:
> > ```shell
> > sudo pacman -Rns yay-bin yay-bin-debug
> > sudo pacman -S --needed git base-devel
> > git clone https://aur.archlinux.org/yay.git
> > cd yay
> > makepkg -si
> > ```
> 
> Receiving this upon inputting the first command.
> 
> ```
> error: target not found: yay-bin
> error: target not found: yay-bin-debug
> ```

Just ignore these errors and continue to the next commands to install the yay. Before cloning the git Repo make sure to remove the yay folder if it exists. 
It is located in the directory where you ran the git clone command. home directory often. (Backup it if required)

If you get any errors indicates that the "yay-bin" or "yay-bin-debug" folders exist, run the first command (consider their paths) to remove them and run the command again.
I hope this helps you.

**Comment by d3vilguard** [comment]
older yay compiled under `yay` and not `yay-bin`. Not really sure if installing the latter compiled `yay-bin` will rewrite `yay`. I don't think it is best advice to just ignore that instead of doing a `-Rns yay`.

**Comment by xxxtrashcion** [comment]
> older yay compiled under `yay` and not `yay-bin`. Not really sure if installing the latter compiled `yay-bin` will rewrite `yay`. I don't think it is best advice to just ignore that instead of doing a `-Rns yay`.

This worked

**Comment by thebigsleepjoe** [comment]
> The same issue here after updating the Archlinux packages: Linux cosmicomics 6.10.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000 x86_64 GNU/Linux
> 
> Removing and reinstalling the yay fix the problem for me:
> 
> ```shell
> sudo pacman -Rns yay-bin yay-bin-debug
> sudo pacman -S --needed git base-devel
> git clone https://aur.archlinux.org/yay.git
> cd yay
> makepkg -si
> ```

In case anyone has the issue where `yay-bin` and `yay` aren't installed:

For me, my packages were named `yay-git` and `yay-git-debug`, so just run `sudo pacman -Rns yay-git yay-git-debug` instead of the original line.

**Comment by alibaghernejad** [comment]
> > The same issue here after updating the Archlinux packages: Linux cosmicomics 6.10.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000 x86_64 GNU/Linux
> > Removing and reinstalling the yay fix the problem for me:
> > ```shell
> > sudo pacman -Rns yay-bin yay-bin-debug
> > sudo pacman -S --needed git base-devel
> > git clone https://aur.archlinux.org/yay.git
> > cd yay
> > makepkg -si
> > ```
> 
> In case anyone has the issue where `yay-bin` and `yay` aren't installed:
> 
> For me, my packages were named `yay-git` and `yay-git-debug`, so just run `sudo pacman -Rns yay-git yay-git-debug` instead of the original line.

Thanks for sharing that.

**Comment by SupinePandora43** [comment]
Happened on x86-64 yay`12.4.2-1` too.
why yay has to be manually rebuilt for it to be fixed?

**Comment by chadnpc** [comment]
> Happened on x86-64 yay`12.4.2-1` too. why yay has to be manually rebuilt for it to be fixed?

Pretty much.

```bash
sudo pacman -Rns yay
sudo pacman -S --needed git base-devel
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
```
This fixed it for me.

**Comment by ecospecifier** [comment]
Thanks everyone, following this thread fixed it for me too with some changes to names as suggested:

`sudo pacman -Rns yay-bin yay-debug`

**Comment by Tritium55** [comment]
This does not fix it for me. After removing yay and trying to rebuild, the build process fails with all connections refusing. Maybe my university WiFi blocks the domains the pkgbuild file is trying to access. I will try again later at home. 
All of this is happening on Pacman version 7.0.0 btw.

Edit: Trying to build in another network did not fix my issue. I think the build process is trying to fetch some stuff from https://proxy.golang.org/ and getting it's connection refused (I don't know why that is and how to replicate the issue)

**Comment by adamency** [comment]
@alibaghernejad @alainQtec Please stop recommending people to use `-n` in `pacman -Rs yay`. This is absolutely unneeded and inexperienced people (i.e. about 80% of people coming here from a short glance at the thread) could lose their configurations when there was absolutely no need to delete it in 99.9% of cases.

Please stop copy-pasting options everywhere simply because you saw them one time in some specific thread online. Assess the relevance of each option to the topic at hand before sharing snippets online, please, for the sake of the community.

**Comment by bugfloyd** [comment]
In my case, I discovered that there were no bin or git packages of yay installed. I searched for installed yay packages using:
```
pacman -Q | grep yay
```
It turned out I had `yay` and `yay-debug` installed. Reinstalling them resolved the error.
```
sudo pacman -Rs yay yay-debug
sudo pacman -S --needed git base-devel 
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si 
```

**Comment by betrixed** [comment]
After a removal and reinstall from git, as described here, on Arch Linux arm (endeavoros actually) fixed with
cd /lib
ls -l *alpm*
sudo ln -s libalpm.so.15.0.0 libalpm.so.13    # Something like this is probably all that is required

**Comment by kentslaney** [comment]
```bash
sudo ln -s /lib/libalpm.so '/lib/'`ldd "$(which yay)" | grep -o 'libalpm.\S* ' | head -1 | cut -d' ' -f1`
```
