### ISSUE TITLE
Korean translations (ko.po) not properly formatted

### ISSUE THREAD

**Issue by scarf005** [Jguer/yay#2517]
### Affected Version

yay v12.4.2 - libalpm v15.0.0

### Describe the bug

```
📦[scarf@arch-distrobox yay]$ LANG=ko_KR.UTF-8 yay -S tlrc
:: %!s(int=2)에 사용할 수 있는 &{%!d(string=cargo) %!d(string=) %!d(string=) 7059752343256422140 1}개 공급자가 있습니다:
:: 저장소 extra
    1) rust 2) rustup 

숫자를 입력하세요 (기본값=1): 
==> ^C
📦[scarf@arch-distrobox yay]$ LANG=c yay -S tlrc
:: There are 2 providers available for cargo:
:: Repository extra
    1) rust 2) rustup
```

### Reproduction Steps

1. follow https://github.com/Jguer/yay?tab=readme-ov-file#source
2. run `LANG=ko_KR.UTF-8 yay -S tlrc`
3. the formatting is not properly applied unlike english one.

https://github.com/Jguer/yay/blob/138c2dd6cdf1a3738ee18f6bf94c1e8c37e15dc4/po/ko.po#L433-L435

### Expected behavior

expected: `cargo에 사용할 수 있는 2개 공급자가 있습니다:`
actual: `%!s(int=2)에 사용할 수 있는 &{%!d(string=cargo) %!d(string=) %!d(string=) 7059752343256422140 1}개 공급자가 있습니다:`

### Output

```sh
{
        "aururl": "https://aur.archlinux.org",
        "aurrpcurl": "https://aur.archlinux.org/rpc?",
        "buildDir": "/home/scarf/.cache/yay",
        "editor": "",
        "editorflags": "",
        "makepkgbin": "makepkg",
        "makepkgconf": "",
        "pacmanbin": "pacman",
        "pacmanconf": "/etc/pacman.conf",
        "redownload": "no",
        "answerclean": "",
        "answerdiff": "",
        "answeredit": "",
        "answerupgrade": "",
        "gitbin": "git",
        "gpgbin": "gpg",
        "gpgflags": "",
        "mflags": "",
        "sortby": "votes",
        "searchby": "name-desc",
        "gitflags": "",
        "removemake": "ask",
        "sudobin": "sudo",
        "sudoflags": "",
        "version": "12.4.2",
        "requestsplitn": 150,
        "completionrefreshtime": 7,
        "maxconcurrentdownloads": 1,
        "bottomup": true,
        "sudoloop": false,
        "timeupdate": false,
        "devel": true,
        "cleanAfter": false,
        "keepSrc": false,
        "provides": true,
        "pgpfetch": true,
        "cleanmenu": true,
        "diffmenu": true,
        "editmenu": false,
        "combinedupgrade": true,
        "useask": false,
        "batchinstall": false,
        "singlelineresults": false,
        "separatesources": true,
        "debug": false,
        "rpc": true,
        "doubleconfirm": true,
        "rebuild": "no"
}
```

**Comment by Jguer** [comment]
Hey @scarf005 , this can be modified in https://www.transifex.com/yay-1/yay/

**Comment by scarf005** [comment]
tho this doesn't seem to be translation string issue: as seen on above po, format strings are correctly written both for english and korean. yet it's getting weirdly formatted...

```
 msgid "There are %d providers available for %s:" 
 msgstr "%s에 사용할 수 있는 %d개 공급자가 있습니다:" 
```

**Comment by Jguer** [comment]
~~unfortunately the order must be kept and can't be exchanged in translation~~

EDIT: I researched a bit and maybe positional variables can be used: 

```
msgstr "%2$s에 사용할 수 있는 %1$d개 공급자가 있습니다:"
```

**Comment by scarf005** [comment]
oh, right, yes it seems to be positional argument problem. i'll try find out how to change format string and apply changes to other po. would it be possible to edit `.po` in-repo directly?

**Comment by Jguer** [comment]
we can try `.po` edits directly @scarf005 , if it doesn't propagate, I'll do it manually
