### ISSUE TITLE
yay -Pu shows no updates

### ISSUE THREAD

**Issue by eyal0803** [Jguer/yay#253]
#### Affected Version
yay v4.505

#### Issue
`yay -Pu` produces no output while `checkupdates` does.

I'd be happy to not update my system for a few days so I'll be able to to some test for you guys. So if there's any data I'm able to provide please let me know.

**Comment by Morganamilo** [comment]
I'll take a look later when I can, until then a bisect is usually the easiest way to find regressions.

**Comment by eyal0803** [comment]
A bisection of what?

**Comment by Morganamilo** [comment]
`git bisect` super useful command.

**Comment by Morganamilo** [comment]
Also `yay -Pu` works for me. Both on the latest tag and latest commit. Maybe you have not refreshed your databases?

**Comment by eyal0803** [comment]
I just refreshed the databases and it shows the updates. How comes that `checkupdates` shows the updates while `yay -Pu` requires a refresh?

It bothers me because I use `yay -Pu`'s output as a list of packages to update for an extension for GNOME, and I got used to it being reliable (before using yay).

**Comment by Morganamilo** [comment]
well updating the database require root. It looks like `checkupdates` runs `pacman -Sy` in a fakeroot and moves the db path to somewhere in /tmp so it can be accessed by the user.

Seems like a lot of effort to implement this in Yay when check updates exists. AUR updates don't need a database update though so if --aur is implemented maybe you could mix and match `yay -Pu` and `checkupdates`.

**Comment by eyal0803** [comment]
Sounds fair. I'll keep an eye out for a potential update. Thanks.

**Comment by Morganamilo** [comment]
Little crude and hacky but this would probably work:
```sh
rm -rf /tmp/yaydb
cp -rf /var/lib/pacman /tmp/yaydb
fakeroot yay -Sy --dbpath /tmp/yaydb &>/dev/null
yay -Pu --dbpath /tmp/yaydb
```
