### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by Manu-sh** [Jguer/yay#2547]
### Steps

```sh
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
sudo pacman -Rncus yay
sudo pacman -U yay-12.4.2-1-x86_64.pkg.tar.zst
```

### Describe the bug

![immagine](https://github.com/user-attachments/assets/0fdb1974-93b4-417e-8274-d184c6e00c55)

### Output
Istruzione non consentita (core dump creato)

**Comment by Manu-sh** [comment]
steps

```sh
git clone https://aur.archlinux.org/yay.git
makepkg -si
sudo pacman -Rncus yay
sudo pacman -U yay-12.4.2-1-x86_64.pkg.tar.zst
```

**Comment by Jguer** [comment]
Hey manu, I can't reproduce this issue.

Can you ensure `~/.config/yay/config.json` doesn't exist and try it out.

If that does not work, can you try and create the file  `~/.config/yay/config.json` with 

```
{
"debug":true
}
```

**Comment by Manu-sh** [comment]
i get the same error in both cases

**Comment by Manu-sh** [comment]
Hi @Jguer tonight I investigated a bit and after some tests I found out that the problem was in `/etc/makepkg.conf` I still don't know the exact reason, anyway replacing with the new version provided by the arch packages (`/etc/makepkg.conf.pacnew`) and rebuilding yay the segfault disappeared, so im going to close this issue, thankyou :)
