### ISSUE TITLE
Naming convention for yay's AUR packages

### ISSUE THREAD

**Issue by maximbaz** [Jguer/yay#26]
Feels like the `yay` AUR package should really be named `yay-git`, while the `yay-bin` should be called just `yay`. Not sure if it is possible to rename packages, but if you agree on this suggestion, consider doing it earlier than later 🙂

Just a suggestion, maybe it's something to do after #17.

**Comment by Jguer** [comment]
yes :shame:, I realized that early on when yay was smaller but couldn't be bothered.

Checklist:
- When on same commit, bin and git should have same md5
- Compile 32bit version and ARM(I think it works) for bin version.
- Change `yay-bin pkgbuild` to yay
- Create yay-git from `yay pkgbuild`
- Request deletion of yay-bin

**Comment by rmarquis** [comment]
Not really. The `-bin` suffix is kind of standard in the AUR, and is self-explanatory: yay-bin is a precompiled package. `yay` would be adequate for a stable version of the `yay-git`.

**Comment by maximbaz** [comment]
Actually yes, you are right. Let me correct:

- `yay-git` should be based on the git repository, building on client's host.
- `yay` should be based on [Source code (tar.gz)] of the [latest release](https://github.com/Jguer/yay/releases/latest), but still building on client's host.
- `yay-bin` is author's pre-compiling binaries, only this one is not building on client's host.

**Comment by Jguer** [comment]
So nothing changes much really (because I kept master on-pair with release). I'll make @maximbaz changes so `yay` conforms to AUR standards.

**Comment by maximbaz** [comment]
@Jguer I'm running the build from `dev` branch for quite a while now, it has many great improvements and I think it is stable enough (besides #32, which I didn't check if it is reproducible on `master` branch). 

Would you consider merging `dev` in `master`, making a release and doing the updates to AUR packages mentioned above? I could give a hand with any of these items if you want.

**Comment by Jguer** [comment]
I still wanted to tweak this release more but I agree, the fixes included in this version heavily outweigh the possible bugs on release. I am very busy until the end of this week. For now I'll merge dev in master and tag the release.

Tomorrow I'll update the PKGBUILDs and hopefully I can finish the config system next week.
