### ISSUE TITLE
yay -Sy (pacman -Sy) ask for sudo and yay -Pn doesn't refresh

### ISSUE THREAD

**Issue by unai-ndz** [Jguer/yay#263]
This way isn't possible to check for aur updates in a script.
With pacman you can check without elevated privileges using checkupdates.
Cower, trizen and pacaur can do this but they also can separate aur and pacman operations so I guess is harder to implement here without implementing that first.

**Comment by unai-ndz** [comment]
I think that would make it cleaner, but doesn't really change the need for sudo in yay -Sy and -Qu doesn't refresh the database either. Something like cower -u (Check foreign packages for updates in the AUR) would solve this problem.

I can duplicate /usr/bin/checkupdates, replace pacman -Qu in one of them and compare the outputs to get the number of aur and native updates for a temporary fix but I don't like it as a permanent one.

**Comment by Morganamilo** [comment]
I added `-Qu` support in #266 so you should be able to do `checkupdates && yay -Qum` to achieve what you want.
