### ISSUE TITLE
yay -Yc removes optionally depended packages and does not remove them recursively

### ISSUE THREAD

**Issue by ratorx** [Jguer/yay#268]
#### Affected Version

yay v4.505 (from the AUR)
yay v3.373 (build from source)

#### Issue
yay -Yc attempts to uninstall packages that are optionally depended on by another package. Also, dependencies are not removed recursively (i.e. `yay -Yc` tries to remove the set of packages that would be removed by `pacman -R $(pacman -Qttdq)` rather than the more useful (in my opinion) `pacman -Rns $(pacman -Qtdq)`)

Is this a deliberate choice?

In addition to this, it doesn't warn when removing optional packages like `pacman -Rns $(pacman -Qttdq)` does.

#### Steps to reproduce

1. Install any package which has optional depends and then the optional dependency (E.g. `neovim` and `python-neovim`). In particular, install using `pacman -S neovim` and `pacman -S --asdeps python-neovim`.
2. Use `yay -Yc`

#### Possible fixes
* Use pacman commands to remove dependencies (Make `yay -Yc` run `pacman -Rns $(pacman -Qtdq)` instead of a call to libalpm).
* Use `alpm_pkg_compute_requiredby` as well as `alpm_pkg_compute_optionalfor` from libalpm when checking each candidate package for dependencies.

**Comment by Morganamilo** [comment]
This is a thing I noticed a while ago but hadn't really thought to do anything about it because I hardly use this feature so have focused on other things.

Now there's an open issue that ups the priority of fixing it, I'll look into it soon.

**Comment by ratorx** [comment]
If there are more important issues to fix, I can have a go at this one. The alpm fix seems pretty simple to implement, although will require a commit in the go-alpm repo as well. Just wanted to make sure it wasn't deliberate before making a pull request.

**Comment by Morganamilo** [comment]
I'm assuming it was just done that way because it was easier to implement. Even if it was deliberate, feedback is always welcome and we're open to change. I would rather it keep optional dependencies too.

If you're gonna implement this yourself I have a couple things I'd like to see it do:
- As mentioned don't remove optional deps.
- Do remove optional deps if `c` is passed twice
- Instead of relying on  `-Rs` to recursively remove deps, figure out the deps recursively inside of yay. This allows yay to print everything It's going to remove.
- Print the total remove size

**Comment by ratorx** [comment]
Should yay print the total remove size before passing the arguments to pacman? This seems slightly redundant as pacman already prints the total removed size when `pacman -R` is run.

**Comment by Morganamilo** [comment]
I was thinking before the `==> Confirm Removal?  [Y/n] ` bit. But I guess you could get rid of that and just use the Pacman prompt. I've realised that using `VerbosePkgList` makes Pacman show the install size for each individual package so I think it would be best to remove all Yay output and printing for `-c`. Just have it calculate what packages to remove and pass it to Pacman.

>Instead of relying on -Rs to recursively remove deps, figure out the deps recursively inside of yay. This allows yay to print everything It's going to remove.

This point is now invalid. You could just keep it how it is.

So as far as code changes go, all you have to is add `-u` to `-R` in the passToPacman() call and remove the Yay output.

**Comment by ratorx** [comment]
Ahh that's unfortunate, I have already implemented the recursive bit in yay. However, I agree that using `VerbosePkgList` seems simplest.

**Comment by Morganamilo** [comment]
Yeah sorry :(, just never thought of it until now.

**Comment by ratorx** [comment]
Sorry, my pull request wasn't clear on go-alpm, I needed that function to fix the this issue, it's not fixed yet. Can you please re-open the issue?

**Comment by Jguer** [comment]
Haha, forgot how linked this was.

**Comment by styles784** [comment]
`yay -Yc` still attempts to remove some optional dependencies on Arch Linux. It doesn't target all optional dependencies, because `yay -Ycc` finds even more packages, but it is unclear how yay decides which optional dependencies to incorrectly target when it should be leaving all of them alone
