### ISSUE TITLE
Download everything and ask all the questions first, then build and install

### ISSUE THREAD

**Issue by maximbaz** [Jguer/yay#27]
_I saw you have this on the [projects](https://github.com/Jguer/yay/projects/1) page, I'm creating this issue for tracking purposes, something to subscribe to, in order to get updates when this works begins._

When installing or upgrading packages, it would be really nice to get all the questions asked first (do I want to edit PKGBUILD, install dependencies, confirm conflicting package replacement, etc.), answer to all of them in one go and let the installation proceed without further interruption.

**Comment by Jguer** [comment]
Yes, I wanted to get that working before releasing `yay v2` but exam season hit a little earlier than expected.
 
- Ask all edit PKGBUILD
- Install all dependencies (Package conflicts are all handled by pacman I think)
- AUR dependencies are installed with --noconfirm on pacman but
- final built packages are moved to `${yay-build-dir}` and one last confirm to install them all.

**Comment by rmarquis** [comment]
>  (Package conflicts are all handled by pacman I think)

Unfortunately, you'll have to handle this by yourself then bypass pacman prompts if you want to ask all the questions first - otherwise you'll have to deal with a yaourt-kind of linear prompts through the whole building process.

**Comment by AladW** [comment]
Even if you ask all questions first, you might have to confirm 100's of times on large dependency chains. Some better approach is to have the user deal with it (by having a "download only" stage, see https://github.com/trizen/trizen/issues/8) or integrate with a suitable file manager.

Also the issue with conflicts pretty much disappears when you use a local repo (I've hardly seen them building 2000+ packages anyway), but I guess that's out of scope for this issue.

**Comment by maximbaz** [comment]
True, although in my personal experience I haven't seen such long dependency chains, I think in 99% of cases you don't need to confirm more than 10 packages at once, and having an integrated approach to answer up to 10 questions and let yay proceed would be very useful 🙂

**Comment by 132ikl** [comment]
Any ETA on this? Liking yay as an alternative to the now unmaintained pacaur but this is definitely my biggest issue with yay.

**Comment by Mayurifag** [comment]
+1 here.

Also, sorry for offtopic, but is there any way to list searched packages the same way like it was in yaourt — I meant, starting from first number and list all them from top to bottom?

**Comment by maximbaz** [comment]
@Mayurifag if you still seek the answer to the offtopic question: `--topdown` will change the sorting order, and since https://github.com/Jguer/yay/pull/83 the numbering always starts from `1` (not released yet, only in master).

**Comment by Mayurifag** [comment]
@maximbaz can i default `--topdown` behaviour in configuration file?

**Comment by maximbaz** [comment]
Yes, actually because `--topdown` is listed in the `Permanent configuration options` section of the `$ yay --help`, after you use `--topdown` at least once, yay automatically updates the config and `--topdown` becomes default for plain `yay` - that is, until you explicitly use `--bottomup`.

In the `~/.config/yay/config.json` the `--topdown` refers to `sortmode: 1`, while `--bottomup` refers to `sortmode: 0`.
