### ISSUE TITLE
Better dependency resolving

### ISSUE THREAD

**Issue by 4shadoww** [Jguer/yay#279]
#### Affected Version
yay v4.505

#### Issue
For example you want to install foo-bin package which has dependency bar. But you want to install bar-bin dependency instead of compile bar from sources. Far as I know here isn't option to choose should yay use regular packages, bin or git. You might think you can just do <code>yay -S bar-bin foo-bin</code> to install binaries, but you can't do that because yay doesn't check that bar-bin provides bar. So yay will end up installing bar-bin bar and foo.(of course that doesn't work because bar-bin conflicts with bar)

So it would be nice to have option what would let you choose should yay use bin or git packages if there is any available. And fix to the problem what I mentioned earlier.

#### Steps to reproduce

Here is real world example:
1. <code>yay -S mingw-w64-binutils-bin mingw-w64-headers-bin mingw-w64-crt-bin mingw-w64-winpthreads-bin mingw-w64-gcc-bin</code>

**Comment by Morganamilo** [comment]
Once Yay finds a valid provider for something it ignores all other packages that provide the same. Having direct targets overide dependencies for provides would sure be a good idea. Thanks.

The option to let the user choose is only possible if the [rpc](https://aur.archlinux.org/rpc) is updated to support provides.

**Comment by Morganamilo** [comment]
As a workaround for `yay -S bar-bin foo-bin` `yay -S bar-bin && yay -S foo-bin` should work.

**Comment by 4shadoww** [comment]
But doesn't rpc already have support to provides? When I do this query https://aur.archlinux.org//rpc/?v=5&type=info&arg[]=mingw-w64-gcc-bin the reply has the provides key and the right value on it.

**Comment by Morganamilo** [comment]
Sure you can search a package by name and get its provides. You can not search a provide and get the matching packages.

**Comment by 4shadoww** [comment]
You are right. Would it be too expensive/slow to check does package have *-bin *-git version and check it that way?

**Comment by Morganamilo** [comment]
Checking for *-git and *-bin versions wouldn't be too expensive, but checking for other stuff like `jdk` provides java-runtime is not feasible.

I would rather push for provides support in the rpc than develop half a solution.
