### ISSUE TITLE
Weird sort order when using yay -Syu

### ISSUE THREAD

**Issue by YamashitaRen** [Jguer/yay#289]
yay -Syu doesn't seem to honor "sortmode".

```
$ yay -Syu
:: Synchronisation des bases de données de paquets...
 core est à jour
 extra est à jour
 community est à jour
 multilib est à jour
 archlinuxfr est à jour
 archlinuxcn est à jour
 alucryd est à jour
:: Querying AUR...
==> Missing AUR Packages: avinaptic2 quassel-icons-symlink trpc-libs sddm-numix-theme-git trpc
==> Out Of Date AUR Packages: openvpn-update-resolv-conf-git jbidwatcher
:: Searching databases for updates...
:: Searching AUR for updates...
:: 84 Packages to upgrade.
 84 archlinuxcn/pcsx2-git                  1.5.0.r2329.2ad5db227-1 -> 1.5.0.r2330.0e83b89db-1
 83 community/argyllcms                                    1.9.2-2 -> 2.0.0-1
 ...
 72 community/telegram-desktop                            1.2.14-1 -> 1.2.14-2
 71 core/gcc                                      7.3.1+20180312-1 -> 7.3.1+20180312-2
 ...
 62 core/netctl                                             1.15-1 -> 1.16-1
 61 extra/adwaita-icon-theme                              3.26.1-1 -> 3.28.0-1
 ...
 13 extra/zenity                                          3.26.0-1 -> 3.28.0-1
 12 multilib/lib32-at-spi2-atk                            2.26.1-1 -> 2.26.2-1
 ...
  2 multilib/lib32-pango                                 1.40.14-1 -> 1.42.0-1
  1 aur/anki20-bin                                        2.0.47-1 -> 2.0.50-1
==> Packages to not upgrade (eg: 1 2 3, 1-3, ^4 or repo name)
==> ^C
```

It seems to use a tweaked alphabetical order. It can randomly use a true alphabetical order too.
Expected order (top to bottom) would be : 
- core, extra, community, multilib, archlinuxcn, aur if using topodown
- aur, archlinux, multilib, community, extra, core if using bottomup

**Comment by Morganamilo** [comment]
Personally I always saw sortmode as a thing that only really applied to searches. Searches usually get a ton of results to the point where you cant fit them all on screen. So I always found it nice that Yay could order stuff so the most relevant stuff was right above your cursor and worked its way up.

When it comes to the upgrade menu its alphabetical because all the info is just as relevant so I never saw a need to make it like the searches.

That being said, if you want it in reverse order it could be added in pretty easily.

>It seems to use a tweaked alphabetical order. It can randomly use a true alphabetical order too.
What do you mean by this though? do you have an example? This sounds like a bug.

The way it should work is: everything is sorted alphabetically, with repo names taking priority over package name. Also aur updates are always after repo updates.

**Comment by YamashitaRen** [comment]
Yes, this is a cosmetic issue. Nothing very urgent but I like to see my package sorted by "importance" (core and aur being the most and less important respectively) when I update them.
Alphabetical sort feels "muddled".

> It seems to use a tweaked alphabetical order. It can randomly use a true alphabetical order too.
> What do you mean by this though? do you have an example? This sounds like a bug.
Can't tell you how to reproduce. Can't tell if it was on stable or git either.
I got two types of sorts for the results.
- Everything sorted alphabetically from bottom to top. AUR at the bottom. Very common.
- Everything sorted alphabetically from top to bottom. AUR at the bottom. Very uncommon. This is the one I used for the bug report.

**Comment by Morganamilo** [comment]
It went from reverse alphabetical to alphabetical recently, I think this 'bug' was just an update.

I do think it would be nice to sort via pacman.conf priority instead. Shouldn't be too hard to do either.

**Comment by YamashitaRen** [comment]
Yes, pacman.conf priority would be good too.

**Comment by Morganamilo** [comment]
Surprisingly easy to implement ;)

![image](https://user-images.githubusercontent.com/16593899/37882403-fa1a0b3a-309a-11e8-8465-3dd3a54f59ae.png)

I'll have to wait until the next cycle to merge it though.

**Comment by YamashitaRen** [comment]
Right, unlike the package search, I don't see much advantage in having inversely sorted packages for updates.

On the other hand, people may be confused to have their sortmode honored when searching but not when updating...
It's probably better to have the flags honored, for consistency sake.

**Comment by Morganamilo** [comment]
I was thinking that but I and assume others like to use bottomup for searching and topdown for the upgrade menu. So I could add a second flag for the upgrade order but that seems cumbersome. Plus it's already not respected and no ones complained thus far.

**Comment by YamashitaRen** [comment]
Yes, was thinking about this too :D 
Both solutions have their merits if you don't want to add cumbersomeness. May be better to let things stay like that until someone complain.

**Comment by Morganamilo** [comment]
Yep that exactly my plan.

**Comment by mindyourlifeguide** [comment]
> Surprisingly easy to implement ;)
> 
> ![image](https://user-images.githubusercontent.com/16593899/37882403-fa1a0b3a-309a-11e8-8465-3dd3a54f59ae.png)
> 
> I'll have to wait until the next cycle to merge it though.

How do I enable this sorting?

**Comment by arstum** [comment]
> > 非常容易实现；）
> > ![图片](https://user-images.githubusercontent.com/16593899/37882403-fa1a0b3a-309a-11e8-8465-3dd3a54f59ae.png)
> > 不过，我必须等到下一个周期合并它。
> 
> 这个例子如何启用？

yay XXX --sortby <votes|popularity|id|baseid|name|base|submitted|modified>
