### ISSUE TITLE
Conflict between AUR and unoffical repos

### ISSUE THREAD

**Issue by YamashitaRen** [Jguer/yay#291]
Yay doesn't let you install a package from AUR if a package with the same name exists in a repo.

How to reproduce : 
Add [archlinuxcn](https://wiki.archlinux.org/index.php/unofficial_user_repositories#archlinuxcn) repo.

`yay -S aur/yay-git`

What happens : 
yay-git from archlinuxcn is getting installed.

What should happen : 
yay-git should be built from AUR.

Same issue if you use `yay yay-git` and input aur/yay-git's number.

**Comment by Morganamilo** [comment]
This should be working in master.

**Comment by YamashitaRen** [comment]
Wow sorry.
I thought I tested it on master but guess I didn't...

**Comment by Morganamilo** [comment]
Probably because you were getting an outdated version from archlinuxcn :P 

How does that work though? A repo can't really host a recompiled -git package. Unless they have automated building or something.

**Comment by YamashitaRen** [comment]
I don't know either, but there is probably automated building involved like you says.

**Comment by Morganamilo** [comment]
I gave the repo a check and `yay-git` was last updated on march 22nd and is currently around 40 commits behind. So I would recommend avoiding it.

**Comment by YamashitaRen** [comment]
Don't worry, I didn't enable it for yay ;)
