### ISSUE TITLE
Annoying Could not find all required packages

### ISSUE THREAD

**Issue by bitwave** [Jguer/yay#299]
#### Affected Version
yay v5.608 (yay package from AUR)
yay v5.608.r2.gec066fd (yay-git from AUR)
#### Issue
Running yay -Syu
Expected behavior: update db & upgrade all packages
Real behavior: update db & complains about packages which cannot be found, because they are installed by hand.
#### Steps to reproduce
1. Install a package not in repo or AUR
2. yay -Syu
3. see error & it is not possible to upgrade packages

**Comment by bitwave** [comment]
Problem was the img2pdf-git package:
```
==> Error: Could not find all required packages:
	qt-virustotal-uploader-git
	img2pdf>=0.2.3
	hopperv4
```
After removing it works.

**Comment by Morganamilo** [comment]
Yay now checks versioned dependencies, it sounds like something might now be working 100%. Could you send your package list with `pacman -Qq`?

**Comment by bitwave** [comment]
the one and only package with versioned deps was img2pdf-git.

**Comment by Morganamilo** [comment]
Oh I think I see now. `img2pdf-git` is a VCS package so if you do `yay -Si img2pdf-git` it shows it provides `img2pdf=0.2.1` which doesn't meet the dependency. But of course that's not the real version and will change after pkgver is run.

**Comment by Morganamilo** [comment]
Should be fixed now.

**Comment by bitwave** [comment]
Thanks!
