### ISSUE TITLE
[pkgbuild] arch arm -> armv7h

### ISSUE THREAD

**Issue by peribothron** [Jguer/yay#30]
(maybe this should be an aur comment instead)

```
arch=('i686' 'x86_64' 'arm')
```
```
$ makepkg -s
==> ERROR: yay is not available for the 'armv7h' architecture.
```
it builds fine with
```
arch=('i686' 'x86_64' 'armv7h')
```
i notice yaourt uses
```

arch=('any')
```

**Comment by Jguer** [comment]
[PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=yay)

Added missing architectures

**Comment by yangxuan8282** [comment]
@Jguer how about add armv7h and aarch64 in release section?

**Comment by Jguer** [comment]
I would like to do that, I've tried automating virtualization with QEMU and then automatic building but it was a mess I was unsatisfied with. 

Cross compiling has proven to be a pain in the ass because of `go-alpm`. If you find me a solution for cross-compiling `go-alpm` or an effective build system I'll be happy to add them to the release

**Comment by yangxuan8282** [comment]
@Jguer 
quote from Works on Arm:

The Works on Arm provides free access to state-of-the-art computing resources for open source developers working to port, test, and build their software on Armv8 servers. 

Maybe you can ask help from them by create a issues in this [repos](https://github.com/WorksOnArm/cluster). The alpine linux seems also use their arm server. And their armv8 server is beast, not sure if same as packet one( 96 core, 128G RAM, build rpi3 64bit kernel within 3 minutes). By the way, their server seems not support build for armv7h.

**Comment by schferbe** [comment]
> I would like to do that, I've tried automating virtualization with QEMU and then automatic building but it was a mess I was unsatisfied with.

Have you tried [simonpi](https://github.com/M0Rf30/simonpi)? It makes creating a Raspberry Pi QEMU system a lot easier.

**Comment by Jguer** [comment]
I haven't but I will, it looks good

**Comment by Jguer** [comment]
@schferbe @yangxuan8282  I have packaged yay-bin with aarch64 builds.

**Comment by yangxuan8282** [comment]
thanks, will test it later
