### ISSUE TITLE
Allow for setting custom cache dir different than build dir

### ISSUE THREAD

**Issue by FedericoYundt** [Jguer/yay#303]
#### Affected Version
yay v5.608

#### Issue
According to yay manual about `BUILD DIRECTORY`:

> This directory is used to store downloaded AUR Packages as well as any source files and built packages from  those packages

The problem is that `tmpfs` is often used for building but cache should often be persistent. Therefore I propoose adding `cacheDir` to available options in config which could be selected independently of `buildDir` .

**Comment by Morganamilo** [comment]
you can set the build dir via makepkg.conf and makepkg will build there. In that case Yay's build dir will effectively be just a cache dir.

**Comment by Morganamilo** [comment]
I'm assuming this is working for you, if not feel free to re open the issue.

**Comment by FedericoYundt** [comment]
Yeah, that works. The docs weren't clear to me in that case.
