### ISSUE TITLE
[Feature] Do a full system upgrade (-Syu) if no flags are given

### ISSUE THREAD

**Issue by Trollwut** [Jguer/yay#305]
Hi folks!

Man, this AUR helper looks fine! I love the "packages not to update" on an update and some more features.

When running `yay` without any flags, I get this output:

    $ yay
    no operation specified (use -h for help)

Any plans on just doing a `yay -Syu` of no flags are given?

**Comment by Morganamilo** [comment]
Are you a user of `pac` by any chance? I was and I did quite enjoy that feature. I thought about adding it when I first started using Yay then just kinda forgot about it. It shouldn't be hard to add if people want this.

**Comment by Trollwut** [comment]
Yes I am :) I did some color fixing for outdated packages for that project

`yay` would be the first helper that would drive me away from abandoned `pacaur` :)

**Comment by Morganamilo** [comment]
Thanks, I did try to clone a lot of the features, batch install mainly, so even though Yay is it's own thing I do want it to be a better version of Pacaur. If you know how to program and have worked on AUR stuff before you could always go implement this yourself ;)

**Comment by Trollwut** [comment]
Never used Go language and I'm not the best programmer, but maybe I'll try it if I have a bit freetime

**Comment by DL6AKU** [comment]
Tried for a fix. First time in Go, please be gentle ;)

**Comment by Jguer** [comment]
This is a nice idea, I'll start using it myself, although it might not be the favourite for some users. I don't there will be complaints but let's see if any user prefers this an option until the next release. 

PS: thinking about it a config option to set the default OP for when no OP is passed also sounds nice (and defaulting to -Syu)
