### ISSUE TITLE
yay --stats does nothing, even though the man page says it should.

### ISSUE THREAD

**Issue by DL6AKU** [Jguer/yay#306]
#### Affected Version
yay v5.608.r8.g42b7df4

#### Issue
When running ```yay --stats``` there is no output even though the man page says it should output statistics. It just quietly exits but with exit code 0.

This might be related to #307

#### Steps to reproduce
1. Run ```yay --stats; echo $?```
2. Observe no output and exit code 0

**Comment by Morganamilo** [comment]
That was changed but it appears the example was forgotten. Use either `yay -Ps` or `yay -P --stats`.

**Comment by DL6AKU** [comment]
Ah, nevermind, I misread the man page. It's already there under the correct subsection. That's why #307 is important.

**Comment by Morganamilo** [comment]
It's correct there but still wrong under the examples section so I get the confusion.

**Comment by andycowl** [comment]
I'm just a humble user and recent Arch convert. I'm thoroughly enjoying yay but I'm confused. The man page for yay (v5.675) states:-

 -s --stats
           Displays information about installed packages and system health. If
           there are orphaned, out-of-date or packages that no longer exist on
           the AUR warnings will be displayed.

The Print option says
       -P, --print
           Perform yay specific print operations.

Intuitively, I expect 'yay stats' to display output. It doesn't matter that it's a 'yay specific operation'. It's not clear to me why '-P' is needed. I am incredibly lazy (that's precisely why I like yay defaulting to 'yay -Syu') and that ('-P') is another two tiresome characters to type.

Displaying stats is not the sort of operation that is scripted to simply check an exit code and discard the output. It's a command for users to display useful statistics. But it doesn't.

**Comment by Morganamilo** [comment]
If we chucked everything in one namespace it would be very crowded. Putting them in different namespaces makes it easier to add more commands in the future and allows more short flags.

For example `yay -Yc` or simply `yay -c` and `yay -Pc` are two separate commands. You couldn't do this if they were in the same namespace.

Plus `yay -Ps` is shorter than `yay stats` anyway.

>Displaying stats is not the sort of operation that is scripted to simply check an exit code and discard the output. It's a command for users to display useful statistics. But it doesn't.

I really don't get what you mean by "But it doesn't".
