### ISSUE TITLE
Does not install AUR package on the first try when AUR dependencies exist

### ISSUE THREAD

**Issue by maximbaz** [Jguer/yay#32]
I've been seeing this bug for quite a while now (I'm running build from `dev` branch), but I was never sure it is not just a random fluke. Now I have a reliable way to reproduce the issue.

- Remove all unused dependencies: `$ yay -Cd`
- Take an AUR package that has AUR dependency, I believe it doesn't have to be `-git` package but the smallest package I happen to have now for this example is `compton-conf-git` (the AUR dependency is `lxqt-build-tools-git` - make sure it is not installed).
- `yay -S compton-conf-git` shows repository dependencies `cmake` and `qt5-tools`, as well as AUR dependency `lxqt-build-tools-git`.
    - Repository dependencies are installed first.
    - AUR dependency is installed next.
    - After `lxqt-build-tools-git` is installed, the installation finishes "successfully".
    - The `compton-conf-git` is not installed, only its dependencies.
- `yay -S compton-conf-git` again, and this time because all the dependencies are already installed, the `compton-conf-git` will actually be installed.

To reproduce again: `yay -Rs compton-conf-git; yay -Cd`.

I think installation finishes after one successful installation of AUR package, regardless of whether it was just one of dependencies or not. 

I remember now that I was installing `fonts-meta-extended-lt` which has like 10 of AUR dependencies, and I had to rerun `yay -S fonts-meta-extended-lt` 10 times before the installation finally finished.

**Comment by Jguer** [comment]
Package building needs an overhaul, I'll start working on a more efficient scheme that allows #27 and on the way I should notice what's wrong with the current build process, probably taking a page or two pacaur. 
Meanwhile, if you find other requirements for the build process mention them so adding them doesn't imply rewriting a whole block of Aur.Install.

**Comment by maximbaz** [comment]
Will do. Ping me if you want an early feedback or another pair of eyes for a code review :+1:

**Comment by maximbaz** [comment]
@Jguer are you planning to merge `flatten` branch any time soon? 😉 
I was using `flatten` for a long time, but now I want to also have the fix for this bug in my build 🙂

**Comment by Jguer** [comment]
I still haven't been able to finish the install spec, but that deserves a branch of its own. I'll merge the flatten branch either way, and probably tag it.
