### ISSUE TITLE
"yay -Syu --help" shows help but then does not exit and instead continues to sysupgrade

### ISSUE THREAD

**Issue by DL6AKU** [Jguer/yay#323]
#### Affected Version
yay v5.608.r27.g0ccfd1a

#### Issue
When I run ```yay -Syu --help```, it shows the help but then does not exit and instead continues to sysupgrade.

When asking for --help, yay should print the help then exit.

#### Steps to reproduce
1. Run ```yay -Syu --help```
2. Help text gets printed but
3. sysupgrade is attempted.

**Comment by Morganamilo** [comment]
I don't know how you manage to think of this stuff, not that I'm complaining, I'm glad some one is reporting all this. This dev cycles seems to be especially buggy thanks to the changes to the install algorithm. 

Thanks for taking your time to report all these.
