### ISSUE TITLE
Could not find built package

### ISSUE THREAD

**Issue by phiresky** [Jguer/yay#333]
#### Affected Version
yay v5.608.r37.g6eb3dcc

#### Issue

When `PKGEXT=.tar` is set in `~/.makepkg.conf` (or /etc),  yay always fails with `Could not find built package teamviewer-13.1.3026-9-x86_64.pkg`. This seems to happen for all packages. It's fixed when removing `PKGEXT=.tar`

PKGEXT=.tar is useful because it saves time because it prevents the built packages from needing to be compressed with `xz`.

**Comment by Morganamilo** [comment]
Shouldn't your PKGEXT be `.pkg.tar`?

**Comment by phiresky** [comment]
Uh.. should it? I've been always been using it like this, and it worked fine with yaourt, pacaur and (I think) earlier versions of yay. It also works fine with pure makepkg. But I'm not sure if it's worth it for you to have compatibility with this. If you search for it the wiki does say `.pkg.tar` but mutliple other places mention PKGEXT=.tar.

**Comment by AladW** [comment]
The default package extension is `.pkg.tar.xz`, if you just want to disable compression I have no idea why you'd remove `.pkg` in the first place.

**Comment by Morganamilo** [comment]
Yay uses the `.pkg*` extension to locate built packages which I believe is fine because .pkg* is the convention (just like Debian has .deb) and makepkg itself says "don't change unless you know what you are doing."

The only way to handle any pkgext is to read the makepkg config file which isn't worth the  effort.

Try `.pkg.tar` and if that doesn't work then we have a bug.

**Comment by AladW** [comment]
A better approach will be available in [pacman 5.1](https://git.archlinux.org/pacman.git/commit/?id=d8591dd3418d55c5736022ef003891fc03b953e0). (alternatively, you can set PKGDEST to a directory in /var/tmp/<random>).

**Comment by Morganamilo** [comment]
I'll definitely use the `--packagelist` when this is released. For now I think the current implementation is fine, there should be no real need to remove .pkg from the `PKGEXT`.
