### ISSUE TITLE
Request: Ignore not found AUR packages when update

### ISSUE THREAD

**Issue by KSXGitHub** [Jguer/yay#334]
When I use yay to update (`yay -Syu`), sometime it prints this error message and exit right away:

```
==> Missing AUR Packages: vte
==> Error: Could not find all required packages:
	vte
```

Those packages I didn't even installed, they don't exist in my system. I tried `yay -Si` and used text editor to find packages that depends on them but didn't find any (only find `vte3` which exists).

So I must use pamac to update (and it succeed).

**Comment by Morganamilo** [comment]
I believe this was fixed in the `-git` version if you want to give that a try.

**Comment by KSXGitHub** [comment]
@Morganamilo 
I am confused, `yay-git` is at version `4.505.r79.g966bb42-1`, older than `yay` and `yay-bin` (version `5.608-1`), how does older version fixes this problem?

**Comment by Morganamilo** [comment]
It is fixed on the `-git` though right?

**Comment by KSXGitHub** [comment]
yes
