### ISSUE TITLE
Feature request: `-Ss` should show difference between installed and in-repo versions

### ISSUE THREAD

**Issue by ypoluektovich** [Jguer/yay#337]
#### Affected Version
yay v5.608.r39.gec71a5b

#### Issue
Unlike pacman (and pacaur), yay doesn't say anything about the difference of installed and in-repo versions of a package.

#### Steps to reproduce
```
$ ( pacman -Ss jdk8-openjdk ; yay -Ss jdk8-openjdk ; pacaur -Ss jdk8-openjdk ) | grep 'openjdk[^-]'
extra/jdk8-openjdk 8.u162-2 [installed: 8.u144-1]
extra/jdk8-openjdk 8.u162-2 (8.1 MiB 38.0 MiB) (Installed)
extra/jdk8-openjdk 8.u162-2 [installed: 8.u144-1]
```

**Comment by Morganamilo** [comment]
I didn't know Pacman did that, thanks for pointing it out, I will for sure add this in.
