### ISSUE TITLE
Editor `emacs -nw` doesn't work

### ISSUE THREAD

**Issue by vinipsmaker** [Jguer/yay#343]
```json
{
        "editor": "emacs -nw"
}
```

Should spawn a new `emacs` instance passing the `-nw` arg.

**Comment by Morganamilo** [comment]
Currently  that would just try to execute the command `"emacs -nw"` instead of executing `emacs` and passing `-nw` as a separate arg. It shouldn't be hard to split it up on white space.

**Comment by Morganamilo** [comment]
Although thinking about it, to fit in with everything else it might make sense to have `editor` and `editorflags` config options. `$EDITOR` and `$VISUAL` should be split on whitespace either way.

**Comment by Morganamilo** [comment]
Give it a try now. Both `yay --editor emacs --editorflags -nw` and `EDITOR="emacs -nw" yay` should work.

**Comment by vinipsmaker** [comment]
yes, it works now. thanks
