### ISSUE TITLE
yay -Yc offers to remove recently updated packages

### ISSUE THREAD

**Issue by DX37** [Jguer/yay#347]
Yay 5.657 sometimes offers me to delete some critical packages, when I run `yay -Yc`.

For example, on my Raspberry Pi 3B with Arch Linux, when I'm updating `linux-raspberrypi`, which obviously contains kernel, after it running the command will offer me to delete that package with kernel.

**Comment by Morganamilo** [comment]
can you confirm its marked as explicit? `yay -Qi linux-raspberrypi`

**Comment by DX37** [comment]
@Morganamilo you talking about it?
`Install Reason  : Installed as a dependency for another package`

**Comment by DX37** [comment]
I also installed some gvfs packages on PC Arch Linux by myself, but yay offered me do delete them too, until I removed them and installed again.

**Comment by Morganamilo** [comment]
Looks like some stuff is marked wrong: 
```
pacman -Qqg base base-devel | sudo pacman -D --asexp linux-raspberrypi linux-raspberrypi-headers raspberrypi-bootloader raspberrypi-bootloader-x raspberrypi-firmware -
```

should mark a bunch of stuff as explicitly installed and catch most things if they are wrong. If you notice anything else that should be explicit mark them too.

**Comment by DX37** [comment]
@Morganamilo Thanks for help. I'll close issue now.

**Comment by Jguer** [comment]
I just marked everything I had on `-Yc` as explicit since I usually clean unneeded dependencies.
 `yay -D --asexplicit $(pacman -Qtdq)`

I really need to transition `yay` to container based testing to avoid this in the future. It's going on my TODO list for when I have a bit more time.

**Comment by Morganamilo** [comment]
I have dabbled a bit in this myself. I was trying to get some sort of testing working. I have a pkgbuild that sets up a local AUR website with a predictable database. This is good for testing resolving Dependencies via the rpc but not much else.

Ideally We should be able to set up a bunch of dud packages that basically do nothing apart from have the correct meta data for testing. Combine this with a copy of the current Pacman database and we have a full never changing set of packages. Then we simply have all the packages in cache so Yay does not need to fetch them.

This gives us free reign to control everything and has no need for an internet connection which allows us to have control of everything. Know the exact state of what should be installed, what should be explicit, ect.

Then use mikkeloscar's Arch docker with Travis and we have automated testing.

**Comment by DX37** [comment]
> I really need to transition yay to container based testing to avoid this in the future. It's going on my TODO list for when I have a bit more time.

Maybe you should use `systemd-nspawn` containers. There is one useful flag:
```
-x, --ephemeral
           If specified, the container is run with a temporary snapshot of its file system that is removed immediately when the container terminates.
```
