### ISSUE TITLE
Setting buildDir to a string not ending in a slash causes inability to install AUR packages

### ISSUE THREAD

**Issue by therealfarfetchd** [Jguer/yay#353]
#### Affected Version
yay v5.675

#### Issue
Installing a package from AUR when the buildDir doesn't end in a slash tries to access `/home/me/.cache/yay<packagename>/…` instead of `/home/me/.cache/yay/<packagename>/…`

#### Steps to reproduce
1. set buildDir in config.json to something like `/home/me/.cache/yay`
2. Install any package from the AUR with `yay -S somepackage`
3. It errors with a message like `somepackage: unable to read file: /home/me/.cache/yaysomepackage/.SRCINFO, open /home/me/.cache/yaysomepackage/.SRCINFO: no such file or directory`

**Comment by Morganamilo** [comment]
When Yay started out it seems like + was used to join directories and stuff. Would be a good idea to get it all fixed up to use .join(). Now that there's an open issue I'll prioritise fixing it, shouldn't be too annoying to just add a slash in the meantime.

Thanks for reporting.
