### ISSUE TITLE
Unable to build mpv-git

### ISSUE THREAD

**Issue by GUiHKX** [Jguer/yay#363]
#### Affected Version
`yay v5.675`

#### Issue
[mpv-git](https://aur.archlinux.org/packages/mpv-git/) doesn't build with yay, but it does with pacaur. Here's the output of [yay -S mpv-git](https://gist.githubusercontent.com/GUiHKX/7518fdb86d6f5d14e327cde7a7581cd8/raw/0c537d78b87618e0547c68ffc6ef8d65f0bd5a6c/yay%2520-S%2520mpv-git). And here's the output of [pacaur -S mpv-git](https://gist.githubusercontent.com/GUiHKX/b4469f99e3507d65f0f95330b32ededc/raw/e780c1d1582b3d8556089a6fa9d8b1c9418d47f3/pacaur%2520-S%2520mpv-git).

#### Steps to reproduce

1. yay -S mpv-git

**Comment by Morganamilo** [comment]
It looks like the pkgbuild has this line in it:
```sh
if pkg-config --exists vulkan; then
  makedepends+=('vulkan-headers')
fi
```

So it adds vulkan as a dependency during the build which means it's impossible to know this from the RPC. I don't really think packages should be doing this and I think think we should support this weird/misleading behaviour.

All you need to do is install `vulkan-headers` before hand anyway so no big deal.

**Comment by GUiHKX** [comment]
Thanks!
