### ISSUE TITLE
[Feature] Compress package list

### ISSUE THREAD

**Issue by tomswartz07** [Jguer/yay#364]
#### Affected Version
`yay v5.675`

#### Issue
Out of the box, when running `-Syu`, the output is very screen intensive. 
Is it possible to add an option to compress the list of upgraded packages, similar to pacaur?

This way, the upgrades are visible on one screen's worth of text and scrolling through the output is not necessary, if there are more updates than lines of terminal.

#### Steps to reproduce
```sh
yay -Syu
 99 core/btrfs-progs                                        4.16-1 -> 4.16-2
 98 core/ca-certificates-mozilla                             3.36-1 -> 3.36.1-1
 97 core/libldap                                          2.4.45-4 -> 2.4.46-1
.....
```

Ideally, a config option could enable output like:
```sh
yay -Syu

Packages (98) core:
              attica-5.45.0-1  babl-0.1.46-1  btrfs-progs-4.16-2  bubblewrap-0.2.1-1  
              extra:
              virtualbox-5.2.10-1  virtualbox-guest-iso-5.2.10-1 ......
```

**Comment by Morganamilo** [comment]
We already have a pacaur style install list after the upgrade menu. Simply hiding the menu when `--answerupgrade` is set should do it.

**Comment by tomswartz07** [comment]
@Morganamilo ah, good catch- I did not know about that feature. 

I noticed a few minor issues with that in the manual (typos, etc), I'll toss up a PR to clarify that, if you want?

**Comment by Morganamilo** [comment]
Yes of course, contributors are always welcome.
