### ISSUE TITLE
Out-of-date official (community) packages are not marked.

### ISSUE THREAD

**Issue by JoshuaRLi** [Jguer/yay#369]
Reproduction is below. As you can see, `aur/google-fruit` is appropriately marked out-of-date but `community/godep` is not, even though it has been [marked out-of-date since 2018-03-16](https://www.archlinux.org/packages/community/x86_64/godep/).

![image](https://user-images.githubusercontent.com/14209781/39268356-a19acf56-489d-11e8-8c5e-50d59db841a5.png)

**Comment by Morganamilo** [comment]
Sadly the sync databases don't contain this information, only the web page. I've heard there's an rpc for the official packages but I can't find anything on that.

**Comment by JoshuaRLi** [comment]
Aww man. I'd have hoped `pacman -Ss godep` would at least show a warning, but it doesn't.

**Comment by Morganamilo** [comment]
Nope, sorry nothing I can do.

**Comment by AladW** [comment]
https://wiki.archlinux.org/index.php/Official_repositories_web_interface

Example
```
$ curl -s "https://www.archlinux.org/packages/search/json/?q=godep" | jq '.results[] | .flag_date'
"2018-03-16T11:43:28.314Z"
```
Some notes:

* This has more uses than additional information in search output, i.e. the output is always accurate regardless of sync or mirror status.
* Only one package (`q`, `name`) parameter can be specified. Unlike the AUR you can however search by the empty string and get all repo packages (`https://www.archlinux.org/packages/search/json/?q=`). The resulting output isn't that large, at 186kb it's even smaller than `packages.gz` (285kb)
* If a package is up-to-date, `flag_date` is `null`.

**Comment by Morganamilo** [comment]
Thanks I thought there was an RPC for the official repos but I couldn't find any information anywhere.

I'm still not a fan of adding an internet requirement for info on repo packages though.

**Comment by AladW** [comment]
>I'm still not a fan of adding an internet requirement for info on repo packages though.

Yeah I agree. I guess if you really wanted this you could put this behind some separate flag like `--jsonsearch` and/or fall back to `pacman`. Or even keep some cache of the output that has to be updated separately. Just throwing some ideas around.

**Comment by AlexWayfer** [comment]
> I'm still not a fan of adding an internet requirement for info on repo packages though.

Can it be an option, disabled by default?

**Comment by Jguer** [comment]
Seems a bit overkill to keep a cache and go through it after you already go through the alpm db. Optional on the fly checking for people who don't mind the extra latency would be more convenient, just wondering as well

**Comment by alerque** [comment]
I would find this information useful as an extra non-standard output option that requires net access at the time of running.
