### ISSUE TITLE
cannot change to /tmp/yaytmp-1000/, no such file or directory

### ISSUE THREAD

**Issue by pgkos** [Jguer/yay#373]
#### Affected Version
`yay v6.717.r4.g37b08ea`

#### Issue
The `gitDownload` function fails (when calling `git clone`) if the build directory does not exist (e.g. `/tmp/yaytmp-1000/` was removed by systemd).

#### Steps to reproduce

1. `rm -rf /tmp/yaytmp-1000`
2. Try to install or update any package which uses git.
3. `fatal: cannot change to '/tmp/yaytmp-1000/': No such file or directory`

**Comment by Jguer** [comment]
This should be fixed in `yay-git`

**Comment by jonathonf** [comment]
Is it possible to create `~/.config/yay/config.json` only when the default values are overridden? That way these sorts of default-settings-change issues won't happen.

**Comment by Jguer** [comment]
In this case `yay` should have been working even with those values.

I believe with some work it should be possible to do that, meanwhile most `yay` users already have a full config made which makes it hard to redistribute after. Right now I'm allocating development time to test development but this is a possible improvement to make in the future or by a new contributor. I'll add it as an issue.
