### ISSUE TITLE
yay -Pc gives empty output

### ISSUE THREAD

**Issue by phaul** [Jguer/yay#376]
#### Affected Version
yay v6.727

#### Issue

`yay -Pc` doesn't print anything. This used to work, and I used -Pc to feed fzf for completion. I don't know what has changed but I get empty output from yay. Exit status is 0. yay -Pfc does output a list of packages, although I don't need it in fish format.

#### Steps to reproduce

phaul@phoenix ~$ yay -Pc
phaul@phoenix ~$

**Comment by Morganamilo** [comment]
I can't seem to reproduce. What if you delete `~/.cache/yay/aur_*`?

**Comment by Jguer** [comment]
Can't reproduce on my side either, there was a bug on this during development https://github.com/Jguer/yay/commit/84569ef6d9d916bf8fa63a3edef12b1e4225cb47 but that was caught in `master`

**Comment by phaul** [comment]
Deleting ```~/.cache/yay/aur_* ``` fixed it.

Feel free to close unless you want to debug it further :) But now that I can't repro it either I don't think I can be any use.

**Comment by Morganamilo** [comment]
I'm guessing the file didn't download properly, could be a problem with Yay or your connection. I'll just assume this is a one off.
