### ISSUE TITLE
yay does not set the Title to the current function

### ISSUE THREAD

**Issue by mustaqimM** [Jguer/yay#378]
#### Affected Version

`yay v6.727`

#### Issue
yay doesn't set any Title to a terminal unlike other helpers which show what package function is currently running.
#### Steps to reproduce

1. Build a git package

**Comment by Jguer** [comment]
My config doesn't even allow title changing so I'm a bit mute on this. Still my vote is `wontfix`, Terminal title shows the program in execution,  it's `yay`, it's okay for me. 

Paging @Morganamilo  for vote
