### ISSUE TITLE
yay -Si calls pacman -Si for repo packages

### ISSUE THREAD

**Issue by Jguer** [Jguer/yay#38]
yay -Si is implemented for AUR packages so Repo packages should also have the same privilege.

**Comment by afg984** [comment]
Isn't it working for master?

**Comment by Jguer** [comment]
It's working, it's just how it works:
AUR package: 
yay calls own function
Repo package:
yay calls pacman as a command

Would just feel better for yay to parse repo package information itself since it already has access to the package DB.

**Comment by excalibur1234** [comment]
yay -Si <AUR package> does not requires root privileges

yay -Si <repo package> requires root privilages. this does not make sense to me, because other AUR helpers like pacaur, yaourt, or trizen do not need root privileges here. 
can you explain this or even better: change it?

**Comment by Chrysostomus** [comment]
It is a bit weird, since it calls pacman for repo packages, and pacman -Si does not require sudo. Why does it ask for password?

**Comment by Morganamilo** [comment]
Fixed in master. We're really overdue a release.

**Comment by Jguer** [comment]
True, time to create a release to do list like updating documentation, completions and release notes and releasing a new version

**Comment by excalibur1234** [comment]
thanks a lot.
the latest release of yay is a great one!
