### ISSUE TITLE
Depencies from AUR packages seem to ignore "provides"

### ISSUE THREAD

**Issue by daniel-nth** [Jguer/yay#381]
#### Affected Version
yay v6.727

#### Issue
[llpp](https://aur.archlinux.org/packages/llpp/) depends on [mupdf](https://www.archlinux.org/packages/community/x86_64/mupdf/). I have [mupdf-gl](https://www.archlinux.org/packages/community/x86_64/mupdf-gl/) installed which provides _mupdf_. Yay wants to uninstall _mupdf-gl_ and install _mudpf_. 

#### Steps to reproduce
1. yay -S mupdf-gl
2. yay -S llpp

**Comment by Morganamilo** [comment]
As far as I can tell this is correct behaviour. `llpp` depends on `mupdf>=1.7` and `mupdf-gl` does not provide a versioned dependency. Maybe you should talk to some one to get it changed to `provieds=(mupdf=$pkgver)`.

**Comment by daniel-nth** [comment]
You are right. Sorry and thanks for the explanation!

**Comment by Morganamilo** [comment]
https://www.archlinux.org/packages/community/x86_64/llpp/ just hit community.
