### ISSUE TITLE
'yay -Syu' sometime messes with install reason

### ISSUE THREAD

**Issue by KSXGitHub** [Jguer/yay#388]
#### Affected Version

v6.727.r0.gdc10c4b

#### Issue

Occasionally, when I run 'yay -Syu', some packages that are explicitly installed is lose their mark (i.e. being marked as 'installed as dependency' or 'orphan'). I can't really reproduce the issue right now.

**Comment by Morganamilo** [comment]
This should have been fixed a couple of releases back.

> I can't really reproduce the issue right now.

Hopefully that confirms it's fixed.

**Comment by Jguer** [comment]
I believe this has been fixed
