### ISSUE TITLE
-Sc removes cached split packages

### ISSUE THREAD

**Issue by Streetwalrus** [Jguer/yay#389]
#### Affected Version
yay v6.727.r9.gfeb3b8b

#### Issue
If the pkgbase of a split package isn't the name of an installed package, `yay -Sc` will remove it from the cache, even if one of its sub-packages is installed.

#### Steps to reproduce
```
$ yay -Sc              
...
==> Do you want to remove all other AUR packages from cache? [Y/n] y
```

An affected package is `transmission-sequential-{gtk,qt,cli}`, with `pkgbase=transmission-sequential`.

**Comment by Morganamilo** [comment]
I thought I took this into account when I first wrote this, seems like I was mistaken. Oh well, was an easy fix anyway, give it a try now and thanks for reporting.

**Comment by Streetwalrus** [comment]
Seems good now, thanks.

**Comment by Streetwalrus** [comment]
Actually that change has turned the problem around, now it's deleting all non-split packages.

**Comment by Morganamilo** [comment]
Turns out packages that are not part of a split package have a pkgbase of null. Should be fixed for real now. Thanks again.

**Comment by Streetwalrus** [comment]
That's exactly what I expected it would be. Thanks again.
