### ISSUE TITLE
Upgrade enhancements: list packages from all sources at once, allow user to filter the list before upgrading

### ISSUE THREAD

**Issue by maximbaz** [Jguer/yay#39]
@Jguer more requirements for the upgrade process that I could think of:

When upgrading, yay lists the packages to upgrade and asks Y/n for confirmation. First it lists pacman packages, after upgrading it lists `-git` packages, and then after upgrading it lists AUR packages. Yaourt combines these and outputs one list with all these packages at once, and asks for the Y/n confirmation once.

Furthermore, while asking for Y/n confirmation, yaourt allows typing `m` and choosing which packages from the list you want to upgrade, and which to skip this time. This applies to packages from any source, pacman or AUR. Right now I have one AUR package that I know has a broken new version, and with yay I cannot upgrade other packages without upgrading this one.

**Comment by Jguer** [comment]
True, that's very useful. 

Updating the cache is a privileged action, so yay would have to run as superuser and break makepkg (From what I  [gather](https://stackoverflow.com/questions/30552760/is-setgid-setuid-on-a-golang-binary-safe) privilege deescalation is not implemented).

For now we could run `sudo pacman -Sy` to update the cache and then do the parsing manually https://github.com/Jguer/go-alpm/commit/260d63877bb371b0ba1b0f5f68d157a68bda591e.

Off-topic so I don't forget: there's a `human` function in the go-alpm package that can be used if exported instead of having another one yay

**Comment by Jguer** [comment]
![](https://raw.githubusercontent.com/Jguer/jguer.github.io/master/yay/yayupgrade.png)
It's working, not really good for merging yet until it's better tested and still not sure about the UX.

**Comment by maximbaz** [comment]
Much colors, such wow :doge: 😄 
I like it, especially the highlighted diff, whether it is a version change or only a new pkgrel.

I'll be testing the branch. So far I saw one issue: the code is not respecting IgnorePkg from /etc/pacman.conf:

![image](https://user-images.githubusercontent.com/1177900/28305533-3d173e7c-6b9c-11e7-9929-368234f258bc.png)

Before it was like that:

![image](https://user-images.githubusercontent.com/1177900/28305659-c0cd5742-6b9c-11e7-8990-a76a19198015.png)

**Comment by Jguer** [comment]
My bad, forgot that config variable, I'll add it in. I also see your `->` are not centered, still haven't been able to fix that

**Comment by maximbaz** [comment]
Is it intended that there is a difference whether I use `-Syu` or `-Su`?

![image](https://user-images.githubusercontent.com/1177900/28359684-5987a0ba-6c73-11e7-97d1-3c3bdd218cd0.png)

**Comment by maximbaz** [comment]
So far it's looking good, I'm using it and everything works as expected :+1: 
I'm fine with merging this and closing the issue.

**Comment by Jguer** [comment]
I think it's only missing `--noconfirm` support and development package support (still needs to be redone in pacaur fashion) but I would also feel comfortable merging after adding `noconfirm`.

**Comment by maximbaz** [comment]
Now that you mention it, I noticed that this branch is not updating development packages anymore. Compare how the build from AUR vs the build from the `parallelUpdate` branch work:

![image](https://user-images.githubusercontent.com/1177900/28435059-e43a7b8c-6d91-11e7-84e6-6f509bf0bbc4.png)

**Comment by maximbaz** [comment]
@Jguer another issue:

![image](https://user-images.githubusercontent.com/1177900/28516928-26c58f7c-7063-11e7-8a53-6c727b836d0e.png)

**Comment by maximbaz** [comment]
Thanks for the fix 🙂

One more bug, or rather a little annoyance - the app gets stuck if there is nothing to update:

![image](https://user-images.githubusercontent.com/1177900/28583852-f7b7dcc2-716a-11e7-8497-c69b9ebb86c6.png)

**Comment by kode54** [comment]
How do I enable this feature? I somehow have it enabled on a fresh install on a server, but it doesn't work on my desktop, which I just installed a few days ago.

**Comment by Jguer** [comment]
```
--combinedupgrade
              During sysupgrade, Yay will first perform a refresh, then
              show its combined menu of repo and AUR packages that will
              be upgraded. Then after reviewing the pkgbuilds, the repo
              and AUR upgrade will start with no need for manual
              intervention.
```
Source: manpage

Also you may be refering to [this](https://github.com/Jguer/yay#yay-is-not-prompting-to-skip-packages-during-system-upgrade)

I believe it's this you were searching

**Comment by kode54** [comment]
Oops. I didn't know there was a manpage, or that the option was referenced there. Sorry about that.
