### ISSUE TITLE
Checking out the source code to `linux` creates `trunk` directory.

### ISSUE THREAD

**Issue by tonylambiris** [Jguer/yay#394]
#### Affected Version
yay v6.727.r0.gdc10c4b

#### Issue
Checking out the source code to `linux` creates `trunk` directory.

#### Steps to reproduce

```
$ pacman -G linux
==> Downloaded linux from ABS
:: Querying AUR...

$ ls
trunk/
```

**Comment by Morganamilo** [comment]
Update, I believe this is already fixed in newer versions.

**Comment by tonylambiris** [comment]
@Morganamilo confirmed fixed in latest git commit, thanks!
