### ISSUE TITLE
Skip conflicting targets from the target list

### ISSUE THREAD

**Issue by tippl** [Jguer/yay#398]
#### Affected Version
yay v6.727

#### Issue
Package cuda used to have dependency of gcc5, which was installed from aur. The package seems to have updated and now requires gcc54 which is in repo.
```
$ yay -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Searching databases for updates...
:: Searching AUR for updates...
:: Checking development packages...
:: Querying AUR...
:: 8 Packages to upgrade.
  8 core/libgpg-error                                       1.29-1 -> 1.31-1
  7 core/tzdata                                            2018d-1 -> 2018e-1
  6 extra/librsvg                                       2:2.42.3-1 -> 2:2.42.4-1
  5 extra/pepper-flash                                29.0.0.140-1 -> 29.0.0.171-1
  4 extra/webkit2gtk                                      2.20.1-1 -> 2.20.2-1
  3 extra/wget                                            1.19.4-3 -> 1.19.5-1
  2 community/cuda                                      9.1.85.3-4 -> 9.1.85.3-5
  1 aur/gcc5                                               5.5.0-1 -> 5.5.0-2
==> Packages to not upgrade: (eg: 1 2 3, 1-3, ^4 or repo name)
==> 

:: Checking for conflicts...
:: Checking for inner conflicts...

==> Inner conflicts found:
 -> gcc54: gcc5
Unresolvable package conflicts, aborting
```

on the other hand
```
$ sudo pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
:: gcc54 and gcc5 are in conflict. Remove gcc5? [y/N] 
```

Edit:
Now that think about it, the main problem is probably the fact gcc5 also has a pending update.

**Comment by Morganamilo** [comment]
You're trying to upgrade gcc5 and install a package that needs gcc54, creating an inner conflict.

Try installing just cuda without doing an upgrade: (yay-git is just there to trigger Yay's AUR output otherwise it would just forward everything to pacman)
![image](https://user-images.githubusercontent.com/16593899/39785340-ad61f0b4-5313-11e8-8443-869cc8f416ae.png)

Just upgrade cuda or gcc5 separately. Or uninstall gcc5 (gcc54 provides gcc5).

Of course gcc is only a makedep so It would be possible to swap the gcc versions between builds but Yay does not currently do this.

**Comment by tippl** [comment]
Yeah, that would probably work. 
The problem is, gcc5 is only installed as dependency to cuda. New cuda doesn't need it anymore and has conflicting package instead. It would be nice if yay recognized gcc5 is no longer needed and to remove it to allow installation of gcc54.
This issue won't probably show up often because the conditions have to be pretty specific, so take this more like as an "nice to have" fix i guess.

**Comment by Morganamilo** [comment]
>New cuda doesn't need it anymore

No but you are trying to update gcc5, so it is considered needed by the user. If gcc5 wan't part of the update Yay would offer to remove it.

Having Yay be smart enough to detect this type of thing would be nice but no promises.

Looking at pacman It does this: 
![image](https://user-images.githubusercontent.com/16593899/39786337-0d230f5c-5318-11e8-8521-1ff305cfd957.png)

So this is probably what Yay would do if it got implemented.
