### ISSUE TITLE
Remove 'Proceed with install?' dialog

### ISSUE THREAD

**Issue by notramo** [Jguer/yay#402]
When installing a package from AUR, after editing the PKGBUILD, `yay` aks if I want to continue the install. I think this is unnecessary, because it aborts the transaction if the editor exited with non-zero. If something is wrong with the PKGBUILD, then closing the editor with non-zero is enough.

**Comment by Morganamilo** [comment]
We always abort on non zero, the editor not doing so was more of an oversight. Sure using `:cq` might be an added bonus, I use it too. But we can't assume every editor supports exiting with non 0. Forcing people to use `:cq` or an equivalent would probably not be very well received and not very intuitive.

**Comment by notramo** [comment]
What about disabling the dialog with a command line flag? If some editor don't support exiting with non-zero, then this dialog could be enabled.

**Comment by Morganamilo** [comment]
I don't think there's much point in adding a config option for one dialog. Yay is pretty minimal with its number of prompts already.

I see this akin to "are you sure you want to exit" type dialogs. A little annoying but they save you sometimes.

Anyway, there's been no other discussion on it so closing.
