### ISSUE TITLE
Ignoring Architecture no longer works

### ISSUE THREAD

**Issue by Atemu** [Jguer/yay#404]
#### Affected Version

`yay v6.727`

#### Issue

Yay asks whether or not I want to build packages that are not compatible with my architecture but after it starts making, it says that the package is not available for my architecture and exits with an error.

This feature did work in v5.675

#### Steps to reproduce

1. Be on a architecture other than i386 or amd64 (armv7h for example)
2. Install a package that is not available for your architecture (`libvirtfs` for example)
3. Accept the `Try to build them anyway?` prompt

**Comment by Morganamilo** [comment]
Looks like I missed this when adding a new makepkg call, should be fixed now. Thanks for reporting.

**Comment by Atemu** [comment]
Thanks for fixing! :)
