### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by DoTheEvo** [Jguer/yay#406]
I know that this might be kinda controversial in arch community
but why not just having dumb as fuck installation instructions in the readme?

noobs would welcome that, and non-noobs appreciate not having to go to aur page, looking for the exact pkgbuild url, and then go to arch wiki to go dig in to how exactly one installs package manually because the last time they did it was like year ago...

- `sudo pacman -S wget`
- `wget https://aur.archlinux.org/cgit/aur.git/snapshot/yay.tar.gz`
- `tar -xzf yay.tar.gz`
- `cd yay`
- `makepkg -si`

**Comment by Morganamilo** [comment]
I'm not against it, I never really thought about it to be honest, manually downloading things fromthe AUR is second nature to me at this point.

Using git over tarballs are the recommended way to do this though.
```
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
```

Manual installation:
```
git clone https://github.com/Jguer/yay
cd yay
make PREFIX=/usr/local install
```

Running from the repo:
```
git clone https://github.com/Jguer/yay
cd yay
make
./yay <command>
```

I'll add it to the readme at some point unless you want to do it.
