### ISSUE TITLE
lua-moses-git always being upgraded

### ISSUE THREAD

**Issue by 2m** [Jguer/yay#408]
#### Affected Version
`yay v6.727`

#### Issue
`lua-moses-git` AUR pacakge is always being upgraded. I am not sure if that is something that the package does wrong or it uses something that is not supported by `yay`.

#### Steps to reproduce
1. `yay -S lua-moses-git` *pacakge installs normally*
2. `yay` *yay wants to upgrade just intalled package*

**Comment by Morganamilo** [comment]
`lua-moses-git`'s AUR page lists `1.6.1.1.r9.g57864a9-2`.
The `pkgver()` function generates `1.6.1.1.r1.gded0a9b-1`.

Somehow the AUR page's version is newer than the actual version. This is a problem with the package and you should contact the maintainer to fix it.

**Comment by 2m** [comment]
Thanks for clarification. Will contact the package author.
