### ISSUE TITLE
cannot parse xf86-video-intel-git skipping: invalid version format: X-ABI-VIDEODRV_VERSION=2

### ISSUE THREAD

**Issue by redg3ar** [Jguer/yay#413]
#### Affected Version
yay v6.727
#### Issue
Error from gendb
cannot parse xf86-video-intel-git skipping: invalid version format: X-ABI-VIDEODRV_VERSION=2
#### Steps to reproduce

1. yay -Y --gendb.

**Comment by Morganamilo** [comment]
Should be fixed via mikkeloscar/gopkgbuild#22.
