### ISSUE TITLE
sudoloop not properly working

### ISSUE THREAD

**Issue by Exagone313** [Jguer/yay#414]
# Affected Version
6.727-2

# Steps to reproduce
1. Enable sudoloop (in ~/.config/yay/config.json, have `"sudoloop": true,`)
2. `yay -S mingw-w64-{binutils,configure,gcc,headers}`  (or probably another package that takes a long time to compile)

# Expected result
It asks for the sudo password once.

# Observed result
It asks for the sudo password after compiling a package that takes a lot of time.

**Comment by Morganamilo** [comment]
Have you changed anything, such has shortened the sudo timeout or disabled the timeout altogether?

**Comment by Exagone313** [comment]
No, I haven't changed something like that. Maybe you can close as wontfix if you don't see the issue, I don't really want to recompile that package, takes too much time.

**Comment by Morganamilo** [comment]
Well I can't see it on my end, I'm happy to try debug it with you, and that doesn't mean you have to recompile mingw again.

But if you like I can just close it here and now until some one else has problems with it.

**Comment by Exagone313** [comment]
I found how did this happen, compilation probably filled the memory at some point, so the sudo loop process couldn't be launched, and then it eventually timed out.
