### ISSUE TITLE
-G does not work for directories with certain characters

### ISSUE THREAD

**Issue by Morganamilo** [Jguer/yay#417]
#### Affected Version
v6.727.r39.g250d6c6

#### Issue
Trying to use `-G` with ABS packages in a path containing characters such as `(` or whitespace does not work. Looking at the code it's because the tar command:

https://github.com/Jguer/yay/blob/250d6c61f7f563f1e1b5701d62c34b3d9619c56e/download.go#L97-L99

Calls the shell and passes the arguments that way. This causes these characters to be interpreted by the shell. We could either use the tar command directly or do it pragmatically through go like how we unpack `packages.gz`.

I don't really want to touch this right now though because there's all sorts of weirdness in that command I don't really understand.

**Comment by Jguer** [comment]
Yes, someone removed the curse word I kept there to describe my feelings about that code. 
It was left there to remind me that is the most hideous line of code in `yay`.
I'll fix it
