### ISSUE TITLE
Package Install specifications

### ISSUE THREAD

**Issue by Jguer** [Jguer/yay#42]
# Managing install dependencies

## Preamble
Dependency management is a critical part in the install process of packages, pacman's approach is seemingly to install packages with their dependencies in one go since they're prebuilt.  
Most AUR packages require build dependencies without which the install process will fail.

The proposed solution for this problem in yay is creating an install graph and installing by tiers.

## Behavior

The user selects what packages he wants to install from the yay menu.
The install package will be fed a slice of AUR packages and Repo packages.

These AUR and Repo packages will be tier 1, tier 1 is for explicitly installed packages.  
If a tier 1 package is a dependency to another tier 1 package it will be installed on another tier and made an explicitly installed.

Already installed packages will be ignored.

Example:
To install yaourt-git (AUR) and caja (repo)

```
Final result after processing, git and pacman were already installed.
|----------------------Tier 1--------------------------|
|  caja yaourt-git                                     |
|------------------------------------------------------|

|----------------------Tier 2--------------------------|
| package-query-git                                    |
| exempi gvfs libexif libsm mate-desktop libnotify     |
|------------------------------------------------------|

|----------------------Tier 3--------------------------|
| yajl gcc-libs expat zlib                             |
| avahi dconf fuse libarchive libcdio-paranoia libsoup |
| udisks2  libsecret libbluray  libgudev  gcr  psmisc  |
|                       ....                           |
|------------------------------------------------------|

|----------------------Tier 4--------------------------|
| glibc  fuse-common                                   |
|                       ....                           |
|------------------------------------------------------|
```  

Before install all tiers are shown to the user along with tier size for approval. After approval the user will only be prompted again at the tier 1 install. Rejecting the tier 1 install will remove the whole tree.

## Implementation
Important points for implementation:  
- After editing the `PKGBUILD` a new `.SRCINFO` will need to be generated
- Capture Ctrl-C and remove full tree.
- Packages are stored as a graph.
- Graph is DFSed before adding each package since adding the same package twice would be bad.
- Nodes will be an interface with a Type function.
``` 
type Node interface {
    Type() //AUR or Repo (there probably is a better way, awaiting revision)
}  
```
- Transversal will be made through a reverse BFS.  
>For the implementation of a reverse BFS, the graph will have a tier 0 (dummy head). 
- Package details will come from `.SRCINFO` parsing since it is the only one that accounts for split packages.

## Objectives

- Get another check on the wiki ( Resolve complex dependencies)
- #5
- #10

**Comment by maximbaz** [comment]
Questions:

- > Before install all tiers are shown to the user 
    
    These tiers, are they gonna be visible to the user, or it is just an internal description? As a user I don't really care about numerous tiers, I just want to see "Install tier" and "Dependency tier", where both "gvfs" and "glibc" are shown in the "Dependency tier" all together.
- > After approval the user will only be prompted again at the tier 1 install.

    I have never understood the reason for the second prompt, why am I asked if I want to install something that I have already agreed on once? Who would spend time building the package just to answer "no, actually I don't want to install it after all"? 🙂

**Comment by Jguer** [comment]
- Tiers are just an internal description, on display you'll see "To Install" and "Dependencies"

- Maybe you're right, sometimes I get last minute regrets of the "I don't really need this" type and cancel, but I guess as long as Ctrl+C is removing installed packages all will be well.

**Comment by maximbaz** [comment]
Ctrl+C, or `yay -Rs` 😉 Yeah, I think the last minute regrets are rather rare and the interface should not be designed for them, it's enough to have one or several options to cancel the build.

Other than that, your spec looks very reasonable to me 👍

**Comment by rmarquis** [comment]
> Package details will come from .SRCINFO parsing since it is the only one that accounts for split packages.

You can pretty much use the RPC interface only and still handle split packages correctly. Using the RPC might also be slightly faster.

**Comment by Jguer** [comment]
Building:
- For AUR regular packages: Use RPC
- For ABS packages: Generate `.SRCINFO` and then parse it
- For AUR split packages: Use RPC, build all packages (Are there any split packages where one subpackage depends on another subpackage?)
- If the `PKGBUILD` was edited: Generate `.SRCINFO` and parse it

I need to study pacaur's and other AUR Helpers split package implementations better.

**Comment by rmarquis** [comment]
> Are there any split packages where one subpackage depends on another subpackage

Yes, this happens frequently. They can even conflict between each others.

A few pointers:
* pacaur solves the pkgname list order, then uses the pkgbase attribute to ensure a single build per pkgbase and the installation in the right order.
* aurutils uses a local repository, which let pacman handle the order of installation.
* bauerbill does something similar to pacaur (I guess), but uses a patched version of makepkg to handle the installation (the old `--pkg` option that was removed in pacman 5.0)
* trizen does something similar to yaourt, asking the user to select split packages to install

> If the PKGBUILD was edited: Generate .SRCINFO and parse it

I pretty much gave up the idea of recomputing the dependency tree when the PKGBUILD is edited due to the heavy complexity, this is something yay could do than nobody else does.

**Comment by maximbaz** [comment]
You should probably add description of how `Clean build? [y/N]` will work. Currently when pressing `N`, user is asked `Edit PKGBUILD?`, but any changes to PKGBUILD are ignored - in fact, the package will not be rebuilt at all if version did not change.

**Comment by Jguer** [comment]
I want to say I've been thinking about this a lot but I've just been very busy lately.
- Running yay as sudo and trying to install an AUR package fails on makepkg level but the PKGBUILD is still cloned (with root permissions nonetheless)

**Clean build**
Yes:  
-  Remove built packages and (`makepkg -C`)

No:
- Roll with whatever is there

No & Edit PKGBUILD:
-  Remove built packages and (`makepkg -C`)
