### ISSUE TITLE
After installing emacs-git from aur emacs binary is not on path. 

### ISSUE THREAD

**Issue by siulkilulki** [Jguer/yay#421]
#### Affected Version
yay v6.727

#### Issue
After installing emacs-git from aur emacs binary is not on path. Trizen installed emacs-git successfuly (same pkgbuild)

#### Steps to reproduce
1. yay emacs-git
2. choose emacs-git package
3. edit pkgbuild and comment `BRANCH=master`, uncomment `BRANCH=emacs-26`

**Comment by Morganamilo** [comment]
Did emacs actually install with Yay or did it error?

**Comment by Morganamilo** [comment]
I can't seem to reproduce this either.

**Comment by siulkilulki** [comment]
Emacs make run successfully. Hmm, I will try to reproduce it. Maybe I was
so tried that day that I've done something stupid, but I didn;t recall such
thing.

2018-05-18 21:42 GMT+02:00 Anna <notifications@github.com>:
