### ISSUE TITLE
Submodules are not initialized

### ISSUE THREAD

**Issue by 2m** [Jguer/yay#426]
#### Affected Version
```
yay v6.777
```

#### Steps to reproduce

Installing [`way-cooler-git`](https://aur.archlinux.org/packages/way-cooler-git/) package fails with:

```
error: failed to load source for a dependency on `wlroots`

Caused by:
  Unable to update file:///home/martynas/.cache/yay/way-cooler-git/src/way-cooler-git/wlroots-rs

Caused by:
  failed to read `/home/martynas/.cache/yay/way-cooler-git/src/way-cooler-git/wlroots-rs/Cargo.toml`
```

Where `wlroots-rs` is actually a git [submodule](https://github.com/way-cooler/way-cooler).

**Comment by Morganamilo** [comment]
I get the same error, not just with Yay but every other AUR helper and when using makepkg. I'd call this an upstream issue.

**Comment by 2m** [comment]
Ahh, sorry. Makes sence. Will notify package author.
