### ISSUE TITLE
Recognition that devel package changed doesn't work for sequeler-git

### ISSUE THREAD

**Issue by synaptiko** [Jguer/yay#427]
#### Affected Version
yay v6.777

#### Issue
For some reason `sequeler-git` is always considered changed; even if it's freshly installed. I use other `-git` packages but have no problem with them (I use for example `neovim-git`, `alacritty-git`). I compared PKGBUILDs of few of them and the only thing I noticed is that `sequeler-git` is missing `$pkgname::` in `source`. Can this be the issue? If so I'll report it on AUR.

#### Steps to reproduce
1. `yay -S sequeler-git`
2. `yay`

**Comment by Morganamilo** [comment]
I appears their srcinfo is out of date. They need to regenerate it.

**Comment by Morganamilo** [comment]
Upstream updated the srcinfo now, so it should work as expected.

**Comment by synaptiko** [comment]
@Morganamilo Thank you, I wasn't sure where the problem is as I wasn't able to spot what's wrong with `sequeler-git` in the first place…
