### ISSUE TITLE
yay not showing new packages, which is dependencies for upgrading another packages

### ISSUE THREAD

**Issue by DX37** [Jguer/yay#428]
#### Affected Version
yay v6.777

#### Issue
Described in topic.

#### Steps to reproduce
Just wait for update like this (whoops, incorrect screenshot):
![_2018-05-24_22-21-21](https://user-images.githubusercontent.com/12829428/40495346-2e0e3bac-5fa1-11e8-8b85-09291b1dad89.png)

There is `libutf8proc`, which is a dep for `subversion` now.

Should this be considered as issue?

**Comment by Morganamilo** [comment]
You've explicitly chosen to ignore the package. I don't see what's wrong here.
