### ISSUE TITLE
yay exits with exit code 0, even if the package wasn't found

### ISSUE THREAD

**Issue by Svinto** [Jguer/yay#430]
#### Affected Version
v6.777.r1.g3f15788

#### Issue
yay exits with exit code 0, even if the package wasn't found.
This makes it harder to use yay in a script.

#### Steps to reproduce
Example 1: `yay -Si ahfgiagfiaef`
Example 2: `yay -G ahfgiagfiaef`

Both has the same output:
> :: Querying AUR...
>  -> Missing AUR Packages:  ahfgiagfiaef

Possibly related to issue #307

**Comment by Jguer** [comment]
Related to #307 but not duplicate, this seems more important to me though.
`yay -S ahfgiagfiaef ` returns the correct error. But  
`yay -G ahfgiagfiaef ` does not so at least that one should be high priority for now

**Comment by Jguer** [comment]
@Svinto This should fix the issues with scripting in `yay-git` for now

**Comment by Svinto** [comment]
Works perfectly. Thanks for the quick response.
