### ISSUE TITLE
Cannot build on rpi3 [armv7h]

### ISSUE THREAD

**Issue by thepasto** [Jguer/yay#435]
#### Affected Version
yay v6.784

#### Issue
```
go build -v -ldflags '-s -w -X main.version=6.784.r1.gcc2322f' -o yay
github.com/jguer/go-alpm
github.com/mikkeloscar/gopkgbuild
github.com/mikkeloscar/aur
# github.com/jguer/go-alpm
.go/src/github.com/jguer/go-alpm/enums.go:79:7: constant 2147483648 overflows SigLevel
make: *** [Makefile:47: build] Error 2
```

#### Steps to reproduce

1. Download PKGBUILD
2. makepkg -s

Thanks!

**Comment by Jguer** [comment]
Can you test if it's working on `yay-git`? after that I'll push it to `yay`

I've been planing for a long time to include `armv7h` on `yay-bin` but I still don't have a nice environment to build those packages

**Comment by thepasto** [comment]
yay-git it's ok now! Thanks.
I'm here for anything you need to test! Let me know what you need!
