### ISSUE TITLE
Yay doesn't appear to handle unknown options gracefully

### ISSUE THREAD

**Issue by mr-bo-jangles** [Jguer/yay#436]
#### Affected Version
yay v6.784

#### Issue
Yay doesn't appear to handle unknown options gracefully

#### Steps to reproduce
```
~ » yay -Syu
[sudo] password for josh: 
:: Synchronising package databases...
 core is up to date
 extra is up to date
 community is up to date
:: Searching databases for updates...
:: Searching AUR for updates...
 -> Local package is newer than AUR: grub2-editor-frameworks (20171121.gba1e9b7-1 -> 20151208.g1e4ae87-1)
:: Querying AUR...
 -> Orphaned AUR Packages:  startupmanager
 -> Out Of Date AUR Packages:  gnome-system-tools  nouveau-fw  spotify  startupmanager
:: 1 Packages to upgrade.
1  aur/insomnia  5.16.2-1 -> 5.16.6-1
==> Packages to not upgrade: (eg: 1 2 3, 1-3, ^4 or repo name)
==> 

:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur: 1]  insomnia-5.16.6-1

  1 insomnia                                 (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
==> PKGBUILDs to edit?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: PKGBUILD up to date, Skipping (1/1): insomnia
:: Parsing SRCINFO (1/1): insomnia
:: Starting full system upgrade...
 there is nothing to do
==> ERROR: options array contains unknown option '!upx'

==> ERROR: An unknown error has occurred. Exiting...
Error downloading sources: insomnia

```

**Comment by Jguer** [comment]
This seems like a `makepkg` issue. `upx` and something else (diff `makepkg.conf` with `makepkg.conf.pacnew`)

What I don't understand is that my `makepkg` has started ignoring those options but apparently not yours

**Comment by Morganamilo** [comment]
I believe the upx option was removed in Pacman 5.1.

**Comment by Morganamilo** [comment]
Pacman 5.1 also brought stricter linting on makepkg, so now makepkg will refuse to build pkgbuilds that use disallowed characters in the pkgname or pkgver. This is one of the things I'm very happy about.

**Comment by eli-schwartz** [comment]
makepkg has always forbidden unknown options in your PKGBUILD, while ignoring them in makepkg.conf. This is not new because of pacman 5.1, it's new because upx was removed and some PKGBUILDs locally specify it.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=insomnia&id=90af315eea6d2d64eb1d27a3b3f755eb18dade29#n10
