### ISSUE TITLE
Yay lists all installed core packages as missing from AUR

### ISSUE THREAD

**Issue by RyanDwyer** [Jguer/yay#437]
#### Affected Version

    $ yay -V
    yay v6.784.r2.gd442af9

#### Issue

    $ yay -Ps
    Yay version v6.784.r2.gd442af9
    ===========================================
    Total installed packages: 1078
    Total foreign installed packages: 1078
    Explicitly installed packages: 324
    Total Size occupied by packages: 7.4 GiB
    ===========================================
    Ten biggest packages:
    libreoffice-fresh: 388.9 MiB
    linux-firmware: 287.5 MiB
    rust: 241.2 MiB
    hipchat: 223.8 MiB
    slack-desktop: 211.0 MiB
    mariadb: 169.1 MiB
    chromium: 161.4 MiB
    docker: 159.5 MiB
    python: 137.8 MiB
    firefox: 137.8 MiB
    ===========================================
    :: Querying AUR...
     -> Missing AUR Packages:  a52dec  aalib  accountsservice  acl

I truncated the list of Missing AUR Packages for this issue, but it lists all my installed core packages. There's 1049 of them.

I've just installed yay because I'm considering switching. Using pacman 5.1 with pacman-contrib installed too if that's related.

**Comment by Morganamilo** [comment]
That's strange, whats your pacman.conf look like?

**Comment by RyanDwyer** [comment]
Here's my pacman.conf with comments removed:

    [options]
    HoldPkg = pacman glibc
    Architecture = auto
    IgnorePkg = xorg-server xorg-server-xwayland
    CheckSpace
    Include = /etc/pacman.d/custom
    SigLevel = Required DatabaseOptional
    LocalFileSigLevel = Optional
    
    [core]
    Include = /etc/pacman.d/mirrorlist
    
    [extra]
    Include = /etc/pacman.d/mirrorlist
    
    [community]
    Include = /etc/pacman.d/mirrorlist
    
    [multilib]
    Include = /etc/pacman.d/mirrorlist

**Comment by RyanDwyer** [comment]
Oh, and my /etc/pacman.d/custom is just:

    Color

**Comment by Morganamilo** [comment]
Oh yeah that include breaks something for some reason. If you comment out the include and just write in Color instead it should work. I'll look into fixing it.

**Comment by RyanDwyer** [comment]
Yep, that's resolved it. Thanks.

**Comment by Jguer** [comment]
I think https://github.com/Jguer/go-alpm/blob/master/conf.go#L203 is broken because this is a constant problem

**Comment by Jguer** [comment]
Ok, let's move this discussion over to `go-alpm`, I'll create a discussion issue where we can evaluate possibilities. 

pacconf is in `pacutils`, pulling it in would mean changing one of our core features, but improve some of our _Not Invented Here_ stance. 
Either way, the only thing I'm against is reading stdouts when we have more integrated solutions
