### ISSUE TITLE
Add some locales

### ISSUE THREAD

**Issue by jefer94** [Jguer/yay#438]
#### Affected Version

yay v6.786

#### Issue
This AUR Helper not have some locales, like es-ES

#### Steps to reproduce

1. yay -Syu

**Comment by Morganamilo** [comment]
In the works, just very slowly. If you're willing to do the the Spanish translations when time comes, I would really appreciate it.

**Comment by jefer94** [comment]
Just I'd need the list of the messages, and it'l translate it

**Comment by dima74** [comment]
What about creating project on, for example, https://crowdin.com/, so it would be easier to add translations? (crowdin is free for open source projects)

**Comment by samosaara** [comment]
I mean, it doesn't really need to be crowdin in IMO, any crowd-sourcing translation website/platform would be much better than fiddling with translation files, forks, pull requests, etc. A lot of people not even know how to do these and are just bilingual.

**Comment by sl1pkn07** [comment]
transifex

**Comment by mattia-b89** [comment]
I am available, for ITALIAN translation!
even if I prefer to use english UI, I think it is a 'good' way to enhance user experience and thus makes this software better
for this reason I opt in.
