### ISSUE TITLE
yay requests to import missing pgp keys even when --skipgpcheck is specified

### ISSUE THREAD

**Issue by GrieverV** [Jguer/yay#439]
#### Affected Version
yay v6.786.r0.gd442af9

#### Issue
yay requests to import missing pgp keys even when specifying `--skippgpcheck`

This is a rather big issue for me since I have a script that acts as a wrapper around `yay` for fully automated builds of packages lists/groups and some packages require `--skipgpcheck` as I prefer not to import some or all pgp keys for select packages
#### Steps to reproduce
The following should be a completely automated install of the `libc++` package from AUR but gets interrupted due to missing pgp keys:

```
yay -S --answerclean All --answeredit None --mflags "--nocheck --skippgpcheck --noconfirm" libc++
```

**Comment by AladW** [comment]
If I understand your proposal right yay would have to parse the mflags string and consider different cases depending on what's specified there. If this is considered a valid usecase (not sure why anyone would like to skip PGP keys) I'd add some flag to disable key import functionality in `yay` instead.

**Comment by Morganamilo** [comment]
Yep that's exactly what I'll do. The user will be expected to pass `--nopgpfetch` and `--mflags --skippgpkeys`, If they wanted to do that for some reason.

**Comment by gaycomputers** [comment]
I actually found a (il)legitimate use for this, I managed to find a arch install that was only accessible through a xen passthrough package that was outdated on it and had a hard dependency breakage that caused the machine to be un-updateable. libffio was breaking pgp checks in yay and pacman, ended up having to skip the pgp fetch and check unsafely, just to get the machine updated to the point I could do -Syu.
