### ISSUE TITLE
Scientific notation of small popularities

### ISSUE THREAD

**Issue by redg3ar** [Jguer/yay#441]
#### Affected Version
yay v6.786.r0.gd442af9
#### Issue
Packages with small decimal popularity are shown in scientific/exponent notation
#### Steps to reproduce

1. yay -Si chrome-shutdown-hook (0.000009 popularity when I cloned it)

Output:
```
~ ❯❯❯ pac -Si chrome-shutdown-hook
:: Querying AUR...
Repository      : aur
Name            : chrome-shutdown-hook
Version         : 1.3.2-1
Description     : Gently shutdown Chrome/Chromium on logout from Gnome Shell.
URL             : https://www.google.com/chrome/index.html
Licenses        : GPL
Provides        : 
Depends On      : procps-ng  python2  gnome-python
Make Deps       : 
Check Deps      : 
Optional Deps   : gnome-tweak-tool
Conflicts With  : 
Maintainer      : Terence
Votes           : 6
Popularity      : 9e-06
```

**Comment by Jguer** [comment]
I've been trying to figure out how to address this issue for 5 minutes at least since I do not see any problem with the way the output is displayed.

Could you explain how this is an issue?

**Comment by Morganamilo** [comment]
They probably wanted it printed as `0.000009`

```
fmt.Printf("%s%15s %f\n", bold("Popularity"), bold(":"), a.Popularity)
```
That works.

**Comment by Jguer** [comment]
Yes, sure, I understood, I just guess having a popularity of `9e-06` or `0.000009` doesn't make much difference, specially since we trim to `0.00%` on `yay -Y` if I'm not wrong.

**Comment by Jguer** [comment]
If this makes difference to some people, I don't really care, it can be displayed as 0.000009.

just thought it was funny

**Comment by redg3ar** [comment]
thank you very much! sorry about the ambiguity
