### ISSUE TITLE
yay: error while loading shared libraries: libalpm.so.10: cannot open shared object file

### ISSUE THREAD

**Issue by tareefdev** [Jguer/yay#443]
I used to use `yay` as AUR helper for several months, but today, when I tried to install some packages form AUR I got this message:

    yay: error while loading shared libraries: libalpm.so.10: cannot open shared object file: No such file or directory

shall I follow the solution [here](https://stackoverflow.com/questions/480764/linux-error-while-loading-shared-libraries-cannot-open-shared-object-file-no-s#21173918)?

**Comment by r3b311i0n** [comment]
You don't need to do that. Just manually reinstall `yay` using `makepkg`.

**Comment by tareefdev** [comment]
That solved the problem, thanks!
