### ISSUE TITLE
"yay -G" couldn't find mendeleydesktop

### ISSUE THREAD

**Issue by 0x1997** [Jguer/yay#448]
#### Affected Version
yay v6.786

#### Issue
* `yay -G mendeleydesktop`
```bash
mendeleydesktop not in standard repositories
:: Querying AUR...
```
* `yay -G aur/mendeleydesktop`
```bash
:: Querying AUR...
 -> Missing AUR Packages:  aur/mendeleydesktop
Could not find all required packages
```

**Comment by Morganamilo** [comment]
`-G` for repo packages uses the ABS which is unique to arch, using a custom repo or Majaro would cause the first error.

It seems like the db prefixes were never implemented in -G `aur/`. Them and --repo/--aur options should probably be added to `-G`.
