### ISSUE TITLE
GitHub asking for password during devel update

### ISSUE THREAD

**Issue by Morganamilo** [Jguer/yay#451]
#### Affected Version

v6.786.r36.g5b6c410

#### Issue
The AUR helper `saur` has ceased development. The AUR package `saur-git` has been removed as well as the git repo `github.com/dylanaraps/saur.git` deleted.

running `git ls-remote` or most other commands on a non existing repo cause git to prompt for a password. This is probably because in theory there could be a private repository there. Using `git://` causes git to fail immediate because the git protocol does not support authentication.

yay then tries to use `https://` to query the repo. At which point git prompts for a password.

The devel checks are meant to timeout after around 4 seconds although yay appears hang until I enter some random password just to get git to exit and yay continue.

As you can already guess this only happens under very very specific circumstances. 

#### Fixing
- Find out why that 4 second timeout isn't working and fix it.
- Use `passToPacmanCapture` to hide output and disable input to git.

#### Steps to reproduce
You can use the following excerpt from `vcs.json` to reproduce:
```
"saur-git": {
		"github.com/dylanaraps/saur.git": {
			"protocols": [
				"git",
				"https"
			],
			"branch": "HEAD",
			"sha": "8759745827194842b18dd24924c1abec24f11dae"
		}
	},
```
The name `saur-git` can be changed to another pkgname just to get the update to trigger. Otherwise yay will delete entries for not currently installed packages.

**Comment by Morganamilo** [comment]
It seems the 4 second timeout is working now, so scratch that point maybe. Needs more testing really.

**Comment by Morganamilo** [comment]
So I looked at the code. Annoyingly we already hide the git output. The problem is git bypasses redirection. For example `git ls-remote https://github.com/dylanaraps/saur.git &> /dev/null` will still print to the terminal. There's probably a git flag out there to fix it, just need to find it.

**Comment by Morganamilo** [comment]
Found it :D

```
GIT_TERMINAL_PROMPT
           If this environment variable is set to 0, git will not prompt on the terminal
           (e.g., when asking for HTTP authentication).
```

**Comment by Jguer** [comment]
I had to go read up on it. 
`go get` sets it as well https://stackoverflow.com/questions/32232655/go-get-results-in-terminal-prompts-disabled-error-for-github-private-repo
