### ISSUE TITLE
Robustness to directories with wrong permissions

### ISSUE THREAD

**Issue by nicoulaj** [Jguer/yay#452]
#### Affected Version
yay v6.786

#### Issue
The AUR `molotov` 2.2.0-1 package extracts an AppImage which contains some directory with invalid chmod (`usr/share/icons` is missing `u+w`). This causes yay to fail when trying to cleanup the source directory:

```
==> Removing existing $srcdir/ directory...
/bin/rm: cannot remove '/home/nicoulaj/.cache/yay/molotov/src/usr/share/icons/default': Permission denied
```

Maybe yay could handle this case (eg: by running a `chmod -R 775 *` on the source directory if delete fails)...

#### Steps to reproduce
1. yay -S molotov

**Comment by Jguer** [comment]
> Maybe yay could handle this case (eg: by running a chmod -R 775 * on the source directory if delete fails)...

Maybe `yay` could handle this but mostly `chmod -R 775 *` on a wildcard for convenience is a bad practice and most of the time when `makepkg` is breaking on something the `PKGBUILD` is in the wrong.

I'm with @Morganamilo on this
>I would just wait for the AUR package to fix it.
