### ISSUE TITLE
[feature request] Automatically sync packages in LAN

### ISSUE THREAD

**Issue by veecue** [Jguer/yay#457]
Hello there,

for pacman, packages can easily be mirrored using pacserve or more modern alternatives such as [pacmon](https://github.com/veecue/pacmon) using `/var/cache/pacman/pkg` and the mirrorlist. Since yay also caches built packages in `~/.cache/yay`, it should be possible to serve them to other instances of yay in the LAN somehow. Can this behaviour be added?

Greetings, veecue

**Comment by Jguer** [comment]
Hello there veecue,

This seems out of scope for `yay` but I've been working on something that may replicate this in the future. I'll come back to this if I finish implementing it.

**Comment by Morganamilo** [comment]
I'm not familiar with how pacmon works exactly. You should already be able to do this somewhat though. Yay will use PKGDEST as a cache similar to `/var/cache/pacman/pkg` Yay will still need need to download the pkgbuilds into its own ~/.cache/yay to check for `pkgver()` updates and such. But it will then just use the pre existing packages in cache instead of building.

**Comment by veecue** [comment]
I understand that it would be pacmons job to do the syncing. However, at least the following feature would need to be implemented in yay: * Trying to pull packages from a given mirrorAnd optionally: * Signing packages with PGP after building and verifying the signatures after pullingCould at least the first one be implemented?Greetings, veecue

**Comment by veecue** [comment]
Ok, I started investigating further and found out, that yay doesn't work when `PKGDEST` is set:
`Could not find built package yay-6.786-1-x86_64.pkg`

Also, `makepkg` supports automated signing of the finished packages, so that shouldn't be a problem either. So what remains to yay is to query some kind of mirrorlist for the built package before building on its own.

**Comment by Morganamilo** [comment]
Yay does support `PKGEST`, it just broke after pacman 5.1 was released and has since been fixed in `yay-git`.

**Comment by dhensen** [comment]
Any progress on this? I am also wanting this. My use case:

having packages that take a relatively long time to build on at least 3 of my machines: one desktop and two laptops. For instance: pycharm-professional, vscode and some more packages that require compile times of above 10m. I'm doing this on my desktop already, which I use as a local package mirror. I would like something, maybe yay, to first check if there is a built pkg corresponding to the upstream repo version already available on my local mirror before building the pkg itself per computer.

**Comment by Morganamilo** [comment]
Wouldn't just setting PKGDEST and some rsync script be enough?
