### ISSUE TITLE
Does not use $XDG_CACHE_HOME for checking out AUR packages and building

### ISSUE THREAD

**Issue by 2m** [Jguer/yay#460]
#### Affected Version
```
yay v6.786
```

#### Steps to reproduce

I have `XDG_CACHE_HOME` set:

```
➜  ~ echo $XDG_CACHE_HOME
/data/cache
```

But the AUR packages are still checked out and built in ~/.cache/yay:

```
...
==> Making package: albert 0.14.20-1 (Mon 04 Jun 2018 10:13:44 PM EEST)
==> Retrieving sources...
  -> Cloning mirrors/albert git repo...
Cloning into bare repository '/home/martynas/.cache/yay/albert/mirrors/albert'...
...
```

**Comment by Morganamilo** [comment]
Works for me. Does `/data/cache` already exist and is writable?

**Comment by 2m** [comment]
Yes, it does exist and is writable:
```
➜  ~ l /data/ | grep cache
drwx------      - martynas  martynas   4 Jun 22:13  cache
```

**Comment by Morganamilo** [comment]
Is it possible the variable isn't exported?

That's all I can think of right now. I'll probably add some warning messages to ease debugging.

**Comment by 2m** [comment]
I double checked it and it is exported.

**Comment by 2m** [comment]
I also just found out that yay actually uses $XDG_CACHE_HOME to put the vcs.json file, but not the AUR packages.

**Comment by Morganamilo** [comment]
That sounds strange. I have tweaked the logic a little bit. Although I don't see why it would not be working in the first place. Please try the latest git and see if it still happens.

**Comment by Morganamilo** [comment]
I just realised builddir is it's own config option in the config file. It will use the `$XDG_CACHE_HOME/$HOME` variables when creating the initial config file. Once set it should stick to that until you change it manually.

**Comment by 2m** [comment]
Just tried the latest git and now it works great! Thanks. :)

**Comment by xeruf** [comment]
Still having this issue - potential regression?
```sh
❯ sudo rm -rf .cache
❯ yay --version
yay v11.0.2 - libalpm v13.0.1
❯ echo $XDG_CACHE_HOME
/home/janek/.local/cache
❯ yay -S leaguedisplays-git
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  leaguedisplays-git-1.0.992.d3731c5-1

:: (1/1) Downloaded PKGBUILD: leaguedisplays-git
  1 leaguedisplays-git               (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: (1/1) Parsing SRCINFO: leaguedisplays-git
==> Making package: leaguedisplays-git 1.0.992.d3731c5-1 (2021-11-04T14:32:28 CET)
==> Retrieving sources...
  -> Cloning LeagueDisplays git repo...
Cloning into bare repository '/home/janek/.cache/yay/leaguedisplays-git/LeagueDisplays'...
[...]
❯ ls .local/cache/yay
completion.cache  vcs.json
```

**Comment by xeruf** [comment]
Had to remove
```json
	"buildDir": "/home/janek/.cache/yay",
	"absdir": "/home/janek/.cache/yay/abs",
```
from config.json

This should not be necessary.
