### ISSUE TITLE
Attempts to write to buildDir when not necessary

### ISSUE THREAD

**Issue by pnrao** [Jguer/yay#463]
#### Affected Version

yay v6.786

#### Issue

There are many operations related to querying packages, removing packages, changing yay's configuration, etc. that do not need access to buildDir. For such operations, yay attempts to write to buildDir, nevertheless. The problem with that is that we might have buildDir on a removable media. For example, my buildDir is set to "/mnt/exthdd3/aur", and when I execute "yay -V" with the drive unmounted, I get this error message:

    % yay -V
    Unable to create BuildDir directory:
    /mnt/exthdd3/aur/
    The error was:
    mkdir /mnt/exthdd3/aur/: permission denied

#### Steps to reproduce
1. Configure buildDir to use an external storage device
2. Unmount the external storage device
3. Perform operations with yay that should not involve downloading or rebuilding packages. For example, "yay -V", "yay -Qi yay", etc.

**Comment by Morganamilo** [comment]
During initialisation Yay checks the existence of the config and cache paths and makes them if needed. Changing Yay to only do this is possible but probably tedious.

Although if your builddir is `/mnt/exthdd3/aur/` then when unmounted that dir should still exist just be empty and Yay should ignore it.

**Comment by Jguer** [comment]
As @Morganamilo said, yay does need that initial access and it is nice that `yay` does not progress further before even attempting an upgrade that could result in a partial upgrade. Also `yay` by default shares the build dir with completions. 

This separation poses more technical difficulties and complexity than provides advantages. 

Having an empty local directory (`mnt/exthdd3/aur/`) can still solve your issue though.
