### ISSUE TITLE
Config file is created in $pwd when .config/yay is deleted

### ISSUE THREAD

**Issue by Jguer** [Jguer/yay#466]
#### Affected Version
`yay-git`

#### Issue
I have taken the custom of testing all file path modifications falling on `master` because unfortunately the track record is not very good on it (https://github.com/Jguer/yay/pull/356 , https://github.com/Jguer/yay/pull/380) and it's happened again.

Never trust file path modifications without testing all of these corner cases, my fault for dragging my feet in regression testing on this.
- Remove config/yay but keep cache/yay
- Remove cache/yay but keep config/yay
- Remove both
- Check that config/yay is created on termination
- Check that cache/aur_sh and cache/aur_fish are created
- Check that build_dir/randomAURpackage exists when tested
- Test one `yay -G` due to filepath aggregation on trunk.

Regression tracked to https://github.com/Jguer/yay/pull/462/commits/3aea877ab92ea6b17b3d282155c1e12aa6378fed

#### Steps to reproduce
1. rm -rf ~/.config/yay
2. cd /tmp/temp-yay
3. yay
4. config.json is created in the current directory

PS: Hope this is reproducible

**Comment by Morganamilo** [comment]
I hate how this boiled down to a copy paste error  e5d7cce49c2d7f6155fc1d5b2ea01fe8de8a2c49.
