### ISSUE TITLE
Some AUR packages only get dependencies installed

### ISSUE THREAD

**Issue by afg984** [Jguer/yay#47]
For example, numix-circle-icon-theme-git

Full log
https://gist.github.com/afg984/f2b5ab210eecffb71065bd1e2295e335

**Comment by muesli** [comment]
Can confirm! Noticed the same issue with `adapta-kde`. It installs its deps, then thinks it's done. Running the same command `yay -S adapta-kde`, again, will then actually install it fine.

**Comment by muesli** [comment]
Actually, this is probably a duplicate of #32.

**Comment by afg984** [comment]
This should have been fixed

**Comment by muesli** [comment]
Nice, do you plan a new release anytime soon?

**Comment by Jguer** [comment]
I'll keep it as a pre-release until I re-add development package updating. It's the only thing missing from a complete release.
