### ISSUE TITLE
Upgrade only aur packages

### ISSUE THREAD

**Issue by Jucgshu** [Jguer/yay#470]
#### Affected Version
yay 6.786

#### Issue
This is not an issue, but I can't find the answer in the manual: is there a way to upgrade only the aur packages (i.e. not the repos)?

Thanks for your help, and thanks for yay ;-)

-j

**Comment by Morganamilo** [comment]
In the -git version you can now do `yay -Sua`.

**Comment by Jucgshu** [comment]
Nice! Thanks for your answer.

Let's wait for the next release then ;-)

-j

**Comment by Morganamilo** [comment]
Well we could always use more testers on -git ;)

In the current release when you're asked what upgrades to skip, you can actually enter `^aur` to mean skip everything that's not from the aur.
