### ISSUE TITLE
PKGDEST breaks install

### ISSUE THREAD

**Issue by a-m-s** [Jguer/yay#471]
#### Affected Version

yay v6.786

#### Issue
The PKGDEST environment variable can be used to tell makepkg to put built packages in a specific place. I use it to provide an equivalent to /var/cache/pacman for AUR builds.

When PKGDEST is set yay allows makepkg to DTRT, but then cannot find the package file to install:
```
Could not find built package <name>-x86_64.pkg
```
I've confirmed that the package file exists in the destination directory (actually it had `.tar.xz` on the end, but presumably that's not the issue here).

There are a few solutions to this problem. `pacaur` chose to place soft links in its `.cache` directory, and I kind of like that.

#### Steps to reproduce

1. `export PKGDEST=/tmp`
2. `yay -S <aur-package>`
3. Install fails.

**Comment by Morganamilo** [comment]
Pacman 5.1 broke this, had since been fixed in `-git`.
