### ISSUE TITLE
Don't update git package when only "-Syu" is run

### ISSUE THREAD

**Issue by now-im** [Jguer/yay#482]
#### Affected Version

yay v6.786

#### Issue
This is not a issue, kind of a feature request. I use rstudio-desktop-git package. That package needs around 1 hour to compile and gets developed daily. It is impossible to work when the package is being compiled. Here is the old way to do it.

- yay -Syu
    Only updates the update pushed by the maintainer.
- yay -Syu --devel
    Updates package along with git commit.

Right now, yay pulls git commit when running -Syu. Kindly consider my suggestions.

**Comment by Morganamilo** [comment]
IgnorePkg is a standard Pacman feature that Yay fully supports when updating, Even for AUR packages.

**Comment by now-im** [comment]
thanks. I had no idea it existed. Fixed it by using:
`yay -Syu --ignore=rstudio-desktop-git`
