### ISSUE TITLE
Help flag requires sudo password?

### ISSUE THREAD

**Issue by whereswaldon** [Jguer/yay#49]
When I run `yay -h`, I'm prompted for my sudo password.
This is not the case when I run `yay --help`.

I can't think why help messages should require sudo access, so I'm assuming that this is a bug?

I'm running `4b78c23`, which is the current master commit. If this is a bug, I'd be happy to take a stab at correcting it myself.

**Comment by Jguer** [comment]
Yes, this should be fixed. If you want to take a stab at it, it's pretty easy.

**Comment by whereswaldon** [comment]
@Jguer Did you fix this already? I'm planning to do it still, but I'm swamped until school lets out in a week.

**Comment by Jguer** [comment]
Fixed by @AnthonyLam  https://github.com/Jguer/yay/commit/ba8e3c98e7acec611d11b61c23e4f1671f2b04fe a few commits ago
