### ISSUE TITLE
Make --ask optional

### ISSUE THREAD

**Issue by AladW** [Jguer/yay#490]
Not sure how to fill in the template on feature requests but I'm pretty sure this is valid for the master branch...

As discussed in https://github.com/actionless/pikaur/issues/201 usage of `pacman --ask` can have some undesired effects, like confirm the removal of conflicting packages that were not found by `yay` or presented to the user. As such the command was classified as "potentially harmful" on ArchWiki and `aurman` (the other active helper using `pacman --ask`) made it optional: https://github.com/polygamma/aurman#make-use-of-the-undocumented---ask-flag-of-pacman

I think it would be a good idea for `yay` to do the same, especially considering existing flags like `--answerclean` where a flag for `pacman --ask` would be a natural extension to.

----
#### Affected Version
https://github.com/Jguer/yay/commit/1002a4f5e5f82ab7480a91751d78b7b4c516c2eb

#### Issue
`--ask` used by default

#### Steps to reproduce

1. `yay -S <pkg>`
2.
3.

**Comment by Morganamilo** [comment]
Yep I'm still following the discussion slightly. Although I consider us in freeze right now. @Jguer will make a release pretty soon but it will be done.

**Comment by Jguer** [comment]
We're in feature freeze right now while stuff seems to settle down, just missing a few completions and the usual trial phase. But I'm hoping to open a new development cycle next week.

**Comment by Morganamilo** [comment]
With this we are back to yellow territory, so the wiki page should be fine for now. That is until #464 is done.
