### ISSUE TITLE
Feature Request: Option to show dependency tree when not all dependencies can be found

### ISSUE THREAD

**Issue by wbthomason** [Jguer/yay#491]
#### Affected Version

`yay v6.786`

#### Issue
I'm currently trying to install a large and deeply-nested AUR metapackage (`ros-melodic-simulators`) with `yay`. Somewhere in the dependency chain, a package incorrectly depends on `pkg-config` instead of `pkgconf`. `yay` only tells me that it couldn't satisfy the `pkg-config` dependency, and not which package depended on `pkg-config`. Having an option to print this information would be very useful, because (as far as I know) the only alternative is to manually trace the dependency tree to find the broken PKGBUILD for patching.

#### Steps to reproduce
N/A

If this is functionality that already exists, my apologies for my ignorance!

**Comment by wbthomason** [comment]
As a further note, `pacaur` does output this information when a dependency cannot be resolved.

**Comment by Morganamilo** [comment]
I'm assuming this is all fixed in -git

**Comment by wbthomason** [comment]
I'll check!

**Comment by wbthomason** [comment]
Yep, it is! Closing; sorry to accidentally spam!

**Comment by Morganamilo** [comment]
To be honest I don't think anyone has ever read the first line of the issue template. ¯\\\_(ツ)\_\/¯

**Comment by Aaron1011** [comment]
Is this now an option? How do I use it?

**Comment by xeruf** [comment]
Also wondering about how to do this to check for a conflicting dependency?
