### ISSUE TITLE
yay does not offer .install files for editing

### ISSUE THREAD

**Issue by jinks** [Jguer/yay#493]
#### Affected Version

yay v6.786

#### Issue

When installing an AUR package that contains a `.install` file (or any equivalent `install=` PKGBUILD option) yay does not offer these files up for editing.

Since `.install` files are run as root they have the potential to be way more malicious than the PKGBUILDs themselves.

#### Steps to reproduce

1.  yay -S nerd-fonts-complete
2. select the PKGBUILD for editing

#### Expected outcome

Both the `PKGBUILD` and `nerd-fonts-complete.install` are opened up for editing.
(Bonus: The presence of an install file is prominently listed in the package list so that these packages can be subjected to extra scrutiny)

#### Actual outcome

Only the `PKGBULD` is opened for editing.

**Comment by AladW** [comment]
>Since .install files are run as root they have the potential to be way more malicious than the PKGBUILDs themselves.

I've always wondered why the Secure column in the wiki only specifically handled PKGBUILDs, while the (newer) Diff view column does not... Note that .install files alone doesn't cut it, e.g. the PKGBUILD could run some custom bundled script. I guess this hits the limits of the pseudo-file-manager-via-editor interface most helpers go with.

**Comment by Morganamilo** [comment]
My view is if you read the pkgbuild, it clearly states the install files and you can easily then open them yourselves in vim. Would you consider an AUR helper secure if it just stopped and went `Please read the pkgbuilds. Press Y when you have read them`?

Anyway this should be doable as soon as #528 is merged.

Plus our diff system does handle the entire tree courtesy of git. So we should be fine on security no matter what seems as its the default option.

**Comment by AladW** [comment]
>My view is if you read the pkgbuild, it clearly states the install files and you can easily then open them yourselves in vim.

I guess you mean if you see install=foo.install, you manually do :e foo.install in vim, similarly for patch files et al. If you do, that doesn't sound very pleasant to deal with.

>Would you consider an AUR helper secure if it just stopped and went Please read the pkgbuilds. Press Y when you have read them?

That's what pretty much all the helpers do with "Optional" in the Secure column do, apart there's no explicit prompt - they just leave you with the retrieved files.

**Comment by AladW** [comment]
NB https://wiki.archlinux.org/index.php/Talk:AUR_helpers#Expand_Secure_criteria_to_include_other_.28non-PKGBUILD.29_bundled_files

**Comment by AladW** [comment]
>Oh it's not but being pleasant is not a requirement.

Ehh... okay? The other thing is that you have to come up with the idea in the first place, which advanced/creative users might, but the rest - which end up being the main audience of these helpers - less so.

On NB: https://en.wikipedia.org/wiki/Nota_bene

**Comment by Morganamilo** [comment]
Don't get me wrong. I'm still going to add the .install editing as soon as #528 is merged. I agree its better to have this. I was just talking about the minimum required criteria basically.

You're right about the types of people that are often attracted to these helpers. I do *try* to make sure people aren't doing insane thing like `-Sy pkgname` and `--noconfirm` everything. But ultimately it is the user's responsibility to know what they are doing.

**Comment by AladW** [comment]
Hm - also regarding your comment on the wiki page - maybe you could 1. edit/view PKGBUILDs and .install files 2. present what other files are in repo (`git ls-files`? could be optional) to the user. 

Not too relevant to the wider discussion on criteria, but it seems worth considering in the `yay` context.

**Comment by jinks** [comment]
> Note that .install files alone doesn't cut it, e.g. the PKGBUILD could run some custom bundled script.

True, but .install files run as root, while the PKGBUILD is built/run by an unprivileged user. Although on the typical personal system that's still a case of https://xkcd.com/1200/.

**Comment by Bryophyllum** [comment]
As I don't think it requires opening a new issue, here's one I have: I'm not shown .install files to, when using Vim. For my surprise, it works as expected with nano and _probably_ the others too.

**Comment by Morganamilo** [comment]
Have you tried `:n`?

**Comment by Bryophyllum** [comment]
@Morganamilo Not really.. _*sighs*_ I should've taken more Vim lessons, or any at all. Anyhow, thank you for your patience for my folly here. c:
