### ISSUE TITLE
yay wants to install aur packages deselected on the interactive prompt

### ISSUE THREAD

**Issue by jeLee6gi** [Jguer/yay#494]
#### Affected Version

yay v6.786

#### Issue
yay wants to upgrade packages that were deselected on the interactive prompt

#### Steps to reproduce

1. Run yay
2. Deselect packages by index

~> yay
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 repo-ck is up to date
:: Searching databases for updates...
:: Searching AUR for updates...
:: Querying AUR...
 -> Missing AUR Packages:  gtk-theme-arc-git  xkblayout-state
 -> Out Of Date AUR Packages:  adbfs-rootless-git  praat  python-gensim  signal-desktop-bin
:: 9 Packages to upgrade.
9  aur/ttf-ms-win10           10.0.16299.192-1 -> 10.0.17134.81-1
8  aur/ttf-ms-win10-japanese  10.0.16299.192-1 -> 10.0.17134.81-1
7  aur/ttf-ms-win10-korean    10.0.16299.192-1 -> 10.0.17134.81-1
6  aur/ttf-ms-win10-other     10.0.16299.192-1 -> 10.0.17134.81-1
5  aur/ttf-ms-win10-sea       10.0.16299.192-1 -> 10.0.17134.81-1
4  aur/ttf-ms-win10-thai      10.0.16299.192-1 -> 10.0.17134.81-1
3  aur/ttf-ms-win10-zh_cn     10.0.16299.192-1 -> 10.0.17134.81-1
2  aur/ttf-ms-win10-zh_tw     10.0.16299.192-1 -> 10.0.17134.81-1
1  aur/vivaldi                1.15.1147.42-1   -> 1.15.1147.47-1
==> Packages to not upgrade: (eg: 1 2 3, 1-3, ^4 or repo name)
==> 2-9

:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur: 9]  ttf-ms-win10-10.0.17134.81-1 (ttf-ms-win10-other ttf-ms-win10-sea ttf-ms-win10-zh_cn ttf-ms-win10-japanese ttf-ms-win10-korean ttf-ms-win10-thai ttf-ms-win10-zh_tw ttf-ms-win10)  vivaldi-1.15.1147.47-1

  2 ttf-ms-win10 (ttf-ms-win10-other ttf-ms-win10-sea ttf-ms-win10-zh_cn ttf-ms-win10-japanese ttf-ms-win10-korean ttf-ms-win10-thai ttf-ms-win10-zh_tw ttf-ms-win10) (Installed) (Build Files Exist)
  1 vivaldi                          (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>

**Comment by Morganamilo** [comment]
Hey, could you test a couple things for me?

Does this still happen if you skip all the packages?
And does it happen on the latest `-git`?

**Comment by jeLee6gi** [comment]
If I skip `1-9` or `aur` no packages are upgraded as expected. The `-git` version does not exhibit this problem at all and is able to correctly skip `2-9` too.

**Comment by Morganamilo** [comment]
Alright thanks. Fixed in git i guess, no idea what fixed it though.

**Comment by jeLee6gi** [comment]
Works for me. Thanks for the advice. ;)
