### ISSUE TITLE
How to remove a package?

### ISSUE THREAD

**Issue by GildedHonour** [Jguer/yay#496]
How to remove a package?

**Comment by Morganamilo** [comment]
Not to be mean, but this issue shows a huge lack of understanding of pacman, makepkg and the AUR in general.  I would suggest you Read the wiki pages of all three. It is Highly recommended to understand these tools before using AUR helpers.

**Comment by GildedHonour** [comment]
And your response shows absense of logical reasoning and presense of big imagination. Are you having a period? Pooooor.

**Comment by Morganamilo** [comment]
Well done you managed to make this my worst interaction on GitHub so far. Atleast @Jguer  @AladW @polygamma might get a laugh out of it.

**Comment by polygamma** [comment]
@GildedHonour maybe you should shift your focus from "being a sexist" to "reading readmes"

**Comment by GildedHonour** [comment]
@polygamma if you spend too much thinking about sexism, you'll start to notice it everywhere, even in the things that have nothing to do with it. 

Regarding ReadMe - where is the word "remove" or "uninstall" mentioned in it at all?

**Comment by polygamma** [comment]
@GildedHonour which definition of sexism are you referring to, so that what you said is not a sexist statement? regarding the readme: I never said which specific readme to read, in order to find out, how to remove packages with yay, but @Morganamilo gave some hints.

**Comment by TaylorDennisLee** [comment]
@GildedHonour use `pacman` and try to uninstall the AUR package just like you would a community package. For instance, after reading this thread, I would type in:

```sudo pacman -R yay```

Good question.

**Comment by AladW** [comment]
3-year olds ask better questions during potty training.

**Comment by TaylorDennisLee** [comment]
You guys read the entire README of every piece of software you use before you use it? If this is not the place to ask this kind of question, you could politely mention that along with the 15-20 keystrokes it would have taken to answer his question. This kind of attitude is a threat to the health and survival of both Linux and the open source software movement in general. It has been a long struggle to save humanity from the hell that is Microsoft WIndows, and you should all appreciate what has been sacrificed to get us this far.

**Comment by polygamma** [comment]
lol.

**Comment by Morganamilo** [comment]
Reading the readme wouldn't help. In fact if you read our entire man page we do not explicitly mention it. Like you said above, you use pacman to remove a package. Users are expected to understand the fundamentals of their package manager.

**Comment by CLOVIS-AI** [comment]
Hi, I'm new to Arch after a lot of time on Debian. From the first message; "I would suggest you Read the wiki pages of all three", I guess you mean these:

https://wiki.archlinux.org/index.php/Pacman
https://wiki.archlinux.org/index.php/AUR_helpers
https://wiki.archlinux.org/index.php/Arch_User_Repository
https://wiki.archlinux.org/index.php/Makepkg

Is there any other important wiki page I should read?

**Comment by AladW** [comment]
I would suggest #1, #2 and #4. Then if by some miracle you end up with more than 10-20 AUR packages (and email notifications don't suffice), you could read #3.

**Comment by Simmetopia** [comment]
Also, if you want to make to have success in linux, you should know how to use man.

If you type `man yay` you will find documentation saying that `yay -R` will remove a package. 

Close to all tools for Linux will have manpages, which can be accessed by `man <tool>`.

When we create open source packages, we spend a lot of our own free time to make something great for others. The least we can do as users of open source software is to consult the manual of said tools before we ask for help.

**Comment by GildedHonour** [comment]
Come teach me how to press the keys on the keyboard. If not you, who else will do that for me?

**Comment by insaaniManav** [comment]
rofl this is the best textbook example of ways to behave and not behave in open source thanks @mantainers for giving me this hilarious content 
Also thanks for developing and maintaining  yay 
God bless you guys for making our lives so darn easy :)

**Comment by GGCristo** [comment]
This is the first time I have seen such an awful thread in the open source community.
I don't know if I should be happy for taking this long or sad because I reached this point.

**Comment by alexruize** [comment]
This is the first google hit for the question at hand. SAD!

**Comment by the42** [comment]
@Simmetopia  to be fair, `man yay` has to say about `-R`:

> -R     Yay will also remove cached data about devel packages

This does not really say that the `-R` option will remove packages. Or at least it is not unambiguous and clear in saying that.
