### ISSUE TITLE
Fish completion on Upgrade not accepting uncompressed files

### ISSUE THREAD

**Issue by diggit** [Jguer/yay#498]
#### Affected Version
current upstream yay v6.786.r90.g1002a4f

#### Issue
Fish completion for package file names is not universal enough. IMO, [this is not true](https://github.com/Jguer/yay/blob/master/completions/fish#L201). 
> In practice, it's going to be tar.xz or tar.gz

Rules for `.tar.gz` and `.tar.xz` should be at least extended by `.tar.lzo` and `.tar`

**Comment by Jguer** [comment]
I'm due on updating fish completions anyway, I'll fix it
