### ISSUE TITLE
Use $XDG_CONFIG_HOME instead of ~/.config/yay?

### ISSUE THREAD

**Issue by whereswaldon** [Jguer/yay#50]
The code currently looks in the path `~/.config/yay` for the `config.json` file. That's the default location of the environment variable `$XDG_CONFIG_HOME`. The advantage of doing so is that users who choose to keep their config in abnormal locations can set the one variable and all of their tools will look in the right place. Since I think the goal is to use the user's configuration directory instead of just dumping crap right in their home directory, it seems like it would fit.

Additionally, changing it would be extremely unlikely to break existing installations, as those two paths should be identical for most users. Of course, if `$XDG_CONFIG_HOME` is unset, it should use the current hard-coded path.

I'd be happy to take this on myself if the change is wanted.

**Comment by Jguer** [comment]
It is a welcome addition, in a way I'm sorry I didn't leave it for you to implement but I haven't had much time to work on yay, so this issue felt like a good way to get back in the game.

Also, config file was declared as a global but the functions handling it were treating like a local. 93de8ba also fixes that.
