### ISSUE TITLE
Git package is not getting updated

### ISSUE THREAD

**Issue by now-im** [Jguer/yay#508]
#### Affected Version

yay v7.887
#### Issue
Running `yay -Syu --devel` is not updating aur git packages.

**Comment by Jguer** [comment]
- Have you `yay -Y --gendb` ?
- Do you git packages need updating? 
- Which ones are not getting detected?
- What is your config?
- What AUR packages do you have installed?
- Can you post your `yay -Pg`

**Comment by now-im** [comment]
1. No. I Didn't. doing it now.
2. Yes. When I used aurman it updated [this](https://aur.archlinux.org/packages/la-capitaine-icon-theme-git) package.
3. I have mentioned the package.
4. Default settings. Nothing is changed.
5. Installed Packages:
`aurman 2.14-1
ibus-avro-git 20150925-1
la-capitaine-icon-theme-git r540.fad3f223-1
rstudio-desktop-git 1.2.679-1
sierrabreeze-kwin-decoration-git r47.e1c7c2d-1
stacer 1.0.9-1
yay 7.887-1`
6. Output:
`yay -Pg                                                                                             [130]
{
        "buildDir": "/home/nowshed/.cache/yay/",
        "editor": "",
        "editorflags": "",
        "makepkgbin": "/usr/bin/makepkg",
        "pacmanbin": "/usr/bin/pacman",
        "pacmanconf": "/etc/pacman.conf",
        "tarbin": "/usr/bin/bsdtar",
        "redownload": "no",
        "rebuild": "no",
        "answerclean": "",
        "answerdiff": "",
        "answeredit": "",
        "answerupgrade": "",
        "gitbin": "git",
        "gpgbin": "gpg",
        "gpgflags": "",
        "mflags": "",
        "sortby": "votes",
        "gitflags": "",
        "requestsplitn": 150,
        "sortmode": 0,
        "sudoloop": false,
        "timeupdate": false,
        "devel": true,
        "cleanAfter": false,
        "gitclone": true,
        "provides": true,
        "pgpfetch": true,
        "upgrademenu": true,
        "cleanmenu": true,
        "diffmenu": true,
        "editmenu": false
}
`

**Comment by Jguer** [comment]
After `yay -Y --gendb`, you now have a `~/.cache/yay/vcs.json`. When devel is called `yay` will compare the hash of the remote git branch with the hash stored in the `vcs.json` from `gendb` or the last, if they do not match it will be added to the update list.

When you update the package through `aurman` that `vcs.json` is not updated and the result is not predictable (I would say you'd get the same update twice).

Conclusion:
Now that `gendb` has been done, when there is a new commit on a devel repo `yay -Syu --devel` should pick it up

**Comment by now-im** [comment]
I will post the result later.
________________________________

**Comment by now-im** [comment]
The problem seems solved.

**Comment by attila123** [comment]
Please help me understand what is happening. I saw in pacman that my package git-cola-git needs updating. I never update via pacman, I use it just for indication. When I ran `yay -Syu` (forgot --devel) it did not find that git-cola-git would need an update. So far so good.
Then I ran `yay -Syu --devel` and it found:
```
:: 2 Packages to upgrade.
2  devel/git-cola-git  v3.4.49.gba1bbc41-1    -> latest-commit
1  devel/megasync-git  v4.2.3.0.1.gb5651f2d-1 -> latest-commit
```
But I got confused as pamac did not indicate that megasync-git would need an update, so I hit Ctrl + c. (So far I updated these ...-git packages by directly invoking e.g. `yay megasync-git` individually.)
So I thought that probably the cache is out-of-date, so I ran: `yay -Y --gendb` to make sure to start from an up-to-date cache. It found all the git repos, OK.
I tried again `yay -Syu --devel` but this time it output: "there is nothing to do".
But if I try running `yay git-cola-git` then it shows the difference between installed and current:
```
1 aur/git-cola-git v3.3.2.g31d93217-1 (+18 0.01%) (Installed: v3.4.49.gba1bbc41-1)
```
So I am confused why `yay -Syu --devel` does not pick it up.
This is on Manjaro if that matters.
yay v9.2.1 - libalpm v11.0.3
The section in ~/.cache/yay/vcs.json for git-cola-git:
```
        "git-cola-git": {
                "github.com/davvid/git-cola.git": {
                        "protocols": [
                                "https"
                        ],
                        "branch": "HEAD",
                        "sha": "f912364a1cd267309e0262e4fb6052acc8b94eb2"
                }
        },
```
Strange that this sha value has nothing to do with g31d93217 or gba1bbc41 seen in the yay output above, is this OK?
`yay megasync-git` shows:
```
1 aur/megasync-git v4.0.2.0.1.g2dec1949-1 (+17 0.44%) (Installed: v4.2.3.0.1.gb5651f2d-1)
```
megasync entries in the cache:
```
        "megasync-git": {
                "github.com/meganz/MEGAsync.git": {
                        "protocols": [
                                "https"
                        ],
                        "branch": "HEAD",
                        "sha": "b5651f2d34d295a70fc20b55f7982abb2ce8b917"
                },
                "github.com/meganz/sdk.git": {
                        "protocols": [
                                "https"
                        ],
                        "branch": "HEAD",
                        "sha": "27055a7ad06203ba9eb3107b184668de98ced77a"
                }
        },
```
`yay -Pg` output:

```
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/avangel/.cache/yay",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"tarbin": "bsdtar",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"gitflags": "",
	"removemake": "ask",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"gitclone": true,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false
}
```

**Comment by Jguer** [comment]
I see many different questions and I'll try to get to them, if I miss something, feel free to ask.

```
But I got confused as pamac did not indicate that megasync-git would need an update, so I hit Ctrl + c. (So far I updated these ...-git packages by directly invoking e.g. yay megasync-git individually.)
```
No idea

```
 So I thought that probably the cache is out-of-date, so I ran: yay -Y --gendb to make sure to start from an up-to-date cache. It found all the git repos, OK.
```
Gendb is not a caching mechanism, yay needs to know what git SHAs you have installed, normally when you install by yay this file is updated. 
When a new user starts using yay, we use gendb to make a list of their git packages and put in that `.json` the latest available SHA of the repo (we have no way of reliably knowing which commit you have installed so we just assume you have the last).

So what happened is you had SHAs saved and it prompted you for an update and then you told yay by gendb to assume that you had installed the latest commits. Once there's new commits in the repo, `yay -Syu --devel` will work as expected.

```
1 aur/git-cola-git v3.3.2.g31d93217-1 (+18 0.01%) (Installed: v3.4.49.gba1bbc41-1)
```
devel won't pick it up because it assumes the installed version is the latest commit (because of gendb)
normal AUR operation won't pick it up because v3.4.49 > v3.3.2

**Comment by attila123** [comment]
OK, I now read in the yay man page that maybe I should not have used the '--gendb':
```
       --gendb
              Generate development package database. Tracks the latest commit for each development package, when there is a new commit Yay will know to update. This is done per package
              whenever a package is synced. This option should only be used when migrating to Yay from another AUR helper.
```
But I also saw that maybe the -R could fix this? `-R     Yay will also remove cached data about devel packages.` But it's not clear for me how to use these extended pacman operations. Could you please clarify? Maybe an example for this in the man page would be helpful.
Or should I simply delete ~/.cache/yay/vcs.json and then try `yay -Syu --devel` again? Is it safe to delete this file?

**Comment by Jguer** [comment]
If you delete the file, yay will be lost on your commits and you'll be in the situation you'll need to gendb it again.
`-R` will remove the package (and remove them from the commit db), we haven't wrapped '-R' just to remove from the commitdb.

Best options:
- You know what packages need building so `yay --rebuild -S megasync-git git-cola-git `
Or, untested and you'll probably be a guinea pig for this: 
- Set your `~/.cache/yay/vcs.json` shas to "0" and `yay -Syu --devel` should pick up updates
Or, just wait that upstream updates their git repositories again and devel will pick it up then

**Comment by attila123** [comment]
Thanks for the quick reply, I went with the sha "0" option and it would update these 3:
```
3  devel/httraqt-git   1.4.10.4.gd3e085c-1    -> latest-commit
2  devel/megasync-git  v4.2.3.0.1.gb5651f2d-1 -> latest-commit
1  devel/uuid          1.6.2-18               -> latest-commit
```
Actually, these were up-to-date somehow.
```
==> httraqt-git-1.4.10.4.gd3e085c-1 already made -- skipping build
loading packages...
warning: httraqt-git-1.4.10.4.gd3e085c-1 is up to date -- reinstalling
...
==> megasync-git-v4.2.3.0.1.gb5651f2d-1 already made -- skipping build
loading packages...
warning: megasync-git-v4.2.3.0.1.gb5651f2d-1 is up to date -- reinstalling
...
warning: uuid-1.6.2-18 is up to date -- reinstalling
```
Somehow I lost the git-cola-git from this vcs.json (maybe I deleted it accidentally), so for that I used `yay --rebuild -S git-cola-git`
Now everything is fine and pamac does not show any packages to update. Thanks again!
I will try to remember to use `yay -Syu --devel` from now on.

**Comment by attila123** [comment]
Regarding -R I think it has a problem and I know how git-cola-git disappeared from my vcs.json. If you cancel package removal with Ctrl + c:
```
$ yay -R git-cola-git
[sudo] password for avangel: 
checking dependencies...

Packages (1) git-cola-git-v3.4.53.gf912364a-1

Total Removed Size:  3,15 MiB

:: Do you want to remove these packages? [Y/n] ^C
Interrupt signal received
```
then the entry for the package is deleted (too soon) from vcs.json.
Is this a known issue? Should I create an issue for this?

**Comment by Jguer** [comment]
I just checked the code on that, it is being removed from the DB before being passed on to Pacman, it's indeed an unknown bug (first one in a while). 
It should be done after and confirming that it doesn't exist as package in the system anymore. 
Feel free to create an issue for this

**Comment by attila123** [comment]
Thanks for your explanations, I misunderstood gendb, now it's clear. I'm going to open the new issue about -R.

**Comment by seafox** [comment]
Has to remain a bug somewhere! I'm using 9.3.1-1 non-git version of yay.
Symptoms: I'm using several aur helpers. Wanted to have yay as a main one...
1. I have a few but not all items in vcs.json. For example, auracle-git is up to date bot it's not in this file. So after successfull run of `$ yay --rebuild -S auracle-git` the package is still absent in vcs.json, which remains untouched.
2. If I simply remove vcs.json, then run `$ yay --gendb` the file contains only the single entry for the latest git package installed in the system.
So failure either way.
Of course `$  yay -Syu --devel` says there is nothing to do...

**Comment by Jguer** [comment]
I just installed `auracle-git` on `yay-git` and I get this entry in `vcs.json`
```
	"auracle-git": {
		"github.com/falconindy/auracle.git": {
			"protocols": [
				"https"
			],
			"branch": "HEAD",
			"sha": "d59f80b1b5e3ce39aa487d9bcc1257881034d638"
		}
	},
```

these are the only rules I have on my gitconfig
````
[url "git@github.com:"]
  insteadOf = https://github.com/
[url "git@github.com:"]
  pushInsteadOf = "git://github.com/"
[url "git@github.com:"]
  pushInsteadOf = "https://github.com/"
```
do you have any such rules in `.gitconfig`?

Edit Reply: I'll try your scenario and check

**Comment by Jguer** [comment]
Renamed `yay-git` PKGBUILD to `yayV9-git`, installed it. `yayV9-git` appears as a missing AUR package in `yay -Ps`. Package validated `pacman -Qq | grep -Ee '-(cvs|svn|git|hg|bzr|darcs)$'`
 Environment set.

Deleted `vcs.json`, did `yay --rebuild -S auracle-git`, got the entry in `vcs.json`.

Deleted `vcs.json`, did `yay --gendb`, got all of the entries of the system (except yayV9-git, as expected)

**Comment by seafox** [comment]
.gitconfig - I don't have that file.
Any other clue or what to check next?

**Comment by Jguer** [comment]
The vcs part of yay hasn't been touched by `yay-git` so it's the same. 
To be able to at least reproduce this problem I may need a `yay -Qem`, also the full output of `yay --gendb` could also help.

**Comment by seafox** [comment]
what specifically you would like me to check?

**Comment by seafox** [comment]
@Jguer I copied auracle-git item you pasted here into vcs.json according to alphanumeric package name order (BTW is it intended that way or doesn't matter at all?). After that run `$ yay -Syu --devel` said there is nothing to do, as expected. Then I set auracle-git vcs.json hash to `"sha": "0"`. Re-run the same command offered to upgrade the package. Defaults were chosen. Build was skipped as it was up to date, and the right hash was written into vcs.json. So at least that part works as expected! The question is how to forcibly add other relevant dev packages, with either zeroed sha or the ones fetched from git?

**Comment by seafox** [comment]
Not related comment/feature request re your
> ...got all of the entries of the system (except yayV9-git, as expected)
Pamac isn't exactly just aur helper, but it senses need for update also locally built git packages that aren't in AUR. Care to consider some indication or trigger to alarm about those, if not directly have a path to a root of local build dir tree in yay config to perform automatic updates directly from remote source like git?

**Comment by seafox** [comment]
Updated to yay v9.3.2-1
`cd ~/.cache/yay`
==vcs.json with latest auracle-git + some others remains
`cp vcs.json vcs.json.old`
`yay -Y --gendb`
==result: file vcs.json timestamp touched, but contents remain UNMODIFIED!
`rm vcs.json`
`yay -Y --gendb`
==result: NO file vcs.json created!
`yay -S --rebuild auracle-git`
==result: build started, finished fine, appeared vcs.json file 2 bytes long containing only `{}`

**Comment by seafox** [comment]
[yay-gendb-nonames.log](https://github.com/Jguer/yay/files/3692937/yay-gendb-nonames.log)
yay --gendb output, package names stripped

**Comment by seafox** [comment]
@Jguer
==Updated to yay v9.3.3-1
`cd ~/.cache/yay`
==vcs.json with latest auracle-git hash + some others remains
`cp vcs.json vcs.json.old`
`yay -Y --gendb`
==result: only one package detected in output log (last installed in the system) and its hash has been updated (as there is pending update to it) in file vcs.json, keeping other contents, but still the rest of missing packages remains UNDETECTED! That is the exact behavior of yay v9.3.1-1
`rm vcs.json`
`yay -Y --gendb`
==result: NO file vcs.json created at all! That's the same behavior as with v9.3.2-1
`yay -S --rebuild auracle-git`
==result: build started, finished fine, appeared vcs.json file 2 bytes long containing only {} - same as 9.3.2-1
`yay -S --rebuild auracle-git`
==result: build started & finished as above, only vcs.json timestamp touched, but the 2 bytes long empty json body {} remains! - same as 9.3.2-1

As obviously detection of packages is broken, I had to add missing packages to vcs.json by hand.
BTW first run as `yay -Syu --devel` found nothing to update, then `yay -Syu` found as expexted...

**Comment by seafox** [comment]
Another glitch is when you modify json file in text editor the trail in hex is
`7D 0A 7D 0A`
but after yay modifies it, the trail is shortened by 1 byte:
`7D 0A 7D`

**Comment by Jguer** [comment]
I am on `yay 9.3.3`, I delete my `vcs.json` and I get `vcs.json` well formed.
Just installing `auracle-git` gets it added on my system and on a clean chroot. I need to know all of the dev packages you have installed to even start trying to reproduce this

**Comment by Jguer** [comment]
Better yet try the `tentative-508` branch. Delete your `vcs.json` and run `yay --gendb`

**Comment by seafox** [comment]
== after vcs.json removed, I ran these:
git clone -b tentative-508 https://github.com/Jguer/yay.git
cd yay
make build
./yay --gendb
== result the same - no vcs.json file generated!
Looks like it doesn't even go there, the last 2 lines of the output:
```
:: Parsing SRCINFO (75/75): xxxxxx
==> GenDB finished. No packages were installed
```

**Comment by Jguer** [comment]
Is there any `Structure:` printed? 
The last 2 lines don't say anything wrong, I would need the full output.

**Comment by seafox** [comment]
No. Only same line I sent you before, i.e. starting with
:: Querying AUR...
-> Missing AUR Pack...
-> Orphaned AUR...
-> Out Of Date...
:: PKGBUILD up to date...
:: Downloaded PKGBUILD...
:: Parsing SRCINFO...

BTW that bug I mentioned earlier today is also a show stopper: I'm FORCED to run `yay` for a second time in a row just to catch devel updates! (Yes, I have -devel saved to TRUE in config!). Also `yay --devel` doesn't make any diff.

**Comment by seafox** [comment]
So essentially, if one facing the same issue, here the steps to "train" yay to update a devel package, shown for auracle-git as a sample:
1. Open ~/.cache/yay/vcs,json and insert in alphabetic order the following inside main JSON {} body:
```
	"auracle-git": {
		"github.com/falconindy/auracle.git": {
			"protocols": [
				"https"
			],
			"branch": "HEAD",
			"sha": "d59f80b1b5e3ce39aa487d9bcc1257881034d638"
		}
	},
```
2. To get the value of SHA hash above for the latest version in git:
`git ls-remote https://github.com/falconindy/auracle.git | grep HEAD`
3. If you want the package to be updated, set `"sha": "0"`
4. Save the file and run `yay` (provided yoy have --devel = true in yay preferences, otherwise you'll need to use `yay --devel`) TWICE in a row, as the first time it may not detect packages.

**Comment by seafox** [comment]
> I get vcs.json well formed.

Yes, normal text tools ignore that. But check in HEX Viewer/Editor!

**Comment by Jguer** [comment]
- `yay --devel` - means `yay -Y --devel`, not `yay -Syu --devel`
- Still can't reproduce your issue

1. `rm ~/.cache/yay/vcs.json`
2. `yay --gendb`
3. `hexdump vcs.json`
  -  last line `0000210 6663 3862 0a22 0909 0a7d 7d09 7d0a`

**Comment by Jguer** [comment]
go/gcc-go version?
fs version?
installed packages?

Create a new issue if needed but this remains not reproducible

**Comment by seafox** [comment]
go version go1.13.1 linux/amd64, ext4

![hex-trail](https://user-images.githubusercontent.com/9025690/66258632-1763b880-e797-11e9-9113-3e8222bad30e.png)

**Comment by seafox** [comment]
To continue saga with tentative-508.
It didn't want to show structure after ./yay --gendb as you instructed, but:
```
yay > ./yay -Y --devel
yay > ./yay

```
== resulted nothing to do, but after second run just after:
`yay > ./yay`
== resulted printed structure To Write, which contained all packages in vcs.json, except this entry:
```
	"rts5227-dkms": {
		"github.com/kmahyyg/rts5229-dkms.git": {
			"protocols": [
				"https"
			],
			"branch": "HEAD",
			"sha": "6e5b86a9f378eeb3279f9cea70b3941beffcf9cb"
		}
	},
```
Apparently that address url was generated some time ago and probably outdated?
Will that cause yay erroneous behavior? What's the right one and why yay couldn't deal with the entry it put there some time ago?

**Comment by Jguer** [comment]
`./yay -Y --devel` - this does nothing

> Apparently that address url was generated some time ago and probably outdated?
Will that cause yay erroneous behavior? What's the right one and why yay couldn't deal with the entry it put there some time ago?

I do not understand the question

**Comment by seafox** [comment]
I'm talking about this address "github.com/kmahyyg/rts5229-dkms.git" that yay entered when the packages was installed months ago. The question is when that address wrong, what yay does? Should it remove the entry if To Write structure doesn't recognize it, or try to replace the package address, or at least alarm the user in output?

**Comment by seafox** [comment]
here we see the url changed between April and May 2019
[rts5227-dkms.zip](https://github.com/Jguer/yay/files/3693647/rts5227-dkms.zip)
