### ISSUE TITLE
makepkg isn't running

### ISSUE THREAD

**Issue by HaginCodes** [Jguer/yay#509]
#### Steps to reproduce

1. makepkg -si
2.chmod: changing permissions of '/home/NAME/yay': Operation not permitted
==> ERROR: An unknown error has occurred. Exiting...
User defined signal 1
3.

**Comment by Morganamilo** [comment]
I'm guessing you cloned the repo as root?

**Comment by HaginCodes** [comment]
nope not cloned as root cloned as a regular user.

**Comment by Morganamilo** [comment]
I'm not quite sure then. There is a bug with makepkg involving symlinks that I don't quite know the specifics of so it could be that. Can you confirm your user owns `/home/NAME/yay`?

**Comment by HaginCodes** [comment]
for some reason removing it and reinstalling it worked successfully lol, not sure why.

**Comment by Morganamilo** [comment]
I'm pretty sure you accidentally did `sudo git clone` or something, that's usually the cause. Oh well it's fixed now.

**Comment by voidus** [comment]
For anyone else discovering this, I faced the same issue after temporarily removing yay because it broke. The problem was that I had an environment variable `PACMAN=yay`, which I needed to unset before calling `makepkg -si` to re-install yay.
