### ISSUE TITLE
SRCDIR/PKGDIR in /etc/makepkg.conf

### ISSUE THREAD

**Issue by torvic9** [Jguer/yay#510]
While yay seems to respect the $SRCDIR/$PKGDIR set in /etc/makepkg.conf, it can't find the built package when installing.

1. Install with yay -S packagename
2. source goes to SRCDIR, built package to PKGDIR
3. yay fails to install with message "Could not find built package packagename..." although package is in PKGDIR.

**Comment by Morganamilo** [comment]
What version are you using? This was part of the template which you ignored :(

**Comment by torvic9** [comment]
Sorry. Deleted too much of the template...
```
pacman -Qi yay                                                                                                                                   
Name                     : yay
Version                  : 6.784-1
```

**Comment by Morganamilo** [comment]
You're running an old version. The pacman 5.1 update broke pkgdest support but it has since been fixed. You can either unset your pkgdest just for this one update or use makepkg directly.

**Comment by torvic9** [comment]
Thank you, I reported this to Manjaro which still has the old one in the repos.
