### ISSUE TITLE
Not respecting makepkg.conf?

### ISSUE THREAD

**Issue by malnvenshorn** [Jguer/yay#511]
**Version:** yay v7.887

I just tried `yay` as a replacement for `pacaur` and I noticed that only one core is used while compiling a package. In my `/etc/makepkg.conf` I have set `MAKEFLAGS="-j$(nproc)"`. Therefor all cores should be used, which is the case when using `pacaur` or running `makepkg` manually. So I guess this is some issue with `yay`.

Edit: Passing `--mflags "--config /etc/makepkg.conf"` works, but why isn't this the default?

**Comment by Morganamilo** [comment]
Yay just calls makepkg without a `--config` flag. makepkg should just find the config file on its own. Are you totally sure this problem is happening?

makeflags only apply to pkgbuilds that use make, what pkgbuilds where you testing? Also compressing the package only uses one core, so maybe you were checking during then.

**Comment by malnvenshorn** [comment]
> makepkg should just find the config file on its own

Yes that's what I thought to. `makepkg` uses `/etc/makepkg.conf` per default, but it doesn't seem to be the case when called by `yay`.

I tried to install freecad and was wondering why it took so long. Then I saw that only one core was in use for the build. When running `makepkg` manually (without any flags) all available cores are used.

> Also compressing the package only uses one core, so maybe you were checking during then.

No, compressing also uses all cores with my config.

**Comment by Morganamilo** [comment]
Weird then, no idea what would cause this unfortunately.

**Comment by dima1911** [comment]
Hi, have the same problem. 
makepkg -j13, and one core working. To slow build.

**Comment by parkerlreed** [comment]
You need to set it in the config itself.

**Comment by dima1911** [comment]
> You need to set it in the makepkg config itself.

I set it, i know what i that...

I typed -j$(nproc), -j13 and nothing.
When i compile other one all good. 
This problem started when i sw back to the arch linux.

**Comment by Aersaud** [comment]
I am also experiencing this myself. If I use yay -S it does not respect my /etc/makepkg.conf, however pulling the PKGBUILD and building it with makepkg -si directly does respect the /etc/makepkg.conf

**Comment by Sedeo77** [comment]
There is a entry in yay config file
./home/[username]/.config/yay/config.json
named
"makepkgconf="
Is this correctly set to /etc/makepkg.conf ?

**Comment by Sedeo77** [comment]
additionally to previous comment - according to man, you also can set it this way instead of editing the file directly:
yay --save --makepkgconf /etc/makepkg.conf
print current config:
yay -g --show
print default config:
yay -d --show

**Comment by molaeiali** [comment]
I have the same problem here, but it's about not respecting CARCH, I want to build mongodb-bin, it has a depends_aarch64 dependency which is not required by my architecture (x86_64) but yay is trying to install that dependency, running makepkg manually doesn't need the dependency though.

I think maybe /etc/makepkg.conf should be default in yay config
@Morganamilo

**Comment by grandchild** [comment]
@molaeiali Can you open a new issue? I think this is a different problem, in that yay doesn't parse the `depends_aarch64` correctly (and unconditionally includes it on other architectures as well). I don't think makepkg is involved in this problem.

**Comment by Jguer** [comment]
https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=mongodb-bin @molaeiali yay uses the RPC to fetch dependencies and the RPC unfortunately doesn't split between architectures making it impossible to fix (using our current dependency fetching)

**Comment by molaeiali** [comment]
Ok so, I think a new issue is not necessary anymore @grandchild, a question due, Is there any way to suggest adding it in rpc? Arch Linux mailing list? irc? or any repo to open an issue that you are aware of? @Jguer

**Comment by Jguer** [comment]
Upstream abandoned discussion with some pointers for a potential patch

https://lists.archlinux.org/pipermail/aur-dev/2014-December/003012.html 

https://bugs.archlinux.org/task/48796

---

https://bbs.archlinux.org/viewtopic.php?pid=1617103#p1617103

Does give some ideas, SRCINFO scraping and parsing would be possible but will require some ( a lot) of changes in yay and it's not the proper way to do it unlike the AUR RPC

**Comment by k4lizen** [comment]
I had the same issue installing the `python310` and `python38` packages from AUR. Then I ran `yay --save --makepkgconf /etc/makepkg.conf` and now it seems to work (I only added `MAKEFLGAS="--jobs=4"` to `/etc/makepkg.conf`). I ran `yay --save --makepkgconf ""` afterwards to see if it would revert to using only one core but it didnt, it built with 4 cores again. Very weird stuff
