### ISSUE TITLE
Full update process is aborted when gpg verification fails for one of the packages

### ISSUE THREAD

**Issue by hckr** [Jguer/yay#513]
#### Affected Version
yay v7.887.r4.g77a5cf5

#### Issue
Full update process is aborted when gpg verification fails for one of the packages. The other possibility would be to just skip that one problematic package and proceed with updating the rest. I am not sure if this behavior really is a problem, but I think I personally would like yay to proceed with installation of all the other AUR packages and then inform me at the end about the problematic ones. As you state in the README, one of the objectives of yay is to "minimize user input", so I am submitting this issue as a food for thought to maybe start a discussion. Am I maybe missing something which would make this change a no go?

#### Steps to reproduce
It's hard to reproduce, because one should have a problematic AUR package on the update list after executing plain `yay` command, then proceed to update all. An example of such package is `mingw-w64-gcc`.
My terminal output: https://pastebin.com/bGNFsFv6

**Comment by Morganamilo** [comment]
Yay does all of its dependency resolving ahead of time. Taking a package out of the process might lead to unmet dependencies. Even during an upgrade packages might have versioned dependencies on each other.

A more general `do you want to rety?` message might work. Gives you time so solve that pgp problem in another terminal before resuming.

Yay does have built in pgp importing though, weird that it did not trigger in your output. Did you disable it?

**Comment by hckr** [comment]
I didn't change anything, it's a plain git version from AUR. Maybe it isn't working properly? Or maybe `mingw-w64-gcc` isn't configured as it should be ([which one of the comments is suggesting](https://aur.archlinux.org/packages/mingw-w64-gcc/#comment-642300))?

**Comment by Morganamilo** [comment]
Yep looks like the srcinfo does not contain the gpg keys as it should. Left a comment to hopefully resolve that. That's that mystery solved.

**Comment by Morganamilo** [comment]
Maintainer just updated including them.

**Comment by hckr** [comment]
Thanks for the info.
