### ISSUE TITLE
Show both diff menu and edit menu

### ISSUE THREAD

**Issue by aenda** [Jguer/yay#514]
yay v7.887
#### Issue
According to the description of https://github.com/Jguer/yay/pull/480, the process for installing AUR packages should be to show the clean menu, the diff menu, and the edit menu. I would like to be able to see PKGBUILD diffs and then based on the diff decide whether I need to edit the file. So I have tried setting the diffmenu and editmenu options, but all that seems to happen is I get the diff menu, and am then prompted to install or not. If I see something from the diff I want to change, I cannot.

For example, when installing thunderbird-enigmail, some lines should be uncommented if you are using thunderbird-beta or thunderbird-nightly, and this gets reset every time the PKGBUILD is updated. Here, I will see that pulling the updated PKGBUILD from upstream changed things, but the only way I can seem to edit the file is by doing it manually and running makepkg, or completely disabling the diff menu, which I would prefer not to do. Is this the intended behavior or how can I get both menus to appear?
#### Steps to reproduce

1. `yay --diffmenu --editmenu --save
2. `yay -S somepackage`

**Comment by Jguer** [comment]
Works over here, can you post your `yay -Pg`?

**Comment by Morganamilo** [comment]
Beat me to it. But yeah, it should work as you described in the first paragraph.

Works as expected for me too.

**Comment by aenda** [comment]
Sure, it's highly possible I misunderstood and configured incorrectly. Here:

```
{
        "buildDir": "/home/gmend/.cache/yay",
        "editor": "",
        "editorflags": "",
        "makepkgbin": "makepkg",
        "pacmanbin": "pacman",
        "pacmanconf": "/etc/pacman.conf",
        "tarbin": "bsdtar",
        "redownload": "no",
        "rebuild": "no",
        "answerclean": "",
        "answerdiff": "",
        "answeredit": "",
        "answerupgrade": "",
        "gitbin": "git",
        "gpgbin": "gpg",
        "gpgflags": "",
        "mflags": "",
        "sortby": "votes",
        "gitflags": "",
        "requestsplitn": 150,
        "sortmode": 0,
        "sudoloop": false,
        "timeupdate": false,
        "devel": false,
        "cleanAfter": false,
        "gitclone": true,
        "provides": true,
        "pgpfetch": true,
        "upgrademenu": true,
        "cleanmenu": true,
        "diffmenu": true,
        "editmenu": true
}
```

**Comment by Morganamilo** [comment]
Config looks fine, what about the full output from `yay --editmenu --diffmenu -S pkgname`?

**Comment by aenda** [comment]
Before seeing your message I actually just removed all yay-related files, uninstalled, and reinstalled, and it seems to be working fine now. Not really sure what was going on, but I'm glad it's fixed - thanks for your help and work on this project!

**Comment by Morganamilo** [comment]
It always bugs me when the actual cause is never figured out :(

Oh well, glad it works. Thanks for reporting.

**Comment by mskiptr** [comment]
I've just encountered – what I believe is – the exact same issue. I used `yay --diffmenu --editmenu --save` command, checked if `editmenu` changed using `yay -Pg` (in a second terminal; yes: `"editmenu": false` -> `"editmenu": true`), and tried to install `aur/refind-theme-regular-git`. It is a package that I'd uninstalled yesterday, so I had some build files still left.
Choices presented to me were as follows:
```
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> A
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> A
==> Proceed with install? [Y/n] N
aborting due to user
```
So in this case, the `editmenu` was skipped.
On the other hand, when I picked not to inspect diffs, the editor worked properly:
```
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> a
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> n
==> PKGBUILDs to edit?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> a
==> Proceed with install? [Y/n] ^C⏎
```
I've also tried both options (several times) in the second terminal, as well as in a freshly started one – always with the same behavior.

My shell is `fish 3.1.2` and the `$EDITOR` is currently `nano 4.9.3`
`yay --version` – `yay v10.0.2 - libalpm v12.0.2`, installed from `community/yay 10.0.2-2` on Manjaro.
`yay -Pg` returns
```
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/piotrek/.cache/yay",
	"absdir": "/home/piotrek/.cache/yay/abs",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": true,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false
}
```
The `diff` from before everything is:
```
39c39
< 	"editmenu": false,
---
> 	"editmenu": true,
```

I did not try rebooting yet. Should I check|upload|try anything else to further isolate the cause?

**Comment by mPiotrek** [comment]
Ok, now I know what was going on. The `Proceed with install? [Y/n]` prompt does not ask whether you approve of the diffs, and want to install as is but gives you an option to quit the installation.
I'm not sure if the OP was confused by this message too, or the original issue was something else, but this is obviously the intended behavior. If anyone else runs into it, I hope this comment helps them.
