### ISSUE TITLE
Running a full update (aur and repos together)

### ISSUE THREAD

**Issue by tapir** [Jguer/yay#515]
I'm running yay version v7.887.
Coming from yaourt `-Syua` update would update both the repo packages and aur. Is there a similar possibility with yay? I've tried adding `--aur --repo` but it still only updates aur packages.

**Comment by Morganamilo** [comment]
Just `-Syu` will do both. `--aur/--repo` are meant for limiting it to just one.

**Comment by tapir** [comment]
got it thanks

**Comment by Dragas** [comment]
This is a terrible design decision. I'm trying to figure out what cli parameters I can pass, and now I'm performing a full system upgrade.

**Comment by ciwarren** [comment]
@Dragas I am dying at that comment, did the same exact thing lol.

**Comment by grandchild** [comment]
@Dragas, @ciwarren: Whenever I don't know what options a command may have, I surely don't just plain _run_ it as a first step! My first steps for unfamiliar commands are: `<cmd> --help`, `<cmd> -h` and `man <cmd>`. _All_ of which work perfectly with yay. (If all of these fail, then _may_ try running it...)

Conversely, the _overwhelmingly_ more frequent operation is to do system upgrades, so it's a good design decision, to have that available most directly.

**Comment by Dragas** [comment]
Destructive operation that runs when you forget to add *any* parameters is good design decision because it's convenient? Are you out of your mind?

**Comment by grandchild** [comment]
How is it destructive? It asks you if you want to proceed. It does nothing desctructive upfront (unless you consider updating the package list destructive -- I don't). You have to give `--noconfirm` for it to actually do something without asking. I think it's a convenient default action, yes.
