### ISSUE TITLE
yay -Yc reports 'go' as an orphaned dependency

### ISSUE THREAD

**Issue by Pratham25** [Jguer/yay#517]
#### Affected Version
yay v7.887

#### Issue
yay -Yc removes the 'go' package which was installed as a dependency for yay in the first place.

#### Steps to reproduce

1.Run yay -Yc
2.Look at the output

**Comment by Pratham25** [comment]
I suppose this is more of a question than an issue though. Is this normal and is it safe to remove the package?

**Comment by Morganamilo** [comment]
Go is a make dependency. Once Yay has been built it is safe to remove it. Of course, Go will be needed again if Yay were to update. So it's up to you if it's worth removing it.

**Comment by Pratham25** [comment]
So if I update through yay again will it automatically reinstall the dependencies?

**Comment by Morganamilo** [comment]
Yep.

**Comment by Pratham25** [comment]
K thanks
