### ISSUE TITLE
installing aur package with empty depends array fails

### ISSUE THREAD

**Issue by tiiiecherle** [Jguer/yay#527]
First of all thanks for this package manager and all the hard work you put into it ;)

#### Affected Version

7.887-1

#### Issue
Installing aur package with empty depends array fails, e.g. cubesql.
Installing / building stops complaining about not fullfilled '' dependency.
Using `yay -S --noconfirm --assume-installed ''= cubesql` works as a workaround.
The PKGBUILD contains depends=('').
Thanks for fixing in advance.

#### Steps to reproduce

`yay -S --noconfirm cubesql
`

**Comment by parkerlreed** [comment]
You used a single double quote in your post when the package actually uses two single quotes 

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cubesql#n10

**Comment by tiiiecherle** [comment]
Sorry, it was actually typed as two single quotes (just looks like double quote) and the depends=('') was copied over from the PKGBUILD. Sorry for any confusion. That`s why I referred to to PKGBUILD.

Thanks for looking into it.

**Comment by Morganamilo** [comment]
`depends=('')` is not an empty array. It is an array of size one where the package it depends on is called empty string. `depends=()` would be an empty array, but you should leave empty values out of a pkgbuilds anyway.

**Comment by Morganamilo** [comment]
I should also add using `-Sy` is a partial upgrade. https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported
