### ISSUE TITLE
No PKGBUILD prompt & non-existing build files

### ISSUE THREAD

**Issue by MatteoCampinoti94** [Jguer/yay#533]
#### Affected Version
yay v7.887

#### Issue
On a clean Arch install yay does not prompt to see/edit PKGBUILD and instead prompts to see diff file claiming that "Build Files Exists" for programs that I'm installing for the first time.

#### Steps to reproduce
`yay -S [package]`

**Comment by Jguer** [comment]
By default `yay` now displays diffs (or less) rather than offer to edit (since 885, https://github.com/Jguer/yay/releases/tag/v7.885). This setting can be changed to the old workflow for example like this:

`yay -Y --editmenu --nodiffmenu --save`

**Comment by MatteoCampinoti94** [comment]
Ahhh, thank you. I will edit my shortcuts then.

**Comment by MatteoCampinoti94** [comment]
Sorry for opening the issue, hadn't noticed the new FAQ in the README my fault.

ps: sorry for the close-open-close, clicked the wrong button
