### ISSUE TITLE
Repo packages not being installed

### ISSUE THREAD

**Issue by Jguer** [Jguer/yay#534]
#### Affected Version
`yay v7.887.r24.g18bbc98`
`yay-git`

#### Issue
Tried on a clean config, 
`yay -S` and `yay` both fail to install repo packages

If the package is already installed `yay` will offer to reinstall the package. This regression is only valid on packages without an existing install (could explain why upgrade is not affected)

#### Steps to reproduce
1. `yay numlock` and selection 1

1. `yay -S numlockx`

(Does not affect `yay -Si`)

@Morganamilo unless off the top of your mind you know what caused this regression, I'll check it later

**Comment by Morganamilo** [comment]
Works with `--combinedupgrade` I guess I focused to much on susupgrade and forgot to test `-S`
