### ISSUE TITLE
Yay doesn't install some package dependencies

### ISSUE THREAD

**Issue by kodo-pp** [Jguer/yay#536]
#### Affected Version

`yay v7.887.r24.g18bbc98`

#### Issue
Yay doesn't install some package dependencies.

Example: `python-theano` AUR package has `python2-numpy` as dependency, but it isn't installed by yay. When makepkg is being run by yay with `--nobuild -fC` (by `buildInstallPkgBuilds` function in `install.go`) it [makepkg] fails to install `python2-numpy` (because `-s` option is not passed to makepkg)

What seems even more strange to me is that other dependencies of `python-theano` (e.g. `python-numpy` (not python2) or `python2-nose`) are installed automatically, but not `python2-numpy`

#### Steps to reproduce

Assuming that `python-theano` and `python2-numpy` are not installed
1. Command: `yay -S python-theano`. Output:
```
:: There are 2 providers available for python-theano:
:: Repository AUR
    1) python-theano 2) python-theano-git 

Enter a number (default=1): 1
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur: 1]  python-theano-1.0.2-1

  1 python-theano                            (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> a
:: Deleting (1/1): /home/kodopp/.cache/yay/python-theano
:: Downloading PKGBUILD (1/1): python-theano
Cloning into 'python-theano'...
remote: Counting objects: 78, done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 78 (delta 11), reused 78 (delta 11)
Unpacking objects: 100% (78/78), done.
HEAD is now at 7c437e9 commented out test
Already up to date.
  1 python-theano                            (Build Files Exist)
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> PKGBUILDs to edit?
==> n
:: Parsing SRCINFO (1/1): python-theano
==> Making package: python-theano 1.0.2-1 (Fri 06 Jul 2018 12:10:45 AM MSK)
==> Retrieving sources...
  -> Downloading Theano-1.0.2.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   122  100   122    0     0    859      0 --:--:-- --:--:-- --:--:--   859
100   323  100   323    0     0    637      0 --:--:-- --:--:-- --:--:--   637
100 2770k  100 2770k    0     0   838k      0  0:00:03  0:00:03 --:--:-- 1064k
==> Validating source files with sha256sums...
    Theano-1.0.2.tar.gz ... Passed
==> Cleaning up...
==> Making package: python-theano 1.0.2-1 (Fri 06 Jul 2018 12:10:49 AM MSK)
==> Checking runtime dependencies...
==> Missing dependencies:
  -> python2-numpy
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
Error making: python-theano
```

However, `python-theano` has `python2-numpy` in the dependencies list in .SRCINFO and PKGBUILD, so I think yay should install it before trying to build `python-theano`

If I then install `python2-numpy`, everything will work, but for some reason it is not installed automatically as a dependency

**Comment by kodo-pp** [comment]
I have noticed now that I can't install `python2-numpy` with yay: when I run `yay -S python2-numpy` I just get nothing:
```
kodopp@archlinux ~ $ yay -S python2-numpy
kodopp@archlinux ~ $ 
```

The same is true for `yay -s python2-numpy` too:
```
kodopp@archlinux ~ $ yay -s python2-numpy
4 aur/python2-numpy-openblas 1.14.5-1 (+11 0.02%) 
    Scientific tools for Python - built with openblas
3 aur/python2-numpydoc 0.7.0-1 (+15 0.00%) (Out-of-date 2018-03-03) 
    Sphinx extension to support docstrings in Numpy format
2 aur/python2-numpy-mkl 1.14.2-1 (+28 0.93%) (Out-of-date 2018-06-25) 
    Scientific tools for Python compiled with intel mkl
1 extra/python2-numpy 1.14.5-1 (2.5 MiB 18.1 MiB) 
    Scientific tools for Python
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 1
kodopp@archlinux ~ $ 
```

It can be installed via `pacman`, however (it is a repo package, not AUR)

**Comment by Morganamilo** [comment]
The pkgbuild seems to be doing some funky stuff. First if defines Depends as:

```
depends=('python'  'python-numpy' 
         'python2' 'python2-numpy')
```

Then the python2 version overrides to:

```
depends=('python2' 'python2-numpy')
```

And the python3 version:
```
depends=('python' 'python-numpy')
```
Now personally I would ditch the global depends and instead append those to the global makedepends. Although strictly I don't really know if the current pkgbuild is considered bad by makepkg's terms. What I can see is the rpc does not support this.

https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=python-theano

I would just tell the maintainer to move the depnds to makedepends. It might be worth reporting it as an rpc bug too but at the rate things are I don't know if it will ever be fixed.

**Comment by Morganamilo** [comment]
Actually thinking about it, I don't know if these packages are actually needed to make the package. In that case the global depends should just be removed.

Closing because of no reply and upstream issue.
