### ISSUE TITLE
Add --noedit flag

### ISSUE THREAD

**Issue by brandon099** [Jguer/yay#54]
Currently using pacaur, and I'd like to request a `--noedit` flag added to yay. I've got some of my installation process scripted and have a few AUR packages I'd like to continue to have my scripted installations "unattended" if switching to yay.

**Comment by MarcelBochtler** [comment]
If this is a wanted feature, I would like to try and implement it.

**Comment by Jguer** [comment]
I'm trying to understand this issue more clearly, I have also had AUR install scripts depend on yay and using ´yay --noconfirm´ I bypass the edit ´PKGBUILD´ stage and the package confirm install. So right now if ´--noedit´ was implemented your script would still be stuck at the "Confirm package installation".

I have no problem with adding a --noedit flag, I'm just confused at your use case.

**Comment by MarcelBochtler** [comment]
In pacaur you have the differentiation between '--noconfirm' which skips everything. So conflicting packages get replaced and so on. The '--noedit' option only skips the user input for editing the PKGBUILDs.
But you still need to confirm the installation.

As far as I saw in the code 'yay --conconfirm' causes the following things:
- Removal of make dependencies
- Not removing already existing build files
- Not editing PKGBUILD
- Confirm the installation of dependencies
- Confirm installation even if some dependencies were not found

I'm not sure how yay would handle conflicting packages with the '--noconfirm' option.

**Comment by Jguer** [comment]
In case of a package conflict yay would drop out with no installed packages since it is pacman's default action. 
If `--noedit` is useful for some scripting action and familiar to people who have used other AUR Helpers, I find no reason not to implement it. I don't think it classifies as feature creep.

If want to try and implement it, I say go for it.

**Comment by MarcelBochtler** [comment]
I don't see the use case for scripted installation with '--noedit' because pacaur also asks for confirmation. Maybe @brandon099 can explain the use for this.

**Comment by brandon099** [comment]
I must have misunderstood what `--noconfirm` did. I hadn't tried one without the other as the man pages don't seem to clearly indicate noconfirm overrides editing PKGBUILDs. 

I was under the impression you had to pass both noedit and noconfirm to skip all prompts and editing PKGBUILD's. 

From a scripted perspective `--noconfirm` seems to do the trick with yay bypassing _all_ commands that require confirmation from the user. 

Nice for familiarity, but from a functional perspective, it's working just great for me knowing that's how noconfirm works. 😄

**Comment by Jguer** [comment]
Closing this for now until someone else brings it up again.

**Comment by jsayol** [comment]
Reviving this. Here's my use case: when I run `yay -Syu` I still want to be asked what AUR packages to skip updating (`Enter packages you don't want to upgrade`) but I don't want to be prompted to edit PKGBUILDs and such (`==> Edit PKGBUILD? [y/N]`). Using `--noconfirm` skips both steps, so in this case `--noedit` would still ask the first question but would not prompt to edit.

Let me know if you need any further clarification.

P.S.: Thanks for Yay! Just started using it and it's a great alternative to apacman :)

**Comment by AlexWayfer** [comment]
> Closing this for now until someone else brings it up again.

I'm bringing it up!

**Comment by Morganamilo** [comment]
I think #226 is a replacement for this which I plan to implement at some point.

**Comment by AlexWayfer** [comment]
> I think #226 is a replacement for this which I plan to implement at some point.

OK, thank you.
