### ISSUE TITLE
Feature request: Option to view PKGBUILDs by default before executing them

### ISSUE THREAD

**Issue by twisty1** [Jguer/yay#541]
As the default behavior, Yay should give the user an option to view and modify PKGBUILDs before running them when using the -S switch. This is to avoid issues and adhere to the best practice of reviewing PKGBUILDs before running them.

**Comment by Morganamilo** [comment]
Can you point out where Yay runs a pkgbuild before giving the option to review?

**Comment by parkerlreed** [comment]
I think he's referring to the default diff view now. Doesn't let you view the whole PKGBUILD without having to pass in extra arguemtns

https://github.com/Jguer/yay/issues/533#issuecomment-402663676

**Comment by Morganamilo** [comment]
But they did say

>This is to avoid issues and adhere to the best practice of reviewing PKGBUILDs before running them.

Which implies Yay is doing something wrong or insecure. So I don't really know what they mean.

**Comment by parkerlreed** [comment]
I see it as being interpreted a few ways.

>adhere to the best practice of reviewing PKGBUILDs before running them

1. I As the user could manually go to the AUR website and review the PKGBUILD for any abnormalities. This takes the most time.

2. Whatever AUR helper you are using offering the PKGBUILD straight up for review. This is more streamlined. Showing diffs may skip over something malicious that might have been added 5 commits back. I think this is what OP was taking issue with.

**Comment by Morganamilo** [comment]
For point 2:

Diffs are from `HEAD` to `HEAD@{u}` so it doesn't matter the amount of commits that have passed. If this is the first time cloning the package the diff is `/dev/null` to `HEAD`.

**Comment by parkerlreed** [comment]
Oh I did not realize. That's actually a great middle-ground.

**Comment by twisty1** [comment]
As others have said, Yay only outputs diffs which while can be useful such as when upgrading packages is not giving the complete story to the user when installing. 

For example, compare the output of Yay to another AUR helper Trizen:

**Yay:**
![yay](https://user-images.githubusercontent.com/41043633/42551495-d2e01d82-851a-11e8-8ef8-5c1bbf728f3e.png)

**Trizen:**
![trizen](https://user-images.githubusercontent.com/41043633/42551503-dca07e98-851a-11e8-90f3-fa192878bba1.png)

As you can see, the latter displays the PKGBUILD in full before continuing and also it asks the user if they want to edit it. It would be great if Yay could at least give the user the choice to review the full PKGBUILD before continuing with the installation on the PC in the interests of security given it's coming from AUR.

**Comment by twisty1** [comment]
The problem is the way Yay approaches these diffs, where they are pretty buried and easily unintentionally skipped over by the user during the install of a package. Other AUR helpers make reviewing the PKGBUILD an explicit step the user must do, which in practice is a much better approach I believe as it's something universally recommended to do when dealing with AUR.

**Comment by Morganamilo** [comment]
>he ability to miss things from several versions back is also a consideration as Yay doesn't display that information either.

See my last comment

>reviewing the full current PKGBUILD

See the edit on @parkerlreed's first post.

**Comment by mbunkus** [comment]
I would really like to see the possibility to edit those PKGBUILDs that I've never seen before and to diff the ones that I have. Why? Because reviewing a whole new file is easier in an editor including syntax highlighting. Reading a diff from `/dev/null` to the current file makes reasoning about the content much harder, mistakes harder to spot.

Once I have reviewed the whole PKGBUILD, I'm fine with reviewing only the differences as ideally those only contain a couple of lines.

**Comment by mbunkus** [comment]
Hmm I see what you mean. I was probably confused because I'm still in the phase of switching to yay — meaning there are a lot of AUR packages that are installed already but for which yay hasn't cloned the repository yet. For those it shows the diff which is basically from `/dev/null`. This should not happen anymore as soon I'll have updated all installed AUR packages with yay at least once.

So… sorry for my post, please disregard it :)

**Comment by iTrooz** [comment]
If you want to improve your workflow by showing diffs by default, you can write
```json

{
  "answerdiff": "a"
}
 ```
to `~/.config/yay/config.json`. (You can see all config options [here](https://github.com/Jguer/yay/blob/38397d1609cd01cb95d3ce2942beeec794eded6e/pkg/settings/config.go#L25))
