### ISSUE TITLE
Feature Request: Waiting for pacman's lock

### ISSUE THREAD

**Issue by zhou13** [Jguer/yay#542]
When pacman is running, yay will exit with error 1:
```
$ yay -Syu
:: Synchronizing package databases...
error: failed to update core (unable to lock database)
error: failed to update extra (unable to lock database)
error: failed to update community (unable to lock database)
error: failed to update multilib (unable to lock database)
error: failed to synchronize all databases
```

However, yaourt can wait until pacman exits:
```
$ yaourt -Syu
==> Pacman is currently in use, please wait.
```

This is very convenient when you want to multi-task.  Is it possible to add this feature to yay?

**Comment by Jguer** [comment]
2 possibilities here:
- Adding it in `passToPacman` for 'S' and 'D' operations
- Or right at cmd.go for 'S', 'D' and 'yogurt' (2 yay instances could be released at same time, `yogurt` operation can just be for browsing, no sense locking so fast)
Actually `passToPacman` seems like the only rational choice

**Comment by Morganamilo** [comment]
You'd also need to handle -F and -U. Basically any operation that writes to the database. -Si and -Dk can run while locked.

**Comment by Morganamilo** [comment]
You can discriminate by the ones that need it on some operations and by the ones that don't on others. `needsRoot()` basically already does this.
