### ISSUE TITLE
Yay doesn't seem to upgrade AUR packages

### ISSUE THREAD

**Issue by mortie** [Jguer/yay#545]
#### Affected Version
yay v7.887

#### Issue
Official repository packages are upgraded when I run `yay -Syu`, but AUR packages are not.

#### Steps to reproduce
1. Have out of date AUR packages
2. Run `yay -Syu`
3. No AUR packages are updated.

I don't know if I'm doing anything wrong, but according to everything I've seen, `yay -Syu` should have updated both official packages and AUR packages. Running the command on my system lists this line: `-> Out Of Date AUR Packages:  clion  dwarffortress-lnp-git  lcov  qtwebkit-bin`, but doesn't upgrade them.

I don't know if it's relevant, but this is the third time I'm switching AUR helpers on this system; I started with packer, then used pacaur, then trizen, and now yay.

**Comment by Morganamilo** [comment]
Out of date is an upstream flag. https://aur.archlinux.org/packages/clion

@Jguer  Probably time we made this an FAQ entry.

**Comment by matthias-g** [comment]
Or maybe change the message to something like `Packages flagged out-of-date: ...`? This would better correspond to the AUR website.
