### ISSUE TITLE
Incorrect handaleing of AUR packages provided by repo packages

### ISSUE THREAD

**Issue by LuSo58** [Jguer/yay#546]
#### Affected Version
yay v7.887.r30.gfafaa26

#### Issue
Yay has troubles working with AUR packages, that are "provided" by any repo packages.
Yay scans the repos and considers providers of packages from repos as replacements (So if a package has to be updated, a "providing package" is installed instead of a newer version of the actual package from AUR). `yay -Syu --aur` works, but it would be better, if `yay -Syu` could manage all updates.

#### Steps to reproduce
1. Have any jetbrains IDE from AUR installed
2. `yay -Syu`
3. Get a message saying, they'll be replaced by `jetbrains-toolbox` (doesn't say why, but probably because it provides them)

**Comment by Morganamilo** [comment]
Can you give the full output?

**Comment by Jguer** [comment]
Waiting for the result of this issue before tagging

**Comment by LuSo58** [comment]
Sorry for the late response. The thing is, that `antergos/jetbrains-toolbox` provides and conflicts with `clion`, `phpstorm`, ... (all the jetbrains IDEs, that are available from AUR), and when updating, yay wants to install jetbrains-toolbox, therefore removing all the AUR packages, that conflict with it, regardless that they are explicitly installed. If I first update with `--repo` option and then with `--aur` option, it works, because then I "force the update from AUR", I guess. I cannot give you the output now, because I have everything at the latest versions, but I remember, there wasn't anything in it like "removing foo, because provided by bar". It just showed, that it's going to install jetbrains-toolbox, and then, that that conflicts with an installed package and asks me whether it should keep or replace (which had the same formatting like when pacman ask for such thing).

**Comment by Morganamilo** [comment]
I'm afraid there's I can do really without the output. Maybe next update eh? Although If you could show me an `-Si` and `-Qi` of the involved packages that would be helpful.

**Comment by LuSo58** [comment]
yay -Qi intellij-idea-ultimate-edition
Name            : intellij-idea-ultimate-edition
Version         : 2018.1.6-1
Description     : An intelligent IDE for Java, Groovy and other programming languages with advanced refactoring features intensely focused on developer productivity.
Architecture    : any
URL             : https://www.jetbrains.com/idea/
Licenses        : Commercial
Groups          : None
Provides        : None
Depends On      : giflib  libxtst
Optional Deps   : intellij-idea-ultimate-edition-jre: JetBrains custom JRE (Recommended) [installed]
                  java-environment: Required if intellij-idea-ultimate-edition-jre is not installed [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 1082,42 MiB
Packager        : Unknown Packager
Build Date      : Pá 20. červenec 2018, 12:24:09 CEST
Install Date    : Pá 20. červenec 2018, 12:40:34 CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None

--------------------------------------------
yay -Si jetbrains-toolbox
Repository      : antergos
Name            : jetbrains-toolbox
Version         : 2:1.9.3935-1
Description     : One-stop access to all your coding tools from JetBrains.
Architecture    : any
URL             : http://www.jetbrains.com/toolbox/
Licenses        : custom
Groups          : development  IDE  editor  jetbrains
Provides        : clion  clion-eap  phpstorm  phpstorm-eap  webstorm  webstorm-eap  rubymine  rubymine-eap  pycharm-pro-eap  pycharm-com-eap  pycharm-eap  pycharm-professional  pycharm-community
                  intellij-idea-ultimate-edition  intellij-idea-community-edition  intellij-idea-ue-eap
Depends On      : fuse  openssl-1.0
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 83,14 MiB
Installed Size  : 84,25 MiB
Packager        : Antergos Build Server <dev@antergos.com>
Build Date      : Pá 22. červen 2018, 20:48:17 CEST
Validated By    : MD5 Sum  SHA-256 Sum  Signature

**Comment by LuSo58** [comment]
yay -Syu
[sudo] password for luso: 
:: Synchronizing package databases...
 antergos is up to date
 core                                                                                                 131,8 KiB  79,4K/s 00:02 [#############################################################################] 100%
 extra                                                                                               1652,4 KiB   283K/s 00:06 [#############################################################################] 100%
 community                                                                                              4,5 MiB   354K/s 00:13 [#############################################################################] 100%
 multilib is up to date
 DEB_Arch_Extra                                                                                         3,6 KiB  0,00B/s 00:00 [#############################################################################] 100%
 DEB_Arch_Extra.sig                                                                                   280,0   B  0,00B/s 00:00 [#############################################################################] 100%
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (13) acpi_call-dkms-1.1.0-144  chromium-68.0.3440.75-1  curl-7.61.0-2  libnm-1.12.2-1  libnm-glib-1.12.2-1  linux-zen-4.17.9-1  linux-zen-docs-4.17.9-1  linux-zen-headers-4.17.9-1
              networkmanager-1.12.2-1  nvidia-dkms-396.24-19  pkgconf-1.5.2-1  webrtc-audio-processing-0.3.1-1  whois-5.3.2-1

Total Download Size:   146,28 MiB
Total Installed Size:  405,10 MiB
Net Upgrade Size:        1,14 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 curl-7.61.0-2-x86_64                                                                                 927,0 KiB   123K/s 00:08 [#############################################################################] 100%
 pkgconf-1.5.2-1-x86_64                                                                                54,0 KiB   600K/s 00:00 [#############################################################################] 100%
 chromium-68.0.3440.75-1-x86_64                                                                        45,1 MiB   340K/s 02:16 [#############################################################################] 100%
 libnm-1.12.2-1-x86_64                                                                                861,4 KiB   402K/s 00:02 [#############################################################################] 100%
 libnm-glib-1.12.2-1-x86_64                                                                           622,5 KiB   181K/s 00:03 [#############################################################################] 100%
 linux-zen-4.17.9-1-x86_64                                                                             74,3 MiB   364K/s 03:29 [#############################################################################] 100%
 linux-zen-docs-4.17.9-1-x86_64                                                                         5,9 MiB   410K/s 00:15 [#############################################################################] 100%
 linux-zen-headers-4.17.9-1-x86_64                                                                      8,3 MiB   345K/s 00:25 [#############################################################################] 100%
 networkmanager-1.12.2-1-x86_64                                                                         2,2 MiB   400K/s 00:06 [#############################################################################] 100%
 nvidia-dkms-396.24-19-x86_64                                                                           7,9 MiB   394K/s 00:20 [#############################################################################] 100%
 webrtc-audio-processing-0.3.1-1-x86_64                                                               287,3 KiB   603K/s 00:00 [#############################################################################] 100%
 whois-5.3.2-1-x86_64                                                                                  36,9 KiB   647K/s 00:00 [#############################################################################] 100%
 acpi_call-dkms-1.1.0-144-x86_64                                                                       11,3 KiB   563K/s 00:00 [#############################################################################] 100%
(13/13) checking keys in keyring                                                                                               [#############################################################################] 100%
(13/13) checking package integrity                                                                                             [#############################################################################] 100%
(13/13) loading package files                                                                                                  [#############################################################################] 100%
(13/13) checking for file conflicts                                                                                            [#############################################################################] 100%
(13/13) checking available disk space                                                                                          [#############################################################################] 100%
:: Running pre-transaction hooks...
(1/1) Remove DKMS modules
==> dkms remove broadcom-wl/6.30.223.271 -k 4.17.8-1-zen
==> dkms remove vboxhost/5.2.16_OSE -k 4.17.8-1-zen
==> dkms remove nvidia/396.24 -k 4.17.8-1-zen
==> dkms remove acpi_call/1.1.0 -k 4.17.8-1-zen
:: Processing package changes...
( 1/13) upgrading acpi_call-dkms                                                                                               [#############################################################################] 100%
( 2/13) upgrading chromium                                                                                                     [#############################################################################] 100%
( 3/13) upgrading curl                                                                                                         [#############################################################################] 100%
( 4/13) upgrading libnm                                                                                                        [#############################################################################] 100%
( 5/13) upgrading libnm-glib                                                                                                   [#############################################################################] 100%
( 6/13) upgrading linux-zen                                                                                                    [#############################################################################] 100%
( 7/13) upgrading linux-zen-docs                                                                                               [#############################################################################] 100%
( 8/13) upgrading linux-zen-headers                                                                                            [#############################################################################] 100%
( 9/13) upgrading networkmanager                                                                                               [#############################################################################] 100%
(10/13) upgrading nvidia-dkms                                                                                                  [#############################################################################] 100%
(11/13) upgrading pkgconf                                                                                                      [#############################################################################] 100%
(12/13) upgrading webrtc-audio-processing                                                                                      [#############################################################################] 100%
(13/13) upgrading whois                                                                                                        [#############################################################################] 100%
:: Running post-transaction hooks...
(1/8) Updating linux-zen module dependencies...
(2/8) Install DKMS modules
==> dkms install acpi_call/1.1.0 -k 4.17.9-1-zen
==> dkms install nvidia/396.24 -k 4.17.9-1-zen
==> dkms install vboxhost/5.2.16_OSE -k 4.17.9-1-zen
==> dkms install broadcom-wl/6.30.223.271 -k 4.17.9-1-zen
(3/8) Updating linux-zen initcpios...
==> Building image from preset: /etc/mkinitcpio.d/linux-zen.preset: 'default'
  -> -k /boot/vmlinuz-linux-zen -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-zen.img
==> Starting build: 4.17.9-1-zen
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [autodetect]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
  -> Running build hook: [keyboard]
  -> Running build hook: [keymap]
  -> Running build hook: [encrypt]
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
==> Generating module dependencies
==> Creating gzip-compressed initcpio image: /boot/initramfs-linux-zen.img
==> Image generation successful
==> Building image from preset: /etc/mkinitcpio.d/linux-zen.preset: 'fallback'
  -> -k /boot/vmlinuz-linux-zen -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-zen-fallback.img -S autodetect
==> Starting build: 4.17.9-1-zen
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
==> WARNING: Possibly missing firmware for module: aic94xx
==> WARNING: Possibly missing firmware for module: wd719x
  -> Running build hook: [keyboard]
  -> Running build hook: [keymap]
  -> Running build hook: [encrypt]
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
==> Generating module dependencies
==> Creating gzip-compressed initcpio image: /boot/initramfs-linux-zen-fallback.img
==> Image generation successful
(4/8) Updating icon theme caches...
(5/8) Reloading system manager configuration...
(6/8) Reloading device manager configuration...
(7/8) Arming ConditionNeedsUpdate...
(8/8) Updating the desktop file MIME type cache...
:: Searching databases for updates...
:: Searching AUR for updates...
 -> Out Of Date AUR Packages:  freeoffice  goland  goland-jre
:: 8 Packages to upgrade.
8  aur/clion                               1:2018.1.6-1 -> 1:2018.2-1
7  aur/clion-cmake                         1:2018.1.6-1 -> 1:2018.2-1
6  aur/clion-gdb                           1:2018.1.6-1 -> 1:2018.2-1
5  aur/clion-jre                           1:2018.1.6-1 -> 1:2018.2-1
4  aur/clion-lldb                          1:2018.1.6-1 -> 1:2018.2-1
3  aur/intellij-idea-ultimate-edition      2018.1.6-1   -> 2018.2-1
2  aur/intellij-idea-ultimate-edition-jre  2018.1.6-1   -> 2018.2-1
1  aur/pycharm-professional                2018.1.4-1   -> 2018.2.0-1
==> Packages to not upgrade: (eg: 1 2 3, 1-3, ^4 or repo name)
==> 
:: Checking for conflicts...
:: Checking for inner conflicts...

==> Package conflicts found:
==> You will have to confirm these when installing
 -> Installing jetbrains-toolbox will remove: pycharm-professional (pycharm-community)

[Repo: 1]  jetbrains-toolbox-2:1.9.3935-1
[Aur: 5]  clion-1:2018.2-1 (clion-cmake clion-gdb clion-jre clion-lldb)  intellij-idea-ultimate-edition-2018.2-1 (intellij-idea-ultimate-edition-jre)

  2 clion (clion-cmake clion-gdb clion-jre clion-lldb) (Installed) (Build Files Exist)
  1 intellij-idea-ultimate-edition (intellij-idea-ultimate-edition-jre) (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: Downloading PKGBUILD (1/2): clion (clion-cmake clion-gdb clion-jre clion-lldb)
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 4 (delta 2), reused 3 (delta 1)
Unpacking objects: 100% (4/4), done.
From https://aur.archlinux.org/clion
   f584bb1..88c7e12  master     -> origin/master
:: Downloading PKGBUILD (2/2): intellij-idea-ultimate-edition (intellij-idea-ultimate-edition-jre)
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 2), reused 0 (delta 0)
Unpacking objects: 100% (4/4), done.
From https://aur.archlinux.org/intellij-idea-ultimate-edition
   2c05b81..60c9f0a  master     -> origin/master
  2 clion (clion-cmake clion-gdb clion-jre clion-lldb) (Installed) (Build Files Exist)
  1 intellij-idea-ultimate-edition (intellij-idea-ultimate-edition-jre) (Installed) (Build Files Exist)
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> Diffs to show?
==> 
HEAD is now at f584bb1 Update to 2018.1.6
Updating f584bb1..88c7e12
Fast-forward
 .SRCINFO | 10 +++++-----
 PKGBUILD |  4 ++--
 2 files changed, 7 insertions(+), 7 deletions(-)
HEAD is now at 2c05b81 [intellij-idea-ultimate-edition] Update to 2018.1.6
Updating 2c05b81..60c9f0a
Fast-forward
 .SRCINFO | 8 ++++----
 PKGBUILD | 6 +++---
 2 files changed, 7 insertions(+), 7 deletions(-)
:: Parsing SRCINFO (1/2): clion (clion-cmake clion-gdb clion-jre clion-lldb)
:: Parsing SRCINFO (2/2): intellij-idea-ultimate-edition (intellij-idea-ultimate-edition-jre)
[sudo] password for luso: 
Sorry, try again.
[sudo] password for luso: 
:: jetbrains-toolbox is in IgnorePkg/IgnoreGroup. Install anyway? [Y/n]

----------------------------------------------------------------------------------------------
Here's the output. I tried adding it to ignored packages, but it seems, it didn't help.

**Comment by Morganamilo** [comment]
That's really confusing me because jetbrains-toolbox had no conflicts. I don't know why yay is prompting that. Also I have no idea why it's ignoring the ignorepkg. I'll look into it.

**Comment by Morganamilo** [comment]
Also nothing thing is pacman should be printing a warning when it skips the jetbrains upgrade. Have you omitted some output?

**Comment by LuSo58** [comment]
No. That's what's confusing me too. Also, the conflicts are, that `jetbrains-toolbox` both provides and conflicts with the AUR packages. There are conflicts, but they aren't the problem. The problem is, that instead of upgrading the explicitly installed package, it wants to install the package, that provides the "meta-packages", just because it is in the repositories and not in AUR. (That's just my guess, but the only explanation I could think of.)

**Comment by LuSo58** [comment]
Another update, but it looks, that having `jetbrains-toolbox` in ingored packages and telling yay not to install it when it asks, works.

--------------------------------------------------------------------------
```
--- [ top ommited ] ---
( 7/12) Reloading system manager configuration...
( 8/12) Creating system user accounts...
( 9/12) Creating temporary files...
(10/12) Reloading device manager configuration...
(11/12) Arming ConditionNeedsUpdate...
(12/12) Updating the desktop file MIME type cache...
:: Searching databases for updates...
:: Searching AUR for updates...
 -> Out Of Date AUR Packages:  freeoffice  rubymine
:: 14 Packages to upgrade.
14  aur/clion                               1:2018.1.6-1 -> 1:2018.2-2
13  aur/clion-cmake                         1:2018.1.6-1 -> 1:2018.2-2
12  aur/clion-gdb                           1:2018.1.6-1 -> 1:2018.2-2
11  aur/clion-jre                           1:2018.1.6-1 -> 1:2018.2-2
10  aur/clion-lldb                          1:2018.1.6-1 -> 1:2018.2-2
 9  aur/goland                              2018.1.5-1   -> 2018.2-1
 8  aur/goland-jre                          2018.1.5-1   -> 2018.2-1
 7  aur/intellij-idea-ultimate-edition      2018.1.6-1   -> 2018.2-1
 6  aur/intellij-idea-ultimate-edition-jre  2018.1.6-1   -> 2018.2-1
 5  aur/lutris                              0.4.18-1     -> 0.4.18.1-2
 4  aur/phpstorm                            2018.1.6-1   -> 2018.2-1
 3  aur/phpstorm-jre                        2018.1.6-1   -> 2018.2-1
 2  aur/pycharm-professional                2018.1.4-1   -> 2018.2.0-1
 1  aur/superlu                             5.2.1-3      -> 5.2.1-4
==> Packages to not upgrade: (eg: 1 2 3, 1-3, ^4 or repo name)
==> 
:: Checking for conflicts...
:: Checking for inner conflicts...

==> Package conflicts found:
==> You will have to confirm these when installing
 -> Installing jetbrains-toolbox will remove: pycharm-professional (pycharm-community)

[Repo: 1]  jetbrains-toolbox-2:1.9.3935-1
[Aur: 10]  clion-1:2018.2-2 (clion-jre clion-gdb clion-cmake clion-lldb)  goland-2018.2-1 (goland-jre goland)  intellij-idea-ultimate-edition-2018.2-1 (intellij-idea-ultimate-edition-jre)  lutris-0.4.18.1-2  phpstorm-2018.2-1 (phpstorm-jre)  superlu-5.2.1-4

  6 clion (clion-jre clion-gdb clion-cmake clion-lldb) (Installed) (Build Files Exist)
  5 goland (goland-jre goland)       (Installed)
  4 intellij-idea-ultimate-edition (intellij-idea-ultimate-edition-jre) (Installed) (Build Files Exist)
  3 lutris                           (Installed) (Build Files Exist)
  2 phpstorm (phpstorm-jre)          (Installed)
  1 superlu                          (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: Downloading PKGBUILD (1/6): clion (clion-jre clion-gdb clion-cmake clion-lldb)
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 2), reused 2 (delta 0)
Unpacking objects: 100% (4/4), done.
From https://aur.archlinux.org/clion
   88c7e12..30bf58e  master     -> origin/master
:: Downloading PKGBUILD (2/6): goland (goland-jre goland)
Cloning into 'goland'...
remote: Enumerating objects: 76, done.
remote: Counting objects: 100% (76/76), done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 76 (delta 30), reused 60 (delta 18)
Unpacking objects: 100% (76/76), done.
:: Downloading PKGBUILD (3/6): intellij-idea-ultimate-edition (intellij-idea-ultimate-edition-jre)
:: Downloading PKGBUILD (4/6): lutris
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 11 (delta 5), reused 0 (delta 0)
Unpacking objects: 100% (11/11), done.
From https://aur.archlinux.org/lutris
   2b430ec..d755d8f  master     -> origin/master
:: Downloading PKGBUILD (5/6): phpstorm (phpstorm-jre)
Cloning into 'phpstorm'...
remote: Enumerating objects: 244, done.
remote: Counting objects: 100% (244/244), done.
remote: Compressing objects: 100% (179/179), done.
remote: Total 244 (delta 92), reused 210 (delta 65)
Receiving objects: 100% (244/244), 69.16 KiB | 590.00 KiB/s, done.
Resolving deltas: 100% (92/92), done.
:: Downloading PKGBUILD (6/6): superlu
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 2), reused 2 (delta 0)
Unpacking objects: 100% (4/4), done.
From https://aur.archlinux.org/superlu
   9aaba4c..ed2bec4  master     -> origin/master
  6 clion (clion-jre clion-gdb clion-cmake clion-lldb) (Installed) (Build Files Exist)
  5 goland (goland-jre goland)       (Installed) (Build Files Exist)
  4 intellij-idea-ultimate-edition (intellij-idea-ultimate-edition-jre) (Installed) (Build Files Exist)
  3 lutris                           (Installed) (Build Files Exist)
  2 phpstorm (phpstorm-jre)          (Installed) (Build Files Exist)
  1 superlu                          (Installed) (Build Files Exist)
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> Diffs to show?
==> 
HEAD is now at 88c7e12 Update to 2018.2
Updating 88c7e12..30bf58e
Fast-forward
 .SRCINFO | 5 +++--
 PKGBUILD | 3 ++-
 2 files changed, 5 insertions(+), 3 deletions(-)
HEAD is now at 95ac0de update to 2018.2
Already up to date.
HEAD is now at 60c9f0a [intellij-idea-ultimate-edition] Update to 2018.2
Already up to date.
HEAD is now at 2b430ec Version bump: 0.4.18-1
Updating 2b430ec..d755d8f
Fast-forward
 .SRCINFO | 12 ++++++++----
 PKGBUILD |  8 ++++----
 2 files changed, 12 insertions(+), 8 deletions(-)
HEAD is now at 8c636a8 update to 2018.2
Already up to date.
HEAD is now at 9aaba4c Fixed merge conflict.
Updating 9aaba4c..ed2bec4
Fast-forward
 .SRCINFO | 4 +---
 PKGBUILD | 4 ++--
 2 files changed, 3 insertions(+), 5 deletions(-)
:: Parsing SRCINFO (1/6): clion (clion-jre clion-gdb clion-cmake clion-lldb)
:: Parsing SRCINFO (2/6): goland (goland-jre goland)
:: Parsing SRCINFO (3/6): intellij-idea-ultimate-edition (intellij-idea-ultimate-edition-jre)
:: Parsing SRCINFO (4/6): lutris
:: Parsing SRCINFO (5/6): phpstorm (phpstorm-jre)
:: Parsing SRCINFO (6/6): superlu
[sudo] password for luso: 
Sorry, try again.
[sudo] password for luso: 
:: jetbrains-toolbox is in IgnorePkg/IgnoreGroup. Install anyway? [Y/n] n
warning: skipping target: jetbrains-toolbox
 there is nothing to do
==> Making package: clion 1:2018.2-2 (Út 31. červenec 2018, 17:45:37 CEST)
==> Retrieving sources...
  -> Downloading CLion-2018.2.tar.gz...
** Resuming transfer from byte position 28114944
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   154  100   154    0     0    155      0 --:--:-- --:--:-- --:--:--   155
--- [And it goes on with building and installing the desired packages, not perfect but it works and all it takes is saying no at a prompt and modifying a single line in a config file] ---
```

**Comment by Morganamilo** [comment]
Alright so looking into it a little more `pycharm-professional` conflicts with `pycharm-community` and `jetbrains-toolbox` provides `pycharm-community`. So that means the conflicts message is correct.

As to why it pulls in `jetbrains-toolbox` I'm not quite sure. Next time you do this update, if it tries to pull in `jetbrains-toolbox` again, ctrl+c out and try again, hitting the number to skip the upgrade `pycharm-professional`.

I have a feeling that might be causing it because of provides and depends like you mentioned. Looks like I'm gonna have to add the antergros repo and try this myself.

**Comment by Morganamilo** [comment]
Yeah I can reproduce this now:

```
:: Searching databases for updates...
:: Searching AUR for updates...
:: Checking development packages...
 -> Ignoring package upgrade: linux-ck (4.16.13-2 -> 4.17.11-1)
 -> Ignoring package upgrade: linux-ck-headers (4.16.13-2 -> 4.17.11-1)
 -> Ignoring package upgrade: vim-youcompleteme-git (2324.00874fab-1 -> 2373.15362d9c-1)
 -> Missing AUR Packages:  aurweb-test  diodon-bzr  gegl02  js  js38  libcloudproviders  linux-ck-zzorra  linux-ck-zzorra-headers  pcmciautils  saur-git  vte
 -> Orphaned AUR Packages:  fbgrab  libsynaptics
 -> Out Of Date AUR Packages:  downgrader  gnome-system-tools  libjson-rpc-cpp  ttf-noto
:: 4 Packages to upgrade.
4  antergos/gksu             2.0.2-6   -> 2.0.2-7
3  antergos/libgksu          2.0.12-8  -> 2.0.12-9
2  antergos/package-query    1.9-3     -> 1.9.r380-3
1  aur/pycharm-professional  000.2.0-1 -> 2018.2.0-1
==> Packages to not upgrade: (eg: 1 2 3, 1-3, ^4 or repo name)
==> ^1
:: Starting full system upgrade...
warning: chromium-widevine: local (1:4.10.1146.0-1) is newer than antergos (1:1.4.8.1000-1)
warning: copyq: local (3.5.0-1) is newer than antergos (3.3.1-1)
warning: gksu: ignoring package upgrade (2.0.2-6 => 2.0.2-7)
warning: libgksu: ignoring package upgrade (2.0.12-8 => 2.0.12-9)
warning: package-query: ignoring package upgrade (1.9-3 => 1.9.r380-3)
warning: pm2ml: local (2017.12-1) is newer than antergos (2016.8-1)
warning: powerpill: local (2018.5-1) is newer than antergos (2017-1)
:: Replace python3-memoizedb with antergos/python-memoizedb? [Y/n] 
:: Replace python3-xcgf with antergos/python-xcgf? [Y/n] 
:: Replace python3-xcpf with antergos/python-xcpf? [Y/n] 
resolving dependencies...
error: local database is inconsistent: version mismatch on package pycharm-professional
looking for conflicting packages...
:: jetbrains-toolbox and pycharm-professional are in conflict (pycharm-community). Remove pycharm-professional? [y/N] y

Package (8)                 Old Version  New Version   Net Change   Download Size

pycharm-professional        000.2.0-1                  -699.38 MiB               
antergos/python-memoizedb                2017.3.30-1      0.07 MiB       0.01 MiB
antergos/python-xcgf                     2017.3-1         0.06 MiB       0.01 MiB
antergos/python-xcpf                     2018-2           0.16 MiB       0.03 MiB
python3-memoizedb           2017.3.30-1                  -0.05 MiB               
python3-xcgf                2017.3-1                     -0.04 MiB               
python3-xcpf                2018-1                       -0.13 MiB               
antergos/jetbrains-toolbox               2:1.9.3935-1    84.25 MiB      83.14 MiB

Total Download Size:     83.19 MiB
Total Installed Size:    84.54 MiB
Net Upgrade Size:      -615.06 MiB

:: Proceed with installation? [Y/n] 
```

**Comment by Morganamilo** [comment]
I think these weird problems were actually from when I tried prefixing `reponame + "/"` for repo packages. So nothing to do with the AUR side.

**Comment by Jguer** [comment]
Worth a pre release patch?

**Comment by Morganamilo** [comment]
I think I'll just wait for a significant amount of updates to build up and if it all works well ill merge it in the next release.
