### ISSUE TITLE
Feature: Continue to update others packages if unrelated one fail

### ISSUE THREAD

**Issue by patrickelectric** [Jguer/yay#548]
sometimes, when updating with `yay`, one aur package fail breaking all update list. Is that possible to add argument to ignore such packages and all dependencies ?

**Comment by samosaara** [comment]
Oh boy, oh yes, I second this. Or better yet, just keep on going no matter what (except when a package depends on some other that has failed) and keep on to build everything and them just print some sort of status report on what has been done and what failed.

**Comment by mschulkind** [comment]
I'd even say this should be the default. Is there a benefit to immediately exiting on any failure?

**Comment by HaleTom** [comment]
I agree with continuing on to the next package by default one fails. 

At the end, the exit code could be non-zero and a warning could appear presenting all the packages which failed.

**Comment by HaleTom** [comment]
Work-around:

First run:
```
pac -aSu
```

to review the PKGBUILD diffs.

Then:

```
for pkg in $(pacman -Qmq); do
    echo y | yay -S --asdeps --noconfirm "$pkg"
done
```

`echo y` is required due to Issue #830.

**Comment by TheAifam5** [comment]
Is much worser if you have cleanup enabled. I know I can enable it again, but that's not an solution for that problem which gets me annoyed as hell. Is there any progress on that issue?

**Comment by joaoantoniocardoso** [comment]
Is this related to #848?

**Comment by Jguer** [comment]
Yes, thank you, they are, I'm going to close this one in favor of the other one as it has more details, although @HaleTom 's bash solution is pretty in a hackish way
