### ISSUE TITLE
AUR packages with edited PKGBUILDs are not installed correctly

### ISSUE THREAD

**Issue by timonegk** [Jguer/yay#549]
#### Affected Version
yay v7.887.r30.gfafaa26

#### Issue
When changing the 'provides', 'depends' or 'conflicts' sections in a PKGBUILD, the changes are not actually used during the installation process. 

For example added dependencies are not installed, removed or added conflicting packages still conflict and removed provided commands may still conflict with already installed packages.

The correct behaviour may be observed in yaourt.

#### Steps to reproduce
Example for 'conflicts':
1. yay -S [any aur package] --editmenu
2. Add coreutils (or any already installed package) to 'conflicts'
3. Observe that there is no conflict.

Example for 'depends':
1. yay -S [any aur package] --editmenu
2. Add any not installed package to 'depends'
3. The installation is aborted, no dependencies are installed.

Example for 'provides':
1. Install an aur package. Observe the conflicts stated in the PKGBUILD.
2. Install one of the conflicts. Remove the conflicting command from the 'provides' section.
3. The installation is still aborted.

**Comment by Morganamilo** [comment]
All the dependencies are resolved ahead of time. Editing the depends make those dependencies be installed. As for the other two points I can't reproduce them. Care to post the output?

**Comment by Morganamilo** [comment]
>After trying a few things, I figured out that this behaviour is only occuring when the package was previously build without editing the PKGBUILD.

Well yeah, if you don't pass `--rebuild` or up the `pkgver` then the cached version is going to be used. That's to be expected.

**Comment by timonegk** [comment]
Okay, in retrospect, that's pretty obvious. I still think that it is very confusing. Maybe it would be a solution to ask for the PKGBUILD edit before asking for rebuild and dropping the rebuild question if the PKGBUILD has been changed, because then, a rebuild is obviously wanted. But this is low priority, I guess.

Have you been able to reproduce the 'depends' problem?

**Comment by Morganamilo** [comment]
Eh whoops, I typos the first message.

All the dependencies are resolved ahead of time. Editing the depends won't make those dependencies be installed.
