### ISSUE TITLE
[Regression] Installing package groups no longer works after update.

### ISSUE THREAD

**Issue by tippl** [Jguer/yay#551]
#### Affected Version
yay v8.918

#### Issue
Changes made in the last version again did not account for package groups, making them not work.

#### Steps to reproduce
```
$ yay -S plasma
There is nothing to do
```

**Comment by Morganamilo** [comment]
Aww c'mon, not again.

**Comment by Morganamilo** [comment]
I'm eating food right now, I'm guessing this still works with `--combinedupgrade` right? I'll fix it soon.

**Comment by tippl** [comment]
Yes, that still works. :ok_hand:

**Comment by Jguer** [comment]
It's always this :laughing:
I'm going to push an update with this patch and go-srcinfo, it's been through the mills in `go test` anyway so I trust having it on release beta not to be a problem.
