### ISSUE TITLE
yay --stats not working

### ISSUE THREAD

**Issue by WANG-lp** [Jguer/yay#553]
#### Affected Version
yay v8.922.r0.gfdcc233

#### Issue
yay --stats prints nothing

#### Steps to reproduce

1. just run `yay --stats`
2. nothing outputs but the return code is 0 (via `echo $?`)

ps. `yaourt --stats` works fine

**Comment by hetraeus** [comment]
Hello, try `yay --print --stats`

**Comment by Morganamilo** [comment]
Or just `yay -Ps`.
