### ISSUE TITLE
Invokes an infinite loop when it contains some special strings that you want to search for

### ISSUE THREAD

**Issue by TheForgetTime** [Jguer/yay#555]
#### Affected Version

`yay v7.887` 
i use the version v7.887 ,but i think the error appared all version

#### Issue
Invokes an infinite loop when it contains some special strings that you want to search for

#### Steps to reproduce

e.g.
yay --query --search -icon-theme

**Comment by Morganamilo** [comment]
` -icon-theme` starts with a dash so it interprets each letter as a flag. The dash in the middle is making yay wait for data from stdin. Use `--` as an end of options separator.

**Comment by TheForgetTime** [comment]
If this program is normal, how do you end it?
Do not use Ctrl+C

**Comment by TheForgetTime** [comment]
I tried to enter some characters to end it, but this failed.

**Comment by Morganamilo** [comment]
>If this program is normal, how do you end it?

I'm not really sure what you're saying here. Yes this is pretty normal behavior. Try `grep -` or `cat -` and they will hang too.

 >Do not use Ctrl+C

If you don't want to then Ctl+D sends an EOF, but really I'd just use ctl+C

>I tried to enter some characters to end it, but this failed.

`--` is an end of options separator, reconsidered by most commands. It just means that everything after it so be taken as a target, even if it starts with a dash. You would not just add it to the end of the command.

**Comment by TheForgetTime** [comment]
pacman -
