### ISSUE TITLE
Cannot see visual version differences

### ISSUE THREAD

**Issue by sergej0** [Jguer/yay#556]
**Affected Version**
yay v8.922.r0.gfdcc233

**Issue**
When upgrading the version differences are not shown anymore visually.

**Steps to reproduce**
1. yay -Syu
```
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (1) bash-4.4.023-1

Total Installed Size:   7.15 MiB
Net Upgrade Size:      -0.02 MiB
```

**Before**
1. yay -Syu
```
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
:: Searching databases for updates...
:: Searching AUR for updates...
 -> Missing AUR Packages:  pcmciautils
:: 1 Packages to upgrade.
1  core/bash  4.4.019-1 -> 4.4.023-1
==> Packages to not upgrade: (eg: 1 2 3, 1-3, ^4 or repo name)
==> 
```

**Comment by Morganamilo** [comment]
#554

**Comment by tesfabpel** [comment]
@Morganamilo Is it possible to have it back even after 3bdb534 (without `--combinedupgrade`)?
It was a good summary of the pending changes (I don't like the pacman one at all)...
The ideal thing is to have that upstream, but I'm afraid it wouldn't be accepted since it would change every other's workflow...

Thank you.

**Comment by Morganamilo** [comment]
I don't understand whats wrong with the flag?

**Comment by tesfabpel** [comment]
> It should be noted that Yay's upgrade menu will not show repo packages
unless --combinedupgrade is used.

Why can't it be shown twice (the first time before updating repo packages and the second time for AUR)?

**Comment by Morganamilo** [comment]
The native pacman criteria requires -Syu not to be split. Before -y new updates not not be checked and after -u the updates have already been applied. So it is only possible to show AUR updates.

combined upgrade works by doing `-y -> show upgrade menu -> -u`

Also note the man page:

```
--save
           Causes the following options to be saved back to the config file.
           This provides an easy way to change config options without
           directly editing the file.
```

**Comment by tesfabpel** [comment]
Ok thank you.
I will change the config file to include the combinedupgrade option since the summary screen is too important for me to have...

**Comment by Morganamilo** [comment]
Also in case you don't know, pacman has an option called `VerbosePkgLists` which kind of does the same thing, just not as pretty.

**Comment by AladW** [comment]
>The native pacman criteria requires -Syu not to be split. 

I wonder if I remove the native pacman criteria again (like I proposed on the wiki discussion page), if everyone will go back to -Sy... I guess there's only one way to find out.

**Comment by polygamma** [comment]
@AladW - I am not planning to do that :)

**Comment by Morganamilo** [comment]
Well I'm taking the criteria as good practice. So if you removed it I would take that as splitting is no longer a bad thing. That being said, I've already put effort into this so I'm not just going to revert it back.

**Comment by AladW** [comment]
Got it. The best practice is not wrapping it at all, but if you do, at least there's some basic guidelines to follow I guess. Not sure how this is best reflected in the table

**Comment by polygamma** [comment]
I think the table really could never be able to represent the whole complexity and thoughts the AUR helper developers have put into all of this...

**Comment by AladW** [comment]
Maybe I'll just color "Yes" in the Native pacman column pink and call it a day. :wink:

**Comment by AladW** [comment]
Update: https://wiki.archlinux.org/index.php?title=Talk%3AAUR_helpers&type=revision&diff=530655&oldid=530652
