### ISSUE TITLE
"Enter packages you don't want to upgrade" never shows

### ISSUE THREAD

**Issue by nivaca** [Jguer/yay#56]
Hi,
I've been testing Yay with great results. However, I never get the "Enter packages you do not want to upgrade" question when I call `yay -Syu` (as in [this image](https://camo.githubusercontent.com/18b7be3dbbbb3a56e71f34f07e25ce2b575a53c3/687474703a2f2f6a677565722e6769746875622e696f2f7961792f796179757067726164652e706e67) ).

Am I doing something wrong?

**Comment by Jguer** [comment]
Hi,
Packages you do not want to upgrade is only available on the master branch since development package support hasn't been backported yet.
This version is available as a pre-release if you edit the PKGbuild from
```
pkgver=2.152
md5sums=('e95e870ddd2232953967eb56ee4097d1')
```
to
```
pkgver=2.188
md5sums=('SKIP')
```
