### ISSUE TITLE
Feature request: allow setting PKGDEST makepkg's variable for yay's usage only

### ISSUE THREAD

**Issue by TomaszGasior** [Jguer/yay#560]
Continuation of https://github.com/Jguer/yay/issues/477

Just allow setting makepkg's PKGDEST variable inside yay's configuration. This way will be possible to have different PKGDEST for makepkg generally and separate only for yay's usage of makepkg.
For me, it will be very helpful. I am often building my own AUR packages using makepkg directly and in these cases, I expect package file next to PKGBUILD.

**Comment by Morganamilo** [comment]
Having a makepkg config is probably what will get done. You can set PKGDEST and whatever else there.

**Comment by Morganamilo** [comment]
Actually thinking about it you could just use `--mflags` to set the config.

**Comment by TomaszGasior** [comment]
No, because yay's `--mflags` switch used while installation completely overrides setting from yay's configuration. For example. This is my yay's settings file:
```
{
	"sortby": "votes",
	"requestsplitn": 100,
	"combinedupgrade": true,
	"sudoloop": true,
	"mflags": "PKGDEST=/home/tomasz/test",
	"cleanAfter": false,
	"gitclone": false
}
```
Then I am using yay standard way. But then when I will encounter problems with wrong checksums and when I will want to add `--skipchecksum` to makepkg, I will do:
`yay markdown_previewer --mflags --skipchecksum`
and in this case "mflags" value from yay's config file is not used. Because of this inconvenience I think setting PKGDIST should be implemented as separate setting.

**Comment by Morganamilo** [comment]
Sure that's a good point.
