### ISSUE TITLE
Feature request: upgrademenu — divide list into "software upgrade" and "package upgrade"

### ISSUE THREAD

**Issue by TomaszGasior** [Jguer/yay#561]
#### Affected Version
yay v8.922

#### Issue

Currently, when `yay -Syu` is invoked (when both `combinedupgrade` and `upgrademenu` are enabled) application shows merged list of repo and AUR packages which needs an upgrade. 

Yaourt has a nice feature. Its upgrade list is visually divided into two groups: "software updates" and "package updates". Packages in the second group have an only PKGBUILD update.

Please see a comparison on the screenshot: https://i.imgur.com/3CfcyED.png

Please introduce similar behavior in yay. It will be helpful while reading long update list.

#### Steps to reproduce

**Comment by Morganamilo** [comment]
I'm not interested in this behaviour I'm afraid. We already colour the version to show how big a version change is.

**Comment by TomaszGasior** [comment]
It seems to me yaourt's separate sections are more readable than colored version numbers…
