### ISSUE TITLE
Yay does not respect 'ignore' list set in pacman.conf

### ISSUE THREAD

**Issue by Taijian** [Jguer/yay#57]
Yay should parse and respect 'ignore' lists in pacman.conf - users put those package names in there for a reason, so yay should not try to update something that the user clearly does not want to have updated.

**Comment by Jguer** [comment]
Regression introduced from changing update methods. I'll implement the fix now.

**Comment by Jguer** [comment]
Should be fixed, didn't go through proper testing since I realized only AUR ignore list was missing.

**Comment by maximbaz** [comment]
@Jguer what was the reason for not printing new versions in the warnings? I found that very useful, and now I miss it being removed in 8fa7c40... 

For example, right now I know that `mesa-17.2.2` is broken, so I'm waiting until the next version is released before removing it from the `ignore` list.

Previously every time I did other operations with yay, I could immediately check if mesa is ready to be unignored or not:

![image](https://user-images.githubusercontent.com/1177900/31762666-339c9ea0-b4bc-11e7-912e-195061fb17b5.png)

> the currently available one is still 17.2.2, so keep it in the `ignored` list

The new version of `yay` doesn't tell me this valuable information:

![image](https://user-images.githubusercontent.com/1177900/31762756-824d1408-b4bc-11e7-918e-7ff13b680676.png)

**Comment by Jguer** [comment]
I also liked it better when it showed the new version as well. It made the function more generic without it but I think I'll re-add it.
