### ISSUE TITLE
Feature request: update package without actually compiling and installing the new version (i.e. skip upgrade this time)

### ISSUE THREAD

**Issue by maximbaz** [Jguer/yay#58]
Imagine the following: you upgrade a certain package to a version `X` and discover that it has a nasty bug. You report the issue on the corresponding bug tracker and install the previous version `X-1` of the package, waiting for the bug to be fixed. If you do nothing, you keep seeing `yay` suggesting you to upgrade from `X-1  ->  X`. 

Now, you don't want to see suggestions to upgrade `X-1  ->  X`, so you add the package to the `ignore` list in pacman, and `yay` doesn't attempt to upgrade it anymore, instead it prints a shiny message `warning: PKG (ignored pkg) ignoring upgrade (X-1  ->  X)`. 

But this makes user responsible to remember to "unignore" it once a new version is released - this is annoying to manually look after this message becoming `... (X-1  ->  X+1)` one day. 

What I would like to see is some kind of `ignore` config in the Yay itself, that will allow me to specify the version `X` that I don't want to upgrade to. Once there is a version `X+1` available, I want `yay` to automatically detect this and make it very visible, that this package has a new `X+1` version and I should try to upgrade to it to see if the bug is fixed.

This is obviously open for discussion, maybe you have a different approach to handle such cases?

**Comment by Jguer** [comment]
For example in the package selection menu, `yay linux header`,  you can already write down this in the numbers line, `Numbers: 13 14 --noconfirm`. 

Maybe for the packages upgrade when it asks you what packages you don't want to upgrade you could write: `Numbers: 2 --version 3` which would make yay ignore package number 2 for that version and package 3 only that time. I think it wouldn't be very computationally expensive and wouldn't add another layer of prompts and flags. Open to ideas.

**Comment by maximbaz** [comment]
I learned that `aurutils` is a helper that allows "updating without actually installing the update". It does it by using a local repository, but nevertheless that got me thinking, maybe a simpler and more generic way would be some kind of way to tell `yay` to "assume" that new version is installed?

How that would work: I have `mesa-17.1.8` installed, I run `yay -Syu` and see that there is `mesa-17.2.2.`. I don't want to install it as it has a bug. So I run something like `yay --assume -S mesa`, which will make `yay` _think_ that I have `mesa-17.2.2` installed, even though in reality I did not install it and I still have `mesa-17.1.8`. That way, I will not get prompts to upgrade `mesa` until `mesa-17.3` is released.

How else this could be useful: imagine you have installed `package-1.0.0-1` installed, and then a new update comes `package-1.0.0-2`. You look at PKGBUILD and decide that there is nothing essentially worth upgrading, so you don't want to spend time compiling and installing, instead you just say `yay --assume -S package`, and `yay` will think that you installed `package-1.0.0-2` and will stop suggesting to upgrade this package until the next version is released.

**Comment by AladW** [comment]
How do you handle the case when an "assumed" package A provides a soname bump? If you later build a package B that links against A, it would link against the old version (as it's the one installed). Should you proceed to update A, B would break unexpectedly (requiring a second build to restore functionality)

So in the end you've done a partial upgrade, since most AUR packages are similar to repo packages in the sense they contain little to no versioning information for their dependencies.

**Comment by maximbaz** [comment]
This is completely true, but I don't think `yay` should handle it in any way, just like `pacman` is not doing it - it is a user's responsibility, if they ignore (with pacman) or assume installed (with yay) a certain package, they must have done it for a very good reason and understanding the risks.
