### ISSUE TITLE
(Build) Dependencies are being parsed before editing the PKGBUILD

### ISSUE THREAD

**Issue by muesli** [Jguer/yay#586]
#### Affected Version
yay v8.922

#### Issue
Dependencies are being installed, even though I've modified the PKGBUILD

#### Steps to reproduce
1. Install a package from AUR, e.g.: yay -S foobar-git
2. Edit the PKGBUILD and remove unwanted dependencies from the PKGBUILD
3. yay will still try to install the dependencies it parsed before I've edited the PKGBUILD's dependencies

**Comment by Morganamilo** [comment]
We do not support this. Read the readme.

**Comment by muesli** [comment]
In that case, why not remove the feature to _edit_ (not view, mind you) PKGBUILDs altogether? This just leads to false assumptions and might confuse users.

I'm sorry for not catching this in the README, but I've been using yay for so long and I usually tend to only read the README before I install something for the first time.

**Comment by polygamma** [comment]
> In that case, why not remove the feature to edit (not view, mind you) PKGBUILDs altogether? This just leads to false assumptions and might confuse users.

That makes no sense. The point of editing the PKGBUILD and other install files is in 99% not to alter the dependencies, but to change other things, e.g. checksums.

> I'm sorry for not catching this in the README, but I've been using yay for so long and I usually tend to only read the README before I install something for the first time.

Maybe you should change such behavior, if you are going to open issues on GitHub?

**Comment by Morganamilo** [comment]
>In that case, why not remove the feature to edit (not view, mind you) PKGBUILDs altogether? This just leads to false assumptions and might confuse users.

Yes edit is basically a glorified view. But I don't want to take away the freedom to edit pkgbuilds, it comes in handy some times

>I'm sorry for not catching this in the README, but I've been using yay for so long and I usually tend to only read the README before I install something for the first time.

That warning is in the man page too ;)

**Comment by muesli** [comment]
> That makes no sense. The point of editing the PKGBUILD and other install files is in 99% not to alter the dependencies, but to change other things, e.g. checksums.

It may be for some (or even most) users, but being given the opportunity to edit the entire PKGBUILD, as a user I would expect all my changes to be taken into account, and not just a sub-set of them. Even though I have now read the README, I'm still not entirely sure if this only affects dependency changes or other values, too?

> Maybe you should change such behavior, if you are going to open issues on GitHub?

Would I have doubted the desired / designed behavior, I certainly would have checked the FAQ and more existing issues before opening a new ticket. In this case I assumed it's an obvious issue that needs be reported - my bad.

Fwiw, I don't think discouraging users and potential contributors from reporting issues (even if they are just perceived ones) is a healthy attitude to open source.

**Comment by polygamma** [comment]
> It may be for some (or even most) users, but being given the opportunity to edit the entire PKGBUILD, as a user I would expect all my changes to be taken into account, and not just a sub-set of them. Even though I have now read the README, I'm still not entirely sure if this only affects dependency changes or other values, too?

Which other values could it possibly affect, too?

> Fwiw, I don't think discouraging users and potential contributors from reporting issues (even if they are just perceived ones) is a healthy attitude to open source.

It's discouraging to point out, that one should read the README before opening issues?
