### ISSUE TITLE
Devel update is broken when package is removed from the AUR

### ISSUE THREAD

**Issue by Morganamilo** [Jguer/yay#604]
#### Affected Version
yay v8.922.r74.g892d9cc - libalpm v11.0.1

#### Issue
If there is devel package installed that is then removed from the AUR. Yay will still attempt to update the package when a new commit happens, leading to a target not found error.

Devel updates should also check if the package exists on the AUR and remove them from vcs.json otherwise.

**Comment by Jguer** [comment]
Always those little specific bugs, you on it?

**Comment by Morganamilo** [comment]
I was going to do it next release because I don't really want any more commits going in this release. But eh I changed my mind and bug fixes are justifiable.
