### ISSUE TITLE
Where did the selection before an upgrade go?

### ISSUE THREAD

**Issue by Trollwut** [Jguer/yay#606]
#### Affected Version
yay v8.922

#### Issue
When upgrading (`yay -Syu`), it showed a list of possible upgrade and to enter numbers of which packages should not be upgraded. Now when I do it, it just lists the upgrades and wants a confirmation to continue - no packages to select.

Where did the selection go? That was my most beloved function. :C

#### Steps to reproduce

1. Run via `yay` or `yay -Syu`
2. …
3. Be sad.

**Comment by Morganamilo** [comment]
Read the FAQ

**Comment by Trollwut** [comment]
Thanks, wasn't abvious for me via the patchnotes

Solved there
