### ISSUE TITLE
Feature: -Sc should also clean old versions of installed package

### ISSUE THREAD

**Issue by bitwave** [Jguer/yay#607]
#### Affected Version

yay v8.922
#### Issue
-Sc flag does not clean old xz and source files of installed packages
#### Steps to reproduce

1. Install foobar
2. Update foobar multiple times
3. run yay -Sc
4. Expected result: all versions excluding the current one are pruned from the cache
5. Real behavior: only prunes the uninstalled packages and prunes untracked files

**Comment by Morganamilo** [comment]
yay -Sc Is mostly for cleaning away the build files in the cache, if you store your packages there it will end up removing them too. For more advanced package cleaning you want `paccache`. It already does this and more.

**Comment by bitwave** [comment]
I did not meant the pacman cache. I meant the package files (*.tar.xz), which are left inside the ~/.cache/yay directory after updating AUR packages.

**Comment by bitwave** [comment]
One example is the signal-desktop-bin package.
My .cache/yay/signal-desktop-bin dir looks like this:

```
PKGBUILD
signal-desktop*
signal-desktop_1.10.0_amd64.deb
signal-desktop_1.10.1_amd64.deb
signal-desktop_1.11.0_amd64.deb
signal-desktop_1.12.0_amd64.deb
signal-desktop_1.12.1_amd64.deb
signal-desktop_1.13.0_amd64.deb
signal-desktop_1.14.1_amd64.deb
signal-desktop_1.14.2_amd64.deb
signal-desktop_1.14.3_amd64.deb
signal-desktop_1.14.4_amd64.deb
signal-desktop_1.7.0_amd64.deb
signal-desktop_1.7.1_amd64.deb
signal-desktop_1.8.0_amd64.deb
signal-desktop_1.9.0_amd64.deb
signal-desktop-bin-1.10.0-1-x86_64.pkg.tar.xz
signal-desktop-bin-1.10.1-1-x86_64.pkg.tar.xz
signal-desktop-bin-1.11.0-1-x86_64.pkg.tar.xz
signal-desktop-bin-1.12.0-1-x86_64.pkg.tar.xz
signal-desktop-bin-1.12.1-1-x86_64.pkg.tar.xz
signal-desktop-bin-1.13.0-1-x86_64.pkg.tar.xz
signal-desktop-bin-1.14.1-1-x86_64.pkg.tar.xz
signal-desktop-bin-1.14.2-1-x86_64.pkg.tar.xz
signal-desktop-bin-1.14.3-1-x86_64.pkg.tar.xz
signal-desktop-bin-1.14.4-1-x86_64.pkg.tar.xz
signal-desktop-bin-1.7.0-1-x86_64.pkg.tar.xz
signal-desktop-bin-1.7.1-1-x86_64.pkg.tar.xz
signal-desktop-bin-1.8.0-1-x86_64.pkg.tar.xz
signal-desktop-bin-1.9.0-2-x86_64.pkg.tar.xz
```

current installed is 1.14.4-1. All the old xz files could be deleted by yay -Sc

**Comment by Morganamilo** [comment]
Yes and `paccache` is the tool you want. I'm not duplicating an already exiting tool that works great and it already in the repos. You'll also want to set PKGDEST to get all the packages in one place.
