### ISSUE TITLE
Several errors in manpage

### ISSUE THREAD

**Issue by simonbcn** [Jguer/yay#608]
#### Affected Version
yay v8.998 - libalpm v11.0.1

#### Issue
```
--noshowdiffs
   Show diffs for build files. Files will be opened by the editor.
```
I suppose that `noshowdiffs` doesn't show the diffs (_it needs be fixed_) and `Files will be opened by the editor.` means that it will open all `PKGBUILD` and `SRCINFO` files in the editor?

```
--afterclean
   Remove package sources after successful Install.
--noafterclean
   Do not remove package sources after successful Install.
```
There is a mismatch with real name config setting `cleanAfter`

```
--pgpfetch
   Prompt to import unknown PGP keys from the validpgpkeys field of each PKGBUILD.
--pgpfetch
   Do not prompt to import unknown PGP keys. This is likley to cause a build failiure unless using options such as --skippgpcheck or a customized gpg config.
```
I suppose that the second setting is `--nopgpfetch`.

**Comment by Morganamilo** [comment]
You say your version is `yay v8.998 - libalpm v11.0.1`, although that does not look like the man page for that version.

**Comment by Jguer** [comment]
I'm in `yay v8.998 - libalpm v11.0.1` no devel and it doesn't show me `--noshowdiffs` so something funky seems to be happening with your manpage @simonbcn

**Comment by simonbcn** [comment]
ok, I had just installed the new version so I guess man showed me the one it had in cache.

**Comment by Morganamilo** [comment]
I just noticed the json hint is actually `cleanAfter` with the capital, which is quite annoying because fixing it would reset the setting to default for everyone.
