### ISSUE TITLE
Upgrade failes when Pkgrel is floating point

### ISSUE THREAD

**Issue by MarcelBochtler** [Jguer/yay#61]
In Manjaro Linux the latest wpa_supplicant update was from version 1:2.6-8.1 to 1:2.6-11.
This caused a problem because in mikkeloscar's gopkgbuild this was not allowed resulting in this 
```
wpa_supplicant strconv.Atoi: parsing "8.1": invalid syntax
0  core/wpa_supplicant                          panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x63ceaa]

goroutine 1 [running]:
main.upSlice.Print(0xc4201c8000, 0x1, 0x1, 0x0)
        /home/jguer/go/src/github.com/jguer/yay/upgrade.go:82 +0x49a
main.upgradePkgs(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/jguer/go/src/github.com/jguer/yay/upgrade.go:292 +0x1de
main.main()
        /home/jguer/go/src/github.com/jguer/yay/cmd.go:245 +0x898
```

I addressed this issue [with mikkeloscar](https://github.com/mikkeloscar/gopkgbuild/pull/2) and he fixed it by using a Version struct instead of an int for pkgrel in [this PR](https://github.com/mikkeloscar/gopkgbuild/pull/3).

This requires a small adjustment in yay for printing it correctly.

**Comment by Jguer** [comment]
Not the first time Manjaro displays this kind of fun quirks.
Mikkeloscar's fixed still isn't merged to master, he should merge it soon enough I hope and as soon as he does I'll pull it.

**Comment by mikkeloscar** [comment]
Merged! :)

**Comment by Jguer** [comment]
@MarcelBochtler Can you check if this commit fixes your problem. In theory that's all that was needed.

**Comment by MarcelBochtler** [comment]
@Jguer Yes, that fixes my problem, but requires a small change in yay. I'll create a pull request.

**Comment by MarcelBochtler** [comment]
Tested it. It works.
