### ISSUE TITLE
Completion stuck for a long time if no prefix of pkg name

### ISSUE THREAD

**Issue by ffffwh** [Jguer/yay#616]
#### Affected Version

- yay version: yay v8.998 - libalpm v11.0.1
- my shell is `bash`

#### Issue
Pressing TAB twice after `yay_-S_` (where _ = space) cause a long not responding time.
TAB after any letter (e.g. `yay_-S_g`) can respond in resonable time.

I tend to press TAB a lot (since completion makes no harm). It is not a good experience that an extra TAB make things stuck.

If this is due to large data to download (60000+ possibilities), it might be better to disable completion when there is no leading letter.

My network condition
```
$ ping aur.archlinux.org
PING aur.archlinux.org (5.9.250.164): 56 data bytes
64 bytes from 5.9.250.164: icmp_seq=0 ttl=46 time=375.987 ms
```

**Comment by Morganamilo** [comment]
Maybe it's time for a better shell ;)

```
morganamilo@Octavia ~ % yay -S 
zsh: do you wish to see all 61405 possibilities (61405 lines)? 
```

In all seriousness, you have a good point, and I wouldn't mind the change.

This is not because of network though, all of it is cached.

**Comment by Jguer** [comment]
This is a bash exclusive problem. I tested all shells on completion speed and it ranges from almost instant (fish), depends on weather instant (zsh) and no concept of speed in infinity waiting time (bash). I think bash simply wasn't made with this type of completion in mind. That's a very good suggestion though

**Comment by Morganamilo** [comment]
>That's a very good suggestion though

Yep only problem is I have no idea how to implement it.

**Comment by Jguer** [comment]
Yes I know how to implement it on fish, but not on bash, a bash expert would be nice

**Comment by Modelmat** [comment]
This is still an issue, why has this been closed?
also happens when you hit space twice, it finishes auto completion then it adds a space.

**Comment by parkerlreed** [comment]
Hmm it's not even tabbing space for me

```
[parker@e55 memloader]$ yay -S 
build/        .git/         .gitignore    LICENSE       linker.ld     linker.specs  Makefile      out/          README.md     src/          tools/        .vscode/     
```

I have to enter at least one character for the tab completion to pick up (bash)

**Comment by Morganamilo** [comment]
See https://github.com/Jguer/yay/pull/625. If you have a solution for the file autocompletion I'd be happy to hear it.

**Comment by Morganamilo** [comment]
@Modelmat Version? And what exactly is wrong, is it the same issue as OP or a new one?

**Comment by parkerlreed** [comment]
@Morganamilo Honestly I'm fine with that. I like it not getting stuck if I forgot to start typing something.

**Comment by Modelmat** [comment]
@Morganamilo It's the latest version from git. It's not exactly the same issue, but I still get the OP's issue I was just pointing out another part where this occurs.
