### ISSUE TITLE
yay fails when trying to install AUR package

### ISSUE THREAD

**Issue by LaserEyess** [Jguer/yay#621]
#### Affected Version
```
yay -V
yay v8.998.r23.g6515a9b - libalpm v11.0.1
```

#### Issue
As the title says, I get the following when trying to do `yay -S rofi-pass`

```
yay -S rofi-pass
panic: runtime error: index out of range

goroutine 1 [running]:
main.splitDep(0xc42026ebe5, 0x1, 0x7ffdae8decd4, 0x9, 0x0, 0x0, 0x0, 0x0)
	/tmp/makepkg/yay-git/src/yay/dep.go:60 +0x100
main.provideSatisfies(0xc42026ebe5, 0x1, 0x7ffdae8decd4, 0x9, 0x7ffdae8decd4)
	/tmp/makepkg/yay-git/src/yay/dep.go:75 +0xaa
main.(*depPool).findSatisfierAurCache(0xc4204b2000, 0x7ffdae8decd4, 0x9, 0x9)
	/tmp/makepkg/yay-git/src/yay/depPool.go:423 +0x63a
main.(*depPool).resolveAURPackages(0xc4204b2000, 0xc4200550c0, 0x1, 0x0, 0x1)
	/tmp/makepkg/yay-git/src/yay/depPool.go:282 +0x204
main.(*depPool).ResolveTargets(0xc4204b2000, 0xc420486660, 0x1, 0x1, 0x0, 0xc420089050)
	/tmp/makepkg/yay-git/src/yay/depPool.go:157 +0xc7b
main.getDepPool(0xc420486660, 0x1, 0x1, 0xc42009e550, 0x0, 0x0, 0xc4200ba000)
	/tmp/makepkg/yay-git/src/yay/depPool.go:362 +0x7e
main.install(0xc4200a01c0, 0xc420055d38, 0x2)
	/tmp/makepkg/yay-git/src/yay/install.go:113 +0x476
main.handleSync(0xc42009a458, 0x1)
	/tmp/makepkg/yay-git/src/yay/cmd.go:273 +0x472
main.handleCmd(0x0, 0x0)
	/tmp/makepkg/yay-git/src/yay/cmd.go:152 +0x32c
main.main()
	/tmp/makepkg/yay-git/src/yay/main.go:239 +0x2b3
```
#### Steps to reproduce
`yay -S rofi-pass`

I had someone else try this and he got the same error, so it's probably not something local to my machine. Also downloading the `rofi-pass` PKGBUILD and doing `makepkg -srci` works so the PKGBUILD doesn't appear to be broken. It doesn't seem limited to `rofi-pass` either, the -git version also fails. As does `rofi-git`. I don't really get it but yay seems to hate rofi. 

To be clear: it's not just stuff named rofi that's failing, for example `dmenu-git` produces the same error.

**Comment by Morganamilo** [comment]
Well done, I have not seen Yay panic in a long time, quite the bug you found :)

Turns out it's https://aur.archlinux.org/packages/menu-calc-git/ causing the problem. It provides `=` and our versioned dep spliter (e.g. `foo=1`) panics on it. I'll be around to fix it later.

menu-calc-git is not a dependency but pulled in as a potential provider. So you can actually successfully install using `yay -S rofi-pass --noprovides`.

**Comment by LaserEyess** [comment]
Aha I just saw the edits in the git log. So basically because rofi was listed as an optional dependency it parsed the provides? Still not quite sure how that works but I am not too familiar with the innermost workings of how dependencies and such are resolved. 

[Also you were not kidding about this package](  https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=menu-calc-git&id=6933d194c5b49355e1fa04e972bc4c6d7f9d7adf)

**Comment by Morganamilo** [comment]
This explains it, kinda a hack but I like it.

https://github.com/Jguer/yay/blob/6515a9bf04b86bad361743185a60717a4aa0d4ba/depPool.go#L163-L175

Also `isntall -Dm755 "=" ${pkgdir}/usr/bin` means place `=` in `/usr` and rename it to `bin` :/

**Comment by Jguer** [comment]
That's a pretty impressive bug I would say. Nice find
