### ISSUE TITLE
Cannot use yay after renaming the username

### ISSUE THREAD

**Issue by Borderliner** [Jguer/yay#627]
#### Affected Version
All

#### Issue
Cannot use `yay` after renaming my user, even after removing it, I recompiled and installed it again, but it fails to run, throwing the following error:
```
$ yay -V
Unable to create BuildDir directory:
/home/[old_username]/.cache/yay
The error was:
mkdir /home/[old_username]: permission denied
```
#### Steps to reproduce
1. sudo usermod -l newUsername oldUsername
2. sudo usermod -d /home/newHomeDir -m newUsername
3. yay -V

I can confirm that I have a home directory with the new username, and the old one is removed completely. Please fix this, thank you.

**Comment by Jguer** [comment]
What is the output of `yay -Pg`?

**Comment by Morganamilo** [comment]
Build dir is usually `/home/user/.cache/yay/`. I don't I need to see the output to guess that this is the problem.

```
yay --builddir $home/.cache/yay --save
```

Will fix it.

This is just a downside of the config system. A better way would be to have builddir to stay as an empty string in the config and have that imply the default. In the same way that makepkgconf stays as an empty string, implying the default.

**Comment by Morganamilo** [comment]
Also for my command I think stuff happens in a weird order, so yay bails out before the --builddir can take effect. You may have to manually edit the config file `~/.config/yay/config.json`.

**Comment by Borderliner** [comment]
@Morganamilo Awesome! Manually changing the path from `~/.config/yay/config.json` fixed this. It would be great if yay could update this path automatically. Thank you.
