### ISSUE TITLE
<package>-git  packages (devel packages) do not get updated with '--devel'

### ISSUE THREAD

**Issue by c0d3z3r0** [Jguer/yay#631]
#### Affected Version
yay v8.998.r35.g639b061 - libalpm v11.0.1

#### Issue
\<package\>-git  packages (devel packages) do not get updated with --devel, for example binwalk-git

Check current and remote version:

~~~
[c0d3@z3r0 ~]$ yay -Ss binwalk-git
aur/binwalk-git 2.1.2b.795.441e2d1-1 (+8 0.00%) (Installed: 1035.f636501.-1)
    A tool for searching a given binary image for embedded files
~~~

Try to update packages:

~~~
[c0d3@z3r0 ~]$ yay -Syu --devel --needed
:: Synchronizing package databases...
 testing is up to date
 core is up to date
 extra is up to date
 community-testing is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
warning: i3lock: ignoring package upgrade (git-1 => 2.10-1)
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
 -> i3lock: ignoring package upgrade (git-1 => 2.10-1)
:: Checking development packages...
warning: redirecting to https://gitlab.gnome.org/GNOME/vala.git/
 -> proxmark3: local (r2128.577b1c27-1) is newer than AUR (r1382.2c79288-1)
 -> proxmark3-flasher: local (r2128.577b1c27-1) is newer than AUR (r1688.bb4e6db-1)
 -> pyside-tools-common: local (0.2.15-4) is newer than AUR (0.2.15-2)
 -> python-pyside-tools: local (0.2.15-4) is newer than AUR (0.2.15-2)
 -> python2-pyside-tools: local (0.2.15-4) is newer than AUR (0.2.15-2)
 -> Missing AUR Packages:  ftw  linux-c0  linux-c0-api-headers  linux-c0-docs  linux-c0-headers  yay-c0
 -> Out Of Date AUR Packages:  intel-opencl  proxmark3  python-pylibftdi  python-pyotp  teensyduino
:: 2 Packages to upgrade.
2  aur/devkitarm  r47-1     -> r48-1
1  aur/webkitgtk  2.4.11-11 -> 2.4.11-12
==> Packages to not upgrade: (eg: 1 2 3, 1-3, ^4 or repo name)
==> 1-2
 there is nothing to do
~~~

Update one manually by reinstall:

~~~
[c0d3@z3r0 ~]$ yay -S binwalk-git
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur: 1]  binwalk-git-2.1.2b.795.441e2d1-1

  1 binwalk-git                      (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
~~~

#### Steps to reproduce

see above

**Comment by Morganamilo** [comment]
Can you actually prove it needs an update?

**Comment by c0d3z3r0** [comment]
Yes, see first command‘s output: Commit 441e2d1 vs f636501

**Comment by Morganamilo** [comment]
If you're comparing AUR version numbers then this is not a devel issue.

```
vercmp 1035.f636501.-1 2.1.2b.795.441e2d1-1
1
```

Somebody changed the version scheme without adding an epoch, blame the maintainer.

**Comment by c0d3z3r0** [comment]
--devel should update from git if there is a new commit, right?

**Comment by Morganamilo** [comment]
Yep, "a new commit" has to compare against something though. Yay will record the current commit during a gendb or package install.

So the normal workflow is:
1. Move from another AUR helper to yay
2. Use gendb to check the git packages that yay was not used to install, after this you never need to run it again
3. Devel updates will now happen on the next new commit

**Comment by c0d3z3r0** [comment]
> Devel updates will now happen on the next new commit
Ahhh, now this all makes sense to me!
So it seems it was a very bad idea to switch from pacaur to yay before upgrading any devel packages...

**Comment by Morganamilo** [comment]
Well ideally you'd be up to date, but the way git packages work I don't see it as a big deal, a new commit will come eventually.

**Comment by Morganamilo** [comment]
And if you absolutely can't wait you can do a "pacaur style --devel"

```
pacman -Qs -- "-git$" | yay -S --needed -
```

**Comment by c0d3z3r0** [comment]
> pacman -Qs -- "-git$" | yay -S --needed -
>   1

This one worked ;)

~~~
pacman -Qsq -- "-git$" | yay -S -
~~~

**Comment by Morganamilo** [comment]
Missed a q, oh well.

Still might want to contact the maintainer about getting a better pkgver function though.

**Comment by Morganamilo** [comment]
If you're on about the last command. You could always redirect it to a file, filter out the packages you don't want and then redirect it to yay.

```
pacman -Qsq -- "-git$" > pkgs
$EDITOR pkgs
< pkgs yay -S -
```

**Comment by Morganamilo** [comment]
`--needed` Stops pacman from installing already up to date packages. For yay's `--devel` stuff, this is already filtered out. But for manually specifying every `-git` package `--needed` does help, although it would still work without the flag, just take a little longer.
