### ISSUE TITLE
Yay nous longer shows upgrade list with colorized version diff and offer to skip packages

### ISSUE THREAD

**Issue by Jubijub** [Jguer/yay#634]
#### Affected Version
Version : 8.998-1 installed this morning
Tested with Fish and Zsh

#### Issue
Invoking yay or yay -Syu no longer shows the fancy list of packages with :
- installed version vs available version
- numbered list, with the possibility to skip some packages by typing the list number

#### Steps to reproduce
1. Yay

#### actual result

- yay does query the mirrors
- yay display the standard Pacman output, ie an unformatted list of packages
- all I can do is confirm Y/n whether I want to upgrade

#### expected results

- yay would display the fancy formatted colored list

#### What I tried
- remove yay via `sudo Pacman -R yay`
- yay is no longer installed (invoking yay fails)
- remove yay git directory
- redo a clean git clone as instructed in the readme
- CD in that dir and do `makepkg -Si`
- yay is back, same issue

As I seem to be the only one complaining something must be wrong on my computer, but I don't know how to troubleshoot further

PS : it used to work on that computer with that same Arch install

**Comment by Morganamilo** [comment]
See the FAQ
https://github.com/Jguer/yay/issues/617
https://github.com/Jguer/yay/issues/606
https://github.com/Jguer/yay/issues/564
