### ISSUE TITLE
Failed to build malformatted PKGBUILD

### ISSUE THREAD

**Issue by Urgau** [Jguer/yay#635]
#### Affected Version
yay v7.885 - libalpm v11.0.1

#### Issue
Yay can't build malformatted PKGBUILD and don't tell us to change the PKGBUILD.

#### Steps to reproduce
Try to build fetchmirrors : yay -S fetchmirrors
https://aur.archlinux.org/packages/fetchmirrors

**Comment by alerque** [comment]
The AUR package is broken. It should be fixed.

Packages uploaded the AUR have two parts, a PKGBUILD and a meta data file that informs the website and the API about some values. In this case the PKGBUILD looks okay but the meta data file is bogus. It should be regenerated with `mksrcinfo` and pushed to the AUR.

Not all AUR helpers query the AUR API to find out about dependencies ahead of time, but `yay` does. Given that this package is broken in the AUR it is perfectly reasonable for it to refuse to continue operations it does not expect t be able to finish.

**Comment by Morganamilo** [comment]
Looking at the commits it looks like the maintainer has been editing the srcinfo by hand. By the way `mksrcinfo` is old and defunct. `makepkg --printsrcinfo` is what you want these days.

**Comment by Morganamilo** [comment]
>yay v7.885 - libalpm v11.0.1

You're quite behind there by the way. There have been 4 new releases since then.

**Comment by Urgau** [comment]
It's seem that it's a bug because :

**yay -V** : 

> yay v7.885 - libalpm v11.0.1

**yay -Qi yay** : 

> Version : 8.998-1

and I confirm that I have yay 8.998

**Comment by Morganamilo** [comment]
Then that's weird. Does it stay like that if you rebuild yay?

**Comment by Urgau** [comment]
Yes it the same when I rebuild. Watch [here](https://asciinema.org/a/ge8ALYZ5Ijd4umRJL29VoR0Hs).

**Comment by Urgau** [comment]
Is it possible to fix the Makefile to support gccgo ?

**Comment by Morganamilo** [comment]
You could ask @Jguer to set the version number in the code when he makes a new release. That will work for yay but not yay-git.

**Comment by Jguer** [comment]
I can start doing it for visual sake, although it could be argued that the default value of the string should be `not supported` so you know you are using a non standard setup

**Comment by alerque** [comment]
Thank you @Morganamilo for the tip about `makepkg --printsrcinfo`. I think `mksrcinfo` needs to be re-released with a deprecation notice, hundreds of us out here are obliviously still using it. I like that the new method avoids putting a date stamp in the file, that was obnoxious for version control reasons.

@Jguer I would recommend setting the value in the make file to the output of `git describe --tags`. This way build from `yay-git` would have both a semantically meaningful version + number of commits and hash of the HEAD version build, but also exact tagged releases would have the version number.
