### ISSUE TITLE
Allow to override PATH for installation

### ISSUE THREAD

**Issue by blueyed** [Jguer/yay#638]
Python packages usually use just "python", which causes issues if you use `yay` while some virtualenv is activated.

With pacaur I've added `/usr/bin` in front of $PATH to work around this (https://github.com/rmarquis/pacaur/issues/400#issuecomment-172837997), but could not find a way to make this work in yay directly.

I might use an alias/function/wrapper script if it turns out to be not feasible for `yay` to support this.

**Comment by Morganamilo** [comment]
You could probably do `yay --makepkg ~/.local/bin/python-makepkg --save` where `python-makepkg` is some wrapper that sets the path before calling makepkg.

**Comment by Jguer** [comment]
Closing on question inactivity
