### ISSUE TITLE
Add an option to clean up after AUR build

### ISSUE THREAD

**Issue by muesli** [Jguer/yay#64]
I often end up having to manually delete /tmp/yaytmp-*, because my machine keeps running for weeks and tmpfs starts filling up the RAM with AUR builds.

It would be nice to have an option/setting to automatically clean up yaytmp after successful builds.

**Comment by AladW** [comment]
Or just set the default build directory to XDG_CACHE_HOME/yay. See https://github.com/rmarquis/pacaur/issues/434 for reasoning.

**Comment by Jguer** [comment]
Closing this since after clean has been added and @AladW provides a very valid alternative.
Maybe yay should come with XDG_CACHE_HOME/yay as default build dir.
