### ISSUE TITLE
Add a background sudo loop

### ISSUE THREAD

**Issue by shaygover** [Jguer/yay#640]
#### Affected Version
v8.998

#### Description:
Add a sudo loop so when an AUR package finishes to build (a few hours later) there will be no need to re enter the root password. 

Thanks

**Comment by alerque** [comment]
Is there something wrong with the sudo loop already built in? From `man yay`:

> --sudoloop
>    Loop sudo calls in the background to prevent sudo from timing out during long builds.

**Comment by shaygover** [comment]
Oops. Except for the help, is there a wiki page that document that. I searched google and looked for a wiki or readme entry but didn't found any. I rarely use --help :/

**Comment by Morganamilo** [comment]
`man yay`

**Comment by shaygover** [comment]
I'm think I'm one of those people who hate grey on black of the console. Am I the first one to come here?

**Comment by alerque** [comment]
If your color scheme is something you hate then fix it. Terminal colors and which ones are used by which programs are almost infinitely customable. That's might be the lamest excuse for not reading the docs I've head. Seriously `man <command>` is basically the defacto place to document usage and what features are available in CLI programs. You are wasting your time looking anywhere else. Always start there first, then go somewhere else if you need more. Wikis and readmes and website documentation are second resort and supplemental. Sure some projects don't do a good job of documenting there, but it should always be where you check.

**Comment by Jguer** [comment]
https://github.com/Jguer/yay/issues/147
