### ISSUE TITLE
Flatpak integration - feature request

### ISSUE THREAD

**Issue by kaymio** [Jguer/yay#649]
#### Affected Version
All versions, but I'm on yay v8.998 - libalpm v11.0.1
#### Issue
Yet another yoghurt, not only as a pacman wrapper and AUR helper but also as a flatpak manager
#### Steps to reproduce
To make yay future proof it would be great to integrate flatpak (updates) into yay.
Up till now I've to manage flatpaks by hand on Arch. I didn't ask, but I don't think the Arch devs are willing to integrate flatpak into pacman. The next logical step would be to integrate it into the best AUR helper!

YAY!

**Comment by Morganamilo** [comment]
That sounds way out of scale. Doesn't flatpak have its own upgrade toolset?

**Comment by kaymio** [comment]
If the AUR is 'wrappable' flatpak should be too.

**Comment by Morganamilo** [comment]
AUR helpers are useful because makepkg by itself has no concept of the AUR it just deals with local pkgbuilds. Helpers expand on makepkg by adding downloading, updating, dependency resolution, ect. I would expect flatpak to provide its own tools that already cover this.

Now when it comes to GUI tools that might make a little sense as maybe flatpak does not have any GUI tools? But as a CLI tool it's hard to see what integration would add.

**Comment by kaymio** [comment]
At the moment I have to manage my flatpaks, my snaps and without an helper also manually my AUR installs beside the usual pacman upgrade and even one AppImage that updates itself when used.
It would be great to have a choice of the type of installation e.g. when installing gimp: gimp-repo, flatpak-gimp, gimp-git.
As you say, the flatpak tools do most of this already. So yay would only have to be a flatpak wrapper that opens up choices for the user and holds the 'whole' system up to date. It would also distinguish yay further from the competition.

The integration of flatpak is slowly but steady becoming the standard for software distribution. It might even mean that only windows software might finally come to Linux, what might help the Linux desktop a lot.

**Comment by AladW** [comment]
Flatpaks are for packages across Linux distributions. AUR helpers are for Arch Linux only. And no, it's not becoming the "standard" - I can assue you it will never replace pacman in Arch, for example.

**Comment by lil5** [comment]
@kaymio Please reconsider, being able to install and update flatpak packages (if flatpak is installed) would be a great asset IMO.

**Comment by noobmagnet** [comment]
Or could be triggered with another switch like `yay -Syu --flapack` so that normal upgrading can still be isolated

**Comment by grandchild** [comment]
Have you guys tried: https://github.com/Jguer/yay/issues/1798#issuecomment-1222238689 yet?

**Comment by nathanfranke** [comment]
1. Are there any noteworthy apps available in flatpak but unavailable in AUR?
2. Flatpak supports sandboxing applications, a great feature. What can AUR learn from this?
3. I can see many people preferring flatpak for security, since AUR only hosts user-created scripts.
