### ISSUE TITLE
Color display error

### ISSUE THREAD

**Issue by zhuxiaoxi** [Jguer/yay#650]
#### Affected Version
`yay v8.922`

#### Issue
highlight color display error

#### Steps to reproduce
- add Community Repository
- Search for packages included in archlinuxcn
![2018-08-22 12-58-07](https://user-images.githubusercontent.com/2098464/44443589-1a3f3080-a60b-11e8-977f-78f2a7659940.png)

**Comment by Jguer** [comment]
The color is determined through an hash of the repository name, archlinuxcn appears to be just unlucky and calculate a grey hash, it's possible to avoid it but it does it's function, it's different than other repositories

**Comment by zhuxiaoxi** [comment]
All the Community Repository cannot have the same hash, This looks more like no color.It's not gray, it's very clear when it is selected.
![2018-08-22 18-02-31](https://user-images.githubusercontent.com/2098464/44457384-a2d2c680-a635-11e8-8a0e-967d8e190e7b.png)
![2018-08-22 18-02-31](https://user-images.githubusercontent.com/2098464/44457420-ba11b400-a635-11e8-9364-ba890f4b8e99.png)

**Comment by Jguer** [comment]
#668 should fix it, it fixed on my test machine. I wouldn't consider a permanent fix, I would rather replace that hash by something faster and more standard

**Comment by Morganamilo** [comment]
A hash seems the only way to guarantee a random but consistent colour for an arbitrary repo name. What else do you have in mind?

**Comment by Jguer** [comment]
*Replace that hashing algorithm
We actually only have a very limited color pallette and we're calculating extensive hashes on top and then reducing them to 0 to 6. Maybe just grabbing the first and last letter and summing their asci would be enough.

**Comment by alerque** [comment]
If there were unlimited shades and frequently dozens of repos, the random color thing would make more sense to me. As it is I think I have to agree with @DragonAssassin that a consistent scheme that categorizes repositories would make much more sense.
