### ISSUE TITLE
ZSH completions don't handle --file

### ISSUE THREAD

**Issue by alerque** [Jguer/yay#651]
The bash completion patterns somehow handle the `--file` flag correctly, but the zsh ones do not.

The flag gets used several places where a package name would normally be expected to pass a package file name instead. An example would be querying the files in a package file that has not been installed yet via a command like `yay -Ql --file pkgname-pkgver-pkgrel-arch.pkg.tar.xz`. In bash, I can use <kbd>&lt;TAB&gt;</kbd> to complete the filename after the `--file` flag, but in zsh it refuses to match anything after that, file name or otherwise.

	❯❯❯ yay -V
	yay v8.998 - libalpm v11.0.1

	❯❯❯ ls *.xz
	sile-git-0.9.3_446_g21db1ae-1-any.pkg.tar.xz

	❯❯❯ yay -Ql --file si<TAB>
	-- no matches found --

**Comment by Morganamilo** [comment]
Pacman seems to refuse to tab complete `--file` too. Meanwhile the shorthand `-p` tries to expand to any directory. Maybe report this upstream?

**Comment by alerque** [comment]
Funny — I tried this with `pacman` before reporting it here and recall it working, hence why I started here and not upstream. I just checked again and it's not working, so either my testing was off or my memory is failing me.

**Comment by Morganamilo** [comment]
Okay so testing again. `-p` works fine. The part about it only completing directories was just because my pwd had no *.pkg.tar.gz files in it.

`--file` refuses to complete anything though.

This this the same for you?

**Comment by Morganamilo** [comment]
Looking at the source https://git.archlinux.org/pacman.git/tree/scripts/completion/zsh_completion.in#n372 it seems the switch statement only looks for short opts. So maybe this is intentional? Perhaps it was too complex to implement it for long opts too?
