### ISSUE TITLE
Exit codes differ from pacman

### ISSUE THREAD

**Issue by EvanPurkhiser** [Jguer/yay#652]
#### Affected Version
yay v8.998.r80.g0a136a3 - libalpm v11.0.1

#### Issue

Exit codes differ from pacman. I'm trying to use yay with `makepkg` by setting the `PACMAN` environment variable. But when makepkg tries to test for dependencies it just immediately fails with

```
==> ERROR: 'yay' returned a fatal error (1): <some-package>
```

#### Steps to reproduce
```
$ pacman -T invalid
invalid
$ echo $?
127
$ yay -T invalid
invalid
$ echo $?
1
```

**Comment by Morganamilo** [comment]
We are not pacman. Yay can fail internally, as can makepkg, pacman, git, ect. So returning error codes becomes a little pointless when you don't know what program the error came from.

Although for cases were yay wraps purely pacman it would make sense. Using yay in makepkg certainly is a nice idea. Unfortunately makepkg tries to run yay as root and it fails.

**Comment by EvanPurkhiser** [comment]
> Using yay in makepkg certainly is a nice idea. Unfortunately makepkg tries to run yay as root and it fails.

Realized this after opening this :)

Seems like this is probably still a valid issue.

**Comment by Jguer** [comment]
#1095 supersedes this
