### ISSUE TITLE
Yay isn't upgrading packages (PyCharm and PHPStorm)

### ISSUE THREAD

**Issue by gringo-go-go** [Jguer/yay#662]
#### Affected Version
yay v8.998 - libalpm v11.0.1

#### Issue
Yay isn't upgrading AUR packages
```
$ yay -Syu 
[sudo] password for xxxxxxx: 
:: Synchronizing package databases...
 antergos is up to date
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
:: 2 Packages to upgrade.
2  aur/phpstorm              2018.2.1-1 -> 2018.2.2-1
1  aur/pycharm-professional  2018.2.1-1 -> 2018.2.2-1
==> Packages to not upgrade: (eg: 1 2 3, 1-3, ^4 or repo name)
==> 
 there is nothing to do
```

#### Steps to reproduce

1. run `yay -Syu`
2. don't enter any package number

**Comment by Morganamilo** [comment]
Does this still happen in the git version?

**Comment by gringo-go-go** [comment]
AFAIK AUR doesn't have git version.

**Comment by Morganamilo** [comment]
I mean the git version of yay:
```
#### Affected Version
As noted here -> <!-- Please ensure you are using the latest yay-git package -->
<!-- Use `yay -V` to get installed version -->
<!-- Example: `yay v3.373` -->
```

**Comment by gringo-go-go** [comment]
Works like a charm with latest git version :)
Thank you very much!

**Comment by alerque** [comment]
If the release version is this broken and the git HEAD version is working, it might be time to cut a release! On the other hand I cannot confirm this behavior. I just tried it with the release  version installed on my system and the commands above and an outstanding AUR update ran. Does this have to do with the `combinedupdate` option that I have set in my configuration or something like that?

**Comment by Jguer** [comment]
I'm back already :innocent:, ready for a release if you are
