### ISSUE TITLE
Is it possible to install all dependencies of a package, but not the package itself?

### ISSUE THREAD

**Issue by stevenroose** [Jguer/yay#663]
Didn't find an IRC channel or discussion forum. Sorry for the question.

**Comment by Morganamilo** [comment]
You can always grab the dependencies via -Si and install with -S --asdeps. But apart from that, not really.

**Comment by stevenroose** [comment]
Hmm, there is no way to get the deps from -Si alone without the rest?

**Comment by Morganamilo** [comment]
Oh yeah silly me, didn't think about recursive dependencies. You could `yay -S pkg` and it will tell you which repo/aur make/runtime deps you need. Although this could be an x y problem. What exactly do you want to achieve? Maybe aurmansolver is what you want?

**Comment by stevenroose** [comment]
I wanted to install a different version from sources, without having to find out what all the dependencies were. The info is already there.

**Comment by Morganamilo** [comment]
Why not just edit the pkgver during the install?

**Comment by Morganamilo** [comment]
Closing because It's not something I really want to implement. This could be achieved via the `--print` flag if someone implemented it for AUR packages.

`yay -Sp pkg | filter out pkg`
