### ISSUE TITLE
Git diff package files: Exclude .SRCINFO

### ISSUE THREAD

**Issue by Edenhofer** [Jguer/yay#667]
#### Affected Version
current master at acced8c440af18104f2bff8b6362a38867aca4e6

#### Issue
Yay is capable of displaying git-diffs for package files. However, the diff can become cluttered due the `.SRCINFO` file being included. As it displays no additional information, I think it would make sense to exclude the file in the diff.
If the user is viewing the `PKGBUILD` the `.SRCINFO` file has no added value. Its existence is only justified to ease parsing but at no point will it contain anything which can not be inferred from the `PKGBUILD`. Furthermore, it has no baring on the build process what-so-ever and might for the rest of the build process not even exist.

If I am not mistaken, amending [this code block](https://github.com/Jguer/yay/blob/19bf8e773c8a269ab96aca789c43b40d6efbdb6c/download.go#L103) should do the trick. Git can easily be instructed to ignore certain files, e.g. using `git diff . ':!\.SRCINFO'`.

#### Steps to reproduce
1. Request `yay` to build an AUR package
2. View the Diff

**Comment by Morganamilo** [comment]
If you're running the git version you should have noticed this is already implemented https://github.com/Jguer/yay/issues/609. Does this not work for you?

**Comment by Edenhofer** [comment]
I am very sorry for the noise! I have not updated yay-git in a while and jumped to conclusions! Furthermore, while searching previous tickets, I happened to include the keyword 'git' and hence did not find #609.

The feature is working flawlessly after updating to the most recent yay-git version.

Sorry again!
