### ISSUE TITLE
Search 'provides' or 'replaces' fields like 'pacman -Ss'

### ISSUE THREAD

**Issue by dlintw** [Jguer/yay#671]
#### Affected Version
yay v8.998 - libalpm v11.0.1
pacman 5.1.1-1

#### Issue
`pacman -Ss firefly` will get 'opendesktop-fonts', but `yay -Ss firefly` can NOT.

**Comment by Jguer** [comment]
```
<!-- Please ensure you are using the latest yay-git package -->
<!-- Use `yay -V` to get installed version -->
<!-- Example: `yay v3.373` -->
```
`pacman -Ss firefly` will get 'opendesktop-fonts', but `yay -Ss firefly` can YES.

**Comment by Jguer** [comment]
![screenshot from 2018-08-30 08-41-06](https://user-images.githubusercontent.com/8071073/44837134-a7e4d680-ac30-11e8-8f38-725075ec22f6.png)

Just to add some more information, this should be fixed in the displayed version.
