### ISSUE TITLE
Support for skippping validity checks

### ISSUE THREAD

**Issue by Modelmat** [Jguer/yay#672]
#### Affected Version

yay v8.998 - libalpm v11.0.1
#### Feature Request
Similar to https://github.com/archlinuxfr/yaourt/issues/108, allow the passing of `skipinteg`, `skipchecksums` and `skippgpcheck` to packages.

This helps with packages such as google-chrome-beta, which go out of date and need to be manually built.

**Comment by Modelmat** [comment]
Same thing as that issue, I wouldn't mind them as top level flags, or even combined into `--skipchecks`.

**Comment by Morganamilo** [comment]
>or even combined into --skipchecks

`--skipinteg` is the combination of `--skipchecksums` and `--skippgpcheck`.

Anyway `--mflags` is there for this, no need to have this as a regular flag. Plus I would rather not encourage the use of `--skipinteg` anyway, it should be a last resort.

**Comment by Modelmat** [comment]
Ok then, that is anyway.
