### ISSUE TITLE
What is the "(Build Files Exist)",howto remove the existed build files?

### ISSUE THREAD

**Issue by CallMeR** [Jguer/yay#677]
#### Affected Version

yay v8.998 - libalpm v11.0.1
#### Steps to reproduce

1.When I want to reinstall some packages,the yay shows "(Build Files Exist)".
2.Some times after I use yay -Rscn some-package,and reinstall them.yay shows "(Build Files Exist)".
3.I've checked the configuration about yay,and I haven't change the default builddir.
4.So,what exactly the "Build Files" are? Where is the files?How can I remove the needless build files after yay installation automaticly?

**Comment by Morganamilo** [comment]
Build files are the pkgbuild and other files needed to make the pkg. e.g. https://aur.archlinux.org/cgit/aur.git/tree/?h=yay. If makepkg is not configured it may also contain fetched sources and the build package.

They are in your builddir, where ever that is set.

You can remove them with `yay -Sc`, or automatically with  `--afterclean`.

**Comment by kgbook** [comment]
> 

It should be `--cleanafter`, but not `--afterclean`.

> --cleanafter
>               Remove untracked files after installation.
> 
>               Untracked files are removed with the exception of directories.  This allows VCS packages to easily pull an update instead of having to reclone the entire repo.

**Comment by kgbook** [comment]
> Build files are the pkgbuild and other files needed to make the pkg. e.g. https://aur.archlinux.org/cgit/aur.git/tree/?h=yay. If makepkg is not configured it may also contain fetched sources and the build package.
> 
> They are in your builddir, where ever that is set.
> 
> You can remove them with `yay -Sc`, or automatically with `--afterclean`.

It should be `--cleanafter`, but not `--afterclean`.

```
--cleanafter
              Remove untracked files after installation.

              Untracked files are removed with the exception of directories.  This allows VCS packages to easily pull an update instead of having to reclone the entire repo.
```

**Comment by pblanco-dekalabs** [comment]
for me after cleaning with `yay -Sc` the warning still appears, and installs a bad version of `conan` (It says that 1.48 is being installed but `conan --version` yields 1.45).

This can be somehow related to the package being stores somewhere else?

~ Thanks!
