### ISSUE TITLE
Update to yay v8.1110 causes creation of $HOME folder on any AUR package installation

### ISSUE THREAD

**Issue by j54n1n** [Jguer/yay#689]
#### Affected Version
```
$ yay -V
yay v8.1110 - libalpm v11.0.1
```

#### Issue
Installing any AUR package results in the creation of a `'$HOME'` folder within the current user home directory.

#### Steps to reproduce
```
$ yay -S sl-alt
...
$ ls
'$HOME'   Desktop   Downloads
$ ls -l | grep HOME
drwxr-xr-x 3 user users   4096 Sep  5 07:25 $HOME
```

**Comment by foosinn** [comment]
I currently have the same issue.
yay v8.1110 - libalpm v11.0.1

**Comment by Morganamilo** [comment]
Yep apologies, there was a brief window where that slipped through #686. I'll leave this one open for reference.
