### ISSUE TITLE
--pgpfetch option not retrieving keys?

### ISSUE THREAD

**Issue by TheToric** [Jguer/yay#690]
version:
yay v8.1115.r0.g6e0797a - libalpm v11.0.1

Issue:
--pgpfetch (or putting the option in the config) does not appear to do anything.

Steps to reproduce:
»yay --pgpfetch -S chocolate-doom (other packages give the same error...)

gives the error:
one or more gpg signatures could not be verified.

**Comment by Morganamilo** [comment]
The maintainer is using an outdated srcinfo tool that does not handle pgp keys. They should be using `makepkg --printsrcinfo`.

**Comment by TheToric** [comment]
Is there a way to fix this on my end?

**Comment by Morganamilo** [comment]
Just add they keys yourself is the easiest one. You could regenerate the srcinfo and commit it though if you wanted.

**Comment by Cherkah** [comment]
This problem is over 5 years old!
Is it still awaiting resolution?
