### ISSUE TITLE
Build failure with multiple Go versions installed

### ISSUE THREAD

**Issue by DisposaBoy** [Jguer/yay#692]
#### Affected Version
All? it's a problem with the Makefile

#### Issue

If you have multiple versions of Go installed but the main one found in `$PATH` is not the same version as `/usr/lib/go/bin/go`, the build will fail with errors like `compile: version "go1.11" does not match go tool version "go1.10.1"`

#### Steps to reproduce

1. Install multiple versions of Go e.g. `go1.10` from source
2. Set `$PATH` to have `g1.10` first
3. Attempt to build yay with the PKGBUILD

**Comment by Morganamilo** [comment]
It seems like the go root defaults to `/usr/lib/go` so the line can be removed completely. I can see https://github.com/DisposaBoy/yay/commit/579f1b9b9a810fb884ac5fb053ea95697639289b Is there any reason for doing this rather than just removing the line?

**Comment by DisposaBoy** [comment]
Explicitly putting `/usr/lib/go/bin` at the front of `$PATH` enables the Makefile to assume the `go` command is the one installed via `makedepends`.
I thought this was important because if `yay` depends on `go1.10` and I happen to install `go1.9` then the build will start failing again.

**Comment by DisposaBoy** [comment]
> The compile: version "go1.11" does not match go tool version "go1.10.1" would totally be on you. Having two version of the same software can get messy.

I didn't have multiple versions of Go installed (well, there is the `$GOROOT_BOOTSTRAP` version, but it's not accessible in `$PATH`). I had `go.10` installed because I need to test different versions of Go, but `yay` has a makedepends on the distro package. That's how I came to have 2 versions. The distro package is never installed by me.

> I'm just going to remove the line. I'd expect you to to export the correct variables for whichever version of go you would like to use.

I did; you don't need anything other than `$PATH`.

> How did you install it by the way? /usr/local? ~/.local?

I install from source, the actual location doesn't matter.

**Comment by Morganamilo** [comment]
What you probably want to do is write your own go dud pkgbuild if you with to not use the system package.
