### ISSUE TITLE
`makepkg -si` would not work without `gcc` and `fakeroot`

### ISSUE THREAD

**Issue by idealhack** [Jguer/yay#696]
#### Affected Version

yay v8.1115 - libalpm v11.0.1

#### Steps to reproduce

```
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

sudo pacman -S gcc fakeroot
makepkg -si
```

**Comment by polygamma** [comment]
https://wiki.archlinux.org/index.php/Arch_User_Repository#Getting_started

**Comment by idealhack** [comment]
@polygamma Thank you! It's a long time since I use AUR. But Is it reasonable to add these packages to the dependencies or return more information in the error?

**Comment by Morganamilo** [comment]
https://github.com/Jguer/yay#dependencies

**Comment by polygamma** [comment]
and also: https://wiki.archlinux.org/index.php/PKGBUILD#makedepends

**Comment by idealhack** [comment]
@Morganamilo @polygamma Thanks. Sure it does not make sense to require every AUR package to contain dependencies in `base-devel` group. This is more like an issue of Arch.

**Comment by svitoz** [comment]
@idealhack
Arch Linux expects you to have followed [Arch User Repository](https://wiki.archlinux.org/index.php/Arch_User_Repository) article when first installing something from AUR and directs to it both from [AUR landing page](https://aur.archlinux.org/) and [General recommendations](https://wiki.archlinux.org/index.php/General_recommendations).

To install your first AUR package you have to do it by invoking `makepkg` and in its documentation [it is also mentioned](https://wiki.archlinux.org/index.php/Makepkg#Usage) that you need to install `base-devel` package group as a baseline to build packages.

One can still improve [AUR landing page](https://aur.archlinux.org/) to direct to AUR article more explicitly. Other than that it is not so much Arch issue as available documentation is clear on this.
