### ISSUE TITLE
Yay doesn't create config json

### ISSUE THREAD

**Issue by linusheinz** [Jguer/yay#697]
I run the latest yay-git and it creates a folder ~/.config/yay but it  doesn't create a json config file

**Comment by linusheinz** [comment]
Thank you

**Comment by linusheinz** [comment]
Why doesn't it create one by default ?

**Comment by Jguer** [comment]
When defaults are changed in `yay` it makes it simpler to push the new defaults to users, avoids useless writes to the system and sometimes we break stuff [8.1115](https://github.com/Jguer/yay/releases/tag/v8.1115) and loading the default settings if not customized helps unbreak it. These are the advantages I can think at the top of my head

**Comment by isavcic** [comment]
@Jguer you should really make that more obvious that, when some `--answerX` parameter is specified without an actual package operation, nothing will get configured if `--save` is not specified.

**Comment by Morganamilo** [comment]
Programs don't tend to remember their command line options, so I don't think there should be any expectations for them to.

However, `--save` and the flags that it applies to are all documented anyway.

**Comment by masaeedu** [comment]
@Jguer It would be useful to document the existence and default location of a configuration file in the man page. I had no idea what I should create in that folder to configure `yay`, and I didn't actually want to update my system just now, so I can't run `yay <stuff> --save`.

**Comment by parkerlreed** [comment]
>and I didn't actually want to update my system just now, so I can't run yay <stuff> --save.

`yay --sudoloop --save` for example will save that to the config. It shouldn't update your system. `--save` doesn't require an actual update operation to be used.

**Comment by Morganamilo** [comment]
Regardless I believe we do document the  location.
