### ISSUE TITLE
[Feature Request] Add a short flag for `--repo`

### ISSUE THREAD

**Issue by Fierthraix** [Jguer/yay#698]
#### Issue
`yay` can search either the repositories or the AUR instead of both by supplying either the `--repo` or `--aur` flag respectively. 

The `--aur` flag has the short equivalent `-a`, allowing for the common usage:
`yay -Ssa qutebrowser` (Search for qutebrowser in the AUR)

By adding a `-r` flag that acts the same as `--repo` (like pacaur has) you get the same composibility and more consistency, so that this should work:
`yay -Ssr qutebrowser` (Search for qutebrowser in the repos)

#### Obstacles
Currently the `-r` is equivalent to `--root` which is one of the pacman flags that `yay` wraps around.
If `yay` is meant to be a perfect wrapper for pacaur than you can't steal the `-r` flag, but if it's not then I'd argue that the `--repo` usage is *far* more common.
The flag doesn't necessarily have to be `-r`, but adding a short flag at all would be very beneficial.

**Comment by Morganamilo** [comment]
`--sysroot` is meant to replace `--root`. The latter was even depreciated for a short while before they realised `--sysroot` is not yet good enough to properly replace `--root`.

Although whether they intend to eventually remove `--root` like they did to `--force`, or just depreciate it forever I'm not sure.

So `-r` may be free for us to use in the future.

**Comment by Jguer** [comment]
Closing until relevant again
