### ISSUE TITLE
Upgrade summary - broken ?

### ISSUE THREAD

**Issue by gferry** [Jguer/yay#699]
#### Affected Version
yay v8.1115 - libalpm v11.0.1

#### Issue
Hi there,

Long time since I've used yay, and for my first upgrade (using yay -Syyu), I don't have upgrade summary anymore (I used to see it a few months ago).

I can have a listing by enabling _**VerbosePkgLists**_ in pacman.conf, but it does not highlight diffs with colors (even though color is enabled in pacman.conf).

Is it intended ?

Thanks a lot,
Regards.

#### Steps to reproduce
1. yay -Syyu

You won't see a detail package upgrade summary, only the standard pacman list.

**Comment by Morganamilo** [comment]
See the FAQ and #554 #564 #606 #617 #634

**Comment by Morganamilo** [comment]
Also passing -y twice is pointless and just adds strain to the mirrors.

**Comment by gferry** [comment]
Thanks, indeed I read the FAQ too fast...
Sorry for that.

**Comment by gferry** [comment]
By the way, I'm using -y twice because I had problems with 'up-to-date' indexes : but I agree with you, it forces pacman to download them everytime.
Regarding the FAQ, maybe you should expicitely write that if package-skip is disabled, upgrade summary won't be displayed ?

Anyway, yay rocks, period :)
