### ISSUE TITLE
Choose default editor for PKGBUILD

### ISSUE THREAD

**Issue by RichardVoid** [Jguer/yay#7]
How can i choose my preferred editor? By default, `yay` opens PKGBUILD's in `vi`.

**Comment by RichardVoid** [comment]
Ok, so i find the way to choose editor. yay just read the $EDITOR environment variable:
https://github.com/Jguer/yay/blob/master/aur/utils.go#L16-L20
And exec it with PKGBUILD here:
https://github.com/Jguer/yay/blob/master/aur/result.go#L114-L118

**Comment by RichardVoid** [comment]
Can we implement `yaourt`'s `choose editor `option? Thus, the user can enter the name of the preferred program and edit PKGBUILD. If no arguments given - run all the way it works now. This should not be difficult.

**Comment by Jguer** [comment]
I find that $EDITOR is the most straightforward and default way of changing the editor. 

Is that an argument like --editor <editor name>?

**Comment by SolarAquarion** [comment]
that could work, it can also do a yayrc or whatever to set editor

**Comment by Jguer** [comment]
I'll add the --editor arg for now. 
Was waiting to test Go's plugin system in 1.8 for the config and git updates so they become something completely optional (but I've seen reports of the plugin system doubling binary sizes).

**Comment by RichardVoid** [comment]
@Jguer I mean something like this.
![2017-02-17-122934_swaygrab](https://cloud.githubusercontent.com/assets/13709036/23060385/8ef65e3a-f50e-11e6-9ce6-aa87f5d72043.png)

**Comment by Jguer** [comment]
If $EDITOR or $VISUAL is not defined show the warning and the "Edit PKGBUILD with:" prompt.

Will add

**Comment by RichardVoid** [comment]
That would be great. Thank you!
