### ISSUE TITLE
searching for aur package with pattern doesn't seem to work

### ISSUE THREAD

**Issue by andymass** [Jguer/yay#700]
#### Affected Version
```
% yay -V
yay v8.1115.r6.g47702f4 - libalpm v11.0.1
% pacman -Qm yay
yay-git 8.1115.r6.g47702f4-1
```

#### Issue / Steps to reproduce

Not sure if i'm misunderstanding something about how package search is supposed to work, but it seems like basic queries fail to find anything.  The search field is documented in the man page simply as `<search pattern>` so I assumed it was okay to use a regex.

```
% yay -Ssa par$
% yay -Ssa ^par
```
(nothing)

```
% pacaur -Ssa par$
aur/perl-par 1.015-1 (19, 0.43)
    Perl Archive Toolkit
aur/par 1.52-4 (37, 0.42)
    Paragraph reformatter
aur/quake-par 0.03.01-2 (9, 0.00)
    Quake PAK archiving utility.
aur/mumps-par 5.1.1-2 (0, 0.00)
    Sparse solver library using Gaussian elimination, with parmetis implementation
```

The particular package is found when not using a pattern:
```
% yay --color=never -Ssa par | grep 'aur/par '
aur/par 1.52-4 (+37 0.42%)
```

**Comment by Morganamilo** [comment]
AUR searching is done via the [RPC](https://aur.archlinux.org/rpc) which is a literal string. Indeed the man page probably should say `<search term>...` or something.

**Comment by andymass** [comment]
Thanks very much for clarifying!  I am used to pacman/pacaur so this limitation never occurred to me. 

Looking into it, it appears [auracle.cc][1] and [cower.c][2] (and hence pacaur) both merely emulate regex aur search by splitting the regex into pieces (e.g. `fo.*bar` becomes `fo` and `bar`), then running the regex on that list to filter further.  I would understand if this issue is solved only with changing the documentation.  However, if this were to be considered as a feature, I think this simple technique would suffice for most usages.  I generally use regex when anchoring a piece of a package name, e.g. `^par` or `par$` and that works very well.

[1]: https://github.com/falconindy/auracle/blob/95a4c805a4124900e9231e8c8acbd08c74d7314d/src/auracle.cc#L116
[2]: https://github.com/falconindy/cower/blob/f27f88f8641f3d64d57130bd84ed68fc131bfe8d/src/cower.c#L1919

**Comment by Morganamilo** [comment]
True regex is possible by matching it against `https://aur.archlinux.org/packages.gz`. You would get have to fetch into for all the hits. The downside being the search would work for the title only.
