### ISSUE TITLE
Proxy env variables being ignored.

### ISSUE THREAD

**Issue by GermanG** [Jguer/yay#701]
#### Affected Version
yay v8.1115 - libalpm v11.0.1
#### Issue
Having my user set with http_proxy variables (which I set or not at login time, depending on script)
#### Steps to reproduce
It's pretty simple, export http_proxy variables:
export HTTPS_PROXY=http://proxyhost:proxyport
export https_proxy=http://proxyhost:proxyport
export HTTP_PROXY=http://proxyhost:proxyport
export http_proxy=http://proxyhost:proxyport

and call yay to install any package. 

It'd be great to have an --export-env to let yay call sudo with "-E"

**Comment by Jguer** [comment]
Not the first proxy issue #429 but slightly different. Yay uses the `net/http` library with the default transport

> DefaultTransport is the default implementation of Transport and is used by DefaultClient. It establishes network connections as needed and caches them for reuse by subsequent calls. It uses HTTP proxies as directed by the $HTTP_PROXY and $NO_PROXY (or $http_proxy and $no_proxy) environment variables. 

The recommended way of preserving environment variables is to append them to env_keep:From the archwiki
```
/etc/sudoers

Defaults env_keep += "ftp_proxy http_proxy https_proxy no_proxy"
```

Have you tried that?

**Comment by GermanG** [comment]
Yup, worked right away.Thanks for the pointer!

**Comment by vale5566** [comment]
I try the same thing, my school forces to use a http_proxy.
I can update the normal packages, but the AUR update fail.

For the normal packages I use wget to update.
I put the same thing in my `/etc/sudoers`

I got this error:
`:: Searching AUR for updates...
Get https://aur.archlinux.org/rpc.php?arg%5B%5D=android-platform&arg%5B%5D=android-sdk&arg%5B%5D=android-sdk-build-tools&arg%5B%5D=android-sdk-platform-tools&arg%5B%5D=android-studio&arg%5B%5D=arch-wiki-cli&arg%5B%5D=chrome-gnome-shell-git&arg%5B%5D=fetchmirrors&arg%5B%5D=fetchpkg&arg%5B%5D=franz-bin&arg%5B%5D=lib32-zlib&arg%5B%5D=libc%2B%2B&arg%5B%5D=libc%2B%2Babi&arg%5B%5D=miraclecast&arg%5B%5D=nodejs-ungit&arg%5B%5D=numix-circle-icon-theme-git&arg%5B%5D=numix-icon-theme-git&arg%5B%5D=pvpn&arg%5B%5D=realvnc-vnc-viewer&arg%5B%5D=spotify&arg%5B%5D=todoist&arg%5B%5D=tor-browser-en&arg%5B%5D=wakeonlan&arg%5B%5D=watchdog&arg%5B%5D=webstorm&arg%5B%5D=yay&type=info&v=5: dial tcp 5.9.250.164:443: i/o timeout`

**Comment by Jguer** [comment]
`dial tcp 5.9.250.164:443: i/o timeout` tells me that you are indeed communicating with the AUR SSL but you're getting no response. 

What type of proxy are you using? 
Can you post a censored version of your environment variables http_proxy and https_proxy? 
Can you confirm curl works with sudo and proxy?
