### ISSUE TITLE
Installing packages fails with: No remote-tracking branch for master from origin

### ISSUE THREAD

**Issue by fho** [Jguer/yay#702]
#### Affected Version
- yay v8.1115 - libalpm v11.0.1 (also happened with earlier versions)
- git version 2.19.0

#### Issue
Installing packages fails with the  error:
`error merging passff-host: fatal: No remote-tracking branch for master from origin`

I already tried removing `~/.cache/yay` but it didn't fix the problem.

#### Steps to reproduce
I get the error with most or all(?) packages that I'm trying to install, e.g:
-`yay -Sy passff-host` 
-`yay -Sy spotify`
-`yay -Sy lain-git`

**Comment by Morganamilo** [comment]
That's a weird one. Can you please show 
````
yay -Pg
````
and
```
git remote -v
```
from inside the cache directory of a failing package.

I'm assuming the last commands are a typo and you mean `yay` instead. Also never do `pacman -Sy` or any equivalent (`yay -Sy`) https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported.

**Comment by fho** [comment]
> I'm assuming the last commands are a typo and you mean yay instead.

Yes, that was a typo. I fixed it in my post

Thanks, you got me the idea that the issue might be in my `.gitconfig` and it was.
The following section in my `.gitconfig` caused the issue:
```
[branch "master"]                                                                                                                                       
        remote = origin
        merge = master
```
