### ISSUE TITLE
#57 reborn - yay does not parse regex in ignorepkg in pacman.conf

### ISSUE THREAD

**Issue by Taijian** [Jguer/yay#71]
Thank you for promptly fixing the original bug I reported (#57)! Unfortunately, there seems to be another issue with the parsing of the ignorepkg list from pacman.conf:

yay only checks for a literal matching pkgname, however pacman will also accept a wildcard like 'php*', matching all php packages (useful for users of nextcloud, which is currently incompatible with php 7.2). Is that something that you could fix?

**Comment by Jguer** [comment]
It's fixable,  joining it with #73 on the TODO list.

**Comment by Morganamilo** [comment]
Looking at how pacman does it. IgnorePkg matching is done using fnmatch. Except with the addition that ! can be used at the start of a pattern to invert it or a \ can be used to escape the !.

```
foo* //try to match foo*
!foo* //try to match NOT foo*
\!foo* //try to match !foo*
```
