### ISSUE TITLE
aur.archlinux.org/yay.git gives 404

### ISSUE THREAD

**Issue by suuuehgi** [Jguer/yay#710]
#### Affected Version
git

#### Issue
https://aur.archlinux.org/yay.git --> 404 - Page Not Found

**Comment by xNevo** [comment]
It's actually https://aur.archlinux.org/packages/yay/.
`https://aur.archlinux.org/yay.git` is the git repository

```sh
root@zeus:~# git clone https://aur.archlinux.org/yay.git
Cloning into 'yay'...
remote: Enumerating objects: 206, done.
remote: Counting objects: 100% (206/206), done.
remote: Compressing objects: 100% (144/144), done.
remote: Total 206 (delta 60), reused 206 (delta 60)
Receiving objects: 100% (206/206), 40.10 KiB | 0 bytes/s, done.
Resolving deltas: 100% (60/60), done.
root@zeus:~#
````

**Comment by suuuehgi** [comment]
> `https://aur.archlinux.org/yay.git` is the git repository

I'm sorry, my bad ... `git clone` failed because I didn't have my `resolv.conf` set up then. Additionally, I was not expecting a 404 when I simply pasted the URL on another computers browser.
