### ISSUE TITLE
document how to download PKGBUILD and build new version

### ISSUE THREAD

**Issue by soloturn** [Jguer/yay#719]
currently the documentation is not obvious on how to download a PKGBUILD from ABS, change it, e.g. to put in a new version the original packager did not do yet, and run makepkg with getting the dependencies so it compiles from source.

**Comment by Morganamilo** [comment]
-G can download pkgbuilds from the ABS. That is the full extend that yay currently interacts with the ABS and local pkgbuilds.

**Comment by soloturn** [comment]
ok i see. this is sufficient. download the PKGBUILD and use makepkg -si to build and installit. tx!!
