### ISSUE TITLE
Print config not human friendly

### ISSUE THREAD

**Issue by drrlvn** [Jguer/yay#72]
The flag `--printconfig` just prints the JSON in a single line with no trailing newline. It would be more helpful to pretty print it.

**Comment by maximbaz** [comment]
And it's not even a valid JSON by the way, but a print-out of the go's struct 🙂 

I think the output should be exactly what `cat ~/.config/yay/config.json` is showing, formatted real JSON.

**Comment by Jguer** [comment]
Printing out the go struct was the easiest and fastest way for debugging. It should be relatively easy to make it print more beautifully if someone wants to take it up, otherwise I can do it on the 24th.

**Comment by AnthonyLam** [comment]
@Jguer Have you worked on this yet? If not I can take a stab at it.

**Comment by Jguer** [comment]
Sorry for the late reply @AnthonyLam , feel free to take a stab at it.
