### ISSUE TITLE
--quiet should be more quiet

### ISSUE THREAD

**Issue by x70b1** [Jguer/yay#720]
#### Affected Version
yay v8.1115 - libalpm v11.0.1

#### Issue
```
$ yay -Su --aur --quiet
:: Searching AUR for updates...
there is nothing to do
```
This should print AUR updates or nothing. 

Or what do you think of that? I'm a bit sorry to try to copy the behavior of other AUR helpers to `yay`. But actually, it doesn't seem very wrong.

**Comment by Morganamilo** [comment]
`-q` is meant for `-Ss`. It's basically a no op here, [even in pacman](https://bugs.archlinux.org/task/20683). To me it seems pointless to handle it unless pacman also respected the flag.

**Comment by x70b1** [comment]
Okay. But is there a way to get a list of AUR updates only? I would like to display them.
`yay -Qua` only works if I use `yay -Sy` before?

What would you recommend? It aims to the same question like #715. I would like to do a `| wc -l`.

**Comment by x70b1** [comment]
And the means `yay -Qum` don't need a `-Sy`?
