### ISSUE TITLE
sudo times out making yay hang

### ISSUE THREAD

**Issue by alex9099** [Jguer/yay#721]
#### Affected Version
yay v8.1115 - libalpm v11.0.1

#### Issue
sudo times out, asking for password and making yay hang (this does not happen on pacaur for example)

#### Steps to reproduce
I tried running yay -Syu (to upgrade everything). My computer is quite slow, so compiling stuff takes a while.

**Comment by Morganamilo** [comment]
Full output?

(Probably gonna add that to the template when I'm home)

**Comment by alex9099** [comment]
Now i don't have packages to upgrade, but it is the normal makepkg output followed by sudo prompting the password, the first packages get installed without a problem, but the ones after a certain time of starting yay get stuck with sudo asking for a password

**Comment by Morganamilo** [comment]
Oh okay. Saying yay hangs made me think of some sort of deadlock where the user could not do anything. Are you using `sudoloop`? You never mentioned it so my guess it you just never enabled it.

**Comment by alex9099** [comment]
Yea, i did not expressed well :) actually yay just waits for sudo, then it seems to give up and get's killed (or kills itself, not sure)

what is sudoloop? can't find anything about it

**Comment by Morganamilo** [comment]
>then it seems to give up and get's killed (or kills itself, not sure)

Sudo will only wait for a password for so long before exiting.

>what is sudoloop? can't find anything about it

`yay --help | grep sudoloop`

**Comment by alex9099** [comment]
> Sudo will only wait for a password for so long before exiting.

Yeah, i wasn't expecting it to timeout so i just let the yay do it's stuff and came back later with a last line being a sudo prompt :)

> yay --help | grep sudoloop

hmm i see, isn't sudoloop suposed to be the default?

**Comment by Jguer** [comment]
You can check default settings with `yay -Pg` (Also just notice -Pg is not in fish autocomplete but -Pd is, to remember) and current settings with `yay -Pd`

**Comment by alex9099** [comment]
yep, it is "false" by default. I guess this is more of a opinion kind of thing, but since the option exists, shouldn't it default to true?

**Comment by Morganamilo** [comment]
sudoloop will break if the user has a shorter or immediate timeout, that is why it is off by default.

**Comment by alex9099** [comment]
I understand, in that case i'll set sudoloop as default for me (still gotta see how to set it as default :D) and close the issue, thanks

**Comment by Morganamilo** [comment]
>still gotta see how to set it as defaul

See `--save`
