### ISSUE TITLE
Invalid option 'assume-installed'

### ISSUE THREAD

**Issue by KNejad** [Jguer/yay#722]
#### Affected Version

`yay -V`: `yay v8.1115 - libalpm v11.0.1`

#### Issue

When running the command `yay -S ros-melodic-desktop-full --assume-installed ros-melodic-rograph-msgs` I get the error message `invalid option 'assume-installed'`. I am not sure if the flag "assume-installed" is supposed to exist but when I use tab completion (on zsh) one of the options is this:

```
--assume-installed    -- Add virtual package to satisfy dependencies
```

It could either be that the option no longer exists (or renamed), since I couldn't find it in the man pages with "man yay". Or there is a bug somewhere.

#### Steps to reproduce
1. Type `yay -S ros-melodic-desktop-full --` and then hit tab twice. From the list of options that pop up one will be the assume-installed flag.
2. If you type in the full command `yay -S ros-melodic-desktop-full --assume-installed ros-melodic-rograph-msgs` it will complain that the flag does not exist

## Edit

It seems "--assume-installed" is an option on pacman. Since I am installing this package through AUR pacman is not being called so yay does not know what to do with the flag. Maybe the best option is for yay to mention when a flag is from pacman and it can't be used. Better yet if this could be added to yay that would be awesome

**Comment by Morganamilo** [comment]
It was just some how missed out of the allowed flags. It's added now for pacman wrapping but yay does not actually understand this flag. Might add it when I fix #695.
