### ISSUE TITLE
--quiet not working with -Qu

### ISSUE THREAD

**Issue by gkaklas** [Jguer/yay#726]
--quiet seems to work in query operations like -Qs and -Qd, but it doesn't work in -Qu: old and new version numbers are shown for both repository and AUR packages. For comparison, `pacman -Quq` shows upgradable packages without their version numbers.

I'm using yay v8.1115.

**Comment by Morganamilo** [comment]
Nice catch, I fixed it. First day at college and now I realise they blocked ssh and I can't push :/

**Comment by Jguer** [comment]
Got it @Morganamilo no worries.
