### ISSUE TITLE
pacman.conf parser does not respect comments

### ISSUE THREAD

**Issue by jakebailey** [Jguer/yay#73]
I have some entries commented out in my IgnorePkg, but yay treats the `#` as a package name and continues parsing everything after it. This comes from the alpm library (which is a fork, so no issue tracker).

Example:
```go
package main

import (
	"fmt"
	"strings"

	"github.com/jguer/go-alpm"
)

func printIgnorePkg(s string) {
	r := strings.NewReader(s)
	conf, _ := alpm.ParseConfig(r)
	fmt.Println(conf.IgnorePkg)
}

func main() {
	printIgnorePkg(`
[options]
IgnorePkg = foo bar # baz
`)

	printIgnorePkg(`
[options]
IgnorePkg = foo bar
`)
}
```

Output:
```
[foo bar # baz]
[foo bar]
```

I suspect there are more issues like this in some of the other parts of the config parser.

**Comment by Jguer** [comment]
I'll patch it in jguer/go-alpm and submit a pull request for the original repository
