### ISSUE TITLE
Cache VCS repositories only

### ISSUE THREAD

**Issue by hexchain** [Jguer/yay#736]
#### Affected Version

yay v8.1139 - libalpm v11.0.1

#### Issue
Currently, `yay` may save everything if the package is successfully built, which includes history versions of built packages that can be very space-consuming.

It would be great if `yay` has an option to cache only VCS repositories to speed up future checkout.

The `SRCDEST` option in `makepkg` also saves all non-VCS sources, which is useless for me in most situations: new tarballs always need to be downloaded, and keeping old ones does not really help.

**Comment by Morganamilo** [comment]
`-Sc` does this. Currently `--afterclean` just does `rm -rf dir`. It would make sense for to reuse the `-Sc` logic for `--afterclean`
