### ISSUE TITLE
Different output for -S option

### ISSUE THREAD

**Issue by iwex** [Jguer/yay#749]
Hi! I have a question.
I tried to install mysql-clients package from AUR.
![image](https://user-images.githubusercontent.com/4510068/46476605-43013b00-c7f1-11e8-9820-3d990f86e881.png)
With -S
![image](https://user-images.githubusercontent.com/4510068/46476612-498fb280-c7f1-11e8-803c-aba662f5d717.png)
So we can see that yay (without -S) searches only in AUR, however it should search in both Pacman and Aur repos.
![image](https://user-images.githubusercontent.com/4510068/46476684-747a0680-c7f1-11e8-8359-a336c7aada64.png)
In yaourt we have both options:
![image](https://user-images.githubusercontent.com/4510068/46476710-8196f580-c7f1-11e8-8a45-e7fc5e550a09.png)

Is it bug or feature? :)

**Comment by Morganamilo** [comment]
Bug I guess:
```
morganamilo@Octavia ~ % yay mysql-clients
6 aur/mysql-clients55 5.5.61-1 (+3 0.00%) 
    MySQL client tools, v5.5
5 aur/mysql-clients57 5.7.23-1 (+6 0.34%) 
    MySQL client tools, v5.7
4 aur/mysql-clients56 5.6.41-1 (+6 0.00%) 
    MySQL client tools, v5.6
3 aur/mysql-clients 8.0.12-1 (+60 0.94%) 
    MySQL client tools
2 community/percona-server-clients 5.7.23_23-2 (1.8 MiB 45.4 MiB) 
    Percona Server client tools
1 extra/mariadb-clients 10.1.36-1 (1.5 MiB 39.0 MiB) 
    MariaDB client tools
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 
```

Yay version, yay config and pacman config?

**Comment by iwex** [comment]
@Morganamilo 
ah.. I have old yay (8.9) from arch repos..
Not everything is ok, thanks :)

**Comment by Morganamilo** [comment]
>arch repo

Don't confuse arch with other downstream distros/third party repos

**Comment by iwex** [comment]
@Morganamilo I've installed 8.998-2 from community repo

**Comment by iwex** [comment]
@Morganamilo It's manjaro)
