### ISSUE TITLE
How to edit PKGBUILD before install

### ISSUE THREAD

**Issue by pierrre** [Jguer/yay#750]
Hello !

I'm a new `yay` user.
I migrated from `yaourt` very recently.

I've noticed one missing feature compared to `yaourt`.
I can't edit the `PKGBUILD` before the install.
It's very useful, because it allows me to remove unwanted dependencies.
I have 2 real examples:

`smartgit` requires to install `java-runtime`.
Actually it is not needed because the source archive file provides its own Java runtime.
So I edit the `PKGBUILD` before an install/update and remove this dependency.

Another example is `yay` itself.
I'm a Go developer and I use my own Go environment.
I don't need the `go` Archlinux package.
When I installed `yay` the first time, using `yaourt`, I could edit the `PKGBUILD` and remove the `go` dependency.

How can I do that with `yay` ?
Thanks.

**Comment by Morganamilo** [comment]
See the manpage/help for `--editmenu`.

Do note that yay doesn't use the pkgbuild for dependencies it uses the RPC. So yay will ignore these changes in its dependency solving. The changes will still apply to the built packages though. This is noted in the FAQ and manpage.

**Comment by pierrre** [comment]
ok, thank you !

**Comment by brainplot** [comment]
I think there's no need for a workaround. `yay --editmenu -S <package-name>` does exactly what you're asking for.

**Comment by pierrre** [comment]
@brainplot no, `yay` installs the dependencies before allowing you to edit the PKGBUILD

**Comment by brainplot** [comment]
Ah, I see. Thanks for the clarification.

**Comment by flying-sheep** [comment]
Also it seems that the `provides` array is cached before the changes.

**Comment by Ashark** [comment]
For those who come from web search and want to make --editmenu option to be permanent:
`yay --editmenu --save`
The config will be created and next time you do not need to specify it. See #855 for the config example.

**Comment by weshouman** [comment]
For a headless run, the `yay -G PACKAGE` option is necessary, and if the package has AUR dependencies the steps would be something like
```
yay -G PACKAGE_NAME
patch -u PKGBUILD -i /path/to/PKGBUILD.patch
yay -S PACKAGE_NAME --answerdiff=None --noremovemake --pgpfetch --answerclean=None --noconfirm --asdeps
makepkg -si
```

**Comment by conorbros** [comment]
> If someone has the same problem and is reading this, my workaround is:
> 
> * `yay -G <package_name>`
> * edit the `PKGBUILD`
> * `makepkg -si`

You might need to use `updpkgsums` to update the hash check too.

**Comment by KAGEYAM4** [comment]
@pierrre  did you find any solution? I read `man yay` but couldn't find anything.

i want to edit pkgbuild to remove dependency, but even after editing the pkgbuild when yay asks, yay still donwloads them and installs them.

**Comment by WildPenquin** [comment]
> I think there's no need for a workaround. `yay --editmenu -S <package-name>` does exactly what you're asking for.

The problem here is that yay will always update the PKGBUILD. If other changes (updating pkgsums) becomes required, it becomes quite laboursome with yay since it will just revert to the original PKGBUILD on each run. Is there a way to tell it to **not update** the PKGBUILD (I've just edited outside yay)? Or run or ignore checksums? (There's plethora of 3rd party software, who do not sign and checksums are useless save for making sure the download was correct).

**EDIT:** To clarify, yes, editmenu works but workaround outside yay is still very much needed. Not all changes can be easily done manually trough the editmenu
