### ISSUE TITLE
Non-AUR packages listed as missing in the AUR

### ISSUE THREAD

**Issue by willemw12** [Jguer/yay#752]
Locally created packages, that are not part of the AUR (and the Archlinux repo) are listed as missing in the AUR:

    $ yay -Syu
    :: Synchronizing package databases...
     core is up to date
     extra is up to date
     community is up to date
    :: Starting full system upgrade...
     there is nothing to do
    :: Searching databases for updates...
    :: Searching AUR for updates...
     -> Missing AUR Packages:  mypackage1  mypackage2
     there is nothing to do
Adding those packages to IgnorePkg= in file /etc/pacman.conf does not help.

yay v8.1139.r13.g6ee14d4 - libalpm v11.0.1

**Comment by willemw12** [comment]
I understand why this message is displayed like that.

I would like to hide those locally created packages from the "Missing AUR Packages" list, for example, by listing those packages in IgnorePkg=.

Would that be possible? Would anyone be interested in implementing this?

**Comment by willemw12** [comment]
Thanks.

Maybe yay is now too silent.

Pacman and yay still report ignored packages which are in the (Arch Linux) repo:

     -> bc: ignoring package upgrade (1.06.95-3 => 1.07.1-1)

which is good, however, yay does not report other ignored packages. That is inconsistent (and incorrect?).

If, instead of using --ignore, yay can automatically detect whether a package is from the AUR or a locally created package, then yay can:

- skip locally created packages from the "Missing AUR Packages" list (fix this issue)
- report all ignored packages

**Comment by Jguer** [comment]
that is pacman output, won't touch, refer to #756 for the discussion on the particular fix

**Comment by willemw12** [comment]
Only as information. I am not suggesting to change yay.

Every AUR helper does it differently.

pacaur -Syu:

    warning: bc: ignoring package upgrade (1.06.95-3 => 1.07.1-1)
    ...
    :: Starting AUR upgrade...
    :: mypackage1 is not present in AUR -- skipping

trizen -Syu:

    warning: bc: ignoring package upgrade (1.06.95-3 => 1.07.1-1)
    ...
    :: mypackage1 was not found in AUR -- skipping

pikaur -Syu:

    :: Ignoring package mypackage1 (3.2.0.26-1 => )
    ...
    warning: bc: ignoring package upgrade (1.06.95-3 => 1.07.1-1)

pikaur -Syu (when packages are not ignored):

    :: warning: Following package cannot be found in AUR:
        mypackage1         
    ...
