### ISSUE TITLE
How to upgrade an ignored package?

### ISSUE THREAD

**Issue by willemw12** [Jguer/yay#753]
If a package is configured as ignored in IgnorePkg= in file /etc/pacman.conf, then to implicitly install the package you can do:

    # pacman -S networkmanager
    :: networkmanager is in IgnorePkg/IgnoreGroup. Install anyway? [Y/n]

However, yay silently ignores the package upgrade:

    $ yay -S networkmanager
    $ yay -S --rebuild networkmanager

yay v8.1139.r13.g6ee14d4 - libalpm v11.0.1

**Comment by Morganamilo** [comment]
Can you please provide the output, unless you are saying both of those commands produce no output.

**Comment by willemw12** [comment]
Both commands produce no output ("silently").

**Comment by Morganamilo** [comment]
Hmm it's working fine on my end. yay and pacman configs?

**Comment by willemw12** [comment]
In a clean chroot environment, I get the same result:

    # arch-nspawn $CHROOT/root yay -Syu
    Please avoid running yay as root/sudo.
    :: Synchronizing package databases...
     core is up to date
     extra is up to date
     community is up to date
    :: Starting full system upgrade...
    warning: bc: ignoring package upgrade (1.06.95-3 => 1.07.1-1)
     there is nothing to do
    :: Searching databases for updates...
    :: Searching AUR for updates...
     -> bc: ignoring package upgrade (1.06.95-3 => 1.07.1-1)
     there is nothing to do


    # arch-nspawn $CHROOT/root yay -S bc
    Please avoid running yay as root/sudo.

**Comment by Morganamilo** [comment]
Weirdly enough I'm able to reproduce it on another machine.

**Comment by Morganamilo** [comment]
It comes down to inRepos() in install.go. The findSatisfier() function respects ignorepkg so ends up ignoring matches and returning false.

Can't fix it right now but that's the cause at least.

**Comment by dvejmz** [comment]
Hey, I'm happy to take this one. However, I do have a question. I've been browsing through `go-alpm` and have found the line where `FindSatisfier()` invokes the underlying `libalpm` API.

    // go-alpm/dependency.go
    ptr := C.alpm_find_dbs_satisfier(pkgHandle, pkgList, cDepString)

`alpm_find_dbs_satisfier()` will always invoke `resolvedep()`, the function that does all the real work, like this

	pkg = resolvedep(handle, dep, dbs, NULL, 1);

That last argument is `prompt`, which instructs `resolvedep` to show the confirmation prompt @willemw12 reported to be missing in `yay`.

    // pacman/lib/libalpm/deps.c
	if(alpm_pkg_should_ignore(handle, pkg)) {
		int install = 0;
		if(prompt) {
			QUESTION(handle, ALPM_QUESTION_INSTALL_IGNOREPKG, pkg,
					 NULL, NULL, &install);
		} else {

My question is, if go-alpm is calling `resolvedep` exactly like `pacman` would in this instance, how come the prompt is not showing up?

**Comment by Morganamilo** [comment]
Probably because we never handle the callback for it.
