### ISSUE TITLE
ERROR: PKGBUILD does not exist

### ISSUE THREAD

**Issue by C-Radius** [Jguer/yay#754]
#### Issue
I cloned yay repository. I switched to its directory. I executed makepkg -si
And I got error no PKGBUILD
Repeated multiple times from scratch. 
Directory doesn't contain a PKGBUILD file.

#### Steps to reproduce

```
xxx% git clone https://github.com/Jguer/yay.git
Cloning into 'yay'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4469 (delta 0), reused 0 (delta 0), pack-reused 4465
Receiving objects: 100% (4469/4469), 4.50 MiB | 554.00 KiB/s, done.
Resolving deltas: 100% (2654/2654), done.
xxx% cd yay
xxx% makepkg -si
```

#### Output
```
==> ERROR: PKGBUILD does not exist.
xxx% 
```

**Comment by Morganamilo** [comment]
As the error suggests, this repo does not contain a pkgbuild. Use the AUR instead.

**Comment by C-Radius** [comment]
Thanks and I'm sorry for my stupidity. So far I never had a problem installing yay. This time somehow I landed here.
