### ISSUE TITLE
How can i skip validity checks?

### ISSUE THREAD

**Issue by bazeeel** [Jguer/yay#755]
I can't install vivaldi-widevine.

**Comment by Morganamilo** [comment]
See mflags.

**Comment by bazeeel** [comment]
thank you.

**Comment by Morganamilo** [comment]
Also worth noting that many packages use a non unique name like eula.txt in the source array. This means that when package upgrades with a new eula, the old one is still there and makepkg thinks it's the correct file.

Then the only thing to do is delete that file and let makepkg redownload it. I'm not sure if it applies to this package but you should always give it a try before skipping checksums.

**Comment by bazeeel** [comment]
I understood and i appreciate your help.

**Comment by arch-user-france1** [comment]
Here it doesn't skip one check: `yay -S --noconfirm --mflags --skipinteg unigine-superposition`
