### ISSUE TITLE
Disable compression of packages to be installed

### ISSUE THREAD

**Issue by dbrgn** [Jguer/yay#765]
#### Affected Version

yay v8.1157.0 - libalpm v11.0.1

#### Issue

When installing a big package (like android-studio), after the package is built it is compressed. That takes around 15-30 minutes on my machine and is entirely useless, because when yay installs the package it's decompressed again.

Makepkg can be configured not to compress packages by setting `PKGEXT=.pkg.tar`. I don't want to do that in my `makepkg.conf` though, since when I manually build packages I do want them to be compressed.

Is there a way to turn off compression for yay invocations of makepkg? (Could even be the default behavior in my opinion.)

**Comment by Morganamilo** [comment]
Yay can use an alternative makepkg.conf. You'd probably want to create one that sources the original but changes the pkgext. Additionally for a one off you could just run `PKGEXT=.pkg.tar yay -S foo`.

**Comment by dbrgn** [comment]
Ah, that makepkg.conf hint helped! Thanks for maintaining yay :slightly_smiling_face:

**Comment by scrouthtv** [comment]
@dbrgn Could you show us how you did it?

**Comment by dbrgn** [comment]
@scrouthtv 

```
$ cat .config/yay/makepkg.conf
source /etc/makepkg.conf

PKGEXT='.pkg.tar'

$ cat .config/yay/config.json | grep makepkg
	"makepkgbin": "makepkg",
	"makepkgconf": "/home/danilo/.config/yay/makepkg.conf",
```

**Comment by scrouthtv** [comment]
Thanks a lot :)

**Comment by marcospb19** [comment]
Just for anyone that googles it and ends up here:

![image](https://user-images.githubusercontent.com/38900226/82366187-30e50800-99e8-11ea-8777-f2b4698440cf.png)

At the end of `/etc/makepkg.conf`, it's enough to do the trick and skip the `Compressing Package` long step.

2023 update:
This doesn't save a lot of time anymore because `zst` is pretty fast.

**Comment by SimonSelg** [comment]
> At the end of `/etc/makepkg.conf`, it's enough to do the trick and skip the `Compressing Package` long step.

Thank you! For anyone wondering, this behavior is documented [here](https://wiki.archlinux.org/index.php/Makepkg#Use_other_compression_algorithms).
