### ISSUE TITLE
git origin push URL incorrect

### ISSUE THREAD

**Issue by HaleTom** [Jguer/yay#773]
#### Affected Version
`yay v8.1115 - libalpm v11.0.1`

#### Issue
I am the maintainer of a `nixnote2-git` in the AUR.

I generally edit my package in `yay`'s cache to avoid duplicates.

`yay`'s default `git remote` setup is:

```
% git remote -v
origin  https://aur.archlinux.org/nixnote2-git.git (fetch)
origin  https://aur.archlinux.org/nixnote2-git.git (push)
```

When I try to push, I get:
```
% git push
fatal: unable to access 'https://aur.archlinux.org/nixnote2-git.git/': The requested URL returned error: 403
```

To allow `push`ing, the setup should be:

```
% git remote -v
origin  https://aur.archlinux.org/nixnote2-git.git (fetch)
origin  ssh://aur@aur.archlinux.org/nixnote2-git.git (push)
```
Ie, to allow pushing `yay` would need to do:

```
remote set-url --push origin ssh://aur@aur.archlinux.org/${pkgname}.git
```

**Comment by Morganamilo** [comment]
I think I'll leave that up to the user to set themselves. I don't want to clone over ssh, nor do I want to add another git call to just change the push URL.

Yay itself is only concerned with fetching. If you want to use the cache for other uses then that will probably work fine but yay does not deal with that.

**Comment by HaleTom** [comment]
Thanks @Jguer. Perfect workaround!

**Comment by HaleTom** [comment]
Note: the alternative push URL is only added when the fetch URL is added.

(I needed to remove the fetch remote and re-add it for the push remote to be auto-setup).

**Comment by Jguer** [comment]
@HaleTom you can check my git config [here](https://github.com/Jguer/dotfiles/blob/master)/gitconfig but it works without any tweaking to use github only over ssh
