### ISSUE TITLE
Fails on empty dependencies

### ISSUE THREAD

**Issue by ObserverOfTime** [Jguer/yay#776]
#### Affected Version
`yay v8.1157.0.r13.ga565544 - libalpm v11.0.1`

#### Issue
Attempting to install [vale-bin](https://aur.archlinux.org/packages/vale-bin) with yay fails because its `PKGBUILD` contains the following lines:
```sh
depends=('')
makedepends=('')
```
(Removing those lines via `editmenu` makes it work.)

To fix this error, empty strings and empty arrays should be ignored during dependency resolution.

#### Output
```
warning: cannot resolve "", a dependency of "vale-bin"
:: The following package cannot be upgraded due to unresolvable dependencies:
      vale-bin

:: Do you want to skip the above package for this upgrade? [y/N] 
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency '' required by vale-bin
```

**Comment by Jguer** [comment]
That PKGBUILD in effect is saying it depends on a package that provides something called ''. It should be `makedepends=()`, so it should be `PKGBUILD Fault`. 

Now, if @Morganamilo wants to ignore empty strings in `morganamilo/go-srcinfo` is a workaround for those `PKGBUILDs` but I think we've had this conversation once already

**Comment by Morganamilo** [comment]
There's no point in ignoring it in yay because pacman will still refuse to install it.

**Comment by ObserverOfTime** [comment]
Yeah, you're right, pacman can't install it. Plus, the packager fixed it now so I'm closing this issue.

**Comment by Morganamilo** [comment]
Makepkg should have detected this and refused to build this in the first place. Turns out it lets slip on arrays of empty strings.

If any one is interested in the internals: https://patchwork.archlinux.org/patch/813/
