### ISSUE TITLE
Exclude packages when updating with yay

### ISSUE THREAD

**Issue by arcolinuxz** [Jguer/yay#780]
**Enhancement**

would be great if we could use yay.conf or some other file to exclude packages coming from aur we do not want to update/install

/etc/pacman.conf example 
IgnorePkg = linux-mainline linux-mainline-headers

issue now on my machine - installed the latest kernel from linux-mainline (build of 30 minutes) - AUR

yay says there is a new update from 4.19.rc7-1 to 4.19.rc8-1

I do NOT want to rebuild it.

We need some way to tell yay not to upgrade some of the packages if we are satisfied with the current version.

Keep up the good work - enjoying yay.

Solution for the moment - I update every package individually with yay

**Comment by Morganamilo** [comment]
IgnorePkg already does this.

**Comment by arcolinuxz** [comment]
great for Arch Linux packages - NOT working for AUR packages

**Comment by Jguer** [comment]
So I downgraded yay to `8.1157.0-1`. I ran `yay` I got this output:
```
❯ yay
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 archstrike is up to date
:: Searching databases for updates...
:: Searching AUR for updates...
:: Checking development packages...
:: 1 Packages to upgrade.
1  aur/yay  8.1157.0-1 -> 8.1173.0-1
==> Packages to not upgrade: (eg: 1 2 3, 1-3, ^4 or repo name)
```

I added yay to my `/etc/pacman.conf` in `IgnorePkg` and I get this output

```
❯ yay
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 archstrike is up to date
:: Searching databases for updates...
:: Searching AUR for updates...
:: Checking development packages...
 -> yay: ignoring package upgrade (8.1157.0-1 => 8.1173.0-1)
:: Starting full system upgrade...
 there is nothing to do
```

So, I'm going to need more information than `NOT working for AUR packages`. For example, what is the output of `yay -Pg`?

**Comment by erikdubois** [comment]
`[erik@ArcoLinux ~]$ yay -Pg
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/erik/.cache/yay",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"tarbin": "bsdtar",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"gitflags": "",
	"removemake": "ask",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"gitclone": true,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false
}
`

**Comment by erikdubois** [comment]
Oh my god - It was working after all.
Yay looks at the /etc/pacman.conf - I forgot to add linux-mainline-headers to the pacman.conf hence the confusion of yay not working
such a waste of time for both of us
closing this topic immediately

**Comment by arcolinuxz** [comment]
Closing now
again sorry
