### ISSUE TITLE
yay verbose output.

### ISSUE THREAD

**Issue by alex19EP** [Jguer/yay#781]
#### Issue
i enabled verbose package list in pacman's options... but yay displays it on one line.
example 
package 3
extra 
fu-p1.3.4. fu-pa2.5. fu-pb1.4.

is it possible to desplay it like a pacman 

fu-b version size 
fu-pa version size
fu-pb version size  

i read man page but not found correct option. 
thanks for help.

**Comment by Jguer** [comment]
do `yay -Syu --combinedupgrade --save` once 
https://github.com/Jguer/yay#frequently-asked-questions

**Comment by Morganamilo** [comment]
I think this is a little different as we show a menu of the updated but pacman's verbodepkglists options shows a table of all packages to be installed replacing the `[AUR 2] foor bar` message.

Still it's not something I really feel like implementing when the update menu serves as a decent substitute.

**Comment by erikpro** [comment]
hello. i think it wood  be useful to have such  option. 
i am blind arch user and i am using screen reader. and when i install a a large number of packages such a presentation is more convenient to understand.
Perhaps you can consider its implementation?

**Comment by Jguer** [comment]
Hum, I understand the issue now, we would only be able to display
```
fu-b version
fu-pa version
fu-pb version
```
And I don't recall the code right now but it could be at that phase we only have a string array. I'll check it but if the above makes a difference I can see if it's possible

**Comment by Morganamilo** [comment]
I think it might make more sense to just reuse the upgrade menu format.
