### ISSUE TITLE
mount, arch-chroot, upgrade should work

### ISSUE THREAD

**Issue by soloturn** [Jguer/yay#787]
it would be great yay would be able to upgrade AUR packages in a arch-chroot environment. to upgrade multiple mounted disks / memory sticks to give a use case. from a security perspective its a nice property that yay does not allow to overwrite the main root partition with some arbitrary sudo, . but in this special case, in a chroot environment, such a check seems not to add any addtional security?

```
# cp /var/cache/pacman/pkg/* /run/media/st/stick1/var/pacman/pkg
# arch-chroot /run/media/st/stick1
# yay -Syu
...
:: Searching AUR for updates...
:: 1 Packages to upgrade.
1  aur/yay  8.1139-1 -> 8.1173.0-1
==> Packages to not upgrade: (eg: 1 2 3, 1-3, ^4 or repo name)
==> 
==> Refusing to install AUR Packages as root, Aborting.
# sudo su - st
$ sudo yay -Syu
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
Error installing repo packages
```

**Comment by alxpettit** [comment]
Morganamilo is right. Try `sudo -u [nonroot user] -i` from inside the chroot, and let us know if you encounter problems!

**Comment by Jguer** [comment]
Closing as a `makepkg` (non)issue
