### ISSUE TITLE
Feature: Add option to skip package compression

### ISSUE THREAD

**Issue by Depau** [Jguer/yay#792]
99.9999% of the times I use yay to build packages that get installed right away. Often I build big packages, such as Oracle Java. They get compressed by makepkg, then decompressed right after by pacman, and this step takes more than every other step.

The compression overhead can be avoided, as pacman can use uncompressed `.pkg.tar` files.

**Comment by Morganamilo** [comment]
See makepkg.conf(5)

**Comment by parkerlreed** [comment]
Yeah just changing the extension in makepkg.conf disables the compression
````
#########################################################################
# EXTENSION DEFAULTS
#########################################################################
#
# WARNING: Do NOT modify these variables unless you know what you are
#          doing.
#
PKGEXT='.pkg.tar'
SRCEXT='.src.tar.gz'
````

**Comment by Depau** [comment]
I didn't know. Thanks for pointing that out. I'll close this issue and use the config instead.
