### ISSUE TITLE
Updating dependencies of a package should be considered

### ISSUE THREAD

**Issue by raneon** [Jguer/yay#793]
#### Issue
Updating the dependencies of a package has no influence. I like yay a lot, but this is the only use case why I still have yaourt around, maybe there is already a solution to update the dependencies, but I couldn't find it. Not all AUR packages are correct and sometimes dependencies need to be updated or there are even cases where building a minimal package is more than enough (example kwin-git).

#### Steps to reproduce
1. yay package
2. Edit pkgbuild and add or remove dependencies
3. Save and continue building the package

#### Output
Actually the dependency changes are ignored, the package will be build with all the original dependencies even though the user changed the dependencies.

**Comment by ghost** [comment]
It still would be a nice feature. But so far I switched to pikaur mostly when I had this issue.
