### ISSUE TITLE
 [Feature request] Support "XferCommand" option in pacman.conf for aur

### ISSUE THREAD

**Issue by amitbha** [Jguer/yay#794]
#### Affected Version

yay v8.1173.0 - libalpm v11.0.1

#### Issue

Sometimes the download speed is too slow, and "~/.config/yay/config.json" has no option to customize download tool, like aria2c, which was configured in pacman.conf as value of "XferCommand" option.

**Comment by Jguer** [comment]
Which download speed are you referring to? Package download? Git clone? PKGBUILD download?

**Comment by amitbha** [comment]
When install "pandoc-bin" from aur, the download speed is around 10KBs.
"htop" shows that yay use curl to download the source package "https://github.com/jgm/pandoc/releases/download/${pkgver}/pandoc-${pkgver}-linux.tar.gz".
So I want to use aria2 for multi-threading download.

**Comment by Morganamilo** [comment]
Stuff in `source=()` is downloaded by makepkg.

**Comment by amitbha** [comment]
> Stuff in `source=()` is downloaded by makepkg.
Tks. It's a upstream problem. 
Can be changed in /etc/makepkg.conf, the "DLAGENTS" option.
