### ISSUE TITLE
Option to not store build files in cache.

### ISSUE THREAD

**Issue by nezumisama** [Jguer/yay#797]
Affected version: yay v8.1173.0 - libalpm v11.0.1

I would like to ask if there's an option to not store build files (downloaded files and pacman packages) in yay's cache folder, and if not, propose such a feature.

Now, I know I can clear the cache manually or with yay -Scc, but that will make yay not know the source files I used to install and the diff option won't work. And I'm pretty sure yay does not need those archives for diff to work, only the source files (PKGBUILD and what not) downloaded from AUR.

My problem with storing those files in the cache folder is that those files can be pretty big. After a single update done with yay the cache folder was over 800MiB.

If this is already solvable in yay with some flag, I apologize for not finding one. I find the man page a bit confusing since it doesn't explain all the details (for example, it doesn't explain whast clean build option does.

**Comment by Jguer** [comment]
You might be looking for
```
--cleanafter
              Remove package sources after successful Install.

              For packages downloaded through git, untracked files are removed with the exception of
              directories. This allows VCS packages to ealily pull an update instead of having to re
              clone the entire repo.
```
This will delete the buildfiles but keep the `PKGBUILD`

**Comment by nezumisama** [comment]
Yes, that seems to the trick. Thanks!
Follow up question: I understand that yay does the build /9via makepkg) in ~/.cache/yay. I'd ideally want yay to use another dir than ~/.cache for building in, and only store the source files (for diff to work). The reason for that is that my home partition is on an SSD, for which I'd like to limit writes and I'd instead prefer builds to be done in /tmp (tmpfs) or on another partition residing on a HDD. Is that doable?

**Comment by Morganamilo** [comment]
>or which I'd like to limit writes

It's pretty pointless to worry about this on modern SSDs

That aside `makepkg.conf(5)` allows configuring all of this.
