### ISSUE TITLE
Is it possible to keep the src directory?

### ISSUE THREAD

**Issue by urbainvaes** [Jguer/yay#798]
When I update a package from a `git` repository, the whole package is rebuilt every time. Is it possible to keep the `src` directory and to recompile only what needs to be recompiled? (Using `makepkg -f`, maybe)

**Comment by parkerlreed** [comment]
That's a makepkg function. 
````
  -e, --noextract  Do not extract source files (use existing $srcdir/ dir)
````

````
yay -S somepackage-git --mflags="-e" --save

````

Then you don't need to specify it again. That saves it to the configuration file.

**Comment by Morganamilo** [comment]
Did you test that? Keeping the src directory is actually default makepkg behaviour (Although yes you are correct in the fact that you'd need to also use -e to avoid re-extracting). Yay explicitly uses -C/-c to clean up src/pkg after it's done and there's no flag to stop that.

So while -e would be going in the right direction It's not possible to use it with yay.

Not that I have tested this but I would assume this is actually impossible even with makepkg. Yes -e would work, but then you can't build anything apart from the current version you previously extracted. If you instead just keep the src dir then the re-extract. Each file is going to get its mtime updated, causing make or whatever to rebuild everything anyway.

**Comment by urbainvaes** [comment]
I don't think the `-e` flag is necessary, and as @Morganamilo said, it would allow building only the version previously extracted. After I install a `git` package once with `makepkg` and delete the `.tar.xz`archive created, the package will not be rebuilt on further call of `makepkg`. So maybe all is needed is an option to prevent yay from cleaning up `src`?

**Comment by Morganamilo** [comment]
I actually give it a go and keeping src around does indeed stop it from recompiling everything. Despite my assumption about the extracting updating mtime.

So such a flag would make sense then. --nocleanbuild I guess?

**Comment by urbainvaes** [comment]
> So such a flag would make sense then. --nocleanbuild I guess?

That would be great. :)

**Comment by HaleTom** [comment]
I would also love to see this.  It really slows down making a large c++ project where the previous `.o` files would be kept inside `$srcdir`.

**Comment by latipun7** [comment]
Why is this closed? Please re-open 🙏

@Morganamilo said:
> I actually give it a go and keeping src around does indeed stop it from recompiling everything. Despite my assumption about the extracting updating mtime.
> 
> So such a flag would make sense then. --nocleanbuild I guess?

It would be great to implement this feature to help to shorten building time. If a build fails, just clean the build via `--cleanmenu`.

Thank you.

**Comment by begin-theadventure** [comment]
I would also like to have this option.
Edit: I found [auracle](https://github.com/falconindy/auracle). It can't build, only clones packages, but it's good enough.
However, I still wonder if there is an AUR helper that can build and keep the files.
Edit2: [Paru](https://github.com/Morganamilo/paru/blob/master/man/paru.conf.5#L153) has it.

**Comment by HaleTom** [comment]
Is the issue bandwidth, disk usage, or build times?

ccache is great for solving the last.

**Comment by latipun7** [comment]
No stale. Waiting https://github.com/Jguer/yay/pull/2272 to be merged 👍
