### ISSUE TITLE
vsc does not respect default repo branch

### ISSUE THREAD

**Issue by maximbaz** [Jguer/yay#80]
I use `antigen-git` AUR package, and I noticed that yay never prompts that an update is available for it. This happens because in [zsh-users/antigen](https://github.com/zsh-users/antigen) the default repo branch is called `develop` and not `master`, while yay always track the master branch:

https://github.com/Jguer/yay/blob/3913673c8c8ae41804a7139ba43201083e200db4/vcs.go#L83-L87

One way to find the default branch is to use the following API call and look for the `default_branch`:

https://api.github.com/repos/zsh-users/antigen

However it is also possible to choose the branch by editing PKGBUILD and appending `#branch=develop` to the `source` parameter, this should also be respected and override the default branch value.

**Comment by Jguer** [comment]
True, vcs branch parsing was rushly made, this should be changed as soon as possible.
