### ISSUE TITLE
Using yay in silent scripts

### ISSUE THREAD

**Issue by shaygover** [Jguer/yay#801]
#### Affected Version
yay v8.1173.0 - libalpm v11.0.1

#### Feature Request
Let's say your writing a silent script that installs some packages and by default you use options like --useask. In this case the script won't be so silent and will need input. So currently I  use --nodiffmenu --noeditmenu --nouseask --nocleanmenu --noupgrademenu. 
Is it possible to add something like --silent that alias all of those?

Thanks

**Comment by Morganamilo** [comment]
what about `>/dev/null`.

**Comment by shaygover** [comment]
That will take care of the output, right? My problem is with the input.

**Comment by Morganamilo** [comment]
Well then there's pacman's --noconfirm.

**Comment by shaygover** [comment]
It'll disable yay questions as well?

**Comment by Jguer** [comment]
Yes, most of the times it will march through to installing and will only break in case of conflicts

**Comment by Morganamilo** [comment]
One thing that does break the trend is sudo. Even with noconfirm it does still prompt for a password. I don't see it as a big deal though because it's actually useful. And if your script has no tty connected to it then sudo is smart enough to error out.
