### ISSUE TITLE
Question: Using yay as a dependency in go project

### ISSUE THREAD

**Issue by patrick-motard** [Jguer/yay#807]
I'm writing a CLI in golang that needs to install both Arch official packages and AUR packages. I could treat yay as a CLI and call it via `exec`, but I thought it would be cool to import it as a dependency to my project and call it's methods directly. Is this possible in yays current state?

Sorry if this is a stupid question. I'm still very new to golang.

**Comment by Jguer** [comment]
It is not a stupid question and is directly connected to #705 since @Morganamilo wants to write an application with somewhat the same requirements as yours. Once that objective is achieved you should be able to call yay as it's own package for a myriad of uses.

**Comment by patrick-motard** [comment]
That's awesome! Thank you! 

Just curious.. the new modules feature being implemented isn't the whole story here right? Without modules i would have expected there to be a yay package i could import into my repo. Modules is nice to get away from GOPATH, but it's always been possible in golang to have a cli application that wraps an importable package right? If so, was yay just not designed in that way and will require some modifications as part of moving to modules?

**Comment by patrick-motard** [comment]
Ah! Okay yeah that makes more sense hah

**Comment by Jguer** [comment]
Exactly :smile: , just searched for modules and misreferenced it

**Comment by Bricklou** [comment]
I'm interessed too about this possibility. But it seem that it's been that this post become a bit old.
