### ISSUE TITLE
Run cache clean from script

### ISSUE THREAD

**Issue by rightaway** [Jguer/yay#808]
If I run `yay -Scc --noconfirm` it doesn't clear the directories whose default answer is `N`. How can I clear the cache from a script? Could an option be added for this?

```
Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove ALL files from cache? [y/N]
```

**Comment by parkerlreed** [comment]
You can use `yes`

````
[parker@stealth ~]$ yes | yay -Scc

Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove ALL files from cache? [y/N] y
removing all files from cache...

Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n] y
removing unused sync repositories...

Build directory: /home/parker/.cache/yay
==> Do you want to remove ALL AUR packages from cache? [Y/n] removing AUR packages from cache...
````

I basically spams y and a newline.

**Comment by Jguer** [comment]
> Does pacman -Scc work with noconfirm?

It does not. We follow the same philosophy of noconfirm following the default answer. Wrapping pacman with yes on noconfirm would also be bad fashion

**Comment by elgs** [comment]
> [parker@stealth ~]$ yes | yay -Scc

This works when it's run from command line or a script. But it doesn't work in a systemd service:

```
ExecStart=echo yes|/usr/bin/yay -Scc
```
The line above in a systemd service doesn't work.

**Comment by grandchild** [comment]
@elgs service file `Exec*` lines are not a shell. If you want piping and all those cool things, then get a shell first:

```
ExecStart=/usr/bin/bash -c 'echo yes | /usr/bin/yay -Scc'
```

**Comment by elgs** [comment]
@grandchild thank you. That works!
