### ISSUE TITLE
Command to just show what's available to upgrade

### ISSUE THREAD

**Issue by rightaway** [Jguer/yay#813]
I have a script to update my system and I'd like to preview what files are available to update. I'd like a flag I could add (something like `--show-only`) that would just show what's available but not attempt to upgrade. The equivalent of `yay -Syyu --combinedupgrade` but without asking for any user input or doing anything other than showing what's out of date. It could exit with a non-zero exit code when there's anything available to upgrade.

**Comment by Jguer** [comment]
How about `yay -Qu`? :smile:

**Comment by Jguer** [comment]
Also adding to this avoid using `yay -Syy` everytime you update, it's mostly a waste of bandwidth

**Comment by rightaway** [comment]
It's still missing some information. For example 
- `Out Of Date AUR Packages:`
- `:: 25 Packages to upgrade.`
- The great formatting and coloring (different columns, colors based on where the package resides and how different the versions are).

`yay` already has a fantastic way of displaying upgrades, there should be a way to just tap into exactly that and display it :)

**Comment by alerque** [comment]
Out of date AUR packages are displayed in `yay -Ps`.
