### ISSUE TITLE
noconfirm skipped some parts of the rebuild process

### ISSUE THREAD

**Issue by vansoest** [Jguer/yay#820]
#### Affected Version
$ yay -V 
yay v8.1173.0 - libalpm v11.0.1

#### Issue
The package `perl-opengl` of the AUR built with `yay --noconfirm` doesn’t work correcty.
Some processes are skipped e.g. the  **check()** method inside the PKGBUILD.

Without `--noconfirm` the package would rebuild normally.

#### Steps to reproduce and outputs
1. $ yay perl-opengl             
[yay.log](https://github.com/Jguer/yay/files/2637579/yay.log)
2. $ yay --noconfirm perl-opengl
[yay_noconfirm.log](https://github.com/Jguer/yay/files/2637578/yay_noconfirm.log)

**Comment by Jguer** [comment]
On my side the package built correctly.
Your logs suggest you ran `yay -S perl-opengl` the package was built and then you ran `yay -S perl-opengl --noconfirm` which just made yay get the built package from cache as evidenced by `==> perl-opengl-0.70-2 already made -- skipping build` l18

```
check() {
  cd "$srcdir/$_distdir"
  echo "" > test.pl # Disable random X11 windows
  if [ -z "$DISPLAY" ]; then
    warning "Empty \$DISPLAY - falling back to xvfb-run (xorg-server-xvfb)"
    xvfb-run -a -s "+extension GLX -screen 0 1280x1024x24" make test
  else
    make test
  fi
}
```

Looking at the `PKGBUILD` itself it only has a build,package and check method and it doesn't even seem to affect the built package. I may need some more help on understanding the issue.

**Comment by Morganamilo** [comment]
Like @Jguer said, the package was cached so no need to rebuild it.
