### ISSUE TITLE
"edit" functionality should run before checking dependencies

### ISSUE THREAD

**Issue by tiiiecherle** [Jguer/yay#821]
#### Affected Version

yay 8.1173.0-1

#### Issue
Dependencies are checked before giving the option to edit pkgbuild and so the PKGBUILD of z-push can not be installed. It should be possible to edit the PKGBUILD before checking dependencies. Thanks

#### Steps to reproduce

`yay -S --editor=pluma --editmenu z-push`

#### Output

:: There are 2 providers available for libvmime:
:: Repository AUR
    1) libvmime 2) zarafa-libvmime 

Enter a number (default=1): 1
==> Error: Could not find all required packages:
    xapian-core=1:1.4.7 (Wanted by: z-push -> kopano-core -> php-xapian)

**Comment by tiiiecherle** [comment]
o.k., then I think it could be a good idea to implement a feature like ---edit-first to make it possible to edit the PKGBUILD upfront.

Is there another workaround?

**Comment by Jguer** [comment]
The FAQ is not clear on this but yay does not source dependencies from the `PKGBUILD`, it is done via the `AUR RPC` therefore the order of operations does not matter
