### ISSUE TITLE
gcc-go does not support go mod

### ISSUE THREAD

**Issue by Jguer** [Jguer/yay#824]
#### Affected Version

yay v9.0.0

#### Issue

gcc-go in core ( `go version go1.10.3 gccgo (GCC) 8.2.1 20181127 linux/amd64`) does not have support for go mod and as such `yay v9.0.0` is incompatible for a simple question of tooling.

The original plan was to remove the vendor directory and let go mod handle dependencies on user install, as a more sane approach than having external modules committed to the repo.

Seeing this I believe there are three possible ways to proceed:

1. Remove go mod and wait for feature parity

2. Specify an alternative make method when gcc-go is detected

3. Abandon all support for gcc-go (my least favourite)

**Comment by Jguer** [comment]
Closing this as it's temporarily solver for gcc-go users

**Comment by Morganamilo** [comment]
There goes the makefile finally being bmake compatible.

Do you know if gccgo will support modules eventually?

**Comment by Jguer** [comment]
I know, I know. I thought about that. But since it's only temporary and I think the gccgo population is bigger than the bmake population sacrifices had to be made :laughing:

**Comment by Jguer** [comment]
Modules are part of the go specification so they should be supported once `gcc-go` is updated. The `go mod` tool is provided by gofrontend

> The master sources for the gccgo frontend may be found at https://go.googlesource.com/gofrontend. They are mirrored at https://github.com/golang/gofrontend.

[go mod get](https://github.com/golang/gofrontend/blob/7b25b4dff4778fc4d6b5d6e10594814146b3e5dd/libgo/go/cmd/go/internal/modget/get.go) so support is there, but since gcc-go can not be built separately from gcc it seems will only land with `gcc 9.0`
