### ISSUE TITLE
Failure to pass validy check and clean build option

### ISSUE THREAD

**Issue by seafox** [Jguer/yay#828]
#### Affected Version
at least with few latest versions, incl.
yay v9.0.1 - libalpm v11.0.1

#### Issue
sometimes some packages updates like `yay -Su crow-translate` (just the recent example I had) will fail

**Edit**: Clean build resolves the issue. If that's not default mode, maybe after validation failure the helper could ask to perform a clean build for the package with default answer Yes? Maybe another option for config?

**Comment by seafox** [comment]
Maybe the logic for reruns would be No when batched (-noconfirm) and interactive Ask with default Yes otherwise?

**Comment by Morganamilo** [comment]
Clean building without the user specifically asking for it is not going to happen. Closing this for #848.
