### ISSUE TITLE
Time part info is missing

### ISSUE THREAD

**Issue by seafox** [Jguer/yay#831]
#### Affected Version
yay v9.0.1.r0.gd3a9082 - libalpm v11.0.1

#### Issue
The datetime information from `-Si` alike commands contains only ISO formatted date, the time information is absent. See the attached screenshot. Other popular AUR helpers do not have this issue.

#### Possible resolution
It would be reasonable to have a datetime format according to local system and user settings (like `trizen` does), with a safe fail-back displaying format, either in accordance with `pacman` look, or, at least, as a standard ISO format with UTC summertime independent timezone.

![yay1](https://user-images.githubusercontent.com/9025690/49829801-0aa14e80-fd98-11e8-8674-a5363ba1b867.png)
![yay2](https://user-images.githubusercontent.com/9025690/49829812-1260f300-fd98-11e8-86cf-a5105362551d.png)

**Comment by parkerlreed** [comment]
Seems possible considering the rpc returns unix epoch

https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=yay

````
{"version":5,"type":"multiinfo","resultcount":1,"results":[{"ID":566447,"Name":"yay","PackageBaseID":115973,"PackageBase":"yay","Version":"9.0.1-3","Description":"Yet another yogurt. Pacman wrapper and AUR helper written in go.","URL":"https:\/\/github.com\/Jguer\/yay","NumVotes":404,"Popularity":72.50214,"OutOfDate":null,"Maintainer":"jguer","FirstSubmitted":1475688004,"LastModified":1544191603,"URLPath":"\/cgit\/aur.git\/snapshot\/yay.tar.gz","Depends":["pacman>=5.1","sudo","git"],"MakeDepends":["go"],"License":["GPL"],"Keywords":["AUR","go","helper","pacman","wrapper"]}]}
````

**Comment by Morganamilo** [comment]
The reason it is just a date is for inline printing:
```
aur/downgrader 2.0.0-3 (+237 4.11%) (Out-of-date 2018-06-07) (Installed)
```
And rather than have two different formats, this one was reused for -Si.

If you want to change the format to be a full datetime make a PR, just make sure to keep the inline variant as it.
