### ISSUE TITLE
zsh: How to make commands appear in completions after install

### ISSUE THREAD

**Issue by fabriken** [Jguer/yay#833]
@## Affected Version

#### Issue

Hi there, 

I'm new here so hope this is the correct way of making a suggestion, my apologies if not.
I wonder if it's possible to add a command to refresh the shell after yay has finished installing a package?

I'm using zsh shell for example and every time a new install is made I need to run the command zsh to refresh the shell so that the newly installed software can be found by the shell.

Example:

yay -Sy firefox
Wait til install is finished.
Then in the shell when typing "firefo" and pressing tab to auto complete it doesn't work until I run "zsh" first.
I know this is a simple thing to do for myself after installing something but it would be nicer I think for especially new user of linux to be able to instantly see that the install was completed properly.

Thanks guys for the awesome work in creating the best AUR helper out there!

**Comment by Morganamilo** [comment]
This can be done with a simple shell function. Also I believe the command you want is `compinit` rather than starting a new shell session on top of your existing one.

Also don't run `-Sy foo` https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported

**Comment by fabriken** [comment]
Thanks Y'all this worked great and thanks for the advice regarding "yay -Sy". :)
