### ISSUE TITLE
Feature Request: default sorting in configuration file

### ISSUE THREAD

**Issue by pztrn** [Jguer/yay#835]
yay v9.0.1 - libalpm v11.0.1

ATM yay sorts packages when searching by votes. For me it is counterintuitive and blows my brain :). I prefer to sort by name by default. Can you please add related settings in configuration file so I can set sorting by name by default?

**Comment by Morganamilo** [comment]
```
--sortby <votes|popularity|id|baseid|name|base|submitted|modified>
              Sort AUR results by a specific field during search.
```

**Comment by pztrn** [comment]
Okay, this is again counterintuitive. Is there any documentation regarding configuration file out there?

**Comment by Morganamilo** [comment]
The recommended way is to apply config options by setting the flag and saving it.

```
yay --sortby name --save
```

The actual config file is simple json. This is also noted in the man page, as well as an example use of the `--save` flag.

**Comment by pztrn** [comment]
Okay, thanks for clarification. One more question - is there any way to sort packages by names ascending (a-z)? It's descending (z-a) currently. Found nothing in man about that.

**Comment by Morganamilo** [comment]
`--topdown` and `--bottomup` are effectively this.
