### ISSUE TITLE
Print path of package file once it's built

### ISSUE THREAD

**Issue by stacktracer** [Jguer/yay#839]
#### Affected Version

yay v9.0.1 - libalpm v11.0.1

#### Issue
It would be helpful in some situations (e.g. #147) for yay to print (to stdout) the path of the built package file. That way if the pacman install command fails for some reason, it's obvious where to find the package file if you want to run pacman manually.

**Comment by Jguer** [comment]
> Rule of Silence: When a program has nothing surprising to say, it should say nothing.

I think printing every time is too verbose, we can check for `pacman -U`s error though and print it then
