### ISSUE TITLE
Provide alternative cache directory

### ISSUE THREAD

**Issue by z3ntu** [Jguer/yay#840]
#### Affected Version

yay v9.0.1 - libalpm v11.0.1

#### Issue

It would be nice if you could set the cache dir to something different than `~/.cache/yay` and I couldn't find an option to do that from quickly reading through the code. For example pacaur has the environment variable `AURDEST` that lets you specificy a different directory to throw the PKGBUILDs in (which is important because I have my `~/.cache` on a tmpfs, but I'd like to save the PKGBUILDs)

Side note: There's a typo in `cachdir` in `main.go`, and I think that that is dead code

**Comment by Jguer** [comment]
If you use `yay -Syu --builddir=<your dir> --save` the pkgbuilds should be thrown in there if I'm not mistaken

**Comment by z3ntu** [comment]
Yep, that is partially what I want. But still `completion.cache` and `vcs.json` (according to the man page) will be lost on reboot.

**Comment by Jguer** [comment]
True, I guess changing `$XDG_CACHE_DIR` is not really an option :laughing:. We are a bit in the middle of refactoring configuration so I'll probably slap an `enhancement` label on it and tie it with those changes.

**Comment by z3ntu** [comment]
Thanks!

**Comment by vonbirdie** [comment]
I've got my /home mounted with noexec causing build errors for some aur packages. Using `yay --builddir=/tmp//yay --save` is a good workaround though.

**Comment by Arzte** [comment]
For anyone coming across this wanting this behavior, for all makepkg based builds, the makepkg variable ``BUILDDIR`` is honored, so you can set your makepkg builddir to ``BUILDDIR=/tmp/makepg`` and still keep PKGBUILDs.

I've tried it with a few package installs like linux-lqx and it seems to work fine.

**Comment by Anonymo** [comment]
I get this: stat /home/user/.cache/yay: permission denied

**Comment by kalitara** [comment]
I had this problem with yay -Sc. I turns out that I had this set:

export AURDEST=/tmp

I'm guessing that the systemd-private directories were getting in the way?

**Comment by RubenKelevra** [comment]
I feel like the build and the cache directory should be split. It's fine to store the cached content in $home, but compiling should happen in a temporary directory.

**Comment by nesv** [comment]
To add my two cents' worth in addition to @RubenKelevra's point, the one thing I would really appreciate from `yay`, is if it would honour the `TMPDIR` environment variable when it does builds.

yay seems pretty fixated on using `/tmp` for builds, but for reasons I would rather not get into here, the systems I'm running this on have `/tmp` mounted with the `noexec` flag. This isn't an issue for most builds, but some packages require being able to exec something in the build directory, and the `noexec` flag causes this to fail. 

It would be nice if I could run something like `TMPDIR=/var/tmp yay ...` for those one-off builds that require being able to exec something in the build dir.

**Comment by ZLima12** [comment]
At the very least, honoring `XDG_CACHE_HOME` would be great. Currently yay is the only thing in my `~/.cache` directory.
