### ISSUE TITLE
Error a failure occurred in build

### ISSUE THREAD

**Issue by KaMiila** [Jguer/yay#845]
makepkg -si
==> Making package: yay 9.0.1-3 (Sun 23 Dec 2018 10:00:35 PM PST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found yay-9.0.1.tar.gz
==> Validating source files with sha1sums...
    yay-9.0.1.tar.gz ... Passed
==> Extracting sources...
  -> Extracting yay-9.0.1.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
go build -v -ldflags '-s -w -X main.version=9.0.1' -o yay -mod=vendor
flag provided but not defined: -mod
usage: build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
make: *** [Makefile:51: build] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by c0d3z3r0** [comment]
@KaMiila try a `yay -Sy go yay-git`

**Comment by Morganamilo** [comment]
Yes, go needing to update does sound like likely. That's no reason to use `-Sy` though https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported

**Comment by c0d3z3r0** [comment]
Then do a `pacman -Syu`

**Comment by Jguer** [comment]
Closing this one as it's due to out of date `go` compiler

**Comment by frod0r** [comment]
I had the same problem, but my go-installation was up to date. My fault was, that I did not have the gcc compiler installed on that computer, but after installing it I could update yay without problems. Maybe that helps

**Comment by Jguer** [comment]
That makes enough sense since yay depends on cgo for `go-alpm` (although when using AUR `base-devel` is always assumed as installed and it includes `gcc`) but in this case `-mod=vendor flag provided but not defined: -mod` shows that the compiler frontend doesn't have `-mod` which was introduced in `go1.11`
