### ISSUE TITLE
[Request] Add armv7h binary release asset

### ISSUE THREAD

**Issue by wilriker** [Jguer/yay#846]
Hi!

I really like `yay` and use it on all my Arch machines via the `aur/yay-bin` package.

I also have two Raspberry Pi 3 at home which run Arch Linux. But since there is no `armv7h` binary release I have to fall back to `aur/yay` which of course has Go as a dependency to compile `yay`. This puts a real burden onto these little things. ;-)

So I kindly like to ask for a release for this arch.

Thanks
Manuel

**Comment by wilriker** [comment]
You can select the architecture Go compiles to via environment variables. Built-in cross-compiling.

`GOOS` selects the target OS and `GOARCH` the CPU architecture. I don't remember off hand what you have to set `GOARCH` to for `armv7h` but that should be easy to find out.

**Comment by Jguer** [comment]
:laughing: Things that use cgo are not as straightforward as just using builtin go. I've had some limited success with the arm gcc cross compiler and some header and library extractions from arm images but it's very hacky

**Comment by Jguer** [comment]
I had added aarch64 binaries as an experiment using QEMU docker builds. If anyone has the hardware to test them on `yay-bin`. If they are working correctly I may also add the specific ones for Rpi2

**Comment by wilriker** [comment]
Unfortunately I cannot test these because I run ARMv7 build on my Rpi3s since I require overlays (and last time I checked overlays were not supported in aarch64 build).

**Comment by Jguer** [comment]
@wilriker Ok, I'll try and add an `armv7h` release as it seems it's not as uncommon as I thought. `aarch64` should already cover most heavier duty ARM machines

**Comment by wilriker** [comment]
Thanks!

**Comment by wilriker** [comment]
And once more thanks for adding `armv7h` to `yay-bin`. Finally I could drop `go` on all my RPi3s. :-)

**Comment by Jguer** [comment]
Just getting it to build nicely on x86_64 hardware was the issue, it was something I really wanted to get solved as well
