### ISSUE TITLE
Yay can't install linux-pf

### ISSUE THREAD

**Issue by BrianAllred** [Jguer/yay#849]
#### Affected Version
yay v9.0.1 - libalpm v11.0.1

#### Issue
Yay will not install `linux-pf`. Entering `yay -S linux-pf` and hitting enter will result in a blinking cursor. 

#### Steps to reproduce
1. `yay -S linux-pf`

#### Output
Nothing

**Comment by AladW** [comment]
It's the natural consequence from trying to do too much. The core of aurutils dependency solving is 50 lines of shell and I've never encountered all these weird issues yay, aurman, pikaur etc. have been struggling with for nearly a year now.

**Comment by Morganamilo** [comment]
Assuming this was fixed by #866. If not feel free to repoen.
