### ISSUE TITLE
"net/http: TLS handshake timeout" when searching AUR for updates

### ISSUE THREAD

**Issue by hckr** [Jguer/yay#850]
#### Affected Version
yay v7.887.r4.g77a5cf5

#### Issue
It's not reproducible every time, but today it happened for me multiple times in a row, so I thought you might want to look into it and possibly increase the timeout if this is possible. When I open the URL provided in the error, Firefox loads it (JSON response) successfully every time.

#### Steps to reproduce

1. yay -Syu

#### Output

> $ yay -Syu
> :: Synchronizowanie baz danych z pakietami…
>  core jest aktualne
>  extra jest aktualne
>  community jest aktualne
>  multilib jest aktualne
>  herecura jest aktualne
>  sublime-text jest aktualne
> :: Searching AUR for updates...
> Get https://aur.archlinux.org/rpc.php?arg%5B%5D=acroread&arg%5B%5D=alacryd&arg%5B%5D=android-ndk&arg%5B%5D=android-sdk-25.2.5&arg%5B%5D=android-sdk-build-tools-24.0.3&arg%5B%5D=android-sdk-ndk-symlink&arg%5B%5D=android-sdk-platform-tools&arg%5B%5D=android-studio&arg%5B%5D=arenatracker-bin&arg%5B%5D=attica-git&arg%5B%5D=attica-qt4&arg%5B%5D=breeze-kde4&arg%5B%5D=cerebro-git&arg%5B%5D=chromium-widevine&arg%5B%5D=colobot-gold-data&arg%5B%5D=colobot-gold-music&arg%5B%5D=directfb&arg%5B%5D=dotnet-sdk-2.0&arg%5B%5D=dvdrip&arg%5B%5D=extra-cmake-modules-git&arg%5B%5D=firefox-nightly-pl&arg%5B%5D=flowblade&arg%5B%5D=fontbuilder&arg%5B%5D=fselect&arg%5B%5D=fsharp&arg%5B%5D=games_nebula&arg%5B%5D=gegl02&arg%5B%5D=gksu&arg%5B%5D=gnethogs&arg%5B%5D=gnu-cobol&arg%5B%5D=godot-bin&arg%5B%5D=google-cloud-sdk-minimal&arg%5B%5D=gpgmepp&arg%5B%5D=gstreamer0.10&arg%5B%5D=gstreamer0.10-base&arg%5B%5D=haskell-cmark&arg%5B%5D=haskell-semigroups&arg%5B%5D=heroku-toolbelt&arg%5B%5D=htmlcxx&arg%5B%5D=jdownloader2&arg%5B%5D=jekyll&arg%5B%5D=js&arg%5B%5D=js17&arg%5B%5D=kactivities-git&arg%5B%5D=karchive-git&arg%5B%5D=kauth-git&arg%5B%5D=kbookmarks-git&arg%5B%5D=kcalcore-git&arg%5B%5D=kcmutils-git&arg%5B%5D=kcodecs-git&arg%5B%5D=kcompletion-git&arg%5B%5D=kconfig-git&arg%5B%5D=kconfigwidgets-git&arg%5B%5D=kcontacts-git&arg%5B%5D=kcoreaddons-git&arg%5B%5D=kcrash-git&arg%5B%5D=kdbusaddons-git&arg%5B%5D=kde-l10n-pl&arg%5B%5D=kdebase-kdepasswd&arg%5B%5D=kdebase-lib&arg%5B%5D=kdebase-runtime&arg%5B%5D=kdeclarative-git&arg%5B%5D=kdecoration-git&arg%5B%5D=kded-git&arg%5B%5D=kdelibs&arg%5B%5D=kdelibs4support-git&arg%5B%5D=kdesignerplugin-git&arg%5B%5D=kdewebkit-git&arg%5B%5D=kdoctools-git&arg%5B%5D=kemoticons-git&arg%5B%5D=kglobalaccel-git&arg%5B%5D=kguiaddons-git&arg%5B%5D=ki18n-git&arg%5B%5D=kiconthemes-git&arg%5B%5D=kidletime-git&arg%5B%5D=kinit-git&arg%5B%5D=kio-git&arg%5B%5D=kirigami-git&arg%5B%5D=kitemmodels-git&arg%5B%5D=kitemviews-git&arg%5B%5D=kjobwidgets-git&arg%5B%5D=knewstuff-git&arg%5B%5D=knotifications-git&arg%5B%5D=kpackage-git&arg%5B%5D=kparts-git&arg%5B%5D=kplotting-git&arg%5B%5D=kscreenlocker-git&arg%5B%5D=kservice-git&arg%5B%5D=ktextwidgets-git&arg%5B%5D=kunitconversion-git&arg%5B%5D=kwallet-git&arg%5B%5D=kwaterfoxhelper&arg%5B%5D=kwayland-git&arg%5B%5D=kwidgetsaddons-git&arg%5B%5D=kwin-git&arg%5B%5D=kwindowsystem-git&arg%5B%5D=kxmlgui-git&arg%5B%5D=lash&arg%5B%5D=lcms&arg%5B%5D=leiningen&arg%5B%5D=lgogdownloader&arg%5B%5D=lib32-gperftools&arg%5B%5D=lib32-libgnutls28&arg%5B%5D=lib32-libstdc%2B%2B5&arg%5B%5D=lib32-libtxc_dxtn&arg%5B%5D=lib32-nettle4&arg%5B%5D=lib32-rtmpdump&arg%5B%5D=lib32-tcp_wrappers&arg%5B%5D=libakonadi-qt4&arg%5B%5D=libcatch-cpp-headers&arg%5B%5D=libgksu&arg%5B%5D=libkactivities4&arg%5B%5D=libkcddb4&arg%5B%5D=libkexiv2_4&arg%5B%5D=libkgapi-git&arg%5B%5D=libkscreen4&arg%5B%5D=libqzeitgeist&arg%5B%5D=libspatialindex-git&arg%5B%5D=libtxc_dxtn&arg%5B%5D=lighttable-git&arg%5B%5D=llvm39-libs&arg%5B%5D=manjaro-features&arg%5B%5D=mhwd-nvidia-304xx&arg%5B%5D=mingw-w64-binutils&arg%5B%5D=mingw-w64-bzip2&arg%5B%5D=mingw-w64-cmake&arg%5B%5D=mingw-w64-configure&arg%5B%5D=mingw-w64-crt&arg%5B%5D=mingw-w64-expat&arg%5B%5D=mingw-w64-flac&arg%5B%5D=mingw-w64-freetype2&arg%5B%5D=mingw-w64-gcc&arg%5B%5D=mingw-w64-gettext&arg%5B%5D=mingw-w64-glew&arg%5B%5D=mingw-w64-glib2&arg%5B%5D=mingw-w64-graphite&arg%5B%5D=mingw-w64-harfbuzz&arg%5B%5D=mingw-w64-headers&arg%5B%5D=mingw-w64-libffi&arg%5B%5D=mingw-w64-libiconv&arg%5B%5D=mingw-w64-libjpeg&arg%5B%5D=mingw-w64-libogg&arg%5B%5D=mingw-w64-libsndfile&arg%5B%5D=mingw-w64-libunistring&arg%5B%5D=mingw-w64-libvorbis&arg%5B%5D=mingw-w64-openal&arg%5B%5D=mingw-w64-pcre&arg%5B%5D=mingw-w64-pkg-config&arg%5B%5D=mingw-w64-sfml&arg%5B%5D=mingw-w64-termcap&type=info&v=5: net/http: TLS handshake timeout

**Comment by hckr** [comment]
It happens also with much simpler requests, e.g.:
> yay -S diskmonitor
> Get https://aur.archlinux.org/rpc.php?arg%5B%5D=diskmonitor&type=info&v=5: net/http: TLS handshake timeout

I understand it might be happening because of the quality of my internet connection, but I think it should work correctly (wait longer) regardless.

**Comment by Jguer** [comment]
We are using the default `http` client which has these settings:
```

var DefaultTransport RoundTripper = &Transport{
        Proxy: ProxyFromEnvironment,
        DialContext: (&net.Dialer{
                Timeout:   30 * time.Second,
                KeepAlive: 30 * time.Second,
                DualStack: true,
        }).DialContext,
        MaxIdleConns:          100,
        IdleConnTimeout:       90 * time.Second,
        TLSHandshakeTimeout:   10 * time.Second,
        ExpectContinueTimeout: 1 * time.Second,
}
```

10s for a TLS handshake seems more than enough in my opinion.
Either way, if you still think it's an issue, you'll want to create an issue on https://github.com/mikkeloscar/aur which handles our AUR requests and I'm sure @mikkeloscar will weight in on it.

**Comment by iujisato** [comment]
Weird, I'm having the same problem on a fresh install of a manjaro dist. 

It's pretty weird, I have like 5 devices on my network and just the `arch` got `TLS handshake timeout` on domains `*.archlinux.org`. 

This problem is happening on `yay` and on the default `firefox` application, but it's not happening on `ping`...

Well, it's not a problem from `yay` but this issue was the only one that seemed to be similar to mine lol

**Comment by hckr** [comment]
It's a long shot – do you happen to use KDE? If so, try killing baloo. It is possible that in my case it did so many IO on disk and slowed everything else down this way. But it might also be a weird coincidence that the problem resolved itself for me.

**Comment by iujisato** [comment]
@hckr I've tried a gnome desktop environment and a KDE. Both have the same problems.
Upon further investigation I discovered that this happens only inside my HOME network, and if I manually add the IP for aur my browser can access it withou any problems...

So I just changed lots and lots of DNS configs and I cant solve this issue, since this is happening even on live cd's...

My last resort would be a factory reset on my wireless router and redo all my network to check if I can advance with it.

**Comment by languitar** [comment]
I am facing this issue on an old raspberry pie 1. Strangely, the URL that caused the timeout is always immediately usable when trying this with curl.

**Comment by RobertBonfada** [comment]
I was having this issue when I try to update VSCode, then I've closed VSCode and worked nice!

**Comment by lucasvazq** [comment]
`yay -S google-chrome` same story, but `yay -Ss google-chrome` works

**Comment by lucasvazq** [comment]
> `yay -S google-chrome` same story, but `yay -Ss google-chrome` works

Fixed.
I had misconfigured the time of my system

**See your own datetime**
`sudo hwclock --verbose`

**Fix it**
`sudo ntpd -qg`
