### ISSUE TITLE
"makepkg -si" requires "make" and "fakeroot"

### ISSUE THREAD

**Issue by johannes87** [Jguer/yay#852]
But neither "make" or "fakeroot" are automatically installed when invoking "makepkg -si"

**Comment by parkerlreed** [comment]
`base-devel` is assumed to be installed... You can't just expect `makepkg` to work right away. Anyways, this isn't even related to `yay`

**Comment by johannes87** [comment]
I see. I didn't read the Wiki before. Thanks!

**Comment by johannes87** [comment]
I still wonder why makepkg is installed on my system when it can't be used without base-devel?
