### ISSUE TITLE
Default config file is not mentioned in readme

### ISSUE THREAD

**Issue by ixevix** [Jguer/yay#855]
#### Affected Version

current

#### Issue
I can not find "config" with ctrl + f from readme on GitHub.

#### Suggest
Improve documentation to mention default config file location.

**Comment by Jguer** [comment]
It is mentioned in the manpage, so from my point of view the documentation is present. We might be switching config architecture soon so I would stay this may suffice for now, if you feel it's not enough feel free to amend the README.MD and create a pull request :smile: .

`man 8 yay`
``` 
CONFIG DIRECTORY
              The config directory is $XDG_CONFIG_HOME/yay/. if $XDG_CONFIG_HOME is unset, the config
              directory will fall back to $HOME/.config/yay.

              config.json Is used to store all of Yay's config options. Editing this file should be
              done through Yay, using the options mentioned in PERMANENT CONFIGURATION SETTINGS.
```

**Comment by ixevix** [comment]
Fine. Even though the man page is not mentioned either.

**Comment by tunnckoCore** [comment]
And yet, it example config.json file won't be bad. :)

Seems like the directory is empty and the config file does not get created.

**Comment by Ashark** [comment]
Yes, the directory is empty and there is no example in documentation.
I have found #697, saying how to save option for config. For example, I want to make "--editmenu" option permanent. So I run `yay --editmenu --save` and then /home/andrew/.config/yay/config.json file is created with the following content:

```json
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/andrew/.cache/yay",
	"absdir": "/home/andrew/.cache/yay/abs",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": true,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false
}

```
This is for yay v10.3.1 - libalpm v13.0.1

**Comment by ninetailedtori** [comment]
If this has not changed for 6 years? It might be worth moving it to the base README, or work on a separate configuration README along with a link to said info on the main README would probably be useful. Besides, a config file is a lot easier for batch menu edits, and is also what most users are expecting as the config system.
