### ISSUE TITLE
Yay does not report correct error when `--overwrite` is used without a value.

### ISSUE THREAD

**Issue by KSXGitHub** [Jguer/yay#858]
#### Affected Version

yay v9.0.1 - libalpm v11.0.2

(I use `yay-bin` in AUR)

#### Issue

Yay does not report correct error when `--overwrite` is used without a value.

#### Steps to reproduce

1. Uninstall `deepin-file-manager` if it exists
2. Run `sudo touch /usr/bin/dde-file-manager`
3. Run `yay -S deepin-file-manager --overwrite` (with overwrite value intentionally left out)

#### Output

**Expected:**

```
yay: option '--overwrite' requires an argument
```

**Received:**

<pre>resolving dependencies...
looking for conflicting packages...

<b>Packages (1)</b> deepin-file-manager-1:4.7.4.3-1

<b>Total Installed Size:</b>  16.52 MiB

<font color="#729ECF"><b>::</b></font><b> Proceed with installation? [Y/n] </b>y
(1/1) checking keys in keyring                                                                         [############################################################] 100%
(1/1) checking package integrity                                                                       [############################################################] 100%
(1/1) loading package files                                                                            [############################################################] 100%
(1/1) checking for file conflicts                                                                      [############################################################] 100%
<font color="#EF2828"><b>error: </b></font>failed to commit transaction (conflicting files)
deepin-file-manager: /usr/bin/dde-file-manager exists in filesystem
Errors occurred, no packages were upgraded.
Error installing repo packages
</pre>

**Comment by KSXGitHub** [comment]
@Morganamilo The template is only for reporting **bugs**, this is a **suggestion**.

**Comment by KSXGitHub** [comment]
@Morganamilo Updated, in turns out to be partly my own fault, but `yay` should've report correct error message (like `pacman` did)

**Comment by KSXGitHub** [comment]
> Anyway, if you're still talking about the older version your point is moot.

I use v9.0.1, is this the latest stable version?

> If this is a problem with the current version then you're going to need to elaborate.

I want yay to print an error message when `--overwrite` is provided without a value (i.e. user gives just `--overwrite` instead of full `--overwrite <blob>`), but yay proceed to install anyway, leading misleading error message.

**Comment by Morganamilo** [comment]
The new proposed system does that. Although whether that actually gets merged is for another discussion. It might be easy to implement here though.
