### ISSUE TITLE
Support for Esc and Ctrl-D in yogurt mode

### ISSUE THREAD

**Issue by notramo** [Jguer/yay#86]
It should exit the program if the readline buffer is only whitespace in yogurt mode, and the user press `Escape` or `Control-d`.

**Comment by maximbaz** [comment]
To be more precise, when nothing was typed yet, <kbd>Ctrl+d</kbd> exits as expected:

![image](https://user-images.githubusercontent.com/1177900/34578936-2853b5a8-f187-11e7-8791-f71f8a13918f.png)

When there is something typed, I have to press <kbd>Ctrl+d</kbd> twice, and this just ungracefully terminates the app.
