### ISSUE TITLE
Is it possible to change the description color ?

### ISSUE THREAD

**Issue by Spheerys** [Jguer/yay#868]
Is it possible to change the package description color ?
I thing a small color difference between the package name and the package description (for example white/light grey) will improve the readibility of the package listing result.
If I remember, yaourt use two colors for package name and package description, and I miss it ^^

**Comment by Morganamilo** [comment]
Do you mean during info or search? Search has the description in bold which is (kind of) a different colour. And for info we just mimic pacman.

**Comment by Spheerys** [comment]
I mean during search.
I didn't activate the bold on my terminal (terminator), I don't know why...
Now it's done and the result is nicer :)
So you can close my issue :)
