### ISSUE TITLE
Improper Exception Handling

### ISSUE THREAD

**Issue by anti4r** [Jguer/yay#869]
yay v9.1.0 - libalpm v11.0.2

Title pretty much explains it. Got an improper error message with a failed `yay -Syu --aur`.

`yay -Syu --aur`

`:: Searching AUR for updates...`
`Get https://aur.archlinux.org/rpc.php?arg%5B%5D=cava&arg%5B%5D=discord&arg%5B%5D=downgrade&arg%5B%5D=drjava&arg%5B%5D=firefox-nightly&arg%5B%5D=libc%2B%2B&arg%5B%5D=libc%2B%2Babi&arg%5B%5D=libspotify&arg%5B%5D=lightdm-webkit-theme-aether&arg%5B%5D=mopidy-soundcloud&arg%5B%5D=mopidy-spotify&arg%5B%5D=mopidy-youtube&arg%5B%5D=oh-my-zsh-git&arg%5B%5D=package-query&arg%5B%5D=polybar&arg%5B%5D=pop-icon-theme-git&arg%5B%5D=python2-pafy&arg%5B%5D=python2-pyspotify&arg%5B%5D=skypeforlinux-preview-bin&arg%5B%5D=slack-desktop&arg%5B%5D=tor-browser-en&arg%5B%5D=ttf-ancient-fonts&arg%5B%5D=ttf-ms-fonts&arg%5B%5D=vim-plug&arg%5B%5D=vivaldi&arg%5B%5D=vokoscreen&arg%5B%5D=xflux&arg%5B%5D=xflux-gui-git&arg%5B%5D=yaourt&arg%5B%5D=yay&type=info&v=5: net/http: TLS handshake timeout`

**Comment by Morganamilo** [comment]
What exactly makes it improper? This is not a panic, the error message was correctly propagated form the rpc and back to main.

The message is kind of ugly though. Sure it could be better but the message clearly conveys what went wrong.

**Comment by Jguer** [comment]
Closing issue as the error is even generated upstream, we just print it out and it is descriptive.
