### ISSUE TITLE
RFC: Detect dependency upgrades and rebuild needed AUR & devel packages too

### ISSUE THREAD

**Issue by maximbaz** [Jguer/yay#87]
Recently I experienced the following: I have an AUR package A installed, that depends on a package B from the official repositories. Package B was updated, so I upgraded it with yay. However package B provides now a different *.so file, so with upgrading B the package A started crashing in runtime.

The fix was as simple as rebuilding package A, but it took me some time to figure out this.

My proposal is the following: I would like yay to track dependencies of AUR and devel packages, and when their dependencies update, suggest to rebuild these packages too. What do you think about it?

**Comment by z3ntu** [comment]
Also the ruby version upgrade from 2.4 to 2.5 made a bunch of AUR package rebuilds needed.

**Comment by AladW** [comment]
https://github.com/trizen/trizen/issues/86#issuecomment-360409395

**Comment by Morganamilo** [comment]
Forgot this was still open, closing in favour of #243.
