### ISSUE TITLE
No error when invalid options passed for a command

### ISSUE THREAD

**Issue by chrisjbillington** [Jguer/yay#872]
#### Affected Version
yay v9.1.0 - libalpm v11.0.2

#### Issue

I mistakenly filed issue #871 because I misread the man page. I typed an invalid command `yay -ww`, equivalent to `yay -Yww` and was expecting output.

However, since '-w' is an invalid option for the -Y command, it would have been good to get an error instead.

**Comment by Morganamilo** [comment]
I hesitated for a while on adding a valid flag check in the first place, mainly for not wanting the extra lines of code and fear of missing some (which happened multiple times). So further checking what flags go to what command is not something I want.

I did talk about erroring on noop if anyone wants to implement it. That would handle some of the situations but not all.
