### ISSUE TITLE
Add option for password request program

### ISSUE THREAD

**Issue by Shatur95** [Jguer/yay#874]
By default, `yay` asks for a password using `sudo`.
I would like to be able to request a password via `pkexec`, `kdesu` or `gksu`. This would be very convenient for graphical wrappers. For example, I working on [Orson](https://github.com/Shatur95/orson).
Could you please add this option to `yay`?

**Comment by Morganamilo** [comment]
All you would need to do is replace `"sudo"` with `config.sudoBin` and add the new config field. Any chance you want to try yourself?

**Comment by Shatur95** [comment]
I found an easier way, sorry to bother you!

**Comment by parkerlreed** [comment]
What was the "easier way"?

https://xkcd.com/979/

**Comment by RubixPower** [comment]
@Shatur95 please tell us the "easier way".

**Comment by Shatur95** [comment]
I just used default terminal app in Orson. It is better to display the information in it than implement graphical wrapper.
