### ISSUE TITLE
Is it possible to change the color of the indicating number？

### ISSUE THREAD

**Issue by Yves1024** [Jguer/yay#875]
#### Affected Version
yay v9.1.0 - libalpm v11.0.2

#### Issue
when there are several results matching the search with command `yay somthing`, I need to select one or some of the indicating number.
HOWEVER,it is so hard to recognize the number,just like this
![image](https://user-images.githubusercontent.com/35786611/52164174-40bfd680-2728-11e9-8b6c-28ebaef8afaa.png)

so is it possible to change the color? or background color like yaourt
![image](https://user-images.githubusercontent.com/35786611/52164169-2685f880-2728-11e9-810d-2094b47edc3e.png)

thanks

**Comment by Morganamilo** [comment]
It's not possible to configure yay's colours. A feature request for that should be under a more general issue. However if your terminal can not display that shade very well maybe you should just configure your terminal to use a different shade of purple.

**Comment by Jguer** [comment]
We could add a configurable color offset, but I think this would screw up way more than just the numbers. 

If our color choices don't create issues with the tango colorscheme of gnome-terminal I would say you'll have issues with other tuis as well with your colorscheme

**Comment by Yves1024** [comment]
I changed the color theme to fix the problem.I'm using [JetBrains Darcula](https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/Xresources/JetBrains%20Darcula) now. Thank you :smile:
