### ISSUE TITLE
yay doesn't show escape sequences embeeded in AUR package files

### ISSUE THREAD

**Issue by joanbm** [Jguer/yay#880]
#### Affected Version
yay v9.1.0.r8.ga645353 - libalpm v11.0.2

#### Issue
When installing/updating a package from AUR, yay offers the user to show the content of the package from AUR, or show the differences from a previously compiled version. However, with the default configuration of git and yay, if certain escape sequences (e.g. backspaces) are contained in one of the files whose diffs are printed, they are still rendered in the console. This means that with the default configuration, it's not safe to use yay's diff feature to audit AUR packages before installing them (e.g. to check if the source URLs are reliable and no malicious commands are included).

More info on git diff + escape sequences: https://www.twistlock.com/labs-blog/hiding-content-git-escape-sequence-twistlock-labs-experiment/

#### Steps to reproduce
1. Run `yay -S sample-pkgbuild-with-backspaces-calls-sudo`
2. When asked "Diffs to show?", type A then press ENTER.
3. Observe the content of the PKGBUILD script.
4. Proceed with the install and note how a command not seen in the PKGBUILD is run.

#### Output
![yaysudo](https://user-images.githubusercontent.com/519004/52377225-8f40de00-2a64-11e9-807a-0358d8252d9d.png)

Escaped PKGBUILD:
```
[zealcharm@SOL ~]$ cat -v PKGBUILD 
pkgname='sample-pkgbuild-with-backspaces-calls-sudo'
pkgver=1
pkgrel=1
pkgdesc="Sample PKGBUILD containing backspaces calls sudo"
arch=('any')
license=('GPL-3.0')

build() {
	sudo bash -c 'echo got $(whoami)'; #^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^H^Hecho "this is a very small script with some innocent backspaces, don't worry"
}

package() {
	true
}
```

**Comment by joanbm** [comment]
Seems that trizen and pikaur (at least) have the same problem, so maybe it would be also good to have some checks from the AUR side...

I was thinking about this, and perhaps a simple solution would be to have a whitelist of allowed characters (e.g ASCII printable, new lines, and perhaps some other) and display a warning to the user in this case for more thorough inspection. Some tests would have to be done to ensure that warning can not be overridden by malicious PKGBUIKDS thought.

It would also be a good idea to do some tests around sanitizing AUR inputs, to make sure escape sequences and other trickery can also not be injected through e.g. package names or descriptions.

**Comment by Morganamilo** [comment]
We (and I assume other helpers) just call `git diff` to show diffs. So I think the solution would be to configure git to show these escapes assuming you can. You could even report it upstream.

@AladW Do you have an opinion? Assuming this effects aurutils too.

**Comment by AladW** [comment]
Amazing. Thanks for the heads-up.

I don't see the whitelist or sanitization approach working, since you'll get a continuous stream of edge-cases for former and an ineffective cat and mouse game for latter.

`aurutils` is affected, though it has the option to redirect the output of `git diff` to a file. I'm not sure if editors like `vim` are vulnerable to the same "hide" trick.

**Comment by AladW** [comment]
You can use `cat -v` too. But then color won't work.

**Comment by eli-schwartz** [comment]
ANSI escape 8, "conceal", is wonderfully evil. Are there other escapes which are especially dangerous?

Just pointing out that as the article notes, the git developers were not very impressed with this vulnerability.

"Great, you've rediscovered a vulnerability in `cat`".

**Comment by joanbm** [comment]
I haven't been able to find the author's conversation with the Git developers, probably it was done in private. I think that ideally this should be fixed upstream in Git, as I don't see much of a use case for 'git diff' displaying backspaces/escape sequences/etc. and notable downsides of doing so.

If this isn't fixed upstream, it should be able to avoid this by configuring 'less' to escape non-printable characters (called by 'git' as the default pager). `env LESSCHARDEF=9b2.21b95.b LESS=-UR yay -S sample-pkgbuild-with-backspaces-calls-sudo` seems to work, except that it makes tabs ugly, and probably suffers from some edge cases as @AladW mentions.

BTW, it looks like escapes in package descriptions also show up in search results (see `yay -Ss sample-pkgbuild-with-backspaces-calls-sudo`).

**Comment by rafasc** [comment]
> Just pointing out that as the article notes, the git developers were not very impressed with this vulnerability.

:disappointed:

There was a similar situation where `git` was asking `less` to chop lines by default allowing code to be hidden after some white spaces. That ultimately resulted in `S` being dropped from the original `LESS=FRSX`  with https://github.com/git/git/commit/b3275838d969b7ecb91aae584226fccbeb046aca (submission thread: https://public-inbox.org/git/4dc69237123e8962b2b2b901692ea78e.id@mailtor/) for those interested.

As far as I am aware, there isn't a public thread in `git`'s mailing list yet.

**Comment by joanbm** [comment]
Still replicates on latest yay version.

**Comment by kescherCode** [comment]
Still replicates on the latest yay version.
On that note, stale bots are bad.
