### ISSUE TITLE
yay fails silently if PATH is not set

### ISSUE THREAD

**Issue by gdamjan** [Jguer/yay#881]
#### Affected Version

`yay v9.1.0 - libalpm v11.0.2`

#### Issue

Running yay without a PATH environment variable makes it fail very silently. I'd expect it to print some message before failing.

#### Steps to reproduce

normal operation
```
$ yay -Qu
…show some packages…
$ echo $?
0
```

Buggy operation, no packages are listed:
```sh
$ PATH= /usr/bin/yay -Qu
$ echo $?
1
```

**Comment by gdamjan** [comment]
this is still a problem with `yay v9.3.1 - libalpm v11.0.3`

**Comment by parkerlreed** [comment]
In what case is PATH ever going to be unset? Your system has to know where to look for binaries/executable files.

**Comment by gdamjan** [comment]
I didn't say that `PATH` should be unset, I'm just saying that `yay` should not fail *silently*. I agree it should fail, just it should be noisy about it.

Now, I discovered this issue when trying to run `yay` in a constrained self-made jail based on namespaces etc, and running it in a completely clean environment.

**Comment by gdamjan** [comment]
yes @stalebot, the issue is still present
