### ISSUE TITLE
yay -S fails to find AUR packages

### ISSUE THREAD

**Issue by Porkepix** [Jguer/yay#883]
#### Affected Version
It affects git version of yay. Stable version does not have the bug.

#### Issue
`yay -S` fails to find AUR package. User needs to specify `yay -Sa` explicitely.

#### Steps to reproduce
1. yay -S yay

#### Output
```
[clement@archlinux ~]$ yay -S yay
error: target not found: yay
Error installing repo packages
```

**Comment by Morganamilo** [comment]
Yep I'm aware of that. Some of the refactoring with alpm caused it. Need to find time to fix it.

**Comment by s7x** [comment]
Same bug with -Si : it doesn't check in both aur and repos.
With the last version of yay-git.

Cheers
