### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by budetisufu** [Jguer/yay#884]
Hi guys!
I saw a request for localization yay. What do I need to do to allow yay to use .mo files?

**Comment by Jguer** [comment]
Work on localization is happening on #342 but hasn't been merged yet because of hold ups in other parts of development. Use that pull request for discussion on implementation of the feature or to accompany its process

**Comment by Morganamilo** [comment]
See also https://github.com/Jguer/yay/pull/799#issuecomment-438649884
