### ISSUE TITLE
Remember AUR packages to not upgrade 

### ISSUE THREAD

**Issue by mannk** [Jguer/yay#887]
Some AUR packages:
- Take a long time to upgrade
- Don't need to be upgraded frequently
... BUT we have to "type their number" every time yay asks for AUR packages to not upgrade.

Concrete example:
I have many JetBrains IDEs installed from the AUR, but, for example, I only want to upgrade CLion when I know I will write a lot of C++... which doesn't happen often.

Feature idea:
- When yay asks for packages to not upgrade, remember which packages are mentionned a lot by the user (say... 3 or 5 times for example. I don't know).
- When yay asks for packages to not upgrade, pre-type numbers corresponding to those packages.

**Comment by Jguer** [comment]
As an alternative, why not add it to ignorepkg in `/etc/pacman.conf`?

**Comment by AladW** [comment]
An AUR helper is not complete until it includes a keylogger and AI to replace the user's brain.

**Comment by mannk** [comment]
> As an alternative, why not add it to ignorepkg in `/etc/pacman.conf`?

That seems like a good alternative, thanks!
