### ISSUE TITLE
Suggestion: Address use case where dependencies must be altered before installation

### ISSUE THREAD

**Issue by alxpettit** [Jguer/yay#889]
Using `yay v9.0.1 - libalpm v11.0.2`.

Is it just me, or does `yay` parse and save the dependencies _before_ allowing the user to edit the `PKGBUILD`? Because I just tried to remove some superfluous ones, but `yay` continued to insist on trying to install them before proceeding with the package build.

Edit: using [this](https://gist.github.com/alxpettit/ac2792a1cf6bad39584a394032283492) config, in case it's relevant.

Edit 2: behavior confirmed with `yay v9.1.0 - libalpm v11.0.2`

**Comment by Morganamilo** [comment]
https://github.com/Jguer/yay#yay-doesnt-install-dependencies-added-to-a-pkgbuild-during-installation

**Comment by alxpettit** [comment]
This doesn't really seem like good behavior to me. Often times the purpose of editing the PKGBUILD is to on-the-fly fix something with how it's set up -- often times something that affects the behavior of `yay`.

**Comment by Morganamilo** [comment]
Yay uses the AUR RPC for dependency resolution, it does not even read the pkgbuild.

**Comment by alxpettit** [comment]
Ooooh. I see! Yeah, I didn't realize that was even a thing.

In that case, my suggestion is moot... is there some way we could address the use case where a dependency must be changed on the fly while building a package?

**Comment by SecT0uch** [comment]
This function would be very practical.
