### ISSUE TITLE
Failed from install/update AUR package (libnm-gtk)

### ISSUE THREAD

**Issue by emersoncavalcanti1972** [Jguer/yay#891]
#### Affected Version
yay v9.1.0 - libalpm v11.0.2

#### Issue
When I use 'yay' to install a package from 'aur', it requires a library (libnm-gtk) that is not among the packages required. I use 'yay' on manjaro.

#### Steps to reproduce

1. yay -Syu --aur

#### Output

-> Missing AUR Packages:  libnm-gtk
 there is nothing to do

**Comment by Morganamilo** [comment]
libnm-gtk Is no longer in the AUR and there's nothing to do, I don't see a problem here.

**Comment by emersoncavalcanti1972** [comment]
Yes, it's replaced for nm-connection-editor
