### ISSUE TITLE
Fails to download some files

### ISSUE THREAD

**Issue by Shywim** [Jguer/yay#892]
#### Affected Version
yay v9.1.0.r12.gaa1e884 - libalpm v11.0.2

#### Issue
yay, for some reason, doesn't download `.pl` files for the [shadow-beta package](https://aur.archlinux.org/packages/shadow-beta/), but create empty files and subsequently fails on md5 checksums. `makepkg` has no problem downloading these files.

#### Steps to reproduce

1. `yay -S shadow-beta`
2. watch yay fail on md5

According to the comments on the AUR, I should not be the only one encountering this issue, though I don't know if this is specific to yay.

#### Output

```
ζ yay -S shadow-beta                                                                [ef21beb] 
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur: 1]  shadow-beta-0.9.22-2

  1 shadow-beta                      (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> A
:: Deleting (1/1): /home/shywim/.cache/yay/shadow-beta
:: Downloaded PKGBUILD (1/1): shadow-beta
:: Parsing SRCINFO (1/1): shadow-beta
  1 shadow-beta                      (Build Files Exist)
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> PKGBUILDs to edit?
==> 
==> Making package: shadow-beta 0.9.22-2 (mer. 20 févr. 2019 21:25:56 CET)
==> Retrieving sources...  -> 
Downloading shadow-alpha-bionic.zip…
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  174M  100  174M    0     0   371k      0  0:08:01  0:08:01 --:--:--  247k
  -> Found wrapper.pl
  -> Found report.pl
==> Validating source files with md5sums...
    shadow-alpha-bionic.zip ... Passed
    wrapper.pl ... FAILED
    report.pl ... FAILED
==> ERROR: One or more files did not pass the validity check!
Error downloading sources: shadow-beta
```
Note that it says that `wrapper.pl` and `report.pl` are found, when they aren't actually there...

**Comment by alwayslivid** [comment]
I doubt that this is an issue related to yay.

You may wish to reach out to the [maintainer](https://aur.archlinux.org/packages/shadow-beta/) of this package instead.

**Comment by Shywim** [comment]
I didn't test with a clean clone with makepkg, my bad :sweat_smile: .
According to the newer comments on the AUR, this is effectively an issue with the package as it has empty files in the AUR repo.
I'll close this issue.
