### ISSUE TITLE
user variables set in perpare() ignored

### ISSUE THREAD

**Issue by skydrome** [Jguer/yay#893]
yay v9.1.0 - libalpm v11.0.2

Setting variables inside of the prepare() function dont get seen when build() is entered. Is this intentional?

**Comment by Morganamilo** [comment]
Yay run's the prepare and actual build in different makepkg calls so environment variables are lost between the steps.

I would assume that regardless of yay, makepkg supports this (--repackge being especially useful) so it's a bad idea for a pkgbuild to do this so I don't consider it a bug.

**Comment by skydrome** [comment]
ok thank you for explaining
