### ISSUE TITLE
Question: Install without testing

### ISSUE THREAD

**Issue by pmatos** [Jguer/yay#898]
Is there a way to install a package even if a test fails?

**Comment by parkerlreed** [comment]
Assuming it's in an actual test/check function

```
yay -S blah --mflags "--nocheck"
```

**Comment by rulatir** [comment]
> Assuming it's in an actual test/check function in the PKGBUILD
> 
> ```
> yay -S blah --mflags "--nocheck"
> ```

Can I configure this as the default somehow, so I don't have to remember each time?

**Comment by parkerlreed** [comment]
I believe you can tag on `--save` once to save it to the config.
