### ISSUE TITLE
Suggests "upgrading" AUR packages to already-installed versions

### ISSUE THREAD

**Issue by AndydeCleyre** [Jguer/yay#9]
So in considering this behavior I eventually realized that `-Su` does not upgrade AUR packages, by design. Is that right? Is there a particular logic behind that?

Anyway, here's an example:

```bash
$ yay -Su
:: Starting full system upgrade...
 there is nothing to do
$ yay -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Starting AUR upgrade...
==> qtwebkit: 2.3.4-4 -> 2.3.4-4
==> tor-browser-en: 6.5-1 -> 6.5-1
==> Proceed with upgrade? (Y/n)
```

**Comment by Jguer** [comment]
Never bothered adding AUR upgrade to -Su. Figured someone who really only wanted to upgrade the through the repositories could use `yay --Sy && yay -Su`.

Anyways, the criteria for AUR upgrade is as follows:
The modification date of the PKGBUILD in the AUR is more recent than the install date of the package.

Which means that the version may not have changed but other changes might have happened in the PKGBUILD (like a new file install or description update).
It is only worrisome if there is a AUR upgrade pending even after building the newest version.

**Comment by AndydeCleyre** [comment]
Alright, thanks for clearing that up. FWIW I think the criteria for AUR upgrade ought to be based solely on `pkgver` and `pkgrel` (and `epoch`), to match `PKGBUILD` creation guidelines, and to prevent minor changes that don't affect the resulting package from being rebuilt unnecessarily.
