### ISSUE TITLE
Confirm with "j" in german

### ISSUE THREAD

**Issue by Musikermomo** [Jguer/yay#90]
"Yes" means "Ja" in German, so you should confirm with  "j" as in pacman:
`sudo pacman -S cowsay`
[...]
` (1) cowsay-3.03-9`
[...]
`:: Installation fortsetzen? [J/n] `

in yay:
`Edit PKGBUILD? [y/N]`

Alternating between pressing "y" and "j" is very confusing while doing a system upgrade.
Accepting "y" and "j" would solve this issue I think.

Many thanks for yay btw!

**Comment by samosaara** [comment]
I think this could be a better opportunity then simply translating to german, This would be a great opportunity to internationalize the project to multiple languages, like Portuguese (😉 😉 @Jguer ) ... But that would demand a rework of the messages system if they're hard-coded, (which I suspect them to be) I would love to help... But that would demand a bunch of design decisions... Like where to store the strings file, the format of the files, how to parse them, a naming scheme for the messages... What's @Jguer opinion to this?

**Comment by Jguer** [comment]
Every string is hardcoded in yay. I'm not the biggest fan of software localisation but yay is a wrapper of a program that is indeed localized.

And the J and the Y really would disturb me if it happened to me so I'm solidary with the idea of localizing at least the response commands.

On the technical side, a map seems like the easiest way to make this work and loading the map from the desired language.

**Comment by wzrdtales** [comment]
this seems to be still not fixed
