### ISSUE TITLE
yay -Syu 

### ISSUE THREAD

**Issue by MarcMcIntosh** [Jguer/yay#905]
#### Issue
So for every aur package I'm asked for 
Enter passphrase for key '/home/marc/.ssh/id_rsa_aur'
and nothing works, regardless of what is typed for the password.

#### Steps to reproduce

1. yay -Syu
2. enter password
3. repeat step 2

#### Output

nothing

**Comment by Morganamilo** [comment]
Do you have some rewrite rule in your git config that's converting http to ssh?

**Comment by MarcMcIntosh** [comment]
yes,
thanks :)
