### ISSUE TITLE
Cannot use arrowkeys or backspace in "Packages to install" prompt in urxvt

### ISSUE THREAD

**Issue by mxmilkiib** [Jguer/yay#906]
#### Affected Version

yay v9.1.0.r9.ge7a17d3 - libalpm v5.1.0

#### Issue

When I press the backspace or arrows keys in the promopt, it doesn't remove the character before the cursor or move the cursor, but instead prints ^? for backspace, ^[[D for left, ^[[C for right, ^[[A for up, and ^[[B for down.

I'm using rxvt-unicode. $TERM is rxvt-unicode-256color. When, on a shell, I press Ctrl-v and then the problem keys, it prints what appears in the yay prompt, i.e., ^?, ^[[D, etc.

**Comment by Jguer** [comment]
That is handled using
```
	reader := bufio.NewReader(os.Stdin)

	numberBuf, overflow, err := reader.ReadLine()
	if err != nil {
		return err
	}
	if overflow {
		return fmt.Errorf("Input too long")
	}
```
Very standard really, so your terminal setup should be breaking on other `go` programs. You didn't specify your shell but I've seen this issue show up  on some shells but not others. Care to give that detail and experiment with a different shell?

Tested using: rxvt-unicode, zsh - could not reproduce

**Comment by mxmilkb** [comment]
Shell is zsh. Bindings are [these](https://github.com/mxmilkb/dotzsh/blob/master/.zsh/bindings.zsh) (though that's a layer above).

So testing again/further now;

zsh or bash and urxvt: backspace /does/ work but arrow keys don't (same as above).

zsh or bash and xterm: backspace produces an ^H, arrow keys don't work. $TERM here is xterm-256-color.

zsh or bash and st: backspace does work, same arrow key problem. $TERM here is st-256color.

I use fzf regularly but don't have any problems with backspace or arrow keys there.
