### ISSUE TITLE
Method to install package from either official or AUR?

### ISSUE THREAD

**Issue by mxmilkb** [Jguer/yay#907]
#### Affected Version

yay v9.1.0.r9.ge7a17d3 - libalpm v5.1.0

#### Issue

I have an alias, `p = yay -Sa`, which I had thought installed from either the official repos or AUR.

I recently went to install ncmpcpp. Doing `p ncmpcpp` gave me a prompt whether to install ncmpcpp-git or ncmpcpp-vim-git from the AUR, packages which provide ncmpcpp.

I realised then I had misread the man page (and went for the vim hotkey version anyway :)

Is there a method one can use to install a specific package from either from official repos (even if there is something in the AUR that provides it) or the AUR?

**Comment by Morganamilo** [comment]
`--aur` restricts targets to the AUR only. `--repo` restricts targets to repos only. Don't use the flags and you don't restrict yourself.

Although you're using r9 which I believe is just broken. The latest master is fixed though.

**Comment by mxmilkb** [comment]
Aah, yes, I was on pacman-next. Have switched from pacman-git to pacman for now, and thank you for the clarification :)

**Comment by Morganamilo** [comment]
I've been updating the pacman-next branch too. So it's up to date with the current master anyway.

**Comment by mxmilkb** [comment]
Aah. Then my root mistake was not upgrading properly.

Hmm, related aside; is there a way, if one edits a PKGBUILD to set the git branch, to make yay use that altered branch the next time one runs a system upgrade with yay?
