### ISSUE TITLE
Unable to download the tar file to install jdk8-arm64

### ISSUE THREAD

**Issue by Montagnard** [Jguer/yay#911]
#### Affected Version
yay v9.1.0 - libalpm v11.0.3

#### Issue

Impossible to download the package ton install jdk8-arm64.
I managed to get the archive from my web browser at the url in the error. However I had to accept terms and conditions of Oracle to get the file.
A simple wget return an html page and not the tar.gz saying that we need to accept terms. 

#### Steps to reproduce

`yay -S arm8-arm64`

#### Output
```:: Parsing SRCINFO (1/2): jdk8-arm64
:: Parsing SRCINFO (2/2): filebot
==> Making package: jdk8-arm64 8u191-1 (Fri Mar  8 18:29:31 2019)
==> Retrieving sources...
  -> Downloading jdk-8u191-linux-arm64-vfp-hflt.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   553  100   553    0     0    546      0  0:00:01  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
==> ERROR: Failure while downloading http://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-arm64-vfp-hflt.tar.gz
    Aborting...
Error downloading sources: jdk8-arm64
```

**Comment by Morganamilo** [comment]
Please use three backticks to format code blocks.

**Comment by Morganamilo** [comment]
Either way I assume it's either a problem with the pkgbuild or the download server on their end.

**Comment by Jguer** [comment]
Almost definitely oracle started to include that terms agreement where before they just served the file, I would warn the maintainer about it

**Comment by Montagnard** [comment]
Thanks first comment on github i tried double backticks but I should have gone futher :p
