### ISSUE TITLE
broke my update 

### ISSUE THREAD

**Issue by andrewczgithub** [Jguer/yay#912]
Hi all,
When i try and update i get -

yay -Syu --devel --timeupdate
database already registered

This is probably due to way i update sublime text,
Best,
Andrew

**Comment by andrewczgithub** [comment]
Solved, two sublime text repo in pacman.conf 
Sorry for the bother. this issue can be closed.
Best,
Andrew

**Comment by NickMatthews-1** [comment]
I had this issue as well and I wanted to update it with the issue I had.

When I was looking at my pacman.conf I had two of the following multilibs in pacman.conf

It appears it cannot have more then 1 of anything not just Sublime text. I found this out as I also use sublime text myself.

I am commenting this in case anyone else has a similar issue and comes across this in the future!

```
[multilib]
Include = /etc/pacman.d/mirrorlist
```
