### ISSUE TITLE
[REQUEST] Use the $SUDO_ASKPASS environment variable

### ISSUE THREAD

**Issue by binaryplease** [Jguer/yay#913]
Yay doesn't care if the $SUDO_ASKPASS environment variable is set. It allways asks for a password. Other applications issue the commands set for SUDO_ASKPASS to authenticate instead, if the variable is set.  

My use-case for this e.g. is this: I use the pass password manager (https://www.passwordstore.org/) for for sudo on the terminal.
For that, you just set $SUDO_ASKPASS environment variable to something like "/home/binaryplease/.local/bin/passsudo" which contains something like
```
#!/bin/bash
pass local/$USER@`hostname` | head -n1
```
If the password vault is open, this doesn't requiere entering a password, which makes using applications that use "sudo" nicer to use.

It would be great, if yay could honor this standard and use the SUDO_ASKPASS var, if set.

**Comment by Morganamilo** [comment]
I didn't know that was a thing. The docs say:

>SUDO_ASKPASS     Specifies the path to a helper program used to read the password if no terminal is available or if the -A option is specified.
```

So it sounds like yay is in the right seems as there is a terminal available. Perhaps yay just needs a --sudoargs flag so you can pass -A yourself.

**Comment by binaryplease** [comment]
> I didn't know that was a thing. The docs say:
> 
> > SUDO_ASKPASS     Specifies the path to a helper program used to read the password if no terminal is available or if the -A option is specified.
> 
> ```
> 
> So it sounds like yay is in the right seems as there is a terminal available. Perhaps yay just needs a --sudoargs flag so you can pass -A yourself.
> ```

Strangly my helper program is always executed. Doing something like "sudo ls" uses my helper script

**Comment by Morganamilo** [comment]
is `which sudo` actually sudo?

**Comment by binaryplease** [comment]
> is `which sudo` actually sudo?

```
✱ which sudo
sudo: aliased to sudo --askpass

```

**Comment by Morganamilo** [comment]
Then there's your problem. Aliases only exist in the shell and not when other programs run commands.

There needs be a sudo bin and sudo args option added like we already have for git and pacman and so on.
