### ISSUE TITLE
Request: Show packages release notes

### ISSUE THREAD

**Issue by AdrienLemaire** [Jguer/yay#917]
I would like to read the content of all packages release notes when running `yay -Syu`.
It currently takes too much time to search each individual packages release notes and read about it, so we end up upgrading our packages while missing on the new features & deprecated features for said packages.

Most projects today will follow one of few conventions:
1. Write notes in a RELEASE, CHANGE or CHANGELOG file
2. Write notes in the github releases page
3. Write notes in a custom location and display in their own website.

Points 1 & 2 can easily be automatized. We could also maintain a user-contributed list of links for points 3.

Such feature would really help us to be more aware of what we're updating. Thanks for considering it

**Comment by MaaxGr** [comment]
Nice idea. Is there a plan, when this will be implemented?

**Comment by muesli** [comment]
PKGBUILDs actually support changelogs to some degree: https://wiki.archlinux.org/index.php/PKGBUILD#changelog

This could come in really handy when updating packages: yay could diff the changelog between the installed and the new version of the package and show you what has changed since the last update.

**Comment by AdrienLemaire** [comment]
I've been using pacolog to track packages updates for the past year. It seems to be tracking the pkgbuild changelog

**Comment by MaaxGr** [comment]
[Pacolog](https://gitlab.com/protist/pacolog) seems to accept only one package name. Do you pipe all packages through the pacolog command? It would be nice, if you could share your current workflow @AdrienLemaire.

Getting an overview over all packages that i update is still a feature that i would like to have in yay.

**Comment by AdrienLemaire** [comment]
I don't have a script, just checking the output of packages I care about. Most commit messages are useless as well... And it would be very slow to run pacolog for every package to be upgraded...

Anyways, if you really want a script, you could get started with this:
```console
$  yay -Qu | awk '{print "echo $(tput setaf 1)"$1"$(tput sgr0);pacolog "$1" | grep -zPo \"(?s)^.*"$2"\" | head -n -1"}' | bash
```

**Comment by klarkc** [comment]
The most important thing that we must read are the breaking changes. So a warning of the breaking changes would help to not mess up things. If packages are using semantic version it's easy to detect it by major bumps. If package is following angular commit guideline, these breaking changes notes are in release notes, CHANGELOG and commit messages.
