### ISSUE TITLE
Display Question and available option in the correct order

### ISSUE THREAD

**Issue by YoyPa** [Jguer/yay#918]
#### Affected Version
$ yay -V
yay v9.1.0 - libalpm v11.0.3

#### Issue
Available options are displayed before the question for ```Diffs to show?```.
Is it possible to keep the same order as ```Packages to cleanBuild?```?

#### Output
```
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
[...]
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> Diffs to show?
==> A
```

PS: The difference make my brain fart for 2s every time :disappointed:

**Comment by Morganamilo** [comment]
Seems like an easy patch to make ;)
