### ISSUE TITLE
yay can fail to install makedepends packages, especially conditional ones and then fail to install AUR package

### ISSUE THREAD

**Issue by Porkepix** [Jguer/yay#920]
#### Affected Version
```
yay --version
yay v9.1.0 - libalpm v11.0.3
```

#### Issue

Conditional additions to makedepends are ignored
#### Steps to reproduce

1. Try to install the `mpv-git` AUR package.
2. It'll fail due to missing dependency `vulkan-headers`

As visible in https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mpv-git the makedepends is added through a conditional statement, but is actually ignored.

I also tried editing the PKGBUILD with `--editmenu` arg (I'm not asked if I want to edit it otherwise, is this normal?) and added the package into the `makedepends`, but it looks like it's done too late in the process, I guess, and therefore fail too.

#### Output
```
$ yay -S mpv-git
:: There are 5 providers available for mpv-git:
:: Repository AUR
    1) mpv-git 2) mpv-ahjolinna-git 3) mpv-amd-full-git 4) mpv-full-build-git 5) mpv-full-git 

Enter a number (default=1): 
:: Checking for conflicts...
:: Checking for inner conflicts...

==> Package conflicts found:
 -> Installing mpv-git will remove: mpv

==> Conflicting packages will have to be confirmed manually

[Aur: 1]  mpv-git-0.29.0_88_g317d3ac266-1

  1 mpv-git                          (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: PKGBUILD up to date, Skipping (1/1): mpv-git
  1 mpv-git                          (Build Files Exist)
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> Diffs to show?
==> 
:: Parsing SRCINFO (1/1): mpv-git
==> Making package: mpv-git 0.29.0_88_g317d3ac266-1 (Thu 28 Mar 2019 12:01:49 AM CET)
==> Retrieving sources...
  -> Updating mpv git repo...
Fetching origin
  -> Found find-deps.py
  -> Found waf-2.0.9
==> Validating source files with sha256sums...
    mpv ... Skipped
    find-deps.py ... Passed
    waf-2.0.9 ... Passed
==> Cleaning up...
==> Making package: mpv-git 0.29.0_88_g317d3ac266-1 (Thu 28 Mar 2019 12:01:51 AM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Missing dependencies:
  -> vulkan-headers
==> ERROR: Could not resolve all dependencies.
Error making: mpv-git
```

**Comment by Morganamilo** [comment]
Yeah we don't support this sort of thing. You can always install whatever deps first.

**Comment by Porkepix** [comment]
Why close the issue? Imho this is the role of an AUR helper to be able to manage the install of listed dependencies, what makes it not relevant here?

**Comment by Jguer** [comment]
Closed as duplicate of https://github.com/Jguer/yay/issues/363

Yay resolves dependencies using AUR RPC, it does not read runtime changes in the PKGBUILD
