### ISSUE TITLE
How do i set --color=always as standard?

### ISSUE THREAD

**Issue by reliefs** [Jguer/yay#924]
#### Steps to reproduce

1. --color=always

#### Output

I need to get --color=always to always run, no clues in the documentation or script.

**Comment by Avi-D-coder** [comment]
I believe yay respects `/etc/pacman.conf`

**Comment by Jguer** [comment]
Indeed correct @Avi-D-coder . As long as Color is uncommented in `/etc/pacman.conf` yay will display color

https://github.com/Jguer/yay#yay-does-not-display-colored-output-how-do-i-fix-it
