### ISSUE TITLE
yay doesn't support new b2sums parameter in PKGBUILD

### ISSUE THREAD

**Issue by TheLinuxNinja** [Jguer/yay#926]
#### Affected Version
yay v9.1.0 - libalpm v11.0.3

#### Issue
When installing lastpass AUR package, error message concerning new hash algorithm b2sums is presented. This will impact other packages as b2sums becomes more prevalent.

#### Steps to reproduce
1. yay -S lastpass

#### Output
> :: Parsing SRCINFO (1/1): lastpass
> failed to parse lastpass: Line 30: Unknown key: "b2sums": b2sums = 493334b0cf11abe2add52a2935b1e3a4afdffd8b4b64d659913084257af058c51b2157fb1fdb4f78da9dee9f61750bcd0614661b092a66c6fd252eff35f348f8

yay -Pg
```
{
"aururl": "https://aur.archlinux.org",
"buildDir": "/home/linuxninja/.cache/yay",
"editor": "",
"editorflags": "",
"makepkgbin": "makepkg",
"makepkgconf": "",
"pacmanbin": "pacman",
"pacmanconf": "/etc/pacman.conf",
"tarbin": "bsdtar",
"redownload": "no",
"rebuild": "no",
"answerclean": "",
"answerdiff": "",
"answeredit": "",
"answerupgrade": "",
"gitbin": "git",
"gpgbin": "gpg",
"gpgflags": "",
"mflags": "",
"sortby": "votes",
"gitflags": "",
"removemake": "ask",
"requestsplitn": 150,
"sortmode": 0,
"completionrefreshtime": 7,
"sudoloop": false,
"timeupdate": false,
"devel": false,
"cleanAfter": false,
"gitclone": true,
"provides": true,
"pgpfetch": true,
"upgrademenu": true,
"cleanmenu": true,
"diffmenu": true,
"editmenu": false,
"combinedupgrade": false,
"useask": false
}
```

**Comment by eli-schwartz** [comment]
Caused by https://github.com/Morganamilo/go-srcinfo/issues/2 by the way.
