### ISSUE TITLE
yay -Qu and the ssl connection to aur.archlinux.org

### ISSUE THREAD

**Issue by terminologie-x** [Jguer/yay#929]
yay v9.2.0 - libalpm v11.0.3

I have some scripts that check available updates for archlinux with yay -Qu. After solving another problem with tcpdump that has nothing todo with yay, I discovered that an ssl connection to aur.archlinux.org is made after executing yay -Qu. This seems new, since pacman -Qu doesn't make a connection to aur.archlinux.org automatically, only if the command is pacman -Qu --devel.

It seems, that the command yay -Qu invokes yay -Qu --devel, right ? Not a problem at all, just to know how things work.

#### Steps to reproduce
1. you need 2 terminals, the second terminal you put a command like this in the terminal
sudo tcpdump -vvvn -i eth0 [hit enter]

2. in the first terminal you put this command, and look for connections in the second terminal
yay -Qu

3. dot it again with pacman
pacman  -Qu [hit enter]

**Comment by Morganamilo** [comment]
> since pacman -Qu doesn't make a connection to aur.archlinux.org automatically, only if the command is pacman -Qu --devel.

What? No. Pacman has no concept of the AUR at all and no `--devel` flag.

**Comment by E5ten** [comment]
@terminologie-x is it possible you aliased pacman=<AUR helper> a very long time ago and then forgot? not sure how else this thinking with pacman having a --devel flag that connects to the AUR would happen.

**Comment by terminologie-x** [comment]
my apologies and thanks to Morganamilo and E5ten, you are absolutly right.

I used pacaur before switching to yay :-D , anyway good job - excellent tool !
