### ISSUE TITLE
I have custom PKGBUILD, is it possible yay to solve build-time dependencies from AUR?

### ISSUE THREAD

**Issue by KestutisMa** [Jguer/yay#934]
Hello, I have my custom PKGBUILD file, that has build-time dependencies from AUR packages.
Is it possible to yay build-install that dependencies, when building my custom PKGBUILD package?

**Comment by parkerlreed** [comment]
Yes? Yay will install any required deps/optdeps of your package.

**Comment by KestutisMa** [comment]
Thanks for reply, but I see that `yay` does not install dependencies after editing PKGBUILD using `--editmenu` option, also that mentioned in https://github.com/Jguer/yay/issues/750#issuecomment-427042210
`makepkg -si` solves that dependencies, but using pacman repositories, not AUR.

**Comment by Jguer** [comment]
As explained in #750, yay uses the AUR RPC for dependency resolution and not PKGBUILD parsing therefore AUR dependencies won't be computed from edited PKGBUILDs

**Comment by KestutisMa** [comment]
Hi and thanks for reply. Use case was: one AUR package was depending on cuda and llvm from official repo, then cuda in repo was updated to 10.1, and llvm to 8.0, but llvm supports only cuda version 9.2 (and 9.2 is in AUR), so I needed to edit PKGBUILD.
If I install that packages by own, they will be marked as explicitly installed and not removed after I remove packaged that was depending on that.
Just taught that it might be useful feature.
Maybe there is another way doing it?

**Comment by Jguer** [comment]
Installing using the `--asdeps` as in `yay -S --asdeps <your-dependencies>` will install these packages as hanging dependencies, then you can install your custom PKGBUILD using makepkg and it should work.

**Comment by KestutisMa** [comment]
Thanks, quite good workaround.

**Comment by MrQubo** [comment]
> As explained in #750, yay uses the AUR RPC for dependency resolution and not PKGBUILD parsing therefore AUR dependencies won't be computed from edited PKGBUILDs (or custom made and unpublished)

@Jguer Is it possible to install custom made and unpublished PKGBUILDs with yay? Even if it cannot install dependencies from AUR it still usefull because of `--removemake` and `--sudoloop`.
Sorry for asking it on this closed issue, but that was my first hit in DuckDuckGo.
