### ISSUE TITLE
[FR] Search in package names only

### ISSUE THREAD

**Issue by efermi** [Jguer/yay#936]
#### Affected Version
yay v9.1.0 - libalpm v11.0.3

#### Issue
It would be useful to have a built-in way to search in package names only. It's a somewhat frequent request too: https://bbs.archlinux.org/viewtopic.php?id=90164, https://bbs.archlinux.org/viewtopic.php?id=54684, https://bbs.archlinux.org/viewtopic.php?id=236426, https://bbs.archlinux.org/viewtopic.php?id=92102

**Comment by hopeseekr** [comment]
So how do you search yay by package name???

**Comment by grandchild** [comment]
It seems what @hopeseekr actually means is that `--searchby name` doesn't actually work, and returns description hits as well:

```
$ yay --searchby name something
5 aur/something r2894.95ca07bd-1 (+0 0.00) 
    Finally something
4 aur/something-for-reddit-git 0.1-1 (+3 0.00) (Out-of-date: 2019-12-24) 
    A Reddit Client For GNOME (with Gtk+ and Python)
3 aur/something-for-reddit 0.2.2-1 (+10 0.03) (Out-of-date: 2020-10-01) 
    A Reddit Client For GNOME (with Gtk+ and Python)
2 community/ruby-httpclient 2.8.3-7 (360.9 KiB 1.7 MiB) 
    gives something like the functionality of libwww-perl (LWP) in Ruby
1 community/python-hypothesmith 0.1.5-1 (17.6 KiB 46.6 KiB) 
    Hypothesis strategies for generating Python programs, something like CSmith
```
