### ISSUE TITLE
Method to take AUR package provides= into account when installing a meta package?

### ISSUE THREAD

**Issue by mxmilkb** [Jguer/yay#937]
Currently, if I try to install the pro-audio package group, it tries to uninstall several AUR -git packages in favour of the official packages, which is not that handy, from the me point of view anyway.

This is the default pacman behaviour, but might yay be able to have some logic that doesn't remove packages that provide what the package group lists?

**Comment by Morganamilo** [comment]
Can't you just --igore them or use pacman's prompt to not install them? Also I lurk on IRC so I see you there too :P

**Comment by Morganamilo** [comment]
Also for reference it's only because of IRC I know what you're on about. You're talking about groups but the tittle says meta packages which are different things entirely.

**Comment by Morganamilo** [comment]
Anyway this is out of scope for yay. But here's a horrible command to do it.

```
pacman -Sgq base | xargs -I % sh -c "pacman -T % || echo %" | sudo pacman -S -
```

It's kinda slow, a libalpm based tool would be much faster but this is much easier.

**Comment by mxmilkb** [comment]
Whoops, I thought I had changed all instances of meta package to package group!

Thank you for the workaround :)
