### ISSUE TITLE
exec.go: Consider replacing sudo with more secure "su -c"?

### ISSUE THREAD

**Issue by robinhood2014** [Jguer/yay#940]
#### Affected Version
9.2.0

#### Issue
Not really an issue with running the program, but more like a suggestion on how to improve its security. For example, it could be run in a business environment, where employees shouldn't install AUR packages willy-nilly, but rather should seek approval from their supervisors; who, if they approve, will input the root password and allow the installation to proceed.

I suggest the following modification in line 80 of file exec.go:
```
- argArr = append(argArr, "sudo")
+ argArr = "su -c '" + argArr + "'"
```
which will replace the generally insecure sudo command with a more secure "su -c" wrapper.

**Comment by Morganamilo** [comment]
Not exactly how that is more secure exactly. Sudo can be configure to use the root password anyway and makepkg is not run as root anyway, only the package install.

Anyway see #916. The PR is correct apart from a one line change. Maybe you'd be interested in taking it over.

**Comment by robinhood2014** [comment]
Interesting insight. I've never programmed in Go before, so to take a crack at this will require some trial and error. I'll look into this as soon as I can get back to my computer, which, unfortunately, won't be for several hours yet. Busy, busy Saturday ahead of me... Criminy, I wish developing software didn't take so many wasted dadgum days and nights like it does now... I miss the days of BASIC, when computer programs were a heck of a lot simpler. From what I've heard, BASIC programs were generally slower than programs written in some other languages back in the day, but hey, that was (and probably still is) the price you paid (pay) for convenience and ease of use.

**Comment by robinhood2014** [comment]
> Sudo can be configure [sic] to use the root password anyway...

So I discovered by running a quick Bing search. One small additon to the `/etc/sudoers` file -- `Defaults rootpw` -- and voila.
So I guess `sudo` vs. `su -c` is really just a matter of personal preference. Maybe, the first time yay is run, we can ask the user which method he/she prefers, and then yay saves that preference in a file called -- oh, say, `~/.config/yay`.

**Comment by Morganamilo** [comment]
The user can configure stuff themselves. We have like 30 different config options.

**Comment by Jguer** [comment]
`employees shouldn't install AUR packages willy-nilly, but rather should seek approval from their supervisors; who, if they approve, will input the root password and allow the installation to proceed.`

There's always a way around that as long as yay reads the configuration from the user directory and PATH is user definable. The best security case then is to configure sudo to use the root password as suggested by @Morganamilo.
