### ISSUE TITLE
PyQt4 Cannot Be Installed Through Yay

### ISSUE THREAD

**Issue by JeffVandrewJr** [Jguer/yay#941]
#### Affected Version 
yay v9.2.0 - libalpm v11.0.3

#### Issue
AUR packages python-pyqt4 and pyqt4-common cannot be installed through yay.

#### Steps to reproduce

1. `yay -Syu`
2. Allow yay to begin upgrading python-pyqt4 and pyqt4-common
3. Obtain error `Could not find PKGDEST for: python2-sip-pyqt4`

This is probably related to the merger of the python2-sip-pyqt4 into python-sip-pyqt4. 

See my comments and the package maintainer response: https://aur.archlinux.org/packages/python2-sip-pyqt4/

#### Output

Output: `Could not find PKGDEST for: python2-sip-pyqt4`
Config:
```
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/jvandrew/.cache/yay",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"tarbin": "bsdtar",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"gitflags": "",
	"removemake": "ask",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"gitclone": true,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false
}
```

**Comment by Morganamilo** [comment]
Works for me. What if you clean build?

**Comment by Morganamilo** [comment]
Blame upstream for changing the pkgbuild without bumping the pkgrel: https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=python-sip-pyqt4

**Comment by JeffVandrewJr** [comment]
Cleanbuild worked. Sorry for wasting anyone's time! I am closing the issue and posting this to the AUR page as well in case others get the same problem.
