### ISSUE TITLE
yay -Rp gives sudo prompt

### ISSUE THREAD

**Issue by jpfkd** [Jguer/yay#943]
#### Affected Version
yay v9.2.0.r5.gd406966 - libalpm v11.0.3

#### Issue
When I run `yay -Rp` to print the target to be removed, yay invokes sudo to gain root access, while pacman does not require root access to execute this operation.

**Comment by H4rryA** [comment]
Made a PR with a fix for this. I'm going to look into a way to simplify the checking for sudo

**Comment by jpfkd** [comment]
It's fixed. Thank you!
