### ISSUE TITLE
no pkgbuild exists

### ISSUE THREAD

**Issue by ThePacificGamer** [Jguer/yay#945]
#### Affected Version
 latest
 not required

#### Issue
I clone yay, i run makepkg -si and the pkgbuild doesn't exist.

#### Steps to reproduce

1. git clone https://github.com/Jguer/yay.git
2. cd yay
3. makepkg -si

#### Output

==> ERROR: PKGBUILD does not exist

**Comment by ThePacificGamer** [comment]
Neverming, I accidently did the github version, not the AUR version

**Comment by Jguer** [comment]
Happens to all of us :laughing:
