### ISSUE TITLE
FR: Add config option to build all AUR packages before installing them

### ISSUE THREAD

**Issue by Qyriad** [Jguer/yay#949]
Currently, each package is built and then installed before moving on to the next package.
There should be a configuration option to build all packages *first*, and *then* install them all, instead of alternating build and install steps.

In particular, this would be helpful to avoid needing to type a password for `sudo` after every sufficiently-long build, though that is not the only motivation for this feature request.

**Comment by T4cC0re** [comment]
I always run into this when there is an update to zfs-dkms, because it links its version to zfs-utils. I always have to build those myself and install them at the same time via pacman. It would be really great if yay could do that.

**Comment by tleydxdy** [comment]
@T4cC0re you can use -d to skip version check, just make sure you're only updating zfs when you're updating with -d for safety

**Comment by Morganamilo** [comment]
See #778. This sounds to be what you all need. Seems like there's an actual purpose for it now.

**Comment by Morganamilo** [comment]
Merged, try out `--batchinstall`.
