### ISSUE TITLE
yay hooks: Before/After - Install/Upgrade/Remove

### ISSUE THREAD

**Issue by maximbaz** [Jguer/yay#95]
I need `Before/After` yay hooks for `Install/Upgrade/Remove` actions similar to pacman hooks. I have btrfs+snapper and I want to make 2 snapshots of system partition before and after each yay operation, so that I can easily rollback if something went bad. I'm currently using pacman hooks for this, but I'm not entirely satisfied because one yay operation might result in 10 pacman calls, and this triggers creation of 2*10 snapshots instead of just 2.

I think I'll implement this myself and send a PR once I get to do this, for now I just want to lay down the requirements and have a place for potential questions/suggestions.

In the script that is triggered by the hook I need to know the following info:
1. Operation (install/upgrade/delete).
2. The list of packages involved in the operation (1st tier is probably enough, see #42).

If I install one AUR package that has two more packages as dependencies, I need the hook to only be triggered once before any package is installed, and once after all of them are installed.

The `post-` hook should trigger even if installation crashed / was cancelled.

**Comment by Morganamilo** [comment]
Hooks seems a tad overkill, especially when pacman has the feature built in, maybe a better solution is to modify yay to not call pacman 10 times during an install.

One way I see around this is build everything with makepkg first then call one `pacman -U foo bar and so on` instead of doing `makepkg -i` and have that call -U every single time. Of course this wont work for build dependencies so I'm not sure how well that idea would work in practise.

**Comment by maximbaz** [comment]
I was re-reading #42 and I was thinking exactly the same, but as you said this won't work with make dependencies, and it wouldn't work for nested dependencies (or "tiers" as they are called in #42).

Having one `pacman -U foo bar and so on` per tier would certainly be a huge improvement by itself, it is part of #42 which I very hope to see implemented at some point 🙂

However if #42 is implemented, then perhaps yay hooks aren't needed as much, yes installation might create more snapshots than needed, but if I keep make dependencies around, upgrading will always be done in one step = one pair of snapshots 🤔 

Yeah perhaps it's best to hold this off until #42 is ready, and then re-think the need for this.

**Comment by Morganamilo** [comment]
This is not so much yay related but more specific to you. Thought maybe you could write your hook to check if its made a snapshot in the past xmins and if so don't bother making another.

**Comment by Jguer** [comment]
My first instinct reading this is that it's a very bloaty feature. I really need to work on #42 when I get back to reduce the amount of pacman calls either way.

**Comment by Jguer** [comment]
Closed until necessary again.

**Comment by JimPix1** [comment]
Should this be reopened again?

**Comment by iTrooz** [comment]
I would love such a feature, to facilitate cleaning yay cache. I am currently running `yay -Sc --aur --noconfirm` through a pacman post-transaction hook which has the exact behaviour I want, except the hook is run when installing dependencies of an AUR package, leading to yay failing to build the (not yet installed, and cleaned) AUR package just after

Implementation idea: loop through and run `/etc/yay/hooks/*.post.sh` files after the transaction

Related: https://itrooz.fr/posts/my_tweaks_to_arch_package_management/#yay
