### ISSUE TITLE
Does yay support proxy?

### ISSUE THREAD

**Issue by CoinCheung** [Jguer/yay#951]
Hi, 

I just find that many packages are failed to be installed. For example, when I run `yay -S libsepol`, I get this error message:
```
Get https://aur.archlinux.org/rpc.php?arg%5B%5D=libsepol&type=info&v=5: dial tcp 5.9.250.164:443: i/o timeout
```
I think it is likely to be the problem with my network, so I used this: 
```
proxychains yay -S libsepol
```
The the error message becomes:
```
Get https://aur.archlinux.org/rpc.php?arg%5B%5D=libsepol&type=info&v=5: dial tcp 224.0.0.1:443: connect: network is unreachable
```
The problem is that whatever package I am trying to install, if I add `proxychains` before the `yay` command, I will have the error message of `network unreachable`. How could I implement an efficient installlation?

**Comment by Jguer** [comment]
yay supports environment proxies (http_proxy and https_proxy) and supports proxychains when built with `gcc-go` (https://github.com/Jguer/yay/issues/429) as proxychains overloads a shared library that yay when compiled with `go` doesn't use since it's a static compile

**Comment by Jguer** [comment]
Closing by innactivity

**Comment by CoinCheung** [comment]
Hi, sorry for continue so late. Would you please be a little more specific ? How could I make proxychains work step by step?

**Comment by Jguer** [comment]
1. `yay -S gcc-go` (replace go)
2. `yay -S yay` (or `yay-git`)

After this `yay` should be compatible with proxychains

**Comment by Morganamilo** [comment]
You're probably going to need a `--rebuild` in there is yay is already up to date.

**Comment by StevenJokes** [comment]
After I did what you said,I still have this error?

yay -S gcc-go
yay -S yay

yay --rebuild

git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

**Comment by intchensc** [comment]
> Hi, sorry for continue so late. Would you please be a little more specific ? How could I make proxychains work step by step?

u may try like this, it works for me
`sudo vim /etc/proxychains.conf`

and u need add "#" to `proxy_dns`

make it to `# proxy_dns`

**Comment by chiboreache** [comment]
after

> 2. `yay -S yay` (or `yay-git`)

it's backing to `gcc` 

`:: go and gcc-go are in conflict. Remove gcc-go? [y/N]`

trying 

`yay -S yay --rebuild`

no difference

**Comment by chiboreache** [comment]
> > Hi, sorry for continue so late. Would you please be a little more specific ? How could I make proxychains work step by step?
> 
> u may try like this, it works for me `sudo vim /etc/proxychains.conf`
> 
> and u need add "#" to `proxy_dns`
> 
> make it to `# proxy_dns`

lol that's works like a charm, thanks mate!

i simply opened it with a VSCode, comment it, and resave as sudo (popup automatically)

**Comment by arash28134** [comment]
> after
> 
> > 2. `yay -S yay` (or `yay-git`)
> 
> it's backing to `gcc`
> 
> `:: go and gcc-go are in conflict. Remove gcc-go? [y/N]`
> 
> trying
> 
> `yay -S yay --rebuild`
> 
> no difference

For anyone who still encounters this problem, remove yay with `sudo pacman -Rns yay` and then install yay again with `makepkg -si` (while you have gcc-go)
if the problem persists, comment `proxy_dns` in proxychains conf file.

**Comment by erenoglu** [comment]
> > after
> > > 2. `yay -S yay` (or `yay-git`)
> > 
> > 
> > it's backing to `gcc`
> > `:: go and gcc-go are in conflict. Remove gcc-go? [y/N]`
> > trying
> > `yay -S yay --rebuild`
> > no difference
> 
> For anyone who still encounters this problem, remove yay with `sudo pacman -Rns yay` and then install yay again with `makepkg -si` (while you have gcc-go) if the problem persists, comment `proxy_dns` in proxychains conf file.

This doesn't work as makepkg demands to remove gcc-go and install go. If you edit PKGBUILD to change go dependency to gcc-go, it starts to compile but then fails with error messages.

**Comment by fingertap** [comment]
I just simply use this alias:
```bash
alias yay='https_proxy=socks5://127.0.0.1:1080 http_proxy=socks5://127.0.0.1:1080 yay'
```

**Comment by Mrtao233** [comment]
1.  ` yay -S gcc-go`
2.  `yay -S yay --rebuild`

3.  alias yay='https_proxy=http://127.0.0.1:8080 http_proxy=http://127.0.0.1:8080 yay'



 将代理app中设置为http协议-----端口8080(比如说，qv2ray之类的）

**Comment by pongfcnkl** [comment]
Before using environment variables, you need to add the following text to the end of Visudo.
vi visudo
```
Defaults env_keep += "HTTP_PROXY HTTPS_PROXY ALL_PROXY no_proxy"
```
