### ISSUE TITLE
Building wine-lol (depending on wine-lol-glibc) with yay fails

### ISSUE THREAD

**Issue by M-Reimer** [Jguer/yay#956]
I'm no user of yay but some users of my PKGBUILD's are.

See for example this bug report:
https://github.com/M-Reimer/wine-lol-glibc/issues/3

Some background story:
To get "League Of Legends" to work on Linux, a patch on wine is needed. This patch needs a patched glibc to do its job.

As I don't want to mess with the system glibc, I decided to build my own "patched" version and install this below /opt/wine-lol. In a second step the patched wine is built which has a "RPATH" set to the patched glibc and also uses the dynamic linker of the patched glibc.

Building wine-lol-glibc (the patched glibc) with yay seems to work for some people but building wine-lol seems to fail for everyone.

Maybe you can have a look at this?

**Comment by Morganamilo** [comment]
It's probably because you declare variables inside the prepare function that you later intend to use in the build function.

**Comment by M-Reimer** [comment]
This part came from the official wine PKGBUILD.
And I don't think this can be the cause, as it works with plain makepkg.

**Comment by Morganamilo** [comment]
It works if you do it all in one plain makepkg call. If if you do one makepkg call to extract the files + prepare, then another to actually build, the enviroment vars won't be preserved between calls.

I assume it's bad practise on the pkgbuilds part but I have no official confirmation on that.

**Comment by M-Reimer** [comment]
The interesting question is: Does yay do this (run makepkg twice to build packages)?
If it's bad practice, then this is bad practice done in official Arch PKGBUILD's:
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/wine#n104

**Comment by M-Reimer** [comment]
This can't be the reason. I've commented the two lines and did a compile with "makepkg".
Still works and doesn't trigger the error some of my PKGBUILD users have.
Must be "something" with the environment, yay builds PKGBUILD's in.

**Comment by Jguer** [comment]
I tried building it in a VM, 
`yay -S wine-lol-glibc` worked without an issue
`yay -S wine-lol` failed to build with the error described in your issue tracker

I got it to compile by moving the following lines (at least it passed the part where it died first, it's still compiling for 1h at least because I forgot to change the cpu cap on the VM so consider this provisional results)

```
export CFLAGS="${CFLAGS/-fno-plt/}"
export LDFLAGS="${LDFLAGS/,-z,now/}"
```
to before in `build()`
```
  # We need RPATH to point to the "lib32" in our prefix
  _RPATH="-rpath=/opt/wine-lol/lib32"
  # Dyamic linker has to be the one in wine-lol-glibc
_LINKER="-dynamic-linker=/opt/wine-lol/lib32/ld-linux.so.2"
(...)
```

The only thing that bugs me is that I failed it first using `yay` compiled with go and compiled the fixed version using `yay` with gcc-go, shouldn't make a difference, but once this build ends I'll try running it clean with `yay` compiled with go.

**Comment by M-Reimer** [comment]
Thanks for testing. I'm currently updating my PKGBUILD to build with wine 4.9 and I've added the changes recommended here.
I'll ask for testers on Reddit as soon as my update is pushed and tested on my machine.

**Comment by M-Reimer** [comment]
I've got two confirmations that building with yay works now.
Thanks for your help with finding this bug.

**Comment by Morganamilo** [comment]
Should probably mention you are doing stuff outside of pkgdir here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=wine-lol#n147

**Comment by M-Reimer** [comment]
What do you mean? These commands create build directories below "src".

**Comment by Morganamilo** [comment]
I'm just tired I guess, glanced at it an assumed you typo'd pkgdir to pkgname.

**Comment by loathingKernel** [comment]
Sorry for the necrobump but this is definitely not a PKGBUILD issue, the PKGBUILD does it "properly" as it follows Arch's `wine` and `wine-staging` PKGBUILDs. I have had users report broken builds due to not honoring the CFLAGS as they were defined in `prepare()`. Moving them into build is also annoying as it breaks clean diffs with upstream PKGBUILDs.

This is **NOT** an issue with the PKGBUILD as it works as intended with the official tools.

**Comment by Morganamilo** [comment]
This breaks `makepkg -o && makepkg -e` wich is official tools. Just cause a package in the repos does something doesn't make it right.

**Comment by loathingKernel** [comment]
Your example explicitly uses developer oriented options, and it is not the suggested usage when building a package, i.e. no user should be doing this without explicitly stating their intention to `makepkg` through the switches. It is extracting the sources and then it uses the prepared source to build a package. Just cause that command can emulate the build process it doesn't mean it is the build process. Part of the complete build process is retaining the environment between steps.

While I do consider that doing it in `build()` is a better practice, it is not an assumption that is safe to make nor applicable everywhere. There is a number of official packages that export variables in `prepare()` for use in `build()`.

https://github.com/archlinux/svntogit-packages/blob/packages/git-review/trunk/PKGBUILD
https://github.com/archlinux/svntogit-packages/blob/packages/nvidia-settings/trunk/PKGBUILD
https://github.com/archlinux/svntogit-packages/blob/packages/openjade/trunk/PKGBUILD
https://github.com/archlinux/svntogit-packages/blob/packages/pyopenssl/trunk/PKGBUILD
https://github.com/archlinux/svntogit-packages/blob/packages/python-lxml/trunk/PKGBUILD
https://github.com/archlinux/svntogit-community/blob/packages/lib32-libvisual/trunk/PKGBUILD
https://github.com/archlinux/svntogit-community/blob/packages/lib32-virtualgl/trunk/PKGBUILD
https://github.com/archlinux/svntogit-community/blob/packages/lib32-vkd3d/trunk/PKGBUILD

And every other go package such as the following as it doesn't set GOPATH again (in this case the go dependencies are downloaded in the user's home directory with the example you posted, which is explicitly NOT the intention of the PKGBUILD).
https://github.com/archlinux/svntogit-community/blob/packages/consul-template/trunk/PKGBUILD

This is a third party tool, it should at the very least not fall over and die in cases that are functioning correctly using the official tools, not the other way around.

**Comment by Morganamilo** [comment]
> Your example explicitly uses developer oriented options, and it is not the suggested usage when building a package

Says who? They're valid and useful flags.

> Part of the complete build process is retaining the environment between steps.

Again says who? 

> While I do consider that doing it in build() is a better practice, it is not an assumption that is safe to make nor applicable everywhere. There is a number of official packages that export variables in prepare() for use in build().

Then we're in agreement somewhat. Only difference is I will not cater to bad practice. The packages you list should be fixed.

**Comment by loathingKernel** [comment]
> Says who? They're valid and useful flags.

> Again says who?

They are valid and useful, when specified explicitly. A naked `makepkg` won't fail because variables are exported in `prepare()`. Ergo the default behavior is not your example which explicitly stops the process, exits to the shell and then starts it again, but rather the retention of the environment.

> Then we're in agreement somewhat. Only difference is I will not cater to bad practice. The packages you list should be fixed.

The bad practice here is to not follow the intention of the upstream tools, as they are being used by the upstream developers. For lack of explicit documentation, upstream should be referred to as the specification.

**Comment by Morganamilo** [comment]
As this has come up multiple times I've decided makepkg will explicitly stop allowing this. Best way to force every one to fix their stuff :P

**Comment by loathingKernel** [comment]
Personally, I am absolutely fine with this change. What matters to me the most is consistency across tools. What I don't like is scratching my head why someone is having issues with my contributions because they are using a helper (which I can't know about).
