### ISSUE TITLE
[Feature Request] Command to download sources and PKGBUILDs

### ISSUE THREAD

**Issue by 132ikl** [Jguer/yay#968]
With pacman, you can run `pacman -Syyuw --noconfirm` to download all packages automatically and then simply run `pacman -Syu` later to install the downloaded packages. Something like this in yay would be nice. Ideally it would download both the sources and the PKGBULIDs, which would allow the user to later run `yay -Syu` to actually install the packages.

**Comment by parkerlreed** [comment]
`-G`?

**Comment by 132ikl** [comment]
-G only downloads PKGBUILDS, not sources, and installs them in the current directory, which means you can't just run `yay -Syu` right after using -G.

**Comment by Jguer** [comment]
This will lead you to build the packages not install them. This it not implement yet but should be.
