### ISSUE TITLE
possibility to show modification time

### ISSUE THREAD

**Issue by ondrejtichacek** [Jguer/yay#970]
Is it possible to show the Modification time (in case of aur packages) or Build time in case of standard repositories, **when searching** for a package?

If not, I think this would be great for quickly recognizing, which package is likely outdated / no-longer maintained.

I know this info can be accessed by `yay -Si <package-name>` but doing this for every package in the list seems unreasonable.

I would suggest the following behavior, possibly controlled by some flag:

```
yay <search-query>
...
2 aur/<package-name> version (+3 0.60%) [Modified: 16 Apr 2019]
    New package
1 aur/<package-name> version (+19 0.60%) (Installed) [Modified: 20 May 2016]
   Old package
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==>
```

**Comment by Jguer** [comment]
A `git` package could be left untouched for very long and not all older software is bad, not a fan of the motivations behind this and I don't like the extra space it would occupy. Leaving it open for discussion but will close it at the end of the month with other stale feature requests.

**Comment by ondrejtichacek** [comment]
I understand your point and by no means I wanted to say that all old software is bad. But I'm sure in some cases this information can be useful. In case of an aur package yay is already printing the "votes" and "popularity" - statistics that can sometimes be misleading as well. Not all "unusual" software is bad. Anyway, it's a matter of personal choice.

Would it be possible to make this additional statistics configurable (while leaving the current as default)? This could include any similar statistics.

In general, I would sometimes appreciate a more verbose output of yay when searching, optionally listing for example the url or other information - I wouldn't mind scrolling through the longer output.
