### ISSUE TITLE
Lost colors in update output

### ISSUE THREAD

**Issue by va-al** [Jguer/yay#974]
#### Affected Version
`yay v9.2.0 - libalpm v11.0.3
`
```
vaal@avasilchenko ~> lsb_release -a
LSB Version:	1.4
Distributor ID:	Antergos
Description:	Antergos Linux
Release:	rolling
Codename:	n/a
```

#### Issue
Colored output for search `-Ss` or `-Syua`, 
![Screenshot from 2019-06-26 13-26-22](https://user-images.githubusercontent.com/3016713/60173030-92bbe280-9816-11e9-819b-d2def54b3623.png)

![Screenshot from 2019-06-26 13-32-07](https://user-images.githubusercontent.com/3016713/60173154-d9114180-9816-11e9-957c-5da81010423f.png)

but lost colors for `-Syu` options or just `yay`.
![Screenshot from 2019-06-26 13-33-00](https://user-images.githubusercontent.com/3016713/60173232-f219f280-9816-11e9-8666-367f6688a09a.png)

![Screenshot from 2019-06-26 13-26-13](https://user-images.githubusercontent.com/3016713/60173031-92bbe280-9816-11e9-8d36-481bfaf703c6.png)

My pacman.conf have uncommented "Color" param.
![Screenshot from 2019-06-26 13-26-46](https://user-images.githubusercontent.com/3016713/60173008-86d02080-9816-11e9-9aa5-ff6c38575a68.png)

`./.config/yay/` isn't created
![Screenshot from 2019-06-26 13-34-34](https://user-images.githubusercontent.com/3016713/60173357-37d6bb00-9817-11e9-90aa-9009c437e3a3.png)

#### Steps to reproduce
1. just try `yay -Syu`

**Comment by Jguer** [comment]
I believe what you want is `yay -Syu --combinedupgrade --save`

And here's why it's not on by default:
https://github.com/Jguer/yay/pull/516

**Comment by va-al** [comment]
I have no  available packages for upgrade, but I'll check it asap. 
But if is feature maybe it must be marked in man pages?

**Comment by Jguer** [comment]
And it is on the man page

**Comment by va-al** [comment]
Probably my English not egnought perfect, sorry. Perhaps it makes sense to make a separate paragraph with a description obtainable for non native speakers? 
Anyway my problem is solved, thank you very much!

**Comment by va-al** [comment]
> I believe what you want is `yay -Syu --combinedupgrade --save`
> 
> And here's why it's not on by default:
> #516

and yet in the continuation of the topic: is it really problematic to format and color the output without using the combined update? Could you take it as a feature request?
