### ISSUE TITLE
Bad AUR packages ordering

### ISSUE THREAD

**Issue by jeroni** [Jguer/yay#975]
Version 9.2.1-1

Reversed package upgrade ordering.

![aur-bad-ordering](https://user-images.githubusercontent.com/9005992/60279351-2e298200-9901-11e9-9ecb-97dccb938d87.png)

**Comment by Jguer** [comment]
What do you mean? Everything seems as it should be.

**Comment by jeroni** [comment]
I didn't know if it was an issue, reverse numbering on packages looked weird.

**Comment by Jguer** [comment]
Maybe using, for example, `yay linux --topdown --save` would be more to your liking, by default yay uses `--bottomup`

**Comment by jeroni** [comment]
I understood (as I can see in man) that --topdown and --bottomup was a repo-type ordering, not inner AUR package ordering.

       --topdown
              Display repository packages first and then AUR packages.

       --bottomup
              Show AUR packages first and then repository packages.

**Comment by Jguer** [comment]
it quite changes the order of packages displayed, the way that menu is presented is bottom up, numbers start at the commandline and move up. Mind doing a little paint masterpiece of how you think it should be?

**Comment by jeroni** [comment]
The natural ordering is
1
2
3
...
as we can see in any application or html ordered list.
The default behaviour "bottomup" is great , as you can see the official repo packages at the very end (which are usually preferred over AUR).
But the reverse ordering on AUR updates was a little confusing to me plus the "negative thing" of "Packages to NOT upgrade". So I got a double confusion with that, it was not as straight forward as I had to stop to think how to just upgrade skype  and not python2-wnck which does not compile right now.
But that's my opinion. I sincerely believe Yay is the best AUR helper ever.

**Comment by Jguer** [comment]
On the "Packages to not upgrade" I agree it is confusing if you're looking fast and changing the highlight on it would make it worse. Would "Packages to skip upgrade" help in understanding?

**Comment by jeroni** [comment]
Skipping sounds better, but...

What if you give both options? Something like packages to upgrade and skip at the same time? 1 2 ^3 6 with ^ understood as "skip this package".
