### ISSUE TITLE
^ syntax to exclude packages to upgrade might not be working as intended

### ISSUE THREAD

**Issue by Porkepix** [Jguer/yay#977]
#### Affected Version
`yay v9.2.1 - libalpm v11.0.3`

#### Steps to reproduce

1.  Run `yay -Syu`
2. It offers you to discard some packages to update, and also show a syntax using `^`. User would expect it to be an exclude, ie. every package excepted this one.
3. Type for example ^1, you would think about every package excepted the first.

Either it doesn't work correctly, either it's not designed to works that way?

The same way, I would expect to use this in ranges.

**Comment by Morganamilo** [comment]
>User would expect it to be an exclude, ie. every package excepted this one.

Exactly, you are asked what packages to no upgrade. ^1 would say "don't upgrade any packages apart from 1"

**Comment by Porkepix** [comment]
Okay well, maybe will I reopen this later on, or won't, no idea why but when I opened the issue it seemed this was not working as described here…
Tried again, and now it does. I'm kinda confused. Therefore, closing.

**Comment by Morganamilo** [comment]
It's kind of confusing but the operator just does what it's mean to and invert. For diffs and such it's a little more sensical seems as the original questions are positives.

**Comment by Porkepix** [comment]
> For diffs and such it's a little more sensical seems as the original questions are positives.

Don't get what you meant here; What I meant is that when I opened the issue, it looks like it was not giving the expected result, the one you described above, and when I tried after your reply it did. No idea why though…
