### ISSUE TITLE
no such host error with proxy with authentication

### ISSUE THREAD

**Issue by Noah-Kennedy** [Jguer/yay#979]
#### Affected Version

`Yay -V` output:
`yay v9.2.1 - libalpm v11.0.3`
#### Issue
I am using a corporate proxy with authentication. The authentication has a `\` in the username for designating the domain, so my http_proxy, HTTP_PROXY, https_proxy, etc. are all in the form `http://<domain>\<username>:<password>@proxy.<company>.com:<port>`. I keep getting a `proxyconnect tcp: dial tcp: lookup http: no such host` error whenever I attempt to update my AUR repos or download a package from the AUR.

Pacman works just fine, as well as curl and wget.

I have already seen #925.

I am using the latest version of Manjaro.

#### Steps to reproduce

1. `yay -S compton-kawase-blur` (or any other package)

#### Output

`Get https://aur.archlinux.org/rpc.php?arg%5B%5D=adapta-maia-theme&arg%5B%5D=gamin&arg%5B%5D=gnome-shell-extension-manjaro-update&arg%5B%5D=gnome-shell-extension-taskbar&type=info&v=5: proxyconnect tcp: dial tcp: lookup http: no such host`

**Comment by Jguer** [comment]
Have you been able to use this proxy in any other go program? I've been researching and I think this format is not supported but I'll keep digging.

Meanwhile I can try and offer you some workarounds:
- Try using yay compiled with `gcc-go`
- Use yay compiled with `gcc-go` and `proxychains` #951, proxychains should support that format

**Comment by Noah-Kennedy** [comment]
Sorry about the delay, was away for the holidays. I have not tried anything else that uses Go yet. I will try using gcc-go and proxychains and let you know where that goes.
