### ISSUE TITLE
fuse-zip: key "pkgver" can not occur after pkgname

### ISSUE THREAD

**Issue by pa-d-v** [Jguer/yay#981]
yay v9.2.1.r9.gf406866 - libalpm v11.0.3

$ yay -S fuse-zip
failed to parse fuse-zip: Line 4: key "pkgver" can not occur after pkgname: pkgver = 0.6.0
while the PKGBUILD https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fuse-zip installs fine with yaourt

#### Output
:: Checking for conflicts...
:: Checking for inner conflicts...
[Repo: 1]  libzip-1.5.2-1
[Aur: 1]  fuse-zip-0.6.0-1

  1 fuse-zip                         (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: Downloaded PKGBUILD (1/1): fuse-zip
  1 fuse-zip                         (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: Parsing SRCINFO (1/1): fuse-zip
failed to parse fuse-zip: Line 4: key "pkgver" can not occur after pkgname: pkgver = 0.6.0

$yay -Pg
{
        "aururl": "https://aur.archlinux.org",
        "buildDir": "/home/pascal/.cache/yay",
        "editor": "",
        "editorflags": "",
        "makepkgbin": "makepkg",
        "makepkgconf": "",
        "pacmanbin": "pacman",
        "pacmanconf": "/etc/pacman.conf",
        "tarbin": "bsdtar",
        "redownload": "no",
        "rebuild": "no",
        "batchinstall": false,
        "answerclean": "",
        "answerdiff": "",
        "answeredit": "",
        "answerupgrade": "",
        "gitbin": "git",
        "gpgbin": "gpg",
        "gpgflags": "",
        "mflags": "",
        "sortby": "votes",
        "gitflags": "",
        "removemake": "ask",
        "requestsplitn": 150,
        "sortmode": 0,
        "completionrefreshtime": 7,
        "sudoloop": false,
        "timeupdate": false,
        "devel": false,
        "cleanAfter": false,
        "gitclone": true,
        "provides": true,
        "pgpfetch": true,
        "upgrademenu": true,
        "cleanmenu": true,
        "diffmenu": true,
        "editmenu": false,
        "combinedupgrade": false,
        "useask": false
}

**Comment by Morganamilo** [comment]
The error is pretty much exactly what it says.

For some reason the maintainer decided they didn't like makepkg's generated order and decided to make their own...

https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=fuse-zip

**Comment by pa-d-v** [comment]
Morganamilo,
Thanks for pointing that out.
Reported to https://aur.archlinux.org/packages/fuse-zip/#comment-699554
Closing this issue.
