### ISSUE TITLE
strange search

### ISSUE THREAD

**Issue by grayich** [Jguer/yay#982]
> yay v9.2.1 - libalpm v11.0.3
> yay v9.2.1.r9.gf406866 - libalpm v11.0.3

` yay -Ss ace stream`
finds - aur/acestream*

`yay -Ss ACE Stream`
does not find - aur/acestream*

`yay -Ss 'ACE Stream'`
finds by description - aur/acestream*

**Comment by Jguer** [comment]
https://github.com/Jguer/yay/blob/f406866a458d1dd5ed737b9671377002e1c46d5d/query.go#L104

Also leaving this here as the relevant bit of code
