### ISSUE TITLE
Missing post install hooks in contrast with yaourt

### ISSUE THREAD

**Issue by Silur** [Jguer/yay#984]
#### System info
Linux  5.1.16-arch1-1-ARCH #1 SMP PREEMPT Wed Jul 3 20:23:07 UTC 2019 x86_64 GNU/Linux

yay v9.2.0 - libalpm v11.0.3

#### Issue
Updating the linux kernel from yay does not run some necessary post-install hooks necessary for LUKS encrypted drives, causing grub fail irrecoverably:
`ERROR: Failed to open encryption mapping: The device <UUID> is not a LUKS volume and the crypto= parameter was not specified.`

#### Steps to reproduce
- yay -S linux with a LUKS encrypted /home partition
- try to boot

#### Fix
- yaourt -S linux from a liveCD + chroot into old

**Comment by Jguer** [comment]
Hooks are not handled by yay, they are handled by pacman. 
I have a luks encrypted `/home` partition and don't face this issue, meaning I'll need more than this to make sure it wasn't just a fluke or pacman was killed for other reasons

**Comment by Jguer** [comment]
Died of old age
