### ISSUE TITLE
[Feature Request] Throttle build from source to # of the CPU

### ISSUE THREAD

**Issue by shaygover** [Jguer/yay#990]
Hi,

When a big package is built from source, the CPU goes to 100% and the PC is slowed down.
It's OK when the build process lasts less then 5 min. 
I propose 2 new config vars:
1. throttling_timer: After this much time has pass the throttling will start. 0 means always. -1 to disable
2. throttling_percent: Max CPU percent the process will take. Between 1% and 99%. 1% might sound dumb but it's the user choice. 

Thanks

**Comment by Jguer** [comment]
This wouldn't be an issue for yay to solve, but for makepkg which does all the building, I would consider first checking the `MAKEFLAGS` in `/etc/makepkg.conf`, see if you're compiling using all cores `-j$(nproc)` for example which will hog all of your cores. 

I've also seen suggested to turn off package compression changing `PKGEXT` to `PKGEXT='.pkg.tar'` to reduce CPU consumption. 

The `yay` process itself is not that CPU demanding so implementing throttling won't help it

**Comment by shaygover** [comment]
But that would mean I'll have to educate each package maintainer. Since yay calls makepkg, can it just throttle it? 

> I've also seen suggested to turn off package compression changing PKGEXT to PKGEXT='.pkg.tar' to reduce CPU consumption.

Where do I do that?

**Comment by parkerlreed** [comment]
It's not up to educating the package maintainer... It's up to you to edit your makepkg.conf for your needs.

**Comment by shaygover** [comment]
Just in case anyone else need this: Just enable MAKEFLAGS="-j3" in your makepkg.conf. So:

> #-- Make Flags: change this for DistCC/SMP systems
> MAKEFLAGS="-j3"

I used 3 for the 3 threads I'm can survive without.
