### ISSUE TITLE
[FR] Extend -U to search in yay cache

### ISSUE THREAD

**Issue by Ashark** [Jguer/yay#991]
#### Affected Version
yay v9.2.1 - libalpm v11.0.3
#### Feature request
I am making many experiments and I constantly need to install or uninstall the same aur packages. When installing, I want to use already built packages from yay cache. And it is inconvenient to always type path to cached packages, especially if I want install several packages at a time:

    yay -U ~/.cache/yay/some_package/some_package.pkg.tar.gz ~/.cache/yay/another_package/another_package.pkg.tar.gz

I think it would be nice if yay extends a -U operation with for example a ```-Uc``` so you could use:

    yay -Uc some_package another_package

**Comment by Jguer** [comment]
I like it actually, will experiment on it

**Comment by Morganamilo** [comment]
>  I want to use already built packages from yay cache

-S already does this.

**Comment by Ashark** [comment]
-S suggests to redownload sources and rebuild.

**Comment by Jguer** [comment]
> > I want to use already built packages from yay cache
> 
> -S already does this.

True, if the cache is not invalidated by a new version. But I find the idea of having a predefined search location for packages compelling.

Maybe like this:
```
$ yay -U <TAB>
-> autocomplete shows all *.pkg.* packages in 
~/.cache/yay/ and $(pwd)
```

For me it's more of an auto complete enhancement then cramming stuff into yay. RFC

**Comment by Ashark** [comment]
Yeah, I also thought about that.
But we need search not in ~/.cache/yay/, but recursively downside from there. And probably not exactly ~/.cache/yay/, but cache dir defined in config.
And also, how to differentiate between some_package.pkg.tar.gz in cwd and in cache dir?

**Comment by Ashark** [comment]
>And also, how to differentiate between some_package.pkg.tar.gz in cwd and in cache dir?

That is another reason to extend -U rather than just auto complete.
Anyway, auto completion will still clutter a command line with full paths. Using -Uc will also allow omitting full file name, i.e. _some_package-1.0-1-x86_64.pkg.tar.gz_ becomes just _some_package_. So it will behave like -S for pacman with cached package.

In this case it is still required some change on the yay side. It should convert that "human" form (Uc) to "machine" form (-U with full paths and full filenames).

**Comment by Ashark** [comment]
I have created a draft for yay -Uc itself, can you please take a look: https://gist.github.com/Ashark/e0e031545f5b397bfbb047d14ce352c9
Then it needs to be integrated into /usr/share/bash-completion/yay

**Comment by Ashark** [comment]
Now it's needed to handle cache dir some way. If defined `XDG_CACHE_HOME`, then cachedir should be `$XDG_CACHE_HOME/yay/`, otherwise `$HOME/.cache/yay/`.
Also, there is a --cachedir parameter. How it should be treated? Should its path be added to default cache path or replaced? Manual says there may be multiple --cachedir parameters.
Maybe there is some runtime variable that contains a cache dir(s) path?
