### ISSUE TITLE
Edit Menu should be shown by default

### ISSUE THREAD

**Issue by godofgrunts** [Jguer/yay#992]
#### Feature Request

Make `editmenu` shown by default. I often have to make changes to pkgbuilds because people don't keep hashes up to date in AUR packages. Other AUR helpers do this by default and you're already showing the `diffmenu` so I don't think it would be bad to show edit as well.

**Comment by Jguer** [comment]
You can set it as default with for example `yay --editmenu --nodiffmenu --save`, there's an issue where it was decided to keep diffmenu as the default but I can't seem to find it

**Comment by godofgrunts** [comment]
Oh I didn't realize I could save those sort of settings. I guess this is a decent enough work around, but seems backwards to me to it that way.
