### ISSUE TITLE
[Feature Request] Diff against last reviewed/used PKGBUILD, rather than last downloaded one

### ISSUE THREAD

**Issue by Nephyrin** [Jguer/yay#994]
#### Affected Version

yay v9.2.1.r9.gf406866 - libalpm v11.0.3

#### Issue

When installing an AUR package, yay will offer to show you the diff of what was obtained.  If you bail out at *any point* after the download, however, it will still cache the downloaded package script.  This means that if I see something shady or (more often) incorrect in a PKGBUILD, I now have to go manually nuke it from `~/.cache/yay` to ensure it won't show up as something I've already reviewed.  Similarly, if I aborted the install for some reason without reviewing the diff, it will still appear as 'no changes'.

This makes the diff-review very non-useful as a security feature for me -- I have to assume any package that is not already installed I have never reviewed, because I have no way to discern why the previously cached files are there, or if I ever looked at them.

#### Steps to reproduce

1.  `yay -S <any aur package>`
2.  Control-C or select 'N' at any point after the download step, even before answering "Diffs to show"
3.  Repeat, and ask to see diffs - you will see 'no changes'.

#### Suggested fix/feature request

Either by default, or as an option, the diff step should should the difference between the last version I approved (by selecting "Proceed with build") and the present one, rather than against whatever was cached.

**Comment by AladW** [comment]
You could do the same @rafasc did here: https://github.com/AladW/aurutils/commit/6ffd3958c3bf853904d88e1296080ed9a2ecdbd7

**Comment by Jguer** [comment]
Closed with #1049
